### ISSUE TITLE
When Debian shutdown, FreePBX hangs | Changing IP address from DHCP to fixed, the Sangoma ID lost

### ISSUE THREAD

**Issue by goedkoper** [FreePBX/issue-tracker#100]
### FreePBX Version

FreePBX 17

### Issue Description

I have installed a fresh version of **Debian 12.5.0** on a DELL OptiPlex 5050 machine (DHCP-client) and works fine.
After that I started the installation of "**FreePBX 17 Official Debian Install Beta**" script, and the works fine  too.
I opened the FreePBX-portal (registered with our "Testing ID"), and everything was working, until I rebooted Debian...
When the pc (Debian) was up and running, I was trying FreePBX again, but it was not function anymore. So I have restart the installation script again, and FreePBX was working with the same Sangoma ID. That was nice.

This system had an IP address given from a DHCP-server.
I wanted to change for a fixed IP address.
In FreePBX I changed the IP from DHCP to Fixed, and restarted FreePBX (reboot).

After the reboot, **I lost my Sangoma ID** !!!
And I **lost my networksettings too** (in Debian) !!!

Now I can not change any IP-addresses, I can not change important settings in FreePBX.

How can I solve this? (no backups ;-( )

Best regards, Gijsbert Kampert

### Operating Environment

Operating system: **Debian 12.5.0**
FreePBX: **17.0.15.14**

**Comment by kapilgupta01** [comment]
Hi @goedkoper We just pushed the fixes for below two imp issues in firewall/networking area so can you please try with below and let us know if issue still persists - 
https://github.com/FreePBX/issue-tracker/issues/99
https://github.com/FreePBX/issue-tracker/issues/94

**Comment by kapilgupta01** [comment]
Hi @goedkoper by chance did you got chance to try with the updated modules? thanks

**Comment by goedkoper** [comment]
I manually set in Debian the networksettings, by edit the /etc/network/interfaces , with a fixed IP-address.
When the computer was reconnected to the Internet, FreePBX does register at Sangoma and works fine again. :-)

**Comment by kapilgupta01** [comment]
Please refer to https://github.com/FreePBX/issue-tracker/issues/127 where if the system is NOT using networkd then Freepbx can  be used to configure the networks otherwise let user to manage the network configurations via networkd utility.

Thanks
