### ISSUE TITLE
[bug]: sangomaconnect fails to install 

### ISSUE THREAD

**Issue by dolesec** [FreePBX/issue-tracker#104]
### FreePBX Version

FreePBX 17

### Issue Description

after initial install sangomaconnect is present locally but will not  installed 

### Operating Environment

new 17 installation using Linode's standard Debian 12 cloud image with the only changes post install being **_apt-get update_** and **_apt-get upgrade_** 

framework         | 17.0.15.14 

Asterisk 21.0.2 

+-------------------+------------+-----------------------------------+-------------+-----------+
| Module            | Version    | Status                            | License     | Signature |
+-------------------+------------+-----------------------------------+-------------+-----------+
| amd               | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| announcement      | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| areminder         | 17.0.3.9   | Enabled                           | Commercial  | Sangoma   |
| arimanager        | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli      | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo      | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| backup            | 17.0.5.14  | Enabled                           | GPLv3+      | Sangoma   |
| blacklist         | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| broadcast         | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| builtin           |            | Enabled                           |             | Unsigned  |
| bulkhandler       | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| calendar          | 17.0.4.6   | Enabled                           | GPLv3+      | Sangoma   |
| callaccounting    | 17.0.5     | Enabled                           | Commercial+ | Sangoma   |
| callback          | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| callerid          | 17.0.1     | Enabled                           | Commercial  | Sangoma   |
| callforward       | 17.0.1.3   | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit         | 17.0.1.2   | Enabled                           | Commercial  | Sangoma   |
| callrecording     | 17.0.3.6   | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting       | 17.0.3.2   | Enabled                           | GPLv3+      | Sangoma   |
| cdr               | 17.0.4.13  | Enabled                           | GPLv3+      | Sangoma   |
| cel               | 17.0.2.7   | Enabled                           | GPLv3+      | Sangoma   |
| certman           | 17.0.3.9   | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| conferences       | 17.0.3.1   | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro    | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| configedit        | 17.0.1.1   | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager    | 17.0.5.7   | Enabled                           | GPLv3+      | Sangoma   |
| core              | 17.0.9.37  | Enabled                           | GPLv3+      | Sangoma   |
| cos               | 17.0.1.1   | Enabled                           | Commercial  | Sangoma   |
| customappsreg     | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| dashboard         | 17.0.4.2   | Enabled                           | AGPLv3+     | Sangoma   |
| daynight          | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| dictate           | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| directory         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| donotdisturb      | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| endpoint          | 17.0.1.55  | Enabled                           | Commercial  | Sangoma   |
| extensionroutes   | 17.0.1     | Enabled                           | Commercial  | Sangoma   |
| extensionsettings | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| fax               | 17.0.3.2   | Enabled                           | GPLv3+      | Sangoma   |
| faxpro            | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| featurecodeadmin  | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| filestore         | 17.0.2.11  | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow      | 17.0.4.6   | Enabled                           | GPLv3+      | Sangoma   |
| firewall          | 17.0.1.14  | Enabled                           | AGPLv3+     | Sangoma   |
| framework         | 17.0.15.14 | Enabled                           | GPLv2+      | Sangoma   |
| hotelwakeup       | 17.0.1.5   | Enabled                           | GPLv2       | Sangoma   |
| iaxsettings       | 17.0.1     | Enabled                           | AGPLv3      | Sangoma   |
| infoservices      | 17.0.1     | Enabled                           | GPLv2+      | Sangoma   |
| ivr               | 17.0.5     | Enabled                           | GPLv3+      | Sangoma   |
| languages         | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| logfiles          | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| manager           | 17.0.5     | Enabled                           | GPLv2+      | Sangoma   |
| miscapps          | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| miscdests         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| music             | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| paging            | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro         | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| parking           | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| parkpro           | 17.0.1.4   | Enabled                           | Commercial  | Sangoma   |
| pbxmfa            | 17.0.2     | Enabled                           | Commercial+ | Sangoma   |
| pinsets           | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro        | 17.0.2     | Enabled                           | Commercial  | Sangoma   |
| pm2               | 17.0.3.1   | Enabled                           | AGPLv3+     | Sangoma   |
| presencestate     | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| printextensions   | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| queueprio         | 17.0.1.4   | Enabled                           | GPLv3+      | Sangoma   |
| queues            | 17.0.1.7   | Enabled                           | GPLv2+      | Sangoma   |
| queuestats        | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| qxact_reports     | 17.0.2     | Enabled                           | Commercial  | Sangoma   |
| recording_report  | 17.0.3.8   | Enabled                           | Commercial  | Sangoma   |
| recordings        | 17.0.2.2   | Enabled                           | GPLv3+      | Sangoma   |
| restapps          | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| ringgroups        | 17.0.2.4   | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect    |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| sangomartapi      | 17.0.1.18  | Enabled                           | Commercial  | Sangoma   |
| setcid            | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings       | 17.0.6.3   | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation        | 17.0.3.3   | Enabled                           | Commercial  | Sangoma   |
| sms               | 17.0.1.10  | Enabled                           | Commercial  | Sangoma   |
| smsplus           | 17.0.3     | Enabled                           | Commercial  | Sangoma   |
| soundlang         | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| sysadmin          | 17.0.1.55  | Enabled                           | Commercial  | Sangoma   |
| timeconditions    | 17.0.1.14  | Enabled                           | GPLv3+      | Sangoma   |
| tts               | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines        | 17.0.1     | Enabled                           | AGPLv3      | Sangoma   |
| ucp               | 17.0.4.14  | Enabled                           | AGPLv3+     | Sangoma   |
| userman           | 17.0.6.19  | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast           | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| vmnotify          | 17.0.1.5   | Enabled                           | Commercial  | Sangoma   |
| voicemail         | 17.0.5.14  | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report  | 17.0.1.1   | Enabled                           | Commercial  | Sangoma   |
| vqplus            | 17.0.1.16  | Enabled                           | Commercial  | Sangoma   |
| weakpasswords     | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| webrtc            | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
+-------------------+------------+-----------------------------------+-------------+-----------+

### Relevant log output

```shell
# fwconsole ma --debug --verbose downloadinstall sangomaconnect

skipbreakingcheck Disabled
Force Disabled
Array
(
[0] => downloadinstall
[1] => sangomaconnect
)
No repos specified, using: [standard] from last GUI settings

Downloading module 'sangomaconnect'
Processing sangomaconnect
Verifying local module download...Verified
Extracting...Done
Download completed in 1 seconds
Updating tables sangomaconnect_user_pre_setup, sangomaconnect_user_setup, sangomaconnect_user_device, sangomaconnect_sngphone_sms_routing, sangomaconnect_phone_locations, sangomaconnect_account_phone_locations...Done
No PBXID file found, not registering module to cloud.
Checking module cloud activation status
System not activated, cannot perform cloud activation
Initializing node dependencies
Found npm-cache v0.7.0
Running installation..
[npm-cache] [INFO] using /home/asterisk/.package_cache as cache directory
[npm-cache] [INFO] [composer] Dependency config file /var/www/html/admin/modules/sangomaconnect/node/composer.json does not exist. Skipping install
[npm-cache] [INFO] [npm] config file exists
[npm-cache] [INFO] [npm] cli exists
[npm-cache] [INFO] [npm] hash of /var/www/html/admin/modules/sangomaconnect/node/package.json: a386f4a77785ce2c5562d106a52cef80
[npm-cache] [INFO] [npm] cache exists
[npm-cache] [INFO] [npm] clearing installed dependencies at /var/www/html/admin/modules/sangomaconnect/node/node_modules
[npm-cache] [INFO] [npm] ...cleared
[npm-cache] [INFO] [npm] retrieving dependencies from /home/asterisk/.package_cache/npm/9.2.0/a386f4a77785ce2c5562d106a52cef80.tar.gz
[npm-cache] [INFO] [bower] Dependency config file /var/www/html/admin/modules/sangomaconnect/node/bower.json does not exist. Skipping install
[npm-cache] [INFO] [npm] done extracting
[npm-cache] [INFO] successfully installed all dependencies

Finished updating libraries!
SangomaConnect Server is not running
SangomaConnect module installed but not activated. Please buy a license and activate the module

In Sangomaconnect.class.php line 1259:

[Whoops\Exception\ErrorException (2)]
chown(): No such file or directory

Exception trace:
at /var/www/html/admin/modules/sangomaconnect/Sangomaconnect.class.php:1259
Whoops\Run->handleError() at n/a:n/a
chown() at /var/www/html/admin/modules/sangomaconnect/Sangomaconnect.class.php:1259
FreePBX\modules\Sangomaconnect->install() at /var/www/html/admin/libraries/modulefunctions.class.php:2594
module_functions->_runscripts() at /var/www/html/admin/libraries/modulefunctions.class.php:2067
module_functions->install() at /var/www/html/admin/libraries/Console/Moduleadmin.class.php:446
FreePBX\Console\Command\Moduleadmin->doInstall() at /var/www/html/admin/libraries/Console/Moduleadmin.class.php:1584
FreePBX\Console\Command\Moduleadmin->handleArgs() at /var/www/html/admin/libraries/Console/Moduleadmin.class.php:236
FreePBX\Console\Command\Moduleadmin->execute() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php:312
Symfony\Component\Console\Command\Command->run() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:1022
Symfony\Component\Console\Application->doRunCommand() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:314
Symfony\Component\Console\Application->doRun() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:168
Symfony\Component\Console\Application->run() at /var/lib/asterisk/bin/fwconsole:163

moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [...]
```

**Comment by tony1661** [comment]
I also have this issue on a brand new Debian 12 VM. I had installed the Beta on a different VM about 1 month ago without any issues.

**Comment by kapilgupta01** [comment]
sangomaconnect v17.0.1.25

**Comment by tony1661** [comment]
> sangomaconnect v17.0.1.25

what does this mean?

**Comment by kapilgupta01** [comment]
sangomaconnect module version. 

Update your module and give a try. 

fwconsole ma downloadinstall sangomaconnect --tag=17.0.1.25

**Comment by tony1661** [comment]
That worked. Also omitting the tag works as well since it downloads the 17.0.1.25 version.

I had this issue when installing Beta from the script. The script fails at the following section: `fwconsole ma install sangomaconnect>> $log 2>&1`

Should that be changed to, run the `fwconsole ma downloadinstall sangomaconnect` if the above command fails?

**Comment by kapilgupta01** [comment]
_fwconsole ma install sangomaconnect _   -> ideally this should work as the latest module is present in the system. I will ensure that latest module is getting installed.

**Comment by tony1661** [comment]
It did not work a few days ago when I reported this issue. Has something been changed?

**Comment by kapilgupta01** [comment]
yes issue got fixed in the latest release @tony1661
