### ISSUE TITLE
[bug]: 'FreePBX\modules\Sccp_Manager\sccpManTraits\helperFunctions' not found

### ISSUE THREAD

**Issue by Jezzzero** [FreePBX/issue-tracker#106]
### FreePBX Version

FreePBX 16

### Issue Description

version when I ran from the CLI  cat version.php: 15.0.16.81

### Operating Environment

Oracle Virtualbox 7.0, Asterisk patch from USECALLMANAGER.NZ,
 accountcodepreserve | 16.0.0.1   | Enabled                           | GPLv2       | Sangoma   |
| adv_recovery        | 16.0.43.8  | Enabled                           | Commercial  | Sangoma   |
| allowlist           | 16.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| amd                 | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| announcement        | 16.0.7     | Enabled                           | GPLv3+      | Sangoma   |
| api                 | 16.0.13    | Enabled                           | AGPLv3+     | Sangoma   |
| areminder           | 16.0.16    | Enabled                           | Commercial  | Sangoma   |
| arimanager          | 16.0.13    | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli        | 16.0.8     | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo        | 16.0.10    | Enabled                           | GPLv3+      | Sangoma   |
| backup              | 16.0.69    | Enabled                           | GPLv3+      | Sangoma   |
| blacklist           | 16.0.21    | Enabled                           | GPLv3+      | Sangoma   |
| broadcast           | 16.0.18    | Enabled                           | Commercial  | Sangoma   |
| builtin             |            | Enabled                           |             | Unsigned  |
| bulkhandler         | 16.0.16    | Enabled                           | GPLv3+      | Sangoma   |
| calendar            | 16.0.21    | Enabled                           | GPLv3+      | Sangoma   |
| callaccounting      | 16.0.12    | Enabled                           | Commercial+ | Sangoma   |
| callback            | 16.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| callerid            | 16.0.5     | Enabled                           | Commercial  | Sangoma   |
| callforward         | 16.0.5     | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit           | 16.0.6     | Enabled                           | Commercial  | Sangoma   |
| callrecording       | 16.0.21    | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting         | 16.0.5     | Enabled                           | GPLv3+      | Sangoma   |
| cdr                 | 16.0.46.8  | Enabled                           | GPLv3+      | Sangoma   |
| cel                 | 16.0.20    | Enabled                           | GPLv3+      | Sangoma   |
| certman             | 16.0.22    | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup           | 16.0.16    | Enabled                           | GPLv3+      | Sangoma   |
| conferences         | 16.0.9     | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro      | 16.0.9     | Enabled                           | Commercial  | Sangoma   |
| configedit          | 16.0.5     | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager      | 16.0.26    | Enabled                           | GPLv3+      | Sangoma   |
| core                | 16.0.68.20 | Enabled                           | GPLv3+      | Sangoma   |
| cos                 | 16.0.7     | Enabled                           | Commercial  | Sangoma   |
| customappsreg       | 16.0.5     | Enabled                           | GPLv3+      | Sangoma   |
| cxpanel             | 16.0.6     | Enabled                           | GPLv3       | Sangoma   |
| dahdiconfig         | 16.0.9     | Enabled                           | GPLv3+      | Sangoma   |
| dashboard           | 16.0.21    | Enabled                           | AGPLv3+     | Sangoma   |
| daynight            | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| dictate             | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| directory           | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| disa                | 16.0.4     | Enabled                           | AGPLv3+     | Sangoma   |
| donotdisturb        | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| dynroute            | 16.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| endpoint            | 16.0.86.15 | Enabled                           | Commercial  | Sangoma   |
| extensionroutes     | 16.0.8     | Enabled                           | Commercial  | Sangoma   |
| extensionsettings   | 16.0.5     | Enabled                           | GPLv3+      | Sangoma   |
| fax                 | 16.0.13    | Enabled                           | GPLv3+      | Sangoma   |
| faxpro              | 16.0.11    | Enabled                           | Commercial  | Sangoma   |
| featurecodeadmin    | 16.0.11    | Enabled                           | GPLv3+      | Sangoma   |
| filestore           | 16.0.18    | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow        | 16.0.23    | Enabled                           | GPLv3+      | Sangoma   |
| firewall            | 16.0.57.6  | Enabled                           | AGPLv3+     | Sangoma   |
| framework           | 16.0.40.7  | Enabled                           | GPLv2+      | Sangoma   |
| fw_langpacks        | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| hotelwakeup         | 16.0.9     | Enabled                           | GPLv2       | Sangoma   |
| iaxsettings         | 16.0.4     | Enabled                           | AGPLv3      | Sangoma   |
| infoservices        | 16.0.2     | Enabled                           | GPLv2+      | Sangoma   |
| iotserver           | 16.0.9.3   | Enabled                           | Commercial  | Sangoma   |
| irc                 | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| ivr                 | 16.0.9     | Enabled                           | GPLv3+      | Sangoma   |
| languages           | 16.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| logfiles            | 16.0.7     | Enabled                           | GPLv3+      | Sangoma   |
| manager             | 16.0.23    | Enabled                           | GPLv2+      | Sangoma   |
| miscapps            | 16.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| miscdests           | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| missedcall          | 16.0.10    | Enabled                           | GPLv3+      | Sangoma   |
| music               | 16.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| outroutemsg         | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| paging              | 16.0.13    | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro           | 16.0.10    | Enabled                           | Commercial  | Sangoma   |
| parking             | 16.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| parkpro             | 16.0.5     | Enabled                           | Commercial  | Sangoma   |
| pbxmfa              | 16.0.14    | Enabled                           | Commercial+ | Sangoma   |
| phonebook           | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| phpinfo             | 16.0.1     | Enabled                           | GPLv2+      | Sangoma   |
| pinsets             | 16.0.8     | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro          | 16.0.4     | Enabled                           | Commercial  | Sangoma   |
| pm2                 | 16.0.8     | Enabled                           | AGPLv3+     | Sangoma   |
| pms                 | 16.0.23    | Enabled                           | Commercial  | Sangoma   |
| presencestate       | 16.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| printextensions     | 16.0.8     | Enabled                           | GPLv3+      | Sangoma   |
| queueprio           | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| queues              | 16.0.27    | Enabled                           | GPLv2+      | Sangoma   |
| queuestats          | 16.0.28    | Enabled                           | Commercial  | Sangoma   |
| qxact_reports       | 16.0.33    | Enabled                           | Commercial  | Sangoma   |
| recording_report    | 16.0.33    | Enabled                           | Commercial  | Sangoma   |
| recordings          | 16.0.16    | Enabled                           | GPLv3+      | Sangoma   |
| restapps            | 16.0.36.8  | Enabled                           | Commercial  | Sangoma   |
| ringgroups          | 16.0.11    | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect      | 16.0.47.8  | Enabled                           | Commercial  | Sangoma   |
| sangomacrm          | 16.0.10.19 | Enabled                           | Commercial  | Sangoma   |
| sangomartapi        | 16.0.49.12 | Enabled                           | Commercial  | Sangoma   |
| sccp-man            |            | Not Installed (Locally available) | GPL         | Unsigned  |
| setcid              | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings         | 16.0.27    | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation          | 16.0.27    | Enabled                           | Commercial  | Sangoma   |
| sms                 | 16.0.25    | Enabled                           | Commercial  | Sangoma   |
| smsplus             | 16.0.2     | Enabled                           | Commercial  | Sangoma   |
| soundlang           | 16.0.9     | Enabled                           | GPLv3+      | Sangoma   |
| superfecta          | 16.0.29    | Enabled                           | GPLv2+      | Sangoma   |
| sysadmin            | 16.0.41.22 | Enabled                           | Commercial  | Sangoma   |
| timeconditions      | 16.0.11    | Enabled                           | GPLv3+      | Sangoma   |
| tts                 | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines          | 16.0.3     | Enabled                           | AGPLv3      | Sangoma   |
| ucp                 | 16.0.38.1  | Enabled                           | AGPLv3+     | Sangoma   |
| userman             | 16.0.44.6  | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast             | 16.0.11    | Enabled                           | GPLv3+      | Sangoma   |
| vmnotify            | 16.0.10    | Enabled                           | Commercial  | Sangoma   |
| voicemail           | 16.0.53    | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report    | 16.0.3     | Enabled                           | Commercial  | Sangoma   |
| voipinnovations     | 16.0.29    | Enabled                           | Commercial  | Sangoma   |
| vqplus              | 16.0.21    | Enabled                           | Commercial  | Sangoma   |
| weakpasswords       | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| webcallback         | 16.0.3     | Enabled                           | Commercial  | Sangoma   |
| webrtc              | 16.0.18    | Enabled                           | GPLv3+      | Sangoma   |
| xmpp                | 16.0.7     | Enabled                           | AGPLv3      | Sangoma   |
| zulu                | 16.0.19    | Enabled                           | Commercial  | Sangoma   |

### Relevant log output

```shell
$autoincrement = (($amp_conf["AMPDBENGINE"] == "sqlite") || ($amp_conf["AMPDBENGINE"] == "sqlite3")) ? "AUTOINCREMENT" : "AUTO_INCREMENT";
$table_req = array('sccpdevice', 'sccpline', 'sccpsettings');
$sccp_compatible = 0;
$db_config = '';
$sccp_version = array();
$cnf_int = \FreePBX::Config();
 
// Do not create Sccp_Manager object as not required.
// Only include required classes and create anonymous class for thisInstaller
 
$thisInstaller = new class{
    use \FreePBX\modules\Sccp_Manager\sccpManTraits\helperFunctions;
};
 
$requiredClasses = array('aminterface', 'extconfigs');
foreach ($requiredClasses as $className) {
    $class = "\\FreePBX\\Modules\\Sccp_manager\\$className";
    if (!class_exists($class, false)) {
        include(__DIR__ . "/sccpManClasses/$className.class.php");
    }
    if (class_exists($class, false)) {
        ${$className} = new $class();
    }
}
 
CheckAsteriskVersion();
$sccp_compatible = $aminterface->getSCCPVersion()['vCode'];
 
outn("<li>" . _("Sccp model Compatible code : ") . $sccp_compatible . "</li>");
if ($sccp_compatible == 0) {
    outn("<br>");
Arguments
"Trait 'FreePBX\modules\Sccp_Manager\sccpManTraits\helperFunctions' not found"
```

**Comment by Jezzzero** [comment]
Its actually FreePBX 16.0.40.7 when viewing from Dashboard.

**Comment by jcolp** [comment]
This module is not part of FreePBX and is not distributed by it. It is a third party module, and you would need to seek assistance elsewhere with it.

**Comment by lgaetz** [comment]
Contributed modules live in https://github.com/FreePBX-ContributedModules
