### ISSUE TITLE
[bug]: FreePBX 17, updating php in debian system removes the ioncube library

### ISSUE THREAD

**Issue by vsc55** [FreePBX/issue-tracker#107]
### FreePBX Version

FreePBX 17

### Issue Description

If you are using debian as the base system and there is a system update in which php is updated and we use the package configuration, when you restart the php service you will get an error since the ioncube_loader_lin_8.2.so module is no longer loaded.

**Error showing apache:**
Script error: the [ionCube](https://www.ioncube.com/) Loader for PHP needs to be installed. The ionCube Loader is the industry standard PHP extension for running protected PHP code, and can usually be added easily to a PHP installation. For Loaders please visit [get-loader.ioncube.com](https://get-loader.ioncube.com/) and for an instructional video please see http://ioncu.be/LV

**Fix:**
To solve it, you have to manually add the following line to the end in "/etc/php/8.2/apache2/php.ini" and "/etc/php/8.2/cli/php.ini", afeter  then restart Apache.
`zend_extension=/usr/lib64/php/20220829/ioncube_loader_lin_8.2.so`
NOTE: The path of the "ioncube_loader_lin_8.2.so" file can be changed depending on the installed version of ioncube.

It would be nice to be able to automate this somehow.

### Operating Environment

Linux: Debian 12

**Comment by vsc55** [comment]
You could create a file in conf.d to prevent the system from overwriting the configuration, what do you think?
```
/etc/php/8.2/apache2/conf.d/00-ioncube-loader.ini
/etc/php/8.2/cli/conf.d/00-ioncube-loader.ini
```

**Comment by ramarajan222** [comment]
Hi @vsc55 ,

We have fixed this for the new system. Added config file as you suggested.

`
 cat /etc/php/8.2/apache2/conf.d/00-ioncube.ini
zend_extension=/usr/lib64/php/20220829/ioncube_loader_lin_8.2.so


 cat /etc/php/8.2/cli/conf.d/00-ioncube.ini
zend_extension=/usr/lib64/php/20220829/ioncube_loader_lin_8.2.so
`

**Comment by dolesec** [comment]
could this have introduced the following which I see on all fwconsole commands after updating this morning ?

_root@fpbx17:~# fwconsole ma list_ 
**_Cannot load the ionCube PHP Loader - it was already loaded_**
...

**Comment by ramarajan222** [comment]
Hi @dolesec ,

Please remove or comment on the below line from /etc/php/8.2/apache2/php.ini and /etc/php/8.2/cli/php.ini files and give it a try. thanks
`
zend_extension=/usr/lib64/php/20220829/ioncube_loader_lin_8.2.so
`

**Comment by dolesec** [comment]
that seems to have resolved it , ty @ramarajan222

**Comment by danardf** [comment]
@kguptasangoma Oh. Let me try it. I never see this issue. I tried to find it on Framework.

**Comment by danardf** [comment]
However, It should be removed automatically through updates or something like that.

**Comment by kapilgupta01** [comment]
you might have old script installed 17 where ioncube was loaded twice , now we are not seeing that issue

**Comment by danardf** [comment]
Looks good now.
Sorry @kguptasangoma
