### ISSUE TITLE
[bug]: Impossible to install/upgrade FreePBX over Tor

### ISSUE THREAD

**Issue by plkonbklo** [FreePBX/issue-tracker#109]
### FreePBX Version

FreePBX 17

### Issue Description

I'm trying to install FreePBX 17 in Debian 12 VM using this script:
https://github.com/FreePBX/sng_freepbx_debian_install
VM is connected to the internet over Tor.
The install is failing at this step:

```
2024-04-21 20:35:06 - Installing FreePBX 17
2024-04-21 20:35:06 - Installing Sysadmin module
2024-04-21 20:35:16 - Installing sangomaconnectmodule
2024-04-21 20:35:25 - Installing install local module
2024-04-21 20:35:26 - Upgrading FreePBX 17 modules
2024-04-21 20:35:28 - Installation failed at step Upgrading FreePBX 17 modules. Please check log /var/log/pbx/freepbx17-install-2024.04.21-20.31.43.log for details.
2024-04-21 20:35:28 - Error at line line: 613 exiting with code 1 (last command was: fwconsole ma upgradeall >> $log 2>&1)
2024-04-21 20:35:28 - Exiting script
```

Trying to run the upgrade manually I'm getting this log:

```
$ sudo fwconsole ma upgradeall
No repos specified, using: [standard] from last GUI settings


In modulefunctions.class.php line 152:
                                                                          
  Unable to Parse XML response from Mirror. See the log for more details  
                                                                          

moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [<args>...]

```

By modifying the `/var/www/html/admin/libraries/modulefunctions.class.php` and checking what's being downloaded I've found out that while trying to download the `https://mirror.freepbx.org/all-17.0.xml` it's being blocked by DDoS protection or something and it's downloading Captcha page instead of xml file.
The same Captcha page is downloaded if I download the xml file using curl over Tor:
```
curl https://mirror.freepbx.org/all-17.0.xml
```
But if I download the xml file using Firefox over Tor then I'm not getting a Captcha and I can access the xml file.

Is it possible to modify the DDoS protection settings on https://mirror.freepbx.org to allow downloading over Tor?
Or maybe modify the source code to use User Agent and headers for HTTP request in the same way as Firefox so it won't be blocked by protection?

### Operating Environment

Debian 12, FreePBX Framework 17.0

**Comment by kguptasangoma** [comment]
Hi @plkonbklo  If I am running "curl https://mirror.freepbx.org/all-17.0.xml" , I am seeing proper response.

Not sure why you are getting captcha page.

**Comment by kapilgupta01** [comment]
As of now we do not have plan to change the DDoS settings for mirror. Thanks
