### ISSUE TITLE
[bug]: Lost Password link links to PreePBX github page

### ISSUE THREAD

**Issue by jms72** [FreePBX/issue-tracker#110]
### FreePBX Version

FreePBX 16

### Issue Description

Clicking "Lost password" on https://community.freepbx.org/auth/crowd?signup=true redirects me to https://github.com/freepbx/issue-tracker which seems not the right destination.

### Operating Environment

N/A not an issue in PreePBX software, an issue in community.freepbx.org website.

**Comment by lgaetz** [comment]
You need to move your account away from crowd single sign on, and setup a local forum user account. Have you done that?
https://community.freepbx.org/t/forum-login-changes/92868

**Comment by jms72** [comment]
It's not so much about recovering my specific account, it's that the "Lost password" links to something that seems unexpected or wrong.

**Comment by lgaetz** [comment]
Hi @jms72 

We are phasing out that login method for the FreePBX forum, so it won't be an issue much longer. 
https://community.freepbx.org/t/forum-login-change-final/96135
