### ISSUE TITLE
[bug]: CDR Pro Trial license not loading

### ISSUE THREAD

**Issue by tony1661** [FreePBX/issue-tracker#112]
### FreePBX Version

FreePBX 17

### Issue Description

I have tried adding the _FreePBX Free Trial Bundle - 1 Month Trial_ as well as the _FreePBX CM CDR Pro Module 1 Month Trial_ to my FreePBX 17 Beta server.

All other trial licenses work however I am unable to get CDR Pro by using the bundle trial or the cdr pro trial.

![image](https://github.com/FreePBX/issue-tracker/assets/5287266/7970b945-4e48-4486-b18e-6d814b25c01a)

### Operating Environment

FreePBX 17 Beta
Debian 12
Proxmox 8

**Comment by kapilgupta01** [comment]
hi @tony1661 CDRPro module might not be installed on your system.
please execute below to install the cdrpro.

_fwconsole ma downloadinstall cdrpro --tag=17.0.3.1_ 

however , please note that we have not yet started testing this module so if you see any issue please report and uninstall this module to continue with your other work with the FreePBX

thank you for using FreePBX 17
Kapil Gupta

**Comment by tony1661** [comment]
I am getting the following error when doing that:

![image](https://github.com/FreePBX/issue-tracker/assets/5287266/c390dbf7-bdbf-4928-8fe6-6553fc64299f)

**Comment by dolesec** [comment]
I see the same

**Comment by kapilgupta01** [comment]
please try -

_fwconsole ma downloadinstall cdrpro --tag=17.0.3.2_

**Comment by dolesec** [comment]
that worked , thank you sir ! 

**_Module cdrpro version 17.0.3.2 successfully installed_**

**Comment by kapilgupta01** [comment]
Hi  @dolesec Good Morning and thank you for the prompt validation

**Comment by dolesec** [comment]
@kguptasangoma after install however and upon fwconsole restart its erroring with the following message ...

```
Running Asterisk post from Cdrpro module
Starting CDRpro Service ...
Starting CDRpro event listener
Error: Class "FreePBX\modules\ProgressBar" not found in file /var/www/html/admin/modules/cdrpro/Cdrpro.class.php on line 258
Stack trace:
  1. Error->() /var/www/html/admin/modules/cdrpro/Cdrpro.class.php:258
  2. FreePBX\modules\Cdrpro->startdaemon() /var/www/html/admin/modules/cdrpro/Cdrpro.class.php:365
  3. FreePBX\modules\Cdrpro->startFreepbx() /var/www/html/admin/libraries/Console/Start.class.php:148
  4. FreePBX\Console\Command\Start->execute() /var/www/html/admin/libraries/Console/Restart.class.php:34
  5. FreePBX\Console\Command\Restart->execute() /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php:312
  6. Symfony\Component\Console\Command\Command->run() /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:1022
  7. Symfony\Component\Console\Application->doRunCommand() /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:314
  8. Symfony\Component\Console\Application->doRun() /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:168
  9. Symfony\Component\Console\Application->run() /var/lib/asterisk/bin/fwconsole:163
```

**Comment by kapilgupta01** [comment]
please try -

fwconsole ma downloadinstall cdrpro --tag=17.0.3.3

**Comment by tony1661** [comment]
That worked. The issue also happens for Advanced Recovery. The module does not get installed from the Trial on v17 Beta

**Comment by tony1661** [comment]
Does it take some time for the module to populate data? It seems that is not showing calls after they have been completed.

<details>

<summary>CDR Pro</summary>

![image](https://github.com/FreePBX/issue-tracker/assets/5287266/065ebbda-4673-404a-81d2-e2ef67aedae2)

</details>

<details>

<summary>CDR</summary>

![image](https://github.com/FreePBX/issue-tracker/assets/5287266/3a419d23-cc10-4b5e-bb1e-93ce88ea4786)

</details>

**Comment by dolesec** [comment]
@tony1661 it can 

take a look at **_fwconsole cdrpro_** from the CLI 

```
root@fpbx17:~# fwconsole cdrpro
Description:
  CDRpro  Reports

Usage:
  cdrpro [options]

Options:
      --sync            Syncronize data from cdr 
      --force           Force update, Sync already synced data.
      --date=DATE       To synchronize with a specific date,use the format Year-Month-Day (e.g., 0000-00-00).
                        If pass date format as Year-Month, it will consider the entire month's days
                        If pass date format as Year-Month-Day, it will only consider the exact same date
                        
  -h, --help            Display help for the given command. When no command is given display help for the list command
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

try forcing a sync with **_fwconsole cdrpro --sync --force --verbose_**

**Comment by tony1661** [comment]
@dolesec that worked! sorta 😅 

I have data populated however I get the following issue:
<details>

<summary># fwconsole cdrpro --sync --force --verbose</summary>

To process the calls, In CDR We must have linkedID column. If linkedid is empty, System  will skip those Cdrs 
Creating Temp Table
Done Temp Table creation
Processing Cdr for the month 2024-04-01
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-02
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-03
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-04
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-05
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-06
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-07
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-08
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-09
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-10
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-11
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-12
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-13
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-14
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-15
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-16
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-17
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-18
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-19
Processing Cdr for the month DONE
Processing linkedid : 1713536222.0
Processing linkedid : 1713536357.5
Processing Cdr for the month 2024-04-20
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-21
Processing Cdr for the month DONE
Processing Cdr for the month 2024-04-22
Processing Cdr for the month DONE
Processing linkedid : 1713788621.11

In Cdrpro.class.php line 2593:
                                         
  [Whoops\Exception\ErrorException (2)]  
  Undefined array key "Conferences"
                                         

Exception trace:
  at /var/www/html/admin/modules/cdrpro/Cdrpro.class.php:2593
 Whoops\Run->handleError() at /var/www/html/admin/modules/cdrpro/Cdrpro.class.php:2593
 FreePBX\modules\Cdrpro->findTheOutDialType() at /var/www/html/admin/modules/cdrpro/Cdrpro.class.php:2651
 FreePBX\modules\Cdrpro->processOutgoing() at /var/www/html/admin/modules/cdrpro/Cdrpro.class.php:2017
 FreePBX\modules\Cdrpro->processCDRentry() at /var/www/html/admin/modules/cdrpro/Console/Cdrpro.class.php:140
 FreePBX\Console\Command\Cdrpro->syncronize() at /var/www/html/admin/modules/cdrpro/Console/Cdrpro.class.php:42
 FreePBX\Console\Command\Cdrpro->execute() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php:312
 Symfony\Component\Console\Command\Command->run() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:1022
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:314
 Symfony\Component\Console\Application->doRun() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:168
 Symfony\Component\Console\Application->run() at /var/lib/asterisk/bin/fwconsole:163

cdrpro [--sync] [--force] [--date DATE]

</details>

![image](https://github.com/FreePBX/issue-tracker/assets/5287266/dd40341a-bc4e-4ab1-bc0a-637abafa33be)

**Comment by dolesec** [comment]
FreePBX dev team will need to look at that one , glad you made some progress though

**Comment by dolesec** [comment]
@tony1661 do you see an error when loading the user control panel as well related to CDRpro ?

I noticed when trying to load UCP I now see this error:

```
Whoops \ Exception \ ErrorException (E_WARNING)
Trying to access array offset on value of type bool
```

![Screenshot 2024-04-23 at 11 25 02 AM](https://github.com/FreePBX/issue-tracker/assets/2153999/385ccf60-c33a-4643-b100-d71c13a80e0f)

**Comment by tony1661** [comment]
@dolesec nope everything seems to be working well since entering that command you suggested. Thanks for that!

**Comment by kapilgupta01** [comment]
Hi @dolesec please try with latest cdrpro i.e. 17.0.3.4 which has your ucp error fix. 

Thanks

**Comment by dolesec** [comment]
ty @kguptasangoma - no issues post upgrade,  that fixed it
