### ISSUE TITLE
[new-feature]: Links to Documentation

### ISSUE THREAD

**Issue by tony1661** [FreePBX/issue-tracker#113]
### FreePBX Version

FreePBX 17

### Feature Description

Can we get  the ability to have a help button on every page of FreePBX to link to the documentation for that page? Rather than having to go looking for it?

![image](https://github.com/FreePBX/issue-tracker/assets/5287266/4e3f745d-b3d0-4571-aff6-b15b252825c2)

**Comment by kapilgupta01** [comment]
Hey @tony1661 

Wiki link for each module is already present inside module updates page. for example see below screenshot for the "asterisk info" module. 

![image](https://github.com/FreePBX/issue-tracker/assets/131970355/83b8087b-ddf3-4fe3-8e6c-73c801b3c4cd)
