### ISSUE TITLE
Block/Hide chan_sip settings under Asterisk SIP Settings and Extensions module [bug]: 

### ISSUE THREAD

**Issue by msanthosh18** [FreePBX/issue-tracker#118]
### FreePBX Version

FreePBX 17

### Issue Description

FreePBX-17 system installed with Asterisk 21 we should block/hide the chan_sip settings option under sip settings and extensions and Trunks 
1.Advanced settings > SIP Channel Driver
2.Extensions > Add New SIP [chan_sip] extension (If in advanced settings, sip channel driver is set to “Both“, this will show up)
3.Add SIP (chan_sip) trunk,
4. Asterisk SIP Settings -> SIP Settings (chan_sip) 

### Operating Environment

Deb -12.5v

**Comment by jissphilip** [comment]
@msanthosh18 
already done .  https://sangoma.atlassian.net/browse/FREEPBX17-242
