### ISSUE TITLE
Block asterisk-switch-version to asterisk21 if SIP Channel Driver set to chan_sip[bug]: 

### ISSUE THREAD

**Issue by msanthosh18** [FreePBX/issue-tracker#119]
### FreePBX Version

FreePBX 17

### Issue Description

FreePBX-17 system installed with below asterisk21 (asterisk 18, 20.) and trying to switch asterisk version to 21 when SIP Channel Driver is set to chan_sip under Advanced settings 

Give warning while switching asterisk to user that "SIP Channel Driver is set to Chan_sip under Advanced Settings , please change to Chan_pjsip and give a try"

### Operating Environment

Deb -12.5v

**Comment by kapilgupta01** [comment]
Below command can give the currently running sip driver. 

`fwconsole setting  ASTSIPDRIVER
Setting of "ASTSIPDRIVER" is (select)[chan_pjsip]
`

If the driver is chan_sip then we need to block upgrading to the chan_sip to avoid any problem and let the user to change the sip driver first before upgrading to the asterisk 21 (which do not support chan-sip).

**Comment by kapilgupta01** [comment]
latest asterisk-version-switch rpm has the fix for this issue, which will block upgrading to 21+ asterisk versions is the current configured sip driver is chan_sip. thanks
