### ISSUE TITLE
[bug]: FreePBX17 legacy backup restore issues

### ISSUE THREAD

**Issue by dairyeng** [FreePBX/issue-tracker#123]
### FreePBX Version

FreePBX 17

### Issue Description

Started a fresh install of 17 after the last thread.
I made a very basic backup from the 13 server for ONLY the config MySql and skipped the asterisk part of the backup to see if I could isolate the issue.
With even just a restore of basic config info from my 13 server the admin console breaks.(see screenshot)
I tested full and minimal backup restores and on17 and another version 13 server in the last thread - so there may just be something wrong with the server outputting the backups incorrectly?
The errors at the end of the restore:

![Screenshot 2024-04-26 003937](https://github.com/FreePBX/issue-tracker/assets/50673605/934ba630-2a0b-49cf-b22a-e59d9e729731)

### Operating Environment

debian 12 fresh minimal install

### Relevant log output

```shell
Finished
There were errors during the restore process
	Undefined array key "amd" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "api" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "builtin" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "bulkhandler" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "calendar" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "callaccounting" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "configedit" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "warmspareenabled" on line 185 of file /var/www/html/admin/modules/core/Restore.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "AMPUSERS" on line 15 of file /var/www/html/admin/modules/dictate/Restore.php
	Undefined array key "extensionsettings" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "filestore" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "firewall" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "pbxmfa" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "pm2" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "queuestats" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "sangomaconnect" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "sangomartapi" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "warmspareenabled" on line 177 of file /var/www/html/admin/modules/sipsettings/Restore.php
	Undefined array key "smsplus" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "soundlang" on line 281 of file /var/www/html/admin/modules/backup/Handlers/Restore/Legacy.php
	Undefined array key "warmspareenabled" on line 74 of file /var/www/html/admin/modules/sysadmin/Restore.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Running an unsupported version of Asterisk. Supported Asterisk versions: 18, 19, 20, 21. Detected Asterisk version: 13.7.2  on line 30 of file /var/www/html/admin/modules/webrtc/Webrtc.class.php
npm WARN deprecated is-buffer@1.0.2: This version of 'is-buffer' is out-of-date. You must update to v1.1.6 or newer
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
```

**Comment by kapilgupta01** [comment]
Hey @dairyeng did you tried with backup v17.0.5.19 version?

**Comment by dairyeng** [comment]
I can't tell because the admin console is broken on that version of the VM after trying the restore.
The (Virtual Machine)backup I made a couple hours before I tried appears to be v17.0.5.18 though so it was probably on that version.
I'll update the backup module to 17.0.5.19 and give it another shot and report back soon.

**Comment by dairyeng** [comment]
Okay on 17.0.5.19(running a restore from a full backup) I got less errors at the end, but I still got some:

Finished
File named: /tmp/backup/0c43d1e4-a6bc-4ee8-b92c-dc19fc24b607/mysql-4.sql
There were errors during the restore process
	Undefined array key "warmspareenabled" on line 185 of file /var/www/html/admin/modules/core/Restore.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "AMPUSERS" on line 15 of file /var/www/html/admin/modules/dictate/Restore.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "warmspareenabled" on line 177 of file /var/www/html/admin/modules/sipsettings/Restore.php
	Undefined array key "warmspareenabled" on line 74 of file /var/www/html/admin/modules/sysadmin/Restore.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Undefined array key "module" on line 373 of file /var/www/html/admin/modules/backup/RestoreBase.php
	Running an unsupported version of Asterisk. Supported Asterisk versions: 18, 19, 20, 21. Detected Asterisk version: 13.7.2  on line 30 of file /var/www/html/admin/modules/webrtc/Webrtc.class.php
npm WARN deprecated is-buffer@1.0.2: This version of 'is-buffer' is out-of-date. You must update to v1.1.6 or newer
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

Trying to navigate away from the Backup/Restore page to the dashboard crashes with the error
![Screenshot 2024-04-26 133141](https://github.com/FreePBX/issue-tracker/assets/50673605/d1624771-2547-4ab1-8b91-dfcbc1ea1516)
 in the attached screenshot

**Comment by dairyeng** [comment]
Update: I've been able to get back into the admin console site by restarting apache2
However it's telling me it can't connect to asterisk now and running sudo systemctl start asterisk didn't seem to start it. The system disk usage section implies that it did get our IVR recordings etc. though so some things worked. 
![Screenshot 2024-04-26 133941](https://github.com/FreePBX/issue-tracker/assets/50673605/f9efe3f2-3aa4-4c6b-8a3b-95fcdd47ef26)

**Comment by dolesec** [comment]
@dairyeng have you tried  **_fwconsole restart_** ?

**Comment by dairyeng** [comment]
@dolesec I hadn't - but doing that doesn't seem to have fixed it. See attached screenshot.
![Screenshot 2024-04-26 151417](https://github.com/FreePBX/issue-tracker/assets/50673605/7e27e96e-0bae-40d9-badd-cc468d0dde4d)

**Comment by dolesec** [comment]
@dairyeng you may have an issue with the manager connection post restore , not uncommon ... 

whats the output of ..

`# ps aux | grep /sbin/asterisk`

**Comment by dairyeng** [comment]
@dolesec 
(don't think I ran it right the first time - screenshot is updated)
![Screenshot 2024-04-26 153543](https://github.com/FreePBX/issue-tracker/assets/50673605/f80d0cf3-b109-4917-949e-e5403641be92)

**Comment by dolesec** [comment]
@dairyeng so asterisk is running and it appears you only have a manager connection issue , I have to run out but there is plenty out there on how to resolve this .. google manager password mismatch Freepbx or something like that 

ill take a look and see if you have resolved it when I get back home 

I imagine if you were to look at the asterisk cli with something like **_asterisk -vvvvvr_** you would see manager authentication failures

**Comment by dolesec** [comment]
@dairyeng 

check out these two files and see in the manager password/secret matches 

/etc/amportal.conf   AMPMGRPASS=
/etc/asterisk/manager.conf   secret =


if those don't match it can produce results similar to what you are seeing , make them match and test again

**Comment by dairyeng** [comment]
@dolesec 
thank you! I reset the passwords to something I knew from the gibberish that was there. It didn't work so I tried asterisk -vvvvvr and it showed me errors about the /username/ being wrong. Those matched between the conf files but it was gibberish like the password, and asterisk was trying to use "admin" which no longer existed apparently.
Changing the account to admin in both conf files and restarting didn't help either and asterisk -vvvvvr got less descriptive just saying it can't authenticate as "admin"... SO, I changed the password in both places to something short and simple, 7 characters long, 6 letters and 1 number. Nope. asterisk -vvvvvr is still saying "failed to authenticate as "admin""
![Screenshot 2024-04-26 161240](https://github.com/FreePBX/issue-tracker/assets/50673605/724de9b4-8e3d-49bc-905d-f001be815d32)

EDIT: changing the password to the default amp111 didn't help either.

**Comment by dairyeng** [comment]
I guess if it helps, I've attached a screenshot of both files to show they've got the same entries.
![Screenshot 2024-04-26 164404](https://github.com/FreePBX/issue-tracker/assets/50673605/f667fd2c-3f7a-44ad-ab13-eb069d0d2148)

**Comment by dairyeng** [comment]
Heh. So I've got another problem: my trunk provider is stalling when I ask them for pjsip trunk setup info... I may need to settle for the most up-to-date version of FreePBX that still does chan_sip trunks for this to work with my provider anyway.

All I REALLY need to do is just get this one dudes freaking extension working but it's got a bug setting the "don't care" etc. on the recording features and the threads about that bug just say to upgrade away from it 😒 I think I'm going to have to settle for whatever version of FreePBX still works with chan_sip trunks in the short term... Unless y'all know of a good trunk provider that does newer sip configs I could port our number to without my current provider dragging their feet on it.

**Comment by dolesec** [comment]
@dairyeng with respect to the manager issue -  if the username and passwords match you should get connected ... check out some of the include files referenced in manager.conf  and see if something is off in one of those 

and for pjsip try to do ip based auth if you can , if you can't registration should be simple enough to set up and your provider should have a mechanism to provide your username and password for registration; I think its actually simpler to set up in pjsip versus chan_sip 

the issues you are facing do not  appear to be related to 17 itself...  both the username and the password should be that random gibberish you spoke of versus the well known defaults -  that was a security enhancement

**Comment by kapilgupta01** [comment]
From your log - 
"Running an unsupported version of Asterisk. Supported Asterisk versions: 18, 19, 20, 21. Detected Asterisk version: 13.7.2 on line 30 of file /var/www/html/admin/modules/webrtc/Webrtc.class.php
"

Also you need to run min asterisk 18 version for Freepbx 17 which supports chan_sip.

**Comment by dairyeng** [comment]
Got it. I assumed that a fresh install of the newest version of FreePBX would install the newest version of Asterisk and etc. I have to confess this is my first time installing/restoring a PBX server that didn't involve just throwing a good backup of the VM into use so I appreciate your patience with me.

I'm starting with a fresh 17 VM as upgrading Asterisk after the fact didn't fix the problem.
So far it's successfully upgraded Asterisk and it's still running.
Before I try and restore a backup again I will make sure that backup version v17.0.5.19 and php8.2-sqlite3 are installed and report back later.

**Comment by kapilgupta01** [comment]
hey , also please note script for fresh 17 will install asterisk 21 so you might have to use asterisk-version-switch to change to asterisk 18 because you want to restore chan_sip.

**Comment by kapilgupta01** [comment]
php8.2-sqlite3 -> why do you need this? We are install php8.2-mysql by default anyway.

**Comment by dairyeng** [comment]
>php8.2-sqlite3 -> why do you need this?

Just carrying over what worked from the last thread. A problem I ran into getting it to read the mysql tables from the backup was resolved by installing php8.2-sqlite3. It was just the version I found by googling my problem.

>hey , also please note script for fresh 17 will install asterisk 21 so you might have to use asterisk-version-switch to change to asterisk 18 because you want to restore chan_sip.

Thanks for the heads up - are you sure it installs 21? Does it install multiple versions and select the lowest one? I have no idea how 13 got installed then? Maybe my "restore" did something - that seems to be the point at which it starts complaining about version 13 being installed. 
I had just installed ver 20 because the message asterisk-version-switch gave me said the certified and uncertified versions of 18 were unavailable and to select another version. I ran it again and tried picking option 2 for the certified version of 18 and it seems to have started installing it anyway and then failed? And then I couldn't run asterisk-version-switch again.... I ended up installing Asterisk 18 via https://github.com/JustIndustrial/Asterisk-install and so far it looks like it's rolling along. I'll let this install finish and take another checkpoint backup of the VM before trying another restore, and will report back later.

**Comment by dairyeng** [comment]
Well that didn't work. it went back to "unable to connect to Asterisk" messages. asterisk -vvvvvr didn't actually output any authentication errors this time - it just never could connect to Asterisk again after restarting it.
Going back to asterisk-version-switch gives me this problem:
![Screenshot 2024-04-26 230713](https://github.com/FreePBX/issue-tracker/assets/50673605/6e3caed3-3b0d-43bd-885c-559a6a8f1649)
Going to try and go back to version 20 now and if it's still not connecting to asterisk I'm just going to revert to my checkpoint backup from a few hours back on this version 17 server.

EDIT: Nah it's busted now. Burning this VM and reverting to the backup. Please let me know how to properly get asterisk 18 onto FreePBX17

**Comment by dolesec** [comment]
@dairyeng FPBX17 is not designed for Asterisk 18,   per asterisk-version-switch ... 

![Screenshot 2024-04-27 at 7 27 28 AM](https://github.com/FreePBX/issue-tracker/assets/2153999/1deb79c2-40d2-410a-80dd-7859bf36e8b3)

**Comment by dairyeng** [comment]
@dolesec I did say I think I just need to use whatever version of FreePBX uses Asterisk18 but was told to keep trying restores on FreePBX 17...

I've spent the last 6 hours getting FreePBX 15 with Astrisk 18 running. It had some sh1 errors on the module upgrade but I think this is where I need to be until I can get a better trunk provider.

Thanks for trying to help.
