### ISSUE TITLE
[bug]: Cannot load the ionCube PHP Loader - it was already loaded

### ISSUE THREAD

**Issue by Andsup** [FreePBX/issue-tracker#126]
### FreePBX Version

FreePBX 17

### Issue Description

after apt-get update and  apt-get upgrade :

Error messages (many times) :

Cron <asterisk@pbx> [ -e /usr/sbin/fwconsole ] && sleep $((RANDOM%30)) && /usr/sbin/fwconsole job --run --quiet 2>&1 > /dev/null

php -v
Cannot load the ionCube PHP Loader - it was already loaded
PHP 8.2.18 (cli) (built: Apr 22 2024 10:12:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.18, Copyright (c) Zend Technologies
    with the ionCube PHP Loader v13.0.2, Copyright (c) 2002-2023, by ionCube Ltd.
    with Zend OPcache v8.2.18, Copyright (c), by Zend Technologies

### Operating Environment

debian 12.5

### Relevant log output

```shell
.
```

**Comment by dolesec** [comment]
@Andsup - try this, see last comment on fixing that issue from Ram  ... https://github.com/FreePBX/issue-tracker/issues/107#issuecomment-2082798296

**Comment by Andsup** [comment]
Thanks !
Solved.
