### ISSUE TITLE
[bug]:  "/etc/systemd/network"  Vs "/etc/network/interfaces/" for FreePBX 17 / Debian

### ISSUE THREAD

**Issue by kapilgupta01** [FreePBX/issue-tracker#127]
### FreePBX Version

FreePBX 17

### Issue Description

We can have two different types of network configuration in the Debian system - 
1) Network files present in  "/etc/systemd/network" Or  
2) Network files present in  "/etc/network/interfaces.d/"

1st one is mainly controlled by systemd.network utility.  

2nd one can be manually controlled by either FreePBX or user.

Right now, Freepbx is using/generating configuration files in the "/etc/network/interfaces.d/" path but this creates the problem for the users who are using "/etc/systemd/network" path which is common for LXC environment. 

Ref: 
1) https://discuss.linuxcontainers.org/t/etc-network-interfaces-is-missing-on-debian-image/16274 
2) https://community.freepbx.org/t/firewall-interfaces/95768/4 
3) https://github.com/FreePBX/issue-tracker/issues/94 

### Operating Environment

Debian 12

**Comment by Andsup** [comment]
to be more precise 👍 

Network config managed in this way on my VPS (regenerated at reboot):

Cloud-init --> Netplan --> systemd.network 

/etc/netplan/50-cloud-init.yaml  

 This file is generated from information provided by the datasource.  Changes
 to it will not persist across an instance reboot.  To disable cloud-init's
 network configuration capabilities, write a file
 /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
 network: {config: disabled}


network:
    version: 2
    ethernets:
        ens3:
            dhcp4: true
            match:
                macaddress: fa:16:3e:3a:dc:25
            mtu: 1500
            set-name: ens3

**Comment by kapilgupta01** [comment]
Correct @Andsup , Freepbx can not control or manage the network configurations if its generated by "systemd.network" so planning to add such validation/checks to avoid the confusion where users might use Freepbx UI to control the network interfaces.

**Comment by Andsup** [comment]
Already a good step.

A guideline to move from the current standard Debian network management to the former one will be a great help.
Or even better a script. 

Do you plan to manage in freepbx firewall network created on the fly like Wireguard Vpn ?
Currently I'm using the extra layer Firewalld solving all those issues (network managers, distro version ...). 
fail2ban could easily interface with firewalld layer. 
(only small attention point : an iptables restart shudown firewalld ...)

**Comment by kapilgupta01** [comment]
sysadmin v17.0.1.71

Fix - We are now disabling the configuration via the FreePBX UI if the system has running networkd utility.  We can either use networkd utility or Freepbx (any one) to control the networking.

thanks

**Comment by Andsup** [comment]
tested version 17.0.1.71, including a full restart

- network management in sysadmin : OK
- Firewall module still  as before : not working well with networkd and no message

Thanks

**Comment by kapilgupta01** [comment]
thanks for the prompt testing. We need to reproduce firewall issue locally to debug.

**Comment by Andsup** [comment]
issues : Firewall - Interfaces #94

may be a path forward : 
- if possible (/etc/network/interfaces/) , manage network and security via freepbx 
- if not, both network and security to be fully managed outside freepbx scope, under the administrator responsability

Thanks for your support.

**Comment by kapilgupta01** [comment]
if possible (/etc/network/interfaces/) , manage network and security via freepbx   -> This we are doing it already so if networkd is not running then freepbx will control the interfaces and write config to this path only.

**Comment by Andsup** [comment]
Hi,

I need some help.

I tried to find a sure way to move away from systemd-network. Nothing clear on google.
So I loooked at my distro freepbx config :
