### ISSUE TITLE
[bug]: Failed to start sangoma-pnpd.service

### ISSUE THREAD

**Issue by LeslieDesser** [FreePBX/issue-tracker#128]
### FreePBX Version

FreePBX 17

### Issue Description

Installed Debien 12 and FPBX 17 a few days ago.  This error showed up on the console.  
Tonight did a module update.  It no longer shows up on the console when the VM is restarted, but the service still fails to start.

### Operating Environment

All latest downloads
+-------------------+------------+---------+-------------+-----------+
| Module            | Version    | Status  | License     | Signature |
+-------------------+------------+---------+-------------+-----------+
| amd               | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| announcement      | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| api               | 17.0.1.1   | Enabled | AGPLv3+     | Sangoma   |
| areminder         | 17.0.3.9   | Enabled | Commercial  | Sangoma   |
| arimanager        | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| asterisk-cli      | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| asteriskinfo      | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| backup            | 17.0.5.20  | Enabled | GPLv3+      | Sangoma   |
| blacklist         | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| broadcast         | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| builtin           |            | Enabled |             | Unsigned  |
| bulkhandler       | 17.0.4     | Enabled | GPLv3+      | Sangoma   |
| calendar          | 17.0.4.7   | Enabled | GPLv3+      | Sangoma   |
| callaccounting    | 17.0.5     | Enabled | Commercial+ | Sangoma   |
| callback          | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| callerid          | 17.0.1     | Enabled | Commercial  | Sangoma   |
| callforward       | 17.0.1.3   | Enabled | AGPLv3+     | Sangoma   |
| calllimit         | 17.0.1.2   | Enabled | Commercial  | Sangoma   |
| callrecording     | 17.0.3.6   | Enabled | AGPLv3+     | Sangoma   |
| callwaiting       | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| cdr               | 17.0.4.13  | Enabled | GPLv3+      | Sangoma   |
| cdrpro            | 17.0.3.13  | Enabled | Commercial  | Sangoma   |
| cel               | 17.0.2.7   | Enabled | GPLv3+      | Sangoma   |
| certman           | 17.0.3.10  | Enabled | AGPLv3+     | Sangoma   |
| cidlookup         | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| conferences       | 17.0.3.1   | Enabled | GPLv3+      | Sangoma   |
| conferencespro    | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| configedit        | 17.0.1.1   | Enabled | AGPLv3+     | Sangoma   |
| contactmanager    | 17.0.5.8   | Enabled | GPLv3+      | Sangoma   |
| core              | 17.0.9.44  | Enabled | GPLv3+      | Sangoma   |
| cos               | 17.0.1.1   | Enabled | Commercial  | Sangoma   |
| customappsreg     | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| dahdiconfig       | 17.0.1.7   | Enabled | GPLv3+      | Sangoma   |
| dashboard         | 17.0.4.2   | Enabled | AGPLv3+     | Sangoma   |
| daynight          | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| dictate           | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| directory         | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| donotdisturb      | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| endpoint          | 17.0.1.59  | Enabled | Commercial  | Sangoma   |
| extensionroutes   | 17.0.1     | Enabled | Commercial  | Sangoma   |
| extensionsettings | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| fax               | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| faxpro            | 17.0.1.14  | Enabled | Commercial  | Sangoma   |
| featurecodeadmin  | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| filestore         | 17.0.2.11  | Enabled | AGPLv3      | Sangoma   |
| findmefollow      | 17.0.4.6   | Enabled | GPLv3+      | Sangoma   |
| firewall          | 17.0.1.17  | Enabled | AGPLv3+     | Sangoma   |
| framework         | 17.0.15.18 | Enabled | GPLv2+      | Sangoma   |
| hotelwakeup       | 17.0.1.5   | Enabled | GPLv2       | Sangoma   |
| iaxsettings       | 17.0.1     | Enabled | AGPLv3      | Sangoma   |
| infoservices      | 17.0.1     | Enabled | GPLv2+      | Sangoma   |
| ivr               | 17.0.5     | Enabled | GPLv3+      | Sangoma   |
| languages         | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| logfiles          | 17.0.3.1   | Enabled | GPLv3+      | Sangoma   |
| manager           | 17.0.5     | Enabled | GPLv2+      | Sangoma   |
| miscapps          | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| miscdests         | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| music             | 17.0.4     | Enabled | GPLv3+      | Sangoma   |
| outroutemsg       | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| paging            | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| pagingpro         | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| parking           | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| parkpro           | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| pbxmfa            | 17.0.2     | Enabled | Commercial+ | Sangoma   |
| phpinfo           | 17.0.1     | Enabled | GPLv2+      | Sangoma   |
| pinsets           | 17.0.3.1   | Enabled | GPLv3+      | Sangoma   |
| pinsetspro        | 17.0.2     | Enabled | Commercial  | Sangoma   |
| pm2               | 17.0.3.2   | Enabled | AGPLv3+     | Sangoma   |
| presencestate     | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| printextensions   | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| queueprio         | 17.0.1.4   | Enabled | GPLv3+      | Sangoma   |
| queues            | 17.0.1.8   | Enabled | GPLv2+      | Sangoma   |
| queuestats        | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| qxact_reports     | 17.0.2     | Enabled | Commercial  | Sangoma   |
| recording_report  | 17.0.3.8   | Enabled | Commercial  | Sangoma   |
| recordings        | 17.0.2.2   | Enabled | GPLv3+      | Sangoma   |
| restapps          | 17.0.1.14  | Enabled | Commercial  | Sangoma   |
| ringgroups        | 17.0.2.4   | Enabled | GPLv3+      | Sangoma   |
| sangomaconnect    | 17.0.1.26  | Enabled | Commercial  | Sangoma   |
| sangomacrm        | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| sangomartapi      | 17.0.1.22  | Enabled | Commercial  | Sangoma   |
| setcid            | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| sipsettings       | 17.0.6.4   | Enabled | AGPLv3+     | Sangoma   |
| sipstation        | 17.0.3.3   | Enabled | Commercial  | Sangoma   |
| sms               | 17.0.1.10  | Enabled | Commercial  | Sangoma   |
| smsplus           | 17.0.3     | Enabled | Commercial  | Sangoma   |
| soundlang         | 17.0.4.1   | Enabled | GPLv3+      | Sangoma   |
| sysadmin          | 17.0.1.66  | Enabled | Commercial  | Sangoma   |
| timeconditions    | 17.0.1.15  | Enabled | GPLv3+      | Sangoma   |
| tts               | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| ttsengines        | 17.0.1     | Enabled | AGPLv3      | Sangoma   |
| ucp               | 17.0.4.14  | Enabled | AGPLv3+     | Sangoma   |
| userman           | 17.0.6.20  | Enabled | AGPLv3+     | Sangoma   |
| vmblast           | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| vmnotify          | 17.0.1.5   | Enabled | Commercial  | Sangoma   |
| voicemail         | 17.0.5.15  | Enabled | GPLv3+      | Sangoma   |
| voicemail_report  | 17.0.1.1   | Enabled | Commercial  | Sangoma   |
| voipinnovations   | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| vqplus            | 17.0.1.16  | Enabled | Commercial  | Sangoma   |
| weakpasswords     | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| webrtc            | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
+-------------------+------------+---------+-------------+-----------+

### Relevant log output

```shell
From Syslog:

2024-05-04T23:29:54.808306+01:00 F-PBX-DL2 systemd[1]: Started sangoma-pnpd.service - Sangoma PnP Service.
2024-05-04T23:29:54.878956+01:00 F-PBX-DL2 pnp_server[14648]: Traceback (most recent call last):
2024-05-04T23:29:54.879433+01:00 F-PBX-DL2 pnp_server[14648]:   File "/usr/local/bin/pnp_server", line 21, in <module>
2024-05-04T23:29:54.879919+01:00 F-PBX-DL2 pnp_server[14648]:     import ConfigParser
2024-05-04T23:29:54.880259+01:00 F-PBX-DL2 pnp_server[14648]: ModuleNotFoundError: No module named 'ConfigParser'
2024-05-04T23:29:54.892931+01:00 F-PBX-DL2 systemd[1]: sangoma-pnpd.service: Main process exited, code=exited, status=1/FAILURE
2024-05-04T23:29:54.893104+01:00 F-PBX-DL2 systemd[1]: sangoma-pnpd.service: Failed with result 'exit-code'.
2024-05-04T23:29:55.039657+01:00 F-PBX-DL2 systemd[1]: sangoma-pnpd.service: Scheduled restart job, restart counter is at 1.
2024-05-04T23:29:55.040660+01:00 F-PBX-DL2 systemd[1]: Stopped sangoma-pnpd.service - Sangoma PnP Service.
```

**Comment by dolesec** [comment]
@LeslieDesser I see the same when pnp is enabled in sysadmin , i typically have it disabled but when enabling the error is present 

if you aren't using it you can safely disable it in sysadmin 

```
syslog:2024-05-04T20:24:33.822856-04:00 fpbx17 systemd[1]: Started sangoma-pnpd.service - Sangoma PnP Service.
syslog:2024-05-04T20:24:33.864033-04:00 fpbx17 pnp_server[1913]: Traceback (most recent call last):
syslog:2024-05-04T20:24:33.864271-04:00 fpbx17 pnp_server[1913]:   File "/usr/local/bin/pnp_server", line 21, in <module>
syslog:2024-05-04T20:24:33.864722-04:00 fpbx17 pnp_server[1913]:     import ConfigParser
syslog:2024-05-04T20:24:33.864804-04:00 fpbx17 pnp_server[1913]: ModuleNotFoundError: No module named 'ConfigParser'
```

good catch

**Comment by LeslieDesser** [comment]
What does the service provide?  Where/when would I use it?

**Comment by ramarajan222** [comment]
The PNP service is used for the auto-provisioning of Sangoma S-series phones. If you are not using a Sangoma S-series phone, then this service is not required.

**Comment by LeslieDesser** [comment]
Thank you for that.  It could well be that S500 may get used.
I have looked at the code and the 'import' line referencing 'ConfigParser'  seems to be redundant as there is no further reference in the code to 'ConfigParser' so its removal may well fix the issue - so I tried that but then there is more:
`File "/usr/local/bin/pnp_server", line 25, in <module>
import MySQLdb
ModuleNotFoundError: No module named 'MySQLdb'`
So I removed that and then got an error at line 203 - so its time to stop and put all back again as it was.

**Comment by LeslieDesser** [comment]
I have spotted an other service that fails to start: logrotate.service
`2024-05-05T11:20:58.756201+01:00 F-PBX-DL2 systemd[1]: Starting logrotate.service - Rotate log files...
2024-05-05T11:20:58.828106+01:00 F-PBX-DL2 logrotate[107066]: error: asterisk:36 lines must begin with a keyword or a filename (possibly in double quotes)
2024-05-05T11:20:58.828524+01:00 F-PBX-DL2 logrotate[107066]: error: found error in file asterisk, skipping
2024-05-05T11:20:58.853754+01:00 F-PBX-DL2 systemd[1]: logrotate.service: Main process exited, code=exited, status=1/FAILURE
2024-05-05T11:20:58.853974+01:00 F-PBX-DL2 systemd[1]: logrotate.service: Failed with result 'exit-code'.
2024-05-05T11:20:58.854090+01:00 F-PBX-DL2 systemd[1]: Failed to start logrotate.service - Rotate log files.
2024-0`

**Comment by dolesec** [comment]
id open a specific issue ticket for that @LeslieDesser , include what log files you were viewing to see that info as well

**Comment by LeslieDesser** [comment]
Done as #134

**Comment by kapilgupta01** [comment]
sadmin v17.0.1.67
and `apt-get install python3-mysqldb`.

updated in latest sng install script due to "python3-mysqldb"
