### ISSUE TITLE
[bug]: freepbx_dbug reporting consistent error related to PHP-BCMATH

### ISSUE THREAD

**Issue by dolesec** [FreePBX/issue-tracker#129]
### FreePBX Version

FreePBX 17

### Issue Description

looking over freepbx_dbug log I noted this was consistently reported as an error for multiple operations ... 

**_ERROR_INSTALL_PHP-BCMATH_**

resolved by installing the two items below and restarting apache 
```
apt-get install php-bcmath
apt-get install php8.2-bcmath

systemctl restart apache2
```

### Operating Environment

root@fpbx17:/var/log# fwconsole ma list 
No repos specified, using: [standard] from last GUI settings

+-------------------+------------+---------+-------------+-----------+
| Module            | Version    | Status  | License     | Signature |
+-------------------+------------+---------+-------------+-----------+
| amd               | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| announcement      | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| api               | 17.0.1.1   | Enabled | AGPLv3+     | Sangoma   |
| areminder         | 17.0.3.9   | Enabled | Commercial  | Sangoma   |
| arimanager        | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| asterisk-cli      | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| asteriskinfo      | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| backup            | 17.0.5.20  | Enabled | GPLv3+      | Sangoma   |
| blacklist         | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| broadcast         | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| builtin           |            | Enabled |             | Unsigned  |
| bulkhandler       | 17.0.4     | Enabled | GPLv3+      | Sangoma   |
| calendar          | 17.0.4.7   | Enabled | GPLv3+      | Sangoma   |
| callaccounting    | 17.0.5     | Enabled | Commercial+ | Sangoma   |
| callback          | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| callerid          | 17.0.1     | Enabled | Commercial  | Sangoma   |
| callforward       | 17.0.1.3   | Enabled | AGPLv3+     | Sangoma   |
| calllimit         | 17.0.1.2   | Enabled | Commercial  | Sangoma   |
| callrecording     | 17.0.3.6   | Enabled | AGPLv3+     | Sangoma   |
| callwaiting       | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| cdr               | 17.0.4.13  | Enabled | GPLv3+      | Sangoma   |
| cdrpro            | 17.0.3.13  | Enabled | Commercial  | Sangoma   |
| cel               | 17.0.2.7   | Enabled | GPLv3+      | Sangoma   |
| certman           | 17.0.3.10  | Enabled | AGPLv3+     | Sangoma   |
| cidlookup         | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| conferences       | 17.0.3.1   | Enabled | GPLv3+      | Sangoma   |
| conferencespro    | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| configedit        | 17.0.1.1   | Enabled | AGPLv3+     | Sangoma   |
| contactmanager    | 17.0.5.8   | Enabled | GPLv3+      | Sangoma   |
| core              | 17.0.9.44  | Enabled | GPLv3+      | Sangoma   |
| cos               | 17.0.1.1   | Enabled | Commercial  | Sangoma   |
| customappsreg     | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| dashboard         | 17.0.4.2   | Enabled | AGPLv3+     | Sangoma   |
| daynight          | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| dictate           | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| directory         | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| donotdisturb      | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| endpoint          | 17.0.1.59  | Enabled | Commercial  | Sangoma   |
| extensionroutes   | 17.0.1     | Enabled | Commercial  | Sangoma   |
| extensionsettings | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| fax               | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| faxpro            | 17.0.1.14  | Enabled | Commercial  | Sangoma   |
| featurecodeadmin  | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| filestore         | 17.0.2.11  | Enabled | AGPLv3      | Sangoma   |
| findmefollow      | 17.0.4.6   | Enabled | GPLv3+      | Sangoma   |
| firewall          | 17.0.1.17  | Enabled | AGPLv3+     | Sangoma   |
| framework         | 17.0.15.18 | Enabled | GPLv2+      | Sangoma   |
| hotelwakeup       | 17.0.1.5   | Enabled | GPLv2       | Sangoma   |
| iaxsettings       | 17.0.1     | Enabled | AGPLv3      | Sangoma   |
| infoservices      | 17.0.1     | Enabled | GPLv2+      | Sangoma   |
| ivr               | 17.0.5     | Enabled | GPLv3+      | Sangoma   |
| languages         | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| logfiles          | 17.0.3.1   | Enabled | GPLv3+      | Sangoma   |
| manager           | 17.0.5     | Enabled | GPLv2+      | Sangoma   |
| miscapps          | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| miscdests         | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| music             | 17.0.4     | Enabled | GPLv3+      | Sangoma   |
| outroutemsg       | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| paging            | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| pagingpro         | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| parking           | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| parkpro           | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| pbxmfa            | 17.0.2     | Enabled | Commercial+ | Sangoma   |
| phpinfo           | 17.0.1     | Enabled | GPLv2+      | Sangoma   |
| pinsets           | 17.0.3.1   | Enabled | GPLv3+      | Sangoma   |
| pinsetspro        | 17.0.2     | Enabled | Commercial  | Sangoma   |
| pm2               | 17.0.3.2   | Enabled | AGPLv3+     | Sangoma   |
| presencestate     | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| printextensions   | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| queueprio         | 17.0.1.4   | Enabled | GPLv3+      | Sangoma   |
| queues            | 17.0.1.8   | Enabled | GPLv2+      | Sangoma   |
| queuestats        | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| qxact_reports     | 17.0.2     | Enabled | Commercial  | Sangoma   |
| recording_report  | 17.0.3.8   | Enabled | Commercial  | Sangoma   |
| recordings        | 17.0.2.2   | Enabled | GPLv3+      | Sangoma   |
| restapps          | 17.0.1.14  | Enabled | Commercial  | Sangoma   |
| ringgroups        | 17.0.2.4   | Enabled | GPLv3+      | Sangoma   |
| sangomaconnect    | 17.0.1.26  | Enabled | Commercial  | Sangoma   |
| sangomacrm        | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| sangomartapi      | 17.0.1.22  | Enabled | Commercial  | Sangoma   |
| setcid            | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| sipsettings       | 17.0.6.4   | Enabled | AGPLv3+     | Sangoma   |
| sipstation        | 17.0.3.3   | Enabled | Commercial  | Sangoma   |
| sms               | 17.0.1.10  | Enabled | Commercial  | Sangoma   |
| smsplus           | 17.0.3     | Enabled | Commercial  | Sangoma   |
| soundlang         | 17.0.4.1   | Enabled | GPLv3+      | Sangoma   |
| sysadmin          | 17.0.1.66  | Enabled | Commercial  | Sangoma   |
| timeconditions    | 17.0.1.15  | Enabled | GPLv3+      | Sangoma   |
| tts               | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| ttsengines        | 17.0.1     | Enabled | AGPLv3      | Sangoma   |
| ucp               | 17.0.4.14  | Enabled | AGPLv3+     | Sangoma   |
| userman           | 17.0.6.20  | Enabled | AGPLv3+     | Sangoma   |
| vmblast           | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| vmnotify          | 17.0.1.5   | Enabled | Commercial  | Sangoma   |
| voicemail         | 17.0.5.15  | Enabled | GPLv3+      | Sangoma   |
| voicemail_report  | 17.0.1.1   | Enabled | Commercial  | Sangoma   |
| voipinnovations   | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| vqplus            | 17.0.1.16  | Enabled | Commercial  | Sangoma   |
| weakpasswords     | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| webrtc            | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
+-------------------+------------+---------+-------------+-----------+

all Debian updates applied as well 

### Relevant log output

```shell
[2024-05-02 13:31:40] [dbug.DEBUG]: Array
(
    [type] => PERF
    [str] => Generating CSS from LESS for customappsreg
    [now] => 0.21704300 1714671100
    [timediff] => ERROR_INSTALL_PHP-BCMATH
    [mem] => 52.074669 MB
    [memdiff] => 80 B
    [file] => /var/www/html/admin/libraries/Console/Reload.class.php:95
)



 [] []
[2024-05-02 13:31:40] [dbug.DEBUG]: 2024-May-02 13:31:40        /var/www/html/admin/libraries/BMO/Performance.class.php:112


 [] []
[2024-05-02 13:31:40] [dbug.DEBUG]: Array
(
    [type] => START
    [str] => Less Parser Generate Module Styles
    [now] => 0.21707000 1714671100
    [timediff] => ERROR_INSTALL_PHP-BCMATH
    [mem] => 52.074593 MB
    [memdiff] => -80 B
    [file] => /var/www/html/admin/libraries/BMO/Less.class.php:83
)



 [] []
[2024-05-02 13:31:40] [dbug.DEBUG]: 2024-May-02 13:31:40        /var/www/html/admin/libraries/BMO/Performance.class.php:112


 [] []
[2024-05-02 13:31:40] [dbug.DEBUG]: Array
(
    [type] => STOP
    [str] => Less Parser Generate Module Styles
    [now] => 0.21759900 1714671100
    [timediff] => ERROR_INSTALL_PHP-BCMATH
    [mem] => 52.075378 MB
    [memdiff] => 824 B
    [file] => /var/www/html/admin/libraries/BMO/Less.class.php:116
)



 [] []
[2024-05-02 13:31:40] [dbug.DEBUG]: 2024-May-02 13:31:40        /var/www/html/admin/libraries/BMO/Performance.class.php:112


 [] []
[2024-05-02 13:31:40] [dbug.DEBUG]: Array
(
    [type] => PERF
    [str] => Finished Generating Less
    [now] => 0.21765200 1714671100
    [timediff] => ERROR_INSTALL_PHP-BCMATH
    [mem] => 52.074799 MB
    [memdiff] => -608 B
    [file] => /var/www/html/admin/libraries/Console/Reload.class.php:95
)



 [] []
[2024-05-02 13:31:40] [dbug.DEBUG]: 2024-May-02 13:31:40        /var/www/html/admin/libraries/BMO/Performance.class.php:112


 [] []
[2024-05-02 13:31:40] [dbug.DEBUG]: Array
(
    [type] => PERF
    [str] => Symlinking files for dashboard
    [now] => 0.21768300 1714671100
    [timediff] => ERROR_INSTALL_PHP-BCMATH
    [mem] => 52.074852 MB
    [memdiff] => 56 B
    [file] => /var/www/html/admin/libraries/Console/Reload.class.php:95
)
```

**Comment by kapilgupta01** [comment]
thanks @dolesec added mentioned packages to the install script.
