### ISSUE TITLE
SangomaConnect won't update / sync with PBX, shows no voicemails or calls[bug]: 

### ISSUE THREAD

**Issue by jlizzotte** [FreePBX/issue-tracker#13]
### FreePBX Version

FreePBX 15

### Issue Description

SangomaConnect won't update / sync with PBX, shows no voicemails or calls

### Operating Environment

FreePBX 15. Asterisk 18

**Comment by kguptasangoma** [comment]
Hi 

You've opened a bug for a Commercial Module.

This Issue tracking system is for our Free and Open Source modules only.

Please open [a commercial support ticket [here](https://help.sangoma.com/)!.

If you are using FreePBX 12 or higher, please make sure you attach a Support Debug package (which is generated through the System Admin module) to the commercial support ticket.  Do not attach it to THIS bug tracker, as it may contain confidential information that will not be hidden from the general public.


Thank you for using FreePBX.
Kapil Gupta
