### ISSUE TITLE
[bug]: Error thrown with message "Class 'ZipArchive' not found"  Stacktrace: #6 Error in /var/www/html/admin/modules/sccp_manager/install.php:817 #5 createBackUpConfig in /var/www/html/admin/modules/sccp_manager/install.php:57 #4 include_once in /var/www/html/admin/libraries/modulefunctions.class.php:2663 #3 module_functions:_doinclude in /var/www/html/admin/libraries/modulefunctions.class.php:2579 #2 module_functions:_runscripts in /var/www/html/admin/libraries/modulefunctions.class.php:2045 #1 module_functions:install in /var/www/html/admin/page.modules.php:303 #0 include in /var/www/html/admin/config.php:481

### ISSUE THREAD

**Issue by davidew98** [FreePBX/issue-tracker#130]
### FreePBX Version

FreePBX 16

### Issue Description

Error thrown with message "Class 'ZipArchive' not found"

Stacktrace:
#6 Error in /var/www/html/admin/modules/sccp_manager/install.php:817
#5 createBackUpConfig in /var/www/html/admin/modules/sccp_manager/install.php:57
#4 include_once in /var/www/html/admin/libraries/modulefunctions.class.php:2663
#3 module_functions:_doinclude in /var/www/html/admin/libraries/modulefunctions.class.php:2579
#2 module_functions:_runscripts in /var/www/html/admin/libraries/modulefunctions.class.php:2045
#1 module_functions:install in /var/www/html/admin/page.modules.php:303
#0 include in /var/www/html/admin/config.php:481

### Operating Environment

Error thrown with message "Class 'ZipArchive' not found"

Stacktrace:
#6 Error in /var/www/html/admin/modules/sccp_manager/install.php:817
#5 createBackUpConfig in /var/www/html/admin/modules/sccp_manager/install.php:57
#4 include_once in /var/www/html/admin/libraries/modulefunctions.class.php:2663
#3 module_functions:_doinclude in /var/www/html/admin/libraries/modulefunctions.class.php:2579
#2 module_functions:_runscripts in /var/www/html/admin/libraries/modulefunctions.class.php:2045
#1 module_functions:install in /var/www/html/admin/page.modules.php:303
#0 include in /var/www/html/admin/config.php:481

### Relevant log output

```shell
Error thrown with message "Class 'ZipArchive' not found"

Stacktrace:
#6 Error in /var/www/html/admin/modules/sccp_manager/install.php:817
#5 createBackUpConfig in /var/www/html/admin/modules/sccp_manager/install.php:57
#4 include_once in /var/www/html/admin/libraries/modulefunctions.class.php:2663
#3 module_functions:_doinclude in /var/www/html/admin/libraries/modulefunctions.class.php:2579
#2 module_functions:_runscripts in /var/www/html/admin/libraries/modulefunctions.class.php:2045
#1 module_functions:install in /var/www/html/admin/page.modules.php:303
#0 include in /var/www/html/admin/config.php:481
```

**Comment by kapilgupta01** [comment]
Please install the php zip package i.e. php8.2-zip"

thanks
