### ISSUE TITLE
[improvement]: Suggestions to improve robustness and reliability

### ISSUE THREAD

**Issue by tdltdl** [FreePBX/issue-tracker#1309]
### FreePBX Version

FreePBX 17

### Improvement Description

Here are some suggestions for the script "sng_freepbx_debian_install.sh"
- add "set -e" at the beginning of the script so if anything wrong occurs, in conjunction with the second suggestion about trap, it is noticeable (and we do not end up with a partially installed system).
- add a "trap xxx EXIT" where xxx is doing some cleanup (delete the pidfile, detect incomplete installation and maybe do some cleanup if the installation was not completed or store the steps that were already completed if they are not idempotent so at next run they can be skipped). That sill also remove the need to explicitly call "terminate" which is not done consistently (example if an unknown option is passed)
- add a date/time to the log filename (something like $(date "+%Y.%m.%d-%H.%M.%S") concatenated in the logfilename). This ensure that we keep th logs of the previous attempts.
- check for root should be one of the first thing to do (before trying to create the directories and log file)
- not sure it is desired, but if mongodb fails to install, the installation is not stopped
- if a package fails to install, the return code is 0 (due to the exit 0 in the terminate function), I would expect a non zero exit code.
- should the pid filename indicate it is the installation of freePBX17 (something like "/var/run/freepbx17_install.pid")? 
- usually the pidfile contains a PID (echo $$ > pid_file). Having this could also allow to check if the proces ID is still actually running making the manual deletion unneeded if the proces is anyway not running anymore
- improve the postfix config (hardcoding "my.hostname.example" could be replace by $(hostname -f)" and "Internet Site" could be asked?)
- usage of apt-key add is deprecated when adding http://deb.freepbx.org/gpg/aptly-pubkey.asc
- would it make sense to automatically configure letsencrypt for SSL?
- some part of the script seems to support arm64 (deb in mongodb lists both amd64 and arm64), but the lib aac always download the amd64 arch.

Question
- What is the rationale for calling many times the pkg_install with each packages individually versus passing once the full list?
- aac library installed ins not the latest one (2.0.1-1 from March 2020, latest is 2.0.2-1 from Sept 2021). Should it be updated?

Disclosure: Those suggestions are only based on reading the script without executing it -so mileage can vary ;-).

**Comment by kapilgupta01** [comment]
Hey @tdltdl  I  merged the PR so we can test the new script. Got some hiccups and updated the codebase. 
Also looks like packages.sury.org is failing as well.
![image](https://github.com/FreePBX/issue-tracker/assets/131970355/e2c73337-0915-4a5b-811e-d4ebf141756c)
