### ISSUE TITLE
[bug]: Asterisk SIP Settings / Default TLS Port Assignment has chan_sip option

### ISSUE THREAD

**Issue by blazestudios97** [FreePBX/issue-tracker#131]
### FreePBX Version

FreePBX 17

### Issue Description

In the Asterisk SIP Settings under the Default TLS Port Assignment, there is still a chan_sip option. Since FreePBX v17 is being built by default with Asterisk v21, which has no longer has chan_sip, this option is no longer needed. In fact I don't think the over all option of selecting a default TLS port is needed since there are no longer two SIP drivers.

![sip_settings_freepbx17](https://github.com/FreePBX/issue-tracker/assets/10702410/7f556af1-721b-4908-aa90-0edd90efa99d)

### Operating Environment

Debian 12
FreePBX 17.0.15.18
Asterisk 21.0.2

**Comment by kapilgupta01** [comment]
We need to hide(disable) all the chan_sip related options for asterisk 21+ systems. 
As Freepbx 17 can support asterisk 18 also so still need to keep the chan_sip only if running asterisk version supports the chan_sip.

**Comment by girishmani1992** [comment]
Hi @blazestudios97 ,

We have hidden all chan_sip related options in asterisk 21+ installed pbx systems. Please upgrade below modules to the version mentioned.

core v17.0.9.46
firewall v17.0.1.18
sipsettings v17.0.6.7


Thanks
