### ISSUE TITLE
[bug]: CID Superfecta module - CID Prefix URL don't work

### ISSUE THREAD

**Issue by veLraT** [FreePBX/issue-tracker#133]
### FreePBX Version

FreePBX 15

### Issue Description

 CID Prefix URL don't work at last module version 15.0.5

$scheme_param array does not exist in the code

To restore work, you need:

1. At Superfecta.class.php 
`if ((isset($scheme_param['Prefix_URL'])) && (trim($scheme_param['Prefix_URL']) != '')) {`
change to 
`if ((isset($options['scheme_settings']['Prefix_URL'])) && (trim($options['scheme_settings']['Prefix_URL'])) != '') {`

2. At …/includes/superfecta_base.php
`protected $prefix = '';`
change to
`public $prefix = '';`

3. At Superfecta.class.php
`$this->out(sprintf(_("Prefix Url result took %s seconds."),number_format((mctime_float() - $start_time), 4)));`
change to
`$this->out(sprintf(_("Prefix Url result took %s seconds."),number_format(($superfecta->mctime_float() - $start_time), 4)));`

Hopefully a fix will be included in future versions so that you don't see security bugs in the FreePBX web interface

### Operating Environment

CID Superfecta module 15.0.5
FreePBX 15.0.37.4

**Comment by kapilgupta01** [comment]
Thanks @veLraT for reporting this issue, suggested fix has been pushed to the edge.
Superfecta v15.0.6
Superfecta v16.0.33
Superfecta v17.0.1.7
