### ISSUE TITLE
Intrusion Detection : no way to disable it. Always on after a restart

### ISSUE THREAD

**Issue by Andsup** [FreePBX/issue-tracker#135]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

After a fwconsole restart, "Intrusion Detection" is always "on". Even if stopped and config saved before the restart.
I would like to manage /etc/fail2ban/jail.local without being recreated during a restart. 
The final goal is to interface fail2ban with firewalld.

'#banaction = iptables-multiport
'#banaction_allports = iptables-allports

banaction = firewallcmd-rich-rules[actiontype=]
banaction_allports = firewallcmd-rich-rules[actiontype=]

### Operating Environment

debian 12.5

### Relevant log output

```shell
.
```

**Comment by ramarajan222** [comment]
Hi @Andsup 

Disable "Intrusion Detection Service" on the firewall module advanced setting. 

![image](https://github.com/FreePBX/issue-tracker/assets/25248291/1f9dca7b-7c93-4cbc-b4e8-7cfe11fabd26)
