### ISSUE TITLE
[bug]: fwconsole reload --verbose ErrorException

### ISSUE THREAD

**Issue by LongchaoFeng** [FreePBX/issue-tracker#137]
### FreePBX Version

FreePBX 17

### Issue Description

I implemented Google TTS by modifying the code in /var/lib/asterisk/agi-bin/propolys-tts.agi. However, after executing 'fwconsole reload --verbose', I encountered a Whoops\Exception\ErrorException, and the changes I made to propolys-tts.agi were rolled back. Is this rollback of code caused by the reload exception? The original code also has this exception when executing reload.

### Operating Environment

+-------------------+------------+---------+-------------+-----------+
| Module            | Version    | Status  | License     | Signature |
+-------------------+------------+---------+-------------+-----------+
| amd               | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| announcement      | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| areminder         | 17.0.3.9   | Enabled | Commercial  | Sangoma   |
| arimanager        | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| asterisk-cli      | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| asteriskinfo      | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| backup            | 17.0.5.14  | Enabled | GPLv3+      | Sangoma   |
| blacklist         | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| broadcast         | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| builtin           |            | Enabled |             | Unsigned  |
| bulkhandler       | 17.0.4     | Enabled | GPLv3+      | Sangoma   |
| calendar          | 17.0.4.6   | Enabled | GPLv3+      | Sangoma   |
| callaccounting    | 17.0.4     | Enabled | Commercial+ | Sangoma   |
| callback          | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| callerid          | 17.0.1     | Enabled | Commercial  | Sangoma   |
| callforward       | 17.0.1.3   | Enabled | AGPLv3+     | Sangoma   |
| calllimit         | 17.0.1.2   | Enabled | Commercial  | Sangoma   |
| callrecording     | 17.0.3.6   | Enabled | AGPLv3+     | Sangoma   |
| callwaiting       | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| cdr               | 17.0.4.13  | Enabled | GPLv3+      | Sangoma   |
| cel               | 17.0.2.7   | Enabled | GPLv3+      | Sangoma   |
| certman           | 17.0.3.7   | Enabled | AGPLv3+     | Sangoma   |
| cidlookup         | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| conferences       | 17.0.3.1   | Enabled | GPLv3+      | Sangoma   |
| conferencespro    | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| configedit        | 17.0.1.1   | Enabled | AGPLv3+     | Sangoma   |
| contactmanager    | 17.0.5.6   | Enabled | GPLv3+      | Sangoma   |
| core              | 17.0.9.33  | Enabled | GPLv3+      | Sangoma   |
| cos               | 17.0.1.1   | Enabled | Commercial  | Sangoma   |
| customappsreg     | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| dashboard         | 17.0.4.2   | Enabled | AGPLv3+     | Sangoma   |
| daynight          | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| dictate           | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| directory         | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| donotdisturb      | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| endpoint          | 17.0.1.53  | Enabled | Commercial  | Sangoma   |
| extensionroutes   | 17.0.1     | Enabled | Commercial  | Sangoma   |
| extensionsettings | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| fax               | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| faxpro            | 17.0.1.14  | Enabled | Commercial  | Sangoma   |
| featurecodeadmin  | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| filestore         | 17.0.2.9   | Enabled | AGPLv3      | Sangoma   |
| findmefollow      | 17.0.4.6   | Enabled | GPLv3+      | Sangoma   |
| firewall          | 17.0.1.13  | Enabled | AGPLv3+     | Sangoma   |
| framework         | 17.0.15.13 | Enabled | GPLv2+      | Sangoma   |
| hotelwakeup       | 17.0.1.5   | Enabled | GPLv2       | Sangoma   |
| iaxsettings       | 17.0.1     | Enabled | AGPLv3      | Sangoma   |
| infoservices      | 17.0.1     | Enabled | GPLv2+      | Sangoma   |
| ivr               | 17.0.5     | Enabled | GPLv3+      | Sangoma   |
| languages         | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| logfiles          | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| manager           | 17.0.3     | Enabled | GPLv2+      | Sangoma   |
| miscapps          | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| miscdests         | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| music             | 17.0.4     | Enabled | GPLv3+      | Sangoma   |
| paging            | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| pagingpro         | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| parking           | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| parkpro           | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| pbxmfa            | 17.0.2     | Enabled | Commercial+ | Sangoma   |
| pinsets           | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| pinsetspro        | 17.0.2     | Enabled | Commercial  | Sangoma   |
| pm2               | 17.0.3.1   | Enabled | AGPLv3+     | Sangoma   |
| presencestate     | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| printextensions   | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| queueprio         | 17.0.1.4   | Enabled | GPLv3+      | Sangoma   |
| queues            | 17.0.1.7   | Enabled | GPLv2+      | Sangoma   |
| queuestats        | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| qxact_reports     | 17.0.2     | Enabled | Commercial  | Sangoma   |
| recording_report  | 17.0.3.6   | Enabled | Commercial  | Sangoma   |
| recordings        | 17.0.2.2   | Enabled | GPLv3+      | Sangoma   |
| restapps          | 17.0.1.14  | Enabled | Commercial  | Sangoma   |
| ringgroups        | 17.0.2.4   | Enabled | GPLv3+      | Sangoma   |
| sangomaconnect    | 17.0.1.20  | Enabled | Commercial  | Sangoma   |
| sangomartapi      | 17.0.1.14  | Enabled | Commercial  | Sangoma   |
| setcid            | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| sipsettings       | 17.0.6.3   | Enabled | AGPLv3+     | Sangoma   |
| sipstation        | 17.0.3.3   | Enabled | Commercial  | Sangoma   |
| sms               | 17.0.1.8   | Enabled | Commercial  | Sangoma   |
| smsplus           | 17.0.3     | Enabled | Commercial  | Sangoma   |
| soundlang         | 17.0.4     | Enabled | GPLv3+      | Sangoma   |
| sysadmin          | 17.0.1.48  | Enabled | Commercial  | Sangoma   |
| timeconditions    | 17.0.1.13  | Enabled | GPLv3+      | Sangoma   |
| tts               | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| ttsengines        | 17.0.1     | Enabled | AGPLv3      | Sangoma   |
| ucp               | 17.0.4.13  | Enabled | AGPLv3+     | Sangoma   |
| userman           | 17.0.6.16  | Enabled | AGPLv3+     | Sangoma   |
| vmblast           | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| vmnotify          | 17.0.1.5   | Enabled | Commercial  | Sangoma   |
| voicemail         | 17.0.5.14  | Enabled | GPLv3+      | Sangoma   |
| voicemail_report  | 17.0.1.1   | Enabled | Commercial  | Sangoma   |
| vqplus            | 17.0.1.13  | Enabled | Commercial  | Sangoma   |
| weakpasswords     | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| webrtc            | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
+-------------------+------------+---------+-------------+-----------+

### Relevant log output

```shell
In Network.class.php line 141:

  [Whoops\Exception\ErrorException (2)]
  Undefined array key "config"

Exception trace:
  at /var/www/html/admin/modules/sysadmin/Network.class.php:141
 Whoops\Run->handleError() at /var/www/html/admin/modules/sysadmin/Network.class.php:141
 FreePBX\modules\Sysadmin\Network->parseInterfaces() at /var/www/html/admin/modules/sysadmin/Network.class.php:20
 FreePBX\modules\Sysadmin\Network->discoverInterfaces() at /var/www/html/admin/modules/sysadmin/Sysadmin.class.php:2442
 FreePBX\modules\Sysadmin->getAllNetworkInfo() at /var/www/html/admin/modules/endpoint/DpmaModel.class.php:978
 FreePBX\modules\Endpoint\DpmaModel->update_dpma_settings_file() at /var/www/html/admin/modules/endpoint/functions.inc/functions_dpma.php:38
 endpoint_conf->get_filename() at /var/www/html/admin/libraries/BMO/FileHooks.class.php:52
 FreePBX\FileHooks->processOldHooks() at /var/www/html/admin/libraries/BMO/FileHooks.class.php:26
 FreePBX\FileHooks->processFileHooks() at /var/www/html/admin/libraries/Console/Reload.class.php:337
 FreePBX\Console\Command\Reload->reload() at /var/www/html/admin/libraries/Console/Reload.class.php:92
 FreePBX\Console\Command\Reload->execute() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php:312
 Symfony\Component\Console\Command\Command->run() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:1022
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:314
 Symfony\Component\Console\Application->doRun() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:168
 Symfony\Component\Console\Application->run() at /var/lib/asterisk/bin/fwconsole:163
```

**Comment by kapilgupta01** [comment]
hi @LongchaoFeng can you please update to the latest sysadmin module and give a try?
sysadmin v17.0.1.67

**Comment by LongchaoFeng** [comment]
thanks @kguptasangoma  sysadmin upgraded to v17.0.1.67, Whoops\Exception\ErrorException no longer appears, but the changes I made to propolys-tts.agi were rolled back.  I still need to check the log, it may be caused by other module errors.
