### ISSUE TITLE
[bug]: According to the debian wiki, ubuntu repositories should not be added to debian.

### ISSUE THREAD

**Issue by maccadoo** [FreePBX/issue-tracker#138]
### FreePBX Version

FreePBX 17

### Issue Description

According to the debian wiki
adding ubuntu repositories to debian creates FrankenDebian and makes it less stable! 
https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

However, line 302 of sng_freepbx_debian_install.sh uses ubuntu repositories.
so, I rewrote this line.
It's working correctly in my environment.

add-apt-repository -y -S "deb [ arch=${arch} ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" >> "$log" 2>&1

to

add-apt-repository -y -S "deb [ arch=${arch} ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main" >> "$log" 2>&1

Why use ubuntu repositories at the expense of stability?

### Operating Environment

debian_version 12.5

**Comment by kapilgupta01** [comment]
Just pushed the changes to the new script. Thanks for reporting this issue @maccadoo
