### ISSUE TITLE
[bug]: I'm getting an error with apt update.

### ISSUE THREAD

**Issue by maccadoo** [FreePBX/issue-tracker#139]
### FreePBX Version

FreePBX 17

### Issue Description

root@fpbx17:~# apt update
N: Repository 'Debian bookworm' changed its 'non-free component' value from 'non-free' to 'non-free non-free-firmware'
N: More information about this can be found online in the Release notes at: https://www.debian.org/releases/bookworm/amd64/release-notes/ch-information.html#non-free-split

line 304 of sng_freepbx_debian_install.sh uses ubuntu repositories.
so, I rewrote this line.
No more errors.

add-apt-repository -y -S "deb http://ftp.debian.org/debian/ stable main non-free" >> "$log" 2>&1

to

add-apt-repository -y -S "deb http://ftp.debian.org/debian/ stable main non-free non-free-firmware" >> "$log" 2>&1

### Operating Environment

debian_version 12.5

**Comment by kapilgupta01** [comment]
Done, please check the latest script.

Thank you for using Freepbx 17
Kapil
