### ISSUE TITLE
[bug]: SipStation Module does not do anything when entering an account key

### ISSUE THREAD

**Issue by LightningManGTS** [FreePBX/issue-tracker#14]
### FreePBX Version

FreePBX 17

### Issue Description

Adding Ioncube to load with PHP and then installing SIPStation works however when you go paste the account key in nothing happens. Reading the console output in developer tools this is all that comes up
![image](https://github.com/FreePBX/issue-tracker/assets/3919521/f8b28648-ed6c-4fbb-a9d9-278a47cf9860)

### Operating Environment

FreePBX Framework 17.0.15
Debian 12
asterisk 20.6
17.0.3

### Relevant log output

```shell
Not sure where I would pull any relevant logs from
```

**Comment by kguptasangoma** [comment]
Hi @LightningManGTS  this error could occur if you have trying to use wrong key, could you please re-try with the proper key?
however I agree we should display a proper error message so raised internal ticket to take care of that improvement. 

Thank you for using FreePBX
Kapil Gupta

**Comment by ramarajan222** [comment]
moving to close, please reopen if still the issue persists. thanks.
