### ISSUE TITLE
Failing to enable chan SIP on FreePBX 17 Beta on Debian 12

### ISSUE THREAD

**Issue by kmadzora** [FreePBX/issue-tracker#140]
### FreePBX Version

FreePBX 17

### Issue Description

I am trying to enable chan sip, when I Change channel driver to "both" it reverts to chan_pjsip. FreePBX 17 Beta on Debian 12

### Operating Environment

FreePBX 17 Beta on Debian 12

**Comment by jcolp** [comment]
Per the comment on https://github.com/FreePBX/issue-tracker/issues/131 by default Asterisk 21 is installed, meaning that chan_sip is not available. Further work needs to be done to hide chan_sip in the GUI in that case. If chan_sip is needed you would need to switch the Asterisk version in use to 18 or 20. Note that eventually all versions of Asterisk with chan_sip will go end of life.
