### ISSUE TITLE
Extension tab missing under Applications

### ISSUE THREAD

**Issue by kmadzora** [FreePBX/issue-tracker#141]
### FreePBX Version

FreePBX 17

### Issue Description

Extensions tab missing under applications 

![exte](https://github.com/FreePBX/issue-tracker/assets/169152351/d1942073-ce31-4569-a7a6-aaebc161c273)

### Operating Environment

FreePBX 17 Beta Debian 12

**Comment by kapilgupta01** [comment]
Its moved to connectivity tab.
