### ISSUE TITLE
[bug]: FreePBX CDR MP3 Playback

### ISSUE THREAD

**Issue by umairmalik2410** [FreePBX/issue-tracker#143]
### FreePBX Version

FreePBX 15

### Issue Description

Unable to playback CDR recordings stored in mp3 format if you upgrade beyond 15.0.24. This is the last version where the mp3 playback works. As soon as you upgrade to 15.0.24.1 the playback no longer works. 

### Operating Environment

Official FreePBX 15.0.37.4 
Current Asterisk Version: 13.38.3
+---------------------+------------+-----------------------------------+------------+-----------+
| Module              | Version    | Status                            | License    | Signature |
+---------------------+------------+-----------------------------------+------------+-----------+
| accountcodepreserve | 13.0.2.2   | Enabled                           | GPLv2      | Sangoma   |
| allowlist           | 15.0.13    | Enabled                           | GPLv3+     | Sangoma   |
| amd                 | 15.0.3     | Enabled                           | GPLv3+     | Sangoma   |
| announcement        | 15.0.3.13  | Enabled                           | GPLv3+     | Sangoma   |
| api                 | 15.0.11    | Enabled                           | AGPLv3+    | Sangoma   |
| arimanager          | 15.0.3.20  | Enabled                           | GPLv3+     | Sangoma   |
| asterisk-cli        | 14.0.4     | Enabled                           | GPLv3+     | Sangoma   |
| asteriskinfo        | 15.0.14    | Enabled                           | GPLv3+     | Sangoma   |
| backup              | 15.0.26    | Enabled                           | GPLv3+     | Sangoma   |
| blacklist           | 15.0.4     | Enabled                           | GPLv3+     | Sangoma   |
| builtin             |            | Enabled                           |            | Unsigned  |
| bulkhandler         | 15.0.4     | Enabled                           | GPLv3+     | Sangoma   |
| calendar            | 15.0.10    | Enabled                           | GPLv3+     | Sangoma   |
| callback            | 15.0.12    | Enabled                           | GPLv3+     | Sangoma   |
| callforward         | 15.0.16    | Enabled                           | AGPLv3+    | Sangoma   |
| callrecording       | 15.0.7.29  | Enabled                           | AGPLv3+    | Sangoma   |
| callwaiting         | 15.0.4.6   | Enabled                           | GPLv3+     | Sangoma   |
| cdr                 | 15.0.24    | Enabled                           | GPLv3+     | Sangoma   |
| cdrpro              |            | Not Installed (Locally available) | Commercial | Sangoma   |
| cel                 | 15.0.17    | Enabled                           | GPLv3+     | Sangoma   |
| certman             | 15.0.49    | Enabled                           | AGPLv3+    | Sangoma   |
| cidlookup           | 15.0.27    | Enabled                           | GPLv3+     | Sangoma   |
| conferences         | 15.0.7.11  | Enabled                           | GPLv3+     | Sangoma   |
| conferencespro      | 15.0.3.18  | Enabled                           | Commercial | Sangoma   |
| configedit          | 13.0.7.3   | Enabled                           | AGPLv3+    | Sangoma   |
| contactmanager      | 15.0.13    | Enabled                           | GPLv3+     | Sangoma   |
| core                | 15.0.22.36 | Enabled                           | GPLv3+     | Sangoma   |
| customappsreg       | 15.0.14    | Enabled                           | GPLv3+     | Sangoma   |
| dashboard           | 15.0.18    | Enabled                           | AGPLv3+    | Sangoma   |
| daynight            | 15.0.12    | Enabled                           | GPLv3+     | Sangoma   |
| dictate             | 15.0.7     | Enabled                           | GPLv3+     | Sangoma   |
| directory           | 15.0.19    | Enabled                           | GPLv3+     | Sangoma   |
| disa                | 15.0.4.9   | Enabled                           | AGPLv3+    | Sangoma   |
| donotdisturb        | 15.0.10    | Enabled                           | GPLv3+     | Sangoma   |
| dynroute            | 15.0.3     | Enabled                           | GPLv3+     | Sangoma   |
| endpoint            | 15.0.65.7  | Enabled                           | Commercial | Sangoma   |
| extensionroutes     | 15.0.8     | Enabled                           | Commercial | Sangoma   |
| extensionsettings   | 13.0.4     | Enabled                           | GPLv3+     | Sangoma   |
| fax                 | 15.0.22    | Enabled                           | GPLv3+     | Sangoma   |
| featurecodeadmin    | 15.0.2     | Enabled                           | GPLv3+     | Sangoma   |
| filestore           | 15.0.9     | Enabled                           | AGPLv3     | Sangoma   |
| findmefollow        | 15.0.37    | Enabled                           | GPLv3+     | Sangoma   |
| firewall            | 15.0.43    | Enabled                           | AGPLv3+    | Sangoma   |
| framework           | 15.0.37.4  | Enabled                           | GPLv2+     | Sangoma   |
| fw_langpacks        | 14.0.1     | Enabled                           | GPLv3+     | Sangoma   |
| googletts           | 0.0.3      | Enabled                           |            | Unknown   |
| hotelwakeup         | 15.0.5.5   | Enabled                           | GPLv2      | Sangoma   |
| iaxsettings         | 15.0.8     | Enabled                           | AGPLv3     | Sangoma   |
| infoservices        | 15.0.3     | Enabled                           | GPLv2+     | Sangoma   |
| irc                 | 13.0.1     | Enabled                           | GPLv3+     | Sangoma   |
| ivr                 | 15.0.30    | Enabled                           | GPLv3+     | Sangoma   |
| languages           | 15.0.13    | Enabled                           | GPLv3+     | Sangoma   |
| logfiles            | 15.0.15    | Enabled                           | GPLv3+     | Sangoma   |
| manager             | 15.0.23    | Enabled                           | GPLv2+     | Sangoma   |
| miscapps            | 15.0.10    | Enabled                           | GPLv3+     | Sangoma   |
| miscdests           | 15.0.2.12  | Enabled                           | GPLv3+     | Sangoma   |
| music               | 15.0.22    | Enabled                           | GPLv3+     | Sangoma   |
| oracle_connector    |            | Not Installed (Locally available) | Commercial | Sangoma   |
| outroutemsg         | 15.0.9     | Enabled                           | GPLv3+     | Sangoma   |
| paging              | 15.0.4.35  | Enabled                           | GPLv3+     | Sangoma   |
| parking             | 15.0.15.4  | Enabled                           | GPLv3+     | Sangoma   |
| phonebook           | 15.0.12    | Enabled                           | GPLv3+     | Sangoma   |
| phpinfo             | 13.0.2     | Enabled                           | GPLv2+     | Sangoma   |
| pinsets             | 15.0.1.15  | Enabled                           | GPLv3+     | Sangoma   |
| pm2                 | 15.0.10    | Enabled                           | AGPLv3+    | Sangoma   |
| pms                 |            | Not Installed (Locally available) | Commercial | Sangoma   |
| presencestate       | 15.0.11    | Enabled                           | GPLv3+     | Sangoma   |
| printextensions     | 13.0.3.4   | Enabled                           | GPLv3+     | Sangoma   |
| queueprio           | 15.0.10    | Enabled                           | GPLv3+     | Sangoma   |
| queues              | 15.0.39    | Enabled                           | GPLv2+     | Sangoma   |
| recordings          | 15.0.6     | Enabled                           | GPLv3+     | Sangoma   |
| restapps            | 15.0.42.5  | Enabled                           | Commercial | Sangoma   |
| ringgroups          | 15.0.11.17 | Enabled                           | GPLv3+     | Sangoma   |
| sangomaconnect      |            | Not Installed (Locally available) | Commercial | Sangoma   |
| sangomartapi        | 15.0.55.3  | Enabled                           | Commercial | Sangoma   |
| setcid              | 15.0.9     | Enabled                           | GPLv3+     | Sangoma   |
| sipsettings         | 15.0.11    | Enabled                           | AGPLv3+    | Sangoma   |
| sipstation          |            | Not Installed (Locally available) | Commercial | Sangoma   |
| sms                 | 15.0.37    | Enabled                           | Commercial | Sangoma   |
| smsplus             | 15.0.2     | Enabled                           | Commercial | Sangoma   |
| soundlang           | 15.0.5.10  | Enabled                           | GPLv3+     | Sangoma   |
| superfecta          | 15.0.5     | Enabled                           | GPLv2+     | Sangoma   |
| sysadmin            | 15.0.33.14 | Enabled                           | Commercial | Sangoma   |
| timeconditions      | 15.0.15.11 | Enabled                           | GPLv3+     | Sangoma   |
| tts                 | 15.0.12    | Enabled                           | GPLv3+     | Sangoma   |
| ttsengines          | 15.0.4.7   | Enabled                           | AGPLv3     | Sangoma   |
| ucp                 | 15.0.15    | Enabled                           | AGPLv3+    | Sangoma   |
| userman             | 15.0.69.19 | Enabled                           | AGPLv3+    | Sangoma   |
| versionupgrade      | 15.0.42    | Enabled                           | Commercial | Sangoma   |
| vmblast             | 15.0.11.8  | Enabled                           | GPLv3+     | Sangoma   |
| voicemail           | 15.0.32    | Enabled                           | GPLv3+     | Sangoma   |
| voipinnovations     |            | Not Installed (Locally available) | Commercial | Sangoma   |
| weakpasswords       | 13.0.2     | Enabled                           | GPLv3+     | Sangoma   |
| webrtc              | 15.0.10.13 | Enabled                           | GPLv3+     | Sangoma   |
| zulu                |            | Not Installed (Locally available) | Commercial | Sangoma   |
+---------------------+------------+-----------------------------------+------------+-----------+

**Comment by kapilgupta01** [comment]
Hi @umairmalik2410 Can you please give a try with the latest 16 system ? thanks

**Comment by lgaetz** [comment]
Clarification. FreePBX 15 is security fixes only at this point. Reproducing the issue in version 16 or 17 will be required.

**Comment by kapilgupta01** [comment]
Closing this jira , please try with 16 or 17 and re-open if issue exists on 16 /17 system. thanks

**Comment by thiagopollachini** [comment]
> ### FreePBX Version
> FreePBX 15
> 
> ### Issue Description
> Unable to playback CDR recordings stored in mp3 format if you upgrade beyond 15.0.24. This is the last version where the mp3 playback works. As soon as you upgrade to 15.0.24.1 the playback no longer works.
> 
> ### Operating Environment
> Official FreePBX 15.0.37.4 Current Asterisk Version: 13.38.3 +---------------------+------------+-----------------------------------+------------+-----------+ | Module | Version | Status | License | Signature | +---------------------+------------+-----------------------------------+------------+-----------+ | accountcodepreserve | 13.0.2.2 | Enabled | GPLv2 | Sangoma | | allowlist | 15.0.13 | Enabled | GPLv3+ | Sangoma | | amd | 15.0.3 | Enabled | GPLv3+ | Sangoma | | announcement | 15.0.3.13 | Enabled | GPLv3+ | Sangoma | | api | 15.0.11 | Enabled | AGPLv3+ | Sangoma | | arimanager | 15.0.3.20 | Enabled | GPLv3+ | Sangoma | | asterisk-cli | 14.0.4 | Enabled | GPLv3+ | Sangoma | | asteriskinfo | 15.0.14 | Enabled | GPLv3+ | Sangoma | | backup | 15.0.26 | Enabled | GPLv3+ | Sangoma | | blacklist | 15.0.4 | Enabled | GPLv3+ | Sangoma | | builtin | | Enabled | | Unsigned | | bulkhandler | 15.0.4 | Enabled | GPLv3+ | Sangoma | | calendar | 15.0.10 | Enabled | GPLv3+ | Sangoma | | callback | 15.0.12 | Enabled | GPLv3+ | Sangoma | | callforward | 15.0.16 | Enabled | AGPLv3+ | Sangoma | | callrecording | 15.0.7.29 | Enabled | AGPLv3+ | Sangoma | | callwaiting | 15.0.4.6 | Enabled | GPLv3+ | Sangoma | | cdr | 15.0.24 | Enabled | GPLv3+ | Sangoma | | cdrpro | | Not Installed (Locally available) | Commercial | Sangoma | | cel | 15.0.17 | Enabled | GPLv3+ | Sangoma | | certman | 15.0.49 | Enabled | AGPLv3+ | Sangoma | | cidlookup | 15.0.27 | Enabled | GPLv3+ | Sangoma | | conferences | 15.0.7.11 | Enabled | GPLv3+ | Sangoma | | conferencespro | 15.0.3.18 | Enabled | Commercial | Sangoma | | configedit | 13.0.7.3 | Enabled | AGPLv3+ | Sangoma | | contactmanager | 15.0.13 | Enabled | GPLv3+ | Sangoma | | core | 15.0.22.36 | Enabled | GPLv3+ | Sangoma | | customappsreg | 15.0.14 | Enabled | GPLv3+ | Sangoma | | dashboard | 15.0.18 | Enabled | AGPLv3+ | Sangoma | | daynight | 15.0.12 | Enabled | GPLv3+ | Sangoma | | dictate | 15.0.7 | Enabled | GPLv3+ | Sangoma | | directory | 15.0.19 | Enabled | GPLv3+ | Sangoma | | disa | 15.0.4.9 | Enabled | AGPLv3+ | Sangoma | | donotdisturb | 15.0.10 | Enabled | GPLv3+ | Sangoma | | dynroute | 15.0.3 | Enabled | GPLv3+ | Sangoma | | endpoint | 15.0.65.7 | Enabled | Commercial | Sangoma | | extensionroutes | 15.0.8 | Enabled | Commercial | Sangoma | | extensionsettings | 13.0.4 | Enabled | GPLv3+ | Sangoma | | fax | 15.0.22 | Enabled | GPLv3+ | Sangoma | | featurecodeadmin | 15.0.2 | Enabled | GPLv3+ | Sangoma | | filestore | 15.0.9 | Enabled | AGPLv3 | Sangoma | | findmefollow | 15.0.37 | Enabled | GPLv3+ | Sangoma | | firewall | 15.0.43 | Enabled | AGPLv3+ | Sangoma | | framework | 15.0.37.4 | Enabled | GPLv2+ | Sangoma | | fw_langpacks | 14.0.1 | Enabled | GPLv3+ | Sangoma | | googletts | 0.0.3 | Enabled | | Unknown | | hotelwakeup | 15.0.5.5 | Enabled | GPLv2 | Sangoma | | iaxsettings | 15.0.8 | Enabled | AGPLv3 | Sangoma | | infoservices | 15.0.3 | Enabled | GPLv2+ | Sangoma | | irc | 13.0.1 | Enabled | GPLv3+ | Sangoma | | ivr | 15.0.30 | Enabled | GPLv3+ | Sangoma | | languages | 15.0.13 | Enabled | GPLv3+ | Sangoma | | logfiles | 15.0.15 | Enabled | GPLv3+ | Sangoma | | manager | 15.0.23 | Enabled | GPLv2+ | Sangoma | | miscapps | 15.0.10 | Enabled | GPLv3+ | Sangoma | | miscdests | 15.0.2.12 | Enabled | GPLv3+ | Sangoma | | music | 15.0.22 | Enabled | GPLv3+ | Sangoma | | oracle_connector | | Not Installed (Locally available) | Commercial | Sangoma | | outroutemsg | 15.0.9 | Enabled | GPLv3+ | Sangoma | | paging | 15.0.4.35 | Enabled | GPLv3+ | Sangoma | | parking | 15.0.15.4 | Enabled | GPLv3+ | Sangoma | | phonebook | 15.0.12 | Enabled | GPLv3+ | Sangoma | | phpinfo | 13.0.2 | Enabled | GPLv2+ | Sangoma | | pinsets | 15.0.1.15 | Enabled | GPLv3+ | Sangoma | | pm2 | 15.0.10 | Enabled | AGPLv3+ | Sangoma | | pms | | Not Installed (Locally available) | Commercial | Sangoma | | presencestate | 15.0.11 | Enabled | GPLv3+ | Sangoma | | printextensions | 13.0.3.4 | Enabled | GPLv3+ | Sangoma | | queueprio | 15.0.10 | Enabled | GPLv3+ | Sangoma | | queues | 15.0.39 | Enabled | GPLv2+ | Sangoma | | recordings | 15.0.6 | Enabled | GPLv3+ | Sangoma | | restapps | 15.0.42.5 | Enabled | Commercial | Sangoma | | ringgroups | 15.0.11.17 | Enabled | GPLv3+ | Sangoma | | sangomaconnect | | Not Installed (Locally available) | Commercial | Sangoma | | sangomartapi | 15.0.55.3 | Enabled | Commercial | Sangoma | | setcid | 15.0.9 | Enabled | GPLv3+ | Sangoma | | sipsettings | 15.0.11 | Enabled | AGPLv3+ | Sangoma | | sipstation | | Not Installed (Locally available) | Commercial | Sangoma | | sms | 15.0.37 | Enabled | Commercial | Sangoma | | smsplus | 15.0.2 | Enabled | Commercial | Sangoma | | soundlang | 15.0.5.10 | Enabled | GPLv3+ | Sangoma | | superfecta | 15.0.5 | Enabled | GPLv2+ | Sangoma | | sysadmin | 15.0.33.14 | Enabled | Commercial | Sangoma | | timeconditions | 15.0.15.11 | Enabled | GPLv3+ | Sangoma | | tts | 15.0.12 | Enabled | GPLv3+ | Sangoma | | ttsengines | 15.0.4.7 | Enabled | AGPLv3 | Sangoma | | ucp | 15.0.15 | Enabled | AGPLv3+ | Sangoma | | userman | 15.0.69.19 | Enabled | AGPLv3+ | Sangoma | | versionupgrade | 15.0.42 | Enabled | Commercial | Sangoma | | vmblast | 15.0.11.8 | Enabled | GPLv3+ | Sangoma | | voicemail | 15.0.32 | Enabled | GPLv3+ | Sangoma | | voipinnovations | | Not Installed (Locally available) | Commercial | Sangoma | | weakpasswords | 13.0.2 | Enabled | GPLv3+ | Sangoma | | webrtc | 15.0.10.13 | Enabled | GPLv3+ | Sangoma | | zulu | | Not Installed (Locally available) | Commercial | Sangoma | +---------------------+------------+-----------------------------------+------------+-----------+
> 
> ### Relevant log output
> _No response_

You need to update the recording file for another table (transient_cdr) in asteriskcdrdb.
It's the same query that you run for cdr table.

**Comment by kapilgupta01** [comment]
hi @thiagopollachini please try with 16 or 17 and if issue exists on 16 and 17 then please raise the fresh new issue. thanks

**Comment by umairmalik2410** [comment]
@thiagopollachini thank you, updating the recordingfile under transient_cdr db worked. thank you!
