### ISSUE TITLE
[bug]: In asterisk 21 installed pbx, need to remove options related to "chan_sip"

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#144]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

In asterisk 21 installed v17 pbx, need to remove options related to "chan_sip". Attached screen-shot for reference. 

As asterisk 21 does not support chan_sip, need to remove these settings. Attached screen-shots of few of these settings.

### Operating Environment

Asterisk 21 
freepbx 17 

![image-20240229-062406](https://github.com/FreePBX/issue-tracker/assets/163297370/7904d51a-79ca-45ac-abf8-3921d172ba64)
![image-20240229-062436](https://github.com/FreePBX/issue-tracker/assets/163297370/884fe88c-0cf3-46b6-9064-14bdca5046b1)
![image-20240229-062506](https://github.com/FreePBX/issue-tracker/assets/163297370/9f0bf709-0e8d-41fd-bfe8-3fc606ff87e1)
![image-20240229-062523](https://github.com/FreePBX/issue-tracker/assets/163297370/e7c10684-5776-4ca9-8e50-31b095851fc1)
![image-20240229-062537](https://github.com/FreePBX/issue-tracker/assets/163297370/5349ff97-9caa-4f6f-8249-9aa6a7f44642)
![image-20240229-062604](https://github.com/FreePBX/issue-tracker/assets/163297370/6026d488-88cc-4941-9b02-6b138a271517)
![image-20240229-062652](https://github.com/FreePBX/issue-tracker/assets/163297370/c4e354c3-b398-4da1-93f2-1bc553d9c70b)
![image-20240229-062803](https://github.com/FreePBX/issue-tracker/assets/163297370/aab1dee8-654d-4ecc-9abf-520730eff4b7)
![image-20240508-115422](https://github.com/FreePBX/issue-tracker/assets/163297370/cc7d6f94-3c35-4d7b-a29f-a22da1fc0f61)
![image-20240508-115605](https://github.com/FreePBX/issue-tracker/assets/163297370/93b2a576-9bf8-4b16-b893-227c00732a35)
![image-20240508-115651](https://github.com/FreePBX/issue-tracker/assets/163297370/90a2816d-f1b0-4c79-90cd-ddcaf304b9cd)

**Comment by blazestudios97** [comment]
If the box is setup to only use Chan_PJSIP then I agree. Unfortunately, users will be able to downgrade Asterisk to 18 or 20 which would allow the use of chan_sip. So until FreePBX stops supporting chan_sip in any form, regardless of the Asterisk version (ie don't build with it) these need to stick around but should only be showed if chan_sip is the only driver or if both drivers are in use.

**Comment by kapilgupta01** [comment]
Hi @blazestudios97 PJSIP is only for asterisk 21+ . IF user downgrade the asterisk then it will continue to work as it is today i.e. both chan_sip and pjsip would be available.

**Comment by kapilgupta01** [comment]
core v17.0.9.55
