### ISSUE TITLE
[bug]: sipsettings : general sip settings & chan_pjsip settings are in single page and same details are displayed on both tabs

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#145]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

In sipsettings, general sip settings & chan_pjsip settings are in single page and same details are displayed on both tabs

 
Thanks

### Operating Environment

<img width="917" alt="sipsettings2" src="https://github.com/FreePBX/issue-tracker/assets/163297370/76bdf387-0fcc-4bb8-8ca9-b533667431e0">

<img width="672" alt="sipsettings1" src="https://github.com/FreePBX/issue-tracker/assets/163297370/ce47004b-4d85-4109-b53b-b6e08048c91f">

**Comment by prasanthcode4** [comment]
sipsettings version 17.0.6.6
