### ISSUE TITLE
[bug]: SIP driver option in advanced settings issue after asterisk-version-switch 

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#148]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

In freepbx v17, if asterisk is downgraded from 21 to 20, then SIP driver option doesn't appear immediately. We have do some additional steps for it to appear.    
1) We have to go to UI > settings > advanced settings > click on "submit" and then "apply config" 
2) We can login to ssh and execute the command "fwconsole reload"

And if asterisk is upgraded from 20 to 21, we can do above steps for sip driver option to disappear.
 
Ideally as asterisk is completely re-installed, services reloaded and freepbx is restarted, sip driver should appear/disappear immediately after the completion of asterisk switch. 

Thanks

### Operating Environment

Freepbx v17

asterisk 20, 21

**Comment by lgaetz** [comment]
Project focus is to not add features to support chan_sip and instead provide features where possible to assist moving to pjsip. chan_sip has been disabled by default on new installs going back to the beginning of version 16, so this is no different.

**Comment by jissphilip** [comment]
core version 17.0.9.59
