### ISSUE TITLE
[improvement]: add the ability for sysadmin to enable/disable sshd PasswordAuthentication 

### ISSUE THREAD

**Issue by dolesec** [FreePBX/issue-tracker#155]
### FreePBX Version

FreePBX 17

### Improvement Description

 a **security** option under sysadmin would be a good place to do this ... it could also act as a placeholder where future  security related options could be implemented 

```
/etc/ssh/sshd_config
PasswordAuthentication no
```

**Comment by kapilgupta01** [comment]
Hi @dolesec We should not allow the ROOT SSH for the debian.
We are adding option in sysadmin to create a temp user, enable ssh for that user but only with ssh_keys (no password). this would be useful for Sangoma Support people and for others whoever wants to enable  ssh access to there system without compromising the security.
Ref https://github.com/FreePBX/issue-tracker/issues/117

**Comment by dolesec** [comment]
I don't mind root ssh so much as long as it not with a password , support uses the keys package as you stated - ill look forward to seeing the new option - ty sir !
