### ISSUE TITLE
Freepbx 17 : firewall and network

### ISSUE THREAD

**Issue by Andsup** [FreePBX/issue-tracker#156]
### FreePBX Version

FreePBX 17

### Improvement Description

Hi,
I tried to switch from "networkd" network management to /etc/network/interfaces files based.
Quite few help on internet to do this migration back to the former way of working.

End result : no network, KVM to repair and a lot of stress
So a very bad experience.

I don't want to go in production with such kind of risk at support level.

Distro freepbx centos is based on "NetworkManager" with config files in /etc/sysconfig/network-scripts/
This is also easily manageable with tools like nmcli et nmtui,.

Why not let, in a first step, this possibility available next to the basic "/etc/network/interfaces" ?

This is not the best and uptodate but still more user friendly way to configure network

Thanks.

**Comment by dolesec** [comment]
@Andsup you're using a standard debian image ? also wondering what the conversion steps were that you took if possible ...

**Comment by Andsup** [comment]
For sure crash is linked to a mistake during the "manually" network file creation .

- Fully out of the box debian image from my hoster  with latest debian 12.5 setup (as many if not all virtual servers)

- Today I back to the initial network setup with Cloud-init off : netplan (DHCP based) -> systemd-networkd.

The server is correctly secured with firewalld (firewall-cmd  ...) but firewalld service have to be restart after each freepbx 17 (re)start.
Killed by the freepbx "Intrusion Detection" service during the load.

My expectation is a config, that even in case of complete crash, could be easily reinstalled from a freepbx backup.
Like the freepbx version 16 distro based version.

NB: message in admin "you'll need to disable systemd-networkd. " is quite incomplete and misleading

**Comment by chrismkinsey** [comment]
FreePBX is now general release, but still pegged to Network-Manager which is yesterday's news.  Even CentOS 7, which went end of life on June 30, 2024 had switched to SystemD (and therefore NetworkD).  But Sangoma...
Many Linux distributions have adopted systemd as their standard initialization system. Some of the major distributions include:

	1.	Ubuntu: Starting from version 15.04 (Vivid Vervet), Ubuntu uses systemd as the default init system.
	2.	Debian: Since Debian 8 (Jessie), systemd is the default.
	3.	Fedora: One of the first adopters, Fedora has used systemd since Fedora 15.
	4.	Red Hat Enterprise Linux (RHEL): Adopted systemd starting with RHEL 7.
	5.	CentOS: Similarly, CentOS 7 and later versions use systemd.
	6.	Arch Linux: Switched to systemd as the default init system in October 2012.
	7.	openSUSE: Uses systemd as the default system and service manager.
	8.	Mageia: Since version 2, Mageia has used systemd.

These distributions leverage systemd for its parallelization capabilities, faster boot times, and unified management of system services.

**Comment by kapilgupta01** [comment]
Freepbx will manage the `/etc/network/interfaces`  if Freepbx is allowed to manage the network interfaces. 

Created below jira also as improvement in sysadmin network management section.

https://github.com/FreePBX/issue-tracker/issues/444  

https://sangomakb.atlassian.net/wiki/spaces/FP/pages/380534846/Network+configuration+with+Freepbx+17

**Comment by diegoweb** [comment]
> Freepbx will manage the `/etc/network/interfaces` if Freepbx is allowed to manage the network interfaces.
> 
> Created below jira also as improvement in sysadmin network management section.
> 
> #444
> 
> [sangomakb.atlassian.net/wiki/spaces/FP/pages/380534846/Network+configuration+with+Freepbx+17](https://sangomakb.atlassian.net/wiki/spaces/FP/pages/380534846/Network+configuration+with+Freepbx+17)

This tutorial expects the user to have their system registered in order to use the full System Admin module.
Free users are still facing the same issue, since they can't edit anything in System Admin module
![image](https://github.com/user-attachments/assets/fa29efb0-5f26-4398-bd14-fe4e81207584)

I'm running a fresh install and I'm still facing this issue:
![image](https://github.com/user-attachments/assets/4c816300-6bb3-42b7-8d75-4146c3240e5c)


Could you please take a look at that?
