### ISSUE TITLE
[bug]: Extensions output to pdf does not work

### ISSUE THREAD

**Issue by IgorKok** [FreePBX/issue-tracker#157]
### FreePBX Version

FreePBX 16

### Issue Description

It does not display numbers in a pdf file, when you click on the “download pdf” button, an error appears (attached screenshot). Russian localization is used, also for the sake of experiment I tried changing line 220 from "$txt = iconv('UTF-8', 'ISO-8859-1', $txt);" to "$txt = iconv('UTF-8', 'ISO-8859-5', $txt);" in the file along the path ""/var/www/html/admin/modules/printextensions/PDF.php"", after this there was no error from the screenshot, the file was output, but hieroglyphs were displayed instead of extension.
![Снимок экрана 2024-05-13 131308](https://github.com/FreePBX/issue-tracker/assets/169649689/d1d1b6e2-f6fb-4ce9-89d8-aa1fd52aa1f6)

### Operating Environment

FreePBX 16.0.40.7, printextensions 16.0.8

**Comment by kapilgupta01** [comment]
latest framework 17,x contains the fix.
