### ISSUE TITLE
[improvement]: consider not installing dahdiconfig by default 

### ISSUE THREAD

**Issue by dolesec** [FreePBX/issue-tracker#161]
### FreePBX Version

FreePBX 17

### Improvement Description

with the stated cloud focus of fpbx17 and in order to avoid the following error with the dahdiconfig module  allow it to be configured on demand when dadhi is actually detected to be present ... essentially turn the current logic around

![dahdi](https://github.com/FreePBX/issue-tracker/assets/2153999/a930b9db-f079-4786-9a7e-bafc89608890)

**Comment by derekcrpd** [comment]
I agree with this. It can be installed (quite easily) by those that need it, rather than forcing the rest of us to uninstall it.

**Comment by kapilgupta01** [comment]
Done, removed dahdiconfig module from the freepbx package install.
