### ISSUE TITLE
[improvement]: Use the new PARK_GET_CHANNEL function to replace/update parkfetch.agi 

### ISSUE THREAD

**Issue by blazestudios97** [FreePBX/issue-tracker#163]
### FreePBX Version

FreePBX 17

### Improvement Description

Currently when picking up a parked channel FreePBX runs the parkfetch.agi script which issues a `parking show <lot>` command and then parses through the output to find the channel sitting on a specific slot in the parking lot. 

This is to replace that process in parkfetch.agi with the PARK_GET_CHANNEL function which will return the channel on a specific slot in a parking lot. By doing something like 

`exten = s,n,Set(PCHANNEL=${GET_PARK_CHANNEL(2,parkinglot_1)})`

This will set PCHANNEL to the current channel that is parked on slot 2 in parkinglot_1. From there, if so desired, the parkfetch.agi could still be called to import channel variables from PCHANNEL to the current channel picking up the call. However, this could potentially now all be done in the dialplan as so:

```
exten = s,n,Set(PCHANNEL=${GET_PARK_CHANNEL(${ARG1},${ARG2})})
exten = s,n,Set(PARKIE=${PCHANNEL})
exten = s,n,Set(REC_STATUS=${IMPORT(${PCHANNEL},REC_STATUS)}) ;repeat IMPORT function for all call recording variables as in parkfetch.agi

```

**Comment by kapilgupta01** [comment]
parking v17.0.2.2

**Comment by blazestudios97** [comment]
This version isn't available online. Let me guess, Edge?

**Comment by blazestudios97** [comment]
Since there wasn't a real review period for the PR...this is should be change:

```
$ext->add($pc, $exten, '',new ext_set('PCHANNEL','${PARK_GET_CHANNEL(${ARG1},${ARG2})}'));
$ext->add($pc, $exten, '',new ext_set('PARKIE','${PCHANNEL}'));
```
I wasn't expecting it to be taken literally so the proper way would just be one line:

`$ext->add($pc, $exten, '',new ext_set('PARKIE','${PARK_GET_CHANNEL(${ARG1},${ARG2})}'));
`

**Comment by kapilgupta01** [comment]
Hi @blazestudios97  Please have a look into https://github.com/FreePBX/parking/pull/3/files . thanks

**Comment by kapilgupta01** [comment]
parking v17.0.2.3
