### ISSUE TITLE
[bug]: Freepbx 17 *45 toggle not working as expected

### ISSUE THREAD

**Issue by tpimont** [FreePBX/issue-tracker#169]
### FreePBX Version

FreePBX 17

### Issue Description

I've create a queue 1810 with dynamic agent 1635 , on the phone of the agent create a BLF to login/logout toggle  *451635*1810
the login is ok and the BLF work, but when try to logout by pressing the button again the BLF is always on and the message is still agent login not logout .

### Operating Environment

Freepbx 17, asterisk 20.6, Rocky 9

### Relevant log output

```shell
[2024-05-17 10:34:29] WARNING[137944][C-00000010]: app_queue.c:8501 aqm_exec: Unable to add interface 'Local/1635@from-queue/n' to queue '1810': Already there
```

**Comment by tpimont** [comment]
sorry the stars were not noted in the message (star)451635(star)1810

**Comment by tpimont** [comment]
i found that in log :
[2024-05-17 11:38:44] WARNING[141457][C-00000012]: res_agi.c:2038 handle_connection: Connecting to '127.0.0.1:4573' failed for url 'agi://127.0.0.1/queue_devstate.agi': Connection refused
[2024-05-17 11:38:44] WARNING[141457][C-00000012]: res_agi.c:2098 launch_netscript: Couldn't connect to any host.  FastAGI failed.

so i disable fastagi in advanced settings and the *45 behaviour is ok , login/logout and BLF on/off
i try to disable firewall but it not solve the problem

**Comment by ramarajan222** [comment]
Enable fastagi and Check Fastagi service is running on your system or not?

` fwconsole pm2 --list
+---------------------------+-------+--------+----------+-----------------------+------+---------+
| Process Name              | PID   | Status | Restarts | Uptime                | CPU  | Mem     |
+---------------------------+-------+--------+----------+-----------------------+------+---------+
| core-calltransfer-monitor | 3719  | online | 0        | 5 hours, 6 minutes    | 0%   | 17.24MB |
| core-fastagi              | 4285  | online | 0        | 5 hours, 6 minutes    | 0.3% | 29.10MB |
| sangomartapi              | 4479  | online | 0        | 5 hours, 6 minutes    | 0.2% | 51.89MB |
| ucp                       | 4593  | online | 0        | 5 hours, 6 minutes    | 0.3% | 28.38MB |
| qcallback                 | 4696  | online | 0        | 5 hours, 6 minutes    | 0%   | 20.38MB |
| qcallback-events          | 4789  | online | 0        | 5 hours, 6 minutes    | 0.3% | 26.90MB |
| restapps                  | 64377 | online | 0        | 31 minutes, 4 seconds | 0%   | 41.75MB |
+---------------------------+-------+--------+----------+-----------------------+------+---------+
`

**Comment by tpimont** [comment]
fwconsole pm2 --list
+--------------+--------+--------+----------+--------------------+------+---------+
| Process Name | PID    | Status | Restarts | Uptime             | CPU  | Mem     |
+--------------+--------+--------+----------+--------------------+------+---------+
| core-fastagi | 143001 | online | 0        | 1 hour, 29 minutes | 0.1% | 59.96MB |
+--------------+--------+--------+----------+--------------------+------+---------+

**Comment by ramarajan222** [comment]
Hi @tpimont,
 On my test system it's working fine and was able to reproduce this issue only when I stopped the fastagi service. Maybe can you try to restart the fast agi and check again?
 
 `fwconsole pm2 --restart=core-fastagi`

**Comment by tpimont** [comment]
After restarting fastagi and re enable it in advanced settings it's ok, dont know why fastagi was out of service .
