### ISSUE TITLE
[bug]: Abort button not working while activating the system 

### ISSUE THREAD

**Issue by Akarsh04** [FreePBX/issue-tracker#170]
### FreePBX Version

FreePBX 17

### Issue Description

Abort button is not working until the email is entered while activating the system
![image](https://github.com/FreePBX/issue-tracker/assets/36078063/1a1ffdb7-ba92-447f-ab84-fecae27f0128)

### Operating Environment

Debian 12

**Comment by kapilgupta01** [comment]
fix has been published to the production.
