### ISSUE TITLE
[improvement]: set inet_interfaces = 127.0.0.1 in postfix main.cf

### ISSUE THREAD

**Issue by dolesec** [FreePBX/issue-tracker#172]
### FreePBX Version

FreePBX 17

### Improvement Description

this seems like a good security measure for the majority of the community who will be installing 17 as it prevents external access to postfix and still allows the PBX system to send mail which is the primary use case - not a publicly accessible mail service. 

add a notation in email setup that this is present and a warning to  only change this is you know what you are doing

![Screenshot 2024-05-18 at 4 58 35 PM](https://github.com/FreePBX/issue-tracker/assets/2153999/32fb73c8-a681-4d2d-815c-00972d2c3c17)

**Comment by kapilgupta01** [comment]
updated the install script to take care of this setting. Any new install will have this new configuration. Thanks
