### ISSUE TITLE
[bug]: SNOM D865 tftp/http file generation hardcodes the mac address in the generic file causing all phones to attempt to register to the same extension

### ISSUE THREAD

**Issue by a197k** [FreePBX/issue-tracker#173]
### FreePBX Version

FreePBX 16

### Issue Description

When provisioning Snom D865 phones, I came across a bug where the generic file 'snomD865.htm' hardcodes the mac address of the last extension that was mapped in endpoint manager.

FreePBX still created the mac specific file e.g. snomM900-000413AAAAAA.htm but the phone on boot looks at a different file because of the generic config that is created, hardcoding the mac. 

This is what the snomD865.htm file looks like in tftpboot when using "save and rebuild config":

```
[root@freepbx tftpboot]# cat snomD865.htm
```

```
<!--# Created on 2024/05/20 12:30:53
#Configuration automatically generated via the EndPoint Module 
#DO NOT HAND MODIFY THIS FILE!--> 

<?xml version="1.0" encoding="utf-8"?>
<setting-files>
<file url="tftp://192.168.0.1/snomD865-000413BBBBBB.htm"/>
</setting-files>
```

Due to this bug, this causes all phones to try to register using the mac file snomD865-000413BBBBBB.htm

### Operating Environment

FreePBX 16.0.40.7
Asterisk 16.29.1
Reproduced on EndPoint manager versions 16.0.86.15 and 16.0.86.11

**Comment by jissphilip** [comment]
endpoint-16.0.86.21
endpoint-17.0.1.63

**Comment by kguptasangoma** [comment]
endpoint v16.0.86.21
