### ISSUE TITLE
[bug]: Unable to install Firewall module "Missing Requirements:	 The File "/usr/lib/sysadmin/includes.php" must exist" 

### ISSUE THREAD

**Issue by msanthosh18** [FreePBX/issue-tracker#175]
### FreePBX Version

FreePBX 17

### Issue Description

Unable to install Firewall module on Tarball installation with open source modules 

### Operating Environment

Deb 12.5

![image](https://github.com/FreePBX/issue-tracker/assets/159993744/004718f8-9412-4baa-a99e-57e71cebf459)

**Comment by prashobkarimbil** [comment]
firewall module needs sysadmin deb package.
