### ISSUE TITLE
[bug]: Voicemail Blasting

### ISSUE THREAD

**Issue by derekcrpd** [FreePBX/issue-tracker#177]
### FreePBX Version

FreePBX 17

### Issue Description

Voicemail blasting does not appear to be functioning correctly, specifically within the IVR module. If I create a new voicemail blast within the Voicemail Blast module and then attempt to use it within the IVR module, it attempts to create another VM Blast, as if one doesn't already exist. After it creates this new one in the IVR module, it remains unable to find a valid VM Blast setup. 

### Operating Environment

Brand new install of FreePBX 17, Asterisk 21:
+-------------------+------------+---------+------------+-----------+
| Module            | Version    | Status  | License    | Signature |
+-------------------+------------+---------+------------+-----------+
| amd               | 17.0.1     | Enabled | GPLv3+     | Sangoma   |
| announcement      | 17.0.2.1   | Enabled | GPLv3+     | Sangoma   |
| api               | 17.0.1.1   | Enabled | AGPLv3+    | Sangoma   |
| arimanager        | 17.0.1.1   | Enabled | GPLv3+     | Sangoma   |
| asterisk-cli      | 17.0.2     | Enabled | GPLv3+     | Sangoma   |
| asteriskinfo      | 17.0.1     | Enabled | GPLv3+     | Sangoma   |
| backup            | 17.0.5.27  | Enabled | GPLv3+     | Sangoma   |
| blacklist         | 17.0.1.2   | Enabled | GPLv3+     | Sangoma   |
| builtin           |            | Enabled |            | Unsigned  |
| bulkhandler       | 17.0.4     | Enabled | GPLv3+     | Sangoma   |
| calendar          | 17.0.4.11  | Enabled | GPLv3+     | Sangoma   |
| callback          | 17.0.2.1   | Enabled | GPLv3+     | Sangoma   |
| callforward       | 17.0.1.3   | Enabled | AGPLv3+    | Sangoma   |
| callrecording     | 17.0.3.6   | Enabled | AGPLv3+    | Sangoma   |
| callwaiting       | 17.0.3.2   | Enabled | GPLv3+     | Sangoma   |
| cdr               | 17.0.4.13  | Enabled | GPLv3+     | Sangoma   |
| cel               | 17.0.2.7   | Enabled | GPLv3+     | Sangoma   |
| certman           | 17.0.3.10  | Enabled | AGPLv3+    | Sangoma   |
| cidlookup         | 17.0.1.1   | Enabled | GPLv3+     | Sangoma   |
| conferences       | 17.0.3.1   | Enabled | GPLv3+     | Sangoma   |
| configedit        | 17.0.1.1   | Enabled | AGPLv3+    | Sangoma   |
| contactmanager    | 17.0.5.8   | Enabled | GPLv3+     | Sangoma   |
| core              | 17.0.9.52  | Enabled | GPLv3+     | Sangoma   |
| customappsreg     | 17.0.1     | Enabled | GPLv3+     | Sangoma   |
| dashboard         | 17.0.4.2   | Enabled | AGPLv3+    | Sangoma   |
| daynight          | 17.0.1.1   | Enabled | GPLv3+     | Sangoma   |
| dictate           | 17.0.1.2   | Enabled | GPLv3+     | Sangoma   |
| directory         | 17.0.1.1   | Enabled | GPLv3+     | Sangoma   |
| donotdisturb      | 17.0.2.1   | Enabled | GPLv3+     | Sangoma   |
| dynroute          | 17.0.3     | Enabled | GPLv3+     | Sangoma   |
| extensionsettings | 17.0.1     | Enabled | GPLv3+     | Sangoma   |
| fax               | 17.0.3.2   | Enabled | GPLv3+     | Sangoma   |
| featurecodeadmin  | 17.0.2     | Enabled | GPLv3+     | Sangoma   |
| filestore         | 17.0.2.11  | Enabled | AGPLv3     | Sangoma   |
| findmefollow      | 17.0.4.6   | Enabled | GPLv3+     | Sangoma   |
| firewall          | 17.0.1.24  | Enabled | AGPLv3+    | Sangoma   |
| framework         | 17.0.15.21 | Enabled | GPLv2+     | Sangoma   |
| hotelwakeup       | 17.0.1.5   | Enabled | GPLv2      | Sangoma   |
| iaxsettings       | 17.0.1     | Enabled | AGPLv3     | Sangoma   |
| infoservices      | 17.0.1     | Enabled | GPLv2+     | Sangoma   |
| ivr               | 17.0.6     | Enabled | GPLv3+     | Sangoma   |
| languages         | 17.0.1     | Enabled | GPLv3+     | Sangoma   |
| logfiles          | 17.0.3.1   | Enabled | GPLv3+     | Sangoma   |
| manager           | 17.0.5     | Enabled | GPLv2+     | Sangoma   |
| miscapps          | 17.0.3     | Enabled | GPLv3+     | Sangoma   |
| miscdests         | 17.0.1.1   | Enabled | GPLv3+     | Sangoma   |
| music             | 17.0.4     | Enabled | GPLv3+     | Sangoma   |
| outroutemsg       | 17.0.1     | Enabled | GPLv3+     | Sangoma   |
| paging            | 17.0.3     | Enabled | GPLv3+     | Sangoma   |
| parking           | 17.0.2.3   | Enabled | GPLv3+     | Sangoma   |
| phpinfo           | 17.0.1     | Enabled | GPLv2+     | Sangoma   |
| pinsets           | 17.0.3.1   | Enabled | GPLv3+     | Sangoma   |
| pm2               | 17.0.3.2   | Enabled | AGPLv3+    | Sangoma   |
| presencestate     | 17.0.2.1   | Enabled | GPLv3+     | Sangoma   |
| printextensions   | 17.0.1.2   | Enabled | GPLv3+     | Sangoma   |
| queueprio         | 17.0.1.4   | Enabled | GPLv3+     | Sangoma   |
| queues            | 17.0.1.8   | Enabled | GPLv2+     | Sangoma   |
| recordings        | 17.0.2.2   | Enabled | GPLv3+     | Sangoma   |
| ringgroups        | 17.0.2.4   | Enabled | GPLv3+     | Sangoma   |
| setcid            | 17.0.1.2   | Enabled | GPLv3+     | Sangoma   |
| sipsettings       | 17.0.6.7   | Enabled | AGPLv3+    | Sangoma   |
| soundlang         | 17.0.4.1   | Enabled | GPLv3+     | Sangoma   |
| sysadmin          | 17.0.1.80  | Enabled | Commercial | Sangoma   |
| timeconditions    | 17.0.1.15  | Enabled | GPLv3+     | Sangoma   |
| tts               | 17.0.1.1   | Enabled | GPLv3+     | Sangoma   |
| ttsengines        | 17.0.1     | Enabled | AGPLv3     | Sangoma   |
| ucp               | 17.0.4.14  | Enabled | AGPLv3+    | Sangoma   |
| userman           | 17.0.6.21  | Enabled | AGPLv3+    | Sangoma   |
| vmblast           | 17.0.1     | Enabled | GPLv3+     | Sangoma   |
| voicemail         | 17.0.5.15  | Enabled | GPLv3+     | Sangoma   |
| weakpasswords     | 17.0.1     | Enabled | GPLv3+     | Sangoma   |
| webrtc            | 17.0.2.1   | Enabled | GPLv3+     | Sangoma   |
+-------------------+------------+---------+------------+-----------+

### Relevant log output

```shell
N/A
```

**Comment by jissphilip** [comment]
Hi @derekcrpd  We have released the version  vmblast-17.0.2

Please install it and try

**Comment by derekcrpd** [comment]
Works perfectly, thank you.
