### ISSUE TITLE
Freepbx17 : filestore locations not visible in backup

### ISSUE THREAD

**Issue by Andsup** [FreePBX/issue-tracker#178]
### FreePBX Version

FreePBX 17

### Issue Description

Freepbx17 : filestore locations not visible in backup

some locations are defined in file "Store screen"

![image](https://github.com/FreePBX/issue-tracker/assets/21259340/369ffffb-7383-49d9-85c8-fa64fd8c7fb1)

but not visible in the backup screen : 

![image](https://github.com/FreePBX/issue-tracker/assets/21259340/389ed6c1-ff30-4c32-9434-b5efed9ede84)

Workaround: set all items enabled

### Operating Environment

.

**Comment by dolesec** [comment]
good catch @Andsup  , ive only ever had on local destination ...

**Comment by kapilgupta01** [comment]
filestore v17.0.2.12
