### ISSUE TITLE
 Add UI option to show chan_sip to pjsip conversion for Asterisk 21

### ISSUE THREAD

**Issue by kapilgupta01** [FreePBX/issue-tracker#179]
### FreePBX Version

FreePBX 17

### Issue Description

If we are running asterisk 21 then only - If we find the backup file has chan_sip ext or chan_sip trunks then give a pop-up to the user to ask - 

"Attention: The backup file contains legacy chan_sip extensions or trunks, which are not compatible with Asterisk 21. You have the option to proceed, in which case these legacy extensions or trunks will be converted to PJSIP. Alternatively, you can cancel the restore process and downgrade the Asterisk version first, then attempt to restore your backup." 
 
 On Continue - > convert to pjsip and restore, 
 On Cancel - terminate the restore process. 

### Operating Environment

Debian 12

### Relevant log output

```shell
NA
```

**Comment by jissphilip** [comment]
core-17.0.9.60
