### ISSUE TITLE
[improvement]: Add a installation option to install only Dahdi packages 

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#181]
### FreePBX Version

FreePBX 17

### Improvement Description

Hi Team,

I am running FreePBX V17 and I want to add a DAHDI (PRI) card to it. However, I do not see any option to install only the DAHDI and its related packages. When I run the script with "--dahdi," it performs a full installation.

We need to add an installation option like "--install dahdi only" to install only the DAHDI and related packages.

**Comment by kapilgupta01** [comment]
done. please refer to the latest script.
