### ISSUE TITLE
[improvement]: installation Script fails when CDROM repo added.

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#182]
### FreePBX Version

FreePBX 17

### Improvement Description

The apt-update fails when the system has the CD-ROM repo added.

We need to add a check in the installation script: if the CD-ROM is present in the repo list, then we need to remove or comment it out to run the installation script successfully.

`root@sangoma:/etc/apt# bash /tmp/sng_freepbx_debian_install.sh
Performing version check...
Perfect! You're already running the latest version.
2024-05-24 04:26:20 - Starting installation.
2024-05-24 04:26:20 -   Starting FreePBX 17 installation process for sangoma Linux sangoma 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
2024-05-24 04:26:20 -   Please refer to the /var/log/pbx/freepbx17-install-2024.05.24-04.26.18.log to know the process...
2024-05-24 04:26:20 - Making sure installation is same
2024-05-24 04:26:27 - Installation failed at step Making sure installation is same. Please check log /var/log/pbx/freepbx17-install-2024.05.24-04.26.18.log for details.
2024-05-24 04:26:27 - Error at line: 625 exiting with code 100 (last command was: apt update >> $log 2>&1)
2024-05-24 04:26:27 - Exiting script
root@sangoma:/etc/apt# cat sources.list
deb cdrom:[Debian GNU/Linux 12.0.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20230610-10:23]/ bookworm main non-free-firmware

deb http://deb.debian.org/debian/ bookworm main non-free-firmware
deb-src http://deb.debian.org/debian/ bookworm main non-free-firmware

deb http://security.debian.org/debian-security bookworm-security main non-free-firmware
deb-src http://security.debian.org/debian-security bookworm-security main non-free-firmware

# bookworm-updates, to get updates before a point release is made;
# see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
deb http://deb.debian.org/debian/ bookworm-updates main non-free-firmware
deb-src http://deb.debian.org/debian/ bookworm-updates main non-free-firmware
root@sangoma:/etc/apt# apt update
Ign:1 cdrom://[Debian GNU/Linux 12.0.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20230610-10:23] bookworm InRelease
Err:2 cdrom://[Debian GNU/Linux 12.0.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20230610-10:23] bookworm Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 http://deb.debian.org/debian bookworm InRelease
Hit:4 http://security.debian.org/debian-security bookworm-security InRelease
Hit:5 http://deb.debian.org/debian bookworm-updates InRelease
Reading package lists... Done
E: The repository 'cdrom://[Debian GNU/Linux 12.0.0 _Bookworm_ - Official amd64 DVD Binary-1 with firmware 20230610-10:23] bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by kapilgupta01** [comment]
done. please refer to the latest script.
