### ISSUE TITLE
[bug]: Invalid ICAL data format using Cpanel Calendar 

### ISSUE THREAD

**Issue by Shane8johnson** [FreePBX/issue-tracker#184]
### FreePBX Version

FreePBX 16

### Issue Description

Trying to add a **CalDav calendar** that is hosted on a CPanel Account. I am able to enter all login information and freepbx even shows it's found one calendar. However, once you press submit, it throws an error "Invalid ICAL data format". I don't know much about internet calender sharing, but I assume that ICAL and CalDav are two different calendar types? I am not sure why it would throw an ICAL error when I am adding a CalDav Calendar. 
![caldavfreepbx](https://github.com/FreePBX/issue-tracker/assets/36906111/25e333a9-6445-49dc-86a1-e4d710b24e45)
![caldavfreepbx-error](https://github.com/FreePBX/issue-tracker/assets/36906111/b15ac7ca-4b0f-4dbe-a9fc-50def96e959e)

### Operating Environment

"name": "calendar",
 "state": "Enabled",
 "version": "16.0.29",
name": "framework",
"version": "16.0.40.7",
"name": "core",
"version": "16.0.68.26",
Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.16 
PBXACT Version 12.7.8-2306-1.sng

### Relevant log output

```shell
InvalidArgumentException thrown with message "Invalid ICAL data format"

Stacktrace:
#10 InvalidArgumentException in /var/www/html/admin/modules/calendar/vendor/om/icalparser/src/IcalParser.php:65
#9 om\IcalParser:parseString in /var/www/html/admin/modules/calendar/drivers/Base.php:209
#8 FreePBX\modules\Calendar\drivers\Base:buildCache in /var/www/html/admin/modules/calendar/drivers/Base.php:186
#7 FreePBX\modules\Calendar\drivers\Base:saveiCal in /var/www/html/admin/modules/calendar/drivers/Caldav.php:120
#6 FreePBX\modules\Calendar\drivers\Caldav:processCalendar in /var/www/html/admin/modules/calendar/drivers/Caldav.php:81
#5 FreePBX\modules\Calendar\drivers\Caldav:updateCalendar in /var/www/html/admin/modules/calendar/drivers/Base.php:78
#4 FreePBX\modules\Calendar\drivers\Base:addCalendar in /var/www/html/admin/modules/calendar/Calendar.class.php:181
#3 FreePBX\modules\Calendar:getDriverByAdd in /var/www/html/admin/modules/calendar/Calendar.class.php:72
#2 FreePBX\modules\Calendar:doConfigPageInit in /var/www/html/admin/libraries/BMO/GuiHooks.class.php:291
#1 FreePBX\GuiHooks:doBMOConfigPage in /var/www/html/admin/libraries/BMO/GuiHooks.class.php:252
#0 FreePBX\GuiHooks:doConfigPageInits in /var/www/html/admin/config.php:449
```

**Comment by kapilgupta01** [comment]
Hi @Shane8johnson We are not able to reproduce the issue, can you please raise support ticket so we can ssh to your system to debug this issue further ?
If you have already raised the support ticket then please share the case number.

Thanks
Kapil

**Comment by Shane8johnson** [comment]
Case #01667333 And replied to support with detailed steps to re-create and with test credentials.

**Comment by kapilgupta01** [comment]
thanks @Shane8johnson . I will check internally.

**Comment by jissphilip** [comment]
calendar version 16.0.32
