### ISSUE TITLE
[bug]: Update ffmpeg Package in FreePBX Repository

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#186]
### FreePBX Version

FreePBX 17

### Issue Description

Ref ==>[1 updates could not be installed automatically](https://community.freepbx.org/t/1-updates-could-not-be-installed-automatically/96776) 

The latest version of FFmpeg is available from the Debian repository. Currently, the FreePBX 17 system has installed the FFmpeg package from the FreePBX repository with higher priority, causing the unattended upgrade to place the FFmpeg package in the 'kept back' file.

Build the latest FFmpeg and release it from the FreePBX repository.

https://ffmpeg.org/releases/

`Package ffmpeg has a higher version available, checking if it is from an allowed origin and is not pinned down.
Package ffmpeg is kept back because a related package is kept back or due to local apt_preferences(5).`

### Operating Environment

FreepbX 17``

### Relevant log output

```shell
apt-cache policy ffmpeg
ffmpeg:
  Installed: 5.1.4-8.sng12
  Candidate: 5.1.4-8.sng12
  Version table:
     7:5.1.4-0+deb12u1 500
        500 https://deb.debian.org/debian bookworm/main amd64 Packages
        500 https://deb.debian.org/debian-security bookworm-security/main amd64 Packages
        500 https://debian.mirror.constant.com bookworm/main amd64 Packages
        500 http://ftp.debian.org/debian stable/main amd64 Packages
 *** 5.1.4-8.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
     5.1.4-7.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-6.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-5.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-3.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
```

**Comment by push143smart** [comment]
Hi @ramarajan222 ,

This is an anticipated occurrence.
The FFmpeg module utilized by FreePBX is based on version 5.4.1, which is derived from the same source code as the debian latest 5.4.1.0 ffmpeg package. 
You can find the ffmpeg source code at the following link:
https://ffmpeg.org/releases/ffmpeg-5.1.4.tar.bz2

**Debian Link:**
https://packages.debian.org/source/stable/ffmpeg.

Executing the unattended-upgrade command will ensure that Debian forcefully pulls the module update list from the Debian Security branch.

The issue experienced by the user is due to the ffmpeg module name version change in Debian compared to the ffmpeg version installed by FreePBX. 

We would suggest against using the ffmpeg modules provided by Debian since there is no difference between the FreePBX repository's ffmpeg module and the one provided by Debian.

**Comment by hknet** [comment]
well, this comes up again as debian is now offering v5.1.6:

apt-cache policy ffmpeg
ffmpeg:
  Installed: 5.1.4-10.sng12
  Candidate: 5.1.4-10.sng12
  Version table:
     7:5.1.6-0+deb12u1 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        500 http://security.debian.org bookworm-security/main amd64 Packages
        500 http://ftp.debian.org/debian stable/main amd64 Packages
 *** 5.1.4-10.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by hknet** [comment]
How could we get this re-evaluated - "won't fix" is sub-optimal as there has been an ffmpeg security update provided by debian...

**Comment by kapilgupta01** [comment]
Hi @hknet yes we do have plan to upgrade freepbx ffmpeg to bring that to latest version, its in our queue as of now so no ETA as such.

**Comment by hknet** [comment]
Dear @kguptasangoma thx for your feedback!
Is there a specific reason why the debian security-update would not be advised to use or could it even break something?

**Comment by ramarajan222** [comment]
We have updated the ffmpeg package and released it in the FreePBX repo.

You can update it using the following commands:


```
apt update 
apt install ffmpeg
```

```
apt-cache policy ffmpeg
ffmpeg:
  Installed: 5.1.6-12.sng12
  Candidate: 5.1.6-12.sng12
  Version table:
     7:5.1.6-0+deb12u1 500
        500 https://deb.debian.org/debian bookworm/main amd64 Packages
        500 https://deb.debian.org/debian-security bookworm-security/main amd64 Packages
        500 https://debian.mirror.constant.com bookworm/main amd64 Packages
        500 http://ftp.debian.org/debian stable/main amd64 Packages
 *** 5.1.6-12.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
     5.1.4-10.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-9.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-8.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-7.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-6.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-5.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-3.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages



```
