### ISSUE TITLE
Sometimes, local directory filestore not showing in modules like backup, cdrpro

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#187]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

Local directory of filestore is not showing up in modules like cdrpro, backup even though local directory is present in filestore module.

filestore v17.0.2.13

Attaching screen-shots for reference.

cdrpro 
![image](https://github.com/FreePBX/issue-tracker/assets/163297370/5897d66b-e821-497f-8267-ebc8db1d07a6)

backup & restore
![image](https://github.com/FreePBX/issue-tracker/assets/163297370/c9455084-f582-4d7b-913d-58dc6f106ecf)

Filestore
![image](https://github.com/FreePBX/issue-tracker/assets/163297370/61e5ba0f-5acd-47eb-ba9d-73b2132f8791)

Thanks

### Operating Environment

root@sangoma:~# fwconsole ma list | grep filest
| filestore         | 17.0.2.13  | Enabled | AGPLv3      | Sangoma   |

### Relevant log output

```shell
.
```

**Comment by jissphilip** [comment]
filestore 17.0.2.14

**Comment by jissphilip** [comment]
Fix Version  filestore 17.0.2.14
