### ISSUE TITLE
[bug]: "Dahdi Config" Module php exeception

### ISSUE THREAD

**Issue by stefanodemartini** [FreePBX/issue-tracker#188]
### FreePBX Version

FreePBX 17

### Issue Description

Trying to access the "Dahdi Config" Module the following php exeception is thrown:

`Whoops \ Exception \ ErrorException (E_WARNING)
Undefined array key 32`
`Whoops\Exception\ErrorException 
/var/www/html/admin/modules/dahdiconfig/includes/dahdi_cards.class.php509`

### Operating Environment

Debian GNU/Linux 12 (bookworm)
FreePBX Version 17.0.15.21
Asterisk Version: 21.0.2
Dahdi version:  3.2.0
PHP Version 8.2.19
Hardware Xorcom Astribank

**Comment by kapilgupta01** [comment]
can you please share full screenshot ?

**Comment by kapilgupta01** [comment]
also please ensure you have dahdiconfig 17.0.1.7 module version. thanks

**Comment by stefanodemartini** [comment]
Of course
Yes, the module is that version

![image](https://github.com/FreePBX/issue-tracker/assets/31214217/80239f6c-d752-452b-9101-348dc4fea960)

**Comment by stefanodemartini** [comment]
![image](https://github.com/FreePBX/issue-tracker/assets/31214217/8fab59ea-24ac-4742-9194-d1d348e363db)

**Comment by jissphilip** [comment]
dahdiconfig version 17.0.1.8
