### ISSUE TITLE
[bug]: Exception with count() when trying to add Phonebook in Digium Phones module.

### ISSUE THREAD

**Issue by mule007** [FreePBX/issue-tracker#190]
### FreePBX Version

FreePBX 16

### Issue Description

I attempted to add a new phonebook in the Digium Phones module. Originally the only phonebook in use was the Internal phonebook. When I created the new phonebook it threw another exception which unfortunately I did not document. Whenever I try to go back to Phone Books in the Digium Phones configuration now I get the following:

```
Whoops\Exception\ErrorException thrown with message "count(): Parameter must be an array or an object that implements Countable"

Stacktrace:
#3 Whoops\Exception\ErrorException in /var/www/html/admin/modules/digium_phones/views/digium_phones_phonebooks.php:140
#2 Whoops\Run:handleError in /var/www/html/admin/modules/digium_phones/views/digium_phones_phonebooks.php:140
#1 require in /var/www/html/admin/modules/digium_phones/page.digium_phones.php:920
#0 include in /var/www/html/admin/config.php:658
```

I noticed that it did create a contacts-1.xml file in /var/www/html/digium_phones
with the following contents:

```
<?xml version="1.0"?>
<contacts group_name="CJS" editable="0" id="2984"/>
```

CJS is the name I gave the new phone book I was attempting to create. But now I am unable to see any of the phonebooks and make any changes, as trying to go to the phonebooks section throws the above error.

I've tried deleting the contacts-1 and contacts-internal.xml files, replacing them with different phonebooks from other hosts, restarting, but no luck.

Thank you!

![image](https://github.com/FreePBX/issue-tracker/assets/53348388/5b0057da-e44c-4ce7-936a-f522e9706e18)

### Operating Environment

Framework 16.0.40.7
Asterisk 20.5.2
FreePBX CentOS distro

+----------------------+------------+-----------------------------------+-------------+-----------+
| Module               | Version    | Status                            | License     | Signature |
+----------------------+------------+-----------------------------------+-------------+-----------+
| accountcodepreserve  | 16.0.0.1   | Enabled                           | GPLv2       | Sangoma   |
| adv_recovery         |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| allowlist            |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| amd                  | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| announcement         | 16.0.7     | Enabled                           | GPLv3+      | Sangoma   |
| api                  | 16.0.13    | Enabled                           | AGPLv3+     | Sangoma   |
| areminder            |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| arimanager           | 16.0.13    | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli         | 16.0.8     | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo         | 16.0.10    | Enabled                           | GPLv3+      | Sangoma   |
| backup               | 16.0.69    | Enabled                           | GPLv3+      | Sangoma   |
| blacklist            | 16.0.21    | Enabled                           | GPLv3+      | Sangoma   |
| broadcast            |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| builtin              |            | Enabled                           |             | Unsigned  |
| bulkdids             |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| bulkextensions       |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| bulkhandler          | 16.0.16    | Enabled                           | GPLv3+      | Sangoma   |
| calendar             | 16.0.29    | Enabled                           | GPLv3+      | Sangoma   |
| callaccounting       |            | Not Installed (Locally available) | Commercial+ | Sangoma   |
| callback             | 16.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| callerid             |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| callforward          | 16.0.5     | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit            |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| callrecording        | 16.0.21    | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting          | 16.0.5     | Enabled                           | GPLv3+      | Sangoma   |
| campon               |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| cdr                  | 16.0.46.8  | Enabled                           | GPLv3+      | Sangoma   |
| cel                  | 16.0.20    | Enabled                           | GPLv3+      | Sangoma   |
| certman              | 16.0.22    | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup            | 16.0.16    | Enabled                           | GPLv3+      | Sangoma   |
| cloudmigration       |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| conferences          | 16.0.9     | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro       |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| configedit           | 16.0.5     | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager       | 16.0.26    | Enabled                           | GPLv3+      | Sangoma   |
| core                 | 16.0.68.20 | Enabled                           | GPLv3+      | Sangoma   |
| cos                  |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| customappsreg        | 16.0.5     | Enabled                           | GPLv3+      | Sangoma   |
| customcontexts       | 13.0.3.2   | Enabled                           | GPLv2+      | Sangoma   |
| cxpanel              |            | Not Installed (Locally available) | GPLv3       | Sangoma   |
| dahdiconfig          | 16.0.9     | Enabled                           | GPLv3+      | Sangoma   |
| dashboard            | 16.0.21    | Enabled                           | AGPLv3+     | Sangoma   |
| daynight             | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| dictate              | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| digium_phones        | 15.0.12    | Enabled                           | GPLv2       | Sangoma   |
| digiumaddoninstaller |            | Not Installed (Locally available) | GPLv2       | Sangoma   |
| directory            | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| disa                 |            | Not Installed (Locally available) | AGPLv3+     | Sangoma   |
| donotdisturb         | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| dundicheck           |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| dynroute             |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| endpoint             | 16.0.86.15 | Enabled                           | Commercial  | Sangoma   |
| extensionroutes      | 16.0.8     | Enabled                           | Commercial  | Sangoma   |
| extensionsettings    | 16.0.5     | Enabled                           | GPLv3+      | Sangoma   |
| fax                  | 16.0.13    | Enabled                           | GPLv3+      | Sangoma   |
| faxpro               |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| featurecodeadmin     | 16.0.11    | Enabled                           | GPLv3+      | Sangoma   |
| filestore            | 16.0.18    | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow         | 16.0.23    | Enabled                           | GPLv3+      | Sangoma   |
| firewall             | 16.0.57.6  | Enabled                           | AGPLv3+     | Sangoma   |
| framework            | 16.0.40.7  | Enabled                           | GPLv2+      | Sangoma   |
| freepbx_ha           |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| fw_langpacks         | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| hotelwakeup          |            | Not Installed (Locally available) | GPLv2       | Sangoma   |
| iaxsettings          | 16.0.4     | Enabled                           | AGPLv3      | Sangoma   |
| infoservices         | 16.0.2     | Enabled                           | GPLv2+      | Sangoma   |
| iotserver            |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| irc                  | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| ivr                  | 16.0.9     | Enabled                           | GPLv3+      | Sangoma   |
| languages            | 16.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| logfiles             | 16.0.7     | Enabled                           | GPLv3+      | Sangoma   |
| manager              | 16.0.23    | Enabled                           | GPLv2+      | Sangoma   |
| miscapps             | 16.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| miscdests            | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| missedcall           |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| motif                |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| music                | 16.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| oracle_connector     |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| outcnam              |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| outroutemsg          | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| paging               | 16.0.13    | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro            |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| parking              | 16.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| parkpro              |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| pbdirectory          |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| pbxmfa               |            | Not Installed (Locally available) | Commercial+ | Sangoma   |
| phonebook            | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| phpagiconf           | 2.11.0.2   | Enabled                           | GPLv3+      | Sangoma   |
| phpinfo              | 16.0.1     | Enabled                           | GPLv2+      | Sangoma   |
| pinsets              | 16.0.8     | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro           |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| pm2                  | 16.0.8     | Enabled                           | AGPLv3+     | Sangoma   |
| pms                  |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| presencestate        | 16.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| printextensions      | 16.0.8     | Enabled                           | GPLv3+      | Sangoma   |
| queuemetrics         |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| queueprio            |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| queues               | 16.0.27    | Enabled                           | GPLv2+      | Sangoma   |
| queuestats           |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| qxact_reports        |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| recording_report     |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| recordings           | 16.0.16    | Enabled                           | GPLv3+      | Sangoma   |
| restapi              |            | Not Installed (Locally available) | AGPLv3      | Sangoma   |
| restapps             | 16.0.36.8  | Enabled                           | Commercial  | Sangoma   |
| ringgroups           | 16.0.11    | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect       |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| sangomacrm           |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| sangomartapi         |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| setcid               | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings          | 16.0.27    | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation           |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| sms                  | 16.0.25    | Enabled                           | Commercial  | Sangoma   |
| smsplus              |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| soundlang            | 16.0.9     | Enabled                           | GPLv3+      | Sangoma   |
| superfecta           | 16.0.29    | Enabled                           | GPLv2+      | Sangoma   |
| synologyabb          |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| sysadmin             | 16.0.41.22 | Enabled                           | Commercial  | Sangoma   |
| timeconditions       | 16.0.11    | Enabled                           | GPLv3+      | Sangoma   |
| tts                  | 16.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines           | 16.0.3     | Enabled                           | AGPLv3      | Sangoma   |
| ucp                  | 16.0.38.1  | Enabled                           | AGPLv3+     | Sangoma   |
| userman              | 16.0.44.6  | Enabled                           | AGPLv3+     | Sangoma   |
| vega                 |            | Not Installed (Locally available) | Commercial+ | Sangoma   |
| vmblast              |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| vmnotify             |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| voicemail            | 16.0.53    | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report     |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| voipinnovations      |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| vqplus               |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| weakpasswords        | 16.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| webcallback          |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| webrtc               |            | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| xmpp                 |            | Not Installed (Locally available) | AGPLv3      | Sangoma   |
| zulu                 |            | Not Installed (Locally available) | Commercial  | Sangoma   |
+----------------------+------------+-----------------------------------+-------------+-----------+

**Comment by kapilgupta01** [comment]
Please use Endpoint manager with DPMA to configure your Dx phones. 
digium_phone is now deprecated. 

this thread can give you more idea -  https://community.freepbx.org/t/dpma-and-freepbx-16/83883/5 

Thank you for using FreePBX
Kapil
