### ISSUE TITLE
[improvement]: Add the UI option on Backup  module to upload the SSH keys 

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#192]
### FreePBX Version

FreePBX 17

### Improvement Description

Hi Team , 

Add a UI option to the backup module to upload SSH keys to the Asterisk user. This will help create the warm spare setup without requiring the user to add the key via the CLI.

![image](https://github.com/FreePBX/issue-tracker/assets/25248291/75ce1d5e-26b7-4574-91d8-e70f5c94cf99)

**Comment by jissphilip** [comment]
backup version 17.0.5.34
