### ISSUE TITLE
[bug]: Transient CDR is disabled warning in v17

### ISSUE THREAD

**Issue by msanthosh18** [FreePBX/issue-tracker#194]
### FreePBX Version

FreePBX 17

### Issue Description

After backup restore of v16 to v17 the dashboard shows "Transient CDR is disabled" 

![image](https://github.com/FreePBX/issue-tracker/assets/159993744/b13d50e1-351e-45d7-9e4c-1fe1904367bc)

### Operating Environment

Deb 12.5

**Comment by jissphilip** [comment]
cdr-15.0.24.7
cdr-16.0.46.9
cdr-17.0.4.15
