### ISSUE TITLE
Legacy backup restore conversion issue in fpbx17

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#195]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

When we restore legacy versions backup(v2, v13, v14), then chan_sip to pjsip conversion is not happening even though we have the given the setting to convert during restore options. 

Thanks

### Operating Environment

Freepbx 17, asterisk 21

**Comment by jissphilip** [comment]
core version 17.0.9.61
