### ISSUE TITLE
[bug]:  FREEPBX 17 restore from 15 error when applying config

### ISSUE THREAD

**Issue by tpimont** [FreePBX/issue-tracker#196]
### FreePBX Version

FreePBX 17

### Issue Description

Hello,
When trying to restore à backup from à 15 version the restore goes OK but when applying config

Error: Call to undefined method Monolog\Handler\NullHandler::setFormatter() in file /var/www/html/admin/libraries/BMO/Logger.class.php on line 230
Stack trace:
  1. Error->() /var/www/html/admin/libraries/BMO/Logger.class.php:230
  2. FreePBX\Logger->createLogDriver() /var/www/html/admin/libraries/BMO/Logger.class.php:135
  3. FreePBX\Logger->driverChannelLogWrite() /var/www/html/admin/libraries/BMO/Logger.class.php:108
  4. FreePBX\Logger->channelLogWrite() /var/www/html/admin/libraries/BMO/Logger.class.php:96
  5. FreePBX\Logger->logWrite() /var/www/html/admin/libraries/BMO/Logger.class.php:41
  6. FreePBX\Logger->log() /var/lib/asterisk/bin/fwconsole:137

### Operating Environment

FREEPBX 17 Asterisk 20.6 Rocky 9

### Relevant log output

```shell
Error: Call to undefined method Monolog\Handler\NullHandler::setFormatter() in file /var/www/html/admin/libraries/BMO/Logger.class.php on line 230
Stack trace:
  1. Error->() /var/www/html/admin/libraries/BMO/Logger.class.php:230
  2. FreePBX\Logger->createLogDriver() /var/www/html/admin/libraries/BMO/Logger.class.php:135
  3. FreePBX\Logger->driverChannelLogWrite() /var/www/html/admin/libraries/BMO/Logger.class.php:108
  4. FreePBX\Logger->channelLogWrite() /var/www/html/admin/libraries/BMO/Logger.class.php:96
  5. FreePBX\Logger->logWrite() /var/www/html/admin/libraries/BMO/Logger.class.php:41
  6. FreePBX\Logger->log() /var/lib/asterisk/bin/fwconsole:137
```

**Comment by kapilgupta01** [comment]
Framework v17.0.15.25
