### ISSUE TITLE
[bug]: Dashboard graph displayed not correctly

### ISSUE THREAD

**Issue by danardf** [FreePBX/issue-tracker#199]
### FreePBX Version

FreePBX 17

### Issue Description

The graph in **Live Network Usage** is not displayed correctly.
The grpah is too large.  It's overiding the other widgets.
![2024-05-30_095538](https://github.com/FreePBX/issue-tracker/assets/24569618/23095a57-2ef1-44d2-bff9-f0922d046593)

And the graph Disk Usage needs to be centered BTW. 

### Operating Environment

Dashboard **17.0.4.2**

**Comment by derekcrpd** [comment]
I notice this too on 17.0.15.27.


![6-8-2024 1-09-43 AM](https://github.com/FreePBX/issue-tracker/assets/96105567/5fe07180-bfd9-497b-93bc-1f9b0e01ccbb)

**Comment by cordeosdev** [comment]
A quick fix for this annoying little display issue is to simply adjust the CSS for the container block.  This should be added to the code base...

#netmonout {
    max-width: 75%;
}

**Comment by cordeosdev** [comment]
For anyone interested in just a quick fix before the base code is updated...
(this is NOT meant for permanent production)

```# first "su -" or "sudo su -" or add sudo [before each command]

# Create custom.css 
# at: /var/www/html/admin/assets/css

cat <<EOF > /var/www/html/admin/assets/css/custom.css
#netmonout {
    max-width: 75%;
}
EOF

chown asterisk:asterisk /var/www/html/admin/assets/css/custom.css

#mysql -u root
#use asterisk;
#UPDATE freepbx_settings SET VALUE='assets/css/custom.css' WHERE keyword='BRAND_CSS_CUSTOM';

echo "UPDATE freepbx_settings SET VALUE='assets/css/custom.css' WHERE keyword='BRAND_CSS_CUSTOM'" | mysql -u root asterisk

```

**Comment by danardf** [comment]
PR raised. https://github.com/FreePBX/dashboard/pull/14
Thanks @cordeosdev

**Comment by danardf** [comment]
@kguptasangoma Hey Kapil
Once merged. please close this issue too.

C.U later.

**Comment by danardf** [comment]
![image](https://github.com/user-attachments/assets/8e57771e-f244-4c30-a930-53070cacad48)

**Comment by kapilgupta01** [comment]
dashboard v17.0.4.6
