### ISSUE TITLE
[bug]: DISA missing in applications menu + DISA module missing / cannot download or install.

### ISSUE THREAD

**Issue by gruubar** [FreePBX/issue-tracker#200]
### FreePBX Version

FreePBX 17

### Issue Description

DISA menu and module appears to be gone from Freepbx 17. Attempts to download and install the module via fwconsole results in "retrieved module XML was empty".

I didn't see anything in wiki/deprecated modules regarding DISA so I assume it should still be here. After a test restore I get a warning about invalid DISA destinations because it is missing.

### Operating Environment

Framework 17.0.15.24, Asterisk 21 (same result with Asterisk 20)
Debian 12.5

**Comment by msanthosh18** [comment]
Module has been enabled, can you try below command to install it

"fwconsole ma downloadinstall disa"

**Comment by gruubar** [comment]
yes this worked, thank you
