### ISSUE TITLE
FreePBX 17 will not install with Asterisk-21 (using open source FreePBX)

### ISSUE THREAD

**Issue by kennesaw10** [FreePBX/issue-tracker#201]
### FreePBX Version

FreePBX 17

### Issue Description

Using the provided beta test installation instructions, I changed the installation of Asterisk from 20 to 21.  Asterisk installs and compiles fine.  However, the FreePBX-17 install script bombs out.

I originally tried the FreePBX-17 and Asterisk-20 install and that works but things fall apart if you are using Asterisk-21.  You get database not found errors, mysql does not work, PHP errors in the install script. The following had to be installed that were not included in the initial scripts:  php-xml, php-mysql

Interestingly, if install per the open source instructions for Asterisk20 and FreePBX-17, then upgrade Asterisk to Asterisk-21, things seem to work.

### Operating Environment

Debian 12, FreePBX-17 edge, Asterisk-21.3

**Comment by kapilgupta01** [comment]
[php-xml, php-mysql](https://github.com/FreePBX/sng_freepbx_debian_install/blob/master/sng_freepbx_debian_install.sh#L714)  both are the part of the initial install script.

Can you please elaborate your problem in more detail?

How did you changes asterisk to 20 from 21 and what steps you followed and the details of the issue you faced. thanks

**Comment by reraikes** [comment]
FWIW...

FreePBX 17 installs without incident here using Asterisk 21 (using my own installation script).

**Comment by kapilgupta01** [comment]
sorry @reraikes not getting your point, Are you facing any error in Freepbx 17 install (with asterisk 21) ? If yes then please share steps to reproduce the issue.
thanks

**Comment by kennesaw10** [comment]
I will spin up a fresh Debian 12 VM today and try a fresh install of Asterisk 21 and FreePPX 17 (non-SMG) install and report back.

**Comment by kennesaw10** [comment]
1.	Clean install of Debian 12.5 on Rack Nerds VM (2 GB memory)
2.	Followed the instructions from this URL: https://sangomakb.atlassian.net/wiki/spaces/FP/pages/10682545/How+to+Install+FreePBX+17+on+Debian+12+with+Asterisk+20
3.	For Asterisk install, replaced “20” with “21” to get current Asterisk-21 install.
4.	In the line of code where PHP 8.2 is installed, the apt install linux-headers failed so the rest of the command line did not run.  I removed the linux-headers part and the rest installed OK.

a.	***@***.***:/# uname -r
b.	6.1.0-9-amd64
c.	***@***.***:/# apt install linux-headers-6.1.0-9-amd64
d.	Reading package lists... Done
e.	Building dependency tree... Done
f.	Reading state information... Done
g.	E: Unable to locate package linux-headers-6.1.0-9-amd64
h.	E: Couldn't find any package by glob 'linux-headers-6.1.0-9-amd64'

5.	When running the Asterisk-21 install, this error occurred but I manually ran make menuselect to complete the install.

a.	/usr/src/asterisk-21.3.1# menuselect/menuselect  menuselect.makeopts
b.	**************************************************
c.	*** Install ncurses to use the menu interface! ***
d.	**************************************************
e.	***@***.***:/usr/src/asterisk-21.3.1# apt install ncurses
f.	Reading package lists... Done
g.	Building dependency tree... Done
h.	Reading state information... Done
i.	E: Unable to locate package ncurses

6.	After handling these errors, I now have a functioning FreePBX-17 running on Asterisk-21.3.1.

**Comment by ramarajan222** [comment]
Hi @reraikes Is there any specific reason you want to install FreePBX manually instead of using the installation script?

Can you try using the installation script and let us know how it goes?

https://github.com/FreePBX/sng_freepbx_debian_install

**Comment by reraikes** [comment]
>not getting your point, Are you facing any error in Freepbx 17 install (with asterisk 21) ? If yes then please share steps to reproduce the issue.

My point was to say that I'm NOT facing any problems installing FreePBX 17 with Asterisk 21.  I have success using either Asterisk 20 or Asterisk 21.

**Comment by kapilgupta01** [comment]
thanks for the confirmation @reraikes , will close this ticket then.

**Comment by reraikes** [comment]
>Is there any specific reason you want to install FreePBX manually instead of using the installation script?

My installation script targets Raspberry Pi's: 

https://www.dslreports.com/forum/r30661088-PBX-FreePBX-for-the-Raspberry-Pi

I don't see any evidence there is an inherent problem using Asterisk 21 (instead of Asterisk 20) with FreePBX 17.

**Comment by antoniovalenzuela** [comment]
Hi,
RPI3 Debian 12

Script "sng_freepbx_debian_install.sh"

2024-08-21 20:33:11 - Setting up folders and asterisk config
2024-08-21 20:33:11 - Installing Asterisk packages.
2024-08-21 20:33:11 - ###############################
2024-08-21 20:33:11 - Installing asterisk21 ....
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package asterisk21

**Comment by kapilgupta01** [comment]
`E: Unable to locate package asterisk21`

this is failed to find the package, are you sure our repo setup properly, check the logs please to ensure sangoma repo is configured properly

**Comment by antoniovalenzuela** [comment]
> `E: Unable to locate package asterisk21`
> 
> this is failed to find the package, are you sure our repo setup properly, check the logs please to ensure sangoma repo is configured properly

Please confirm the repo URL👍

**Comment by kapilgupta01** [comment]
https://github.com/FreePBX/sng_freepbx_debian_install/blob/master/sng_freepbx_debian_install.sh#L300-L301

**Comment by antoniovalenzuela** [comment]
> https://github.com/FreePBX/sng_freepbx_debian_install/blob/master/sng_freepbx_debian_install.sh#L300-L301

RPI needs ARM, are they available?

**Comment by antoniovalenzuela** [comment]
Solved! works perfect in RPI3

https://sangomakb.atlassian.net/wiki/spaces/FP/pages/10682545/How+to+Install+FreePBX+17+on+Debian+12+with+Asterisk+21
