### ISSUE TITLE
[bug]: Superfecta module unavailable

### ISSUE THREAD

**Issue by reraikes** [FreePBX/issue-tracker#203]
### FreePBX Version

FreePBX 17

### Issue Description

root@FreePBX:~# fwconsole ma download superfecta
No repos specified, using: [standard,extended] from last GUI settings

Downloading module 'superfecta'
The following error(s) occured:
 - Retrieved Module XML Was Empty

### Operating Environment

Framework version: 17
Asterisk version: 20

**Comment by kapilgupta01** [comment]
Can you please try below and see if this works @reraikes ?
`fwconsole ma downloadinstall superfecta --tag=17.0.1.7`

**Comment by reraikes** [comment]
That succeeds.

**Comment by kapilgupta01** [comment]
great. Can you please share output of cat /etc/sangoma/pbx-brand file?

**Comment by reraikes** [comment]
There is no '/etc/sangoma' directory.

**Comment by kapilgupta01** [comment]
okay thanks, I was suspecting the same to check our mirror settings.  We will fix this from our mirror side, meanwhile you can use tag command to continue with your testing.

Thank you for trying Freepbx 17
Kapil

**Comment by kapilgupta01** [comment]
superfecta v16.0.34
superfecta v17.0.1.8
