### ISSUE TITLE
[bug]: FreePBX 17 reload issue 

### ISSUE THREAD

**Issue by kapilgupta01** [FreePBX/issue-tracker#204]
### FreePBX Version

FreePBX 17

### Issue Description

Ref - https://community.freepbx.org/t/fpbx-17-fresh-install-getting-the-please-run-fwconsole-reload-verbose-error/96863 

Reload is failing due to below permission error - 

In Network.class.php line 113:

 [Whoops\Exception\ErrorException (2)]
  file_get_contents(/etc/network/interfaces): Failed to open stream: Permission denied

Exception trace:
  at /var/www/html/admin/modules/sysadmin/Network.class.php:113
 Whoops\Run->handleError() at n/a:n/a
 file_get_contents() at /var/www/html/admin/modules/sysadmin/Network.class.php:113
...
...

### Operating Environment

NA

**Comment by jissphilip** [comment]
sysadmin version 17.0.1.85

**Comment by microchipmatt** [comment]
Just to be clear, this bug is fixed in this version correct?: sysadmin version 17.0.1.85

**Comment by jissphilip** [comment]
@microchipmatt  Yes
