### ISSUE TITLE
Division by zero File:/var/www/html/admin/modules/dashboard/classes/PruneHistory.class.php:190

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#205]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

In dashboard, getting below error. 

`Division by zero
File:/var/www/html/admin/modules/dashboard/classes/PruneHistory.class.php:190`

Attaching screen-shot

![image](https://github.com/FreePBX/issue-tracker/assets/163297370/98e031b2-37b6-4ce6-b736-70c2176615ec)

Thanks

### Operating Environment

Fpbx 17

### Relevant log output

```shell
.
```

**Comment by kapilgupta01** [comment]
dashboard v17.0.4.3
