### ISSUE TITLE
[bug]: freepbx-17-dahdi-missing-drivers 

### ISSUE THREAD

**Issue by kapilgupta01** [FreePBX/issue-tracker#206]
### FreePBX Version

FreePBX 17

### Issue Description

ref : https://community.freepbx.org/t/freepbx-17-dahdi-missing-drivers/96868 

### Operating Environment

NA

### Relevant log output

```shell
NA
```

**Comment by jcolp** [comment]
According to the DAHDi history, support for the wct1xxp driver was removed and then subsequently (somewhat recently) added back in: https://github.com/asterisk/dahdi-linux/pull/29

Looking at the latest releases the wct1xxp is not part of 3.3.0 but is in 3.4.0-rc1

**Comment by kapilgupta01** [comment]
Hi @jcolp yes, latest beta DAHDI driver release has wct1xxp  support so we are adding that beta version to the freepbx 17 to try/test. thanks

**Comment by push143smart** [comment]
Hi @kguptasangoma ,

We developed the Dahdi rpm specific to the 3.4.0-rc1 beta release and uploaded it to the stable repository.

After testing on Debian 12.5, we can verify that the wct1xxx driver is now available.

Customers can go ahead and use the FreePBX install to update the dahdi respective rpms.

Best Regards,
Pushkar
