### ISSUE TITLE
[bug]: Whoops\\Exception\\ErrorException","message":"Creation of dynamic property superfecta_single::$scheme_name is deprecated"

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#209]
### FreePBX Version

FreePBX 17

### Issue Description

Getting below error when running superfecta Debug/Test Run Scheme .

`{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Creation of dynamic property superfecta_single::$scheme_name is deprecated","code":8192,"file":"\/var\/www\/html\/admin\/modules\/superfecta\/includes\/processors\/superfecta_single.php","line":14}}`

### Operating Environment

Freepbx `17```

### Relevant log output

```shell
{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Creation of dynamic property superfecta_single::$scheme_name is deprecated","code":8192,"file":"\/var\/www\/html\/admin\/modules\/superfecta\/includes\/processors\/superfecta_single.php","line":14}}
```

**Comment by ramarajan222** [comment]
`fwconsole ma list | grep superfecta
| superfecta        | 17.0.1.8   | Enabled | GPLv2+      | Sangoma   |`

**Comment by girishmani1992** [comment]
Hi,

Superfecta related issue screen-shots

When trying to edit existing superfecta scheme, getting this error 
![image](https://github.com/FreePBX/issue-tracker/assets/163297370/e4cd84fc-6f89-45b3-a30e-79342a75d486)

When I try to debug/test scheme, entered the number, I’m getting below error.
![image](https://github.com/FreePBX/issue-tracker/assets/163297370/6a5202d5-2449-4dbc-b7b9-b67b1a37f1b0)


Thanks

**Comment by kennesaw10** [comment]
Same issue here.  No matter which provider(s) you choose for CID Superfecta, the whoops error occurs.

**Comment by kapilgupta01** [comment]
superfecta v17.0.1.9

**Comment by kapilgupta01** [comment]
hi @kennesaw10 please try with the latest superfecta 
superfecta v17.0.1.9
