### ISSUE TITLE
Where there is only a single certificate in certman, automatically make it the default.

### ISSUE THREAD

**Issue by lgaetz** [FreePBX/issue-tracker#210]
### FreePBX Version

FreePBX 17

### Improvement Description

From a fresh 17 install, I immediately deleted the existing self signed cert. After that, I created a new LE cert. Even though there was only a single cert showing, I still have to manually set the default flag to make this cert system default. It would be better if there is only a single cert in certman, that it be set to default automatically.

**Comment by prasanthcode4** [comment]
certman version 17.0.3.12
