### ISSUE TITLE
The Phonebook module does not appear in FreePBX-17 modules

### ISSUE THREAD

**Issue by kennesaw10** [FreePBX/issue-tracker#211]
### FreePBX Version

FreePBX 17

### Issue Description

Currently, there is no phonebook module in FreePBX-17.  In FreePBX-16, it is at version 16.0.3.  This module needs to be ported to FreePBX-17 as many of us use it.

### Operating Environment

Debian 12.5, FreePBX-17 (Beta), Asterisk-21.3.1 
Open source modules only.

FreePBX-16:
![image](https://github.com/FreePBX/issue-tracker/assets/169156393/5f17c646-aeb9-4207-8ee0-32ad648d82fb)

FreePBX-17:
![image](https://github.com/FreePBX/issue-tracker/assets/169156393/be2646f2-24a5-4de8-ad6b-bcf38f456bd8)

### Relevant log output

 fwconsole ma downloadinstall phonebook
No repos specified, using: [standard,extended,unsupported] from last GUI settings

Downloading module 'phonebook'
The following error(s) occured:
 - Retrieved Module XML Was Empty

**Comment by ramarajan222** [comment]
Hi ,

The Phonebook module is deprecated. It has been replaced by the Contact Manager module. Please use the Contact Manager module.
