### ISSUE TITLE
Direct Voicemail feature code not working 

### ISSUE THREAD

**Issue by chopsywa** [FreePBX/issue-tracker#214]
### FreePBX Version

FreePBX 17

### Issue Description

When dialing *<ext>, there is about 2 seconds of silence, then the prompt "Your call cannot be completed as dialled. Please check the number and dial again". 

I tried customizing the feature code to *999 as the prefix. This worked (dialing *999101 took me to voicemail leave a message prompt)

### Operating Environment

Running on Debian 12 fully patched.
+-------------------+------------+-----------------------------------+-------------+-----------+
| Module            | Version    | Status                            | License     | Signature |
+-------------------+------------+-----------------------------------+-------------+-----------+
| amd               | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| announcement      | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| areminder         | 17.0.3.9   | Disabled                          | Commercial  | Sangoma   |
| arimanager        | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli      | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo      | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| backup            | 17.0.5.32  | Enabled                           | GPLv3+      | Sangoma   |
| blacklist         | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| broadcast         | 17.0.1.6   | Disabled                          | Commercial  | Sangoma   |
| builtin           |            | Enabled                           |             | Unsigned  |
| bulkhandler       | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| calendar          | 17.0.4.13  | Enabled                           | GPLv3+      | Sangoma   |
| callaccounting    | 17.0.5     | Disabled                          | Commercial+ | Sangoma   |
| callback          | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| callerid          | 17.0.1     | Disabled                          | Commercial  | Sangoma   |
| callforward       | 17.0.1.5   | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit         | 17.0.1.2   | Disabled                          | Commercial  | Sangoma   |
| callrecording     | 17.0.3.6   | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting       | 17.0.3.4   | Enabled                           | GPLv3+      | Sangoma   |
| cdr               | 17.0.4.15  | Enabled                           | GPLv3+      | Sangoma   |
| cel               | 17.0.2.8   | Enabled                           | GPLv3+      | Sangoma   |
| certman           | 17.0.3.10  | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| conferences       | 17.0.3.2   | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro    | 17.0.1.6   | Disabled                          | Commercial  | Sangoma   |
| configedit        | 17.0.1.1   | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager    | 17.0.5.11  | Enabled                           | GPLv3+      | Sangoma   |
| core              | 17.0.9.63  | Enabled                           | GPLv3+      | Sangoma   |
| cos               | 17.0.1.1   | Disabled                          | Commercial  | Sangoma   |
| customappsreg     | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| dashboard         | 17.0.4.3   | Enabled                           | AGPLv3+     | Sangoma   |
| daynight          | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| dictate           | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| directory         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| donotdisturb      | 17.0.2.3   | Enabled                           | GPLv3+      | Sangoma   |
| dynroute          | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| endpoint          | 17.0.1.65  | Enabled                           | Commercial  | Sangoma   |
| extensionroutes   | 17.0.1     | Enabled                           | Commercial  | Sangoma   |
| extensionsettings | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| fax               | 17.0.3.3   | Enabled                           | GPLv3+      | Sangoma   |
| faxpro            | 17.0.1.14  | Disabled                          | Commercial  | Sangoma   |
| featurecodeadmin  | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| filestore         | 17.0.2.17  | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow      | 17.0.4.8   | Enabled                           | GPLv3+      | Sangoma   |
| firewall          | 17.0.1.25  | Enabled                           | AGPLv3+     | Sangoma   |
| framework         | 17.0.15.27 | Enabled                           | GPLv2+      | Sangoma   |
| hotelwakeup       | 17.0.1.6   | Enabled                           | GPLv2       | Sangoma   |
| iaxsettings       | 17.0.1     | Disabled                          | AGPLv3      | Sangoma   |
| infoservices      | 17.0.1     | Enabled                           | GPLv2+      | Sangoma   |
| ivr               | 17.0.6     | Enabled                           | GPLv3+      | Sangoma   |
| languages         | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| logfiles          | 17.0.3.1   | Enabled                           | GPLv3+      | Sangoma   |
| manager           | 17.0.5     | Enabled                           | GPLv2+      | Sangoma   |
| miscapps          | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| miscdests         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| music             | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| paging            | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro         | 17.0.1.6   | Disabled                          | Commercial  | Sangoma   |
| parking           | 17.0.2.4   | Enabled                           | GPLv3+      | Sangoma   |
| parkpro           | 17.0.1.4   | Disabled                          | Commercial  | Sangoma   |
| pbxmfa            | 17.0.2     | Disabled                          | Commercial+ | Sangoma   |
| pinsets           | 17.0.3.2   | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro        | 17.0.2     | Disabled                          | Commercial  | Sangoma   |
| pm2               | 17.0.3.2   | Enabled                           | AGPLv3+     | Sangoma   |
| presencestate     | 17.0.2.3   | Enabled                           | GPLv3+      | Sangoma   |
| printextensions   | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| queueprio         | 17.0.1.4   | Enabled                           | GPLv3+      | Sangoma   |
| queues            | 17.0.1.9   | Enabled                           | GPLv2+      | Sangoma   |
| queuestats        | 17.0.1.6   | Disabled                          | Commercial  | Sangoma   |
| qxact_reports     | 17.0.2     | Disabled                          | Commercial  | Sangoma   |
| recording_report  | 17.0.3.8   | Disabled                          | Commercial  | Sangoma   |
| recordings        | 17.0.2.2   | Enabled                           | GPLv3+      | Sangoma   |
| restapps          | 17.0.1.15  | Enabled                           | Commercial  | Sangoma   |
| ringgroups        | 17.0.2.4   | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect    | 17.0.1.25  | Disabled                          | Commercial  | Sangoma   |
| sangomartapi      | 17.0.1.25  | Enabled                           | Commercial  | Sangoma   |
| setcid            | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings       | 17.0.6.7   | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation        | 17.0.3.3   | Enabled                           | Commercial  | Sangoma   |
| sms               | 17.0.1.12  | Enabled                           | Commercial  | Sangoma   |
| smsconnector      |            | Not Installed (Locally available) | GPLv3+      | Unknown   |
| smsplus           | 17.0.3     | Enabled                           | Commercial  | Sangoma   |
| soundlang         | 17.0.4.1   | Enabled                           | GPLv3+      | Sangoma   |
| sysadmin          | 17.0.1.85  | Enabled                           | Commercial  | Sangoma   |
| timeconditions    | 17.0.1.16  | Enabled                           | GPLv3+      | Sangoma   |
| tts               | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines        | 17.0.1     | Enabled                           | AGPLv3      | Sangoma   |
| ucp               | 17.0.4.17  | Enabled                           | AGPLv3+     | Sangoma   |
| userman           | 17.0.6.24  | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast           | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| vmnotify          | 17.0.1.5   | Disabled                          | Commercial  | Sangoma   |
| voicemail         | 17.0.5.17  | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report  | 17.0.1.1   | Disabled                          | Commercial  | Sangoma   |
| vqplus            | 17.0.1.16  | Disabled                          | Commercial  | Sangoma   |
| weakpasswords     | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| webrtc            | 17.0.2.2   | Enabled                           | GPLv3+      | Sangoma   |
+-------------------+------------+-----------------------------------+-------------+-----------+

### Relevant log output

```shell
Console verbose was OFF and is now 15.
  == Using SIP RTP Audio TOS bits 184
  == Using SIP RTP Audio TOS bits 184 in TCLASS field.
  == Using SIP RTP Audio CoS mark 5
    -- Executing [*101@from-internal:1] Answer("PJSIP/101-00000017", "") in new stack
       > 0x7f3c34460c30 -- Strict RTP learning after remote address set to: 192.168.104.163:10210
       > 0x7f3c34460c30 -- Strict RTP qualifying stream type: audio
       > 0x7f3c34460c30 -- Strict RTP switching source address to 49.255.160.50:10210
    -- Executing [*101@from-internal:2] Gosub("PJSIP/101-00000017", "macro-user-callerid,s,1()") in new stack
    -- Executing [s@macro-user-callerid:1] Set("PJSIP/101-00000017", "TOUCH_MONITOR=1717559651.38") in new stack
    -- Executing [s@macro-user-callerid:2] Set("PJSIP/101-00000017", "CHANCONTEXT=") in new stack
    -- Executing [s@macro-user-callerid:3] Set("PJSIP/101-00000017", "CHANCONTEXT=") in new stack
    -- Executing [s@macro-user-callerid:4] Set("PJSIP/101-00000017", "CHANEXTENCONTEXT=101-00000017") in new stack
    -- Executing [s@macro-user-callerid:5] Set("PJSIP/101-00000017", "CHANEXTEN=101-00000017") in new stack
    -- Executing [s@macro-user-callerid:6] Set("PJSIP/101-00000017", "CALLERID(number)=101") in new stack
    -- Executing [s@macro-user-callerid:7] Set("PJSIP/101-00000017", "AMPUSER=101") in new stack
    -- Executing [s@macro-user-callerid:8] Set("PJSIP/101-00000017", "HOTDESCKCHAN=101-00000017") in new stack
    -- Executing [s@macro-user-callerid:9] Set("PJSIP/101-00000017", "HOTDESKEXTEN=101") in new stack
    -- Executing [s@macro-user-callerid:10] Set("PJSIP/101-00000017", "HOTDESKCALL=0") in new stack
    -- Executing [s@macro-user-callerid:11] ExecIf("PJSIP/101-00000017", "0?Set(HOTDESKCALL=1)") in new stack
    -- Executing [s@macro-user-callerid:12] ExecIf("PJSIP/101-00000017", "0?Set(CALLERID(name)=)") in new stack
    -- Executing [s@macro-user-callerid:13] GotoIf("PJSIP/101-00000017", "0?report") in new stack
    -- Executing [s@macro-user-callerid:14] ExecIf("PJSIP/101-00000017", "1?Set(REALCALLERIDNUM=101)") in new stack
    -- Executing [s@macro-user-callerid:15] Set("PJSIP/101-00000017", "AMPUSER=101") in new stack
    -- Executing [s@macro-user-callerid:16] GotoIf("PJSIP/101-00000017", "0?limit") in new stack
    -- Executing [s@macro-user-callerid:17] Set("PJSIP/101-00000017", "AMPUSERCIDNAME=Mark Dutton") in new stack
    -- Executing [s@macro-user-callerid:18] ExecIf("PJSIP/101-00000017", "0?Set(__CIDMASQUERADING=TRUE)") in new stack
    -- Executing [s@macro-user-callerid:19] GotoIf("PJSIP/101-00000017", "0?report") in new stack
    -- Executing [s@macro-user-callerid:20] Set("PJSIP/101-00000017", "AMPUSERCID=101") in new stack
    -- Executing [s@macro-user-callerid:21] Set("PJSIP/101-00000017", "__DIAL_OPTIONS=HhTtr") in new stack
    -- Executing [s@macro-user-callerid:22] Set("PJSIP/101-00000017", "CALLERID(all)="Mark Dutton" <101>") in new stack
    -- Executing [s@macro-user-callerid:23] ExecIf("PJSIP/101-00000017", "0?Set(CUSDIAL=)") in new stack
    -- Executing [s@macro-user-callerid:24] ExecIf("PJSIP/101-00000017", "0?Set(CALLERID(all)="Mark Dutton" <101>)") in new stack
    -- Executing [s@macro-user-callerid:25] GotoIf("PJSIP/101-00000017", "0?limit") in new stack
    -- Executing [s@macro-user-callerid:26] ExecIf("PJSIP/101-00000017", "0?Set(GROUP(concurrency_limit)=101)") in new stack
    -- Executing [s@macro-user-callerid:27] ExecIf("PJSIP/101-00000017", "0?Set(CHANNEL(language)=)") in new stack
    -- Executing [s@macro-user-callerid:28] NoOp("PJSIP/101-00000017", "Macro depricated!! To keep the same line numbers") in new stack
    -- Executing [s@macro-user-callerid:29] NoOp("PJSIP/101-00000017", "Macro depricated !!  To keep the same line numbers") in new stack
    -- Executing [s@macro-user-callerid:30] GotoIf("PJSIP/101-00000017", "0?continue") in new stack
    -- Executing [s@macro-user-callerid:31] Set("PJSIP/101-00000017", "__TTL=64") in new stack
    -- Executing [s@macro-user-callerid:32] GotoIf("PJSIP/101-00000017", "1?continue") in new stack
    -- Goto (macro-user-callerid,s,48)
    -- Executing [s@macro-user-callerid:48] Set("PJSIP/101-00000017", "CALLERID(number)=101") in new stack
    -- Executing [s@macro-user-callerid:49] Set("PJSIP/101-00000017", "CALLERID(name)=Mark Dutton") in new stack
    -- Executing [s@macro-user-callerid:50] GotoIf("PJSIP/101-00000017", "0?cnum") in new stack
    -- Executing [s@macro-user-callerid:51] Set("PJSIP/101-00000017", "CDR(cnam)=Mark Dutton") in new stack
    -- Executing [s@macro-user-callerid:52] Set("PJSIP/101-00000017", "CDR(cnum)=101") in new stack
    -- Executing [s@macro-user-callerid:53] Return("PJSIP/101-00000017", "") in new stack
    -- Executing [*101@from-internal:3] GotoIf("PJSIP/101-00000017", "0?from-internal,,1") in new stack
    -- Executing [*101@from-internal:4] Goto("PJSIP/101-00000017", "bad-number,s,1") in new stack
    -- Goto (bad-number,s,1)
    -- Executing [s@bad-number:1] Goto("PJSIP/101-00000017", "11,1") in new stack
    -- Goto (bad-number,11,1)
    -- Executing [11@bad-number:1] ResetCDR("PJSIP/101-00000017", "") in new stack
    -- Executing [11@bad-number:2] Set("PJSIP/101-00000017", "CDR_PROP(disable)=true") in new stack
    -- Executing [11@bad-number:3] Progress("PJSIP/101-00000017", "") in new stack
    -- Executing [11@bad-number:4] Wait("PJSIP/101-00000017", "1") in new stack
    -- Executing [11@bad-number:5] Playback("PJSIP/101-00000017", "silence/1&cannot-complete-as-dialed&check-number-dial-again,noanswer") in new stack
    -- <PJSIP/101-00000017> Playing 'silence/1.ulaw' (language 'en_AU')
    -- <PJSIP/101-00000017> Playing 'cannot-complete-as-dialed.ulaw' (language 'en_AU')
  == Spawn extension (bad-number, 11, 5) exited non-zero on 'PJSIP/101-00000017'
[2024-06-05 11:54:16] WARNING[26445]: res_pjsip_pubsub.c:803 subscription_get_handler_from_rdata: No registered subscribe handler for event as-feature-event from 101
```

**Comment by ramarajan222** [comment]
looks like something wrong with the dialplan .Can you share the working and not working diaplans.

Not working scenario, run the command on asterisk cli and get the output 

`
dialplan show *101@from-internal
`

Working scenario (after changing feature code) run the command on asterisk cli and get the output

`
dialplan show *999101@from-internal
`

**Comment by reraikes** [comment]
@ramarajan222,

FWIW...

I'm not seeing a problem here:

`FreePBX*CLI> dialplan show *12@from-internal
[ Included context 'ext-local' created by 'pbx_config' ]
  '*12' =>          1. Set(CONNECTEDLINE(name-charset,i)=utf8)    [extensions_additional.conf:1753]
                    2. Set(CONNECTEDLINE(name,i)=12 Voicemail)    [extensions_additional.conf:1754]
                    3. Set(CONNECTEDLINE(num,i)=12)               [extensions_additional.conf:1755]
                    4. Gosub(macro-vm,s,1(12,DIRECTDIAL,${IVR_RETVM})) [extensions_additional.conf:1756]
                    5. Goto(vmret,1)                              [extensions_additional.conf:1757]

-= 1 extension (5 priorities) in 1 context. =-
`

*12 routes the call to extension 12's VM as expected.

**Comment by lgaetz** [comment]
This is not a 17 specific issue, it's a dialplan conflict with the default contact manager speeddial feature code of `*10` and direct dialing vm to extensions that being with the digits 10.

@chopsywa you're going to need to change the contact manager speeddial feature code to something that doesn't conflict, my goto for this case is to change from `*10` to `**10`

**Comment by reraikes** [comment]
>This is not a 17 specific issue, it's a dialplan conflict with the default contact manager speeddial feature code of *10

I don't install/use contact manager, so that explains why I don't have a problem with calls to *10 reaching VM.

**Comment by chopsywa** [comment]
Thank you @lgaetz
