### ISSUE TITLE
[bug]: Error "Undefined variable $vmops_attach" when editing the extension number

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#215]
### FreePBX Version

FreePBX 17

### Issue Description

Error "Undefined variable $vmops_attach" when editing the extension number.

`
root@sangoma:~# fwconsole ma list | grep "core\|voicemail\|framework"
| core              | 17.0.9.63  | Enabled | GPLv3+      | Sangoma   |
| framework         | 17.0.15.27 | Enabled | GPLv2+      | Sangoma   |
| voicemail         | 17.0.5.17  | Enabled | GPLv3+      | Sangoma   |
| voicemail_report  | 17.0.1.1   | Enabled | Commercial  | Sangoma   |`

![image](https://github.com/FreePBX/issue-tracker/assets/25248291/8dc23dbb-0562-40da-9abf-a9ca78de5eb4)

### Operating Environment

FreePBX V17

### Relevant log output

```shell
Whoops\Exception\ErrorException thrown with message "Undefined variable $vmops_attach"

Stacktrace:
#3 Whoops\Exception\ErrorException in /var/www/html/admin/modules/voicemail/functions.inc.php:556
#2 Whoops\Run:handleError in /var/www/html/admin/modules/voicemail/functions.inc.php:556
#1 voicemail_configpageload in /var/www/html/admin/libraries/components.class.php:495
#0 component:buildconfigpage in /var/www/html/admin/config.php:457
```

**Comment by kapilgupta01** [comment]
voicemail 17.0.5.18
