### ISSUE TITLE
Virtual extension call forward option not restored in pbx systems 

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#217]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

In server A, created a virtual extension and it is set with call forward & dnd options. Then took backup of server A and restored to server B (v17). Call forward option is not restored in v17. 

Attached relevant logs for reference. With below we can see that the call forward options are missing in v17.

server A logs 
`[root@freepbx ~]# asterisk -rx "database show" | grep 2011

/AMPUSER/2011/answermode                          : disabled
/AMPUSER/2011/cfringtimer                         : 0
/AMPUSER/2011/cidname                             : VirtExtGM2011
/AMPUSER/2011/cidnum                              : 2011
/AMPUSER/2011/concurrency_limit                   : 3
/AMPUSER/2011/cwtone                              : disabled
/AMPUSER/2011/device                              : 2011&992011
/AMPUSER/2011/dictate/email                       :
/AMPUSER/2011/dictate/enabled                     : disabled
/AMPUSER/2011/dictate/format                      : ogg
/AMPUSER/2011/dictate/from                        : ZGljdGF0ZUBmcmVlcGJ4Lm9yZw==
/AMPUSER/2011/followme/annmsg                     :
/AMPUSER/2011/followme/changecid                  : default
/AMPUSER/2011/followme/ddial                      : EXTENSION
/AMPUSER/2011/followme/dring                      :
/AMPUSER/2011/followme/fixedcid                   :
/AMPUSER/2011/followme/grpconf                    : DISABLED
/AMPUSER/2011/followme/grplist                    : 2011
/AMPUSER/2011/followme/grppre                     :
/AMPUSER/2011/followme/grptime                    : 20
/AMPUSER/2011/followme/postdest                   : ext-local,2011,dest
/AMPUSER/2011/followme/prering                    : 7
/AMPUSER/2011/followme/remotealertmsg             :
/AMPUSER/2011/followme/ringing                    : Ring
/AMPUSER/2011/followme/rvolume                    :
/AMPUSER/2011/followme/strategy                   : ringallv2-prim
/AMPUSER/2011/followme/toolatemsg                 :
/AMPUSER/2011/hint                                : PJSIP/992011&Custom:DND2011,CustomPresence:2011
/AMPUSER/2011/intercom                            : enabled
/AMPUSER/2011/intercom/override                   : reject
/AMPUSER/2011/language                            :
/AMPUSER/2011/missedcall                          : disable
/AMPUSER/2011/noanswer                            :
/AMPUSER/2011/outboundcid                         :
/AMPUSER/2011/password                            :
/AMPUSER/2011/queues/qnostate                     : usestate
/AMPUSER/2011/recording                           :
/AMPUSER/2011/recording/in/external               : dontcare
/AMPUSER/2011/recording/in/internal               : dontcare
/AMPUSER/2011/recording/ondemand                  : disabled
/AMPUSER/2011/recording/out/external              : dontcare
/AMPUSER/2011/recording/out/internal              : dontcare
/AMPUSER/2011/recording/priority                  : 10
/AMPUSER/2011/ringtimer                           : 0
/AMPUSER/2011/rvolume                             :
/AMPUSER/2011/voicemail                           : novm
/CF/2011                                          : 4031
/CW/2011                                          : ENABLED
/CustomDevstate/CF2011                            : BUSY
/CustomDevstate/DEVCF2011                         : BUSY
/CustomDevstate/DEVCF992011                       : BUSY
/CustomDevstate/DEVDND2011                        : BUSY
/CustomDevstate/DEVDND992011                      : BUSY
/CustomDevstate/DND2011                           : BUSY
/CustomDevstate/FOLLOWME2011                      : NOT_INUSE
/CustomDevstate/FOLLOWME992011                    : NOT_INUSE
/CustomPresence/2011                              : available,,
/CustomPresence/992011                            : available,,
/DEVICE/2011/default_user                         : 2011
/DEVICE/2011/dial                                 : VIRTUAL/2011
/DEVICE/2011/tech                                 : virtual
/DEVICE/2011/type                                 : fixed
/DEVICE/2011/user                                 : 2011
/DEVICE/992011/default_user                       : 2011
/DEVICE/992011/dial                               : PJSIP/992011
/DEVICE/992011/tech                               : pjsip
/DEVICE/992011/type                               : fixed
/DEVICE/992011/user                               : 2011
/DND/2011                                         : YES
`

server B (v17) logs after restore 

`root@sangoma:~# asterisk -rx "database show" | grep 2011

/AMPUSER/2011/answermode                          : disabled
/AMPUSER/2011/cidname                             : VirtExtGM2011
/AMPUSER/2011/cidnum                              : 2011
/AMPUSER/2011/device                              : 992011
/AMPUSER/2011/followme/annmsg                     :
/AMPUSER/2011/followme/ddial                      : EXTENSION
/AMPUSER/2011/followme/dring                      :
/AMPUSER/2011/followme/grplist                    : 2011
/AMPUSER/2011/followme/grppre                     :
/AMPUSER/2011/followme/grptime                    : 20
/AMPUSER/2011/followme/postdest                   : ext-local,2011,dest
/AMPUSER/2011/followme/prering                    : 7
/AMPUSER/2011/followme/remotealertmsg             :
/AMPUSER/2011/followme/ringing                    : Ring
/AMPUSER/2011/followme/rvolume                    :
/AMPUSER/2011/followme/strategy                   : ringallv2-prim
/AMPUSER/2011/followme/toolatemsg                 :
/AMPUSER/2011/hint                                : PJSIP/992011&Custom:DND2011,CustomPresence:2011
/AMPUSER/2011/noanswer                            :
/AMPUSER/2011/outboundcid                         :
/AMPUSER/2011/password                            :
/AMPUSER/2011/recording                           :
/AMPUSER/2011/recording/in/external               : dontcare
/AMPUSER/2011/recording/in/internal               : dontcare
/AMPUSER/2011/recording/ondemand                  : disabled
/AMPUSER/2011/recording/out/external              : dontcare
/AMPUSER/2011/recording/out/internal              : dontcare
/AMPUSER/2011/recording/priority                  : 10
/AMPUSER/2011/ringtimer                           : 0
/AMPUSER/2011/voicemail                           : novm
/AMPUSER/992011/cfringtimer                       : -1
/CW/2011                                          : ENABLED
/CustomDevstate/DEVDND992011                      : BUSY
/CustomDevstate/DND2011                           : BUSY
/CustomDevstate/FOLLOWME992011                    : NOT_INUSE
/CustomPresence/992011                            : available,,
/DEVICE/992011/default_user                       : 2011
/DEVICE/992011/dial                               : PJSIP/992011
/DEVICE/992011/tech                               : pjsip
/DEVICE/992011/type                               : fixed
/DEVICE/992011/user                               : 2011
/DND/2011                                         : YES
`

Thanks  

### Operating Environment

Fpbx 17

**Comment by lgaetz** [comment]
Need to check if this is an issue with CF/CFU settings for all extensions, not just virtual. 

I believe that call waiting AstDB settings are also lost on backup/restore which may be related to this.

**Comment by jissphilip** [comment]
callforward-17.0.1.6
callforward-16.0.6
callforward-15.0.17
