### ISSUE TITLE
Superfecta basic functionlity broken  

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#219]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

Superfecta callerid name is matched for incoming calls, however it is not being set while sending call to assigned route. 
When I enabled agi debug and checked, I'm getting this 

"<PJSIP/PJSIP_0_150-00000010>AGI Rx << Error: Undefined constant "agi_calleridname" in file /var/www/html/admin/modules/superfecta/agi/superfecta.agi on line 30 <PJSIP/PJSIP_0_150-00000010>AGI Tx >> 510 Invalid or unknown command"

superfecta v17.0.1.9

Logs 

` -- Executing [1234@from-pstn:20] AGI("PJSIP/PJSIP_0_150-00000010", "agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi") in new stack
AGI Tx >> agi_network: yes
AGI Tx >> agi_network_script: /var/www/html/admin/modules/superfecta/agi/superfecta.agi
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_request: agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_channel: PJSIP/PJSIP_0_150-00000010
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_language: en
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_type: PJSIP
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_uniqueid: 1717659367.24
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_version: 21.0.2
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_callerid: 7878784557
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_calleridname: 7878784557
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_callingpres: 0
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_callingani2: 0
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_callington: 0
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_callingtns: 0
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_dnid: 1234
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_rdnis: unknown
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_context: from-pstn
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_extension: 1234
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_priority: 20
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_enhanced: 0.0
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_accountcode:
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> agi_threadid: 140154315978432
<PJSIP/PJSIP_0_150-00000010>AGI Tx >>
<PJSIP/PJSIP_0_150-00000010>AGI Rx << GET VARIABLE CIDSFSCHEME
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1 (YmFzZV9TUzE=)
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Executing Scheme.." 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Executing Scheme..
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Scheme Asked is: SS1" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Scheme Asked is: SS1
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "The DID is: 1234" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: The DID is: 1234
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "The CNUM is: 7878784557" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: The CNUM is: 7878784557
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "The CNAME is: 7878784557" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: The CNAME is: 7878784557
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi:
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Starting scheme SS1" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Starting scheme SS1
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID before strip_tags: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID before strip_tags: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID after strip_tags: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID after strip_tags: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Strip_Accent_Characters: Y" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Strip_Accent_Characters: Y
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID before stripAccents: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID before stripAccents: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID after stripAccents: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID after stripAccents: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID before preg_replace: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID before preg_replace: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID after preg_replace: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID after preg_replace: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Character Encodings: 'ISO-8859-1'" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Character Encodings: 'ISO-8859-1'
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Converting result to UTF-8" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Converting result to UTF-8
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID before mb_convert_encoding: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID before mb_convert_encoding: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID after mb_convert_encoding: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID after mb_convert_encoding: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller_Id_Max_Length: '60'" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller_Id_Max_Length: '60'
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID before mb_substr: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID before mb_substr: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID after mb_substr: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID after mb_substr: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID before mb_substr: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID before mb_substr: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Caller ID after mb_substr: Girish TestNum2, length: 15, mb_strlen: 15" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Caller ID after mb_substr: Girish TestNum2, length: 15, mb_strlen: 15
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << VERBOSE "Setting caller id to: Girish TestNum2" 1
 agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi: Setting caller id to: Girish TestNum2
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << SET VARIABLE SUPERFECTA_NEW "Girish TestNum2"
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 200 result=1
<PJSIP/PJSIP_0_150-00000010>AGI Rx << Error: Undefined constant "agi_calleridname" in file /var/www/html/admin/modules/superfecta/agi/superfecta.agi on line 30
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 510 Invalid or unknown command
<PJSIP/PJSIP_0_150-00000010>AGI Rx << Stack trace:
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 510 Invalid or unknown command
<PJSIP/PJSIP_0_150-00000010>AGI Rx <<   1. Error->() /var/www/html/admin/modules/superfecta/agi/superfecta.agi:30
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> 510 Invalid or unknown command
    -- <PJSIP/PJSIP_0_150-00000010>AGI Script agi://127.0.0.1//var/www/html/admin/modules/superfecta/agi/superfecta.agi completed, returning 0
<PJSIP/PJSIP_0_150-00000010>AGI Tx >> HANGUP
`

Thanks 

### Operating Environment

fpbx 17

**Comment by kapilgupta01** [comment]
superfecta v17.0.1.10

**Comment by girishmani1992** [comment]
Hi,

Issue resolved with superfecta v17.0.1.10.



Thanks

**Comment by warthog9** [comment]
Confirmed this fixes the problem for me as well, any idea when this is going to hit the download/update repos so v17.0.1.9 stops replacing my manually installed v17.0.1.10 that doesn't have gpg signatures?
