### ISSUE TITLE
Some of the astdb values are not restoring 

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#221]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

In backup/restore, some of the values of astdb are not restoring. I have attached command output of backup system and restored v17 system.

Values are concurrency_limit, cwtone, followme/changecid, followme/fixedcid, intercom related options, etc

[v16_backup_system_command_output.txt](https://github.com/user-attachments/files/15613876/v16_backup_system_command_output.txt)
[v17restored_system_command_output.txt](https://github.com/user-attachments/files/15613877/v17restored_system_command_output.txt)

Thanks

### Operating Environment

fpbx17

**Comment by jissphilip** [comment]
core-15.0.22.37
core-16.0.68.27
core-17.0.9.67
