### ISSUE TITLE
Whoops \ Exception \ ErrorException (E_WARNING) file_get_contents(/home/asterisk/.ssh/id_ecdsa.pub): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#222]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

I'm getting whoops error when I tried to open backup module. Followed below steps 

1) Cloned a new system of v17 
2) Activated and track is set to edge 
3) Upgraded all modules from backend command and executed "fwconsole reload"
4) When I tried to open backup module, this error showed up.

backup v17.0.5.32

 Screen-shot

![image](https://github.com/FreePBX/issue-tracker/assets/163297370/7dca6a76-55f1-46b9-b0cf-899f4613ca3d)

Thanks

### Operating Environment

fpbx 17

**Comment by jissphilip** [comment]
backup-17.0.5.33
