### ISSUE TITLE
Whoops \ Exception \ ErrorException (E_WARNING) Undefined array key "fxs_port_1_context"

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#225]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

I have created 2 dahdi extensions for FXS, when I tried to edit group number and save it, I'm getting error 

"Whoops \ Exception \ ErrorException (E_WARNING) Undefined array key "fxs_port_1_context""

dahdiconfig v17.0.1.8

Attaching screen-shot for reference

![image](https://github.com/FreePBX/issue-tracker/assets/163297370/1b2695e4-3c7b-457e-859b-b426f8123701)

Thanks

### Operating Environment

fpbx 17

**Comment by jissphilip** [comment]
dahdiconfig version 17.0.1.9
