### ISSUE TITLE
Whoops \ Exception \ ErrorException (E_DEPRECATED) uksort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#226]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

While creating dahdi trunk, I'm getting below whoops error.

"Whoops \ Exception \ ErrorException (E_DEPRECATED) uksort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero"

Attached screen-shot for reference.

![image](https://github.com/FreePBX/issue-tracker/assets/163297370/33ffb226-5858-4601-85e6-08caff45dbdc)

Thanks

### Operating Environment

fpbx 17

**Comment by jissphilip** [comment]
dahdiconfig version 17.0.1.9
