### ISSUE TITLE
[bug]: FAX configuration module error and Asterisk info error from fax module

### ISSUE THREAD

**Issue by tpimont** [FreePBX/issue-tracker#227]
### FreePBX Version

FreePBX 17

### Issue Description

hello,
Fax configuration module error   
 Whoops \ Exception \ ErrorException (E_WARNING)  Undefined array key "force_detection"
 And in Asterisk info fax error too
Undefined array key "global"  File:/var/www/html/admin/modules/asteriskinfo/Modules/Fax.php:79

### Operating Environment

Freepbx 17  Asterisk 20 Rocky 9

### Relevant log output

```shell
Fax configuration module error   
 Whoops \ Exception \ ErrorException (E_WARNING)  Undefined array key "force_detection"
 And in Asterisk info fax error too
Undefined array key "global"  File:/var/www/html/admin/modules/asteriskinfo/Modules/Fax.php:79
```

**Comment by kapilgupta01** [comment]
Fax configuration module error
Whoops \ Exception \ ErrorException (E_WARNING) Undefined array key "force_detection"

what is the line number for this error @tpimont ?

**Comment by tpimont** [comment]
line 217
                    <input type="radio" class="form-control" id="force_detection_yes" name="force_detection" value="yes" <?php echo (($settings['force_detection'] == 'yes') ? 'checked' : ''); ?> >

**Comment by tpimont** [comment]
in file /var/www/html/admin/modules/fax/views/view.form_options.php

**Comment by kapilgupta01** [comment]
asteriskinfo v17.0.2
fax v17.0.3.4
Please try with ^ versions.

`fwconsole ma downloadinstall fax --tag=17.0.3.4
`
`fwconsole ma downloadinstall asteriskinfo --tag=17.0.2`
