### ISSUE TITLE
In functions.inc.php line 151:    [Whoops\Exception\ErrorException (2)]   Undefined array key "custom"

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#228]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

Getting error while executing "fwconsole reload". Error given below

`root@sangoma:~# fwconsole r -v
Reload Started

In functions.inc.php line 151:

  [Whoops\Exception\ErrorException (2)]
  Undefined array key "custom"

Exception trace:
  at /var/www/html/admin/modules/dahdiconfig/functions.inc.php:151
 Whoops\Run->handleError() at /var/www/html/admin/modules/dahdiconfig/functions.inc.php:151
 dahdiconfig_conf->generateConf() at /var/www/html/admin/libraries/BMO/FileHooks.class.php:67
 FreePBX\FileHooks->processOldHooks() at /var/www/html/admin/libraries/BMO/FileHooks.class.php:26
 FreePBX\FileHooks->processFileHooks() at /var/www/html/admin/libraries/Console/Reload.class.php:340
 FreePBX\Console\Command\Reload->reload() at /var/www/html/admin/libraries/Console/Reload.class.php:95
 FreePBX\Console\Command\Reload->execute() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php:312
 Symfony\Component\Console\Command\Command->run() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:1022
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:314
 Symfony\Component\Console\Application->doRun() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:168
 Symfony\Component\Console\Application->run() at /var/lib/asterisk/bin/fwconsole:163

reload [--json] [--dry-run] [--skip-registry-checks] [--dont-reload-asterisk]

`
dahdiconfig v17.0.1.9

Thanks

### Operating Environment

fpbx17

**Comment by kapilgupta01** [comment]
dahdiconfig v17.0.1.10
