### ISSUE TITLE
[bug][SECURITY]: sng_freepbx_debian_install

### ISSUE THREAD

**Issue by jfinstrom** [FreePBX/issue-tracker#23]
### FreePBX Version

FreePBX 17

### Issue Description

This script adds the asterisk user with passwordless access to the sudoers file.   I am sure you will find plenty of feedback to why giving your webserver escalated privileges is a bad idea.  You can even probably look at early privilege escalation bugs in the project for discussion.

### Operating Environment

Debian

**Comment by kguptasangoma** [comment]
thanks @jfinstrom for the feedback, removed the asterisk user from the sudoers list and pushed the new script to the github repo.
