### ISSUE TITLE
[bug]: Backup & Restore, Restoration Window does not Scroll like it used to

### ISSUE THREAD

**Issue by microchipmatt** [FreePBX/issue-tracker#230]
### FreePBX Version

FreePBX 17

### Issue Description

Backup & Restore, Restoration Window does not Scroll like it used to, In previous versions, the windows would scroll on restoration so one could watch and identify any errors. The Windows no longer has the Scroll Function:
![image](https://github.com/FreePBX/issue-tracker/assets/11633632/e63ebaf1-17cb-408c-9c05-9ebeb0b5280d)

### Operating Environment

FreePBX 17, Debian 12.5, Backup & Restore Module.

**Comment by kapilgupta01** [comment]
Added the scroll option but auto adjusting is still needs to fix.

Backup v17.0.5.36
