### ISSUE TITLE
Certificate update and validity 

### ISSUE THREAD

**Issue by Andsup** [FreePBX/issue-tracker#235]
### FreePBX Version

FreePBX 17

### Issue Description

After a successfully updated certificate.

In certificate management :
![image](https://github.com/FreePBX/issue-tracker/assets/21259340/4cb82909-cfc5-4b65-8858-f697bd713d31)

In the browser after a restart of freepbx and the browser :
![image](https://github.com/FreePBX/issue-tracker/assets/21259340/ec51f38c-32cd-4937-b721-5a3c9b7588c2)

Validity are not aligned

/etc/apache2/pki is not updated

### Operating Environment

debian 12.5

### Relevant log output

```shell
.
```

**Comment by ramarajan222** [comment]
On my testing system, the latest certificate has been updated automatically for Apache, not sure why it didn't happen automatically on your system.

You can update the certificate manually, go to sysadmin==>https setup and select the certificate and click on the install button.

**Comment by Andsup** [comment]
I did : sysadmin==>https setup and select the certificate and click on the install button.
- certifcate installed (visible via the browser) 
- apache restarted
BUT:
- screen do not keep the installed certificate after the apache restart

![image](https://github.com/FreePBX/issue-tracker/assets/21259340/f6207923-1fbc-4bb6-a194-5e7122922f8b)

Is that ok ?

**Comment by ramarajan222** [comment]
Yes. That is expected only, the configured certificate details on the right side.
![image](https://github.com/FreePBX/issue-tracker/assets/25248291/09983237-4372-4fa8-8bcc-9cc38b82ce99)

**Comment by Andsup** [comment]
Thanks for your support.
