### ISSUE TITLE
[bug]: Connectivity->Firewall->Networks : Unable to save Description

### ISSUE THREAD

**Issue by infotts-py** [FreePBX/issue-tracker#238]
### FreePBX Version

FreePBX 16

### Issue Description

In  Connectivity->Firewall->Networks we're unable to save a  description for networks we've added. It simply disappears after hitting Save.

### Operating Environment

PBX Version:
17.0.15.27
PBX Distro:
12.7.8-2402-3.sng12
Asterisk Version:
21.0.2
Firewall : 17.0.1.25

**Comment by kapilgupta01** [comment]
Looks like new entry description works fine but existing entry adding description not working.

@infotts-py can you please confirm adding new entry and description works fine for you or not?

**Comment by infotts-py** [comment]
You're right. A new entry will save the description if that field is completed at the same time. Error only occurs with an existing entry.

**Comment by kapilgupta01** [comment]
firewall v17.0.1.26

**Comment by infotts-py** [comment]
That works. Thank you

**Comment by kapilgupta01** [comment]
Thanks for the prompt response @infotts-py . 

Please continue to test Freepbx 17 and provide your feedbacks.

Regards
Kapil
