### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by microinnovation** [FreePBX/issue-tracker#239]
### FreePBX Version

FreePBX 16

### Issue Description

PharException thrown with message "phar error: Cannot open phar archive "/tftpboot/-vpn.tar" for reading"

Stacktrace:
#7 PharException in /var/www/html/admin/modules/endpoint/functions.inc/functions_common.php:5462
#6 PharData:addFile in /var/www/html/admin/modules/endpoint/functions.inc/functions_common.php:5462
#5 endpoint_vpncfg in /var/www/html/admin/modules/endpoint/functions.inc/functions_yealink.php:506
#4 endpoint_write_yealink_ext in /var/www/html/admin/modules/endpoint/functions.inc/functions_common.php:69
#3 endpoint_write_ext in /var/www/html/admin/modules/endpoint/functions.inc/functions_common.php:1769
#2 endpoint_rebuild_template in /var/www/html/admin/modules/endpoint/views/page.endpoint.php:430
#1 include_once in /var/www/html/admin/modules/endpoint/page.endpoint.php:10
#0 include in /var/www/html/admin/config.php:658

### Operating Environment

PBX Version:15.0.37.4
PBX Distro:12.7.8-2203-2.sng7
Asterisk Version:16.24.1
EndPoint Manager15.0.65.7

### Relevant log output

```shell
/var/www/html/admin/modules/endpoint/functions.inc/functions_common.php
Arguments
"phar error: Cannot open phar archive "/tftpboot/-vpn.tar" for reading"
```

**Comment by kapilgupta01** [comment]
hey were you trying to use the VPN configuration? If yes then ensure you have done the VPN configuration properly.

**Comment by microinnovation** [comment]
The VPN configuration is working on the device, this happened when updating the feature buttons on Yealink template.

I was able to get around the problem by going through extensions mapping and selecting the phones and doing a Save, Rebuild Config(s) and Update Device .

Versus running the Save, Rebuild Config(s) and Update Device from the template itself.

**Comment by kapilgupta01** [comment]
Okay @microinnovation , Not sure why mac address was coming empty in your problematic call flow.
Anyway added check to avoid the whoops error. 

Also, you are using Freepbx 15 so recommend you to think about upgrading to 16 as 15 is right now only security fixes release.
