### ISSUE TITLE
[improvement]: synology module should not be enabled by default 

### ISSUE THREAD

**Issue by dolesec** [FreePBX/issue-tracker#243]
### FreePBX Version

FreePBX 17

### Improvement Description

@kguptasangoma @lgaetz I'm happy we have a new module however the fact that on new system installs it's going to throw a dashboard warning is not ideal 

I don't use Synology and I'm sure that's the case with many others as well 

this type of module should be installed manually if desired, not by default where most will have to remove it for a clean dash

![Screenshot 2024-06-12 at 6 51 30 PM](https://github.com/FreePBX/issue-tracker/assets/2153999/c3a0aab1-4e0f-4cc3-a110-2de70e7a5207)

**Comment by kapilgupta01** [comment]
Agreed @dolesec . synology should be disabled by default. thanks for reporting this issue.

**Comment by msanthosh18** [comment]
above module has been disabled by default now
