### ISSUE TITLE
[bug]: Commercial Endpoint Manager/Polycom: custom softkeys disappear when user adds BLF keys using UCP

### ISSUE THREAD

**Issue by CaptainChris2019** [FreePBX/issue-tracker#249]
### FreePBX Version

FreePBX 16

### Issue Description

Commercial endpoint manager. If a custom soft key is added, and a BLF line key is added through the UCP, the custom softkeys will disappear until the phone is reset to template.

### Operating Environment

FreePBX 16
Endpoint Manager 16.0.86.21
Poly VVX 400

**Comment by kapilgupta01** [comment]
Hi 

You've opened a bug for a Commercial Module.

This Issue tracking system is for our Free and Open Source modules only.

Please open [a commercial support ticket [here](https://help.sangoma.com/)!.

If you are using FreePBX 12 or higher, please make sure you attach a Support Debug package (which is generated through the System Admin module) to the commercial support ticket.  Do not attach it to THIS bug tracker, as it may contain confidential information that will not be hidden from the general public.


Thank you for using FreePBX.
Kapil Gupta
