### ISSUE TITLE
file(/home/asterisk/.ssh/authorized_keys): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#252]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

In global settings of backup & restore module in fresh v17 system, there's an option to add public key of another system. When I added key and tried to save it, I'm getting error _"file(/home/asterisk/.ssh/authorized_keys): Failed to open stream: No such file or directory"_ 

File authorized_keys should be automatically created whenever we open backup module initially in fresh system

Image attached 

![image](https://github.com/FreePBX/issue-tracker/assets/163297370/5d2f7454-9b16-4fad-8b5f-5619f50479bf)

Thanks

### Operating Environment

fpbx 17

**Comment by jissphilip** [comment]
backup version 17.0.5.43
