### ISSUE TITLE
[bug]: phoneapps commerical module not working on FreePBX 17 for Yealink brand

### ISSUE THREAD

**Issue by dolesec** [FreePBX/issue-tracker#253]
### FreePBX Version

FreePBX 17

### Issue Description

testing PhoneApps on FreePBX 17 using Yealink T46s endpoint and all seem to encounter a whoops error and fail.

before licensing buttons would display a message stating it was not licensed, after licensing it appears all PhoneApp's encounter a whoops error  

_i don't see the same issue on the Sangaom S 705_ 

### Operating Environment

+---------------------+------------+---------+-------------+-----------+
| Module              | Version    | Status  | License     | Signature |
+---------------------+------------+---------+-------------+-----------+
| accountcodepreserve | 17.0.0.1   | Enabled | GPLv2       | Sangoma   |
| amd                 | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| api                 | 17.0.1.4   | Enabled | AGPLv3+     | Sangoma   |
| areminder           | 17.0.3.10  | Enabled | Commercial  | Sangoma   |
| arimanager          | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| backup              | 17.0.5.40  | Enabled | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| broadcast           | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| builtin             |            | Enabled |             | Unsigned  |
| bulkhandler         | 17.0.4     | Enabled | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.14  | Enabled | GPLv3+      | Sangoma   |
| callaccounting      | 17.0.5     | Enabled | Commercial+ | Sangoma   |
| callback            | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| callerid            | 17.0.1     | Enabled | Commercial  | Sangoma   |
| callforward         | 17.0.1.6   | Enabled | AGPLv3+     | Sangoma   |
| calllimit           | 17.0.1.2   | Enabled | Commercial  | Sangoma   |
| callrecording       | 17.0.3.6   | Enabled | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4   | Enabled | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.15  | Enabled | GPLv3+      | Sangoma   |
| cdrpro              | 17.0.3.16  | Enabled | Commercial  | Sangoma   |
| cel                 | 17.0.2.8   | Enabled | GPLv3+      | Sangoma   |
| certman             | 17.0.3.11  | Enabled | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| conferencespro      | 17.0.1.7   | Enabled | Commercial  | Sangoma   |
| configedit          | 17.0.1.1   | Enabled | AGPLv3+     | Sangoma   |
| contactmanager      | 17.0.5.11  | Enabled | GPLv3+      | Sangoma   |
| core                | 17.0.9.67  | Enabled | GPLv3+      | Sangoma   |
| cos                 | 17.0.1.1   | Enabled | Commercial  | Sangoma   |
| customappsreg       | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| dashboard           | 17.0.4.3   | Enabled | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| disa                | 17.0.3     | Enabled | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3   | Enabled | GPLv3+      | Sangoma   |
| endpoint            | 17.0.1.70  | Enabled | Commercial  | Sangoma   |
| extensionroutes     | 17.0.1     | Enabled | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4   | Enabled | GPLv3+      | Sangoma   |
| faxpro              | 17.0.1.15  | Enabled | Commercial  | Sangoma   |
| featurecodeadmin    | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.20  | Enabled | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.8   | Enabled | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.26  | Enabled | AGPLv3+     | Sangoma   |
| framework           | 17.0.15.27 | Enabled | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6   | Enabled | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1     | Enabled | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1     | Enabled | GPLv2+      | Sangoma   |
| ivr                 | 17.0.6     | Enabled | GPLv3+      | Sangoma   |
| languages           | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3   | Enabled | GPLv3+      | Sangoma   |
| manager             | 17.0.5     | Enabled | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| music               | 17.0.4     | Enabled | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| paging              | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| pagingpro           | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| parking             | 17.0.2.4   | Enabled | GPLv3+      | Sangoma   |
| parkpro             | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| pbxmfa              | 17.0.2     | Enabled | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1     | Enabled | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| pinsetspro          | 17.0.2     | Enabled | Commercial  | Sangoma   |
| pm2                 | 17.0.3.2   | Enabled | AGPLv3+     | Sangoma   |
| presencestate       | 17.0.2.4   | Enabled | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4   | Enabled | GPLv3+      | Sangoma   |
| queues              | 17.0.1.9   | Enabled | GPLv2+      | Sangoma   |
| queuestats          | 17.0.1.7   | Enabled | Commercial  | Sangoma   |
| qxact_reports       | 17.0.2     | Enabled | Commercial  | Sangoma   |
| recording_report    | 17.0.3.8   | Enabled | Commercial  | Sangoma   |
| recordings          | 17.0.2.2   | Enabled | GPLv3+      | Sangoma   |
| restapps            | 17.0.1.15  | Enabled | Commercial  | Sangoma   |
| ringgroups          | 17.0.2.4   | Enabled | GPLv3+      | Sangoma   |
| sangomaconnect      | 17.0.1.33  | Enabled | Commercial  | Sangoma   |
| sangomacrm          | 17.0.1.5   | Enabled | Commercial  | Sangoma   |
| sangomartapi        | 17.0.1.25  | Enabled | Commercial  | Sangoma   |
| setcid              | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.7   | Enabled | AGPLv3+     | Sangoma   |
| sipstation          | 17.0.3.3   | Enabled | Commercial  | Sangoma   |
| sms                 | 17.0.1.13  | Enabled | Commercial  | Sangoma   |
| smsplus             | 17.0.3     | Enabled | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1   | Enabled | GPLv3+      | Sangoma   |
| sysadmin            | 17.0.1.88  | Enabled | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.17  | Enabled | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1     | Enabled | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.18  | Enabled | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.25  | Enabled | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| vmnotify            | 17.0.1.7   | Enabled | Commercial  | Sangoma   |
| voicemail           | 17.0.5.19  | Enabled | GPLv3+      | Sangoma   |
| voicemail_report    | 17.0.1.1   | Enabled | Commercial  | Sangoma   |
| voipinnovations     | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| vqplus              | 17.0.1.16  | Enabled | Commercial  | Sangoma   |
| weakpasswords       | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| webcallback         | 17.0.4     | Enabled | Commercial  | Sangoma   |
| webrtc              | 17.0.2.2   | Enabled | GPLv3+      | Sangoma   |
+---------------------+------------+---------+-------------+-----------+

### Relevant log output

```shell
GET /applications.php/restapps/main?token=5e897a5c-81d5-4bab-bd9b-29ef0aea87da&user=1502 HTTP/1.1
Host: fpbx17.cditcpbx.net:82
User-Agent: Yealink SIP-T46S 66.86.0.15 80:5e:c0:2f:3c:2e
Accept: */*

HTTP/1.1 500 Internal Server Error
Date: Fri, 14 Jun 2024 15:00:52 GMT
Server: Apache
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html;charset=UTF-8

1aa5b
<!DOCTYPE html><!--


Whoops\Exception\ErrorException: Undefined variable $minversion in file /var/www/html/admin/modules/restapps/functions.inc/aastra.class.php on line 1378
Stack trace:
  1. Whoops\Exception\ErrorException-&gt;() /var/www/html/admin/modules/restapps/functions.inc/aastra.class.php:1378
  2. Whoops\Run-&gt;handleError() /var/www/html/admin/modules/restapps/functions.inc/aastra.class.php:1378
  3. aastra_device_has_softkey_uri_selection() /var/www/html/admin/modules/restapps/functions.inc/aastra.class.php:584
  4. aastra_page_display() /var/www/html/admin/modules/restapps/functions.inc/aastra.class.php:717
  5. aastra_get_page() /var/www/html/admin/modules/restapps/applications/RestappsApplications.class.php:256
  6. RestappsApplications-&gt;processRequest() /var/www/html/admin/modules/restapps/applications/RestappsApplications.class.php:51
  7. RestappsApplications-&gt;run() /var/www/html/admin/modules/restapps/applications.php:23




/var/www/html/admin/modules/restapps/applications/RestappsApplications.class.php
azGsIsjvh7pZcegJLWAelk4Jie3Z0oy/NRWCh3Dv6llW768mCbs4SEMQ3962h3CMaH6/CpDbTWo6
LBDKwm48/7McFjvydIn3ZjWbRdU/gPPdEJIRMqzAvFVRrolE2M6fMpyospUki9Njkgvrlka3P0qz
NPo4tfOfhBgr/wQvEmMrn5RS0zxeDvNPDnON/1hJV+/IPeAiT+aFv8Gu0wOvHLN3IekZvDPkSE0i
oLjdm0McFqjPPO3SSZwabcQTY0WzuyMxOQZ39+aIwVBan17A1EhNN6cwjJQrO6qO1LuuUhFV6Is4
Z1u0oh1DNnku35diLgtCmmG/9NP6Ut0RTHN9CZ7G/GomZnMMKMRyClytCDq2OojkC0z/hLvyb+nV
vvU836bBae0ItfRXn4z34MQQxAK9lJ9lczIL6jlAgJ6kc9S6Plc6GNrmWrGLdx5FSQfb7xngrQiS
lPIbGs6wyfHubulkK0wEkC1LpVV605uJTRMgSnbLxjnnaI0aKkfiWR0dujrjIGeUlYGKiBXT/yDS
vT+0/sGNyvIYHIxynHnBbCvSWs1TPOkiNTQIWEEeOOpRBPXnnlRoNLW49vHjG6DyOhLhNqE2d1Jz
dKnI2MpQNGr8k2czUJDfqkRPxszL2w40ZtbHW499cAkUy28laSgjtv8AI/YEPV6GY4RdI0yido2T
t2+vZO3Ydvnj5r3K3mg3UV2oNusukkTw5uApDuT4JNQaWgyqo1DPfr8K9ObOpugAWGHlBioilYPU
3ylebD04IYIwMRMFaF4GOESStsbk1Y/qeZHw7p105J9QuqV2/u1xJ+Kr4jNZ6fHXkLfzuS7Vm8dA
3+F0poKAI9xfbFI3e/LHRQWPWd0UJFab1MJ/d24GHcSCIgsqiSuLOBhjHQNcQFebeD4DYNCrJ9Gt
I1u3CCdOOeaADyxLXLfMzOfDWZ4+KVATqWl9ELer/201zfgdgoN9PrGT0ALYexBQf/wFxCpvxiFk
Qh7SmQd8wVY5l9U36gYIqDkM4TUdAX6+SS40Wdz+8ZQEo5WN13JlPdLoZVd/mdOCZNSdo7xQDczN
3UbxujplLjt7CHWFhz7DE3hUh63Vtgb++ye9ADJQfLYbi5TEE7eDMm7J/OLpmjx26/i8TNHs+hYT
LB21Df+Swg2gkcRKg4NhuOLu4PIX4fotNQ9zfdUvQZYjycLPkXzJBe45qT5Ty5CE9SiqTuK89Q/I
NY2bUXr2iP9uU/PRzNoD3G/bbjIyr8c2fyMezCGJXWch/V8KZcTN/xx44BI6ZXKcQ+oBPSDPsAk9
mLsVNgYy3ehr/BS+221/SXNbukrg6bZEp0jgBpQu59kRr8juP7UeulCU5pr1f0v9ECrK24Bg88WO
3535BH2vfVXOzTDO+tRs71i7WHrhgDFLhyDHcN9VRYzIq/EJRctu4zidfyA9Lf5802Z/UK3xmopB
YnHyXSDW7Gh6Tjq7vU5PJZrdjyBWIuicvGFFhYOcegrNYX2mWBu+CRiQhwsogZPa1unyq0L11DwU
GLam1ErV+Bahdd0rC+CGIj3xwkS5lEJ/ceTllu2sltCF+J6pe6h5u0RxO5ASxTsxLoZpW2nVAPhm
GzzjJ+gMnwriaJDfx0d1De/DIimWYt5X8Lg//L4fMJWesXv1ClAfb7Rqwt3GHts6B3YyAmH7A0iC
0mPKnVoFXoDy39i1LtPX2/X6B0muToods1yqAN9GOLEt3iFuumrmZJvABxugsswgnZSUhMRCNqbp
hexjM0Q67LlvO50SrAZh+r/bG6IBiBtRb4yPOK4Fcxoh73skrSnFYpT5Gc7a0flNB+TcVjiQaYaS
PB0FXl1sjVUpE5a18ZVZjjjwmZq66OKATKZWFQFmW4UCJb+qJ0TWpEqivLzqNilDmqFZu6pzmOzD
3WMF9Rk3WHF/0IGYEZyM1weT4axhT918jEdgnhZ+Q6M13wBs5nQvCs9q+HLT5dnCaf+FmnMmM2Et
WPC8lr47IvKbRt+efGWdks88DM5XBajToP1d8aJ3SCZou82BXyN7MEjg8WZuP6YhAsoQ4sKsAEhf
HTw8lP0Dc5XY4GXMbXWo3JeXKXDbkBaHul6wNQ8oCAVLrEctU5rbjNlVFRD8w/O6ECVkqztQinf6
aINTyRETGpw2u/Tm3qijrQJkmEpKcZGn8udyAjWWuPReEvEhU1KEtkh+O9EFh35XG5l3WsT9T5pY
eGHJqz2LAA5GHFIXUNBMoW3jQSW2FI55QzsjooK+31+tN6K+DzbtTgqgeIcjcPsWi6TBQn4MtJCY
3c3/+Mu/XgzPf4+jaBAZ1+frME9DGQQRVekLwemvDgybdEcldngsVU3WDzjwxRhFlWmuD2F9XMjN
TY3635m+FMSYbUh4tYIyA/NypQT5LOM+9OXvJb9Qr8Qg5rSUjdI09F/2RnKg1b29tdGzEXZzo4Ix
eN/T3ivKkc395bJuBg+vmEGgCKc9W5ZBVEo5pwRAvEBWd2VsBP2AWb7MPuHmftvLy5wPTVb2QlgU
eDMwkiTnzyTY/PlFSJu0ASfXBs0/y2CPTEZMbrbD4CdKyRbCnb9MJQ3+SIzeO1gDMXKKtqyjbVn7
toBfH//i5idQ94+tYobK6Dp8xcboa01aKANJuc+t+FsYcLpoR+B7+9J+O50Zd1fAAd8iI6R25iB7
s1wUyMIgDVFFsLA9ljUBzB9In4aMyF76SxIYDCVnAjRCheqizGl/8W+wAoBtqLjbWLgQij+8deWb
YWZRq4TM3YnQsu2xjaVC7hKGa0u5PNaYjCucZDpekNbbhMgJkJ/SUl7OwdZSbS93DHwcdkaEv0ZO
o0GA5uUel/ljqzcBGtXCb/qUjpC1Py4t6bEqccBw1FdhgRFGcVhQJmKQw7GZnI7WjzUl1VDwvJcg
XGlrRK3wuDEeXwLT01lUf06PJOrthU2HAZTan4gkyM/nh3N9BomDeTnPzsDeEKgClv3uCWIRUXFA
6MBTl34rxfCI1H5nC2ton5tCd32/UZ+Y7H9+uJsGGEXNp4vn3qyhacinnbTkrI60N3tyqEMr/bR5
Arguments
"Trying to access array offset on value of type null"
```

**Comment by kapilgupta01** [comment]
Hi @dolesec 
please try with restapps v17.0.1.16 

Thanks

**Comment by dolesec** [comment]
thank you -  its resolved. 

have a great weekend!

**Comment by dolesec** [comment]
looks like there are some lingering errors with specific apps, ill open those individually ...

**Comment by kapilgupta01** [comment]
sure thanks @dolesec
