### ISSUE TITLE
[bug]: backup progress dialogue now resets to the top of the page with every new line written 

### ISSUE THREAD

**Issue by dolesec** [FreePBX/issue-tracker#260]
### FreePBX Version

FreePBX 17

### Issue Description

when running a backup and trying to follow the progress its extremely difficult as recently the dialogue resets to the top with every new line written to the backup log 

this is new behavior and undesirable 

instead it should continue to scroll down and show the last line written - it should not reset to the top of the page 

https://github.com/FreePBX/issue-tracker/assets/2153999/d6d8481a-95dc-4705-a83c-1065fb51e21b

### Operating Environment

backup              | 17.0.5.43

### Relevant log output

```shell
none
```

**Comment by kapilgupta01** [comment]
backup v17.0.5.45
