### ISSUE TITLE
Asterisk Phonebook Module

### ISSUE THREAD

**Issue by kennesaw10** [FreePBX/issue-tracker#266]
### FreePBX Version

FreePBX 17

### Feature Description

You have not provided adequate means of replacing the phonebook module with the contact manager.  There are other uses of the phonebook module such as caller-id lookup, creating whitelist entries,  etc.   Currently, there is no way to import entries from the phonebook module into the Contact Manager module.  I would think it would be a simple task for someone to do the PHP8.2 updates to this module and port it into FreePBX-17.  You are not understanding the larger use of this simple module.

**Comment by kennesaw10** [comment]
I have also noticed that if you try to add only a caller-id name and number to the contact manager module, you get a whoops error.  This makes the module pretty unusable for simpler implementations.  Also, if I try to update the database manually via mysql, there is no clear linkage between the contact manager name and numbers database.  I have been unable to decipher the relationship of the UID in the name database with the numbers which accompany the name.

**Comment by kapilgupta01** [comment]
"I have also noticed that if you try to add only a caller-id name and number to the contact manager module, you get a whoops error"

I just tried to add number and name and it worked fine for me. 

![image](https://github.com/FreePBX/issue-tracker/assets/131970355/c1ab02f0-fcb7-459d-bf96-68969d51a19d)

Please share the steps you are  executing ?

**Comment by blazestudios97** [comment]
I cannot replicate this issue either.

**Comment by kennesaw10** [comment]
I just tried it again and it worked.  Perhaps I had not upgraded the module when I tried this.  I'm currently at 17.0.5.11 and it is working now.

However, I still see the need for the phonebook module.

**Comment by lgaetz** [comment]
@kennesaw10 

The two supported Caller ID lookup modules, Caller ID Lookup and Superfecta both support lookups in contact manager.

The only supported method of doing whitelisting is with the AllowList module which does support Contact Manager.  Are you perhaps doing your own solution here, and if so, I recommend you raise a forum discussion to see how best to move to CM for this. I have published some small scripts for doing CM integrations.

You can use the Bulk Import module to import entries into contact management using CSV.
