### ISSUE TITLE
[bug]: could not find driver: could not find driver

### ISSUE THREAD

**Issue by paramjeetSingh84** [FreePBX/issue-tracker#267]
### FreePBX Version

FreePBX 13/14

### Issue Description

![FreePBX error](https://github.com/FreePBX/issue-tracker/assets/173242654/f5776c31-69ac-446a-9052-4221c29cbf0d)

### Operating Environment

I am facing this issue from last two day.

**Comment by kapilgupta01** [comment]
Hi @paramjeetSingh84 Freepbx 13/14 is EOL so request you to please try with Freepbx 16/17,

Also, check if you have proper php plugins installed in your system to support your php mysql driver. 

Regards
Kapil
