### ISSUE TITLE
[bug]: PJSIP Endpoints for extensions have double auth settings

### ISSUE THREAD

**Issue by blazestudios97** [FreePBX/issue-tracker#269]
### FreePBX Version

FreePBX 17

### Issue Description

When FreePBX v17 is generating PJSIP endpoint configs for extensions it is including both `auth=` and `outbound_auth=` settings in the config. Per the Asterisk documents you should not have both auth methods in the config, it should be one or the other.

Oh and `refer_blind_progress` is outputted twice. Someone is QAing this stuff right? Someone who understands that chan_pjsip doesn't like wrong, bad or the same settings repeated in the config? Chan_sip didn't care, chan_pjsip does and this kind of thing can break stuff.

### Operating Environment

Debian 12
Asterisk 21

### Relevant log output

```shell
[100]
type=endpoint
aors=100
auth=100-auth
tos_audio=ef
tos_video=af41
cos_audio=5
cos_video=4
allow=ulaw,alaw,gsm,g726,g722
context=from-internal
callerid=Testing <100>

dtmf_mode=rfc4733
direct_media=yes
outbound_auth=100-auth
aggregate_mwi=yes
use_avpf=no
rtcp_mux=no
max_audio_streams=1
max_video_streams=1
bundle=no
ice_support=no
media_use_received_transport=no
trust_id_inbound=yes
user_eq_phone=no
media_encryption=no
timers=yes
timers_min_se=90
media_encryption_optimistic=no
refer_blind_progress=yes
refer_blind_progress=yes
rtp_timeout=30
rtp_timeout_hold=300
rtp_keepalive=0
send_pai=yes
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes
language=en
one_touch_recording=on
record_on_feature=apprecord
record_off_feature=apprecord
```

**Comment by kapilgupta01** [comment]
core v17.0.9.70
