### ISSUE TITLE
Sysadmin storage alerts

### ISSUE THREAD

**Issue by yeya** [FreePBX/issue-tracker#27]
### FreePBX Version

FreePBX 16

### Improvement Description

In sysadmin module, storage - add an option to silence specific drives alerts.
Ther is apps like snapd that mount drives, this drives are always 100% so the alert goes on.

**Comment by kapilgupta01** [comment]
Added drive options in Sysadmin->Storage section and by default all the drives are enabled and if someone wants can disable it. Only for Freepbx 17.

Sysadmin v17.0.1.90
Framework v17.0.17
