### ISSUE TITLE
[improvement]: Use current versions of Asterisk and fix asterisk-version-switch

### ISSUE THREAD

**Issue by blazestudios97** [FreePBX/issue-tracker#270]
### FreePBX Version

FreePBX 17

### Improvement Description

The versions of Asterisk on the system do not line up with current versions, save Asterisk v18. However, when running asterisk-version-switch it claims that Asterisk v18 is not available. 

Here is my current output of asterisk-version-switch, note the glaring contradiction in it.

```
Current version:  Asterisk 18.23.1 is running

        (LTS) = Long Term Support | (EOL) = End of Life | (S) = Standard

        Press 1 for  Asterisk 18 (Currently not available, Please select other asterisk versions)
        Press 2 for  Asterisk 18 Certified (Currently not available, Please select other asterisk versions)
        Press 3 for  Asterisk 20 (LTS)
        Press 4 for  Asterisk 21 (S)

        Press q to exit and not change your Asterisk Version
```
Yes, I was able to switch to Asterisk v18 despite asterisk-version-switch telling me it wasn't available. If it's not available, why is it in the list? If it's not available, why can I select it and it install Asterisk v18 without any issues?

Selecting Asterisk v20 installs Asterisk v20.4.0 which is from July 2023, current version is 20.8.1.

Selecting Asterisk v21 (and the default install) install Asterisk v21.0.2 which is from December 2023, current version is 21.3.1

Selecting Asterisk v18, which is not supposed to be available, not only installs Asterisk v18 it's the only version of Asterisk that is current, installing the latest version of 18.23.1

Can we please get the versions of Asterisk 20 and 21 up to date, who knows how many feature adds or bug fixes are being missed being  6 months to a year behind on versions.

**Comment by ramarajan222** [comment]
Published latest asterisk version for asterisk and asterisk-version-switch

Latest version are below
1.Asterisk 21 => 21.3.1
2.Asterisk 20 => 20.8.1
3.asterisk-version-switch =>6.1-27.sng12

Upgrade the packages to the latest release, please reopen the ticket if you find any issues. thanks.
