### ISSUE TITLE
[new-feature]: Yealink OUI Add

### ISSUE THREAD

**Issue by jloder01** [FreePBX/issue-tracker#273]
### FreePBX Version

FreePBX 16

### Feature Description

Can we get the OUI's for Yealink T46U phones added to the Endpoint Manager so network scan will find them? The following are needed:

80:5E:C0
80:5E:0C
24:9A:D8
C4:FC:22
44:DB:D2

Thank you for adding these.

**Comment by kapilgupta01** [comment]
Its already the part of endpoint v16.0.86.24.

Please check if you can upgrade to ^ version, if you are not getting the updated module then please check your module renew license. 

Thanks
