### ISSUE TITLE
[bug]: Cannot move voicemail messages with UCP after update

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#275]
### FreePBX Version

FreePBX 16

### Issue Description

ReF
https://community.freepbx.org/t/cannot-move-voicemail-messages-with-ucp-after-update/97298

This issue occurs when the UI language is set to other than  English

### Operating Environment

FreePBX V16

**Comment by jissphilip** [comment]
voicemail-16.0.55
 voicemail version 17.0.5.22
