### ISSUE TITLE
Unable to write to /etc/wanpipe/global.conf

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#276]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

In FreePBX Dashboard, “Unable to write to /etc/wanpipe/global.conf” error and when I click it, it says “Please change permissions on /etc/wanpipe/global.conf or disable Sangoma DIGIUM mode.”

Thanks

### Operating Environment

fpbx17, hardware with sangoma card installed.

**Comment by Akarsh04** [comment]
dahdiconfig v17.0.1.12
