### ISSUE TITLE
Advanced Recovery Not Installing 

### ISSUE THREAD

**Issue by jasonurkow** [FreePBX/issue-tracker#280]
### FreePBX Version

FreePBX 17

### Issue Description

I have purchased the Advanced Recovery modules and a few others but only the Advanced Recovery module will not activate/load after updating the subscription.

### Operating Environment

FreePBX 17.0.16
Advanced Recovery not listed with fwconsole ms list

**Comment by kapilgupta01** [comment]
Hi @jasonurkow Can you please "cat /etc/sangoma/pbx-brand" output ? 
thanks

**Comment by jasonurkow** [comment]
> Hi @jasonurkow Can you please "cat /etc/sangoma/pbx-brand" output ? thanks

FreePBXDistro

**Comment by kapilgupta01** [comment]
Can you please try to check now? 

fwconsole ma downloadinstall adv_recovery

**Comment by jasonurkow** [comment]
> Can you please try to check now?
> 
> fwconsole ma downloadinstall adv_recovery

Woohoo it is installed and activated now!

**Comment by kapilgupta01** [comment]
great thanks for the prompt feedback. Please give a try and let us know if you face any issues, We are also doing QA for this module right now. thanks

**Comment by jasonurkow** [comment]
> great thanks for the prompt feedback. Please give a try and let us know if you face any issues, We are also doing QA for this module right now. thanks

So I am following the instructions at https://sangomakb.atlassian.net/wiki/spaces/PG/pages/35783290/Advanced+Recovery#Overview

This is there error I am getting on step one

sudo -u asterisk ssh-copy-id -i  /home/asterisk/.ssh/id_rsa.pub root@172.31.2.130

/usr/bin/ssh-copy-id: ERROR: failed to open ID file '/home/asterisk/.ssh/id_rsa.pub': No such file

**Comment by kapilgupta01** [comment]
Can you please check below wiki to ensure you are following the steps as mentioned in below wiki - 
https://sangomakb.atlassian.net/wiki/spaces/FP/pages/281542711/Advanced+Recovery+in+Freepbx17

**Comment by jasonurkow** [comment]
This is what I get when I click on save in the "Public key of other system"

![public key saving error](https://github.com/FreePBX/issue-tracker/assets/9469663/1b3ea93f-4e75-4add-b371-eae742545dfc)

**Comment by girishmani1992** [comment]
@jasonurkow ,

This occurs in new systems where authorized_keys not present. To resolve this, open "Backup & Restore" UI from new tab once again, so that "authorized_keys" file is created automatically in the path "/home/asterisk/.ssh"

Thanks

**Comment by jasonurkow** [comment]
> @jasonurkow ,
> 
> This occurs in new systems where authorized_keys not present. To resolve this, open "Backup & Restore" UI from new tab once again, so that "authorized_keys" file is created automatically in the path "/home/asterisk/.ssh"
> 
> Thanks

Thank you, that worked and I have now saved both of the Public Keys.  

When I run fwconsole --advr --precheck 172.31.2.130 I get
![precheck error](https://github.com/FreePBX/issue-tracker/assets/9469663/4987effe-1936-47b0-92f5-0a1e8c237890)

Do I have to restart something?

**Comment by girishmani1992** [comment]
Try like this @jasonurkow  

fwconsole advr --precheck 172.31.2.130

**Comment by jasonurkow** [comment]
> fwconsole advr --precheck 172.31.2.130

That worked!  documentation needs updating here - https://sangomakb.atlassian.net/wiki/spaces/FP/pages/281542711/Advanced+Recovery+in+Freepbx17

**Comment by jasonurkow** [comment]
Ok, now Advanced recovery module will not load and give error - Undefined variable $optgroup

I've attached HTML file in a zip.

[There was an error.zip](https://github.com/user-attachments/files/16018472/There.was.an.error.zip)

**Comment by kapilgupta01** [comment]
hi @jasonurkow can you please try with v17.0.2.27 ?

fwconsole ma downloadinstall adv_recovery --tag=17.0.2.27 

thanks

**Comment by jasonurkow** [comment]
Hello @kguptasangoma that version works flawlessly so far!  I did the Quick Configure and the servers are now syncing! 

I'll keep you posted after they are done syncing

**Comment by kapilgupta01** [comment]
thanks @jasonurkow

**Comment by jasonurkow** [comment]
The Sync was successful and I performed a simulated failover by disconnecting the network cable on the primary server.  After 60 seconds the Secondary became active.  I reconnected the network on the Primary and after about a minute it became Active and the Secondary went into a Standby state.

Thank you to everyone who assisted me with getting this going!
