### ISSUE TITLE
[improvement]:  Ability to disable / dismiss No Swap warning

### ISSUE THREAD

**Issue by spessoni** [FreePBX/issue-tracker#282]
### FreePBX Version

FreePBX 17

### Improvement Description

I would like the ability to dismiss (not hide) the _no swap_ waning. I am installing as a LXC (Container) on Proxmox with a ZFS file system.  The default Proxmox ZFS install did not create a swap partition and it is not recommend to create a swap partition on ZFS.

https://pve.proxmox.com/pve-docs/local-zfs-plain.html (SWAP on ZFS):

> Swap-space created on a zvol may generate some troubles, like blocking the server or generating a high IO load, often seen when starting a Backup to an external Storage.
> 
> We strongly recommend to use enough memory, so that you normally do not run into low memory situations. Should you need or want to add swap, it is preferred to create a partition on a physical disk and use it as a swap device. 

I am _not_ running a large PBX (just a couple of extensions) and _should not_ run into any memory limitations.

**Comment by dolesec** [comment]
why not just create it @spessoni ?

this worked for me on lightsail ... https://www.webhostingforbeginners.net/how-to-add-swap-space-on-aws-lightsail-server-instance/

```
fallocate -l 512M /swapfile
ls -lh /swapfile
sudo chmod 600 /swapfile
ls -lh /swapfile
sudo swapon /swapfile
swapon /swapfile
mkswap /swapfile
sudo swapon /swapfile
sudo free -h
sudo cp /etc/fstab /etc/fstab.bak
sudo vi /etc/fstab
sudo vi /etc/fstab
sudo swapon --show or free -h
sudo swapon --show 
```

**Comment by spessoni** [comment]
Thanks for the reply @dolesec !

Unfortunately, ZFS won't support this:
```
swapon: /swapfile: skipping - it appears to have holes.
```

https://zfsonlinux.org/manpages/0.8.0/man8/zfs.8.html#lbAN - ZFS Volumes as Swap:

> Do not swap to a file on a ZFS file system. A ZFS swap file configuration is not supported.

**Comment by dolesec** [comment]
interesting  @spessoni - the only place I really encounter that is TrueNAS :(

this may help @spessoni  https://askubuntu.com/questions/1198903/can-not-use-swap-file-on-zfs-files-with-holes

**Comment by spessoni** [comment]
Yes! I saw that as well @dolesec. But it is against the ZFS recommend way of doing things. This leaves me 3 options:

- Ignore the error in FreePBX, but I will constantly have that warning as it is not dismissible.
- Repartition ProxMox to allow for ZFS and Swap (I only have one SSD, ZFS allows better recovery from power off conditions)
- Try to setup a zram or zswap, but this would be a waste of resources.

I would prefer to be able to dismiss the error (I would even take an advanced option somewhere) and move on. :)

It did see a hacky way to disable it by editing the machine brand with MySQL, but I don't know what other repercussions that would incur:

[How to remove the swap space warning on Freepbx](https://community.freepbx.org/t/how-to-remove-the-swap-space-warning-on-freepbx/79337)

```
sudo mysql
use asterisk;
UPDATE freepbx_settings SET value = 'PBXact UCC' WHERE keyword = 'DASHBOARD_FREEPBX_BRAND';
truncate table notifications;
```

**Comment by dolesec** [comment]
understood @spessoni  - this is a one-off, if you have a workaround to clear them (it looks safe enough for the task) I'd use it.  btw, have you checked advanced settings, maybe there's something to suppress dashboard warnings? however, that's kinda the purpose of having a dashboard.

**Comment by kapilgupta01** [comment]
Freepbx 17 has flexibility to run on various different installation types/flavors of Debian and this kind of OS level constraints, I think should be bit relax.

just fyi - We are in the process of improving sysadmin->storage alert notification section to let user to choose which drive to monitor for alert so we could add option in that section itself to let user to choose swap memory warning on/off.  
Ref - https://github.com/FreePBX/issue-tracker/issues/27

**Comment by kapilgupta01** [comment]
Added Configuration option in Sysadmin->Storage section i.e. Enable/Disable SWAP warning" which is enabled by default and if someone wants can disable it. Only for Freepbx 17.

Sysadmin v17.0.1.90
Framework v17.0.17
