### ISSUE TITLE
[improvement]: 2 minor PRs for improved documentation of security reporting processes

### ISSUE THREAD

**Issue by chrsmj** [FreePBX/issue-tracker#29]
### FreePBX Version

FreePBX 17

### Improvement Description

Improved documentation to make it clearer where to go and what to do when you report a security vulnerability:

1. https://github.com/FreePBX/.github/pull/2
2. https://github.com/FreePBX/issue-tracker/pull/28

**Comment by jcolp** [comment]
I will look at these and consider changes. I am trying to use a single security policy for everything, and so having forked versions is not something I am keen on.

**Comment by jcolp** [comment]
And please split this up into two separate PRs.
