### ISSUE TITLE
[bug]: Unable to provision Sangoma S500 phones using endpoint manager.

### ISSUE THREAD

**Issue by jaredjhoughton** [FreePBX/issue-tracker#290]
### FreePBX Version

FreePBX 17

### Issue Description

After last night, I am unable to provision phones using Endpoint Manager. It was working, but then it stopped.

### Operating Environment

FreePBX 17.0.16
Asterisk 21.3.1

+---------------------+-----------+---------+-------------+-----------+
| Module              | Version   | Status  | License     | Signature |
+---------------------+-----------+---------+-------------+-----------+
| accountcodepreserve | 17.0.0.1  | Enabled | GPLv2       | Sangoma   |
| allowlist           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| amd                 | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1  | Enabled | GPLv3+      | Sangoma   |
| api                 | 17.0.1.4  | Enabled | AGPLv3+     | Sangoma   |
| areminder           | 17.0.3.10 | Enabled | Commercial  | Sangoma   |
| arimanager          | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| backup              | 17.0.5.54 | Enabled | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| broadcast           | 17.0.1.6  | Enabled | Commercial  | Sangoma   |
| builtin             |           | Enabled |             | Unsigned  |
| bulkhandler         | 17.0.5    | Enabled | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.15 | Enabled | GPLv3+      | Sangoma   |
| callaccounting      | 17.0.5    | Enabled | Commercial+ | Sangoma   |
| callback            | 17.0.2.1  | Enabled | GPLv3+      | Sangoma   |
| callerid            | 17.0.1    | Enabled | Commercial  | Sangoma   |
| callforward         | 17.0.1.6  | Enabled | AGPLv3+     | Sangoma   |
| calllimit           | 17.0.1.2  | Enabled | Commercial  | Sangoma   |
| callrecording       | 17.0.3.6  | Enabled | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4  | Enabled | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.15 | Enabled | GPLv3+      | Sangoma   |
| cdrpro              | 17.0.3.17 | Enabled | Commercial  | Sangoma   |
| cel                 | 17.0.2.8  | Enabled | GPLv3+      | Sangoma   |
| certman             | 17.0.3.12 | Enabled | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2  | Enabled | GPLv3+      | Sangoma   |
| conferencespro      | 17.0.1.7  | Enabled | Commercial  | Sangoma   |
| configedit          | 17.0.1.1  | Enabled | AGPLv3+     | Sangoma   |
| contactmanager      | 17.0.5.11 | Enabled | GPLv3+      | Sangoma   |
| core                | 17.0.9.72 | Enabled | GPLv3+      | Sangoma   |
| cos                 | 17.0.1.1  | Enabled | Commercial  | Sangoma   |
| customappsreg       | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.2  | Enabled | GPLv2+      | Sangoma   |
| dashboard           | 17.0.4.3  | Enabled | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| disa                | 17.0.3    | Enabled | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3  | Enabled | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.1  | Enabled | GPLv3+      | Sangoma   |
| endpoint            | 17.0.1.71 | Enabled | Commercial  | Sangoma   |
| extensionroutes     | 17.0.1    | Enabled | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4  | Enabled | GPLv3+      | Sangoma   |
| faxpro              | 17.0.1.16 | Enabled | Commercial  | Sangoma   |
| featurecodeadmin    | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.21 | Enabled | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.8  | Enabled | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.26 | Enabled | AGPLv3+     | Sangoma   |
| framework           | 17.0.16   | Enabled | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6  | Enabled | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1    | Enabled | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1    | Enabled | GPLv2+      | Sangoma   |
| ivr                 | 17.0.6    | Enabled | GPLv3+      | Sangoma   |
| languages           | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3  | Enabled | GPLv3+      | Sangoma   |
| manager             | 17.0.5    | Enabled | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3    | Enabled | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| music               | 17.0.4    | Enabled | GPLv3+      | Sangoma   |
| outcnam             | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| paging              | 17.0.3    | Enabled | GPLv3+      | Sangoma   |
| pagingpro           | 17.0.1.6  | Enabled | Commercial  | Sangoma   |
| parking             | 17.0.2.4  | Enabled | GPLv3+      | Sangoma   |
| parkpro             | 17.0.1.4  | Enabled | Commercial  | Sangoma   |
| pbxmfa              | 17.0.2    | Enabled | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1    | Enabled | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2  | Enabled | GPLv3+      | Sangoma   |
| pinsetspro          | 17.0.2    | Enabled | Commercial  | Sangoma   |
| pm2                 | 17.0.3.2  | Enabled | AGPLv3+     | Sangoma   |
| pms                 | 17.0.2.15 | Enabled | Commercial  | Sangoma   |
| presencestate       | 17.0.2.4  | Enabled | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4  | Enabled | GPLv3+      | Sangoma   |
| queues              | 17.0.1.9  | Enabled | GPLv2+      | Sangoma   |
| queuestats          | 17.0.1.7  | Enabled | Commercial  | Sangoma   |
| qxact_reports       | 17.0.2    | Enabled | Commercial  | Sangoma   |
| recording_report    | 17.0.3.8  | Enabled | Commercial  | Sangoma   |
| recordings          | 17.0.2.2  | Enabled | GPLv3+      | Sangoma   |
| restapps            | 17.0.1.19 | Enabled | Commercial  | Sangoma   |
| ringgroups          | 17.0.2.4  | Enabled | GPLv3+      | Sangoma   |
| sangomaconnect      | 17.0.1.35 | Enabled | Commercial  | Sangoma   |
| sangomacrm          | 17.0.1.8  | Enabled | Commercial  | Sangoma   |
| sangomartapi        | 17.0.1.26 | Enabled | Commercial  | Sangoma   |
| setcid              | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.8  | Enabled | AGPLv3+     | Sangoma   |
| sipstation          | 17.0.3.3  | Enabled | Commercial  | Sangoma   |
| sms                 | 17.0.1.13 | Enabled | Commercial  | Sangoma   |
| smsplus             | 17.0.3    | Enabled | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1  | Enabled | GPLv3+      | Sangoma   |
| superfecta          | 17.0.1.10 | Enabled | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.89 | Enabled | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.17 | Enabled | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1    | Enabled | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.19 | Enabled | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.25 | Enabled | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| vmnotify            | 17.0.1.7  | Enabled | Commercial  | Sangoma   |
| voicemail           | 17.0.5.22 | Enabled | GPLv3+      | Sangoma   |
| voicemail_report    | 17.0.1.1  | Enabled | Commercial  | Sangoma   |
| voipinnovations     | 17.0.1.4  | Enabled | Commercial  | Sangoma   |
| vqplus              | 17.0.1.16 | Enabled | Commercial  | Sangoma   |
| weakpasswords       | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| webcallback         | 17.0.4    | Enabled | Commercial  | Sangoma   |
| webrtc              | 17.0.2.2  | Enabled | GPLv3+      | Sangoma   |
+---------------------+-----------+---------+-------------+-----------+

### Relevant log output

```shell
4034	[2024-07-03 13:21:18] ERROR[124015] loader.c: Error loading module 'chan_local.so': /lib/x86_64-linux-gnu/asterisk/modules/chan_local.so: cannot open shared object file: No such file or directory	
4035	[2024-07-03 13:21:18] ERROR[124015] loader.c: Error loading module 'res_pjsip_phoneprov_provider.so', missing dependency: res_phoneprov	
4036	[2024-07-03 13:21:18] ERROR[124015] loader.c: res_timing_dahdi declined to load.	
4037	[2024-07-03 13:21:18] ERROR[124015] loader.c: chan_mobile declined to load.	
4038	[2024-07-03 13:21:18] ERROR[124015] loader.c: cdr_csv declined to load.	
4039	[2024-07-03 13:21:18] ERROR[124015] loader.c: cdr_sqlite3_custom declined to load.	
4040	[2024-07-03 13:21:18] ERROR[124015] loader.c: cel_sqlite3_custom declined to load.	
4041	[2024-07-03 13:21:18] ERROR[124015] loader.c: res_hep_rtcp declined to load.	
4042	[2024-07-03 13:21:18] ERROR[124015] loader.c: res_hep_pjsip declined to load.
```

**Comment by kapilgupta01** [comment]
Hi @jaredjhoughton Do you mean any module update broke the provisioning? 
Can you please see 'fwconsole debug" and "/var/log/apache2/error.log" if you see any problem.

**Comment by jaredjhoughton** [comment]
Hello @kguptasangoma,

Thank you for responding. This is what I find in error.log:
[Fri Jul 05 00:00:01.361065 2024] [mpm_prefork:notice] [pid 674] AH00163: Apache/2.4.59 (Debian) OpenSSL/3.0.13 configured -- resuming normal operations
[Fri Jul 05 00:00:01.361629 2024] [core:notice] [pid 674] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jul 05 21:33:14.554495 2024] [mpm_prefork:notice] [pid 674] AH00170: caught SIGWINCH, shutting down gracefully
[Fri Jul 05 21:36:12.076607 2024] [so:warn] [pid 534] AH01574: module ssl_module is already loaded, skipping
[Fri Jul 05 21:36:12.353106 2024] [mpm_prefork:notice] [pid 654] AH00163: Apache/2.4.59 (Debian) OpenSSL/3.0.13 configured -- resuming normal operations
[Fri Jul 05 21:36:12.353150 2024] [core:notice] [pid 654] AH00094: Command line: '/usr/sbin/apache2'

This is what I get from DBUG:

==> /var/log/asterisk/freepbx.log <==
[2024-07-06 04:08:07] [freepbx.INFO]: Deprecated way to add Console commands for module pbxmfa, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
[2024-07-06 04:08:07] [freepbx.INFO]: Deprecated way to add Console commands for module sangomartapi, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
[2024-07-06 04:08:07] [freepbx.INFO]: Deprecated way to add Console commands for module vmnotify, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
[2024-07-06 04:08:07] [freepbx.INFO]: Deprecated way to add Console commands for module voicemail, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
[2024-07-06 04:08:54] [freepbx.INFO]: Deprecated way to add Console commands for module api, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
[2024-07-06 04:08:54] [freepbx.INFO]: Deprecated way to add Console commands for module backup, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
[2024-07-06 04:08:54] [freepbx.INFO]: Deprecated way to add Console commands for module pbxmfa, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
[2024-07-06 04:08:54] [freepbx.INFO]: Deprecated way to add Console commands for module sangomartapi, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
[2024-07-06 04:08:54] [freepbx.INFO]: Deprecated way to add Console commands for module vmnotify, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
[2024-07-06 04:08:54] [freepbx.INFO]: Deprecated way to add Console commands for module voicemail, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module api, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module api, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module backup, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module backup, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module pbxmfa, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module pbxmfa, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module sangomartapi, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module sangomartapi, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module vmnotify, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module voicemail, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module vmnotify, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []
OUT > [2024-07-06 04:09:02] [freepbx.INFO]: Deprecated way to add Console commands for module voicemail, adding console commands this way can have negative performance impacts. Please use module.xml. See: https://wiki.freepbx.org/display/FOP/Adding+fwconsole+commands [] []

As shown in the original post, I only get errors from Asterisks about the res_pjsip_phoneprov_provider.so module. I have also rebuilt everything from scratch, and the problem still exists. I don't know if it was an update. I should have checked before I blew out my previous setup. This instance of FreePBX is set up in a test environment. I successfully provisioned the phone I used to test on my production Freepbx 15.

Please let me know if you need me to provide anything else.
Jared

**Comment by jaredjhoughton** [comment]
Hello @kguptasangoma 

Thank you for getting back to me. I have found the issue that was causing my problem. It was self-inflicted. I hope you did not spend a lot of time on this.

Again, thank you!
Jared
