### ISSUE TITLE
[bug]: maxptime must be changed to multiples of 20

### ISSUE THREAD

**Issue by eduardomazolini** [FreePBX/issue-tracker#294]
### FreePBX Version

FreePBX 15

### Issue Description

On the operator's network Vivo/Telefônica in Brazil, when calling an iPhone device, the call is not completed.
The device shows a missed call, but it doesn't even ring.

The bug was reported for Asterisk but there are no fixes for older versions. So I'm reporting here because this is the distribution I actually use.

https://github.com/asterisk/asterisk/issues/260

```
SDP: Session Description Protocol

      a=maxptime:<maximum packet time>

         This gives the maximum amount of media that can be encapsulated
         in each packet, expressed as time in milliseconds.  The time
         SHALL be calculated as the sum of the time the media present in
         the packet represents.  For frame-based codecs, the time SHOULD
         be an integer multiple of the frame size.  This attribute is
         probably only meaningful for audio data, but may be used with
         other media types if it makes sense.  It is a media-level
         attribute, and it is not dependent on charset.  Note that this
         attribute was introduced after RFC 2327, and non-updated
         implementations will ignore this attribute.

```

source: https://datatracker.ietf.org/doc/html/rfc4566

When we use alaw, ulaw or another codec with 20 ms of audio for exemple, we break the RFC because the fixed value of 150 does not respect "time SHOULD be an integer multiple of the frame size."

### Operating Environment

______                   ______ ______ __   __
|  ___|                  | ___ \| ___ \\ \ / /
| |_    _ __   ___   ___ | |_/ /| |_/ / \ V /
|  _|  | '__| / _ \ / _ \|  __/ | ___ \ /   \
| |    | |   |  __/|  __/| |    | |_/ // /^\ \
\_|    |_|    \___| \___|\_|    \____/ \/   \/

FW Console - FreePBX Utility 15.0.37.1

+---------------------+------------+------------+------------+-----------+
| Módulo              | Versão     | Estado     | Licença    | Signature |
+---------------------+------------+------------+------------+-----------+
| accountcodepreserve | 13.0.2.2   | Habilitado | GPLv2      | Sangoma   |
| amd                 | 15.0.3     | Habilitado | GPLv3+     | Sangoma   |
| announcement        | 15.0.3.13  | Habilitado | GPLv3+     | Sangoma   |
| api                 | 15.0.10    | Habilitado | AGPLv3+    | Sangoma   |
| arimanager          | 15.0.3.20  | Habilitado | GPLv3+     | Sangoma   |
| asterisk-cli        | 14.0.4     | Habilitado | GPLv3+     | Sangoma   |
| asteriskinfo        | 15.0.14    | Habilitado | GPLv3+     | Sangoma   |
| backup              | 15.0.25    | Habilitado | GPLv3+     | Sangoma   |
| blacklist           | 15.0.4     | Habilitado | GPLv3+     | Sangoma   |
| builtin             |            | Habilitado |            | Unsigned  |
| bulkhandler         | 15.0.4     | Habilitado | GPLv3+     | Sangoma   |
| calendar            | 15.0.10    | Habilitado | GPLv3+     | Sangoma   |
| callback            | 15.0.12    | Habilitado | GPLv3+     | Sangoma   |
| callforward         | 15.0.16    | Habilitado | AGPLv3+    | Sangoma   |
| callrecording       | 15.0.7.29  | Habilitado | AGPLv3+    | Sangoma   |
| callwaiting         | 15.0.4.6   | Habilitado | GPLv3+     | Sangoma   |
| cdr                 | 15.0.17.28 | Habilitado | GPLv3+     | Sangoma   |
| cel                 | 15.0.15.19 | Habilitado | GPLv3+     | Sangoma   |
| certman             | 15.0.49    | Habilitado | AGPLv3+    | Sangoma   |
| cidlookup           | 15.0.27    | Habilitado | GPLv3+     | Sangoma   |
| conferences         | 15.0.7.11  | Habilitado | GPLv3+     | Sangoma   |
| configedit          | 13.0.7.3   | Habilitado | AGPLv3+    | Sangoma   |
| contactmanager      | 15.0.11    | Habilitado | GPLv3+     | Sangoma   |
| core                | 15.0.22.34 | Habilitado | GPLv3+     | Sangoma   |
| customappsreg       | 15.0.14    | Habilitado | GPLv3+     | Sangoma   |
| cxpanel             | 15.0.4     | Habilitado | GPLv3      | Sangoma   |
| dahdiconfig         | 15.0.5.9   | Habilitado | GPLv3+     | Sangoma   |
| dashboard           | 15.0.16    | Habilitado | AGPLv3+    | Sangoma   |
| daynight            | 15.0.12    | Habilitado | GPLv3+     | Sangoma   |
| dictate             | 15.0.7     | Habilitado | GPLv3+     | Sangoma   |
| directory           | 15.0.18    | Habilitado | GPLv3+     | Sangoma   |
| disa                | 15.0.4.9   | Habilitado | AGPLv3+    | Sangoma   |
| donotdisturb        | 15.0.10    | Habilitado | GPLv3+     | Sangoma   |
| dynroute            | 15.0.3     | Habilitado | GPLv3+     | Sangoma   |
| extensionsettings   | 13.0.4     | Habilitado | GPLv3+     | Sangoma   |
| fax                 | 15.0.22    | Habilitado | GPLv3+     | Sangoma   |
| featurecodeadmin    | 13.0.6.11  | Habilitado | GPLv3+     | Sangoma   |
| filestore           | 15.0.7     | Habilitado | AGPLv3     | Sangoma   |
| findmefollow        | 15.0.37    | Habilitado | GPLv3+     | Sangoma   |
| firewall            | 15.0.43    | Habilitado | AGPLv3+    | Sangoma   |
| framework           | 15.0.37.1  | Habilitado | GPLv2+     | Sangoma   |
| fw_langpacks        | 14.0.1     | Habilitado | GPLv3+     | Sangoma   |
| hotelwakeup         | 15.0.5.5   | Habilitado | GPLv2      | Sangoma   |
| iaxsettings         | 15.0.8     | Habilitado | AGPLv3     | Sangoma   |
| infoservices        | 15.0.3     | Habilitado | GPLv2+     | Sangoma   |
| irc                 | 13.0.1     | Habilitado | GPLv3+     | Sangoma   |
| ivr                 | 15.0.30    | Habilitado | GPLv3+     | Sangoma   |
| languages           | 15.0.13    | Habilitado | GPLv3+     | Sangoma   |
| logfiles            | 15.0.15    | Habilitado | GPLv3+     | Sangoma   |
| manager             | 15.0.21    | Habilitado | GPLv2+     | Sangoma   |
| miscapps            | 15.0.10    | Habilitado | GPLv3+     | Sangoma   |
| miscdests           | 15.0.2.12  | Habilitado | GPLv3+     | Sangoma   |
| music               | 15.0.22    | Habilitado | GPLv3+     | Sangoma   |
| outroutemsg         | 15.0.9     | Habilitado | GPLv3+     | Sangoma   |
| paging              | 15.0.4.35  | Habilitado | GPLv3+     | Sangoma   |
| parking             | 15.0.15.4  | Habilitado | GPLv3+     | Sangoma   |
| phonebook           | 15.0.12    | Habilitado | GPLv3+     | Sangoma   |
| phpinfo             | 13.0.2     | Habilitado | GPLv2+     | Sangoma   |
| pinsets             | 15.0.1.15  | Habilitado | GPLv3+     | Sangoma   |
| pm2                 | 15.0.10    | Habilitado | AGPLv3+    | Sangoma   |
| presencestate       | 15.0.11    | Habilitado | GPLv3+     | Sangoma   |
| printextensions     | 13.0.3.4   | Habilitado | GPLv3+     | Sangoma   |
| queueprio           | 15.0.10    | Habilitado | GPLv3+     | Sangoma   |
| queues              | 15.0.38    | Habilitado | GPLv2+     | Sangoma   |
| recordings          | 15.0.5     | Habilitado | GPLv3+     | Sangoma   |
| ringgroups          | 15.0.11.17 | Habilitado | GPLv3+     | Sangoma   |
| setcid              | 15.0.9     | Habilitado | GPLv3+     | Sangoma   |
| sipsettings         | 15.0.11    | Habilitado | AGPLv3+    | Sangoma   |
| sms                 | 15.0.37    | Habilitado | Commercial | Sangoma   |
| soundlang           | 15.0.5.10  | Habilitado | GPLv3+     | Sangoma   |
| superfecta          | 15.0.5     | Habilitado | GPLv2+     | Sangoma   |
| sysadmin            | 15.0.30    | Habilitado | Commercial | Sangoma   |
| timeconditions      | 15.0.15.11 | Habilitado | GPLv3+     | Sangoma   |
| tts                 | 15.0.12    | Habilitado | GPLv3+     | Sangoma   |
| ttsengines          | 15.0.4.7   | Habilitado | AGPLv3     | Sangoma   |
| ucp                 | 15.0.15    | Habilitado | AGPLv3+    | Sangoma   |
| userman             | 15.0.69.16 | Habilitado | AGPLv3+    | Sangoma   |
| versionupgrade      | 15.0.42    | Habilitado | Commercial | Sangoma   |
| vmblast             | 15.0.11.8  | Habilitado | GPLv3+     | Sangoma   |
| voicemail           | 15.0.29    | Habilitado | GPLv3+     | Sangoma   |
| weakpasswords       | 13.0.2     | Habilitado | GPLv3+     | Sangoma   |
| webrtc              | 15.0.10.13 | Habilitado | GPLv3+     | Sangoma   |
| xmpp                | 15.0.6.12  | Habilitado | AGPLv3     | Sangoma   |
+---------------------+------------+------------+------------+-----------+

### Relevant log output

```shell
attention to: a=maxptime:150

<--- Transmitting SIP request (1017 bytes) to UDP:10.255.240.111:5060 --->
INVITE sip:9XXXXXXX@10.255.240.111 SIP/2.0
Via: SIP/2.0/UDP 10.17.XX.XXX:5060;rport;branch=z9hG4bKPj6139179d-2e3f-4864-b346-d56fc952b416
From: <sip:193855XXXX@10.17.XX.XXX>;tag=036176f7-9931-482c-8be8-09d52241d253
To: <sip:9XXXXXXX@10.255.240.111>
Contact: <sip:asterisk@10.17.XX.XXX:5060>
Call-ID: 4515bba6-e134-45cc-b422-e687cc2e596e
CSeq: 501 INVITE
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub, histinfo
Session-Expires: 1800
Min-SE: 90
Max-Forwards: 70
User-Agent: FPBX-15.0.17.55(16.15.1)
Content-Type: application/sdp
Content-Length:   339

v=0
o=- 1429284841 1429284841 IN IP4 10.17.XX.XXX
s=Asterisk
c=IN IP4 10.17.XX.XXX
t=0 0
m=audio 12752 RTP/AVP 8 0 111 9 3 101
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:111 G726-32/8000
a=rtpmap:9 G722/8000
a=rtpmap:3 GSM/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:150
a=sendrecv

<--- Received SIP response (335 bytes) from UDP:10.255.240.111:5060 --->
SIP/2.0 100 Trying
Via: SIP/2.0/UDP 10.17.XX.XXX:5060;branch=z9hG4bKPj6139179d-2e3f-4864-b346-d56fc952b416;rport=5060
From: <sip:193855XXXX@10.17.XX.XXX>;tag=036176f7-9931-482c-8be8-09d52241d253
To: <sip:9XXXXXXX@10.255.240.111>;tag=gK04db6aaa
Call-ID: 4515bba6-e134-45cc-b422-e687cc2e596e
CSeq: 501 INVITE
Content-Length: 0


<--- Received SIP response (1087 bytes) from UDP:10.255.240.111:5060 --->
SIP/2.0 180 Ringing
Via: SIP/2.0/UDP 10.17.XX.XXX:5060;branch=z9hG4bKPj6139179d-2e3f-4864-b346-d56fc952b416;rport=5060
From: <sip:193855XXXX@10.17.XX.XXX>;tag=036176f7-9931-482c-8be8-09d52241d253
To: <sip:9XXXXXXX@10.255.240.111>;tag=gK04db6aaa
Call-ID: 4515bba6-e134-45cc-b422-e687cc2e596e
CSeq: 501 INVITE
Contact: <sip:9XXXXXXX@10.255.240.111:5060>
Allow: INVITE,ACK,CANCEL,BYE,REGISTER,REFER,INFO,SUBSCRIBE,NOTIFY,PRACK,UPDATE,OPTIONS,MESSAGE,PUBLISH
Supported: tdialog
P-Charging-Vector: icid-value="155383cacb419fcc96119a8346689982.3899208974.262197594.19";orig-ioi=19741;term-ioi=SPO-CO-scscf01.ims.mnc010.mcc724.3gppnetwork.org
P-Early-Media: sendrecv
Mime-Version: 1.0
User-Agent: Vectura Signaling Server
Require: 100rel
RSeq: 95660
Content-Length:   222
Content-Disposition: session; handling=required
Content-Type: application/sdp

v=0
o=Sonus_UAC 388422 703400 IN IP4 10.255.240.111
s=SIP Media Capabilities
c=IN IP4 10.255.240.112
t=0 0
m=audio 61006 RTP/AVP 8 101
a=ptime:20
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=sendrecv

<--- Transmitting SIP request (439 bytes) to UDP:10.255.240.111:5060 --->
PRACK sip:9XXXXXXX@10.255.240.111:5060 SIP/2.0
Via: SIP/2.0/UDP 10.17.XX.XXX:5060;rport;branch=z9hG4bKPjc6eafa4a-120f-4620-8527-e13857fe597e
From: <sip:193855XXXX@10.17.XX.XXX>;tag=036176f7-9931-482c-8be8-09d52241d253
To: <sip:9XXXXXXX@10.255.240.111>;tag=gK04db6aaa
Call-ID: 4515bba6-e134-45cc-b422-e687cc2e596e
CSeq: 502 PRACK
RAck: 95660 501 INVITE
Max-Forwards: 70
User-Agent: FPBX-15.0.17.55(16.15.1)
Content-Length:  0


<--- Received SIP response (531 bytes) from UDP:10.255.240.111:5060 --->
SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.17.XX.XXX:5060;branch=z9hG4bKPjc6eafa4a-120f-4620-8527-e13857fe597e;rport=5060
From: <sip:193855XXXX@10.17.XX.XXX>;tag=036176f7-9931-482c-8be8-09d52241d253
To: <sip:9XXXXXXX@10.255.240.111>;tag=gK04db6aaa
Call-ID: 4515bba6-e134-45cc-b422-e687cc2e596e
CSeq: 502 PRACK
P-Charging-Vector: icid-value="155383cacb419fcc96119a8346689982.3899208974.262197594.19";orig-ioi=19741;term-ioi=SPO-CO-scscf01.ims.mnc010.mcc724.3gppnetwork.org
User-Agent: Vectura Signaling Server
Content-Length: 0


<--- Received SIP response (703 bytes) from UDP:10.255.240.111:5060 --->
SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.17.XX.XXX:5060;branch=z9hG4bKPj6139179d-2e3f-4864-b346-d56fc952b416;rport=5060
From: <sip:193855XXXX@10.17.XX.XXX>;tag=036176f7-9931-482c-8be8-09d52241d253
To: <sip:9XXXXXXX@10.255.240.111>;tag=gK04db6aaa
Call-ID: 4515bba6-e134-45cc-b422-e687cc2e596e
CSeq: 501 INVITE
Contact: <sip:9XXXXXXX@10.255.240.111:5060>
Allow: INVITE,ACK,CANCEL,BYE,REGISTER,REFER,INFO,SUBSCRIBE,NOTIFY,PRACK,UPDATE,OPTIONS,MESSAGE,PUBLISH
P-Charging-Vector: icid-value="155383cacb419fcc96119a8346689982.3899208974.262197594.19";orig-ioi=19741;term-ioi=SPO-CO-scscf01.ims.mnc010.mcc724.3gppnetwork.org
User-Agent: Vectura Signaling Server
Supported: replaces
Content-Length: 0


<--- Transmitting SIP request (411 bytes) to UDP:10.255.240.111:5060 --->
ACK sip:9XXXXXXX@10.255.240.111:5060 SIP/2.0
Via: SIP/2.0/UDP 10.17.XX.XXX:5060;rport;branch=z9hG4bKPjbffe1ce3-e2d8-40cb-8ca6-f75e130ce3fe
From: <sip:193855XXXX@10.17.XX.XXX>;tag=036176f7-9931-482c-8be8-09d52241d253
To: <sip:9XXXXXXX@10.255.240.111>;tag=gK04db6aaa
Call-ID: 4515bba6-e134-45cc-b422-e687cc2e596e
CSeq: 501 ACK
Max-Forwards: 70
User-Agent: FPBX-15.0.17.55(16.15.1)
Content-Length:  0


<--- Received SIP request (602 bytes) from UDP:10.255.240.111:5060 --->
BYE sip:asterisk@10.17.XX.XXX:5060 SIP/2.0
Via: SIP/2.0/UDP 10.255.240.111:5060;branch=z9hG4bK04Bea4dc8e9373cd2e5
From: <sip:9XXXXXXX@10.255.240.111>;tag=gK04db6aaa
To: <sip:193855XXXX@10.17.XX.XXX>;tag=036176f7-9931-482c-8be8-09d52241d253
Call-ID: 4515bba6-e134-45cc-b422-e687cc2e596e
CSeq: 564493 BYE
Max-Forwards: 63
P-Charging-Vector: icid-value="155383cacb419fcc96119a8346689982.3899208974.262197594.19";orig-ioi=19741;term-ioi=SPO-CO-scscf01.ims.mnc010.mcc724.3gppnetwork.org
User-Agent: Vectura Signaling Server
Reason: Q.850;cause=16;text="Normal call clearing"
Content-Length: 0


<--- Transmitting SIP response (373 bytes) to UDP:10.255.240.111:5060 --->
SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.255.240.111:5060;rport=5060;received=10.255.240.111;branch=z9hG4bK04Bea4dc8e9373cd2e5
Call-ID: 4515bba6-e134-45cc-b422-e687cc2e596e
From: <sip:9XXXXXXX@10.255.240.111>;tag=gK04db6aaa
To: <sip:193855XXXX@10.17.XX.XXX>;tag=036176f7-9931-482c-8be8-09d52241d253
CSeq: 564493 BYE
Server: FPBX-15.0.17.55(16.15.1)
Content-Length:  0
```

**Comment by jcolp** [comment]
What exactly are you expecting the FreePBX project to do?

**Comment by kapilgupta01** [comment]
Hi @eduardomazolini Can you please share more details with respect to issue you are expecting Freepbx project to fix ?

**Comment by kapilgupta01** [comment]
Closing as there is nothing to fix in the freepbx. Please feel free to re-open if you find any issue in Freepbx. thanks
