### ISSUE TITLE
Add Asterisk Phonebook repo to Contributed Modules

### ISSUE THREAD

**Issue by lgaetz** [FreePBX/issue-tracker#295]
### FreePBX Version

FreePBX 17

### Feature Description

With Asterisk Phonebook module deprecation in 17, the community may wish to maintain it going forward. If so, the repo and 17 branch will need to be created at the contributed project.

**Comment by kapilgupta01** [comment]
https://github.com/FreePBX/phonebook present here so may be can improve this for 17 by the community. Release/17.0 branch is already present.
