### ISSUE TITLE
[bug]: Cannot login to UCP 16.0.38 - AJAX Error

### ISSUE THREAD

**Issue by Nxcoms** [FreePBX/issue-tracker#296]
### FreePBX Version

FreePBX 16

### Issue Description

Logging into UCP, error message “There was an error, see console log for details” is displayed

The console log shows this (FQDN redacted for security)

Source map error: Error: request failed with status 403
Resource URL: https://..***/ucp/assets/js/compiled/main/jsphpg_b76ec9325a1a5caca04f28721d9cc414.js?load_version=v16.0.38.1
Source Map URL: bootstrap-toggle.min.js.map

POST https://xxx.xxx.xxx/ucp/ajax.php

Status 403 Forbidden
Version HTTP/1.1
Transferred 762 B (32 B size)
Referrer Policy strict-origin-when-cross-origin
DNS ResolutionSystem

Forbidden: ajaxRequest declined

jsphpg_b76ec9325a1a5caca04f28721d9cc414.js:2682:233
ready https://../ucp/assets/js/compiled/main/jsphpg_b76ec9325a1a5caca04f28721d9cc414.js?load_version=v16.0.38.1:2682
(Async: setTimeout handler)
ready https://../ucp/assets/js/compiled/main/jsphpg_b76ec9325a1a5caca04f28721d9cc414.js?load_version=v16.0.38.1:2681
jQuery 7
ajax https://../ucp/assets/js/compiled/main/jsphpg_b76ec9325a1a5caca04f28721d9cc414.js?load_version=v16.0.38.1:21
b jQuery
normalLogin https://../ucp/assets/js/compiled/main/jsphpg_b76ec9325a1a5caca04f28721d9cc414.js?load_version=v16.0.38.1:2692
handleMFAFunc https://../ucp/assets/js/compiled/main/jsphpg_b76ec9325a1a5caca04f28721d9cc414.js?load_version=v16.0.38.1:2691
setupLogin https://../ucp/assets/js/compiled/main/jsphpg_b76ec9325a1a5caca04f28721d9cc414.js?load_version=v16.0.38.1:2690
jQuery 2

No errors in fwconsole debug
No errors in httpd logs

Issue also occurs in 16.0.38
There is no issue when the UCP module is downgraded to 16.0.36, and users can log in normally

### Operating Environment

FPBX standard distro 16.0.40.8
Core 16.0.68.20
Framework 16.0.40.8
All modules up to date
UCP version is 16.0.38.1

**Comment by msanthosh18** [comment]
Hi @Nxcoms ,
Can you please upgrade UCP to 16.0.38.2 and give a try by clearing the browser cache 
"fwconsole ma downloadinstall ucp --tag=16.0.38.2"

If its an issue please share the below logs along with console logs and screen shot
/var/log/httpd/access_log

**Comment by kapilgupta01** [comment]
Hi @Nxcoms Can you please reply to above comment? 

Closing this ticket as no feedback, feel free to re-open with your comment. thanks

**Comment by vxtra1973** [comment]
I hit this issue too.

access.log says:

[21/Nov/2024:11:04:58 +0000] "POST /ucp/ajax.php HTTP/1.1" 403 794 "https://example.host.com/ucp/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0" " - - 
[21/Nov/2024:11:06:39 +0000] "GET /admin/ajax.php?command=authping HTTP/1.1" 401 1030 "https://example.host.com/admin/config.php?display=userman" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0" " - - 
[21/Nov/2024:11:06:45 +0000] "GET /admin/ajax.php?command=authping HTTP/1.1" 401 1030 "https://example.host.com/admin/config.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0" " 

as @Nxcoms says, downgrading to 16.0.36 works for now.
