### ISSUE TITLE
[bug]: Freepbx 17.0.16  Endpoint Manager 17.0.1.71 Commercial - "Undefined array key "resync""

### ISSUE THREAD

**Issue by ra1nmak3r** [FreePBX/issue-tracker#297]
### FreePBX Version

FreePBX 17

### Issue Description

Fresh install of Freepbx 17 on Debian 12.6 (using install script)
After adding an emtpy/unchanged Brand Template to Endpoint Manager (e.g. Yealink) the Endpoint Manager fails with 
"Whoops \ Exception \ ErrorException (E_WARNING)
Undefined array key "resync""
This sometimes happens immediately at the "Save" operation and sometimes after reloading the Page (Endpoint Manager)

Only thing that worked so far is force uninstall and reinstall the Endpoint Manager 
The Endpoint Manager is licensed.

### Operating Environment

PBX Version: 17.0.16
PBX Distro: 12.7.8-2402-3.sng12
Asterisk Version: 21.3.1
Debian: 12.6
Kernel-Version: Debian 6.1.94-1

fwconsole ma list:

+---------------------+-----------+---------+-------------+-----------+
| Module              | Version   | Status  | License     | Signature |
+---------------------+-----------+---------+-------------+-----------+
| accountcodepreserve | 17.0.0.1  | Enabled | GPLv2       | Sangoma   |
| allowlist           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| amd                 | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1  | Enabled | GPLv3+      | Sangoma   |
| api                 | 17.0.1.4  | Enabled | AGPLv3+     | Sangoma   |
| areminder           | 17.0.3.10 | Enabled | Commercial  | Sangoma   |
| arimanager          | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| backup              | 17.0.5.54 | Enabled | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| broadcast           | 17.0.1.6  | Enabled | Commercial  | Sangoma   |
| builtin             |           | Enabled |             | Unsigned  |
| bulkhandler         | 17.0.5    | Enabled | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.15 | Enabled | GPLv3+      | Sangoma   |
| callaccounting      | 17.0.5    | Enabled | Commercial+ | Sangoma   |
| callback            | 17.0.2.1  | Enabled | GPLv3+      | Sangoma   |
| callerid            | 17.0.1    | Enabled | Commercial  | Sangoma   |
| callforward         | 17.0.1.6  | Enabled | AGPLv3+     | Sangoma   |
| calllimit           | 17.0.1.2  | Enabled | Commercial  | Sangoma   |
| callrecording       | 17.0.3.6  | Enabled | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4  | Enabled | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.15 | Enabled | GPLv3+      | Sangoma   |
| cdrpro              | 17.0.3.17 | Enabled | Commercial  | Sangoma   |
| cel                 | 17.0.2.8  | Enabled | GPLv3+      | Sangoma   |
| certman             | 17.0.3.12 | Enabled | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2  | Enabled | GPLv3+      | Sangoma   |
| conferencespro      | 17.0.1.7  | Enabled | Commercial  | Sangoma   |
| configedit          | 17.0.1.1  | Enabled | AGPLv3+     | Sangoma   |
| contactmanager      | 17.0.5.11 | Enabled | GPLv3+      | Sangoma   |
| core                | 17.0.9.68 | Enabled | GPLv3+      | Sangoma   |
| cos                 | 17.0.1.1  | Enabled | Commercial  | Sangoma   |
| customappsreg       | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.2  | Enabled | GPLv2+      | Sangoma   |
| dashboard           | 17.0.4.3  | Enabled | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| disa                | 17.0.3    | Enabled | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3  | Enabled | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.1  | Enabled | GPLv3+      | Sangoma   |
| endpoint            | 17.0.1.71 | Enabled | Commercial  | Sangoma   |
| extensionroutes     | 17.0.1    | Enabled | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4  | Enabled | GPLv3+      | Sangoma   |
| faxpro              | 17.0.1.16 | Enabled | Commercial  | Sangoma   |
| featurecodeadmin    | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.21 | Enabled | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.8  | Enabled | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.26 | Enabled | AGPLv3+     | Sangoma   |
| framework           | 17.0.16   | Enabled | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6  | Enabled | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1    | Enabled | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1    | Enabled | GPLv2+      | Sangoma   |
| ivr                 | 17.0.6    | Enabled | GPLv3+      | Sangoma   |
| languages           | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3  | Enabled | GPLv3+      | Sangoma   |
| manager             | 17.0.5    | Enabled | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3    | Enabled | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| music               | 17.0.4    | Enabled | GPLv3+      | Sangoma   |
| outcnam             | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| paging              | 17.0.3    | Enabled | GPLv3+      | Sangoma   |
| pagingpro           | 17.0.1.6  | Enabled | Commercial  | Sangoma   |
| parking             | 17.0.2.4  | Enabled | GPLv3+      | Sangoma   |
| parkpro             | 17.0.1.4  | Enabled | Commercial  | Sangoma   |
| pbxmfa              | 17.0.2    | Enabled | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1    | Enabled | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2  | Enabled | GPLv3+      | Sangoma   |
| pinsetspro          | 17.0.2    | Enabled | Commercial  | Sangoma   |
| pm2                 | 17.0.3.2  | Enabled | AGPLv3+     | Sangoma   |
| pms                 | 17.0.2.15 | Enabled | Commercial  | Sangoma   |
| presencestate       | 17.0.2.4  | Enabled | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4  | Enabled | GPLv3+      | Sangoma   |
| queues              | 17.0.1.9  | Enabled | GPLv2+      | Sangoma   |
| queuestats          | 17.0.1.7  | Enabled | Commercial  | Sangoma   |
| qxact_reports       | 17.0.2    | Enabled | Commercial  | Sangoma   |
| recording_report    | 17.0.3.8  | Enabled | Commercial  | Sangoma   |
| recordings          | 17.0.2.2  | Enabled | GPLv3+      | Sangoma   |
| restapps            | 17.0.1.19 | Enabled | Commercial  | Sangoma   |
| ringgroups          | 17.0.2.4  | Enabled | GPLv3+      | Sangoma   |
| sangomaconnect      | 17.0.1.35 | Enabled | Commercial  | Sangoma   |
| sangomacrm          | 17.0.1.8  | Enabled | Commercial  | Sangoma   |
| sangomartapi        | 17.0.1.26 | Enabled | Commercial  | Sangoma   |
| setcid              | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.8  | Enabled | AGPLv3+     | Sangoma   |
| sipstation          | 17.0.3.3  | Enabled | Commercial  | Sangoma   |
| sms                 | 17.0.1.13 | Enabled | Commercial  | Sangoma   |
| smsplus             | 17.0.3    | Enabled | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1  | Enabled | GPLv3+      | Sangoma   |
| superfecta          | 17.0.1.10 | Enabled | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.89 | Enabled | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.17 | Enabled | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1    | Enabled | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.19 | Enabled | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.25 | Enabled | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| vmnotify            | 17.0.1.7  | Enabled | Commercial  | Sangoma   |
| voicemail           | 17.0.5.22 | Enabled | GPLv3+      | Sangoma   |
| voicemail_report    | 17.0.1.1  | Enabled | Commercial  | Sangoma   |
| voipinnovations     | 17.0.1.4  | Enabled | Commercial  | Sangoma   |
| vqplus              | 17.0.1.16 | Enabled | Commercial  | Sangoma   |
| weakpasswords       | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| webcallback         | 17.0.4    | Enabled | Commercial  | Sangoma   |
| webrtc              | 17.0.2.2  | Enabled | GPLv3+      | Sangoma   |
+---------------------+-----------+---------+-------------+-----------+

### Relevant log output

```shell
Stack frames (7)
6
Whoops\Exception\ErrorException 
/var/www/html/admin/modules/endpoint/EndpointYealink.class.php47
5
Whoops\Run handleError
/var/www/html/admin/modules/endpoint/EndpointYealink.class.php47
4
FreePBX\modules\Endpoint\EndpointYealink endpoint_getYealinkValues
/var/www/html/admin/modules/endpoint/functions.inc/functions_common.php4451
3
 endpoint_blankConfigVariables
/var/www/html/admin/modules/endpoint/functions.inc/functions_yealink.php668
2
 endpoint_write_yealink_commons
/var/www/html/admin/modules/endpoint/views/page.endpoint.php117
1
 unknown
/var/www/html/admin/modules/endpoint/page.endpoint.php10
0
 include
/var/www/html/admin/config.php658

Environment & details:
GET Data
display	
"endpoint"
POST Data empty
Files empty
Cookies
lang	
"en_US"
searchHide	
"1"
PHPSESSID	
"teadt5ngllf8tj1d11vn3iaf49"
_ga	
"GA1.2.1305092311.1720420526"
_gid	
"GA1.2.290672352.1720420526"
_ga_65BVXK7F61	
"GS1.2.1720438166.4.1.1720438664.0.0.0"
Session
langdirection	
"ltr"
module_name	
"modules"
module_page	
"modules"
AMP_user	
ampuser {#1}
Server/Request Data
SCRIPT_URL	
"/admin/config.php"
SCRIPT_URI	
"https://voip.m****.**/admin/config.php"
SSLSETUP	
"true"
HTACCESS	
"on"
HTTPS	
"on"
HTTP_HOST	
"voip.m****.**"
HTTP_CONNECTION	
"keep-alive"
HTTP_SEC_CH_UA	
""Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126""
HTTP_SEC_CH_UA_MOBILE	
"?0"
HTTP_SEC_CH_UA_PLATFORM	
""Windows""
HTTP_UPGRADE_INSECURE_REQUESTS	
"1"
HTTP_USER_AGENT	
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
HTTP_ACCEPT	
"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
HTTP_SEC_FETCH_SITE	
"same-origin"
HTTP_SEC_FETCH_MODE	
"navigate"
HTTP_SEC_FETCH_USER	
"?1"
HTTP_SEC_FETCH_DEST	
"document"
HTTP_REFERER	
"https://voip.m****.**/admin/config.php?display=modules"
HTTP_ACCEPT_ENCODING	
"gzip, deflate, br, zstd"
HTTP_ACCEPT_LANGUAGE	
"en-US,en;q=0.9,de;q=0.8"
HTTP_COOKIE	
"lang=en_US; searchHide=1; PHPSESSID=teadt5ngllf8tj1d11vn3iaf49; _ga=GA1.2.1305092311.1720420526; _gid=GA1.2.290672352.1720420526; _ga_65BVXK7F61=GS1.2.172043816 ▶"
PATH	
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
SERVER_SIGNATURE	
""
SERVER_SOFTWARE	
"Apache"
SERVER_NAME	
"voip.m****.**"
SERVER_ADDR	
"10.1.1.9"
SERVER_PORT	
"443"
REMOTE_ADDR	
"132.147.2.76"
DOCUMENT_ROOT	
"/var/www/html"
REQUEST_SCHEME	
"https"
CONTEXT_PREFIX	
""
CONTEXT_DOCUMENT_ROOT	
"/var/www/html"
SERVER_ADMIN	
"[no address given]"
SCRIPT_FILENAME	
"/var/www/html/admin/config.php"
REMOTE_PORT	
"55681"
GATEWAY_INTERFACE	
"CGI/1.1"
SERVER_PROTOCOL	
"HTTP/1.1"
REQUEST_METHOD	
"GET"
QUERY_STRING	
"display=endpoint"
REQUEST_URI	
"/admin/config.php?display=endpoint"
SCRIPT_NAME	
"/admin/config.php"
PHP_SELF	
"/admin/config.php"
REQUEST_TIME_FLOAT	
1720438919.0708
REQUEST_TIME	
1720438919
Environment Variables empty
Registered Handlers
0. Whoops\Handler\PrettyPageHandler
```

**Comment by ra1nmak3r** [comment]
UPDATE:
When I added "Global settings" first before I added the Brand Template the array key error went away!

**Comment by kapilgupta01** [comment]
endpoint v17.0.1.17
