### ISSUE TITLE
SSH entry doesn't show in initial warmspare setup

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#298]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

In warmspare setup of v17, 
1) first created SSH entry in filestore, 
2) then go to backup module, 
3) create new backup entry
4) Now when you enable warmspare option, and select SSH, there's a dropdpwn, however it'll not show filestore ssh entry 
5) But when you click on submit, then edit this backup entry again, SSH entry of filestore is shown now. 

SSH entry doesn't show until submit in backup module page. 

Thanks

### Operating Environment

fpbx17

**Comment by kapilgupta01** [comment]
backup v17.0.5.55

**Comment by girishmani1992** [comment]
Hi,

Issue has been resolved with backup v17.0.5.55


Thanks
