### ISSUE TITLE
[bug]: In EndpointCommon.class.php line 1313:    Syntax error

### ISSUE THREAD

**Issue by ccampbell118** [FreePBX/issue-tracker#300]
### FreePBX Version

FreePBX 17

### Issue Description

I tried to do module updates. As part of that I upgraded endpoint from 17.0.1.71 to 17.0.1.73 and received this output:

Upgrading module 'endpoint' from 17.0.1.71 to 17.0.1.73
Downloading module 'endpoint'
Processing endpoint
Downloading...
 94921905/94921905 [============================] 100%
Finished downloading
Extracting...Done
Download completed in 6 seconds
Create symlink...Done
Checking database tables...Done
Migrating tables as required...Done
Checking Settings and Defaults...
In EndpointCommon.class.php line 1313:

  Syntax error

moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [<args>...]

The rest of the modules seemed to update successfully. 

### Operating Environment

# apt list --installed | grep asterisk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

asterisk-sounds-core-en-alaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-en-au-alaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-en-au-ulaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-en-au-wideband/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-en-gb-alaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-en-gb-ulaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-en-gb-wideband/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-en-ulaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-en-wideband/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-es-alaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-es-ulaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-es-wideband/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-fr-alaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-fr-ulaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-fr-wideband/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-it-alaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-it-ulaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-it-wideband/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-ja-alaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-ja-ulaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-core-ja-wideband/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-extra-en-alaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-extra-en-ulaw/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-extra-en-wideband/bookworm,bookworm,now 1.5-2.sng12 all [installed]
asterisk-sounds-moh-opsound-alaw/bookworm,bookworm,now 2.03-1.sng12 all [installed]
asterisk-sounds-moh-opsound-sln/bookworm,bookworm,now 2.03-1.sng12 all [installed]
asterisk-sounds-moh-opsound-ulaw/bookworm,bookworm,now 2.03-1.sng12 all [installed]
asterisk-sounds-moh-opsound-wideband/bookworm,bookworm,now 2.03-1.sng12 all [installed]
asterisk-version-switch/bookworm,bookworm,now 6.1-27.sng12 all [installed]
asterisk21-addons-bluetooth/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-addons-core/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-addons-mysql/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-addons-ooh323/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-addons/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-core/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-curl/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-dahdi/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-doc/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-flite/bookworm,now 2.4-37.2505af1.sng12 amd64 [installed]
asterisk21-g729/bookworm,now 2003-1.sng12 amd64 [installed]
asterisk21-odbc/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-ogg/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-res-digium-phone/bookworm,now 3.6.8-1.sng12 amd64 [installed]
asterisk21-resample/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-snmp/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-speex/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-sqlite3/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21-voicemail/bookworm,now 21.3.1-1.sng12 amd64 [installed]
asterisk21.0-freepbx-asterisk-modules/bookworm,now 1.0-1.sng12 amd64 [installed]
asterisk21/bookworm,now 21.3.1-1.sng12 amd64 [installed]

# fwconsole ma list output
No repos specified, using: [standard,commercial,extended] from last GUI settings

+------------------+-----------+----------------------------------------+-------------+-----------+
| Module           | Version   | Status                                 | License     | Signature |
+------------------+-----------+----------------------------------------+-------------+-----------+
| announcement     | 17.0.2.1  | Enabled                                | GPLv3+      | Sangoma   |
| arimanager       | 17.0.1.1  | Enabled                                | GPLv3+      | Sangoma   |
| asterisk-cli     | 17.0.2    | Enabled                                | GPLv3+      | Sangoma   |
| asteriskinfo     | 17.0.2    | Enabled                                | GPLv3+      | Sangoma   |
| backup           | 17.0.5.54 | Enabled                                | GPLv3+      | Sangoma   |
| builtin          |           | Enabled                                |             | Unsigned  |
| bulkhandler      | 17.0.5    | Enabled                                | GPLv3+      | Sangoma   |
| calendar         | 17.0.4.15 | Enabled                                | GPLv3+      | Sangoma   |
| callback         | 17.0.2.1  | Enabled                                | GPLv3+      | Sangoma   |
| callforward      | 17.0.1.6  | Enabled                                | AGPLv3+     | Sangoma   |
| callrecording    | 17.0.3.6  | Enabled                                | AGPLv3+     | Sangoma   |
| callwaiting      | 17.0.3.4  | Enabled                                | GPLv3+      | Sangoma   |
| cdr              | 17.0.4.16 | Enabled                                | GPLv3+      | Sangoma   |
| cel              | 17.0.2.8  | Enabled                                | GPLv3+      | Sangoma   |
| certman          | 17.0.3.12 | Enabled                                | AGPLv3+     | Sangoma   |
| conferences      | 17.0.3.2  | Enabled                                | GPLv3+      | Sangoma   |
| contactmanager   | 17.0.5.11 | Enabled                                | GPLv3+      | Sangoma   |
| core             | 17.0.9.73 | Enabled                                | GPLv3+      | Sangoma   |
| customappsreg    | 17.0.1    | Enabled                                | GPLv3+      | Sangoma   |
| dashboard        | 17.0.4.3  | Enabled                                | AGPLv3+     | Sangoma   |
| daynight         | 17.0.1.1  | Enabled                                | GPLv3+      | Sangoma   |
| directory        | 17.0.1.1  | Enabled                                | GPLv3+      | Sangoma   |
| donotdisturb     | 17.0.2.3  | Enabled                                | GPLv3+      | Sangoma   |
| endpoint         | 17.0.1.71 | Disabled; Pending upgrade to 17.0.1.73 | Commercial  | Sangoma   |
| extensionroutes  | 17.0.1    | Enabled                                | Commercial  | Sangoma   |
| fax              | 17.0.3.4  | Enabled                                | GPLv3+      | Sangoma   |
| featurecodeadmin | 17.0.2    | Enabled                                | GPLv3+      | Sangoma   |
| filestore        | 17.0.2.21 | Enabled                                | AGPLv3      | Sangoma   |
| findmefollow     | 17.0.4.9  | Enabled                                | GPLv3+      | Sangoma   |
| firewall         | 17.0.1.26 | Enabled                                | AGPLv3+     | Sangoma   |
| framework        | 17.0.17   | Enabled                                | GPLv2+      | Sangoma   |
| iaxsettings      | 17.0.1    | Enabled                                | AGPLv3      | Sangoma   |
| infoservices     | 17.0.1    | Enabled                                | GPLv2+      | Sangoma   |
| ivr              | 17.0.6    | Enabled                                | GPLv3+      | Sangoma   |
| languages        | 17.0.1    | Enabled                                | GPLv3+      | Sangoma   |
| logfiles         | 17.0.3.3  | Enabled                                | GPLv3+      | Sangoma   |
| manager          | 17.0.5    | Enabled                                | GPLv2+      | Sangoma   |
| miscapps         | 17.0.3    | Enabled                                | GPLv3+      | Sangoma   |
| miscdests        | 17.0.1.1  | Enabled                                | GPLv3+      | Sangoma   |
| music            | 17.0.4    | Enabled                                | GPLv3+      | Sangoma   |
| paging           | 17.0.3    | Enabled                                | GPLv3+      | Sangoma   |
| parking          | 17.0.2.4  | Enabled                                | GPLv3+      | Sangoma   |
| pbxmfa           |           | Not Installed (Locally available)      | Commercial+ | Sangoma   |
| pinsets          | 17.0.3.2  | Enabled                                | GPLv3+      | Sangoma   |
| pm2              | 17.0.3.2  | Enabled                                | AGPLv3+     | Sangoma   |
| printextensions  | 17.0.1.2  | Enabled                                | GPLv3+      | Sangoma   |
| queues           | 17.0.1.9  | Enabled                                | GPLv2+      | Sangoma   |
| recordings       | 17.0.2.2  | Enabled                                | GPLv3+      | Sangoma   |
| ringgroups       | 17.0.2.4  | Enabled                                | GPLv3+      | Sangoma   |
| setcid           | 17.0.1.2  | Enabled                                | GPLv3+      | Sangoma   |
| sipsettings      | 17.0.6.8  | Enabled                                | AGPLv3+     | Sangoma   |
| soundlang        | 17.0.4.1  | Enabled                                | GPLv3+      | Sangoma   |
| sysadmin         | 17.0.1.91 | Enabled                                | Commercial  | Sangoma   |
| timeconditions   | 17.0.1.17 | Enabled                                | GPLv3+      | Sangoma   |
| tts              | 17.0.1.1  | Enabled                                | GPLv3+      | Sangoma   |
| ttsengines       | 17.0.1    | Enabled                                | AGPLv3      | Sangoma   |
| ucp              | 17.0.4.20 | Enabled                                | AGPLv3+     | Sangoma   |
| userman          | 17.0.6.26 | Enabled                                | AGPLv3+     | Sangoma   |
| voicemail        | 17.0.5.22 | Enabled                                | GPLv3+      | Sangoma   |
| weakpasswords    | 17.0.1    | Enabled                                | GPLv3+      | Sangoma   |
+------------------+-----------+----------------------------------------+-------------+-----------+

**Comment by kapilgupta01** [comment]
Hi @ccampbell118 Endpoint manager is failing to pull the latest firmware details from https://katanafpbx.schmoozecom.com" server so can you please confirm if you can ping katanafpbx.schmoozecom.com and try again please ? thanks

**Comment by ccampbell118** [comment]
We can’t ping outbound to external addresses in general. I have reached out to our web filter team to see if they will allow an exemption for the PBX until EoD today. My apologies, I should have checked that before filling out a bug report. This might be an issue that is particular to our environment, but I will have to see what the web filter team comes back with.

Thank you.

**Comment by ccampbell118** [comment]
I am closing this. My apologies for wasting your time, this was a web filter issue. It's working now. 

Module(s) requiring upgrades: endpoint
Upgrading module 'endpoint' from 17.0.1.73 to 17.0.1.73
Downloading module 'endpoint'
Processing endpoint
Verifying local module download...Verified
Extracting...Done
Download completed in 4 seconds
Create symlink...Done
Checking database tables...Done
Migrating tables as required...Done
Checking Settings and Defaults...Done
Generating Configs...Done
Downloading Firmware...Done (Background)
updating Logout phones config...(Background)Generating CSS...Done
Module endpoint version 17.0.1.73 successfully installed
Updating Hooks...Done
Chowning directories...Done
All upgrades completed successfully!
Updating Hooks...Done
Chowning directories...Done
