### ISSUE TITLE
Coding Error - don't understand '[]' from /etc/asterisk/musiconhold_additional.conf

### ISSUE THREAD

**Issue by mischa365** [FreePBX/issue-tracker#302]
### FreePBX Version

FreePBX 16

### Issue Description

Coding Error - don't understand '[]' from /etc/asterisk/musiconhold_additional.conf

### Operating Environment

Linux

### Relevant log output

```shell
.
```

**Comment by kapilgupta01** [comment]
hi @mischa365 can you please share full stack trace so we can see which module is throwing the error and also if possible share contents of /etc/asterisk/musiconhold_additional.conf (if not confidential) so we can try to reproduce the issue locally. thanks

**Comment by mischa365** [comment]
![2024-07-11_12-57-59](https://github.com/FreePBX/issue-tracker/assets/175188259/3d68f2b3-735c-4238-9236-aa311c57919d)

**Comment by kapilgupta01** [comment]
Hi @mischa365 yes so this shows something not right in "/etc/asterisk/musiconhold_additional.conf"  please review this file to ensure contents of this file is good.

**Comment by kapilgupta01** [comment]
Hi @mischa365 did you got the problematic point in your "/etc/asterisk/musiconhold_additional.conf" file?
Closing this issue as nothing to do from freepbx side.

thanks
