### ISSUE TITLE
[bug]:  Backup not showing FTP filestore location

### ISSUE THREAD

**Issue by jasonurkow** [FreePBX/issue-tracker#306]
### FreePBX Version

FreePBX 17

### Issue Description

I have a filestore location created using a FTP location.  But when I go into  the Backup module the filestore location isn't available.

### Operating Environment

PBX Version:  17.0.17
PBX Distro:  12.7.8-2402-3.sng12
Asterisk Version:  21.3.1
Backup & Restore:  17.0.5.56
Filestore:  17.0.2.21
![filestore](https://github.com/user-attachments/assets/2245e5c0-352b-4faf-ba33-0d1e84a04729)
![backup storage location](https://github.com/user-attachments/assets/52c7481a-27a5-424d-94c8-49aa67a97506)

**Comment by msanthosh18** [comment]
Hi @jasonurkow ,
Can you upgrade backup module  to latest and give a try by clearing the browser cache once
```
fwconsole ma downloadinstall backup --tag 17.0.5.57
fwconsole r
```

**Comment by jasonurkow** [comment]
That upgrade worked on one of my servers.  On my second server, I had to go into the Filestore and disable the FTP, and then reenable it for it to show up as a storage location within the backup module.

It is now working.  I will report back in a week to let you know if it is still working.
