### ISSUE TITLE
[improvement]: Completely disable fail2ban for VMs with masquerading. Run intrusion processes on the VM host as a service managed by FreePBX.

### ISSUE THREAD

**Issue by myvirtualexam** [FreePBX/issue-tracker#307]
### FreePBX Version

FreePBX 17

### Improvement Description

We always use FreePBX as a VM. VMs in Qemu can be configured on top of a network bridge or by using macvtap. With a bridge traffic is masqueraded so the source IP address is rewritten to the host's IP address and FreePBX is locked out within seconds. With macvtap this isn't the case but then the VM and host can only talk to each other over a separate network interface, not the interface of incoming connections. This is often not an issue except of the host is used as a VPN/File/etc. server. The VPN then cannot reach the VMs.

As a workaround I had to mask fail2ban because it is started no matter if the firewall is disabled and I configured a comprehensive set of iptables rules on the host to limit SIP registrations.

It would be nice if the intrusion detection can be hosted as a separate instance on the host. Downside is the variety of the operating systems that must be supported.

**Comment by kapilgupta01** [comment]
Hi @myvirtualexam May be you can have your own firewall in front of all the VMs and stop using freepbx inbuilt firewall and fail2ban.
