### ISSUE TITLE
[bug]: Lots of held packages that can not receive packages

### ISSUE THREAD

**Issue by dblaber** [FreePBX/issue-tracker#308]
### FreePBX Version

FreePBX 17

### Issue Description

Hello, I have had freepbx 17 beta installed since may, and have notice the number of packages that are unable to be updated due to being held is increasing by the day. 

`dmb@pbx:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  linux-image-6.1.0-18-amd64
Use 'sudo apt autoremove' to remove it.
The following packages have been kept back:
  freepbx17 libnode-dev libnode108 node-babel7 node-babel7-runtime node-undici node-v8-compile-cache nodejs
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded`

Count of held packages:
`dmb@pbx:~$ apt-mark showhold|wc -l \r\n
1544
`
Many seem to be in connection with nodejs. 
Is there a plan for unholding these packages, so that security updates etc can be applied? How is the upgrade process going to work from beta->GA?

### Operating Environment

Freepbx 17

### Relevant log output
dmb@pbx:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  linux-image-6.1.0-18-amd64
Use 'sudo apt autoremove' to remove it.
The following packages have been kept back:
  freepbx17 libnode-dev libnode108 node-babel7 node-babel7-runtime node-undici node-v8-compile-cache nodejs
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded

dmb@pbx:~$ apt-mark showhold|wc -l
1544

**Comment by dblaber** [comment]
dmb@pbx:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  linux-image-6.1.0-18-amd64
Use 'sudo apt autoremove' to remove it.
The following packages have been kept back:
  freepbx17 libnode-dev libnode108 node-babel7 node-babel7-runtime node-undici node-v8-compile-cache nodejs
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded

dmb@pbx:~$ apt-mark showhold|wc -l
1544

**Comment by kapilgupta01** [comment]
hi @dblaber  We are holding - 
1) Freepbx17 - package - this is required only for  the initial setup and after that we do not need this at all
2) sangoma-pbx17 package - this is required only for  the initial setup and after that we do not need this at all
3) nodejs - we do not want nodejs to get updated to the latest stable otherwise this may break the freepbx. We like to keep this on nodejx 18.x only which is tested/validated one.
4) Linux headers - Keeping this hold only if installed with DAHDI option , because DAHDI drivers will work only on supported kernel. If you are not using DAHDI then this will not be held.

Let us know what else you are seeing as hold packages?

thanks

**Comment by dblaber** [comment]
> 2\. s is required only for  the initial setup and

Nope, that sums it up, as long as this is intentional, as there is an upgrade flow later on (which I imagine there would be some kind of upgrade script that handles majors upgrades to those packages going forward. Bug can be closed if this is intentional.

**Comment by kapilgupta01** [comment]
dmb@pbx:~$ apt-mark showhold|wc -l
1544

I am worried about this count , we should not have so many hold packages

**Comment by dblaber** [comment]
> dmb@pbx:~$ apt-mark showhold|wc -l 1544
> 
> I am worried about this count , we should not have so many hold packages

Here is all of them, they seem to all be related to nodejs and what you mentioned:
`
dmb@pbx:~$ apt-mark showhold
freepbx17
node-abab
node-abbrev
node-abstract-leveldown
node-accepts
node-acorn
node-active-x-obfuscator
node-addon-api
node-address
node-addressparser
node-after
node-agent-base
node-ajv
node-ajv-keywords
node-almond
node-amdefine
node-ampproject-remapping
node-ansi
node-ansi-align
node-ansi-color-table
node-ansi-colors
node-ansi-escapes
node-ansi-font
node-ansi-regex
node-ansi-styles
node-ansi-up
node-ansistyles
node-any-promise
node-anymatch
node-ap
node-applause
node-aproba
node-archy
node-are-we-there-yet
node-arg
node-argparse
node-argv
node-arr-diff
node-arr-exclude
node-arr-flatten
node-arr-union
node-array-differ
node-array-equal
node-array-find-index
node-array-flatten
node-array-from
node-array-union
node-array-uniq
node-array-unique
node-arrify
node-asap
node-asn1
node-asn1.js
node-assert
node-assert-plus
node-assertion-error
node-assertive
node-assume
node-ast-types
node-ast-util
node-astw
node-async
node-async-each
node-async-limiter
node-async-stacktrace
node-asynckit
node-atomico-rollup-plugin-sizes
node-auth-header
node-auto-bind
node-autolinker
node-autoprefixer
node-autosize
node-aws-sign2
node-aws4
node-axios
node-babel-helper-define-polyfill-provider
node-babel-loader
node-babel-plugin-add-module-exports
node-babel-plugin-array-includes
node-babel-plugin-lodash
node-babel-plugin-polyfill-corejs2
node-babel-plugin-polyfill-corejs3
node-babel-plugin-polyfill-es-shims
node-babel-plugin-polyfill-regenerator
node-babel-plugin-transform-vue-jsx
node-babel7
node-babel7-debug
node-babel7-runtime
node-babel7-standalone
node-babylon
node-backbone
node-backoff
node-balanced-match
node-base
node-base16
node-base62
node-base64-js
node-base64id
node-base64url
node-bash
node-bash-match
node-basic-auth
node-basic-auth-parser
node-batch
node-bcrypt-pbkdf
node-beeper
node-benchmark
node-big-integer
node-big.js
node-bignumber
node-binary-extensions
node-bindings
node-bl
node-blacklist
node-blob
node-block-stream
node-bluebird
node-blueimp-md5
node-blueprintjs-colors
node-bn.js
node-body-parser
node-boolbase
node-boom
node-bootstrap
node-bootstrap-sass
node-bootstrap-switch
node-boxen
node-brace-expansion
node-braces
node-brfs
node-brorand
node-brotli-size
node-browser-pack
node-browser-resolve
node-browser-stdout
node-browser-unpack
node-browserify
node-browserify-aes
node-browserify-cipher
node-browserify-des
node-browserify-lite
node-browserify-rsa
node-browserify-sign
node-browserify-zlib
node-browserslist
node-buble
node-buf-compare
node-buffer
node-buffer-crc32
node-buffer-equal
node-buffer-xor
node-bufferjs
node-bufferlist
node-buffers
node-builtin-modules
node-builtin-status-codes
node-builtins
node-bunyan
node-busboy
node-bytes
node-cacache
node-cache-base
node-cache-loader
node-cached-path-relative
node-call-limit
node-callback-stream
node-caller
node-camelcase
node-camelcase-keys
node-caniuse-api
node-caniuse-db
node-caniuse-lite
node-canvas-confetti
node-carto
node-caseless
node-catty
node-cbor
node-chai-as-promised
node-chainsaw
node-chalk
node-chance
node-change-case
node-channels
node-character-parser
node-charm
node-chart.js
node-check-error
node-cheerio
node-chokidar
node-chownr
node-chroma-js
node-chrome-trace-event
node-chrono
node-ci-info
node-cipher-base
node-cjs-module-lexer
node-cjson
node-clarinet
node-class-utils
node-classnames
node-clean-css
node-clean-yaml-object
node-cli-boxes
node-cli-cursor
node-cli-spinners
node-cli-table
node-cli-truncate
node-cli-width
node-client-sessions
node-clipboard
node-cliui
node-clone
node-clone-buffer
node-clone-deep
node-clone-stats
node-cloneable-readable
node-co
node-coa
node-code
node-coffee-loader
node-coffeeify
node-collection-visit
node-color
node-color-convert
node-color-name
node-color-string
node-colormin
node-colors
node-colorspace
node-columnify
node-combine-source-map
node-combined-stream
node-commander
node-commist
node-commondir
node-commoner
node-compare-versions
node-component-consoler
node-component-emitter
node-compressible
node-compression
node-compression-webpack-plugin
node-concat-map
node-concat-stream
node-concat-with-sourcemaps
node-concordance
node-config
node-config-chain
node-configstore
node-configurable-http-proxy
node-connect
node-console-browserify
node-console-control-strings
node-console-group
node-consolidate
node-constantinople
node-constants-browserify
node-content-disposition
node-content-type
node-convert-source-map
node-cookie
node-cookie-jar
node-cookie-parser
node-cookie-signature
node-cookiejar
node-cookies
node-copy-concurrently
node-copy-descriptor
node-copy-paste
node-copy-webpack-plugin
node-core-js
node-core-js-builder
node-core-js-bundle
node-core-js-compat
node-core-js-pure
node-core-util-is
node-cors
node-cosmiconfig
node-coveralls
node-cpr
node-crc
node-crc32
node-create-ecdh
node-create-hash
node-create-hmac
node-create-react-class
node-create-require
node-cron-validator
node-cronstrue
node-cross-fetch
node-cryptiles
node-crypto-browserify
node-crypto-random-string
node-cson-parser
node-css
node-css-color-names
node-css-loader
node-css-select
node-css-selector-tokenizer
node-css-tree
node-css-what
node-cssom
node-cssstyle
node-csstype
node-csv-spectrum
node-cuint
node-currently-unhandled
node-cycle
node-cyclist
node-d
node-d3
node-d3-array
node-d3-axis
node-d3-brush
node-d3-chord
node-d3-collection
node-d3-color
node-d3-contour
node-d3-dispatch
node-d3-drag
node-d3-dsv
node-d3-ease
node-d3-fetch
node-d3-force
node-d3-format
node-d3-geo
node-d3-hierarchy
node-d3-interpolate
node-d3-path
node-d3-polygon
node-d3-quadtree
node-d3-queue
node-d3-random
node-d3-scale
node-d3-scale-chromatic
node-d3-selection
node-d3-shape
node-d3-time
node-d3-time-format
node-d3-timer
node-d3-transition
node-d3-voronoi
node-d3-zoom
node-dabh-diagnostics
node-daemon
node-dagre-d3-renderer
node-dagre-layout
node-dargs
node-dashdash
node-data-uri-to-buffer
node-date-now
node-date-time
node-dateformat
node-de-indent
node-death
node-debbundle-acorn
node-debbundle-es-to-primitive
node-debbundle-insert-module-globals
node-debug
node-debug-fabulous
node-decamelize
node-decko
node-decompress-response
node-deep-eql
node-deep-equal
node-deep-extend
node-deep-for-each
node-deep-is
node-deepmerge
node-defaults
node-define-lazy-prop
node-define-properties
node-define-property
node-defined
node-deflate-js
node-del
node-delayed-stream
node-delegates
node-delve
node-depd
node-deprecated
node-deps-sort
node-dequeue
node-des.js
node-detect-file
node-detect-indent
node-detect-newline
node-detective
node-diacritics
node-diff
node-difflet
node-dirty
node-doctrine
node-dom-helpers
node-dom-serializer
node-dom4
node-domain-browser
node-domelementtype
node-domhandler
node-domino
node-dommatrix
node-dompurify
node-domutils
node-dot
node-dot-prop
node-dottie
node-dryice
node-dtrace-provider
node-duplexer
node-duplexer3
node-duplexify
node-duration
node-ebnf-parser
node-ecc-jsbn
node-editor
node-ejs
node-electron-to-chromium
node-elliptic
node-emittery
node-emoji
node-emojis-list
node-enabled
node-encodeurl
node-encoding
node-end-of-stream
node-enhanced-resolve
node-enquirer
node-entities
node-err-code
node-errno
node-error-ex
node-errorhandler
node-errs
node-es-abstract
node-es-module-lexer
node-es5-ext
node-es5-shim
node-es6-error
node-es6-iterator
node-es6-map
node-es6-promise
node-es6-set
node-es6-shim
node-es6-symbol
node-es6-weak-map
node-escape-html
node-escape-string-regexp
node-escodegen
node-escope
node-eslint-plugin-es
node-eslint-plugin-eslint-plugin
node-eslint-plugin-flowtype
node-eslint-plugin-html
node-eslint-plugin-node
node-eslint-plugin-react-hooks
node-eslint-plugin-requirejs
node-eslint-scope
node-eslint-utils
node-eslint-visitor-keys
node-espree
node-esprima
node-esprima-fb
node-esquery
node-esrecurse
node-estraverse
node-estree-walker
node-esutils
node-etag
node-event-emitter
node-eventemitter2
node-eventemitter3
node-events
node-eventsource
node-everything.js
node-evp-bytestokey
node-execa
node-exit
node-exit-hook
node-expand-brackets
node-expand-tilde
node-expect.js
node-exports-loader
node-express
node-extend
node-extend-shallow
node-external-editor
node-extglob
node-extract-zip
node-extsprintf
node-falafel
node-fancy-log
node-fast-deep-equal
node-fast-levenshtein
node-fast-safe-stringify
node-fastcgi
node-fastcgi-stream
node-faye-websocket
node-fbjs
node-fd-slicer
node-fecha
node-fetch
node-file-entry-cache
node-file-loader
node-file-sync-cmp
node-file-uri-to-path
node-filename-regex
node-filesize
node-fill-range
node-finalhandler
node-find-cache-dir
node-find-up
node-findit2
node-findup-sync
node-fined
node-first-chunk-stream
node-flagged-respawn
node-flat-cache
node-flatted
node-flow-remove-types
node-flush-write-stream
node-fn-name
node-fn.name
node-follow-redirects
node-for-in
node-for-own
node-foreground-child
node-forever-agent
node-form-data
node-formidable
node-fragment-cache
node-free-style
node-fresh
node-from2
node-fs-exists-sync
node-fs-extra
node-fs-readdir-recursive
node-fs-write-stream-atomic
node-fs.realpath
node-fstream
node-fstream-ignore
node-function-bind
node-functional-red-black-tree
node-fuzzaldrin-plus
node-fuzzysort
node-gauge
node-generator-supported
node-generic-pool
node-genfun
node-get
node-get-caller-file
node-get-func-name
node-get-stdin
node-get-stream
node-get-value
node-getobject
node-getpass
node-gettext-parser
node-gettext.js
node-github-url-from-git
node-gitlab-favicon-overlay
node-glob
node-glob-base
node-glob-parent
node-glob-stream
node-global-modules
node-global-prefix
node-globals
node-globby
node-globule
node-glogg
node-googlediff
node-got
node-graceful-fs
node-graphlibrary
node-graphql
node-growl
node-grunt-babel
node-grunt-cli
node-grunt-contrib-clean
node-grunt-contrib-coffee
node-grunt-contrib-concat
node-grunt-contrib-copy
node-grunt-contrib-internal
node-grunt-contrib-nodeunit
node-grunt-contrib-requirejs
node-grunt-contrib-uglify
node-grunt-known-options
node-grunt-legacy-log
node-grunt-legacy-log-utils
node-grunt-legacy-util
node-grunt-replace
node-grunt-sass
node-grunt-webpack
node-gulp-babel
node-gulp-changed
node-gulp-coffee
node-gulp-concat
node-gulp-flatten
node-gulp-load-plugins
node-gulp-mocha
node-gulp-newer
node-gulp-plumber
node-gulp-postcss
node-gulp-rename
node-gulp-sass
node-gulp-sourcemaps
node-gulp-tap
node-gulp-tsb
node-gulp-util
node-gulplog
node-gyp
node-gzip-size
node-har-schema
node-har-validator
node-has-ansi
node-has-binary
node-has-cors
node-has-flag
node-has-gulplog
node-has-symbol-support-x
node-has-to-string-tag-x
node-has-unicode
node-has-value
node-has-values
node-has-yarn
node-hash-base
node-hash-sum
node-hash-test-vectors
node-hash.js
node-hashish
node-hawk
node-he
node-help-me
node-highlight.js
node-hmac-drbg
node-hoek
node-hook-std
node-hooker
node-hosted-git-info
node-hsluv
node-html-comment-regex
node-html5shiv
node-htmlescape
node-htmlparser2
node-http-errors
node-http-proxy
node-http-server
node-http-signature
node-https-browserify
node-https-proxy-agent
node-i18next
node-i18next-browser-languagedetector
node-i18next-http-backend
node-iconv
node-iconv-lite
node-icss-replace-symbols
node-icss-utils
node-ieee754
node-iferr
node-ignore
node-ignore-by-default
node-imagemagick
node-immediate
node-immutable
node-immutable-tuple
node-import-lazy
node-imports-loader
node-imurmurhash
node-indent-string
node-inflected
node-inflection
node-inflight
node-inherits
node-ini
node-inline-source-map
node-inquirer
node-interpret
node-invariant
node-invert-kv
node-ip
node-ip-address
node-ip-regex
node-ipaddr.js
node-irregular-plurals
node-is-accessor-descriptor
node-is-arrayish
node-is-binary-path
node-is-buffer
node-is-builtin-module
node-is-data-descriptor
node-is-descriptor
node-is-directory
node-is-docker
node-is-dotfile
node-is-equal-shallow
node-is-extendable
node-is-extglob
node-is-finite
node-is-generator-fn
node-is-glob
node-is-module
node-is-negated-glob
node-is-node
node-is-npm
node-is-number
node-is-obj
node-is-object
node-is-path-cwd
node-is-path-in-cwd
node-is-path-inside
node-is-plain-obj
node-is-plain-object
node-is-primitive
node-is-promise
node-is-redirect
node-is-reference
node-is-retry-allowed
node-is-stream
node-is-typedarray
node-is-unc-path
node-is-valid-glob
node-is-windows
node-is-wsl
node-isarray
node-iscroll
node-isexe
node-ismobilejs
node-isobject
node-isomorphic-fetch
node-isomorphic.js
node-isstream
node-istanbul
node-istextorbinary
node-isurl
node-jake
node-jasmine
node-jed
node-jest-debbundle
node-jest-react
node-jest-worker
node-jison-lex
node-jju
node-jmespath
node-jose
node-jose-browser-runtime
node-jquery
node-jquery-mousewheel
node-jquery-textcomplete
node-jquery-ui
node-jquery-ujs
node-js-beautify
node-js-cookie
node-js-sdsl
node-js-tokens
node-js-yaml
node-jsbn
node-jschardet
node-jsdom
node-jsesc
node-json-buffer
node-json-loader
node-json-localizer
node-json-parse-better-errors
node-json-parse-helpfulerror
node-json-schema
node-json-schema-traverse
node-json-stable-stringify
node-json-stringify-safe
node-json2module
node-json5
node-jsonfile
node-jsonify
node-jsonminify
node-jsonparse
node-jsonselect
node-jsonstream
node-jsprim
node-jstimezonedetect
node-jszip
node-jszip-utils
node-keese
node-kew
node-keygrip
node-keypress
node-kind-of
node-klaw
node-knockout
node-knockout-sortable
node-kuler
node-labeled-stream-splicer
node-lastfm
node-latest-version
node-lazy-cache
node-lazy-debug-legacy
node-lazy-property
node-lazystream
node-lcid
node-lcov-parse
node-ldapjs
node-leaflet
node-leaflet.markercluster
node-leche
node-less
node-less-loader
node-less-plugin-clean-css
node-leveldown
node-leven
node-levn
node-lex-parser
node-lexical-scope
node-lib0
node-libpq
node-libravatar
node-libs-browser
node-lie
node-liftoff
node-lightgallery
node-llhttp
node-load-grunt-tasks
node-load-json-file
node-loader-runner
node-loader-utils
node-locate-character
node-locate-path
node-lodash
node-lodash-packages
node-lodash-reescape
node-lodash-reevaluate
node-log-driver
node-log4js
node-logform
node-loose-envify
node-loud-rejection
node-lowercase-keys
node-lru-cache
node-ltx
node-lumino
node-lunr
node-lynx
node-macaddress
node-magic-string
node-make-dir
node-make-error
node-map-cache
node-map-obj
node-map-visit
node-markdown-it
node-marked
node-marked-man
node-match-at
node-matcher
node-md5-hex
node-md5-o-matic
node-md5.js
node-mdn-browser-compat-data
node-mdn-data
node-media-typer
node-mem
node-memfs
node-memory-fs
node-meow
node-merge
node-merge-descriptors
node-merge-stream
node-mersenne
node-mess
node-methods
node-micromatch
node-miller-rabin
node-mime
node-mime-types
node-mimic-fn
node-mimic-response
node-mini-css-extract-plugin
node-minimalistic-crypto-utils
node-minimatch
node-minimist
node-minipass
node-miragejs
node-mississippi
node-mithril
node-mixin-deep
node-mj-context-menu
node-mkdirp
node-mkdirp-classic
node-mocha-lcov-reporter
node-mock-fs
node-mocks-http
node-modern-syslog
node-module-deps
node-moment
node-moment-timezone
node-mongodb
node-morgan
node-mousetrap
node-move-concurrently
node-mqtt
node-mqtt-connection
node-mqtt-packet
node-ms
node-multimatch
node-multiparty
node-multipipe
node-music-library-index
node-mustache
node-mutate-fs
node-mute-stream
node-mysql
node-mysticatea-eslint-plugin
node-mz
node-n3
node-nan
node-natural-sort
node-ncp
node-negotiator
node-neo-async
node-netmask
node-nock
node-node-dir
node-node-expat
node-node-rest-client
node-node-rsa
node-node-sass
node-nodemailer
node-nomnom
node-nopt
node-normalize-git-url
node-normalize-package-data
node-normalize-path
node-normalize-range
node-normalize.css
node-nouislider
node-nouislider-doc
node-npm-bundled
node-npm-package-arg
node-npm-run-path
node-npmlog
node-npmrc
node-nth-check
node-number-allocator
node-number-is-nan
node-nunjucks
node-nwmatcher
node-oauth-1.0a
node-oauth-sign
node-obj-util
node-object-assign
node-object-copy
node-object-inspect
node-object-key
node-object-path
node-object-visit
node-object.omit
node-on-finished
node-on-headers
node-once
node-one-time
node-open
node-opencv
node-opener
node-openpgp-seek-bzip
node-opentip
node-optimist
node-optionator
node-orchestrator
node-ordered-read-streams
node-original
node-os-browserify
node-os-locale
node-os-tmpdir
node-osenv
node-output-file-sync
node-p-cancelable
node-p-finally
node-p-is-promise
node-p-limit
node-p-locate
node-p-map
node-p-timeout
node-package
node-package-json
node-package-preamble
node-pako
node-parallel-transform
node-parents
node-parse-asn1
node-parse-base64vlq-mappings
node-parse-filepath
node-parse-glob
node-parse-json
node-parse-ms
node-parse-srcset
node-parse5
node-parse5-html-rewriting-stream
node-parse5-htmlparser2-tree-adapter
node-parse5-parser-stream
node-parse5-plain-text-conversion-stream
node-parse5-sax-parser
node-parseurl
node-pascalcase
node-passport
node-path-browserify
node-path-dirname
node-path-exists
node-path-is-absolute
node-path-is-inside
node-path-root
node-path-root-regex
node-path-to-regexp
node-path-type
node-pathval
node-pause
node-pbkdf2
node-peek-readable
node-pegjs
node-pend
node-performance-now
node-pg
node-pg-hstore
node-picocolors
node-pify
node-pikaday
node-pinkie
node-pinkie-promise
node-pinkyswear
node-pkg-dir
node-pkg-up
node-platform
node-plugin-error
node-plur
node-po2json
node-policyfile
node-popper2
node-posix-character-classes
node-posix-getopt
node-postcss
node-postcss-cli
node-postcss-load-config
node-postcss-load-options
node-postcss-load-plugins
node-postcss-loader
node-postcss-modules
node-postcss-modules-extract-imports
node-postcss-modules-values
node-postcss-preset-evergreen
node-postcss-reporter
node-postcss-value-parser
node-pre-gyp
node-preact
node-prelude-ls
node-prepend-http
node-preserve
node-pretty-bytes
node-pretty-hrtime
node-pretty-ms
node-prismjs
node-private
node-process
node-process-nextick-args
node-progress
node-promise
node-promise-inflight
node-promise-retry
node-prompts
node-promzard
node-prop-types
node-propagate
node-proper-lockfile
node-propget
node-prosemirror-markdown
node-prosemirror-model
node-prosemirror-schema-basic
node-prosemirror-schema-list
node-prosemirror-state
node-prosemirror-test-builder
node-prosemirror-transform
node-prosemirror-view
node-proto-list
node-proxy
node-proxy-addr
node-proxy-from-env
node-proxyquire
node-prr
node-pruddy-error
node-pseudomap
node-pseudorandombytes
node-psl
node-public-encrypt
node-puka
node-pump
node-pumpify
node-punycode
node-q
node-qrcode-generator
node-qs
node-querystring
node-querystring-es3
node-querystringify
node-queue-async
node-quick-lru
node-quote-stream
node-qw
node-rai
node-ramda
node-random-bytes
node-randombytes
node-randomfill
node-range-parser
node-raven-js
node-raw-body
node-raw-loader
node-rc
node-rdf-canonize
node-re2
node-react
node-react-dom
node-react-fast-compare
node-react-highlighter
node-react-is
node-react-lifecycles-compat
node-react-popper
node-react-refresh
node-react-shallow-renderer
node-react-test-renderer
node-read
node-read-file
node-read-only-stream
node-read-package-json
node-read-pkg
node-read-pkg-up
node-readable-stream
node-readdirp
node-recast
node-rechoir
node-redent
node-redis
node-redux
node-regenerate
node-regenerate-unicode-properties
node-regenerator
node-regenerator-preset
node-regenerator-runtime
node-regenerator-transform
node-regex-cache
node-regex-not
node-regexpp
node-regexpu-core
node-registry-auth-token
node-registry-url
node-regjsgen
node-regjsparser
node-reinterval
node-remark-slide
node-remove-trailing-separator
node-repeat-element
node-repeat-string
node-repeating
node-replace-ext
node-request
node-request-capture-har
node-require-all
node-require-dir
node-require-directory
node-require-from-string
node-require-inject
node-require-main-filename
node-require-relative
node-requirejs
node-requirejs-text
node-requires-port
node-reserved
node-resize-observer-polyfill
node-resolve
node-resolve-cwd
node-resolve-dir
node-resolve-from
node-resolve-pkg
node-response-time
node-restore-cursor
node-resumer
node-retape
node-retry
node-rewire
node-rimraf
node-ripemd160
node-rollup-plugin-alias
node-rollup-plugin-babel
node-rollup-plugin-buble
node-rollup-plugin-commonjs
node-rollup-plugin-inject
node-rollup-plugin-json
node-rollup-plugin-node-polyfills
node-rollup-plugin-node-resolve
node-rollup-plugin-replace
node-rollup-plugin-sass
node-rollup-plugin-sourcemaps
node-rollup-plugin-string
node-rollup-plugin-strip
node-rollup-plugin-terser
node-rollup-plugin-typescript
node-rollup-plugin-typescript2
node-rollup-plugin-uglify
node-rollup-pluginutils
node-route-recognizer
node-run-async
node-run-queue
node-rw
node-rx
node-safe-buffer
node-sane
node-sanitize-html
node-sax
node-scheduler
node-schema-utils
node-schlock
node-sdp-jingle-json
node-security
node-seedrandom
node-select2
node-sellside-emitter
node-semver
node-semver-diff
node-send
node-seq
node-sequencify
node-serialize-javascript
node-serve-favicon
node-serve-index
node-serve-static
node-set-blocking
node-set-getter
node-set-immediate-shim
node-set-value
node-setimmediate
node-setprototypeof
node-sha
node-sha.js
node-shasum
node-shebang-command
node-shebang-regex
node-shell-quote
node-shelljs
node-shiny-server-client
node-should
node-should-sinon
node-sigmund
node-signal-exit
node-simple-string-table
node-simple-swizzle
node-sinclair-typebox
node-single-line-log
node-sink-test
node-sinon
node-sinon-chai
node-slash
node-slice-ansi
node-slide
node-smart-buffer
node-smash
node-snapdragon
node-snapdragon-node
node-snapdragon-util
node-sntp
node-socket.io-parser
node-sockjs
node-sockjs-client
node-socks
node-solid-rest
node-sort-keys
node-sorted-object
node-source-list-map
node-source-map
node-source-map-resolve
node-source-map-support
node-sourcemap-codec
node-sparkles
node-spdx-correct
node-spdx-exceptions
node-spdx-expression-parse
node-spdx-license-ids
node-split
node-split-string
node-split2
node-sprintf-js
node-sqlite3
node-sshpk
node-ssri
node-stable
node-stack-trace
node-stack-utils
node-standard-error
node-standard-http-error
node-starttls
node-static
node-static-eval
node-static-extend
node-static-module
node-stats-webpack-plugin
node-statsd-parser
node-statuses
node-std-mocks
node-stealthy-require
node-step
node-stream-array
node-stream-assert
node-stream-browserify
node-stream-combiner2
node-stream-consume
node-stream-each
node-stream-http
node-stream-iterate
node-stream-shift
node-stream-splicer
node-stream-to-observable
node-streamtest
node-strftime
node-strict-uri-encode
node-string-decoder
node-string-width
node-string.prototype.codepointat
node-stringmap
node-stringstream
node-strip-ansi
node-strip-bom
node-strip-bom-stream
node-strip-eof
node-strip-indent
node-strip-json-comments
node-style-loader
node-stylus
node-subarg
node-superagent
node-supertest
node-supports-color
node-svg2ttf
node-symbol-observable
node-syntax-error
node-tacks
node-tap
node-tap-mocha-reporter
node-tap-parser
node-tapable
node-tape
node-tar
node-tar-fs
node-tar-stream
node-telegram-bot-api
node-temp
node-term-size
node-terser
node-test
node-text-encoding
node-text-hex
node-text-table
node-thenby
node-thenify
node-thenify-all
node-three-orbit-controls
node-three-stl-loader
node-throttleit
node-through
node-through2
node-through2-filter
node-tildify
node-tilejson
node-time-stamp
node-time-zone
node-timeago.js
node-timed-out
node-timers-browserify
node-tinycolor
node-tippex
node-tmatch
node-tmp
node-to-absolute-glob
node-to-arraybuffer
node-to-fast-properties
node-to-object-path
node-to-regex
node-to-regex-range
node-toidentifier
node-token-types
node-tough-cookie
node-transformers
node-traverse
node-trim-newlines
node-triple-beam
node-trust-json-document
node-trust-keyto
node-trysound-sax
node-ts-loader
node-tslib
node-tty-browserify
node-tunein
node-tunnel-agent
node-turbolinks
node-turndown
node-tweetnacl
node-typanion
node-type-check
node-type-detect
node-type-is
node-typedarray
node-typedarray-to-buffer
node-typescript
node-typestyle
node-ua-parser-js
node-uglify-js
node-uglify-save-license
node-uid-number
node-uid-safe
node-ultron
node-umd
node-unbzip2-stream
node-unc-path-regex
node-underscore
node-underscore.string
node-undici
node-unicode-15.0.0
node-unicode-canonical-property-names-ecmascript
node-unicode-loose-match
node-unicode-match-property-ecmascript
node-unicode-match-property-value-ecmascript
node-unicode-property-aliases
node-unicode-property-aliases-ecmascript
node-unicode-property-value-aliases
node-unicode-property-value-aliases-ecmascript
node-union-value
node-uniq
node-uniqid
node-uniqs
node-unique-filename
node-unique-stream
node-unique-string
node-universalify
node-unorm
node-unpipe
node-unset-value
node-uri-js
node-uri-path
node-url
node-url-join
node-url-loader
node-url-parse
node-url-parse-lax
node-url-to-options
node-urlgrey
node-use
node-util
node-util-deprecate
node-utilities
node-utils-merge
node-utml
node-uuid
node-v8-compile-cache
node-v8flags
node-vali-date
node-validate-npm-package-license
node-validate-npm-package-name
node-vary
node-vasync
node-vega
node-verror
node-vhost
node-vinyl
node-vinyl-fs
node-vinyl-sourcemaps-apply
node-vlq
node-vm-browserify
node-vows
node-vscode-debugprotocol
node-vue
node-vue-hot-reload-api
node-vue-resource
node-vue-style-loader
node-w3c-keyname
node-warning
node-watchpack
node-wcwidth.js
node-webassemblyjs
node-webfinger
node-webfont
node-webidl-conversions
node-webpack-env
node-webpack-merge
node-webpack-sources
node-webpack-stats-plugin
node-webrtc-adapter
node-websocket
node-websocket-driver
node-websocket-stream
node-whatwg-fetch
node-when
node-which
node-which-module
node-wide-align
node-widest-line
node-wikibase-cli
node-wikibase-edit
node-wikibase-sdk
node-wikidata-lang
node-wildemitter
node-winston
node-winston-compat
node-winston-transport
node-with
node-wordwrap
node-worker-loader
node-wrap-ansi
node-wrappy
node-write
node-write-file-atomic
node-write-file-promise
node-ws
node-ws-iconv
node-xdg-basedir
node-xml2js
node-xmldom
node-xmlhttprequest
node-xoauth2
node-xtend
node-xterm
node-xxhashjs
node-y-protocols
node-y-websocket
node-y18n
node-yajsml
node-yallist
node-yaml
node-yamlish
node-yargs
node-yargs-parser
node-yarn-tool-resolve-package
node-yauzl
node-yazl
node-yjs
node-yn
node-ytdl-core
node-zen-observable
node-zeparser
node-zkochan-cmd-shim
node-zrender
nodejs
sangoma-pbx17
`

**Comment by kapilgupta01** [comment]
okay thanks so mostly nodejs , yes we do not want nodejs to get updated so we are locking the nodejs version.
