### ISSUE TITLE
[improvement]: Enable Send connected line by default on the extension

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#311]
### FreePBX Version

FreePBX 17

### Improvement Description

Currently, the "Send Connected Line" option is set to "NO" by default in the extension settings. Because of this, the connected line caller ID is not being updated. We need to set it to "YES" to enable the connected line update.

![image](https://github.com/user-attachments/assets/cd9c807e-2caf-42f3-a2a6-d82cf98fcc15)

**Comment by jfinstrom** [comment]
Is there a valid reason to change expected behavior here?   This is technically a breaking change and I am not understanding why you would want to make a breaking change.  Defaults should always be set to expected behavior or the most common use case.  Changing this makes all new installs behave different than they historically have.

**Comment by kapilgupta01** [comment]
Hi @jfinstrom 

thanks for your feedback, please find below explanation behind this issue/changes.

Asterisk has this parameter set to true / yes only by default. Ref  - https://github.com/asterisk/asterisk/blob/master/configs/samples/pjsip.conf.sample#L659 

In Freepbx 16 we are not showing this option at all in the UI so asterisk considering default value which is YES.

Now for Freepbx 17, we are exposing this config option to the UI (default to yes to align with default settings of Asterisk and Freepbx 16) so now user can control the value of this parameter.

Please let us know if you stil have any further queries.

Thanks
Kapil

**Comment by jfinstrom** [comment]
Makes sense, thanks for the response

**Comment by ramarajan222** [comment]
Core V17.0.12
