### ISSUE TITLE
[bug]: Cannot reload after configuring dahdi

### ISSUE THREAD

**Issue by carlos-chavez-p** [FreePBX/issue-tracker#312]
### FreePBX Version

FreePBX 17

### Issue Description

After configuring dahdi through the Freepbx interface I get an error when trying to apply the changes.  From linux cli I get the following error:

root@pbxindemex:~# fwconsole reload -vvv
Reload Started

In functions.inc.php line 101:
                                         
  [Whoops\Exception\ErrorException (2)]  
  Undefined array key "mfcr2_logging"    
                                         

Exception trace:
  at /var/www/html/admin/modules/dahdiconfig/functions.inc.php:101
 Whoops\Run->handleError() at /var/www/html/admin/modules/dahdiconfig/functions.inc.php:101
 dahdiconfig_conf->generateConf() at /var/www/html/admin/libraries/BMO/FileHooks.class.php:67
 FreePBX\FileHooks->processOldHooks() at /var/www/html/admin/libraries/BMO/FileHooks.class.php:26
 FreePBX\FileHooks->processFileHooks() at /var/www/html/admin/libraries/Console/Reload.class.php:340
 FreePBX\Console\Command\Reload->reload() at /var/www/html/admin/libraries/Console/Reload.class.php:95
 FreePBX\Console\Command\Reload->execute() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php:312
 Symfony\Component\Console\Command\Command->run() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:1022
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:314
 Symfony\Component\Console\Application->doRun() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:168
 Symfony\Component\Console\Application->run() at /var/lib/asterisk/bin/fwconsole:163

reload [--json] [--dry-run] [--skip-registry-checks] [--dont-reload-asterisk]

### Operating Environment

+---------------------+-----------+-----------------------------------+-------------+-----------+
| Module              | Version   | Status                            | License     | Signature |
+---------------------+-----------+-----------------------------------+-------------+-----------+
| accountcodepreserve | 17.0.0.1  | Enabled                           | GPLv2       | Sangoma   |
| adv_recovery        |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| allowlist           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| amd                 | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| api                 | 17.0.1.5  | Enabled                           | AGPLv3+     | Sangoma   |
| areminder           |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| arimanager          | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| backup              | 17.0.5.56 | Enabled                           | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| broadcast           |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| builtin             |           | Enabled                           |             | Unsigned  |
| bulkhandler         | 17.0.5    | Enabled                           | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.15 | Enabled                           | GPLv3+      | Sangoma   |
| callaccounting      |           | Not Installed (Locally available) | Commercial+ | Sangoma   |
| callback            | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| callerid            |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| callforward         | 17.0.1.6  | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit           |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| callrecording       | 17.0.3.7  | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4  | Enabled                           | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.16 | Enabled                           | GPLv3+      | Sangoma   |
| cdrpro              |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| cel                 | 17.0.2.8  | Enabled                           | GPLv3+      | Sangoma   |
| certman             | 17.0.3.12 | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro      |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| configedit          | 17.0.1.1  | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager      | 17.0.5.11 | Enabled                           | GPLv3+      | Sangoma   |
| core                | 17.0.9.75 | Enabled                           | GPLv3+      | Sangoma   |
| cos                 |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| customappsreg       | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.3  | Enabled                           | GPLv2+      | Sangoma   |
| dahdiconfig         | 17.0.1.12 | Enabled                           | GPLv3+      | Sangoma   |
| dashboard           | 17.0.4.3  | Enabled                           | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| disa                | 17.0.3    | Enabled                           | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3  | Enabled                           | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.1  | Enabled                           | GPLv3+      | Sangoma   |
| extensionroutes     |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4  | Enabled                           | GPLv3+      | Sangoma   |
| faxpro              |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| featurecodeadmin    | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.21 | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.9  | Enabled                           | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.26 | Enabled                           | AGPLv3+     | Sangoma   |
| framework           | 17.0.17   | Enabled                           | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6  | Enabled                           | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1    | Enabled                           | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1    | Enabled                           | GPLv2+      | Sangoma   |
| ivr                 | 17.0.6    | Enabled                           | GPLv3+      | Sangoma   |
| languages           | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3  | Enabled                           | GPLv3+      | Sangoma   |
| manager             | 17.0.5    | Enabled                           | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| music               | 17.0.4    | Enabled                           | GPLv3+      | Sangoma   |
| outcnam             | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| paging              | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro           |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| parking             | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| parkpro             |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| pbxmfa              |           | Not Installed (Locally available) | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1    | Enabled                           | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro          |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| pm2                 | 17.0.3.2  | Enabled                           | AGPLv3+     | Sangoma   |
| pms                 |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| presencestate       | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4  | Enabled                           | GPLv3+      | Sangoma   |
| queues              | 17.0.1.9  | Enabled                           | GPLv2+      | Sangoma   |
| queuestats          |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| qxact_reports       |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| recording_report    |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| recordings          | 17.0.2.2  | Enabled                           | GPLv3+      | Sangoma   |
| ringgroups          | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect      |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| sangomacrm          |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| sangomartapi        |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| setcid              | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.8  | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation          |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| sms                 | 17.0.1.13 | Enabled                           | Commercial  | Sangoma   |
| smsplus             | 17.0.3    | Enabled                           | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1  | Enabled                           | GPLv3+      | Sangoma   |
| superfecta          | 17.0.2    | Enabled                           | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.91 | Enabled                           | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.17 | Enabled                           | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1    | Enabled                           | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.20 | Enabled                           | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.26 | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| vmnotify            |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| voicemail           | 17.0.5.22 | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report    |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| voipinnovations     | 17.0.1.4  | Enabled                           | Commercial  | Sangoma   |
| vqplus              |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| weakpasswords       | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| webcallback         |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| webrtc              | 17.0.2.2  | Enabled                           | GPLv3+      | Sangoma   |
+---------------------+-----------+-----------------------------------+-------------+-----------+

### Relevant log output

```shell
root@pbxindemex:~# fwconsole reload -vvv
Reload Started

In functions.inc.php line 101:
                                         
  [Whoops\Exception\ErrorException (2)]  
  Undefined array key "mfcr2_logging"    
                                         

Exception trace:
  at /var/www/html/admin/modules/dahdiconfig/functions.inc.php:101
 Whoops\Run->handleError() at /var/www/html/admin/modules/dahdiconfig/functions.inc.php:101
 dahdiconfig_conf->generateConf() at /var/www/html/admin/libraries/BMO/FileHooks.class.php:67
 FreePBX\FileHooks->processOldHooks() at /var/www/html/admin/libraries/BMO/FileHooks.class.php:26
 FreePBX\FileHooks->processFileHooks() at /var/www/html/admin/libraries/Console/Reload.class.php:340
 FreePBX\Console\Command\Reload->reload() at /var/www/html/admin/libraries/Console/Reload.class.php:95
 FreePBX\Console\Command\Reload->execute() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php:312
 Symfony\Component\Console\Command\Command->run() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:1022
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:314
 Symfony\Component\Console\Application->doRun() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:168
 Symfony\Component\Console\Application->run() at /var/lib/asterisk/bin/fwconsole:163

reload [--json] [--dry-run] [--skip-registry-checks] [--dont-reload-asterisk]
```

**Comment by jissphilip** [comment]
dahdiconfig version 17.0.1.13
