### ISSUE TITLE
[bug]: I'am missing the Dynamic Routes function in Betaversion FreePBX 17.0.17

### ISSUE THREAD

**Issue by goedkoper** [FreePBX/issue-tracker#315]
### FreePBX Version

FreePBX 17

### Issue Description

I'am missing the Dynamic Routes function in Betaversion FreePBX 17.0.17
Where can I find it? Or is it skipped? Maybe an other name given?

### Operating Environment

Debian 12 Beta version FreePBX 17.0.17

**Comment by kapilgupta01** [comment]
Hi @goedkoper are you talking about dynroute module?  If yes then please downloadinstall this module.
