### ISSUE TITLE
[improvement]: Remove google-analytics from web UI and let users decide whether or not to opt-in in data collection

### ISSUE THREAD

**Issue by ghost** [FreePBX/issue-tracker#318]
### FreePBX Version

FreePBX 17

### Improvement Description

Hi, 
It could be as easy as a checkbox in the first configuration page, where the admin password is set.
I removed it by myself for now but i hope you will consider this. 
Thank you in advance.

**Comment by kapilgupta01** [comment]
We are giving dashboard warning for the fresh setup to notify the users for BROWSER_STATS so user can disable them if they like to via advanced setting.

**Comment by ghost** [comment]
The problem is that you let the users disable it ***ONLY*** AFTER it works at least for the first time.
This way it does not matter if a user disables it or not because by then you get the data from the first use.
I also noticed the web ui calls a script from cdnjs.cloudflare.com: why is that? can't you put this js in a local file? why so important to let cloudflare know about my installation?
What about users who want to use freepbx with no internet connection?

Thank you in advance.
