### ISSUE TITLE
[bug]: Incredble PBX 

### ISSUE THREAD

**Issue by raddystar** [FreePBX/issue-tracker#32]
### FreePBX Version

FreePBX 16

### Issue Description

Exception
Exception 
/var/www/html/admin/libraries/BMO/Cron.class.php126
6
FreePBX\Cron addLine
/var/www/html/admin/libraries/BMO/Cron.class.php203
5
FreePBX\Cron add
/var/www/html/admin/modules/clouddevices/Clouddevices.class.php7
4
FreePBX\modules\Clouddevices updateCrons
/var/www/html/admin/modules/clouddevices/Clouddevices.class.php7
3
FreePBX\modules\Clouddevices install
/var/www/html/admin/libraries/modulefunctions.class.php2568
2
module_functions _runscripts
/var/www/html/admin/libraries/modulefunctions.class.php2041
1
module_functions install
/var/www/html/admin/page.modules.php209
0
 include
/var/www/html/admin/config.php481

### Operating Environment

<html>
<body>
<h2 class="details-heading" style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, helvetica, arial, sans-serif; font-weight: 300; line-height: 1.1; color: rgb(66, 136, 206); margin-top: 0px; margin-bottom: 10px; font-size: 18.48px; padding-bottom: 10px; border-bottom: 1px solid rgba(0, 0, 0, 0.1); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Environment &amp; details:</h2><div class="data-table-container" id="data-tables" style="box-sizing: border-box; color: rgb(64, 64, 64); font-family: &quot;Helvetica Neue&quot;, helvetica, arial, sans-serif; font-size: 13.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="data-table" id="sg-get-data" style="box-sizing: border-box; width: 1171.88px; margin-bottom: 10px;"><label style="box-sizing: border-box; display: block; max-width: 100%; margin: 10px 0px 5px; font-weight: bold; font-size: 16px; color: rgb(48, 48, 48); padding-bottom: 5px;">GET Data</label>
display | "modules"
-- | --
action | "process"
quietmode | "1"
online | "1"

</div></div>
</body>

- </html>

1. [ ]

**Comment by jcolp** [comment]
I'm going to close this out, as I don't believe this is an issue to be resolved here.

The output specifies the "clouddevices" module, which is not part of FreePBX and is from another vendor. You would need to seek help from them. From an IncrediblePBX perspective they also have their own forum which is a resource for help. If things are determined to be a core FreePBX issue then issues can be raised here.
