### ISSUE TITLE
Command "setup-sangoma" broken in v17

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#322]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

We can use command "setup-sangoma" for configuring sangoma cards. In v17 systems, this command is not working and giving below errors.

`root@sangoma:~# setup-sangoma
Can't locate Card.pm in @INC (you may need to install the Card module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at ./wancfg_zaptel.pl line 88.
BEGIN failed--compilation aborted at ./wancfg_zaptel.pl line 88.`

Thanks

### Operating Environment

v17 pbxact appliances with dahdi, wanpipe, etc packages installed.

**Comment by ramarajan222** [comment]
Fix has been added to the installation script so moving to close.
