### ISSUE TITLE
[bug]: Queue Caller Announcements not set correct

### ISSUE THREAD

**Issue by r27687** [FreePBX/issue-tracker#323]
### FreePBX Version

FreePBX 17

### Issue Description

Values under the tab Queue "Caller Announcements" is not set correct in queues_additional.conf and does not change according to changes in the gui.

![image](https://github.com/user-attachments/assets/a303afd7-ea18-4d01-b7a9-190879c2e348)

oot@debian:~# cat /etc/asterisk/queues_additional.conf 
;--------------------------------------------------------------------------------;
;          Do NOT edit this file as it is auto-generated by FreePBX.             ;
;--------------------------------------------------------------------------------;
; For information on adding additional paramaters to this file, please visit the ;
; FreePBX.org wiki page, or ask on IRC. This file was created by the new FreePBX ;
; BMO - Big Module Object. Any similarity in naming with BMO from Adventure Time ;
; is totally deliberate.                                                         ;
;--------------------------------------------------------------------------------;
[100000]
announce-frequency=0
announce-holdtime=no
announce-position=no

### Operating Environment

Debian 12
Framework: 17.0.17
Asterisk Version: 21.3.1
Queues: 17.0.1.9

Failed on multiple systems and hardware.

**Comment by eliweaver732** [comment]
Had the same issue as described above.

**Operating Environment**
Debian 12
Framework: 17.0.17
Asterisk Version: 21.3.1
Queues: 17.0.1.9

**Comment by jissphilip** [comment]
queues version 16.0.28
queues version 17.0.1.10

HI @eliweaver732  Please install the new version and do reload
