### ISSUE TITLE
[bug]:  Asterisk 21.4 and FreePBX-17 Voicemail module version 17.0.5.22 won't install

### ISSUE THREAD

**Issue by kennesaw10** [FreePBX/issue-tracker#324]
### FreePBX Version

FreePBX 17

### Issue Description

Installing on Debian 12, Asterisk 21.4 (latest), FreePBX-17-Edge
Voicemail module version 17.0.5.22 won't install during normal FreePBX install.  Manual install after FreePBX is running also does not work.
`
`root@Debian12:/usr/local/sbin# fwconsole ma downloadinstall voicemail --edge
Edge repository temporarily enabled
No repos specified, using: [standard,unsupported,extended] from last GUI settings

Downloading module 'voicemail'
Processing voicemail
Verifying local module download...Verified
Extracting...Done
Download completed in 0 seconds
Updating tables voicemail_admin...Done
Resetting temporarily repository state

In LoadConfig.class.php line 336:

  Coding Error - don't understand ': Storage database:' from /etc/asterisk/voicemail.conf

moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [<args>...]

### Operating Environment

Debian 12 Cloud Intstall.  FreePBX-17-EDGE, Asterisk 21.4 (Latest)
Framework:  17.0.17
Core : 17.0.13

### Relevant log output

```shell
root@Debian12:/usr/local/sbin# fwconsole ma downloadinstall voicemail --edge
Edge repository temporarily enabled
No repos specified, using: [standard,unsupported,extended] from last GUI settings

Downloading module 'voicemail'
Processing voicemail
Verifying local module download...Verified
Extracting...Done
Download completed in 0 seconds
Updating tables voicemail_admin...Done
Resetting temporarily repository state

In LoadConfig.class.php line 336:

  Coding Error - don't understand ': Storage database:' from /etc/asterisk/voicemail.conf


moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [<args>...]
```

**Comment by kapilgupta01** [comment]
can you please check your /etc/asterisk/voicemail.conf file ? or may be take backup and let freepbx to generate fresh one? looks like something is not right in /etc/asterisk/voicemail.conf which parser is not liking @kennesaw10

**Comment by kennesaw10** [comment]
This was a fresh install from scratch to which I did not restore from a backup.  I ran a backup as you suggested with no change.  This seems to be something that has changed in Asterisk 21.4.  The module install failed during the initial install and errors out with a manual install of the module from the CLI.  I will attach the voicemail.conf file generated by the install.

![image](https://github.com/user-attachments/assets/3223cce3-8238-4765-a240-e3d71973e3f4)
[voicemail.conf.txt](https://github.com/user-attachments/files/16361648/voicemail.conf.txt)

**Comment by kennesaw10** [comment]
I FOUND IT.   The Asterisk 21.4 install is putting a colon instead of a semi-colon in the voicemail.conf file.  I changed it to a semi-colon and the module will load.  Sangoma needs to fix Asterisk 21.4 to generate an error-free Voicemail.conf file.

![image](https://github.com/user-attachments/assets/134c39ab-a3d7-4add-8d93-d52f584dc0b9)

**Comment by blazestudios97** [comment]
You are using the FreePBX install script for all of this right? This isn't from the IPBX setup you did, correct? Because this is actually an Asterisk issue because the sample file has the bad formatting and the only way you got that is from issuing a "make samples" which you wouldn't do if you ran the official install script.

**Comment by blazestudios97** [comment]
The semicolon for commenting a line is actually a colon in the sample file:

; -----------------------------------------------------------------------------
; ODBC storage configuration
```
; -----------------------------------------------------------------------------
; Voicemail can be stored in a database using the ODBC driver.
;
: Storage database:
; The value of odbcstorage is the database connection configured in
```

Needs to have that colon turned into a semi-colon to be seen as a proper comment. It stops the loading (at least in FreePBX systems) of the voicemail.conf file.

**Comment by blazestudios97** [comment]
I already opened a ticket in the Asterisk issue tracker for this: https://github.com/asterisk/asterisk/issues/819

**Comment by blazestudios97** [comment]
There is a PR pending in Asterisk that fixes this typo issue. Waiting for it to be merged.

**Comment by kapilgupta01** [comment]
Thanks @blazestudios97 for chiming in for this issue.

**Comment by kapilgupta01** [comment]
closing as nothing to do from freepbx point of view. thanks
