### ISSUE TITLE
I can't get to the web interface[bug]: 

### ISSUE THREAD

**Issue by mischa365** [FreePBX/issue-tracker#325]
### FreePBX Version

FreePBX 16

### Issue Description

![2024-07-24_11-10-54](https://github.com/user-attachments/assets/aa89c33d-7099-412c-9098-23449e567491)

### Operating Environment

Linux

### Relevant log output

```shell
,.
```

**Comment by kapilgupta01** [comment]
Hi @mischa365 please check your httpd error or access logs or check "fwconsole debug" logs.

**Comment by mischa365** [comment]
![2024-07-25_07-43-59](https://github.com/user-attachments/assets/3555168c-c32a-4510-ad77-0fa91a6180f3)

**Comment by kapilgupta01** [comment]
log does not tell about any error, may be you can check browser console logs or network logs to see why you are getting only some data but not all.

**Comment by mischa365** [comment]
![2024-07-25_09-30-37](https://github.com/user-attachments/assets/48107ee5-7207-4a5b-ac97-6a0e1692cef2)

**Comment by kapilgupta01** [comment]
Hi @mischa365 check your browser network logs or may be try with "fwconsole restart"

**Comment by mischa365** [comment]
![2024-07-25_09-46-43](https://github.com/user-attachments/assets/365196b8-3be4-4a47-a43a-236c01067e9c)

**Comment by kapilgupta01** [comment]
Hi, 

This appears to be a support issue. 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta
