### ISSUE TITLE
[improvement]: Evaluate Dependencies in 17 installer

### ISSUE THREAD

**Issue by jfinstrom** [FreePBX/issue-tracker#327]
### FreePBX Version

FreePBX 17

### Improvement Description

From the discussion [HERE](https://community.freepbx.org/t/fpbx60-appliance-cannot-run-mongo-in-freepbx-17/99134/7) it seems like mongo db isn't required or needed anymore. The installer is based on ever growing instructions that have always been added to but have unlikely ever been removed from.  Perhaps go through each dependency and see if it exist for something or if it is just legacy garbage that can be removed.

**Comment by kohenkatz** [comment]
Removing MongoDB if it's not actually used would also be very helpful for trying to get this working on ARM64 platforms such as Amazon EC2 "Graviton" or Raspberry Pi.

**Comment by kapilgupta01** [comment]
removed mongodb from the freepbx 17 install script.
