### ISSUE TITLE
[bug]: Backup Restore API doesn't manage the transaction ID

### ISSUE THREAD

**Issue by danardf** [FreePBX/issue-tracker#328]
### FreePBX Version

FreePBX 17

### Issue Description

When we try to run a backup the API returns a transaction ID.
Next if we use this one with **fetchApiStatus**, this one stays on "Processing" forever. 

Also, I tried on FreePBX 16, looks good.

### Operating Environment

| framework         | 17.0.17    | Enabled                           | GPLv2+      | Sangoma   |
| backup              | 17.0.5.57 | Enabled                           | GPLv3+      | Sangoma   |

### Relevant log output

```shell
{
	"data": {
		"fetchApiStatus": {
			"status": true,
			"message": "Processing"
		}
	}
}
```

**Comment by kapilgupta01** [comment]
backup v17.0.5.58
api v17.0.1.6

**Comment by danardf** [comment]
@kguptasangoma Thanks

**Comment by danardf** [comment]
@kguptasangoma  
Well. It's better but There's still an issue on 17 and it's new on 16 (Never tested before) regarding how is managed the transaction ID.

For example: 
If you try to launch multiple backups in same time, some transaction ID stay on "Processing".
It's better on 16 but the issue is on 17 everytime.
On 16, there is some process terminated  "Executed", but on 17, all tasks stay on "Processing" 

I have not tested with different taks using transaction ID thought! 

With a single backup, no problem. That works on 16 and 17.
