### ISSUE TITLE
Add TLS v1.3 option to SSL method in Asterisk SIP settings 

### ISSUE THREAD

**Issue by tsharkey67** [FreePBX/issue-tracker#329]
### FreePBX Version

FreePBX 17

### Improvement Description

When creating a SIP trunk can the option to use TLS v1.3 be added to the drop menu section in SSL method in >Asterisk SIP settings > TSL/SSL/SRTP> SSL method .

I've tried adding it in pjsip.transports_custom_post.conf but the TLS handshake still appeared to use TLV 1.2

**Comment by kapilgupta01** [comment]
Related forum thread - https://community.freepbx.org/t/how-to-enable-tlsv1-3-as-ssl-method-against-a-sip-trunk/99256

**Comment by kapilgupta01** [comment]
sipsettings v17.0.6.9
