### ISSUE TITLE
[bug]: SQLSTATE[HY000] [2002] Can't connect to local MySQL server

### ISSUE THREAD

**Issue by Ademiluyi** [FreePBX/issue-tracker#331]
### FreePBX Version

FreePBX 16

### Issue Description

SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)::SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (111)

### Operating Environment

FreePBX 15.0.37.4

**Comment by kapilgupta01** [comment]
hi @Ademiluyi please ensure your mysql/mariadb server is running properly? 
try "fwconsole m" if not able to connect then check why mariadb is not running.
