### ISSUE TITLE
[bug]: Asterisk Manager adds amp; to permit string

### ISSUE THREAD

**Issue by r27687** [FreePBX/issue-tracker#333]
### FreePBX Version

FreePBX 17

### Issue Description

Module Asterisk Manager adds amp; to permit string between ip ranges in gui and only show last range in manager_additional.conf

![image](https://github.com/user-attachments/assets/a3369147-d665-4ce8-bbb2-650c9d6d24cb)

![image](https://github.com/user-attachments/assets/e6f7ffdb-ed5d-4d97-ad0f-cf9de09a99e2)

### Operating Environment

Debian 12
FreePBX 17.0.17.1
Asterisk 21.3.1

**Comment by jissphilip** [comment]
manager version 17.0.6
