### ISSUE TITLE
[improvement]: Add File Size in Backup API

### ISSUE THREAD

**Issue by danardf** [FreePBX/issue-tracker#334]
### FreePBX Version

FreePBX 16

### Improvement Description

To be consistent with the GUI, fetchAllBackups should provide the field "Size" in the list.

I'm creating a PR for this ticket.

**Comment by danardf** [comment]
PR Done.
https://github.com/FreePBX/backup/pull/63

**Comment by danardf** [comment]
@kguptasangoma 
Hi. Have you got some news?

**Comment by kapilgupta01** [comment]
backup v16.0.70.1
(merged to 17 as well so next release of backup module in 17 will have this fix as well)
