### ISSUE TITLE
[bug]: Ioncube requirement with sysadmin code present

### ISSUE THREAD

**Issue by jfinstrom** [FreePBX/issue-tracker#335]
### FreePBX Version

FreePBX 16

### Issue Description

If you have the sysadmin module present, not enabled or installed it will trigger an ioncube warning. I had to run fwconsole ma remove sysadmin to get rid of the ioncube intercept.   The only thing I can find in the code is in Userman functions.inc is loaded directly but it shouldn't be unless sysadmin is enabled.   So not sure what is being called. 

### Operating Environment

Ubuntu 22.04 installed with official script, commercial modules removed

**Comment by jfinstrom** [comment]
Note ioncube is on this system so it shouldn't error but it was unhappy
`root@dev:~# php -v
PHP 8.2.21 (cli) (built: Jul  4 2024 16:26:28) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.21, Copyright (c) Zend Technologies
    with the ionCube PHP Loader v13.0.2, Copyright (c) 2002-2023, by ionCube Ltd.
    with Zend OPcache v8.2.21, Copyright (c), by Zend Technologies
root@dev:~#`

**Comment by kapilgupta01** [comment]
hi @jfinstrom what kind of error you were seeing ? is it "ioncube license error " in the freepbx_dbug message?

**Comment by jfinstrom** [comment]
It looks like apache2 was using a different php version than the cli.  So FreePBX was running under php8.1 which didn't have the appropriate configs. 

If anyone runs across this in the future they can run 

`a2query -m  |  grep php`

**Comment by kapilgupta01** [comment]
Hi @jfinstrom  thanks for that command, I will add that to installation script as a part of post validation.
