### ISSUE TITLE
FTP Filestore unable to authenticate [bug]: 

### ISSUE THREAD

**Issue by AA7CL** [FreePBX/issue-tracker#339]
### FreePBX Version

FreePBX 17

### Issue Description

Running a fresh install of FreePBX 17 beta, I restored from version 16 and getting an error while running a backup to a FTP server configured in the filestore. The error says “unable to login/authenticate with FTP”. I have confirmed all of the credentials and settings are okay in the FTP/Filestore and confirmed them using Fileszilla. Executing  FTP on the CLI, FTP doesn't appear to be installed. Am I missing something?

### Operating Environment

Package: freepbx17
Version: 17.1-1.sng12
Priority: extra
Section: alien
Maintainer: root <root@8f6030df246f>
Installed-Size: 623 MB
Download-Size: 197 MB
APT-Manual-Installed: yes
APT-Sources: http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
Description: Asterisk FreePBX Web Interface
 FreePBX is a GUI that gives you the ability to manage your Asterisk system.
 This RPM Contains FreePBX Version 17.1
 .
 (Converted from a rpm package by alien version 8.95.6.)

+---------------------+-----------+----------+------------+-----------+
| Module              | Version   | Status   | License    | Signature |
+---------------------+-----------+----------+------------+-----------+
| accountcodepreserve | 17.0.0.1  | Enabled  | GPLv2      | Sangoma   |
| allowlist           | 17.0.1.1  | Enabled  | GPLv3+     | Sangoma   |
| amd                 | 17.0.1    | Enabled  | GPLv3+     | Sangoma   |
| announcement        | 17.0.2.1  | Enabled  | GPLv3+     | Sangoma   |
| api                 | 17.0.1.6  | Enabled  | AGPLv3+    | Sangoma   |
| areminder           | 17.0.3.10 | Disabled | Commercial | Sangoma   |
| arimanager          | 17.0.1.1  | Enabled  | GPLv3+     | Sangoma   |
| asterisk-cli        | 17.0.2    | Enabled  | GPLv3+     | Sangoma   |
| asteriskinfo        | 17.0.2    | Enabled  | GPLv3+     | Sangoma   |
| backup              | 17.0.5.58 | Enabled  | GPLv3+     | Sangoma   |
| blacklist           | 17.0.1.2  | Enabled  | GPLv3+     | Sangoma   |
| broadcast           | 17.0.1.6  | Disabled | Commercial | Sangoma   |
| builtin             |           | Enabled  |            | Unsigned  |
| bulkhandler         | 17.0.5    | Enabled  | GPLv3+     | Sangoma   |
| calendar            | 17.0.4.15 | Enabled  | GPLv3+     | Sangoma   |
| callback            | 17.0.2.1  | Enabled  | GPLv3+     | Sangoma   |
| callerid            | 17.0.1    | Disabled | Commercial | Sangoma   |
| callforward         | 17.0.1.6  | Enabled  | AGPLv3+    | Sangoma   |
| calllimit           | 17.0.1.2  | Enabled  | Commercial | Sangoma   |
| callrecording       | 17.0.3.7  | Enabled  | AGPLv3+    | Sangoma   |
| callwaiting         | 17.0.3.4  | Enabled  | GPLv3+     | Sangoma   |
| cdr                 | 17.0.4.16 | Enabled  | GPLv3+     | Sangoma   |
| cdrpro              | 17.0.3.19 | Enabled  | Commercial | Sangoma   |
| cel                 | 17.0.2.8  | Enabled  | GPLv3+     | Sangoma   |
| certman             | 17.0.3.12 | Enabled  | AGPLv3+    | Sangoma   |
| cidlookup           | 17.0.1.1  | Enabled  | GPLv3+     | Sangoma   |
| conferences         | 17.0.3.2  | Enabled  | GPLv3+     | Sangoma   |
| conferencespro      | 17.0.1.7  | Disabled | Commercial | Sangoma   |
| configedit          | 17.0.1.1  | Enabled  | AGPLv3+    | Sangoma   |
| contactmanager      | 17.0.5.11 | Enabled  | GPLv3+     | Sangoma   |
| core                | 17.0.13   | Enabled  | GPLv3+     | Sangoma   |
| cos                 | 17.0.1.1  | Disabled | Commercial | Sangoma   |
| customappsreg       | 17.0.1    | Enabled  | GPLv3+     | Sangoma   |
| customcontexts      | 17.0.1.3  | Enabled  | GPLv2+     | Sangoma   |
| dashboard           | 17.0.4.3  | Enabled  | AGPLv3+    | Sangoma   |
| daynight            | 17.0.1.1  | Enabled  | GPLv3+     | Sangoma   |
| dictate             | 17.0.1.2  | Enabled  | GPLv3+     | Sangoma   |
| directory           | 17.0.1.1  | Enabled  | GPLv3+     | Sangoma   |
| disa                | 17.0.3    | Enabled  | AGPLv3+    | Sangoma   |
| donotdisturb        | 17.0.2.3  | Enabled  | GPLv3+     | Sangoma   |
| dynroute            | 17.0.3.1  | Enabled  | GPLv3+     | Sangoma   |
| endpoint            | 17.0.1.73 | Enabled  | Commercial | Sangoma   |
| extensionroutes     | 17.0.1    | Enabled  | Commercial | Sangoma   |
| extensionsettings   | 17.0.1    | Enabled  | GPLv3+     | Sangoma   |
| fax                 | 17.0.3.4  | Enabled  | GPLv3+     | Sangoma   |
| faxpro              | 17.0.1.18 | Disabled | Commercial | Sangoma   |
| featurecodeadmin    | 17.0.2    | Enabled  | GPLv3+     | Sangoma   |
| filestore           | 17.0.2.22 | Enabled  | AGPLv3     | Sangoma   |
| findmefollow        | 17.0.4.9  | Enabled  | GPLv3+     | Sangoma   |
| firewall            | 17.0.1.26 | Enabled  | AGPLv3+    | Sangoma   |
| framework           | 17.0.19.1 | Enabled  | GPLv2+     | Sangoma   |
| hotelwakeup         | 17.0.1.6  | Enabled  | GPLv2      | Sangoma   |
| iaxsettings         | 17.0.1    | Enabled  | AGPLv3     | Sangoma   |
| infoservices        | 17.0.1.1  | Enabled  | GPLv2+     | Sangoma   |
| ivr                 | 17.0.6    | Enabled  | GPLv3+     | Sangoma   |
| languages           | 17.0.1    | Enabled  | GPLv3+     | Sangoma   |
| logfiles            | 17.0.3.3  | Enabled  | GPLv3+     | Sangoma   |
| manager             | 17.0.6    | Enabled  | GPLv2+     | Sangoma   |
| miscapps            | 17.0.3    | Enabled  | GPLv3+     | Sangoma   |
| miscdests           | 17.0.1.1  | Enabled  | GPLv3+     | Sangoma   |
| missedcall          | 17.0.1.1  | Enabled  | GPLv3+     | Sangoma   |
| music               | 17.0.5    | Enabled  | GPLv3+     | Sangoma   |
| outcnam             | 17.0.1    | Enabled  | GPLv3+     | Sangoma   |
| outroutemsg         | 17.0.1    | Enabled  | GPLv3+     | Sangoma   |
| paging              | 17.0.3    | Enabled  | GPLv3+     | Sangoma   |
| pagingpro           | 17.0.1.6  | Disabled | Commercial | Sangoma   |
| parking             | 17.0.2.4  | Enabled  | GPLv3+     | Sangoma   |
| parkpro             | 17.0.1.4  | Disabled | Commercial | Sangoma   |
| phpinfo             | 17.0.1    | Enabled  | GPLv2+     | Sangoma   |
| pinsets             | 17.0.3.2  | Enabled  | GPLv3+     | Sangoma   |
| pinsetspro          | 17.0.2    | Disabled | Commercial | Sangoma   |
| pm2                 | 17.0.3.2  | Enabled  | AGPLv3+    | Sangoma   |
| pms                 | 17.0.2.15 | Disabled | Commercial | Sangoma   |
| presencestate       | 17.0.2.4  | Enabled  | GPLv3+     | Sangoma   |
| printextensions     | 17.0.1.2  | Enabled  | GPLv3+     | Sangoma   |
| queueprio           | 17.0.1.4  | Enabled  | GPLv3+     | Sangoma   |
| queues              | 17.0.1.10 | Enabled  | GPLv2+     | Sangoma   |
| queuestats          | 17.0.1.7  | Disabled | Commercial | Sangoma   |
| qxact_reports       | 17.0.3    | Disabled | Commercial | Sangoma   |
| recording_report    | 17.0.3.8  | Disabled | Commercial | Sangoma   |
| recordings          | 17.0.2.2  | Enabled  | GPLv3+     | Sangoma   |
| restapps            | 17.0.1.20 | Enabled  | Commercial | Sangoma   |
| ringgroups          | 17.0.2.4  | Enabled  | GPLv3+     | Sangoma   |
| sangomacrm          | 17.0.1.15 | Disabled | Commercial | Sangoma   |
| sangomartapi        | 17.0.1.28 | Enabled  | Commercial | Sangoma   |
| setcid              | 17.0.1.2  | Enabled  | GPLv3+     | Sangoma   |
| sipsettings         | 17.0.6.8  | Enabled  | AGPLv3+    | Sangoma   |
| sipstation          | 17.0.3.3  | Enabled  | Commercial | Sangoma   |
| sms                 | 17.0.1.15 | Enabled  | Commercial | Sangoma   |
| smsplus             | 17.0.3    | Enabled  | Commercial | Sangoma   |
| soundlang           | 17.0.4.1  | Enabled  | GPLv3+     | Sangoma   |
| superfecta          | 17.0.2    | Enabled  | GPLv2+     | Sangoma   |
| sysadmin            | 17.0.1.92 | Enabled  | Commercial | Sangoma   |
| timeconditions      | 17.0.1.18 | Enabled  | GPLv3+     | Sangoma   |
| tts                 | 17.0.1.1  | Enabled  | GPLv3+     | Sangoma   |
| ttsengines          | 17.0.1    | Enabled  | AGPLv3     | Sangoma   |
| ucp                 | 17.0.4.20 | Enabled  | AGPLv3+    | Sangoma   |
| userman             | 17.0.6.26 | Enabled  | AGPLv3+    | Sangoma   |
| vmblast             | 17.0.2    | Enabled  | GPLv3+     | Sangoma   |
| vmnotify            | 17.0.1.7  | Disabled | Commercial | Sangoma   |
| voicemail           | 17.0.5.22 | Enabled  | GPLv3+     | Sangoma   |
| voicemail_report    | 17.0.1.1  | Disabled | Commercial | Sangoma   |
| voipinnovations     | 17.0.1.4  | Enabled  | Commercial | Sangoma   |
| vqplus              | 17.0.1.16 | Disabled | Commercial | Sangoma   |
| weakpasswords       | 17.0.1    | Enabled  | GPLv3+     | Sangoma   |
| webcallback         | 17.0.4    | Enabled  | Commercial | Sangoma   |
| webrtc              | 17.0.2.2  | Enabled  | GPLv3+     | Sangoma

### Relevant log output

```shell
I can't find any relevant logs that show any FTP/backup activitiy
```

**Comment by msanthosh18** [comment]
Hi @AA7CL 
Can you try to login from Freepbx -17 system to ftp server  by using below command to confirm ftp access is fine from FreePBX 

`sftp -P 21 ftpuser@ftpserverip`
then enter the ftp login password, if this connection established then filestore ftp instance will work, 
If still an issue even after ftp connection success, please provide the below logs 

`/var/log/asterisk/backup.log`

**Comment by AA7CL** [comment]
Thank you for your quick response!

A little more info:

FreePBX-17:

[cid:49968228-4adf-41ed-812d-83b439a9936b]

I've tried with TLS enabled and disabled, same result.


I'm using TrueNAS share to store the backup.

This is what I get when using port 21

***@***.***:~# sftp -P21 ***@***.***
kex_exchange_identification: Connection closed by remote host
Connection closed by 192.168.1.10 port 21
Connection closed.
Connection closed

From the syslog on the TrueNAS server:

Aug 05 11:16:21 truenas proftpd[2235637]: 127.0.0.1 (192.168.1.7[192.168.1.7]) - client sent SSH2 command 'SSH-2.0-OpenSSH_9.2p1', disconnecting

I can login on port 22 with the same credentials:

***@***.***:~# sftp ***@***.***
***@***.***'s password:
Connected to 192.168.1.10.
sftp>


Any suggestions?

Thank you!


________________________________

**Comment by AA7CL** [comment]
A little more debug:
root@freepbx-deb:~# sftp -v -P21 freepbx@192.168.1.10
OpenSSH_9.2p1 Debian-2+deb12u3, OpenSSL 3.0.13 30 Jan 2024
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 192.168.1.10 [192.168.1.10] port 21.
debug1: Connection established.
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa_sk type -1
debug1: identity file /root/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: identity file /root/.ssh/id_ed25519_sk type -1
debug1: identity file /root/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /root/.ssh/id_xmss type -1
debug1: identity file /root/.ssh/id_xmss-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u3
debug1: kex_exchange_identification: banner line 0: 220 ProFTPD Server (truenas FTP Server) [::ffff:192.168.1.10]
kex_exchange_identification: Connection closed by remote host
Connection closed by 192.168.1.10 port 21
Connection closed.  
Connection closed

**Comment by kapilgupta01** [comment]
Hi @AA7CL what is the port settings in your filestore / FTP instance? please ensure that config is right

**Comment by AA7CL** [comment]
Yes, the settings are correct. 

I can use Filezilla to login into the NAS using the same credentials  on port 21. TLS is required on the NAS and Filezilla negotiates the connection just fine. 

What client does FreePBX use to connect to  a FTP server using TLS?  I can't find any logs that show a connection.

**Comment by AA7CL** [comment]
I just booted up the old VM running FreePBX 16.0.40.8 and the filestore  is configured the same way. The backup ran and successfully and  connect  to the NAS. I noticed on freepbx -17, there is no FTP client installed. Could this be the issue?

**Comment by AA7CL** [comment]
More info: I was able to establish an Openssl  connection from the command line. "openssl s_client -tls1_2 -crlf -connect 192.168.1.10:21 -starttls ftp". I installed the FTP client on the Debian 12 distro I'm running freePBX 17 on. Still unable to authenticate using the backup/restore module.  I did install ftp-ssl on another host and was able to login to the NAS with not issues. I removed the filestore configuration, rebooted freePBX and re-configured the FTP filestore with the same results, Unable to authenticate. So, I still believe there is some sort of bug in the backup and restore module. Any ideas or tests I should run would be helpful!

Thanks,
Jim

**Comment by kapilgupta01** [comment]
Hi @AA7CL by chance is it possible for you to create a test account for us in your NAS so we can try to connect to your server?

If you are okay then please send me email with the credentials to kgupta@sangoma.com 

Freepbx 17 has updated openssl and supported upgraded version of PHP libraries in Filestore module so not sure if that something is causing any issue.

Thanks

**Comment by AA7CL** [comment]
Sorry, the NAS is not available to the public.

Jim
________________________________

**Comment by AA7CL** [comment]
I ran a tcpdump this morning. Looks like TLS is not working. Can I send a pcap file?

Jim
________________________________

**Comment by AA7CL** [comment]
Snippet from the pcap (attached) file:

8	0.049450	8	192.168.1.10	192.168.1.7	FTP	117	Response: 550 SSL/TLS required on the control channel
9	0.050295	9	192.168.1.7	192.168.1.10	FTP	78	Request: QUIT
10	0.050671	10	192.168.1.10	192.168.1.7	FTP	86	Response: 221 Goodbye.
[ftp.zip](https://github.com/user-attachments/files/16530934/ftp.zip)

**Comment by kapilgupta01** [comment]
Hi @AA7CL without accessing your system its hard to say whats going on ? Freepbx 17 has got the newer version of PHP libraries so may be there might be some compatibility issue. 
If you can raise support request then please raise one and give me the case number so we can ssh to your system to debug this issue further.

Thanks

**Comment by kapilgupta01** [comment]
Hi, 

This appears to be a support issue. 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta

**Comment by AA7CL** [comment]
As I have said before, my NAS is not available to the Public. However, you can create a trial FTP server at Files.com and test it there. Or as an alternative, spin up a VM and install FTP server software on your own network. Configure it to use TLS and then try and connect to it using the Backup and Restore Module. From the testing I've done, there is no  TLS handshake from the client (FreePBX) even though "use TLS" switch is enabled in the Filestore. This is clearly a bug! I've opened a case but was told to buy support credits. This is not a support issue. Thanks for your help!
