### ISSUE TITLE
[bug]: Unable to install on arm64

### ISSUE THREAD

**Issue by realJoshByrnes** [FreePBX/issue-tracker#340]
### FreePBX Version

FreePBX 17

### Issue Description

As expected, it's not possible to install FreePBX on aarch64 (specifically, Apple silicon) devices with the official installation script.

`Linux **** 6.1.0-20-cloud-arm64 #1 SMP Debian 6.1.85-1 (2024-04-11) aarch64 GNU/Linux`

There's a few notable issues when running the installer:
- The FreePBX repo doesn't support aarch64.
- MongoDB 7.0 doesn't support arm64 on Debian.

I'm investigating where the issues lie to have freepbx installing on aarch64 natively, or with amd64 emulation through Rosetta, etc.

### Operating Environment

N/A

**Comment by reraikes** [comment]
FreePBX has been running natively on arm64 Raspberry Pi's for years using Debian (including FreePBX 17 now).

For details, see: https://www.dslreports.com/forum/r30661088-PBX-FreePBX-for-the-Raspberry-Pi

**Comment by realJoshByrnes** [comment]
Hi @reraikes, You're absolutely right (I have FreePBX on a Pi), but I was referring to the official installer. My bad for not making that clear.

**Comment by kapilgupta01** [comment]
Hi @realJoshByrnes thanks for the reporting this issue, however our first priority to have Stable freepbx 17 on Debian 12.x platform.

**Comment by realJoshByrnes** [comment]
@kguptasangoma Of course. I'm actually also referring to freepbx 17 on Debian 12.x, just with Arm64.
Wasn't expecting anything to be done, I created this issue so I could reference it when I'm making changes and/or submitting a PR.
