### ISSUE TITLE
[bug]: systemctl reload apache2 has a problem

### ISSUE THREAD

**Issue by zhigang327** [FreePBX/issue-tracker#342]
### FreePBX Version

FreePBX 17

### Issue Description

When the script runs to systemctl reload apache2, an error will occur and the script will exit without completing the installation.

### Operating Environment

FreePBX17

### Relevant log output

```shell
Starting module download from https://mirror.freepbx.org/modules/packages/core/core-17.0.13.tgz.gpg ...
Processing
Downloading...
       0/1175597 [>---------------------------]   0%
     723/1175597 [>---------------------------]   0%
  118218/1175597 [==>-------------------------]  10%
  236112/1175597 [=====>----------------------]  20%
  353120/1175597 [========>-------------------]  30%
  471288/1175597 [===========>----------------]  40%
  588296/1175597 [==============>-------------]  50%
  706464/1175597 [================>-----------]  60%
  823472/1175597 [===================>--------]  70%
  940624/1175597 [======================>-----]  80%
 1175597/1175597 [============================] 100%
Finished downloading
Extracting...Done
Module https://mirror.freepbx.org/modules/packages/core/core-17.0.13.tgz.gpg successfully downloaded
Updating tables trunks, pjsip, sip, dahdi, iax, indications_zonelist, devices, users, incoming, dahdichandids, outbound_route_patterns, outbound_route_sequence, outbound_route_trunks, outbound_routes, outbound_route_email, trunk_dialpatterns...Done
Starting Call Transfer Monitoring Service
Stopping Call Transfer Monitoring Service
Restarting Call Transfer Monitoring Service
Adding emergencydevices table..Done
Migrating pickup groups to named pickup groups
Migrating call groups to named call groups
Checking for possibly invalid emergency caller id fields..none found
Migrating old media encryption values...done
Removing encoding on incoming routes alertinfo values...done
Generating CSS...Done
Module core version 17.0.13 successfully installed
Updating Hooks...Done
Chowning directories...Done
        Verifying GPG...
Done
Checking cos...
Good
Checking customappsreg...
Good
Checking customcontexts...
Good
Checking dashboard...
Good
Checking daynight...
Good
Checking dictate...
Good
Checking directory...
Good
Checking disa...
Good
Checking donotdisturb...
Good
Checking dynroute...
Good
Checking endpoint...
Signature Invalid
        Refreshing endpoint
Unable to update module endpoint - 17.0.1.73:
        Verifying GPG...
Done
Checking extensionroutes...
Good
Checking extensionsettings...
Good
Checking fax...
Good
Checking faxpro...
Signature Invalid
        Refreshing faxpro
Unable to update module faxpro - 17.0.1.18:
        Verifying GPG...
Done
Checking featurecodeadmin...
Good
Checking filestore...
Good
Checking findmefollow...
Good
Checking firewall...
Good
Checking framework...
Signature Invalid
        Refreshing framework
Starting module download from https://mirror.freepbx.org/modules/packages/framework/framework-17.0.19.1.tgz.gpg ...
Processing
Downloading...
        0/17296063 [>---------------------------]   0%
In Curl.php line 490:

  cURL error 28: SSL connection timeout


moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [<args>...]

2024-08-05 09:29:05 - ****** INSTALLATION FAILED *****
2024-08-05 09:29:05 - Installation failed at step Wrapping up the installation process. Please check log /var/log/pbx/freepbx17-install-2024.08.05-08.39.26.log for details.
2024-08-05 09:29:05 - Error at line: 1161 exiting with code 1 (last command was: fwconsole ma refreshsignatures >> "$log" 2>&1)
2024-08-05 09:29:05 - Exiting script
```

**Comment by zhigang327** [comment]
I reinstalled several times in a row, and each time a different error occurred, but the error was always on line 1161

Stopped UCP Node Server
Shutting down Asterisk Gracefully. Will forcefully kill after 30 seconds.
Press C to Cancel
Press N to shut down NOW
[>---------------------------] < 1 sec[->--------------------------] < 1 sec
Advanced Recovery service is not running
Queue Callback Server is not running
Queue Callback Event Server is not running
Running FreePBX startup...
Running Asterisk pre from Firewall module
Running Asterisk pre from Sysadmin module
Running Sysadmin Hooks
Firewall module detected.
Restarting fail2ban
fail2ban Restarted
Checking Vpn server
Starting Asterisk...
[>---------------------------] < 1 sec
[->--------------------------] < 1 sec
[--->------------------------] < 1 sec
[----->----------------------] 1 sec
[------->--------------------] 1 sec
[--------->------------------] 1 sec
[----------->----------------] 1 sec
Asterisk Started
Running Asterisk post from Adv_recovery module
Advanced Recovery is not licensed.
Running Asterisk post from Cdrpro module
Cdrpro is not licensed.
Stopping CDRpro Service
cdrpro is not running
Running Asterisk post from Core module
Starting Call Transfer Monitoring Service
Starting Core FastAGI Server...
[>---------------------------] < 1 sec
Started Core FastAGI Server. PID is 118906
Running Asterisk post from Endpoint module
Running Asterisk post from Pagingpro module
Running Asterisk post from Restapps module
RestApps is not licensed.
Running Asterisk post from Sangomaconnect module
This product is not licensed
Running Asterisk post from Sangomartapi module
Starting Sangoma RT API Server...
[>---------------------------] < 1 sec
Started Sangoma RT API Server. PID is 119021
Running Asterisk post from Ucp module
Starting UCP Node Server...
[>---------------------------] < 1 sec
Started UCP Node Server. PID is 119121
Running Asterisk post from Vqplus module
Queues Pro is not licensed.
2024-08-05 12:01:25 - Wrapping up the installation process
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Enabling module socache_shmcb.
Enabling module ssl.
See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
To activate the new configuration, you need to run:
  systemctl restart apache2
Enabling module expires.
To activate the new configuration, you need to run:
  systemctl restart apache2
Enabling module rewrite.
To activate the new configuration, you need to run:
  systemctl restart apache2
Warning: The unit file, source configuration file or drop-ins of apache2.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Getting Data from Online Server...
Done
Checking Signatures of Modules...
Checking accountcodepreserve...
Good
Checking adv_recovery...
Good
Checking allowlist...
Good
Checking amd...
Good
Checking announcement...
Good
Checking api...
Good
Checking areminder...
Good
Checking arimanager...
Good
Checking asterisk-cli...
Good
Checking asteriskinfo...
Good
Checking backup...
Good
Checking blacklist...
Good
Checking broadcast...
Good
Checking builtin...
Checking bulkhandler...
Good
Checking calendar...
Good
Checking callaccounting...
Good
Checking callback...
Good
Checking callerid...
Good
Checking callforward...
Good
Checking calllimit...
Good
Checking callrecording...
Good
Checking callwaiting...
Good
Checking cdr...
Good
Checking cdrpro...
Good
Checking cel...
Good
Checking certman...
Good
Checking cidlookup...
Good
Checking conferences...
Good
Checking conferencespro...
Good
Checking configedit...
Good
Checking contactmanager...
Good
Checking core...
Signature Invalid
        Refreshing core
Starting module download from https://mirror.freepbx.org/modules/packages/core/core-17.0.13.tgz.gpg ...
Processing
The following error(s) occured:
 - Failed download module tarball from https://mirror.freepbx.org/modules/packages/core/core-17.0.13.tgz.gpg, server may be down
2024-08-05 12:01:49 - ****** INSTALLATION FAILED *****
2024-08-05 12:01:49 - Installation failed at step Wrapping up the installation process. Please check log /var/log/pbx/freepbx17-install-2024.08.05-10.50.15.log for details.
2024-08-05 12:01:49 - Error at line: 1161 exiting with code 2 (last command was: fwconsole ma refreshsignatures >> "$log" 2>&1)
2024-08-05 12:01:49 - Exiting script

**Comment by kapilgupta01** [comment]
Can you please retry "fwconsole ma refreshsignatures" once again ? thanks

**Comment by zhigang327** [comment]
> 您能否再试一次“fwconsole ma refreshsignatures”？谢谢

Of course, how do I do it?

**Comment by kapilgupta01** [comment]
"fwconsole ma refreshsignatures"  execute this from the linux CLI please

**Comment by zhigang327** [comment]
> "fwconsole ma refreshsignatures" execute this from the linux CLI please

OK, I'll try it
