### ISSUE TITLE
[bug]: The Administration button does not work

### ISSUE THREAD

**Issue by mischa365** [FreePBX/issue-tracker#343]
### FreePBX Version

FreePBX 16

### Issue Description

![2024-08-05_12-26-59](https://github.com/user-attachments/assets/9c22bc15-e681-4a98-b94e-aca994f18b5e)

### Operating Environment

Linux

**Comment by kapilgupta01** [comment]
is this freepbx 16 or freepbx 17 @mischa365 ?

**Comment by mischa365** [comment]
16

**Comment by msanthosh18** [comment]
Hi @mischa365 
Ensure all modules are latest and clear the browser cache then try, do you see any error on browser console log when you click on Administration login button ..?

Did you tried any other different browser.?

**Comment by mischa365** [comment]
The modules have been updated. There is no error, it's just as if the administration button is not responding. I've tried other browsers.

**Comment by msanthosh18** [comment]
Hi @mischa365 ,
Can you open browser console log, just reload the tab and share the console screenshot, since we are unable to reproduce the issue in my testing system

**Comment by mischa365** [comment]
![2024-08-05_14-22-26](https://github.com/user-attachments/assets/8c7c73ca-cb9a-4b37-84dc-7fabcdda7166)

**Comment by msanthosh18** [comment]
Hi @mischa365 ,
The screenshot you shared is Elements log, not console log, please click on red marked place and see there should be an error when you click on administrator button, we need that screen shot to see the error.

![image](https://github.com/user-attachments/assets/35248fc0-30ba-49e5-88cb-b29ea47261b6)

**Comment by mischa365** [comment]
![2024-08-05_14-53-38](https://github.com/user-attachments/assets/2a25be54-e397-4bbd-adff-0bf1175725e2)

**Comment by kapilgupta01** [comment]
Hi @mischa365 if you set the language to english then are you able to login?

**Comment by mischa365** [comment]
No

**Comment by kapilgupta01** [comment]
can you please check "fwconsole debug" and find out if you are seeing any error or any error in httpd (error/access) logs?

**Comment by mischa365** [comment]
![2024-08-05_15-28-58](https://github.com/user-attachments/assets/18c5cc66-9500-4857-92a1-4aacb86d144e)

**Comment by kapilgupta01** [comment]
Hi @mischa365 you can try following commands from the linux cli - 
1) `fwconsole ma upgradeall `
2) `fwconsole restart`

Try to access the UI and check below logs - 
`/var/log/httpd/error_log` and `/var/log/httpd/access_log`

**Comment by mischa365** [comment]
![2024-08-06_08-03-06](https://github.com/user-attachments/assets/86503b4e-7cc2-458c-9b4d-b2abb6129c30)

**Comment by kapilgupta01** [comment]
so do you see any error in httpd logs ?

**Comment by mischa365** [comment]
Permission denied

**Comment by mischa365** [comment]
I log in under the administrator

**Comment by kapilgupta01** [comment]
/
Hi, 

This appears to be a support issue. 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta
