### ISSUE TITLE
[bug]: Contact Manager - Failed to Install

### ISSUE THREAD

**Issue by mandersonbluepride** [FreePBX/issue-tracker#344]
### FreePBX Version

FreePBX 17

### Issue Description

When trying to update a contact's email address etc I got an error - I can't seem to get it to install etc: Exception thrown with message "Unable to locate the FreePBX BMO Class 'Contactmanager'A required module might be disabled or uninstalled. Recommended steps (run from the CLI): 1) fwconsole ma install contactmanager 2) fwconsole ma enable contactmanager"

Stacktrace:
#9 Exception in /var/www/html/admin/libraries/BMO/Self_Helper.class.php:214
#8 FreePBX\Self_Helper:loadObject in /var/www/html/admin/libraries/BMO/Self_Helper.class.php:108
#7 FreePBX\Self_Helper:autoLoad in /var/www/html/admin/libraries/BMO/Self_Helper.class.php:39
#6 FreePBX\Self_Helper:__get in /var/www/html/admin/modules/restapps/Restapps.class.php:673
#5 FreePBX\modules\Restapps:usermanShowPage in /var/www/html/admin/libraries/BMO/Hooks.class.php:320
#4 call_user_func_array in /var/www/html/admin/libraries/BMO/Hooks.class.php:320
#3 FreePBX\Hooks:executeCall in /var/www/html/admin/libraries/BMO/Hooks.class.php:355
#2 FreePBX\Hooks:processHooks in /var/www/html/admin/modules/userman/Userman.class.php:777
#1 FreePBX\modules\Userman:myShowPage in /var/www/html/admin/modules/userman/page.userman.php:2
#0 include in /var/www/html/admin/config.php:658

![Screenshot 2024-08-05 at 9 32 50 AM](https://github.com/user-attachments/assets/6f5adaac-9573-4185-876a-2b2be9b07eeb)

Upon trying to run the commands, the first command gets "Done" but never does anything so then then I try to run the second command and I get the error "Module contactmanager cannot be enabled"
![Screenshot 2024-08-05 at 9 34 38 AM](https://github.com/user-attachments/assets/a1c36fdc-8206-4d3b-9fea-6bcd1ef2c5a3)
![Screenshot 2024-08-05 at 9 35 00 AM](https://github.com/user-attachments/assets/957a6571-87df-477d-9cbb-71b3d97de04c)

### Operating Environment

FreePBX 17.0.19.1
Asterisk: 21.4.1

No repos specified, using: [standard,commercial] from last GUI settings

+---------------------+-----------+-----------------------------------+-------------+-----------+
| Module              | Version   | Status                            | License     | Signature |
+---------------------+-----------+-----------------------------------+-------------+-----------+
| accountcodepreserve | 17.0.0.1  | Enabled                           | GPLv2       | Sangoma   |
| adv_recovery        | 17.0.4    | Enabled                           | Commercial  | Sangoma   |
| allowlist           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| amd                 | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| api                 | 17.0.1.6  | Enabled                           | AGPLv3+     | Sangoma   |
| areminder           | 17.0.3.10 | Enabled                           | Commercial  | Sangoma   |
| arimanager          | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| backup              | 17.0.5.58 | Enabled                           | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| broadcast           | 17.0.1.6  | Enabled                           | Commercial  | Sangoma   |
| builtin             |           | Enabled                           |             | Unsigned  |
| bulkhandler         | 17.0.5    | Enabled                           | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.15 | Enabled                           | GPLv3+      | Sangoma   |
| callaccounting      | 17.0.5    | Enabled                           | Commercial+ | Sangoma   |
| callback            | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| callerid            | 17.0.1    | Enabled                           | Commercial  | Sangoma   |
| callforward         | 17.0.1.6  | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit           | 17.0.1.2  | Enabled                           | Commercial  | Sangoma   |
| callrecording       | 17.0.3.7  | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4  | Enabled                           | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.16 | Enabled                           | GPLv3+      | Sangoma   |
| cdrpro              | 17.0.3.19 | Enabled                           | Commercial  | Sangoma   |
| cel                 | 17.0.2.8  | Enabled                           | GPLv3+      | Sangoma   |
| certman             | 17.0.3.12 | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro      | 17.0.1.7  | Enabled                           | Commercial  | Sangoma   |
| configedit          | 17.0.1.1  | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager      |           | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| core                | 17.0.13   | Enabled                           | GPLv3+      | Sangoma   |
| cos                 | 17.0.1.1  | Enabled                           | Commercial  | Sangoma   |
| customappsreg       | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.3  | Enabled                           | GPLv2+      | Sangoma   |
| dashboard           | 17.0.4.3  | Enabled                           | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| disa                | 17.0.3    | Enabled                           | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3  | Enabled                           | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.1  | Enabled                           | GPLv3+      | Sangoma   |
| endpoint            | 17.0.1.73 | Enabled                           | Commercial  | Sangoma   |
| extensionroutes     | 17.0.1    | Enabled                           | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4  | Enabled                           | GPLv3+      | Sangoma   |
| faxpro              | 17.0.1.18 | Enabled                           | Commercial  | Sangoma   |
| featurecodeadmin    | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.22 | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.9  | Enabled                           | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.26 | Enabled                           | AGPLv3+     | Sangoma   |
| framework           | 17.0.19.1 | Enabled                           | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6  | Enabled                           | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1    | Enabled                           | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1.1  | Enabled                           | GPLv2+      | Sangoma   |
| ivr                 | 17.0.6    | Enabled                           | GPLv3+      | Sangoma   |
| languages           | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3  | Enabled                           | GPLv3+      | Sangoma   |
| manager             | 17.0.6    | Enabled                           | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| music               | 17.0.5    | Enabled                           | GPLv3+      | Sangoma   |
| oembranding         |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| outcnam             | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| paging              | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro           | 17.0.1.6  | Enabled                           | Commercial  | Sangoma   |
| parking             | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| parkpro             | 17.0.1.4  | Enabled                           | Commercial  | Sangoma   |
| pbxmfa              | 17.0.2.1  | Enabled                           | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1    | Enabled                           | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro          | 17.0.2    | Enabled                           | Commercial  | Sangoma   |
| pm2                 | 17.0.3.2  | Enabled                           | AGPLv3+     | Sangoma   |
| pms                 | 17.0.2.15 | Enabled                           | Commercial  | Sangoma   |
| presencestate       | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4  | Enabled                           | GPLv3+      | Sangoma   |
| queues              | 17.0.1.10 | Enabled                           | GPLv2+      | Sangoma   |
| queuestats          | 17.0.1.7  | Enabled                           | Commercial  | Sangoma   |
| qxact_reports       | 17.0.3    | Enabled                           | Commercial  | Sangoma   |
| recording_report    | 17.0.3.8  | Enabled                           | Commercial  | Sangoma   |
| recordings          | 17.0.2.2  | Enabled                           | GPLv3+      | Sangoma   |
| restapps            | 17.0.1.20 | Enabled                           | Commercial  | Sangoma   |
| ringgroups          | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect      | 17.0.1.35 | Enabled                           | Commercial  | Sangoma   |
| sangomacrm          | 17.0.1.16 | Enabled                           | Commercial  | Sangoma   |
| sangomartapi        | 17.0.1.28 | Enabled                           | Commercial  | Sangoma   |
| setcid              | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.8  | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation          | 17.0.3.3  | Enabled                           | Commercial  | Sangoma   |
| sms                 | 17.0.1.15 | Enabled                           | Commercial  | Sangoma   |
| smsplus             | 17.0.3    | Enabled                           | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1  | Enabled                           | GPLv3+      | Sangoma   |
| superfecta          | 17.0.2    | Enabled                           | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.92 | Enabled                           | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.18 | Enabled                           | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1    | Enabled                           | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.20 | Enabled                           | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.26 | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| vmnotify            | 17.0.1.7  | Enabled                           | Commercial  | Sangoma   |
| voicemail           | 17.0.5.22 | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report    | 17.0.1.1  | Enabled                           | Commercial  | Sangoma   |
| voipinnovations     | 17.0.1.4  | Enabled                           | Commercial  | Sangoma   |
| vqplus              | 17.0.1.16 | Enabled                           | Commercial  | Sangoma   |
| weakpasswords       | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| webcallback         | 17.0.4    | Enabled                           | Commercial  | Sangoma   |
| webrtc              | 17.0.2.2  | Enabled                           | GPLv3+      | Sangoma   |
+---------------------+-----------+-----------------------------------+-------------+-----------+

**Comment by kapilgupta01** [comment]
`| contactmanager | | Not Installed (Locally available) | GPLv3+ | Sangoma |
`

Please install this module by executing following command - 
`fwconsole ma install contactmanager`

**Comment by mandersonbluepride** [comment]
This is what we found in the logs that was missed earlier. Looks like there was an issue with one of the email fields being too long.

From the backup log.

```
backup.log-[2024-08-04 06:03:04] [bf9d0f30-f3d5-4d31-acc0-2398b1e9ca43.INFO]: Processing contactmanager [] []
backup.log-[2024-08-04 06:03:04] [bf9d0f30-f3d5-4d31-acc0-2398b1e9ca43.INFO]: Resetting contactmanager module data [] []
backup.log:[2024-08-04 06:04:56] [bf9d0f30-f3d5-4d31-acc0-2398b1e9ca43.ERROR]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'email' at row 1 on line 2750 of file /var/www/html/admin/modules/contactmanager/Contactmanager.class.php [] []
backup.log-[2024-08-04 06:04:56] [bf9d0f30-f3d5-4d31-acc0-2398b1e9ca43.INFO]: #0 /var/www/html/admin/modules/contactmanager/Contactmanager.class.php(2750): PDOStatement->execute() #1 /var/www/html/admin/modules/contactmanager/Contactmanager.class.php(2083): FreePBX\modules\Contactmanager->addEmailsByEntryID() #2 /var/www/html/admin/modules/contactmanager/Contactmanager.class.php(1991): FreePBX\modules\Contactmanager->addEntryByGroupID() #3 /var/www/html/admin/modules/contactmanager/Contactmanager.class.php(1220): FreePBX\modules\Contactmanager->updateUsermanEntryByGroupID() #4 /var/www/html/admin/modules/contactmanager/Contactmanager.class.php(254): FreePBX\modules\Contactmanager->usermanUpdateGroup() #5 /var/www/html/admin/libraries/modulefunctions.class.php(2594): FreePBX\modules\Contactmanager->install() #6 /var/www/html/admin/libraries/modulefunctions.class.php(2067): module_functions->_runscripts() #7 /var/www/html/admin/modules/backup/Handlers/FreePBXModule.php(28): module_functions->install() #8 /var/www/html/admin/modules/backup/Handlers/FreePBXModule.php(23): FreePBX\modules\Backup\Handlers\FreePBXModule->install() #9 /var/www/html/admin/modules/backup/Models/Restore.php(58): FreePBX\modules\Backup\Handlers\FreePBXModule->reset() #10 /var/www/html/admin/modules/backup/Handlers/Restore/Common.php(121): FreePBX\modules\Backup\Models\Restore->reset() #11 /var/www/html/admin/modules/backup/Handlers/Restore/Multiple.php(70): FreePBX\modules\Backup\Handlers\Restore\Common->processModule() #12 /var/www/html/admin/modules/backup/Console/Backup.class.php(371): FreePBX\modules\Backup\Handlers\Restore\Multiple->process() #13 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php(312): FreePBX\Console\Command\Backup->execute() #14 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run() #15 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand() #16 /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun() #17 /var/lib/asterisk/bin/fwconsole(163): Symfony\Component\Console\Application->run() #18 {main} [] []
backup.log-[2024-08-04 06:04:56] [bf9d0f30-f3d5-4d31-acc0-2398b1e9ca43.INFO]: Processing customappsreg [] []
```

From the database,

MariaDB [asterisk]> DESCRIBE userman_users;
+-------------------+--------------+------+-----+---------+----------------+
| Field             | Type         | Null | Key | Default | Extra          |
+-------------------+--------------+------+-----+---------+----------------+
| id                | int(11)      | NO   | PRI | NULL    | auto_increment |
| auth              | varchar(150) | YES  |     | freepbx |                |
| authid            | varchar(750) | YES  |     | NULL    |                |
| username          | varchar(150) | YES  | MUL | NULL    |                |
| description       | varchar(255) | YES  |     | NULL    |                |
| password          | varchar(255) | YES  |     | NULL    |                |
| default_extension | varchar(45)  | NO   |     | none    |                |
| primary_group     | int(11)      | YES  |     | NULL    |                |
| permissions       | longblob     | YES  |     | NULL    |                |
| fname             | varchar(100) | YES  |     | NULL    |                |
| lname             | varchar(100) | YES  |     | NULL    |                |
| displayname       | varchar(200) | YES  |     | NULL    |                |
| title             | varchar(100) | YES  |     | NULL    |                |
| company           | varchar(100) | YES  |     | NULL    |                |
| department        | varchar(100) | YES  |     | NULL    |                |
| language          | varchar(100) | YES  |     | NULL    |                |
| timezone          | varchar(100) | YES  |     | NULL    |                |
| dateformat        | varchar(100) | YES  |     | NULL    |                |
| timeformat        | varchar(100) | YES  |     | NULL    |                |
| datetimeformat    | varchar(100) | YES  |     | NULL    |                |
| email             | longtext     | YES  |     | NULL    |                |
| cell              | varchar(100) | YES  |     | NULL    |                |
| work              | varchar(100) | YES  |     | NULL    |                |
| home              | varchar(100) | YES  |     | NULL    |                |
| fax               | varchar(100) | YES  |     | NULL    |                |
+-------------------+--------------+------+-----+---------+----------------+
25 rows in set (0.001 sec)

MariaDB [asterisk]> DESCRIBE contactmanager_entry_emails;
+---------+--------------+------+-----+---------+----------------+
| Field   | Type         | Null | Key | Default | Extra          |
+---------+--------------+------+-----+---------+----------------+
| id      | int(11)      | NO   | PRI | NULL    | auto_increment |
| entryid | int(11)      | NO   |     | NULL    |                |
| email   | varchar(100) | YES  |     | NULL    |                |
+---------+--------------+------+-----+---------+----------------+
3 rows in set (0.001 sec)

MariaDB [asterisk]>



So, it looks like the username_users table has an unrestricted length, but contactmanager_entry_emails is restricted to 100 characters. One of our users had a group of emails declared for it. To get around this issue, we trimmed the group down to below a length of 100 and re-installed the contact manager module. It successfully installed after that.
