### ISSUE TITLE
[bug]: EndPoint Manager - Poly (Expansion Module) Issue

### ISSUE THREAD

**Issue by mandersonbluepride** [FreePBX/issue-tracker#345]
### FreePBX Version

FreePBX 17

### Issue Description

I was updating configurations for our Polycom VVX 411 phones, however the issue is the phones with an Expansion Module attached, I get an error when "Rebuilding the configuration."  If I take the expansion module off, it loads fine.  

![Screenshot 2024-08-05 at 9 49 45 AM](https://github.com/user-attachments/assets/0e8c53ea-5762-41b5-b973-4e32361ce066)

### Operating Environment

FreePBX: 17.0.19.1
Asterisk: 21.4.1

No repos specified, using: [standard,commercial] from last GUI settings

+---------------------+-----------+-----------------------------------+-------------+-----------+
| Module              | Version   | Status                            | License     | Signature |
+---------------------+-----------+-----------------------------------+-------------+-----------+
| accountcodepreserve | 17.0.0.1  | Enabled                           | GPLv2       | Sangoma   |
| adv_recovery        | 17.0.4    | Enabled                           | Commercial  | Sangoma   |
| allowlist           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| amd                 | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| api                 | 17.0.1.6  | Enabled                           | AGPLv3+     | Sangoma   |
| areminder           | 17.0.3.10 | Enabled                           | Commercial  | Sangoma   |
| arimanager          | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| backup              | 17.0.5.58 | Enabled                           | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| broadcast           | 17.0.1.6  | Enabled                           | Commercial  | Sangoma   |
| builtin             |           | Enabled                           |             | Unsigned  |
| bulkhandler         | 17.0.5    | Enabled                           | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.15 | Enabled                           | GPLv3+      | Sangoma   |
| callaccounting      | 17.0.5    | Enabled                           | Commercial+ | Sangoma   |
| callback            | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| callerid            | 17.0.1    | Enabled                           | Commercial  | Sangoma   |
| callforward         | 17.0.1.6  | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit           | 17.0.1.2  | Enabled                           | Commercial  | Sangoma   |
| callrecording       | 17.0.3.7  | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4  | Enabled                           | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.16 | Enabled                           | GPLv3+      | Sangoma   |
| cdrpro              | 17.0.3.19 | Enabled                           | Commercial  | Sangoma   |
| cel                 | 17.0.2.8  | Enabled                           | GPLv3+      | Sangoma   |
| certman             | 17.0.3.12 | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro      | 17.0.1.7  | Enabled                           | Commercial  | Sangoma   |
| configedit          | 17.0.1.1  | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager      |           | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| core                | 17.0.13   | Enabled                           | GPLv3+      | Sangoma   |
| cos                 | 17.0.1.1  | Enabled                           | Commercial  | Sangoma   |
| customappsreg       | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.3  | Enabled                           | GPLv2+      | Sangoma   |
| dashboard           | 17.0.4.3  | Enabled                           | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| disa                | 17.0.3    | Enabled                           | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3  | Enabled                           | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.1  | Enabled                           | GPLv3+      | Sangoma   |
| endpoint            | 17.0.1.73 | Enabled                           | Commercial  | Sangoma   |
| extensionroutes     | 17.0.1    | Enabled                           | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4  | Enabled                           | GPLv3+      | Sangoma   |
| faxpro              | 17.0.1.18 | Enabled                           | Commercial  | Sangoma   |
| featurecodeadmin    | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.22 | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.9  | Enabled                           | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.26 | Enabled                           | AGPLv3+     | Sangoma   |
| framework           | 17.0.19.1 | Enabled                           | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6  | Enabled                           | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1    | Enabled                           | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1.1  | Enabled                           | GPLv2+      | Sangoma   |
| ivr                 | 17.0.6    | Enabled                           | GPLv3+      | Sangoma   |
| languages           | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3  | Enabled                           | GPLv3+      | Sangoma   |
| manager             | 17.0.6    | Enabled                           | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| music               | 17.0.5    | Enabled                           | GPLv3+      | Sangoma   |
| oembranding         |           | Not Installed (Locally available) | Commercial  | Sangoma   |
| outcnam             | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| paging              | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro           | 17.0.1.6  | Enabled                           | Commercial  | Sangoma   |
| parking             | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| parkpro             | 17.0.1.4  | Enabled                           | Commercial  | Sangoma   |
| pbxmfa              | 17.0.2.1  | Enabled                           | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1    | Enabled                           | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro          | 17.0.2    | Enabled                           | Commercial  | Sangoma   |
| pm2                 | 17.0.3.2  | Enabled                           | AGPLv3+     | Sangoma   |
| pms                 | 17.0.2.15 | Enabled                           | Commercial  | Sangoma   |
| presencestate       | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4  | Enabled                           | GPLv3+      | Sangoma   |
| queues              | 17.0.1.10 | Enabled                           | GPLv2+      | Sangoma   |
| queuestats          | 17.0.1.7  | Enabled                           | Commercial  | Sangoma   |
| qxact_reports       | 17.0.3    | Enabled                           | Commercial  | Sangoma   |
| recording_report    | 17.0.3.8  | Enabled                           | Commercial  | Sangoma   |
| recordings          | 17.0.2.2  | Enabled                           | GPLv3+      | Sangoma   |
| restapps            | 17.0.1.20 | Enabled                           | Commercial  | Sangoma   |
| ringgroups          | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect      | 17.0.1.35 | Enabled                           | Commercial  | Sangoma   |
| sangomacrm          | 17.0.1.16 | Enabled                           | Commercial  | Sangoma   |
| sangomartapi        | 17.0.1.28 | Enabled                           | Commercial  | Sangoma   |
| setcid              | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.8  | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation          | 17.0.3.3  | Enabled                           | Commercial  | Sangoma   |
| sms                 | 17.0.1.15 | Enabled                           | Commercial  | Sangoma   |
| smsplus             | 17.0.3    | Enabled                           | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1  | Enabled                           | GPLv3+      | Sangoma   |
| superfecta          | 17.0.2    | Enabled                           | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.92 | Enabled                           | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.18 | Enabled                           | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1    | Enabled                           | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.20 | Enabled                           | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.26 | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| vmnotify            | 17.0.1.7  | Enabled                           | Commercial  | Sangoma   |
| voicemail           | 17.0.5.22 | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report    | 17.0.1.1  | Enabled                           | Commercial  | Sangoma   |
| voipinnovations     | 17.0.1.4  | Enabled                           | Commercial  | Sangoma   |
| vqplus              | 17.0.1.16 | Enabled                           | Commercial  | Sangoma   |
| weakpasswords       | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| webcallback         | 17.0.4    | Enabled                           | Commercial  | Sangoma   |
| webrtc              | 17.0.2.2  | Enabled                           | GPLv3+      | Sangoma   |
+---------------------+-----------+-----------------------------------+-------------+-----------+

**Comment by kapilgupta01** [comment]
Hi @mandersonbluepride can you please share the full backtrace?

**Comment by mandersonbluepride** [comment]
Hi @kguptasangoma here is what I am thinking you are asking: 
![Screenshot 2024-08-08 at 8 57 22 PM](https://github.com/user-attachments/assets/b34a1acb-20a6-4803-8eef-9f8b74133b11)
![Screenshot 2024-08-08 at 8 57 40 PM](https://github.com/user-attachments/assets/28297490-e7d8-41c0-b677-663ef96e307a)
![Screenshot 2024-08-08 at 8 57 54 PM](https://github.com/user-attachments/assets/ae248bef-4fad-44e1-a64f-86eef8fd7c23)



If I need to give you something different please let me know!

**Comment by jissphilip** [comment]
@mandersonbluepride 
endpoint-17.0.1.76
Please update your system with given version and try

**Comment by mandersonbluepride** [comment]
After updating to 17.0.1.76 on EndPoint Manager I am still getting the same error when I go to rebuild the configuration for a phone. 
![Screenshot 2024-08-10 at 12 50 15 PM](https://github.com/user-attachments/assets/220bca50-656b-4252-a121-646e23a6ad93)


Here is the page I get after reloading:
![Screenshot 2024-08-10 at 12 57 03 PM](https://github.com/user-attachments/assets/e020014d-4b63-4f5f-a4ce-af06a79b1ad6)
![Screenshot 2024-08-10 at 12 57 11 PM](https://github.com/user-attachments/assets/0ad5def0-5fa2-4fe4-89ad-7e8195dcdead)
