### ISSUE TITLE
[bug]: Freepbx 17 cannot be configured

### ISSUE THREAD

**Issue by mischa365** [FreePBX/issue-tracker#349]
### FreePBX Version

FreePBX 16

### Issue Description

.

### Operating Environment

![2024-08-06_15-58-00](https://github.com/user-attachments/assets/0d0ebb30-a2ca-4dc3-85c2-cded6dde63cb)

### Relevant log output

```shell
It gives an error that there is no such file
```

**Comment by kapilgupta01** [comment]
hi @mischa365 check what file you have in "/tmp". looks like due to language you have got different file name.

**Comment by kapilgupta01** [comment]
Hi, 

This appears to be a support issue. 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta
