### ISSUE TITLE
[bug]: .htaccess files are disabled on this webserver. Please enable them

### ISSUE THREAD

**Issue by Matthew-Rauch** [FreePBX/issue-tracker#35]
### FreePBX Version

FreePBX 17

### Issue Description

After fresh install of Debain 12 and then install from the script this error is all over the admin dashboard.
.htaccess files are disabled on this webserver. Please enable them

Was able to fix by adding the below code to the /etc/apache2/sites-enabled/000-default.conf
<Directory /var/www/html>
  AllowOverride All
</Directory>

### Operating Environment

Debian 12.5.0
FreePBX 17.0.15.5
Asterisk 20

**Comment by msanthosh18** [comment]
Hi @Matthew-Rauch 
This has been fixed with latest ffmpeg package, just remove warning on dashboard and check once.
With fresh new install it wont appear.

If you see again with fresh new install then please re -open the jira.

Thanks.
