### ISSUE TITLE
[bug]:   Open Source FreePBX-17 UCP Module V 17.0.4.20 not working

### ISSUE THREAD

**Issue by kennesaw10** [FreePBX/issue-tracker#358]
### FreePBX Version

FreePBX 17

### Issue Description

Unable to access UCP on FreePBX-17 open source install.  Error message says check console log but there is no error logged by the attempted access to the UCP module login.  Attempt was made using Chrome, Firefox and Safari.

![image](https://github.com/user-attachments/assets/e2db74db-9183-4e52-ad7e-f44d96b2ac8f)

### Operating Environment

Debian 12, php 8.2, FreePBX-17, Asterisk 21.4.1.  Rest of system operating normally without incident.
H

### Relevant log output

```shell
Here is log output in the Apache2 access.log:

104.219.80.27 - - [08/Aug/2024:15:48:03 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:06 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:09 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:13 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:17 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:21 -0400] "POST /admin/ajax.php HTTP/1.1" 200 861 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:25 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:29 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:32 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:34 -0400] "GET /ucp/ HTTP/1.1" 200 4354 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:35 -0400] "GET /ucp/?load_version=17.0.17.1 HTTP/1.1" 200 4352 "http://[redacted]/ucp/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:36 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:40 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:43 -0400] "POST /ucp/ajax.php?module=userman&command=checkPasswordReminder HTTP/1.1" 200 728 "http://[redacted]/ucp/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:43 -0400] "POST /ucp/ajax.php HTTP/1.1" 403 722 "http://[redacted]/ucp/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:44 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:48 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
104.219.80.27 - - [08/Aug/2024:15:48:52 -0400] "POST /admin/ajax.php HTTP/1.1" 200 860 "http://[redacted]/admin/config.php?display=logfiles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
```

**Comment by kennesaw10** [comment]
Data was imported from FreePBX-16 backup from system with Asterisk 20.   If I try UCP on a fresh install and add an extension with UCP access, it works.  Something seems to be related to importing the backup.

**Comment by msanthosh18** [comment]
Hi @kennesaw10 ,
Can you check pm2 service for ucp is running, you can use below command to check

  fwconsole pm2 --list | grep ucp
  
  If its shows running, then pls share the browser console logs when you try to login ucp.

**Comment by kennesaw10** [comment]
$ fwconsole pm2 --list
+---------------------------+-------+--------+----------+------------+-----+---------+
| Process Name              | PID   | Status | Restarts | Uptime     | CPU | Mem     |
+---------------------------+-------+--------+----------+------------+-----+---------+
| core-calltransfer-monitor | 55003 | online | 0        | 36 seconds | 0%  | 44.54MB |
| ucp                       | 55550 | online | 16       | 26 seconds | 0%  | 50.71MB |
+---------------------------+-------+--------+----------+------------+-----+---------+

LOG:
` jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:15 JQMIGRATE: Migrate is installed with logging active, version 3.4.0
jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17 JQMIGRATE: jQuery.fn.unbind() is deprecated
migrateWarn @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17Understand this warning
jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17 console.trace
migrateWarn @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17
jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17 JQMIGRATE: jQuery.fn.bind() is deprecated
migrateWarn @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17Understand this warning
jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17 console.trace
migrateWarn @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17
jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17 JQMIGRATE: jQuery.fn.click() event shorthand is deprecated
migrateWarn @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17Understand this warning
jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17 console.trace
migrateWarn @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17
ucp/:1 Unchecked runtime.lastError: The message port closed before a response was received.Understand this error
jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17 JQMIGRATE: jQuery.isFunction() is deprecated
migrateWarn @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17
obj.<computed> @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:19
q.fn.formToArray @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:538
q.fn.formSerialize @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:538
normalLogin @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:2088
handleMFAFunc @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:2087
(anonymous) @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:2086
await in (anonymous)
dispatch @ jquery-3.6.0.min.js?load_version=v17.0.4.20:2
v.handle @ jquery-3.6.0.min.js?load_version=v17.0.4.20:2Understand this warning
jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17 console.trace
migrateWarn @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:17
obj.<computed> @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:19
q.fn.formToArray @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:538
q.fn.formSerialize @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:538
normalLogin @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:2088
handleMFAFunc @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:2087
(anonymous) @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:2086
await in (anonymous)
dispatch @ jquery-3.6.0.min.js?load_version=v17.0.4.20:2
v.handle @ jquery-3.6.0.min.js?load_version=v17.0.4.20:2
jquery-3.6.0.min.js?load_version=v17.0.4.20:2 
        
        
       POST http://[domain redacted]/ucp/ajax.php 403 (Forbidden)
send @ jquery-3.6.0.min.js?load_version=v17.0.4.20:2
ajax @ jquery-3.6.0.min.js?load_version=v17.0.4.20:2
(anonymous) @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:32
obj.<computed> @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:20
S.<computed> @ jquery-3.6.0.min.js?load_version=v17.0.4.20:2
normalLogin @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:2088
handleMFAFunc @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:2087
(anonymous) @ jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:2086
await in (anonymous)
dispatch @ jquery-3.6.0.min.js?load_version=v17.0.4.20:2
v.handle @ jquery-3.6.0.min.js?load_version=v17.0.4.20:2Understand this error
jsphpg_b010f040d71d00083c04dbcd3450bd73.js?load_version=v17.0.4.20:2078 Forbidden: ajaxRequest declined
`

**Comment by kennesaw10** [comment]
Additional notes:  If I do a clean install and use bulk handler to import extensions, UCP works.  There is something in the backup from FreePBX-16 which is not working correctly with FreePBX-17.

**Comment by msanthosh18** [comment]
Can you  share ucp logs 
/var/log/asterisk/ucp_err.log

**Comment by kennesaw10** [comment]
/var/log/asterisk/ucp_err.log shows these lines over and over:

2024-08-09 06:13 -04:00: Error: error:0A00018F:SSL routines::ee key too small
2024-08-09 06:13 -04:00:     at node:internal/tls/secure-context:70:13
2024-08-09 06:13 -04:00:     at Array.forEach (<anonymous>)
2024-08-09 06:13 -04:00:     at setCerts (node:internal/tls/secure-context:68:3)
2024-08-09 06:13 -04:00:     at configSecureContext (node:internal/tls/secure-context:157:5)
2024-08-09 06:13 -04:00:     at Object.createSecureContext (node:_tls_common:117:3)
2024-08-09 06:13 -04:00:     at Server.setSecureContext (node:_tls_wrap:1471:27)
2024-08-09 06:13 -04:00:     at Server (node:_tls_wrap:1335:8)
2024-08-09 06:13 -04:00:     at new Server (node:https:76:3)
2024-08-09 06:13 -04:00:     at Object.createServer (node:https:120:10)
2024-08-09 06:13 -04:00:     at Server (/var/www/html/admin/modules/ucp/node/lib/server.js:106:19) {
2024-08-09 06:13 -04:00:   library: 'SSL routines',
2024-08-09 06:13 -04:00:   reason: 'ee key too small',
2024-08-09 06:13 -04:00:   code: 'ERR_SSL_EE_KEY_TOO_SMALL'
2024-08-09 06:13 -04:00: }
2024-08-09 06:13 -04:00: Error: error:0A00018F:SSL routines::ee key too small
2024-08-09 06:13 -04:00:     at node:internal/tls/secure-context:70:13
2024-08-09 06:13 -04:00:     at Array.forEach (<anonymous>)
2024-08-09 06:13 -04:00:     at setCerts (node:internal/tls/secure-context:68:3)
2024-08-09 06:13 -04:00:     at configSecureContext (node:internal/tls/secure-context:157:5)
2024-08-09 06:13 -04:00:     at Object.createSecureContext (node:_tls_common:117:3)
2024-08-09 06:13 -04:00:     at Server.setSecureContext (node:_tls_wrap:1471:27)
2024-08-09 06:13 -04:00:     at Server (node:_tls_wrap:1335:8)
2024-08-09 06:13 -04:00:     at new Server (node:https:76:3)
2024-08-09 06:13 -04:00:     at Object.createServer (node:https:120:10)
2024-08-09 06:13 -04:00:     at Server (/var/www/html/admin/modules/ucp/node/lib/server.js:106:19) {
2024-08-09 06:13 -04:00:   library: 'SSL routines',
2024-08-09 06:13 -04:00:   reason: 'ee key too small',
2024-08-09 06:13 -04:00:   code: 'ERR_SSL_EE_KEY_TOO_SMALL'
2024-08-09 06:13 -04:00: }
~

**Comment by msanthosh18** [comment]
can you regenerate the cert and give a try after restarting the ucp pm2 service  
"fwconsole pm2  --restart ucp"

**Comment by kapilgupta01** [comment]
hi @kennesaw10 any update here? thanks

**Comment by kennesaw10** [comment]
Have not had a chance yet.  I am away for the week.

⁣Get BlueMail for Android ​

**Comment by n9yty** [comment]
@kguptasangoma This may be out of place, but I reported this originally where @kennesaw10 got involved, and I was seeing this problem with running without https/TLS/SSL/etc so I don't think that is the cause of the problem. The error I saw in the browser was a 403 Forbidden when it tried to POST to the ajax endpoint, and it was a cross-site scripting problem even though all the domains I saw reported were the same (or a subdomain).

**Comment by kennesaw10** [comment]
What is the outcome?  I did generate a new certificate and it did not fix the problem.  Was a solution determined or is there another issue being worked related to this?

**Comment by kapilgupta01** [comment]
Hi @kennesaw10 We are not able to reproduce this issue so closed as non reproducible.

If you can reproduce the issue and share the steps for us to reproduce then we can dig further. 

Or if you can share the access of your system (DM me to kgupta@sangoma.com) where issue is happening that also would be helpful.

Thanks
Kapil

**Comment by kennesaw10** [comment]
The issue is easily reproduced.  Here are the steps used:

 

1.	Install FreePBX-17-latest and Asterisk-21-latest on new system.
2.	Determine the systems is working with newly added extensions.
3.	Access UCP module on FreePBX-17 and log in.  UCP will work.
4.	Take FreePBX-16 backup of production system running current FreePBX-16 modules and extensions.
5.	FreePBX-16 production system and extensions work with UCP on the FreePBX-16 system.
6.	Restore FreePBX-16 backup to the FreePBX-17 system.
7.	UCP will no longer work on the FreePBX-17 system.

 

I can let you have access to the FreePBX-16 and FreePBX-17 systems if you like or I can send you the FreePBX-16 backup if you would like to restore it to your test system.  Advise how you would like to handle.  Firewalls are locked down to known IP addresses so I’d need to know IP address you would access from.

**Comment by kennesaw10** [comment]
Please reopen this ticket.  Additional information was sent to Kapil via email at his request.

**Comment by jjessel5** [comment]
In case this helps. I had the same issue with the UCP daemon node not running on the Dashboard and what solved the issue for me was to create a new certificate in FreePBX. Certificate Management > New Certificate > Generate Signed Certificate. I left all as default and created it. Then set it as default. Then immediately upon visiting the Dashboard afterwards the UCP daemon was fine.

Before the above was done, I tried reinstalling UCP and even pm2 without any success. This is my second PBX transfer from 16 to 17. The first PBX transfer didn't have this issue.

**Comment by kapilgupta01** [comment]
Hi @kennesaw10 your reported issue got fixed which was mainly due to using another brand where default values were not set properly. this is reason for Freepbx backup & restore we were not able to reproduce.

Please update to the latest ucp module in 17 and try again.

thanks @jjessel5 for your suggestion, yes 17 we need to regenerate the cert to ensure https/ucp works fine.

**Comment by kennesaw10** [comment]
I have Backup/Restore module version 17.0.5.60.  I just tried a restore and UCP still does not work.  What version of backup are you advising to use?

**Comment by kapilgupta01** [comment]
hi @kennesaw10 which version of ucp module you are using in 17?

**Comment by kennesaw10** [comment]
17.0 4.20

⁣Get BlueMail for Android ​

**Comment by n9yty** [comment]
Any update?

**Comment by kapilgupta01** [comment]
reported original issue got fixed and no known issue open as such @n9yty 

Can you please update all modules , refresh browser cache and try again ? and if not working then please make a small video and show us the steps to reproduce the issue inhouse.

thanks

**Comment by kennesaw10** [comment]
Kapil,

 

Same as I originally reported:

 

1.	Install a clean Asterisk21 on Debian 12
2.	Install a clean FreePBX-17 (Latest not Edge) Open Source ONLY
3.	Insure you have a working clean system
4.	For test purposes, install an extension
5.	Add User Management details for extension
6.	Apply Changes
7.	Open UCP
8.	Enter extension and password you just set up ==> UCP will work
9.	Now restore the backup from a different FrePBX-16 system which has all module updates applied
10.	Open UCP
11.	Enter extension/password for one of the extensions in the backup ==> UCP does not work, just returns to login screen.

 

What will work is to bulk export extensions from old system and import them into the new clean system.  Then UCP works for the imported extensions on a clean system.  It does not work if you have already restored a backup from the old system and bulk import the old extensions.  Likewise if you restore the backup from the old system and add a new extension, UCP does not work.  Something in the backup that is being restored from the old system interferes with UCP on the new system.  A video of the procedure would shed no light on the issue.

 

I have done this today with the results above for what does or does not work.

 

If you would like to test with my FreePBX backup, I did email you a copy previously and can send to someone again.

 

If you follow the steps above it definitely shows UCP not working with the old data.

**Comment by kennesaw10** [comment]
One more piece of information, on the old FreePBX-16 system, the UCP module has been held at 16.0.37 because updating to new versions on IncrediblePBX (formerly PBXinaFlash) prevented UCP from working.  Apparently whatever changed in the module between 16.0.37 and later revisions break UCP for our IncrediblePBX systems.  I’m suspect that is relevant to this issue in FreePBX-17.

**Comment by msanthosh18** [comment]
Hi @kennesaw10 ,
We were having an issue with UCP - 17.0.4.20 with your shared backup file for ucp login, and got fixed with latest version ucp-17.0.4.23, can you give a try by running below command and reload, once done, clear the browser cache then try to login


fwconsole ma downloadinstall ucp --tag 17.0.4.23 -f

**Comment by kennesaw10** [comment]
At first, this did not work for me but I cleared my browser cache, closed the browser and reopened it and this has fixed my UCP issue.  When will this version of the ucp module be released for the freepbx-17 current track?

Also, thank you for your time and attention on clear this up.  I was not looking forward to having to bulk-import everything to a new system and then manually rebuild the missing pieces.

**Comment by n9yty** [comment]
I assume this means that working on a system that had a prior restore attempt won't work, it will require a fresh start? Just so I know and don't waste time wondering why it isn't working. :)

**Comment by kapilgupta01** [comment]
hi @n9yty may be you can try to create fresh 17 system, create user / extension and try to login to ucp to confirm all good.

**Comment by kapilgupta01** [comment]
Hi @kennesaw10  what if you take backup of Freepbx system and restore to 17 ? 

Issue which we have fixed last time shared backup file was due to using different branding then Freepbx/PBXact so wondering if we have any other such hidden stuff so would like you to confirm backup and restore on Freepbx 16 to Freepbx 17 first.

If freepbx also, you are facing same issue then we may need backup file again to reproduce the issue in-house.

**Comment by kennesaw10** [comment]
I have just taken a FreePBX backup of my production FreePBX-16 system and restored it over my test FreePBX-17 system and it worked correctly.  Everything restored correctly.  Also, the UCP works.  I think this issue is resolved.
