### ISSUE TITLE
[bug]: Restore from FreePBX fails if Framework module is included

### ISSUE THREAD

**Issue by thadrumr** [FreePBX/issue-tracker#36]
### FreePBX Version

FreePBX 17

### Issue Description

If I try and restore a backup to a new FreePBX 17 that was installed with the new script it will cause issues with the Framework module.  The following error shows up about the framework module.  Module: "FreePBX Framework", File: "/var/lib/asterisk/agi-bin/phpagi-asmanager.php missing".  Here is a link to a post with the fix I used.  https://community.freepbx.org/t/migrate-from-centos-freepbx-15-to-asterisk-16-on-debian-11/80241/10

### Operating Environment

  The framework version I have is 17.0.15.5 and its running underneath Debian 12.5

**Comment by kapilgupta01** [comment]
hi @thadrumr is this still an issue with the latest modules? thanks

**Comment by thadrumr** [comment]
I couldn’t tell you honestly as my system is up and running on version 17 now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kapilgupta01** [comment]
okay great so I am closing this jira, feel free to re-open if you find the issue again.

Also, how's 17 looks like to you @thadrumr ? any feedback ?
