### ISSUE TITLE
[bug]: Time-Condition needs "matched" and "non-matched" selection

### ISSUE THREAD

**Issue by rehoehle** [FreePBX/issue-tracker#362]
### FreePBX Version

FreePBX 17

### Issue Description

When you try to add a time condition you have to add both conditions. I think thats not correct.

![2024-08-12_14-59](https://github.com/user-attachments/assets/d97ae4b2-c238-43f8-8492-d88cad4e23b4)

Or what is the concept? Ether it is in the range or not. And the next thing is that i think the labels are not the best for what the function should do. 

I have defined a time group and want to play a record if it's not in the time range of the defined time.

### Operating Environment

Debian 12

**Comment by lgaetz** [comment]
This is correct, as an admin you must set both the matching and not matching destinations. You must explicitly tell freepbx what to do with calls in both cases, when it matches and when it doesn't match the time group.

See the user guide and example usage in the wiki
https://sangomakb.atlassian.net/wiki/spaces/PG/pages/24248517/Time+Conditions+Module

**Comment by rehoehle** [comment]
@lgaetz ok but that doesn't make any sense. For example i want that after 6 o'clock when the company is closed there should be an audio that says you are out of the business time. So That has only one Match "after the time period". So otherwise the condition shouldn't do anything. 

So how should i release that? All manual that if have found says that i have to specify one of them. 

So i see in the example that i have then set a ring group for matching but that doesn't make sense because i have a lot of ring groups with different external numbers. When i do it in that way then i hear the audio but for all and it goes only to one ring group because then an condition is missing for that should take place. 

So how should i solve that?

**Comment by lgaetz** [comment]
It's inappropriate to use the issue tracker for general questions and assistance. If you need help, raise a question in the community forum
https://community.freepbx.org/
