### ISSUE TITLE
[bug]: Submenu isn't opening correctly (closes when you go down)

### ISSUE THREAD

**Issue by rehoehle** [FreePBX/issue-tracker#363]
### FreePBX Version

FreePBX 17

### Issue Description

It's most times not possible to go the sub menu. The menu is opening when you go down it's closing before you can click something. You have first click on the main point to hold it open. It's a bit annoying. 

### Operating Environment

MacOS / Browser Brave

**Comment by lgaetz** [comment]
I have noticed this as well, and have been meaning to open a ticket on this. It's particularly easy to repro if you
- increase the zoom on the browser
- hover over the menu button so the menu appears
- slowly move the mouse pointer down, when the pointer hits the space between the button and the menu, the menu closes

![image](https://github.com/user-attachments/assets/2f4aa98d-4176-43b3-b83a-03fe54e39945)

**Comment by reraikes** [comment]
I also experience this annoyance.

**Comment by rehoehle** [comment]
I think the gab is a bit too big. I think it's a simple fix. The other things run good.

**Comment by kapilgupta01** [comment]
framework v17.0.19.2

**Comment by rehoehle** [comment]
@kguptasangoma one question. Is the UI updated over the package manager or the modules?

**Comment by kapilgupta01** [comment]
hi @rehoehle please update the framework module.

**Comment by rehoehle** [comment]
@kguptasangoma ok thanks. When is the update available? I have 17.0.19.1 but there is no newer version.

**Comment by reraikes** [comment]
>When is the update available? I have 17.0.19.1 but there is no newer version.

@rehoehle,

Do you have Edge mode enabled in Advanced Settings?

**Comment by rehoehle** [comment]
@reraikes no it's disabled. But the i will wait until it's stable :) thanks.

**Comment by kapilgupta01** [comment]
hi @rehoehle done, i just pushed configedit to stable.
