### ISSUE TITLE
[bug]: Sangoma Property Management

### ISSUE THREAD

**Issue by AntonioTejeda86** [FreePBX/issue-tracker#368]
### FreePBX Version

FreePBX 17

### Issue Description

I’m using FreePBX 17 on debian 12, I want to test free version of Property Management before buying the commercial module for some clients, but something is going wrong.
I’m following the instructions on: https://sangomakb.atlassian.net/wiki/spaces/PG/pages/35782916/Property+Manager+Getting+Started
So I created the four groups inside de Property Management directory, and added a user to each group, except for the customer group, but then when I go to “General → Privileges” this error page appears:
![SPM](https://github.com/user-attachments/assets/59ea9795-389d-4b21-870f-7b07b2631f97)

Whoops \ Exception \ ErrorException (E_WARNING)

Undefined variable $grp_rec

So I want to know how to fix this.

Regards

### Operating Environment

I have FreePBX 17 working on debian 12.6

**Comment by kapilgupta01** [comment]
Hi @3p3r1a please give a try with below pms module.

`fwconsole ma downloadinstall pms --tag=17.0.2.16`

Thank you for using FreePBX 17
Kapil

**Comment by AntonioTejeda86** [comment]
I used now that verison with:
fwconsole ma downloadinstall pms --tag=17.0.2.16

but the same error is appearing

**Comment by kapilgupta01** [comment]
Hi @3p3r1a latest pms module is 17.0.2.18 so please try with this one.

Let us know if still you are having the problem with the latest pms module ?
thanks
