### ISSUE TITLE
[bug]: Module Configuration Editor - Cannot select text

### ISSUE THREAD

**Issue by bosidaa** [FreePBX/issue-tracker#369]
### FreePBX Version

FreePBX 17

### Issue Description

In Configuration File Editor (Config Edit), text cannot be selected.

It's possible to click on a line, backspace, delete, insert, but not select. Nor with a mouse, nor with keyboard (shift+arrow/end etc.).

[Forum reference](https://community.freepbx.org/t/fpb17-configuration-file-editor-cant-select/99726)

### Operating Environment

FreePBX 17

**Comment by kapilgupta01** [comment]
configedit v17.0.1.2

**Comment by inferno-cc** [comment]
@MPreeti-Sangoma released a bugfix, but after some tests it does not look like as a solution for this bug :(

the select actually works functionally, but there is no visual confirmation of a selection

**Comment by kapilgupta01** [comment]
hi @inferno-cc can you please make small video to show the problem so we can try to take a look? thanks

**Comment by inferno-cc** [comment]
@kguptasangoma hereby a video demonstrating selecting the text and copying it with ctr+c and then pasting with ctr+v :)

https://github.com/user-attachments/assets/9a97959c-4cb5-4596-ae66-b9f6706b2123

**Comment by zsirmo** [comment]
Selection not visible in browsers (FF 129.0, 130.0b7, GC 127.0.6533.122)

**Comment by inferno-cc** [comment]
> @kguptasangoma hereby a video demonstrating selecting the text and copying it with ctr+c and then pasting with ctr+v :)
> 
>  2024-08-22_16-35-24.mp4

@kguptasangoma have you had any chance to check this? (:

**Comment by kapilgupta01** [comment]
Hi @inferno-cc yes we are looking into this one. thanks

**Comment by jissphilip** [comment]
configedit version 17.0.1.3

**Comment by zsirmo** [comment]
https://github.com/user-attachments/assets/b53697e4-efa2-43e0-bd0d-0304a5447ba4

Hello, check video, selected text not visible(all grey)
Checked in FF(beta channel) and official Google Chrome

**Comment by jissphilip** [comment]
Hi @zsirmo 
Please test with version  17.0.1.4

**Comment by zsirmo** [comment]
> Hi @zsirmo Please test with version 17.0.1.4

working, perfect!

**Comment by kapilgupta01** [comment]
thank you for quick testing @zsirmo
