### ISSUE TITLE
[bug]: GQL addBackup allows to add the same name.

### ISSUE THREAD

**Issue by danardf** [FreePBX/issue-tracker#370]
### FreePBX Version

FreePBX 16

### Issue Description

When we try to add a backup job, there is no logic to check if the name is already in use.
I will raise a PR to fix it. 

### Operating Environment

| backup            | 16.0.70.1 
| backup            | 17.0.5.58 

### Relevant log output

```shell
none
```

**Comment by danardf** [comment]
@kguptasangoma PR raised in https://github.com/FreePBX/backup/pull/65

**Comment by danardf** [comment]
@kguptasangoma here ^^

**Comment by kapilgupta01** [comment]
backup 16.0.70.2 and 17.0.5.60
