### ISSUE TITLE
[bug]: Creditcard payment for Sysadmin Pro not working

### ISSUE THREAD

**Issue by rehoehle** [FreePBX/issue-tracker#371]
### FreePBX Version

FreePBX 17

### Issue Description

I try now since some days to buy a new license for the new system but it's not working. My creditcard is working because i bought something on another website.

![2024-08-14_19-25](https://github.com/user-attachments/assets/23eae629-d4f4-423b-94f3-025f546c63e1)

There is no real error message. Do you know something about that?

With FreePBX 16 it was working. For this i bought the pro version without any problems.

### Operating Environment

MacOS / Brave

**Comment by kapilgupta01** [comment]
can you please purchase via portal.sangoma.com @rehoehle

**Comment by rehoehle** [comment]
@kguptasangoma yes ok but you should perhaps fix the problem and give a better error message and don't close the ticket. Or redirect directly to the portal when there is a bitter buying solution.
