### ISSUE TITLE
[bug]: FreePBX 17 - Parking Lot music on hold field fails to update in the GUI, setting however does work

### ISSUE THREAD

**Issue by chewy-chewbacca** [FreePBX/issue-tracker#375]
### FreePBX Version

FreePBX 17

### Issue Description

As stated in the title, the parking lot on FreePBX 17 will show a random music on hold selection in the "Parked Music Class". If you change it, the change will take effect, however the field in the GUI still shows the original "random" entry.  Tested against a few FreePBX 17 PBXes.

To reproduce:
I have two music on hold groups: default and Opus

The parking lot shows "default"
I set to "Opus"
Save and Apply
Parking lot still shows "default" even though "Opus" was selected.

Again, the music selection change DOES work, it's just the GUI field that doesn't.

### Operating Environment

FreePBX 17

**Comment by chewy-chewbacca** [comment]
Just to add: These are all restored configurations from FreePBX 16

**Comment by jissphilip** [comment]
parking version 17.0.2.5
