### ISSUE TITLE
[bug]: Version 17 - Editing Extensions throws error.

### ISSUE THREAD

**Issue by myr1de** [FreePBX/issue-tracker#376]
### FreePBX Version

FreePBX 17

### Issue Description

![Screenshot at Aug 14 20-04-07](https://github.com/user-attachments/assets/58adee0b-7206-4ef0-9d61-8e08ad288b5b)

When editing extensions I get the following on the screen. I can go back and the same things happen. 

### Operating Environment

Debian 12

**Comment by chewy-chewbacca** [comment]
Looks like it's coming from endpoint manager. 

Maybe try
fwconsole ma downloadinstall endpoint --edge

**Comment by myr1de** [comment]
tried that and still same issue. 

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/398512f7-28fc-49e8-a053-4554f7014124">

**Comment by kapilgupta01** [comment]
Hi @myr1de  can you please see what is the output of below command in your system? Looks like some values are not right.

If you are not using endpoint manager then may be uninstall it. 

`SELECT * FROM endpoint_templates`

**Comment by myr1de** [comment]
> Hi @myr1de can you please see what is the output of below command in your system? Looks like some values are not right.
> 
> If you are not using endpoint manager then may be uninstall it.
> 
> `SELECT * FROM endpoint_templates


So from the sql table?

**Comment by kapilgupta01** [comment]
yes, execute below from your freepbx linux cli. 

To enter to DB -> 
`fwconsole m`   

Execute below query - 
`SELECT * FROM endpoint_templates`

**Comment by myr1de** [comment]
> yes, execute below from your freepbx linux cli.
> 
> To enter to DB -> `fwconsole m`
> 
> Execute below query - `SELECT * FROM endpoint_templates`

Ok it does return table data that detail out the extensions.  Are you wanting the return of that?

**Comment by jissphilip** [comment]
endpoint version 17.0.1.80
