### ISSUE TITLE
[bug]:Could not resolve host: mirror.freepbx.org; Unknown error

### ISSUE THREAD

**Issue by Nzisenns** [FreePBX/issue-tracker#378]
### FreePBX Version

FreePBX 16

### Issue Description

Tried to set up extensions. Was navigating to SIPStation.

### Operating Environment

<head></head><div class="data-table-container" id="data-tables" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; color: rgb(19, 19, 19); font-family: &quot;Helvetica Neue&quot;, helvetica, arial, sans-serif; font-size: 12px; font-variant-ligatures: normal; orphans: 2; widows: 2; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="data-table" id="sg-get-data" style="width: 904.594px; margin-bottom: 10px;"><label class="empty" style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: inline; padding-bottom: 5px;">GET Data</label><span> </span><span class="empty" style="color: rgba(0, 0, 0, 0.3); font-weight: 300;">empty</span></div><div class="data-table" id="sg-post-data" style="width: 904.594px; margin-bottom: 10px;"><label class="empty" style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: inline; padding-bottom: 5px;">POST Data</label><span> </span><span class="empty" style="color: rgba(0, 0, 0, 0.3); font-weight: 300;">empty</span></div><div class="data-table" id="sg-files" style="width: 904.594px; margin-bottom: 10px;"><label class="empty" style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: inline; padding-bottom: 5px;">Files</label><span> </span><span class="empty" style="color: rgba(0, 0, 0, 0.3); font-weight: 300;">empty</span></div><div class="data-table" id="sg-cookies" style="width: 904.594px; margin-bottom: 10px;"><label style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: block; padding-bottom: 5px;">Cookies</label>
lang | "en_US"
-- | --
searchHide | "1"
PHPSESSID | "deudgg2jrsvgeuej099lskbjqm"

</div><div class="data-table" id="sg-environment-variables" style="width: 904.594px; margin-bottom: 10px;"><label class="empty" style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: inline; padding-bottom: 5px;">Environment Variables</label><span> </span><span class="empty" style="color: rgba(0, 0, 0, 0.3); font-weight: 300;">empty</span></div></div><div class="data-table-container" id="handlers" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; color: rgb(19, 19, 19); font-family: &quot;Helvetica Neue&quot;, helvetica, arial, sans-serif; font-size: 12px; font-variant-ligatures: normal; orphans: 2; widows: 2; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><label style="font-size: 16px; color: rgb(48, 48, 48); font-weight: bold; margin: 10px 0px 5px; display: block; padding-bottom: 5px;">Registered Handlers</label><div class="handler active" style="padding: 4px 0px; font-style: normal; font-variant-caps: normal; font-weight: normal; font-stretch: normal; font-size: 14px; line-height: normal; font-family: Inconsolata, &quot;Fira Mono&quot;, &quot;Source Code Pro&quot;, Monaco, Consolas, &quot;Lucida Console&quot;, monospace; font-size-adjust: none; font-kerning: auto; font-variant-alternates: normal; font-variant-ligatures: normal; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-position: normal; font-variant-emoji: normal; font-feature-settings: normal; font-optical-sizing: auto; font-variation-settings: normal;">0. Whoops\Handler\PrettyPageHandler</div></div>

### Relevant log output

```shell
/var/www/html/admin/modules/soundlang/Soundlang.class.php
        }
        if(!empty($exceptions)) {
            $message = '';
            $code = '';
            foreach($exceptions as $e) {
                if($this->config->get('MODULE_REPO') !== $this->config->get_conf_default_setting('MODULE_REPO')) {
                    $this->config->reset_conf_settings(array('MODULE_REPO'),true);
                    $code = 500;
                    $message = _("The mirror server did not return the correct response and had been previously changed from the default server(s), it has now been reset back to the standard default. Please try again");
                } else {
                    $code = $e->getCode();
                    $msg = $e->getMessage();
                    $message .= !empty($msg) ? $msg : sprintf(_("Error %s returned from remote servers %s"),$code,json_encode($mirrors['mirrors']));
                    $message .= ", ";
                }
 
            }
            $message = rtrim(trim($message),",");
 
            throw new \Exception($message,$code);
        } else {
            throw new \Exception(sprintf(_("Unknown Error. Response was empty from %s"),json_encode($mirrors['mirrors'])),0);
        }
    }
}
 
Arguments
"Could not resolve host: mirror.freepbx.org; Unknown error"
```

**Comment by kapilgupta01** [comment]
If you ping mirror.freepbx.org then does it working fine ? If not then please check your DNS/Networking settings.

`ping mirror.freepbx.org
PING mirror.freepbx.org.cdn.cloudflare.net (172.67.42.223) 56(84) bytes of data.
64 bytes from 172.67.42.223 (172.67.42.223): icmp_seq=1 ttl=55 time=3.36 ms
`

**Comment by Nzisenns** [comment]
Host resolves.

**Comment by kapilgupta01** [comment]
so are you able to reproduce this every single time?

**Comment by kapilgupta01** [comment]
closing as no response, feel free to re-open and share steps to reproduce the issue.

Thank you for using FreePBX
Kapil
