### ISSUE TITLE
[bug]: FTPS Not Working

### ISSUE THREAD

**Issue by FastEddy1114** [FreePBX/issue-tracker#379]
### FreePBX Version

FreePBX 17

### Issue Description

I recently upgraded from FreePBX 16 to 17.  I uploaded my latest backup to FreePBX and restored the backup without issue.  I noticed that my backups to FTP were not showing up on the FTP server.  I monitored the server interface of the FTP server and noticed every time the backup ran it would throw an error on the FTP server stating "503 use AUTH first."  My FTP server is configured to "Require explicit FTP over TLS", and this configuration works fine with my FreePBX 16 server.  When the old server connects to the FTP server there is a log entry of "AUTH TLS" followed by "234 Using authentication type TLS."  The only way I can get the FreePBX 17 server to connect is to reconfigure the FTP server to allow plain FTP.  In Settings > Filestore > FTP the FTP instance on the FreePBX 17 server is set to "Use TLS" > "Yes" just like it is on the FreePBX 16 server.  Something is not right in the implementation here as the toggle for the Use TLS option seems to be ignored and it is stuck on No no matter what.

### Operating Environment

FreePBX 17.0.19.1, Asterisk Version: 21.4.1, Filestore version: 17.0.2.22

### Relevant log output

```shell
When FreePBX 17 tries to connect via FTPS
2024-08-16T16:13:31.331Z << [FTP Session 12 192.168.x.x] 503 Use AUTH first.
2024-08-16T16:13:31.332Z >> [FTP Session 12 192.168.x.x] QUIT
2024-08-16T16:13:31.332Z << [FTP Session 12 192.168.x.x] 221 Goodbye.

When FreePBX 16 tries to connect via FTPS
2024-08-16T19:13:47.756Z >> [FTP Session 38 192.168.x.x] AUTH TLS
2024-08-16T19:13:47.757Z << [FTP Session 38 192.168.x.x] 234 Using authentication type TLS.
```

**Comment by AA7CL** [comment]
I'm glad to see I'm not the only one having this issue. I've opened a bug issue as you did and was told or open a support case with Sangoma. I ran a tcpdump on my system and TLS is not being implemented even thought it is selected in the Filestore  configuration. Sangoma told me to update the modules (mine are already up to date) and they also told be to buy some credits. Hmmmmmm.... buy support credits to fix a bug.... :) Like you, my FreePBX 16 instance works fine.

**Comment by kapilgupta01** [comment]
Hi @FastEddy1114 @AA7CL Can any one of you provide us the access of your FTP server so we can try to connect to reproduce issue in-house? Please send me email with credentials to kgupta@sangoma.com

**Comment by FastEddy1114** [comment]
> Hi @FastEddy1114 @AA7CL Can any one of you provide us the access of your FTP server so we can try to connect to reproduce issue in-house? Please send me email with credentials to [kgupta@sangoma.com](mailto:kgupta@sangoma.com)

Kapil, I have emailed you credentials so you can test connecting to my FTP server so you can troubleshoot this in-house.

**Comment by jissphilip** [comment]
filestore version 17.0.2.24

**Comment by AA7CL** [comment]
I'm running 17.0.2.23. Does 24 fix this issue? If so, how do you get it?

**Comment by jissphilip** [comment]
fwconsole ma update filestore --edge

**Comment by AA7CL** [comment]
That worked and fixed the issue.. Thanks Phillip!


________________________________
