### ISSUE TITLE
Menu, remove the 2px gap in the menu

### ISSUE THREAD

**Issue by dddns** [FreePBX/issue-tracker#382]
### FreePBX Version

FreePBX 16

### Improvement Description

Hi,
freepbx v17 is so great, the installed is the best i've seen, really mean it!

But, i just noticed one strange thing, there's about a 2px gap in the upper menu, and the dropdown when you select a menu, and when moving the mouse, the dropdown disapears when the pointer hits that gap, i have to move the mouse really fast so that it doesn't disapear.
Is it possible to remove this space between? here's an image:

![image](https://github.com/user-attachments/assets/703dedd0-aebe-43a1-b62e-add7aec33378)

Thanks in advanced,

**Comment by lgaetz** [comment]
This has been reported and resolved in issue #363

**Comment by kapilgupta01** [comment]
Please try with below framework release.
`fwconsole ma downloadinstall framework --tag=17.0.19.4`

**Comment by dddns** [comment]
it's perfect! thanks.
