### ISSUE TITLE
[bug]: MongoDB does not install using FreePBX 17 Install script on Debain12 

### ISSUE THREAD

**Issue by drtrioxide** [FreePBX/issue-tracker#385]
### FreePBX Version

FreePBX 17

### Issue Description

Run install script on Proxmox VM running Debain 12 and have the same issue even installing MongoDB as standalone application.

Exits the install MondoDB does not install at all it appears the MongoDB repository has been removed from Debain install.

### Operating Environment

Debain 12 ARM64  - FreePBX 17  

### Relevant log output

```shell
/// Extract from Install log. Where Monogo is installed 
---------------------------------

2024-08-20 01:10:23 - ###############################
2024-08-20 01:10:27 - Setting up MongoDB
2024-08-20 01:10:27 - Installing  mongodb....
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package mongodb-org
2024-08-20 01:10:28 - Exiting script

//From /etc/apt/sources.list.d/archive_uri-http_repo_mongodb_org_apt_debian-bookworm.list
deb [arch=arm64] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main
# deb-src [arch=arm64] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 mainetc/apt/sources.list.d/

// 
Even trying to install mongodb it does not install this breaks the install
```

**Comment by jfinstrom** [comment]
I think the only things that used this may have been xmpp and perhaps zulu. I see nothing in the current code base. I think it is safe to remove this from the install script. This is mentioned in https://github.com/FreePBX/issue-tracker/issues/327

**Comment by kapilgupta01** [comment]
removed mongo-db from the install script.
