### ISSUE TITLE
[bug]: Queue still using Asterisk v20 or lower settings when using Asterisk v21 which breaks functionality of settings.

### ISSUE THREAD

**Issue by blazestudios97** [FreePBX/issue-tracker#386]
### FreePBX Version

FreePBX 17

### Issue Description

When running Asterisk v21 with FreePBX v17, the Queues module has not be properly updated to account for there no longer being a Macro call setting in app_queue as app_macro is removed. When creating Queues in FreePBX v17 the dialplan generated is still using the v20 or lower settings for app_queue. Generated output is

`exten => 1000,n(qcall),Queue(1000,${QOPTIONS},,${QAANNOUNCE},${QMAXWAIT},${QAGI},,${QGOSUB},${QRULE},${QPOSITION})` which means there is an extra setting and what should be a GoSub calls is now processed as a Rule. The proper output for Asterisk v21 should be:

`exten => 1000,n(qcall),Queue(1000,${QOPTIONS},,${QAANNOUNCE},${QMAXWAIT},${QAGI},${QGOSUB},${QRULE},${QPOSITION})`

For easier comparison:
`Queue(1000,${QOPTIONS},,${QAANNOUNCE},${QMAXWAIT},${QAGI},,${QGOSUB},${QRULE},${QPOSITION})` - v20 or lower
`Queue(1000,${QOPTIONS},,${QAANNOUNCE},${QMAXWAIT},${QAGI},${QGOSUB},${QRULE},${QPOSITION})` - v21 or higher

### Operating Environment

Debian 12

**Comment by jissphilip** [comment]
queues version 17.0.1.11
