### ISSUE TITLE
[bug]: FreePBX Dasboard / phpsysinfo error - not loading properly

### ISSUE THREAD

**Issue by miskor-bgd** [FreePBX/issue-tracker#387]
### FreePBX Version

FreePBX 17

### Issue Description

Hello,
Just installed brand new clean FreePBX 17 with Asterisk 21 on RPi 3b (without errors) using RonR script from here:

https://www.dslreports.com/forum/r30661088-PBX-FreePBX-for-the-Raspberry-Pi

Immediately on first FreePBX web interface login I was greeted with dashboard error:

**Cannot assign float to property DiskDevice::$_total of type int
File:/var/www/html/admin/modules/dashboard/classes/phpsysinfo/includes/to/device/class.DiskDevice.inc.php:270**

Dashboard panel System Overview also has error message "**There was an error asking for Overview. Check the error logs for more information.**"

Can we fix this? I remember that Dashboard was loading properly in my older FreePBX installation (like 14 or 15) so it should load on the same hardware with newer FreePBX properly...

Thank you!

### Operating Environment

FreePBX 17.0.19.1
Asterisk 21.4.2
Raspbian GNU/Linux 12 (bookworm)

**Comment by kapilgupta01** [comment]
dashboard v17.0.4.4

**Comment by miskor-bgd** [comment]
Upgraded to v17.0.4.4, rebooted, error is still there:

Cannot assign float to property DiskDevice::$_used of type int
File:/var/www/html/admin/modules/dashboard/classes/phpsysinfo/includes/to/device/class.DiskDevice.inc.php:296

**Comment by miskor-bgd** [comment]
@kguptasangoma can you please reopen this issue, I believe it is not solved with v17.0.4.4... Thanks!

**Comment by jissphilip** [comment]
dashboard version 17.0.4.5
