### ISSUE TITLE
[bug]: http://deb.freepbx.org/freepbx17-prod/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

### ISSUE THREAD

**Issue by jasonblewis** [FreePBX/issue-tracker#39]
### FreePBX Version

FreePBX 17

### Issue Description

after setting up freepbx17 using the installer script, i see this warning when I do an 'apt update':

```
root@freepbx17:/etc/apt# apt update
Hit:1 http://security.debian.org/debian-security bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease                  
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease          
Hit:4 http://deb.debian.org/debian bookworm-backports InRelease        
Ign:5 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 InRelease        
Hit:6 http://deb.freepbx.org/freepbx17-prod bookworm InRelease
Hit:7 https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 Release
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: http://deb.freepbx.org/freepbx17-prod/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
root@freepbx17:/etc/apt# 

```

### Operating Environment

FreePBX 17 Debian installer beta. immediately after finishing install.

**Comment by jasonblewis** [comment]
Consider adding the key to the archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list file. See the signed-by section of:

https://manpages.debian.org/bookworm/apt/sources.list.5.en.html

**Comment by chrsmj** [comment]
Here's the files to copy in to /etc/apt/sources.list.d/ from an [Ansible-ized version of the installer](https://github.com/chrsmj/sng_freepbx_debian_install/tree/ansible-ize):

https://github.com/chrsmj/sng_freepbx_debian_install/blob/ansible-ize/ansible-role/sng_freepbx_debian/files/20-sangoma-fpbx-repository-dev.sources

https://github.com/chrsmj/sng_freepbx_debian_install/blob/ansible-ize/ansible-role/sng_freepbx_debian/files/20-sangoma-fpbx-repository-prod.sources

**Comment by kapilgupta01** [comment]
https://github.com/FreePBX/sng_freepbx_debian_install/issues/7 closed so closing this jira as well, let us know if issue still exist. thanks
