### ISSUE TITLE
[bug]: Call Confirm settings of Follow Me not being restored

### ISSUE THREAD

**Issue by inferno-cc** [FreePBX/issue-tracker#391]
### FreePBX Version

FreePBX 15

### Issue Description

By migrating the old data from FreePBX 15 to FreePBX 17 we are using the Backup / Restore module.
It looks like the Call Confirm setting (if set to Yes) of the FollowMe module is not being correctly restored using the Restore module.

How to reproduce:
- Set Call Confirm to Yes of extension X
- Backup using the Backup-Restore module
- Restore the backup
- Check the extension's FollowMe call confirm value

Tested on the Backup/Restore module v. 15.0.10.68 (will check on the recent versions and confirm later)

### Operating Environment

FreePBX 15.0.17.64
Backup-Restore 15.0.10.68

**Comment by kapilgupta01** [comment]
findmefollow 17.0.4.10
