### ISSUE TITLE
[bug]: Problems with Sangoma Property Management

### ISSUE THREAD

**Issue by AntonioTejeda86** [FreePBX/issue-tracker#392]
### FreePBX Version

FreePBX 17

### Issue Description

I’m using FreePBX 17 on debian 12, I want to test free version of Property Management before buying the commercial module for some clients, but something is going wrong.
I’m following the instructions on: https://sangomakb.atlassian.net/wiki/spaces/PG/pages/35782916/Property+Manager+Getting+Started
So I created the four groups inside de Property Management directory, and added a user to each group, except for the customer group, but then when I go to “General → Privileges” this error page appears:

![image](https://github.com/user-attachments/assets/8bc917ba-7e1a-4b10-aece-563e4d494ece)

Whoops \ Exception \ ErrorException (E_WARNING)

Undefined variable $grp_rec

I posted this once, and I received the response to try to use 

fwconsole ma downloadinstall pms --tag=17.0.2.16

I already used that, it was installed correctly but the same error is appearing

### Operating Environment

debian 12.6

**Comment by kapilgupta01** [comment]
Issue got fixed in below release.

Pms v17.0.2.18

Thank you for using Freepbx 17
Kapil
