### ISSUE TITLE
[bug]: FreePBX 17 Restore Oddities - Call Waiting Disabled and/or Voicemail "Required from Extension" doesn't get set properly on restore

### ISSUE THREAD

**Issue by chewy-chewbacca** [FreePBX/issue-tracker#394]
### FreePBX Version

FreePBX 17
FreePBX 16

### Issue Description

I've verified across multiple installs of FreePBX 17 with 16 restores, the following will randomly happen:

- Call Waiting will be disabled across the board (3 installs)
- Voicemail "Require from Extension" either doesn't restore properly or sets itself improperly. On a few systems this went from don't require from extension to require from extension.  (4 installs). _I found out because clients were calling saying, "what's my voicemail password, this never happened before"_

Minor issues. The call waiting one was a little more worrisome but I fixed it quickly. 

### Operating Environment

Debian 12.6/FreePBX 17
All backed up and restored systems were fully up to date prior to the backup and restore to 17.

**Comment by jissphilip** [comment]
core version 15.0.22.38
core version 16.0.68.29
core version 17.0.15
