### ISSUE TITLE
[bug]: Problem Restore Backup - CDR

### ISSUE THREAD

**Issue by marcelo-merenda** [FreePBX/issue-tracker#395]
### FreePBX Version

FreePBX 17

### Issue Description

After the last update, I can´t restore CDR.
There are an error:
Unable to locate the FreePBX BMO Class 'Removecdrtrigger'A required module might be disabled or uninstalled. Recommended steps (run from the CLI): 1) fwconsole ma install removecdrtrigger 2) fwconsole ma enable removecdrtrigger on line 214 of file /var/www/html/admin/libraries/BMO/Self_Helper.class.php

The table cdr is empty.

Please verifiy.
Marcelo Henrique Merenda

### Operating Environment

Asterisk 21.4.1
+---------------------+-----------+---------------------------------------------+-------------+-----------+
| Module              | Version   | Status                                      | License     | Signature |
+---------------------+-----------+---------------------------------------------+-------------+-----------+
| accountcodepreserve | 17.0.0.1  | Enabled and up to date                      | GPLv2       | Sangoma   |
| adv_recovery        |           | Not Installed (Available online: 17.0.4)    | Commercial  |           |
| allowlist           | 17.0.1.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| amd                 | 17.0.1    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| api                 | 17.0.1.6  | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| areminder           |           | Not Installed (Available online: 17.0.3.10) | Commercial  |           |
| arimanager          | 17.0.1.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| backup              | 17.0.5.60 | Enabled and up to date                      | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| broadcast           |           | Not Installed (Available online: 17.0.1.6)  | Commercial  |           |
| builtin             |           | Enabled; Not available online               |             | Unsigned  |
| bulkhandler         | 17.0.5    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.18 | Enabled and up to date                      | GPLv3+      | Sangoma   |
| callaccounting      |           | Not Installed (Available online: 17.0.5)    | Commercial+ |           |
| callback            | 17.0.2.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| callerid            |           | Not Installed (Available online: 17.0.1)    | Commercial  |           |
| callforward         | 17.0.1.6  | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| calllimit           |           | Not Installed (Available online: 17.0.1.2)  | Commercial  |           |
| callrecording       | 17.0.3.7  | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.19 | Enabled and up to date                      | GPLv3+      | Sangoma   |
| cdrpro              |           | Not Installed (Available online: 17.0.3.19) | Commercial  |           |
| cel                 | 17.0.2.8  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| certman             | 17.0.3.13 | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| conferencespro      |           | Not Installed (Available online: 17.0.1.7)  | Commercial  |           |
| configedit          | 17.0.1.2  | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| contactmanager      | 17.0.5.11 | Enabled and up to date                      | GPLv3+      | Sangoma   |
| core                | 17.0.14   | Enabled and up to date                      | GPLv3+      | Sangoma   |
| cos                 |           | Not Installed (Available online: 17.0.1.1)  | Commercial  |           |
| customappsreg       | 17.0.1    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.3  | Enabled and up to date                      | GPLv2+      | Sangoma   |
| dahdiconfig         |           | Not Installed (Available online: 17.0.1.14) | GPLv3+      |           |
| dashboard           | 17.0.4.3  | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| disa                | 17.0.4    | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.2  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| endpoint            |           | Not Installed (Available online: 17.0.1.80) | Commercial  |           |
| extensionroutes     | 17.0.1    | Enabled and up to date                      | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| faxpro              |           | Not Installed (Available online: 17.0.1.18) | Commercial  |           |
| featurecodeadmin    | 17.0.2    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.22 | Enabled and up to date                      | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.9  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.26 | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| framework           | 17.0.19.5 | Enabled and up to date                      | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6  | Enabled and up to date                      | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1    | Enabled and up to date                      | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1.1  | Enabled and up to date                      | GPLv2+      | Sangoma   |
| ivr                 | 17.0.6    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| languages           | 17.0.1    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| manager             | 17.0.6    | Enabled and up to date                      | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| music               | 17.0.5    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| outcnam             | 17.0.1    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| paging              | 17.0.3    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| pagingpro           |           | Not Installed (Available online: 17.0.1.6)  | Commercial  |           |
| parking             | 17.0.2.5  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| parkpro             |           | Not Installed (Available online: 17.0.1.4)  | Commercial  |           |
| pbxmfa              |           | Not Installed (Available online: 17.0.2.1)  | Commercial+ |           |
| phpinfo             | 17.0.1    | Enabled and up to date                      | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| pinsetspro          |           | Not Installed (Available online: 17.0.2)    | Commercial  |           |
| pm2                 | 17.0.3.2  | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| pms                 |           | Not Installed (Available online: 17.0.2.18) | Commercial  |           |
| presencestate       | 17.0.2.4  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| queues              | 17.0.1.11 | Enabled and up to date                      | GPLv2+      | Sangoma   |
| queuestats          |           | Not Installed (Available online: 17.0.1.7)  | Commercial  |           |
| qxact_reports       |           | Not Installed (Available online: 17.0.3)    | Commercial  |           |
| recording_report    |           | Not Installed (Available online: 17.0.3.8)  | Commercial  |           |
| recordings          | 17.0.2.2  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| restapps            |           | Not Installed (Available online: 17.0.1.21) | Commercial  |           |
| ringgroups          | 17.0.2.4  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| sangomaconnect      |           | Not Installed (Available online: 17.0.1.35) | Commercial  |           |
| sangomacrm          |           | Not Installed (Available online: 17.0.1.16) | Commercial  |           |
| sangomartapi        |           | Not Installed (Available online: 17.0.1.28) | Commercial  |           |
| setcid              | 17.0.1.2  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.9  | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| sipstation          |           | Not Installed (Available online: 17.0.3.3)  | Commercial  |           |
| sms                 |           | Not Installed (Available online: 17.0.1.15) | Commercial  |           |
| smsplus             |           | Not Installed (Available online: 17.0.3)    | Commercial  |           |
| soundlang           | 17.0.4.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| superfecta          | 17.0.2.1  | Enabled and up to date                      | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.95 | Enabled and up to date                      | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.18 | Enabled and up to date                      | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1  | Enabled and up to date                      | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1    | Enabled and up to date                      | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.20 | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.27 | Enabled and up to date                      | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| vmnotify            |           | Not Installed (Available online: 17.0.1.7)  | Commercial  |           |
| voicemail           | 17.0.5.22 | Enabled and up to date                      | GPLv3+      | Sangoma   |
| voicemail_report    |           | Not Installed (Available online: 17.0.1.1)  | Commercial  |           |
| voipinnovations     |           | Not Installed (Available online: 17.0.1.4)  | Commercial  |           |
| vqplus              |           | Not Installed (Available online: 17.0.1.17) | Commercial  |           |
| weakpasswords       | 17.0.1    | Enabled and up to date                      | GPLv3+      | Sangoma   |
| webcallback         |           | Not Installed (Available online: 17.0.4)    | Commercial  |           |
| webrtc              | 17.0.2.2  | Enabled and up to date                      | GPLv3+      | Sangoma   |
+---------------------+-----------+---------------------------------------------+-------------+-----------+

![ErroImportacaoCDR](https://github.com/user-attachments/assets/1d46ea6c-6381-4aef-a4f6-917cfd3fae6a)

**Comment by marcelo-merenda** [comment]
I believe there is a problem in the cdr module.
I forced the installation of the backup module version 17.0.5.58 and restored the backup, but it gave the same error.
Then, I forced the installation of the cdr 17.0.4.16 module and restored the backup again, and this time it worked, recovering the CDRs.

**Comment by jissphilip** [comment]
cdr version 15.0.24.11 
cdr version 16.0.46.14 
cdr version 17.0.4.20

**Comment by jissphilip** [comment]
cdr version 15.0.24.12

cdr version 16.0.46.15

cdr version 17.0.4.21
