### ISSUE TITLE
[improvement]: Remove MongoDB config from sangoma-pbx17 package

### ISSUE THREAD

**Issue by JoseGoncalves** [FreePBX/issue-tracker#396]
### FreePBX Version

FreePBX 17

### Improvement Description

When installing the `sangoma-pbx17` package in a Debian 12 distro without MongoDB installed the following error messages are displayed:
```
Setting up sangoma-pbx17 (2402-3.sng12) ...
/usr/bin/sed: can't read /etc/mongod.conf: No such file or directory
Failed to enable unit: Unit file mongod.service does not exist.
Failed to start mongod.service: Unit mongod.service not found.
```

Because MongoDB is not a required service in FreePBX 17 (see https://github.com/FreePBX/sng_freepbx_debian_install/pull/87),  the following lines should be removed from the package's `postint` script:
```
# MongoDB
/usr/bin/sed -ri 's/#?smallfiles.*/smallfiles = true/' /etc/mongod.conf
systemctl enable mongod || :
systemctl start mongod || :
```

**Comment by kapilgupta01** [comment]
done, removed mongo-db from the sangoma-pbx17 package.

**Comment by JoseGoncalves** [comment]
Hi @kguptasangoma. In which `sangoma-pbx17` version should that MongoDB config be removed?
I've checked the latest version available (2408-1.sng12) and it still has that config:
```
jmpg@st-3:~$ apt download sangoma-pbx17 
Get:1 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 sangoma-pbx17 all 2408-1.sng12 [11.0 kB]
Fetched 11.0 kB in 0s (25.7 kB/s)         
jmpg@st-3:~$ mkdir sangoma-pbx17
jmpg@st-3:~$ cd sangoma-pbx17/
jmpg@st-3:~/sangoma-pbx17$ ar x ../sangoma-pbx17_2408-1.sng12_all.deb 
jmpg@st-3:~/sangoma-pbx17$ tar xvf control.tar.xz 
./
./conffiles
./control
./md5sums
./postinst
./postrm
jmpg@st-3:~/sangoma-pbx17$ grep -C1 mongod postinst 
# MongoDB
/usr/bin/sed -ri 's/#?smallfiles.*/smallfiles = true/' /etc/mongod.conf
systemctl enable mongod || :
systemctl start mongod || :

```

**Comment by kapilgupta01** [comment]
i will check @JoseGoncalves

**Comment by msanthosh18** [comment]
Hi @JoseGoncalves 
Can you just run `apt update`, download the `sangoma-pbx17` and give a try it should be removed with it now.

Note : rpm version is still same.

**Comment by JoseGoncalves** [comment]
Hi @msanthosh18. I've checked, and now it's OK. Thanks!
