### ISSUE TITLE
[improvement]: adding hkps key server to refresh GPG keys

### ISSUE THREAD

**Issue by unkhum** [FreePBX/issue-tracker#400]
### FreePBX Version

FreePBX 16

### Improvement Description

Some organizations have the security policy where only SSL connections are allowed.
In this case, "Reloading..." window is continuously displayed on the web page after applying the config.
This is because the GPG keys can't be refreshed

`[freepbx.INFO]: Tried to refresh keys and failed with: GPG took too long to run the command:`

Adding **hkps** key server to GPG.class.php will fix this issue. For example:

`// List of well-known keyservers.
        private $keyservers = array(
                "hkps://keys.openpgp.org",
                "hkp://keyserver.ubuntu.com:80",  // This is in case port 11371 is blocked outbound
                "pgp.mit.edu", // Other random keyservers
                "keyserver.pgp.com"  // Other random keyserver
        ); // Yes. sks is there twice.`

**Comment by kapilgupta01** [comment]
framework v17.0.19.8

Added to v17 only as of now.
