### ISSUE TITLE
[bug]: FreePBX install script on new Debian 12 fails, could not locate package asterisk21

### ISSUE THREAD

**Issue by mdemoulin** [FreePBX/issue-tracker#403]
### FreePBX Version

FreePBX 17

### Issue Description

I tried to install FreePBX 17  on a fresh install of Debian 12 using the install script. After it was over, I got the Apache2 default page when I browsed to http://ftp.local/, and when I went to browsed to http://pbx/admin/, I got a 404-page not found error. The only changes I made to the server was installing net-tools, htop, screen, tshark, vim, and sngrep, per https://sangomakb.atlassian.net/wiki/spaces/FP/pages/295403538/Step+By+Step+Debian+12+Installation (and setting the IP address to static, and a few other customizations)

This is a virtual machine on a Promox server, for what it's worth, and is intended to be a pure SIP install (i.e., no DADHI)

### Operating Environment

as above

### Relevant log output

```shell
2024-08-29 15:06:22 - Installing Asterisk packages.
2024-08-29 15:06:22 - ###############################
2024-08-29 15:06:22 - Installing asterisk21 ....
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package asterisk21
2024-08-29 15:06:23 - Exiting script
```

**Comment by kapilgupta01** [comment]
Hi @mdemoulin 

Are you sure you have Sangoma repo configured in your server to pull the asterisk21 packages?

**Comment by JoseGoncalves** [comment]
@mdemoulin please check the output of command `apt policy asterisk21`. If all went good with the repositories setup by the script, you should see something similar to this:
```
asterisk21:
  Installed: (none)
  Candidate: 21.4.1-1.sng12
  Version table:
     21.4.1-1.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     21.3.1-1.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     21.0.2-1.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
```

**Comment by mdemoulin** [comment]
@kguptasangoma, I did not do that. That was not in the instructions. Perhaps it should be

@JoseGoncalves, that command returned `Unable to locate package asterisk2`

Thanks to you both; you have given me a thread to pull at

I will try again and report on the results, after adding what I need to my repo list

**Comment by JoseGoncalves** [comment]
The script automaticaly sets the repositories for you. If  `apt policy asterisk21` does not report avaliable packages, something has failed previously... you should have in the log file more information from that failure (previous to that log excerpt you posted).

**Comment by mdemoulin** [comment]
I have tried this again with the same results

`/etc/apt/sources.list.d/archive_uri-http_deb_freepbx_org_freepbx17-prod-bookworm.list`:
> `geb [arch=amd64] http://deb.freepbx.org/freepbx17-prod bookworm main`
> `# deb-src [arch=amd64] http://deb.freepbx.org/freepbx17-prod bookworm main`

`/etc/apt/sources.list.d/archive_uri-http_ftp_debian_org_debian_-bookworm.list`:
> `deb http://ftp.debian.org/debian/ stable non-free non-free-firmware main`
> `# deb-src http://ftp.debian.org/debian/ stable non-free non-free-firmware main`

I have run `apt update` fillowed by `apt install asterisk21`, and it still tells me `E: Unable to locate package asterisk21`

I have looked through the log file, and could find anything that jumps out to me as something that would cause this; what should I search for?

**Comment by mdemoulin** [comment]
Also, does it hurt anything if I run the scrupt more than once?

**Comment by JoseGoncalves** [comment]
Strange... what is the output of command `apt policy`?

**Comment by kapilgupta01** [comment]
you can re-run the script and check "/var/log/pbx/freepbx17-install-<date>.log" file to see if script actually finished successfully.

**Comment by mdemoulin** [comment]
@kguptasangoma: Thanks for that information

@JoseGoncalves: `apt policy` says:
```
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://ftp.debian.org/debian stable/main i386 Packages
     release v=12.6,o=Debian,a=stable,n=bookworm,l=Debian,c=main,b=i386
     origin ftp.debian.org
 500 http://ftp.debian.org/debian stable/non-free-firmware i386 Packages
     release v=12.6,o=Debian,a=stable,n=bookworm,l=Debian,c=non-free-firmware,b=i386
     origin ftp.debian.org
 500 http://ftp.debian.org/debian stable/non-free i386 Packages
     release v=12.6,o=Debian,a=stable,n=bookworm,l=Debian,c=non-free,b=i386
     origin ftp.debian.org
 600 http://deb.freepbx.org/freepbx17-prod bookworm/main all Packages
     release o=. bookworm,a=bookworm,n=bookworm,l=. bookworm,c=main,b=all
     origin deb.freepbx.org
 600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     release o=. bookworm,a=bookworm,n=bookworm,l=. bookworm,c=main,b=amd64
     origin deb.freepbx.org
 500 http://deb.debian.org/debian bookworm-updates/main i386 Packages
     release v=12-updates,o=Debian,a=stable-updates,n=bookworm-updates,l=Debian,c=main,b=i386
     origin deb.debian.org
 500 http://security.debian.org/debian-security bookworm-security/non-free-firmware i386 Packages
     release v=12,o=Debian,a=stable-security,n=bookworm-security,l=Debian-Security,c=non-free-firmware,b=i386
     origin security.debian.org
 500 http://security.debian.org/debian-security bookworm-security/main i386 Packages
     release v=12,o=Debian,a=stable-security,n=bookworm-security,l=Debian-Security,c=main,b=i386
     origin security.debian.org
 500 http://deb.debian.org/debian bookworm/non-free-firmware i386 Packages
     release v=12.6,o=Debian,a=stable,n=bookworm,l=Debian,c=non-free-firmware,b=i386
     origin deb.debian.org
 500 http://deb.debian.org/debian bookworm/main i386 Packages
     release v=12.6,o=Debian,a=stable,n=bookworm,l=Debian,c=main,b=i386
     origin deb.debian.org
Pinned packages:
```

**Comment by JoseGoncalves** [comment]
Hi @mdemoulin. It seems that you are trying to install FreePBX in an old 32 bits CPU (i386). AFAIK, FreePBX only supplies 64 bits packages (amd64), that's why it can not find appropriate Asterisk packages to install on your machine.

**Comment by mdemoulin** [comment]
@JoseGoncalves,
Wow, I had no idea. I just created a new Proxmox VM and did not change the CPU from the default, which is kvm64... and Linux is not recognizing that as 64 bits. I will be doing further research

**Comment by kapilgupta01** [comment]
Our Debian repository which is hosting asterisk and freepbx packages currently supporting only "arch=amd64".

**Comment by mdemoulin** [comment]
The weird thing is that I have FreePBX 16 installed on a Proxmox VM with the same CPU setting (`kvm64`), and `uname -m` returns `x86_64` on that one

**Comment by kapilgupta01** [comment]
That might be due to our own centos 7 based iso, Freepbx 17 is Debian.

**Comment by JoseGoncalves** [comment]
`x86_64` is the CentOS equivalent name to `amd64` architecture in Debian.

Don't know Proxmox, but, if you can create a VM from an ISO image, I would advise you use the latest 64-bit netinst Debian image to create a minimal Debian with only SSH server installed. You can download that ISO image from https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/

**Comment by mdemoulin** [comment]
@JoseGoncalves,
Thank you, that did it. I am properly embarrased for not realizing I was installing a i368 iso
