### ISSUE TITLE
[bug]: When running an existing backup from the GUI it saves the file to the main back up directory

### ISSUE THREAD

**Issue by 3xton** [FreePBX/issue-tracker#408]
### FreePBX Version

FreePBX 17

### Issue Description

Hello,
When i run an existing backup named Daily from the GUI it saves it to the main back backup directory instead of the Daily directory.
`Saving to: Local:'Local backup storage' instance ,File location: /var/spool/asterisk/backup/20240901-151254-1725192774-17.0.19.7-14756052.tar.gz `

Thank you,
Dani

### Operating Environment

Debian 12
Freepbx 17

**Comment by prasanthcode4** [comment]
Hi , Please check with this option "Append Backup Name as a directory to the Storage path". I have confirmed that it works correctly on both version 17 and version 16 systems.
<img width="539" alt="screen3" src="https://github.com/user-attachments/assets/a00702bf-ecb7-46d5-a8fc-d10833c15ab4">
