### ISSUE TITLE
[bug]: Download form on website does not work

### ISSUE THREAD

**Issue by abctaylor** [FreePBX/issue-tracker#41]
### FreePBX Version

FreePBX 16

### Issue Description

In any browser, the download button downloads nothing. Even with extensions disabled.

![image](https://github.com/FreePBX/issue-tracker/assets/30197206/e9170644-526d-4f1d-b369-1bb1196e818c)

### Operating Environment

N/A

**Comment by abctaylor** [comment]
For anyone who comes here from a search engine: https://downloads.freepbxdistro.org/ISO/

**Comment by ramarajan222** [comment]
Tried with  Chrome browser and the download is working fine.

![image](https://github.com/FreePBX/issue-tracker/assets/25248291/6b7de278-0022-4fcf-b7b2-333c3b8808bd)

**Comment by lgaetz** [comment]
There is an issue here with some browsers, but it's not a FreePBX engineering issue. I've escalated to the web maintenance team.
