### ISSUE TITLE
[bug]: FreePBX 16 to 17 upgrade (after I had restore it from the version 16 file, before following the steps to upgrade to 17)

### ISSUE THREAD

**Issue by steelmark5** [FreePBX/issue-tracker#411]
### FreePBX Version

FreePBX 17

### Issue Description

Hello. I have upgraded my FreePBX from 16 to 17 on (08/31/2024). I got a problem. 

Here is the problem in the pictures (attachments): 
![unnamed](https://github.com/user-attachments/assets/66c19cce-3b46-4065-979b-b38e137f79a0)
![unnamed (1)](https://github.com/user-attachments/assets/a154c13b-5046-4c77-bb51-e1a4dc5671de)
![unnamed (2)](https://github.com/user-attachments/assets/762bcd27-d2d3-49ae-b1e9-f1acb3517e09)
![unnamed (3)](https://github.com/user-attachments/assets/26163338-a37d-4921-b87e-8e9b162d4755)
![unnamed (4)](https://github.com/user-attachments/assets/c1f2345c-0fde-4ed1-8e62-c72c8dc1cf84)
![unnamed (5)](https://github.com/user-attachments/assets/807cad67-3da5-447c-b41b-1fc94fa44391)
![unnamed (6)](https://github.com/user-attachments/assets/7c8c3e03-07e5-445c-aa64-c27eeba40459)
  

Also, before this problem that is shown. The Asterisk had failed to start automatically when I first turned it on today (09/01/2024). So, I had to fwconsole restart, and it started the Asterisk. Then, I shut the server off and turned the server back on to make sure that problem went away, that's when this problem (in the pictures) came up.

### Operating Environment

Framework version: 17.0.19.7
Asterisk version: 20.9.1

Modules version:

+---------------------+-----------+---------+-------------+-----------+
| Module              | Version   | Status  | License     | Signature |
+---------------------+-----------+---------+-------------+-----------+
| accountcodepreserve | 17.0.0.1  | Enabled | GPLv2       | Sangoma   |
| adv_recovery        | 17.0.4    | Enabled | Commercial  | Sangoma   |
| allowlist           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| amd                 | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1  | Enabled | GPLv3+      | Sangoma   |
| api                 | 17.0.1.6  | Enabled | AGPLv3+     | Sangoma   |
| areminder           | 17.0.3.10 | Enabled | Commercial  | Sangoma   |
| arimanager          | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| backup              | 17.0.5.60 | Enabled | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| broadcast           | 17.0.1.6  | Enabled | Commercial  | Sangoma   |
| builtin             |           | Enabled |             | Unsigned  |
| bulkhandler         | 17.0.5    | Enabled | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.19 | Enabled | GPLv3+      | Sangoma   |
| callaccounting      | 17.0.5    | Enabled | Commercial+ | Sangoma   |
| callback            | 17.0.2.1  | Enabled | GPLv3+      | Sangoma   |
| callerid            | 17.0.1    | Enabled | Commercial  | Sangoma   |
| callforward         | 17.0.1.6  | Enabled | AGPLv3+     | Sangoma   |
| calllimit           | 17.0.1.2  | Enabled | Commercial  | Sangoma   |
| callrecording       | 17.0.3.7  | Enabled | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4  | Enabled | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.20 | Enabled | GPLv3+      | Sangoma   |
| cdrpro              | 17.0.3.19 | Enabled | Commercial  | Sangoma   |
| cel                 | 17.0.2.8  | Enabled | GPLv3+      | Sangoma   |
| certman             | 17.0.3.13 | Enabled | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2  | Enabled | GPLv3+      | Sangoma   |
| conferencespro      | 17.0.1.7  | Enabled | Commercial  | Sangoma   |
| configedit          | 17.0.1.2  | Enabled | AGPLv3+     | Sangoma   |
| contactmanager      | 17.0.5.11 | Enabled | GPLv3+      | Sangoma   |
| core                | 17.0.15   | Enabled | GPLv3+      | Sangoma   |
| cos                 | 17.0.1.1  | Enabled | Commercial  | Sangoma   |
| customappsreg       | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.3  | Enabled | GPLv2+      | Sangoma   |
| dashboard           | 17.0.4.5  | Enabled | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| disa                | 17.0.5    | Enabled | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3  | Enabled | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.2  | Enabled | GPLv3+      | Sangoma   |
| endpoint            | 17.0.1.81 | Enabled | Commercial  | Sangoma   |
| extensionroutes     | 17.0.1    | Enabled | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4  | Enabled | GPLv3+      | Sangoma   |
| faxpro              | 17.0.1.18 | Enabled | Commercial  | Sangoma   |
| featurecodeadmin    | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.23 | Enabled | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.10 | Enabled | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.26 | Enabled | AGPLv3+     | Sangoma   |
| framework           | 17.0.19.7 | Enabled | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6  | Enabled | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1    | Enabled | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1.1  | Enabled | GPLv2+      | Sangoma   |
| ivr                 | 17.0.6    | Enabled | GPLv3+      | Sangoma   |
| languages           | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3  | Enabled | GPLv3+      | Sangoma   |
| manager             | 17.0.6    | Enabled | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3    | Enabled | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| music               | 17.0.5    | Enabled | GPLv3+      | Sangoma   |
| outcnam             | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| paging              | 17.0.3    | Enabled | GPLv3+      | Sangoma   |
| pagingpro           | 17.0.1.6  | Enabled | Commercial  | Sangoma   |
| parking             | 17.0.2.5  | Enabled | GPLv3+      | Sangoma   |
| parkpro             | 17.0.1.4  | Enabled | Commercial  | Sangoma   |
| pbxmfa              | 17.0.2.1  | Enabled | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1    | Enabled | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2  | Enabled | GPLv3+      | Sangoma   |
| pinsetspro          | 17.0.2    | Enabled | Commercial  | Sangoma   |
| pm2                 | 17.0.3.2  | Enabled | AGPLv3+     | Sangoma   |
| pms                 | 17.0.2.18 | Enabled | Commercial  | Sangoma   |
| presencestate       | 17.0.2.4  | Enabled | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4  | Enabled | GPLv3+      | Sangoma   |
| queues              | 17.0.1.11 | Enabled | GPLv2+      | Sangoma   |
| queuestats          | 17.0.1.7  | Enabled | Commercial  | Sangoma   |
| qxact_reports       | 17.0.3    | Enabled | Commercial  | Sangoma   |
| recording_report    | 17.0.3.8  | Enabled | Commercial  | Sangoma   |
| recordings          | 17.0.2.2  | Enabled | GPLv3+      | Sangoma   |
| restapps            | 17.0.1.21 | Enabled | Commercial  | Sangoma   |
| ringgroups          | 17.0.2.4  | Enabled | GPLv3+      | Sangoma   |
| sangomaconnect      | 17.0.1.35 | Enabled | Commercial  | Sangoma   |
| sangomacrm          | 17.0.1.16 | Enabled | Commercial  | Sangoma   |
| sangomartapi        | 17.0.1.28 | Enabled | Commercial  | Sangoma   |
| setcid              | 17.0.1.2  | Enabled | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.9  | Enabled | AGPLv3+     | Sangoma   |
| sipstation          | 17.0.3.3  | Enabled | Commercial  | Sangoma   |
| sms                 | 17.0.1.15 | Enabled | Commercial  | Sangoma   |
| smsplus             | 17.0.3    | Enabled | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1  | Enabled | GPLv3+      | Sangoma   |
| superfecta          | 17.0.2.1  | Enabled | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.95 | Enabled | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.18 | Enabled | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1  | Enabled | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1    | Enabled | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.21 | Enabled | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.27 | Enabled | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2    | Enabled | GPLv3+      | Sangoma   |
| vmnotify            | 17.0.1.7  | Enabled | Commercial  | Sangoma   |
| voicemail           | 17.0.5.22 | Enabled | GPLv3+      | Sangoma   |
| voicemail_report    | 17.0.1.1  | Enabled | Commercial  | Sangoma   |
| voipinnovations     | 17.0.1.4  | Enabled | Commercial  | Sangoma   |
| vqplus              | 17.0.1.17 | Enabled | Commercial  | Sangoma   |
| weakpasswords       | 17.0.1    | Enabled | GPLv3+      | Sangoma   |
| webcallback         | 17.0.4    | Enabled | Commercial  | Sangoma   |
| webrtc              | 17.0.2.2  | Enabled | GPLv3+      | Sangoma   |
+---------------------+-----------+---------+-------------+-----------+

**Comment by kapilgupta01** [comment]
hi @steelmark5 please restart the apache2 service.

thanks
