### ISSUE TITLE
[bug]: Cron job generates error after system updates (apt-get upgrade)

### ISSUE THREAD

**Issue by chewy-chewbacca** [FreePBX/issue-tracker#413]
### FreePBX Version

FreePBX 17

### Issue Description

Started receiving the following email from FreePBX to asterisk@mypbx. Seemed to happen after the latest round of PHP 8.2 updates.

Subject: Cron <asterisk@pbx> [ -e /usr/sbin/fwconsole ] && sleep $((RANDOM%30)) && /usr/sbin/fwconsole job --run --quiet 2>&1 > /dev/null

Body:
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20220829/redis.so (/usr/lib/php/20220829/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20220829/redis.so.so (/usr/lib/php/20220829/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

### Operating Environment

Debian 12.6 Up to date / FreePBX 17 Up to date

**Comment by kapilgupta01** [comment]
Hi @chewy-chewbacca what is the "php -v" output ?

**Comment by kapilgupta01** [comment]
I just updated my 17 system and everything is looking good from my end.
`root@uc-42126347:~# php -v
PHP 8.2.23 (cli) (built: Aug 30 2024 11:34:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.23, Copyright (c) Zend Technologies
    with the ionCube PHP Loader v13.0.2, Copyright (c) 2002-2023, by ionCube Ltd.
    with Zend OPcache v8.2.23, Copyright (c), by Zend Technologies
`

`root@uc-42126347:~# uname -a
Linux uc-42126347 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
`

**Comment by kapilgupta01** [comment]
Please ensure that you have all the php8.2-<package> installed. 

Also for your error , it looks like you may be missing php8.2-igbinary package so try to install this one.

**Comment by chewy-chewbacca** [comment]
> Hi @chewy-chewbacca what is the "php -v" output ?

PHP 8.2.23 (cli) (built: Aug 30 2024 11:34:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.23, Copyright (c) Zend Technologies
    with the ionCube PHP Loader v13.0.2, Copyright (c) 2002-2023, by ionCube Ltd.
    with Zend OPcache v8.2.23, Copyright (c), by Zend Technologies

and

```
root@pbx:~# apt-get install php8.2-igbinary
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
php8.2-igbinary is already the newest version (3.2.16-1+0~20240830.50+debian12~1.gbp150a52).
php8.2-igbinary set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
```

**Comment by kapilgupta01** [comment]
so php is loading properly so not sure why you got the error for cron job, try to run below command manually ?

`/usr/sbin/fwconsole job --run`

**Comment by chewy-chewbacca** [comment]
No idea. This system was installed during the RC phase, not sure if that has anything to do with it.

Command seemed to run ok

```
`root@pbx:~# /usr/sbin/fwconsole job --run
Running dashboard :: scheduler ...
Done with scheduler
Running calendar :: sync ...
Starting Calendar Sync...
Finished
Done with sync
Running timeconditions :: schedtc ...
==Working with TimeCondition:WD==
INVERTED BLF: false (NOT_INUSE = NOT_INUSE & INUSE = INUSE)
OVERRIDE MODE: not set
=>08:00-17:00|mon-fri|*|* is not now
TIME MATCHED: False (INUSE)
BLF MODE: False (INUSE)
Privilege: Command
Changing TC1 to INUSE


==Working with TimeCondition:WD Lead==
INVERTED BLF: false (NOT_INUSE = NOT_INUSE & INUSE = INUSE)
OVERRIDE MODE: not set
=>08:00-17:00|mon-fri|*|* is not now
TIME MATCHED: False (INUSE)
BLF MODE: False (INUSE)
Privilege: Command
Changing TC3 to INUSE


==Working with TimeCondition:WD YLead==
INVERTED BLF: false (NOT_INUSE = NOT_INUSE & INUSE = INUSE)
OVERRIDE MODE: not set
=>08:00-17:00|mon-fri|*|* is not now
TIME MATCHED: False (INUSE)
BLF MODE: False (INUSE)
Privilege: Command
Changing TC4 to INUSE


==Working with TimeCondition:Support==
INVERTED BLF: false (NOT_INUSE = NOT_INUSE & INUSE = INUSE)
OVERRIDE MODE: not set
=>08:00-17:00|mon-fri|*|* is not now
TIME MATCHED: False (INUSE)
BLF MODE: False (INUSE)
Privilege: Command
Changing TC5 to INUSE


==Working with TimeCondition:Sales==
INVERTED BLF: false (NOT_INUSE = NOT_INUSE & INUSE = INUSE)
OVERRIDE MODE: not set
=>08:00-17:00|mon-fri|*|* is not now
TIME MATCHED: False (INUSE)
BLF MODE: False (INUSE)
Privilege: Command
Changing TC6 to INUSE


==Working with TimeCondition:PhilDil==
INVERTED BLF: false (NOT_INUSE = NOT_INUSE & INUSE = INUSE)
OVERRIDE MODE: not set
=>08:00-17:00|mon-fri|*|* is not now
TIME MATCHED: False (INUSE)
BLF MODE: False (INUSE)
Privilege: Command
Changing TC7 to INUSE


Done with schedtc
`
```

**Comment by kapilgupta01** [comment]
this is working fine so what error you are getting ?

**Comment by chewy-chewbacca** [comment]
No errors other than that email I receive, which is annoying.

**Comment by kapilgupta01** [comment]
This actually means failed to run the fwconsole job command but you are able to run this properly so not sure why you are getting emails,  please check /var/log/cron log file if you find any more clue.  

`Subject: Cron [asterisk@pbx](mailto:asterisk@pbx) [ -e /usr/sbin/fwconsole ] && sleep $((RANDOM%30)) && /usr/sbin/fwconsole job --run --quiet 2>&1 > /dev/null

Body:
PHP Warning: PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20220829/redis.so (/usr/lib/php/20220829/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20220829/redis.so.so (/usr/lib/php/20220829/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

**Comment by chewy-chewbacca** [comment]
Nothing interesting found. If I receive another one of these, I'll keep troubleshooting. Thanks!

**Comment by kapilgupta01** [comment]
Please feel free to re-open if you find more data to reproduce this issue. thanks
