### ISSUE TITLE
[bug]: Logrotate sangomartapi:27 unknown option ‘endscript’ – ignoring line

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#417]
### FreePBX Version

FreePBX 16

### Issue Description

Ref
https://community.freepbx.org/t/anacron-job-cron-daily/100201

There is no postrotate script so no need of endscript for /supervisor_queue_log . we need to remove "endscript" to avaiod the logrotate cron error.

`
logrotate sangomartapi
error: sangomartapi:27 unknown option 'endscript' -- ignoring line

`
 cat sangomartapi
/var/log/asterisk/sangomartapi/*.log {
    daily
    rotate 7
    dateext
    missingok
    notifempty
    sharedscripts
    copytruncate
    create 0664 asterisk asterisk
    su asterisk asterisk
    postrotate
    /usr/sbin/fwconsole pm2 --reload-logs -q
    endscript
}

/var/log/asterisk/supervisor_queue_log {
    weekly
size 50M
    rotate 10
    dateext
    missingok
    notifempty
    sharedscripts
    copytruncate
    create 0664 asterisk asterisk
    su asterisk asterisk
    endscript
}

`

### Operating Environment

FreePVX V16 and V17

### Relevant log output

```shell
logrotate sangomartapi
error: sangomartapi:27 unknown option 'endscript' -- ignoring line
```

**Comment by jissphilip** [comment]
sangomartapi version 16.0.49.28
 sangomartapi version 17.0.2.9
