### ISSUE TITLE
[improvement]: Initial network settings for Debian and system admin module does not work properly.

### ISSUE THREAD

**Issue by ctagithub** [FreePBX/issue-tracker#423]
### FreePBX Version

FreePBX 17

### Improvement Description

Fresh install yesterday.  Debian install without issue.  Did NOT install network manager or net tools.  Networking does not work as expected.  Issue discovered as follows.

Network has to be configured by Debian initially as dhcp or static address.  Debian puts network configuration in /etc/network/interfaces and that configuration file includes /etc/network/interfaces.d/*. FreePBX system admin module sets network settings at /etc/network/interfaces.d/nameofadapter.  After network configuration is done in sysadmin module and reboot the configuration in /etc/network/interfaces remains when it should be cleared.  Sysadmin should either do it how Debian does it or should update/clear the Debian configuration.  In our case we had multiple ip addresses after configuration, sometimes static would not work, sometimes it would after reboot. This line was in interfaces file #iface eno1 inet dhcp which we remarked out and the problem was resolved.

**Comment by kapilgupta01** [comment]
Hi @ctagithub 

Freepbx is writing the configuration files in "/etc/network/interfaces.d/" path.

Are you saying , writing the files is good but it just Freepbx not deleting `/etc/network/interfaces` causing the issues in networking?

**Comment by uj** [comment]
Similar issue today.  New install.  Installed Debian 12 exactly using the FreePBX website instructions.  The Debian installer gave me a DHCP address.  I went into the FreePBX web gui network settings, and changed it to a static address and rebooted.  Now, the console shows that I have 2 addresses.  1 static and 1 dhcp.  The FreePBX interface only shows the static, but the dhcp is also still definitely being applied.

**Comment by kapilgupta01** [comment]
sysadmin v17.0.1.96

Now when Freepbx will write the config to the `/etc/network/interfaces.d/*` path that time will also remove the entry of that interface from the `/etc/network/interfaces` file.

On an existing system - Please try to re-save the interface/network settings so Freepbx can remove the entry of that interface from the `/etc/network/interfaces` file.
