### ISSUE TITLE
[bug]: FreePBX17 dtmf does not work

### ISSUE THREAD

**Issue by tsaba12** [FreePBX/issue-tracker#424]
### FreePBX Version

FreePBX 17

### Issue Description

DTMF does not work for incoming calls after the announcement has been played in the IVR. It works only during the announcement duration. 

### Operating Environment

FreePBX version: 17.0.19.7
IVR version: 17.0.6
Asterisk CLI: 17.0.2

**Comment by msanthosh18** [comment]
@tsaba12 
Unable to reproduce this locally, Can you upgrade IVR module to latest 17.0.8 and give a try
Please share the asterisk cli logs for complete call to debug if its still not working for you along with ivr, announcement settings.

**Comment by lgaetz** [comment]
It would probably be useful to enable DTMF logging before sharing logs, Settings -> Asterisk Logfile Settings. It's off by default.

![image](https://github.com/user-attachments/assets/012d9179-faa8-45c3-ba94-69eb7d956714)

**Comment by 1soproni** [comment]
> @tsaba12 Unable to reproduce this locally, Can you upgrade IVR module to latest 17.0.8 and give a try Please share the asterisk cli logs for complete call to debug if its still not working for you along with ivr, announcement settings.

We cannot see IVR as upgradeable.

![image](https://github.com/user-attachments/assets/855d3281-0115-47a0-8926-e8fce095d90c)

What's wrong?

**Comment by kapilgupta01** [comment]
try again please or else you can use 
`fwconsole ma downloadinstall ivr --tag=17.0.8`

**Comment by 1soproni** [comment]
Update was done.
![image](https://github.com/user-attachments/assets/eb7b443c-55c6-4ca4-9963-aba1cd0644ea)
Why it was not visible in the repo?
IVR testing is ongoing.

**Comment by kapilgupta01** [comment]
please capture the dtmf logs as mentioned by @lgaetz in the previous comment. thanks

**Comment by tsaba12** [comment]
[pbxlog1.txt](https://github.com/user-attachments/files/16931520/pbxlog1.txt)
I attached the log with failed DTMF recognition. 
If i push the DTMF code after the announcement played the PBX said "app_read.c: User entered nothing."

**Comment by tsaba12** [comment]
I did another test. In the IVR it would switch the extension with DTMF "89". In this case, if I press "89" during the announcement, the log shows that I only pressed "8". 
So the FREEPBX only takes the first DTMF character, and that only during the announcement playback time.


35840	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:1] Set("PJSIP/Innotel-00000598", "__DIRECTION=INBOUND") in new stack	
35841	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:2] Gosub("PJSIP/Innotel-00000598", "sub-record-check,s,1(in,xxxxxxxxxx,dontcare)") in new stack	
35842	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:1] GotoIf("PJSIP/Innotel-00000598", "0?initialized") in new stack	
35843	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:2] Set("PJSIP/Innotel-00000598", "__REC_STATUS=INITIALIZED") in new stack	
35844	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:3] Set("PJSIP/Innotel-00000598", "NOW=1725959822") in new stack	
35845	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:4] Set("PJSIP/Innotel-00000598", "__DAY=10") in new stack	
35846	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:5] Set("PJSIP/Innotel-00000598", "__MONTH=09") in new stack	
35847	[2024-09-10 11:17:02] WARNING[146479][C-000001c6] taskprocessor.c: The 'stasis/pool-control' task processor queue reached 500 scheduled tasks again.	
35848	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:6] Set("PJSIP/Innotel-00000598", "__YEAR=2024") in new stack	
35849	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:7] Set("PJSIP/Innotel-00000598", "__TIMESTR=20240910-111702") in new stack	
35850	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:8] Set("PJSIP/Innotel-00000598", "__FROMEXTEN=unknown") in new stack	
35851	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:9] Set("PJSIP/Innotel-00000598", "__MON_FMT=wav") in new stack	
35852	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:10] NoOp("PJSIP/Innotel-00000598", "Recordings initialized") in new stack	
35853	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:11] ExecIf("PJSIP/Innotel-00000598", "0?Set(ARG3=dontcare)") in new stack	
35854	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:12] Set("PJSIP/Innotel-00000598", "REC_POLICY_MODE_SAVE=") in new stack	
35855	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:13] ExecIf("PJSIP/Innotel-00000598", "0?Set(REC_STATUS=NO)") in new stack	
35856	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:14] GotoIf("PJSIP/Innotel-00000598", "2?checkaction") in new stack	
35857	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx_builtins.c: Goto (sub-record-check,s,17)	
35858	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@sub-record-check:17] GotoIf("PJSIP/Innotel-00000598", "1?sub-record-check,in,1") in new stack	
35859	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx_builtins.c: Goto (sub-record-check,in,1)	
35860	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [in@sub-record-check:1] NoOp("PJSIP/Innotel-00000598", "Inbound Recording Check to xxxxxxxxxx") in new stack	
35861	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [in@sub-record-check:2] Set("PJSIP/Innotel-00000598", "FROMEXTEN=unknown") in new stack	
35862	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [in@sub-record-check:3] ExecIf("PJSIP/Innotel-00000598", "12?Set(FROMEXTEN=xxxxxxxxxx)") in new stack	
35863	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [in@sub-record-check:4] Gosub("PJSIP/Innotel-00000598", "recordcheck,1(dontcare,in,xxxxxxxxxx)") in new stack	
35864	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [recordcheck@sub-record-check:1] NoOp("PJSIP/Innotel-00000598", "Starting recording check against dontcare") in new stack	
35865	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [recordcheck@sub-record-check:2] Goto("PJSIP/Innotel-00000598", "dontcare") in new stack	
35866	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx_builtins.c: Goto (sub-record-check,recordcheck,3)	
35867	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [recordcheck@sub-record-check:3] Return("PJSIP/Innotel-00000598", "") in new stack	
35868	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [in@sub-record-check:5] Return("PJSIP/Innotel-00000598", "") in new stack	
35869	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:3] Set("PJSIP/Innotel-00000598", "CHANNEL(tonezone)=hu") in new stack	
35870	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:4] Set("PJSIP/Innotel-00000598", "__FROM_DID=xxxxxxxxxx") in new stack	
35871	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:5] Set("PJSIP/Innotel-00000598", "returnhere=1") in new stack	
35872	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:6] Gosub("PJSIP/Innotel-00000598", "app-blacklist-check,s,1()") in new stack	
35873	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@app-blacklist-check:1] GotoIf("PJSIP/Innotel-00000598", "0?blacklisted") in new stack	
35874	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@app-blacklist-check:2] Set("PJSIP/Innotel-00000598", "CALLED_BLACKLIST=1") in new stack	
35875	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@app-blacklist-check:3] Return("PJSIP/Innotel-00000598", "") in new stack	
35876	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:7] Set("PJSIP/Innotel-00000598", "CDR(did)=xxxxxxxxxx") in new stack	
35877	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:8] GotoIf("PJSIP/Innotel-00000598", "0?") in new stack	
35878	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:9] ExecIf("PJSIP/Innotel-00000598", "0 ?Set(CALLERID(name)=xxxxxxxxxx)") in new stack	
35879	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:10] Set("PJSIP/Innotel-00000598", "__MOHCLASS=") in new stack	
35880	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:11] Set("PJSIP/Innotel-00000598", "__REVERSAL_REJECT=FALSE") in new stack	
35881	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:12] GotoIf("PJSIP/Innotel-00000598", "1?post-reverse-charge") in new stack	
35882	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx_builtins.c: Goto (from-pstn,xxxxxxxxxx,14)	
35883	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:14] NoOp("PJSIP/Innotel-00000598", "") in new stack	
35884	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:15] Set("PJSIP/Innotel-00000598", "__CALLINGNAMEPRES_SV=allowed_not_screened") in new stack	
35885	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:16] Set("PJSIP/Innotel-00000598", "__CALLINGNUMPRES_SV=allowed_not_screened") in new stack	
35886	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:17] Set("PJSIP/Innotel-00000598", "CALLERID(name-pres)=allowed_not_screened") in new stack	
35887	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:18] Set("PJSIP/Innotel-00000598", "CALLERID(num-pres)=allowed_not_screened") in new stack	
35888	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:19] Set("PJSIP/Innotel-00000598", "__ALERT_INFO=alert_external") in new stack	
35889	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:20] NoOp("PJSIP/Innotel-00000598", "CallerID Entry Point") in new stack	
35890	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:21] Set("PJSIP/Innotel-00000598", "__CRM_DIRECTION=INBOUND") in new stack	
35891	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:22] Set("PJSIP/Innotel-00000598", "__CRM_SOURCE=xxxxxxxxxx") in new stack	
35892	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:23] Set("PJSIP/Innotel-00000598", "__CRM_LINKEDID=1725959822.6773") in new stack	
35893	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:24] AGI("PJSIP/Innotel-00000598", "agi://127.0.0.1/sangomacrm.agi,true") in new stack	
35894	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] res_agi.c: <PJSIP/Innotel-00000598>AGI Script agi://127.0.0.1/sangomacrm.agi completed, returning 0	
35895	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:25] ExecIf("PJSIP/Innotel-00000598", "1?Set(CHANNEL(hangup_handler_push)=crm-hangup,s,1)") in new stack	
35896	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [xxxxxxxxxx@from-pstn:26] Goto("PJSIP/Innotel-00000598", "ivr-3,s,1") in new stack	
35897	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx_builtins.c: Goto (ivr-3,s,1)	
35898	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:1] Set("PJSIP/Innotel-00000598", "TIMEOUT_LOOPCOUNT=0") in new stack	
35899	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:2] Set("PJSIP/Innotel-00000598", "INVALID_LOOPCOUNT=0") in new stack	
35900	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:3] Set("PJSIP/Innotel-00000598", "_IVR_CONTEXT_ivr-3=") in new stack	
35901	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:4] Set("PJSIP/Innotel-00000598", "_IVR_CONTEXT=ivr-3") in new stack	
35902	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:5] Set("PJSIP/Innotel-00000598", "__IVR_RETVM=") in new stack	
35903	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:6] Set("PJSIP/Innotel-00000598", "__IVR_ACCEPT_POUND=0") in new stack	
35904	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:7] GotoIf("PJSIP/Innotel-00000598", "0?skip") in new stack	
35905	[2024-09-10 11:17:02] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:8] Answer("PJSIP/Innotel-00000598", "") in new stack	
35906	[2024-09-10 11:17:03] SECURITY[1701] res_security_log.c: SecurityEvent="SuccessfulAuth",EventTV="2024-09-10T11:17:03.099+0200",Severity="Informational",Service="AMI",EventVersion="1",AccountID="RdWopwC9vxYk",SessionID="0x7f6c34042350",LocalAddress="IPV4/TCP/0.0.0.0/5038",RemoteAddress="IPV4/TCP/127.0.0.1/34722",UsingPassword="0",SessionTV="2024-09-10T11:17:03.099+0200"	
35907	[2024-09-10 11:17:03] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:9] Set("PJSIP/Innotel-00000598", "IVR_MSG=custom/Ugyeleti_idoben_hivott&custom/Adja_meg_pinkodjat") in new stack	
35908	[2024-09-10 11:17:03] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:10] Set("PJSIP/Innotel-00000598", "TIMEOUT(digit)=10") in new stack	
35909	[2024-09-10 11:17:03] VERBOSE[146479][C-000001c6] func_timeout.c: Digit timeout set to 10.000	
35910	[2024-09-10 11:17:03] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:11] Read("PJSIP/Innotel-00000598", "IVREXT,custom/Ugyeleti_idoben_hivott&custom/Adja_meg_pinkodjat,,,0,10") in new stack	
35911	[2024-09-10 11:17:03] VERBOSE[146479][C-000001c6] file.c: <PJSIP/Innotel-00000598> Playing 'custom/Ugyeleti_idoben_hivott.alaw' (language 'hu')	
35912	[2024-09-10 11:17:04] VERBOSE[146479][C-000001c6] file.c: <PJSIP/Innotel-00000598> Playing 'custom/Adja_meg_pinkodjat.alaw' (language 'hu')	
35913	[2024-09-10 11:17:05] SECURITY[1701] res_security_log.c: SecurityEvent="SuccessfulAuth",EventTV="2024-09-10T11:17:05.416+0200",Severity="Informational",Service="AMI",EventVersion="1",AccountID="RdWopwC9vxYk",SessionID="0x7f6c44174fb0",LocalAddress="IPV4/TCP/0.0.0.0/5038",RemoteAddress="IPV4/TCP/127.0.0.1/54342",UsingPassword="0",SessionTV="2024-09-10T11:17:05.416+0200"	
35914	[2024-09-10 11:17:06] SECURITY[1701] res_security_log.c: SecurityEvent="SuccessfulAuth",EventTV="2024-09-10T11:17:06.327+0200",Severity="Informational",Service="AMI",EventVersion="1",AccountID="RdWopwC9vxYk",SessionID="0x7f6c4014d840",LocalAddress="IPV4/TCP/0.0.0.0/5038",RemoteAddress="IPV4/TCP/127.0.0.1/54352",UsingPassword="0",SessionTV="2024-09-10T11:17:06.327+0200"	
35915	[2024-09-10 11:17:06] DTMF[146479][C-000001c6] channel.c: DTMF begin '8' received on PJSIP/Innotel-00000598	
35916	[2024-09-10 11:17:06] DTMF[146479][C-000001c6] channel.c: DTMF begin ignored '8' on PJSIP/Innotel-00000598	
35917	[2024-09-10 11:17:06] DTMF[146479][C-000001c6] channel.c: DTMF end '8' received on PJSIP/Innotel-00000598, duration 331 ms	
35918	[2024-09-10 11:17:06] DTMF[146479][C-000001c6] channel.c: DTMF end passthrough '8' on PJSIP/Innotel-00000598	
35919	[2024-09-10 11:17:09] SECURITY[1701] res_security_log.c: SecurityEvent="SuccessfulAuth",EventTV="2024-09-10T11:17:09.399+0200",Severity="Informational",Service="AMI",EventVersion="1",AccountID="RdWopwC9vxYk",SessionID="0x7f6c48168e90",LocalAddress="IPV4/TCP/0.0.0.0/5038",RemoteAddress="IPV4/TCP/127.0.0.1/54368",UsingPassword="0",SessionTV="2024-09-10T11:17:09.399+0200"	
35920	[2024-09-10 11:17:12] SECURITY[1701] res_security_log.c: SecurityEvent="SuccessfulAuth",EventTV="2024-09-10T11:17:12.471+0200",Severity="Informational",Service="AMI",EventVersion="1",AccountID="RdWopwC9vxYk",SessionID="0x5650b197bfa0",LocalAddress="IPV4/TCP/0.0.0.0/5038",RemoteAddress="IPV4/TCP/127.0.0.1/54370",UsingPassword="0",SessionTV="2024-09-10T11:17:12.471+0200"	
35921	[2024-09-10 11:17:15] SECURITY[1701] res_security_log.c: SecurityEvent="SuccessfulAuth",EventTV="2024-09-10T11:17:15.531+0200",Severity="Informational",Service="AMI",EventVersion="1",AccountID="RdWopwC9vxYk",SessionID="0x7f6c080af5f0",LocalAddress="IPV4/TCP/0.0.0.0/5038",RemoteAddress="IPV4/TCP/127.0.0.1/39320",UsingPassword="0",SessionTV="2024-09-10T11:17:15.531+0200"	
35922	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] app_read.c: User entered '8'	
35923	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:12] GotoIf("PJSIP/Innotel-00000598", "0?#,1") in new stack	
35924	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:13] GotoIf("PJSIP/Innotel-00000598", "0?t,1") in new stack	
35925	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:14] GotoIf("PJSIP/Innotel-00000598", "1?i,1") in new stack	
35926	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx_builtins.c: Goto (ivr-3,i,1)	
35927	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [i@ivr-3:1] Set("PJSIP/Innotel-00000598", "INVALID_LOOPCOUNT=1") in new stack	
35928	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [i@ivr-3:2] GotoIf("PJSIP/Innotel-00000598", "0?final") in new stack	
35929	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [i@ivr-3:3] Set("PJSIP/Innotel-00000598", "IVR_MSG=custom/Helytelen_pinkod") in new stack	
35930	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [i@ivr-3:4] Goto("PJSIP/Innotel-00000598", "s,start") in new stack	
35931	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx_builtins.c: Goto (ivr-3,s,10)	
35932	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:10] Set("PJSIP/Innotel-00000598", "TIMEOUT(digit)=10") in new stack	
35933	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] func_timeout.c: Digit timeout set to 10.000	
35934	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:11] Read("PJSIP/Innotel-00000598", "IVREXT,custom/Helytelen_pinkod,,,0,10") in new stack	
35935	[2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] file.c: <PJSIP/Innotel-00000598> Playing 'custom/Helytelen_pinkod.alaw' (language 'hu')	
35936	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] app_read.c: User disconnected	
35937	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] pbx.c: Executing [h@ivr-3:1] Hangup("PJSIP/Innotel-00000598", "") in new stack	
35938	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] pbx.c: Spawn extension (ivr-3, h, 1) exited non-zero on 'PJSIP/Innotel-00000598'	
35939	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] app_stack.c: PJSIP/Innotel-00000598 Internal Gosub(crm-hangup,s,1) start	
35940	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@crm-hangup:1] NoOp("PJSIP/Innotel-00000598", "Sending Hangup to CRM") in new stack	
35941	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@crm-hangup:2] NoOp("PJSIP/Innotel-00000598", "HANGUP CAUSE: 16") in new stack	
35942	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@crm-hangup:3] ExecIf("PJSIP/Innotel-00000598", "0?Set(__CRM_VOICEMAIL=)") in new stack	
35943	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@crm-hangup:4] NoOp("PJSIP/Innotel-00000598", "MASTER CHANNEL: 1725959822.6773 = 1725959822.6773") in new stack	
35944	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@crm-hangup:5] GotoIf("PJSIP/Innotel-00000598", "0?return") in new stack	
35945	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@crm-hangup:6] Set("PJSIP/Innotel-00000598", "__CRM_HANGUP=1") in new stack	
35946	[2024-09-10 11:17:18] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@crm-hangup:7] AGI("PJSIP/Innotel-00000598", "agi://127.0.0.1/sangomacrm.agi") in new stack

**Comment by ramarajan222** [comment]
Hi @tsaba12 

Only DTMF digit 8 is received in the log, and somehow digit 9 is not received in Asterisk. What type of DTMF mode is configured in the PJSIP trunk? Can you try using "RFC4733"?
Also, if you suspect that Asterisk is not detecting it, you can capture a PCAP on the PBX to confirm whether DTMF is being received from the telco.

```

35910 [2024-09-10 11:17:03] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:11] Read("PJSIP/Innotel-00000598", "IVREXT,custom/Ugyeleti_idoben_hivott&custom/Adja_meg_pinkodjat,,,0,10") in new stack
35911 [2024-09-10 11:17:03] VERBOSE[146479][C-000001c6] file.c: <PJSIP/Innotel-00000598> Playing 'custom/Ugyeleti_idoben_hivott.alaw' (language 'hu')
35912 [2024-09-10 11:17:04] VERBOSE[146479][C-000001c6] file.c: <PJSIP/Innotel-00000598> Playing 'custom/Adja_meg_pinkodjat.alaw' (language 'hu')
35915 [2024-09-10 11:17:06] DTMF[146479][C-000001c6] channel.c: DTMF begin '8' received on PJSIP/Innotel-00000598
35916 [2024-09-10 11:17:06] DTMF[146479][C-000001c6] channel.c: DTMF begin ignored '8' on PJSIP/Innotel-00000598
35917 [2024-09-10 11:17:06] DTMF[146479][C-000001c6] channel.c: DTMF end '8' received on PJSIP/Innotel-00000598, duration 331 ms
35918 [2024-09-10 11:17:06] DTMF[146479][C-000001c6] channel.c: DTMF end passthrough '8' on PJSIP/Innotel-00000598
35922 [2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] app_read.c: User entered '8'
35923 [2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:12] GotoIf("PJSIP/Innotel-00000598", "0?#,1") in new stack
35924 [2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:13] GotoIf("PJSIP/Innotel-00000598", "0?t,1") in new stack
35925 [2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [s@ivr-3:14] GotoIf("PJSIP/Innotel-00000598", "1?i,1") in new stack
35926 [2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx_builtins.c: Goto (ivr-3,i,1)
35927 [2024-09-10 11:17:16] VERBOSE[146479][C-000001c6] pbx.c: Executing [i@ivr-3:1] Set("PJSIP/Innotel-00000598", "INVALID_LOOPCOUNT=1") in new stack
```

**Comment by 1soproni** [comment]
I try to capture a PCAP but cannot see any rtpevent in it.
What's wrong?
RTP/rtp_udp is enabled under Analyze/Enabled protocols menu
Capture command is "tcpdump -i eth0 udp port 5060 or udp portrange 10000-20000 -s 0 -w /tmp/dtmf.pcap"

**Comment by kapilgupta01** [comment]
Hi, 

This appears to be a support issue. 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta
