### ISSUE TITLE
[bug]: When "Anonymous Calls Allowed" is enabled DTMF detection on the IVR no longer works

### ISSUE THREAD

**Issue by mdeleonardis2441** [FreePBX/issue-tracker#425]
### FreePBX Version

FreePBX 13/14

### Issue Description

When "Anonymous Calls Allowed" is enabled DTMF detection from anonymous calls to the IVR does not work. Calls with Caller ID have no issue as the DTMF is properly detected by the IVR. 

### Operating Environment

[fwconsole output.txt](https://github.com/user-attachments/files/16910410/fwconsole.output.txt)

**Comment by kapilgupta01** [comment]
please give a try on Freepbx 16 or freepbx 17 ?

13 and 14 is EOL.
