### ISSUE TITLE
[bug]: Apache2 default page instead of webUI after install script.

### ISSUE THREAD

**Issue by TremerePuck** [FreePBX/issue-tracker#426]
### FreePBX Version

FreePBX 17

### Issue Description

After running the install script on a fresh install of Debian 12.7 the "Apache2 Debian Default Page" loads rather than the expected webUI.

### Operating Environment

Debian 12.7

**Comment by JoseGoncalves** [comment]
The installer must have aborted with an error. Please check the log file at `/var/log/pbx/freepbx17-install-<date-timestamp>.log` for issues with the installation process.
