### ISSUE TITLE
[bug]: Module Admin does not present a progress indicator

### ISSUE THREAD

**Issue by JoseGoncalves** [FreePBX/issue-tracker#428]
### FreePBX Version

FreePBX 17

### Issue Description

In `Module Admin`, when I press the `Check Online` button, a progress indicator does not appear and, momentaneously, looks like that nothing is being done. 

I would expect that a behaviour similar to FreePBX 15 would occur, were the following appears when that button is pressed:

![Screenshot from 2024-09-08 11-45-34](https://github.com/user-attachments/assets/6f6ec2ec-43b6-4f97-a8cb-e86c01d79125)

### Operating Environment

* Debian 12
* Package: freepbx: 17.1-1.sng12

**Comment by kapilgupta01** [comment]
fraework v17.0.19.10

**Comment by JoseGoncalves** [comment]
Tried to upgrade the framework, but version 17.0.19.10 is still not visible in edge mode.
It takes some time to reach the repo?

**Comment by JoseGoncalves** [comment]
It's now available... I've tested and it's OK. Thanks!
