### ISSUE TITLE
[bug]: How to clear ip ban from Fail@Ban

### ISSUE THREAD

**Issue by khan5305** [FreePBX/issue-tracker#429]
### FreePBX Version

FreePBX 16

### Issue Description

Blocked by Fail2Ban
Any hosts in this section have been classified as an attackers by Fail2Ban's SIP jail. All traffic from them will be ignored for 30 minutes after they were classified as malicious.

If you believe one of the hosts has been added in error, you can click the red 'X' to remove the block. If the host continues to send invalid data, it will be automatically re-added.

**172.16.1.127**

### Operating Environment

ASAP

### Relevant log output

```shell
ASAP solution need
```

**Comment by kapilgupta01** [comment]
Please refer to below wiki.
https://sangomakb.atlassian.net/wiki/spaces/PG/pages/35226461/System+Admin-Intrusion+Detection

**Comment by kapilgupta01** [comment]
Hi, 

This appears to be a support issue. 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta
