### ISSUE TITLE
[bug]: UCP footer missing image and not aligned correctly 

### ISSUE THREAD

**Issue by dolesec** [FreePBX/issue-tracker#430]
### FreePBX Version

FreePBX 17

### Issue Description

UCP version 17.0.4.21  appears as below... 
![incorrectly displayed version 17](https://github.com/user-attachments/assets/d4fffd3a-6350-4e29-bfcf-cf4988e0dc7c)

compared to version 16 ...
![correctly displayed in version 16](https://github.com/user-attachments/assets/0d30587d-ade7-476a-8a5e-ef465ef40fe7)

### Operating Environment

+---------------------+-----------+-----------------------------------+-------------+-----------+
| Module              | Version   | Status                            | License     | Signature |
+---------------------+-----------+-----------------------------------+-------------+-----------+
| accountcodepreserve | 17.0.0.1  | Enabled                           | GPLv2       | Sangoma   |
| allowlist           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| amd                 | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| api                 | 17.0.1.6  | Enabled                           | AGPLv3+     | Sangoma   |
| arimanager          | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| backup              | 17.0.5.60 | Enabled                           | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| builtin             |           | Enabled                           |             | Unsigned  |
| bulkhandler         | 17.0.5    | Enabled                           | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.19 | Enabled                           | GPLv3+      | Sangoma   |
| callback            | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| callerid            | 17.0.1    | Enabled                           | Commercial  | Sangoma   |
| callforward         | 17.0.1.6  | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit           | 17.0.1.2  | Enabled                           | Commercial  | Sangoma   |
| callrecording       | 17.0.3.7  | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4  | Enabled                           | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.21 | Enabled                           | GPLv3+      | Sangoma   |
| cel                 | 17.0.2.9  | Enabled                           | GPLv3+      | Sangoma   |
| certman             | 17.0.3.13 | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro      | 17.0.1.7  | Enabled                           | Commercial  | Sangoma   |
| configedit          | 17.0.1.4  | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager      | 17.0.5.11 | Enabled                           | GPLv3+      | Sangoma   |
| core                | 17.0.16   | Enabled                           | GPLv3+      | Sangoma   |
| customappsreg       | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.3  | Enabled                           | GPLv2+      | Sangoma   |
| dashboard           | 17.0.4.5  | Enabled                           | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| disa                | 17.0.5    | Enabled                           | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3  | Enabled                           | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| endpoint            | 17.0.1.81 | Enabled                           | Commercial  | Sangoma   |
| extensionroutes     | 17.0.1    | Enabled                           | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4  | Enabled                           | GPLv3+      | Sangoma   |
| featurecodeadmin    | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.18 | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.10 | Enabled                           | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.26 | Enabled                           | AGPLv3+     | Sangoma   |
| framework           | 17.0.19.8 | Enabled                           | GPLv2+      | Sangoma   |
| iaxsettings         | 17.0.1    | Enabled                           | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1.1  | Enabled                           | GPLv2+      | Sangoma   |
| ivr                 | 17.0.6    | Enabled                           | GPLv3+      | Sangoma   |
| languages           | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3  | Enabled                           | GPLv3+      | Sangoma   |
| manager             | 17.0.6    | Enabled                           | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| music               | 17.0.5    | Enabled                           | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| paging              | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| parking             | 17.0.2.5  | Enabled                           | GPLv3+      | Sangoma   |
| pbxmfa              | 17.0.2.1  | Enabled                           | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1    | Enabled                           | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| pm2                 | 17.0.3.2  | Enabled                           | AGPLv3+     | Sangoma   |
| presencestate       | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4  | Enabled                           | GPLv3+      | Sangoma   |
| queues              | 17.0.1.11 | Enabled                           | GPLv2+      | Sangoma   |
| recordings          | 17.0.2.2  | Enabled                           | GPLv3+      | Sangoma   |
| restapps            | 17.0.1.22 | Enabled                           | Commercial  | Sangoma   |
| ringgroups          | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect      | 17.0.1.37 | Enabled                           | Commercial  | Sangoma   |
| sangomartapi        | 17.0.2.7  | Enabled                           | Commercial  | Sangoma   |
| setcid              | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.9  | Enabled                           | AGPLv3+     | Sangoma   |
| sms                 | 17.0.1.15 | Enabled                           | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1  | Enabled                           | GPLv3+      | Sangoma   |
| superfecta          |           | Not Installed (Locally available) | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.95 | Enabled                           | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.18 | Enabled                           | GPLv3+      | Sangoma   |
| ucp                 | 17.0.4.21 | Enabled                           | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.27 | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| voicemail           | 17.0.5.22 | Enabled                           | GPLv3+      | Sangoma   |
| weakpasswords       | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| webrtc              | 17.0.2.2  | Enabled                           | GPLv3+      | Sangoma   |
+---------------------+-----------+-----------------------------------+-------------+-----------+

**Comment by kapilgupta01** [comment]
ucp v17.0.4.22

**Comment by jissphilip** [comment]
ucp version 17.0.4.23
