### ISSUE TITLE
[bug]: No email from scheduled backup job

### ISSUE THREAD

**Issue by AlanCham56** [FreePBX/issue-tracker#431]
### FreePBX Version

FreePBX 17

### Issue Description

I have installed FreePBX 17 on Debian 12 and have a working system.  I used sysadmin to setup email and I have working email using the "debug" button.  However, if I manually run a backup, I receive the "success" email message from the system.  But, the scheduled job (0330) runs but NEVER sends an email.  The mail log shows no entries.  Email testing works and I see the messages being delivered in the mail log.  There is a cron entry in asterisk's crontab and when I run it manually everything works.  What else should I be checking. 

### Operating Environment

PBX Version: 17.0.19.7    PBX Distro:12.7.8-2402-3.sng12   Asterisk Version:21.4.1  with current updates

**Comment by kapilgupta01** [comment]
can you please see the backup log , do you see any entry of sending email kind of text?

**Comment by AlanCham56** [comment]
backup log is pretty sparse. Here are the entries from this morning.  The backup file was created.  Nothing in mail.log at that time. 
[2024-09-09 03:30:20] [80be158c-b3f2-4e32-b72a-9e59a9aeb1c1.DEBUG]: Removing /var/spool/asterisk/backup/Nightly-D-Local/20240901-033004-1725179404-17.0.19.7-1734455373.tar.gz.tar.gz [] []
[2024-09-09 03:30:20] [80be158c-b3f2-4e32-b72a-9e59a9aeb1c1.INFO]: Saving to selected Filestore locations [] []
[2024-09-09 03:30:20] [80be158c-b3f2-4e32-b72a-9e59a9aeb1c1.INFO]: Finished Saving to selected Filestore locations [] []

**Comment by kapilgupta01** [comment]
Hi @AlanCham56 are you seeing any log related with backup or email in "/var/log/asterisk/freepbx_dbug" ?

We have tried locally and we are able to from the logs that email has generated properly. Just fyi - output will be something like below - 

`[2024-09-11 12:16:17] [34766105-80c9-4622-aa65-b25f186113ef.INFO]: Saving to selected Filestore locations [] []
[2024-09-11 12:16:17] [34766105-80c9-4622-aa65-b25f186113ef.DEBUG]:     Saving to: Local:'Local backup storage' instance ,File location: /var/spool/asterisk/backup/20240911-121602-1726037162-17.0.19.9-970008106.tar.gz  [] []
[2024-09-11 12:16:17] [34766105-80c9-4622-aa65-b25f186113ef.INFO]: Finished Saving to selected Filestore locations [] []
[2024-09-11 12:16:18] [34766105-80c9-4622-aa65-b25f186113ef.DEBUG]: Generated Backup process result email to girishmani@sangoma.com. Status: Success [] []`

**Comment by AlanCham56** [comment]
That file is zero length on my system.  Is there something I need to do (an
fwconsole command, for example) to turn on debugging output?

/Alan/

**Comment by kapilgupta01** [comment]
if you run backup manually then email worked right? 

can you please paste your cron job entry and also output of "fwconsole job --list" output

**Comment by AlanCham56** [comment]
Yes, manually running the backup generates the message every time.  Copy/pasting the command line part of the crontab entry also sends the email every time.  

**Asterisk's crontab...**
root@deb12:/home/it# crontab -l -u asterisk
19 0 * * * /usr/sbin/fwconsole certificates --updateall -q 2>&1 >/dev/null
*/15 * * * * [ -e /usr/sbin/fwconsole ] && sleep $((RANDOM\%30)) && /usr/sbin/fwconsole userman --syncall -q
* * * * * [ -e /usr/sbin/fwconsole ] && sleep $((RANDOM\%30)) && /usr/sbin/fwconsole queuestats --syncall >> /var/log/asterisk/queuestats_syncall.log 2>&1
0 0 * * * [ -e /usr/sbin/fwconsole ] && sleep $((RANDOM\%30)) && /usr/sbin/fwconsole queuestats --purnedata >> /var/log/asterisk/queuestats_purnedata.log 2>&1
30 3 * * * /usr/sbin/fwconsole backup --backup=d780912f-25c8-406b-903d-afad955221b1  > /dev/null 2>&1
* 4 * * * /usr/sbin/fwconsole util cleanplaybackcache -q
2 11 * * 6 [ -e /usr/sbin/fwconsole ] && /usr/sbin/fwconsole ma listonline --sendemail -q > /dev/null 2>&1
* * * * * [ -e /usr/sbin/fwconsole ] && /usr/sbin/fwconsole job --run --quiet 2>&1 > /dev/null


**Job List...**
[joblist.txt](https://github.com/user-attachments/files/17007089/joblist.txt)

**Comment by kapilgupta01** [comment]
Are you saying if you run below command manually then you get the email ? but when the same command runs via cron then you do not get the email right ?
` /usr/sbin/fwconsole backup --backup=d780912f-25c8-406b-903d-afad955221b1`

if yes then may be add log to this command like modify your cron job and change the syntax to - 
` /usr/sbin/fwconsole backup --backup=d780912f-25c8-406b-903d-afad955221b1 >> /var/log/asterisk/backup_cron.log 2>&1`

then lets see if you get any logs to find out the root cause of your problem.

Thanks

**Comment by AlanCham56** [comment]
File is attached from the run you requested.   Only line of interest was that an email was generated.  Do you want me to change the crontab entry itself from /dev/null to making a file? 
[BUoutput.txt](https://github.com/user-attachments/files/17021063/BUoutput.txt)

**Comment by kapilgupta01** [comment]
Hi @AlanCham56 as you can see, log has below print , so you should have entry to the /var/log/maillog for the same. 

`Generated Backup process result email to alan@servicefirstpharmacies.com. Status: Success
`

**Comment by kapilgupta01** [comment]
Hi, 

This appears to be a support issue. 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta
