### ISSUE TITLE
[bug]: FreePBX 17 installation script

### ISSUE THREAD

**Issue by nabilsafir** [FreePBX/issue-tracker#435]
### FreePBX Version

FreePBX 17

### Issue Description

When starting the script of installation of FreePBX 17 in my Debian 12.7.0 it get stopped in the checking stage and doesn't gie any error.
checking logs I found the bellow :

```
2024-09-11 20:50:12 - ###############################
2024-09-11 20:50:12 - wget already present ....
2024-09-11 20:50:12 - ###############################
2024-09-11 20:50:12 - Performing version check...
```

### Operating Environment

FreePBX 17 in Debian 12.7.0

### Relevant log output

```shell
2024-09-11 20:50:12 - ###############################
2024-09-11 20:50:12 - wget already present ....
2024-09-11 20:50:12 - ###############################
2024-09-11 20:50:12 - Performing version check...
```

**Comment by msanthosh18** [comment]
Hi @nabilsafir ,
Can you see what is the error on install log file  which will be under /var/log/pbx

If no error, can you run again install script and see

example : /var/log/pbx/freepbx17-install-2024.09.12-07.12.37.log

**Comment by nabilsafir** [comment]
> Hi @nabilsafir , Can you see what is the error on install log file which will be under /var/log/pbx
> 
> If no error, can you run again install script and see
> 
> example : /var/log/pbx/freepbx17-install-2024.09.12-07.12.37.log

Hi @msanthosh18 
only give me the bellow :
2024-09-11 20:50:12 - ###############################
2024-09-11 20:50:12 - wget already present ....
2024-09-11 20:50:12 - ###############################
2024-09-11 20:50:12 - Performing version check...

**Comment by kapilgupta01** [comment]
Hi @nabilsafir please try with the latest script so you can see wget process output into the log file ?

**Comment by nabilsafir** [comment]
Thank you @kguptasangoma 
Now I get the logs :
root@tunpbx01:~# tail /var/log/pbx/freepbx17-install-2024.09.12-12.39.29.log
2024-09-12 12:39:29 - ###############################
2024-09-12 12:39:29 - wget already present ....
2024-09-12 12:39:29 - ###############################
2024-09-12 12:39:29 - Performing version check...
--2024-09-12 12:39:29--  https://github.com/FreePBX/sng_freepbx_debian_install/raw/master/sng_freepbx_debian_install.sh
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
ERROR: The certificate of ‘github.com’ is not trusted.
ERROR: The certificate of ‘github.com’ doesn't have a known issuer.

**Comment by JoseGoncalves** [comment]
Hi @nabilsafir. Can you check if running the following command as root before executing the installation script solves your issue:
```
apt install ca-certificates
```

**Comment by nabilsafir** [comment]
Hi @JoseGoncalves I did but doesn't resolve the issue, I finished by adding --no-check-certificate in the script and --skipversion  to skip comparing between the online version and mine and that resolved the issue.
Thank you all so much for your help.

**Comment by JoseGoncalves** [comment]
You can, of course, skip version checking using the scrip's `--skipversion` option but, if wget is failing with that error, is because you have something wrong in your base Debian install (some failure in CA Certificates installation ?).

My fealing is that you will encounter other problems going forward, if you don't find (and fix) the cause of this problem...

**Comment by JoseGoncalves** [comment]
P.S. You could try to reinstall the `ca-certificates`  package:
```
apt install --reinstall ca-certificates
```

**Comment by nabilsafir** [comment]
Get it, Thanks for bringing here this information, I will then reinstall the VM.

**Comment by rodrickmakore** [comment]
Hello, I am experiencing the same issue. I tried to re-install Debian 12 in a VM a couple of times with no success. Are there any other solutions available?
