### ISSUE TITLE
[bug]: CDRreports pro - call recording downloads stop at 5mb 

### ISSUE THREAD

**Issue by dolesec** [FreePBX/issue-tracker#436]
### FreePBX Version

FreePBX 17

### Issue Description

i attempted to download a recording from the CDRpro module and all downloads stop at 5mb ... this seems to be an issue with this paid module only as going to the free CDR reports and finding the same file allows for it to be downloaded without an issue 

this will fail to download ...
![Screenshot 2024-09-11 at 2 04 38 PM](https://github.com/user-attachments/assets/f413b6f5-fff5-48b8-88bb-c7984aff6e81)

this will successfully download the same file ...
![Screenshot 2024-09-11 at 2 09 08 PM](https://github.com/user-attachments/assets/290837a1-6c84-4b90-bd05-1820c1b3f2ea)

### Operating Environment

freepbx 17, all modules up to date

**Comment by jissphilip** [comment]
cdrpro version 17.0.3.21
cdrpro version 16.0.27
 cdrpro version 15.0.22
