### ISSUE TITLE
[bug]: Error on header parsing: Unable to decipher SIP request: OPTIONS sip:4001@0.0.0.0:5060;transport=UDP SIP/2.0

### ISSUE THREAD

**Issue by jawad097** [FreePBX/issue-tracker#437]
### FreePBX Version

FreePBX 16

### Issue Description

i want to to call my asterisk from python script using pyvoip library

### Operating Environment

asterisk 11 vicidial 8.0.1

**Comment by kapilgupta01** [comment]
Hi, 

This appears to be a support issue. 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta
