### ISSUE TITLE
[bug]: ucp tries to connect to ucp node server even if disabled

### ISSUE THREAD

**Issue by billsimon** [FreePBX/issue-tracker#44]
### FreePBX Version

FreePBX 17

### Issue Description

In Advanced Settings, nodejs server is disabled:

![image](https://github.com/FreePBX/issue-tracker/assets/5303782/8f9a6bb8-6b21-4e44-9d6b-26d7c5e4fcfd)

Yet in UCP, a red toast continually pops up about not being able to connect to the service:

![image](https://github.com/FreePBX/issue-tracker/assets/5303782/7dcf5fba-76e0-48da-98c3-da56a06bd772)

### Operating Environment

Deb 12
FreePBX 17.0.15.5
ucp 17.0.4.12

**Comment by jissphilip** [comment]
ucp-17.0.4.13
