### ISSUE TITLE
[bug]: Can’t select Snom D865/862 in the Snom template 

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#440]
### FreePBX Version

FreePBX 17

cant-select-snom-d865-862-in-the-snom-template

REF:-

https://community.freepbx.org/t/cant-select-snom-d865-862-in-the-snom-template/100367

### Operating Environment

FreePBX V17

### Relevant log output
![image](https://github.com/user-attachments/assets/ec5874ac-839c-4784-a568-5541c3c9247d)

**Comment by MPreeti-Sangoma** [comment]
Hi @ramarajan222 ,It appears that the PHP configuration values for max_input_vars and post_max_size differ from those on system-17, where post_max_size is set to 20M and max_input_vars to 5000. Currently, these settings are resolving the issue.

**Comment by ramarajan222** [comment]
Increased max_input_vars to 2000 in the installation script. This will take care of the new system; for the old installation, run the command below manually.

```
sed -i 's/;max_input_vars = 1000/max_input_vars = 5000/' /etc/php/8.2/apache2/php.ini
systemctl restart apache2

```
