### ISSUE TITLE
[bug]: Apt-update / upgrade bricks the whole system

### ISSUE THREAD

**Issue by rehoehle** [FreePBX/issue-tracker#441]
### FreePBX Version

FreePBX 17

### Issue Description

I have seen that there is an hold back update of FreePBX17. 

```
Die folgenden Pakete sind zurückgehalten worden:
  freepbx17
```

after installing this package the whole system was bricked. So first a lot of modules where missing and the Web-UI was broken. So i had to install some missing package. After fixing that problem i run into routing problems. So the complete routing was not working anymore. There was something with a missing "cdr" package i guess. 

On one inbound route there was now the DND message but there is nothing set. On other routes now Announcements appeared. So the whole routing was totally broken and a had to restore the whole system.

![2024-09-14_12-27](https://github.com/user-attachments/assets/2c4f84f5-e017-410d-8c67-9b2c0e915f1f)
![2024-09-14_12-33](https://github.com/user-attachments/assets/8ec3f08e-257f-4464-ac13-5864275f3bd3)

I've made some screenshots. 

### Operating Environment

Debian 12

### Relevant log output

```shell
I have a full logfile. There are numbers in it and i don't want to provide it here. So if someone need it please tell me.
```

**Comment by jcolp** [comment]
According to https://github.com/FreePBX/issue-tracker/issues/308#issuecomment-2228369809 the freepbx17 package is held on purpose.

**Comment by rehoehle** [comment]
@jcolp thanks for your reply. But ist that so clever? When you install that everything is broken. So then you have to find a way to remove that after installation. Normally you try to keep your packages up to date. This package will break your whole system. When you make a mistake and perhaps have other hold back packages it's not so good in my opinion.

@kguptasangoma can i remove that package? Or are there dependencies in it that are used?

**Comment by kapilgupta01** [comment]
`freepbx17` package is for initial setup of Freepbx in the Debian OS.

If we try to re-install this package or upgrade this package then this will overwrite the system configurations to the default again. 

We should not upgrade or re-install this package , that is the reason this is mark as "hold".

If you try to remove this package then "apt remove" will also remove all the files provided by this package which will break the default settings of the system.

**Comment by rehoehle** [comment]
@kguptasangoma sorry but that not a good solution in my opinion. Next time there are other hold back packages from Debian and someone install all of them and then the system is broken. Why are install scripts executed twice? Why not only on install? Then you can update the package over and over again and you have no problems. 

Or write a file that the system is installed correctly and then skip everything on install there are a lot solution instead of bricking the system when running the package again.

**Comment by kapilgupta01** [comment]
Thanks for h9ighlighting the concern @rehoehle  We can revisit this approach.
also just fyi - we are holding sangoma-pbx17 and nodejs* packages also to block auto upgrade for these packages also due to compatibility issues with the freepbx.
