### ISSUE TITLE
[bug]: FreePBX is using both /etc/network/interfaces and /etc/network/interfaces.d/enp6s18

### ISSUE THREAD

**Issue by uj** [FreePBX/issue-tracker#443]
### FreePBX Version

FreePBX 17

### Issue Description

When I installed Debian using the exact instructions on the FreePBX website, it initially gave me a DHCP address.  After the install, I went into the FreePBX and changed the DHCP to a static address, applied, and rebooted.

Now, the FreePBX web GUI only shows the Static IP (as expected), but the system actually has both a static and a dhcp address now.

I have this on SSH login:
```
Current Network Configuration
+-----------+-------------------+---------------------------+
| Interface | MAC Address       | IP Addresses              |
+-----------+-------------------+---------------------------+
| enp6s18   | BC:24:11:E5:F4:E7 | 192.168.42.103            |
|           |                   | 192.168.42.199            |
+-----------+-------------------+---------------------------+
```

This is the /etc/network/interfaces file:
```
source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug enp6s18
iface enp6s18 inet dhcp
```

This is the /etc/network/interfaces.d/enp6s18 file
```
# Sysadmin Generated network configuration.
# This file was generated at 2024-09-13T03:15:02+00:00
auto enp6s18
allow-hotplug enp6s18
iface enp6s18 inet static
  address 192.168.42.103
  netmask 255.255.255.0
  gateway 192.168.42.1
```

I did not create or modify either file.

FreePBX should have disabled the dhcp, but it did not.

### Operating Environment

FreePBX 17
Debian 12

**Comment by jissphilip** [comment]
sysadmin version 17.0.1.96
