### ISSUE TITLE
[improvement]: FreePBX Sysadmin Network Settings Improvements

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#444]
### FreePBX Version

FreePBX 17

### Improvement Description

**Sysadmin Network Settings Improvements**

Debian there can be various ways to configure the network settings which purely depends on how the system is getting deployed. 

Its not possible for Freepbx to control or manage all types of possible network settings, hence as of now, Freepbx sysadmin network settings can control the "_/etc/network/interfaces.d/*_"  configuration method.

https://sangomakb.atlassian.net/wiki/spaces/FP/pages/380534846/Network+configuration+with+Freepbx+17

**Current Behavior:**

Currently, if the FreePBX Sysadmin detects that the network is configured using a method other than the "_/etc/network/interfaces_" configuration then it will give 'Unable to configure the network" warning to the user to let user know that Freepbx can not manage the network and user is allowed to manage by themselves. 

**Improvements**

Need to improve this process to ask the user at the very first level itself like 

1. When the user navigates to Sysadmin Network Settings and the network is configured differently than through interfaces configuration, prompt the following question:
a. "Your system network is configured differently than through interfaces configuration, which FreePBX Sysadmin doesn't support. Do you want to manage the network using FreePBX sysadmin? YES or NO."
b. If the user selects "YES," write the network configuration into (/etc/network/interfaces.d/).
c. If the user selects "NO," do not make network configuration changes.

Here, Freepbx is assuming that if user chose Freepbx to generate/manage the network configurations then - 
1) No other service will not write the configurations to the "_/etc/network/interfaces.d/_" path.
2) No other service will try to manage the network settings. 

Thanks

**Comment by jissphilip** [comment]
sysadmin version 17.0.1.97
