### ISSUE TITLE
[new-feature]: Queue's handling Agents

### ISSUE THREAD

**Issue by goedkoper** [FreePBX/issue-tracker#445]
### FreePBX Version

FreePBX 16

### Feature Description

Help wanted!

I would like to see a solution for FreePBX.

A call comes in via Inboud Route;
It enters a Queue;
That Queue has 10 Agents;
A maximum of 2 of those Agents may be in conversation;
The remaining callers must be placed in the Queue;
When 1 of the 2 calls is hung up, the next person waiting in the Queue is offered to the other 9 Agents.
How do I solve that within FreePBX16 or FreePBX17.

I would like to hear from you.

Greetings, Gijsbert

**Comment by jcolp** [comment]
This appears to be a support request. The FreePBX community forum[1] is better suited to such questions, so I would suggest posting there instead to see if anyone can provide suggestions.

[1] https://community.freepbx.org/

**Comment by goedkoper** [comment]
Ok, I will check  https://community.freepbx.org/
Thanks.
