### ISSUE TITLE
[improvement]: EPM Default setting change for Grandstream

### ISSUE THREAD

**Issue by c-ferrall** [FreePBX/issue-tracker#447]
### FreePBX Version

FreePBX 16

### Improvement Description

There is a setting in EPM that makes a Grandstream phone send a command to unregister other registered sessions with the same extension when the phone is rebooted.  This causes a problem when an extension has multiple endpoints.

P81 needs to be changed from 1 to 0.  The default value from Grandstream is 0 but EPM uses 1.

,# Unregister On Reboot. 0 - No, 1 - Yes, 2 - Instance. Default is 0
,# Number: 0, 1
,# Mandatory
,P81 = 0

**Comment by kapilgupta01** [comment]
Hi, 

This appears to be a support issue. 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta

**Comment by c-ferrall** [comment]
I see this as a bug because it is a wrong default setting within the system.  A support issue would be if I didn't know how to fix it.  The fix is correcting the wrong setting within EPM.



Chris Ferrall
Chief Technology Officer
860.610.6014



-------- Original message --------
From: kguptasangoma ***@***.***>
Date: 9/19/24 12:33 (GMT-05:00)
To: FreePBX/issue-tracker ***@***.***>
Cc: Chris Ferrall ***@***.***>, Author ***@***.***>
Subject: Re: [FreePBX/issue-tracker] [improvement]: EPM Default setting change for Grandstream (Issue #447)


Hi,

This appears to be a support issue.

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at https://help.sangoma.com/<https://urldefense.proofpoint.com/v2/url?u=https-3A__help.sangoma.com_&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Ig9syPS4d7UDiAkEQqWLuYniIQPK7Nti_iNbSee5km8&m=QfyvloumakDyDJa_1lYUiH7q8uxSaQ4EOjiWNHynEmIVBsk--NY1dburOUkirymP&s=yQZBCXKlTXZ9gu8zsy33BiCGukehUv5FG3Y-FAqRQuM&e=>

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview<https://urldefense.proofpoint.com/v2/url?u=https-3A__sangomakb.atlassian.net_wiki_spaces_FP_overview&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Ig9syPS4d7UDiAkEQqWLuYniIQPK7Nti_iNbSee5km8&m=QfyvloumakDyDJa_1lYUiH7q8uxSaQ4EOjiWNHynEmIVBsk--NY1dburOUkirymP&s=C2D54USLYACOCEU2GneyKXmM7Ir8bjNuPeZH9mB9Z78&e=>
Community Forums with search
http://community.freepbx.org<https://urldefense.proofpoint.com/v2/url?u=http-3A__community.freepbx.org&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Ig9syPS4d7UDiAkEQqWLuYniIQPK7Nti_iNbSee5km8&m=QfyvloumakDyDJa_1lYUiH7q8uxSaQ4EOjiWNHynEmIVBsk--NY1dburOUkirymP&s=Ni6J1_dqEaW86GZa6Q55zHIWf1DaY0UWOyath0S1Gu8&e=>
Paid support.
https://help.sangoma.com/<https://urldefense.proofpoint.com/v2/url?u=https-3A__help.sangoma.com_&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Ig9syPS4d7UDiAkEQqWLuYniIQPK7Nti_iNbSee5km8&m=QfyvloumakDyDJa_1lYUiH7q8uxSaQ4EOjiWNHynEmIVBsk--NY1dburOUkirymP&s=yQZBCXKlTXZ9gu8zsy33BiCGukehUv5FG3Y-FAqRQuM&e=>

Thank you for using FreePBX
Kapil Gupta

**Comment by kapilgupta01** [comment]
Endpoint Manager is a commercial module so any issue related to the commercial modules should be handled via our support channel and Github issue tracker is for handling open source module issues, hence closed as support issues. 

however as you mentioned , default looks wrong so i just pushed the fix to endpoint v16.0.86.29 and v17.0.1.86

**Comment by c-ferrall** [comment]
Thank you.

I will direct future issues to the proper channel.



Chris Ferrall
Chief Technology Officer
860.610.6014



-------- Original message --------
From: kguptasangoma ***@***.***>
Date: 9/19/24 13:11 (GMT-05:00)
To: FreePBX/issue-tracker ***@***.***>
Cc: Chris Ferrall ***@***.***>, Author ***@***.***>
Subject: Re: [FreePBX/issue-tracker] [improvement]: EPM Default setting change for Grandstream (Issue #447)


Endpoint Manager is a commercial module so any issue related to the commercial modules should be handled via our support channel and Github issue tracker is for handling open source module issues, hence closed as support issues.

however as you mentioned , default looks wrong so i just pushed the fix to endpoint v16.0.86.29 and v17.0.1.86
