### ISSUE TITLE
[bug]: Restoring from Backup Includes System-Dependent Paths in fail2ban

### ISSUE THREAD

**Issue by ourherald** [FreePBX/issue-tracker#45]
### FreePBX Version

FreePBX 17

### Issue Description

The Restore function in the Backup/Restore module can render fail2ban unusable due to incorrect paths. For example, restoring a backup from CentOS-based FreePBX distro onto a Debian-based system prepped with the new installer script makes it impossible to start fail2ban because `/etc/fail2ban/jails.local` is generated with the paths from the prior system (i.e. `/var/log/httpd/` rather than `/var/log/apache2/` or `/var/log/secure` instead of `/var/log/auth.log`).

### Operating Environment

FreePBX 17 on Debian 12 with Asterisk 21.02 and backup version 17.0.5.13.

### Relevant log output

```shell
root@pbx0:/# systemctl status fail2ban
x fail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-03-17 00:57:55 EDT; 16h ago
   Duration: 295ms
       Docs: man:fail2ban(1)
    Process: 110770 ExecStart=/usr/bin/fail2ban-server -xf start (code=exited, status=255/EXCEPTION)
   Main PID: 110770 (code=exited, status=255/EXCEPTION)
        CPU: 296ms

Mar 17 00:57:55 pbx0 fail2ban-server[110770]: 2024-03-17 00:57:55,833 fail2ban.configreader   [110770]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
Mar 17 00:57:55 pbx0 fail2ban-server[110770]: 2024-03-17 00:57:55,834 fail2ban.configreader   [110770]: WARNING 'filter' not defined in 'sshd'. Using default one: ''
Mar 17 00:57:55 pbx0 fail2ban-server[110770]: 2024-03-17 00:57:55,834 fail2ban.jailreader     [110770]: WARNING No filter set for jail sshd
Mar 17 00:57:55 pbx0 fail2ban-server[110770]: 2024-03-17 00:57:55,835 fail2ban.configreader   [110770]: WARNING 'filter' not defined in 'sshd'. Using default one: ''
Mar 17 00:57:55 pbx0 fail2ban-server[110770]: 2024-03-17 00:57:55,835 fail2ban.configreader   [110770]: WARNING 'action' not defined in 'sshd'. Using default one: ''
Mar 17 00:57:55 pbx0 fail2ban-server[110770]: 2024-03-17 00:57:55,836 fail2ban.jailreader     [110770]: WARNING No actions were defined for sshd
Mar 17 00:57:55 pbx0 fail2ban-server[110770]: 2024-03-17 00:57:55,902 fail2ban                [110770]: ERROR   Failed during configuration: Have not found any log file for ssh-iptables jail
Mar 17 00:57:55 pbx0 fail2ban-server[110770]: 2024-03-17 00:57:55,902 fail2ban                [110770]: ERROR   Async configuration of server failed
Mar 17 00:57:55 pbx0 systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Mar 17 00:57:55 pbx0 systemd[1]: fail2ban.service: Failed with result 'exit-code'.
```

**Comment by jissphilip** [comment]
sysadmin version 17.0.1.45

**Comment by miken32** [comment]
@jissphilip it would be great if your programmers would mention issues in commits messages so they will be linked with each other. I'm surprised this isn't already a policy carried over from the internal git server. It would make it much easier to track changes.

**Comment by poltrian** [comment]
Have the same problem, when i change the path in fail2ban.local and do e reboot the old path is still there. Is any solution?

**Comment by ourherald** [comment]
It sounds like the FreePBX folks have resolved this with a new sysadmin version (if I'm understanding @jissphilip's comment correctly). In the short term, the work-around I've found successful is to add a file with the correct jail definitions at `/etc/fail2ban/jails.d/custom_jails.local`.

**Comment by jissphilip** [comment]
@miken32 
We have made changes in the sysadmin  commercial module ( repo is not in the github).
for all open source tickets we have adding the ticket number in the commit for references

Thank you For using FreePBX 
Philip  Joseph
