### ISSUE TITLE
[bug]: Firewall Services page fails to load

### ISSUE THREAD

**Issue by cstainless** [FreePBX/issue-tracker#450]
### FreePBX Version

FreePBX 17

### Issue Description

The Firewall Services page fails to a PHP whoops page. "strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated"

http://[server]/admin/config.php?display=firewall&page=services

See screenshot:
![Capture2](https://github.com/user-attachments/assets/148dabfb-4d66-4f2a-b338-8dfc48066d6d)

### Operating Environment

FreePBX Version: 17.0.19.9
PBX Distro: 12.7.8-2408-1.sng12
Asterisk Version: 20.9.1

Modules:

+---------------------+-----------+----------+-------------+-----------+
| Module              | Version   | Status   | License     | Signature |
+---------------------+-----------+----------+-------------+-----------+
| accountcodepreserve | 17.0.0.1  | Enabled  | GPLv2       | Sangoma   |
| adv_recovery        | 17.0.4    | Disabled | Commercial  | Sangoma   |
| allowlist           | 17.0.1.1  | Enabled  | GPLv3+      | Sangoma   |
| amd                 | 17.0.1    | Enabled  | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1  | Enabled  | GPLv3+      | Sangoma   |
| api                 | 17.0.1.6  | Enabled  | AGPLv3+     | Sangoma   |
| areminder           | 17.0.3.10 | Disabled | Commercial  | Sangoma   |
| arimanager          | 17.0.1.1  | Enabled  | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2    | Enabled  | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2    | Enabled  | GPLv3+      | Sangoma   |
| backup              | 17.0.5.60 | Enabled  | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2  | Enabled  | GPLv3+      | Sangoma   |
| broadcast           | 17.0.1.6  | Disabled | Commercial  | Sangoma   |
| builtin             |           | Enabled  |             | Unsigned  |
| bulkhandler         | 17.0.5    | Enabled  | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.19 | Enabled  | GPLv3+      | Sangoma   |
| callaccounting      | 17.0.5    | Disabled | Commercial+ | Sangoma   |
| callback            | 17.0.2.1  | Enabled  | GPLv3+      | Sangoma   |
| callerid            | 17.0.1    | Disabled | Commercial  | Sangoma   |
| callforward         | 17.0.1.6  | Enabled  | AGPLv3+     | Sangoma   |
| calllimit           | 17.0.1.2  | Disabled | Commercial  | Sangoma   |
| callrecording       | 17.0.3.7  | Enabled  | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4  | Enabled  | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.21 | Enabled  | GPLv3+      | Sangoma   |
| cdrpro              | 17.0.3.19 | Disabled | Commercial  | Sangoma   |
| cel                 | 17.0.2.9  | Enabled  | GPLv3+      | Sangoma   |
| certman             | 17.0.3.13 | Enabled  | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1  | Enabled  | GPLv3+      | Sangoma   |
| clearlydevices      | 17.0.1.1  | Enabled  | Commercial  | Unknown   |
| conferences         | 17.0.3.2  | Enabled  | GPLv3+      | Sangoma   |
| conferencespro      | 17.0.1.7  | Disabled | Commercial  | Sangoma   |
| configedit          | 17.0.1.4  | Enabled  | AGPLv3+     | Sangoma   |
| contactmanager      | 17.0.5.11 | Enabled  | GPLv3+      | Sangoma   |
| core                | 17.0.16   | Enabled  | GPLv3+      | Sangoma   |
| cos                 | 17.0.1.1  | Disabled | Commercial  | Sangoma   |
| customappsreg       | 17.0.1    | Enabled  | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.3  | Enabled  | GPLv2+      | Sangoma   |
| dashboard           | 17.0.4.5  | Enabled  | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1  | Enabled  | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2  | Enabled  | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1  | Enabled  | GPLv3+      | Sangoma   |
| disa                | 17.0.5    | Enabled  | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3  | Enabled  | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.2  | Enabled  | GPLv3+      | Sangoma   |
| endpoint            | 17.0.1.84 | Enabled  | Commercial  | Sangoma   |
| extensionroutes     | 17.0.1    | Disabled | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1    | Enabled  | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4  | Enabled  | GPLv3+      | Sangoma   |
| faxpro              | 17.0.1.18 | Disabled | Commercial  | Sangoma   |
| featurecodeadmin    | 17.0.2    | Enabled  | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.23 | Enabled  | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.10 | Enabled  | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.26 | Enabled  | AGPLv3+     | Sangoma   |
| framework           | 17.0.19.9 | Enabled  | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6  | Enabled  | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1    | Enabled  | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1.1  | Enabled  | GPLv2+      | Sangoma   |
| ivr                 | 17.0.8    | Enabled  | GPLv3+      | Sangoma   |
| languages           | 17.0.1    | Enabled  | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3  | Enabled  | GPLv3+      | Sangoma   |
| manager             | 17.0.6    | Enabled  | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3    | Enabled  | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1  | Enabled  | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.2  | Enabled  | GPLv3+      | Sangoma   |
| music               | 17.0.5    | Enabled  | GPLv3+      | Sangoma   |
| outcnam             | 17.0.1    | Enabled  | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1    | Enabled  | GPLv3+      | Sangoma   |
| paging              | 17.0.3    | Enabled  | GPLv3+      | Sangoma   |
| pagingpro           | 17.0.1.6  | Disabled | Commercial  | Sangoma   |
| parking             | 17.0.2.5  | Enabled  | GPLv3+      | Sangoma   |
| parkpro             | 17.0.1.4  | Disabled | Commercial  | Sangoma   |
| pbxmfa              | 17.0.2.1  | Disabled | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1    | Enabled  | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2  | Enabled  | GPLv3+      | Sangoma   |
| pinsetspro          | 17.0.2    | Disabled | Commercial  | Sangoma   |
| pm2                 | 17.0.3.2  | Enabled  | AGPLv3+     | Sangoma   |
| pms                 | 17.0.2.18 | Disabled | Commercial  | Sangoma   |
| presencestate       | 17.0.2.4  | Enabled  | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2  | Enabled  | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4  | Enabled  | GPLv3+      | Sangoma   |
| queues              | 17.0.1.11 | Enabled  | GPLv2+      | Sangoma   |
| queuestats          | 17.0.1.7  | Disabled | Commercial  | Sangoma   |
| qxact_reports       | 17.0.3    | Disabled | Commercial  | Sangoma   |
| recording_report    | 17.0.3.8  | Disabled | Commercial  | Sangoma   |
| recordings          | 17.0.2.2  | Enabled  | GPLv3+      | Sangoma   |
| restapps            | 17.0.1.21 | Disabled | Commercial  | Sangoma   |
| ringgroups          | 17.0.2.4  | Enabled  | GPLv3+      | Sangoma   |
| sangomaconnect      | 17.0.1.35 | Disabled | Commercial  | Sangoma   |
| sangomacrm          | 17.0.1.16 | Disabled | Commercial  | Sangoma   |
| sangomartapi        | 17.0.1.28 | Disabled | Commercial  | Sangoma   |
| setcid              | 17.0.1.2  | Enabled  | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.9  | Enabled  | AGPLv3+     | Sangoma   |
| sipstation          | 17.0.3.3  | Disabled | Commercial  | Sangoma   |
| sms                 | 17.0.1.15 | Disabled | Commercial  | Sangoma   |
| smsplus             | 17.0.3    | Disabled | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1  | Enabled  | GPLv3+      | Sangoma   |
| superfecta          | 17.0.2.1  | Enabled  | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.95 | Enabled  | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.18 | Enabled  | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1  | Enabled  | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1    | Enabled  | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.22 | Enabled  | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.27 | Enabled  | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2    | Enabled  | GPLv3+      | Sangoma   |
| vmnotify            | 17.0.1.7  | Disabled | Commercial  | Sangoma   |
| voicemail           | 17.0.5.22 | Enabled  | GPLv3+      | Sangoma   |
| voicemail_report    | 17.0.1.1  | Disabled | Commercial  | Sangoma   |
| voipinnovations     | 17.0.1.4  | Disabled | Commercial  | Sangoma   |
| vqplus              | 17.0.1.17 | Disabled | Commercial  | Sangoma   |
| weakpasswords       | 17.0.1    | Enabled  | GPLv3+      | Sangoma   |
| webcallback         | 17.0.4    | Disabled | Commercial  | Sangoma   |
| webrtc              | 17.0.2.2  | Enabled  | GPLv3+      | Sangoma   |
+---------------------+-----------+----------+-------------+-----------+

**Comment by kapilgupta01** [comment]
firewall v17.0.1.27
