### ISSUE TITLE
[bug]: FreePBX and Apache2 have a circular dependency in systemd

### ISSUE THREAD

**Issue by sfjuocekr** [FreePBX/issue-tracker#455]
### FreePBX Version

FreePBX 17

### Issue Description

During startup you are greeted with: "ordering cycle found skipping: apache2"

This is because the apache2.service contains freepbx.service as a wanted service and freepbx lists apache2 as an after target, this causes systemd to skip the launch of apache2.

I suggest changing the freepbx.service:

```
[Unit]
Description=FreePBX VoIP Server
After=mariadb.service network-online.target apache2.service
Wants=network-online.target
 
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/fwconsole start
ExecStop=/usr/sbin/fwconsole stop
 
[Install]
WantedBy=multi-user.target
```

And leaving the apache2.service untouched/remove the freepbx.service from the after targets.

### Operating Environment

Debian 12.7

**Comment by kapilgupta01** [comment]
Hi @sfjuocekr did you used the today latest script to install the freepbx 17?

can you please remove “freepbx.service” from After option in apache2 service file present in “/lib/systemd/system/apache2.service”.

This got fixed in the latest script.
