### ISSUE TITLE
[bug]: SQL Error Call Event Logging Cel.class.php

### ISSUE THREAD

**Issue by srs-adamr** [FreePBX/issue-tracker#459]
### FreePBX Version

FreePBX 17

### Issue Description

Call Event Logging UI is throwing an error due to malformed query. 

Solution: Simply add cel.eventtime to the SELECT. 

```
    $sql = "SELECT SQL_CALC_FOUND_ROWS DISTINCT cel.linkedid, cel.eventtime FROM cel WHERE 1";
```

### Operating Environment

FreePBX 17 on Debian 12
Using MySQL 8.0.37 via External Database

### Relevant log output

```shell
SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'asteriskcdrdb.cel.eventtime' which is not in SELECT list; this is incompatible with DISTINCT
File:/var/www/html/admin/modules/cel/Cel.class.php:486
```

**Comment by Akarsh04** [comment]
Please ensure that the CEL module is up to date. We haven't encountered any issues with the Call Event Logging UI, as it is just a simple query without any problems.

**Comment by srs-adamr** [comment]
This is the latest version (17.0.2.9), however this is with using an external database of MySQL 8.0.37 (a common use case for enterprise users). The query format is not valid in this use case, due to subtle differences between MariaDb and MySQL. The addition of that one portion of the query line supports both instances. I encourage you to review it further 👍

**Comment by jissphilip** [comment]
cel version 17.0.2.10
