### ISSUE TITLE
Exception thrown with message "SQLSTATE[HY000] [2002] Connection refused::SQLSTATE[HY000] [2002] Connection refused"  Stacktrace: #7 Exception in /var/www/html/admin/libraries/utility.functions.php:120 #6 die_freepbx in /var/www/html/admin/libraries/BMO/Database.class.php:145 #5 PDOException in /var/www/html/admin/libraries/BMO/Database.class.php:140 #4 PDO:__construct in /var/www/html/admin/libraries/BMO/Database.class.php:140 #3 FreePBX\Database:__construct in /var/www/html/admin/libraries/BMO/FreePBX.class.php:71 #2 FreePBX:__construct in /var/www/html/admin/bootstrap.php:144 #1 require_once in /etc/freepbx.conf:9 #0 include_once in /var/www/html/admin/config.php:126[bug]: 

### ISSUE THREAD

**Issue by DarshanPatelIAI** [FreePBX/issue-tracker#46]
### FreePBX Version

FreePBX 16

### Issue Description

Exception thrown with message "SQLSTATE[HY000] [2002] Connection refused::SQLSTATE[HY000] [2002] Connection refused"

Stacktrace:
#7 Exception in /var/www/html/admin/libraries/utility.functions.php:120
#6 die_freepbx in /var/www/html/admin/libraries/BMO/Database.class.php:145
#5 PDOException in /var/www/html/admin/libraries/BMO/Database.class.php:140
#4 PDO:__construct in /var/www/html/admin/libraries/BMO/Database.class.php:140
#3 FreePBX\Database:__construct in /var/www/html/admin/libraries/BMO/FreePBX.class.php:71
#2 FreePBX:__construct in /var/www/html/admin/bootstrap.php:144
#1 require_once in /etc/freepbx.conf:9
#0 include_once in /var/www/html/admin/config.php:126

### Operating Environment

Microsoft Edge - Windows 11

### Relevant log output

```shell
Exception thrown with message "SQLSTATE[HY000] [2002] Connection refused::SQLSTATE[HY000] [2002] Connection refused"

Stacktrace:
#7 Exception in /var/www/html/admin/libraries/utility.functions.php:120
#6 die_freepbx in /var/www/html/admin/libraries/BMO/Database.class.php:145
#5 PDOException in /var/www/html/admin/libraries/BMO/Database.class.php:140
#4 PDO:__construct in /var/www/html/admin/libraries/BMO/Database.class.php:140
#3 FreePBX\Database:__construct in /var/www/html/admin/libraries/BMO/FreePBX.class.php:71
#2 FreePBX:__construct in /var/www/html/admin/bootstrap.php:144
#1 require_once in /etc/freepbx.conf:9
#0 include_once in /var/www/html/admin/config.php:126
```

**Comment by jcolp** [comment]
This doesn't appear to be a bug, as the message states that FreePBX is unable to connect to the database. Please use the FreePBX community forums[1] for assistance.

[1] https://community.freepbx.org/
