### ISSUE TITLE
[bug]: Unstabel version of FreePBX in combination with Debian

### ISSUE THREAD

**Issue by goedkoper** [FreePBX/issue-tracker#462]
### FreePBX Version

FreePBX 17

### Issue Description

I am concerned about the new version of FreePBX.

FreePBX on Debian 12 linux version.
This is how I experience problems and instability of this system.

Installing it goes well! Transferring from old to new also works well.
However, if there is a sudden power outage and you then boot the system, the FreePBX web interface will no longer work.

Reinstall your Debian and FreePBX17 again, the ID is (fortunately) recognized, I also want to show it, but after restarting the system: "Allowed memory size of 536870912 bytes exhausted (tried to allocate 1281717103 bytes)".

I haven't even been able to perform a restore from a previously made backup.

Other problem: When you change the network card settings from the FreePBX web interface, your network stops working. It is as if FreePBX does not support Linux commands (properly).

I have the above on a test environment, but I now have two FreePBX17 environments at my customers...

I'd like to hear it.
![screendump](https://github.com/user-attachments/assets/2c633ef7-e2fe-474c-bc5f-abdfb955c081)

Best regards, Gijsbert Kampert

### Operating Environment

Debian 12 (Gnome), FreePBX 17.

### Relevant log output

```shell
Allowed memory size of 536870912 bytes exhausted (tried to allocate 1281717103 bytes)
```

**Comment by msanthosh18** [comment]
Hi @goedkoper ,
This looks like apache2 service is not started properly, Can you restart apache2 service manually and give a try

`systemctl restart apache2 `

**Comment by nicolasmtz** [comment]
I had the same problem after a fresh installation of Debian 12.7 and FreePBX 17, just after the first reboot.
After restarting apache2 with the following command, the problem disappeared:
systemctl restart apache2

Also noticed that restapps was down.  Solved with:
fwconsole start restapps

Everything worked in future reboots.

**Comment by kapilgupta01** [comment]
memory error is due to apache2 didnt started properly, we are adding protection check as a part of https://github.com/FreePBX/issue-tracker/issues/496 to fix that issue.

**Comment by goedkoper** [comment]
Thank You very much!
________________________________
Van: kguptasangoma ***@***.***>
Verzonden: dinsdag 15 oktober 2024 05:51
Aan: FreePBX/issue-tracker ***@***.***>
CC: Gijsbert Kampert | IGCN ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [FreePBX/issue-tracker] [bug]: Unstabel version of FreePBX in combination with Debian (Issue #462)


memory error is due to apache2 didnt started properly, we are adding protection check as a part of #496<https://github.com/FreePBX/issue-tracker/issues/496> to fix that issue.
