### ISSUE TITLE
[bug]: Creation of dynamic property FreePBX\modules\Sangomacrm\CRMAPI\API::$settings is deprecated

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#467]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

In sangomcrm, when we select “restapi” and calling its REST API for the first time, we get error as shown below : 

```
root@sangoma:~# curl -H "Token: e8541ba19a3f6d19c134c12777547dd05aed02e653fd136163650be61ccb36a6" http://PBXIP/admin/api/sangomacrm/rest/users/extension/101
Creation of dynamic property FreePBX\modules\Sangomacrm\CRMAPI\API::$settings is deprecated
```

When we set php error level to none in advanced settings and then try again, we get another error as given below 

 curl -H "Token: e8541ba19a3f6d19c134c12777547dd05aed02e653fd136163650be61ccb36a6" http://PBXIP/admin/api/sangomacrm/rest/users/extension/101
{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Uncaught TypeError: Slim\\App::__construct(): Argument #1 ($responseFactory) must be of type Psr\\Http\\Message\\ResponseFactoryInterface, array given, called in \/var\/www\/html\/admin\/modules\/sangomacrm\/CRMAPI\/API.php on line 54 and defined in \/var\/www\/html\/admin\/libraries\/Composer\/vendor\/slim\/slim\/Slim\/App.php:47\nStack trace:\n#0 \/var\/www\/html\/admin\/modules\/sangomacrm\/CRMAPI\/API.php(54): Slim\\App->__construct()\n#1 \/var\/www\/html\/admin\/modules\/sangomacrm\/Sangomacrm.class.php(897): FreePBX\\modules\\Sangomacrm\\CRMAPI\\API->__construct()\n#2 \/var\/www\/html\/admin\/libraries\/BMO\/Ajax.class.php(127): FreePBX\\modules\\Sangomacrm->ajaxCustomHandler()\n#3 \/var\/www\/html\/admin\/ajax.php(63): FreePBX\\Ajax->doRequest()\n#4 \/var\/www\/html\/admin\/api\/api.php(3): include('...')\n#5 {main}\n  thrown","code":1,"file":"\/var\/www\/html\/admin\/libraries\/Composer\/vendor\/slim\/slim\/Slim\/App.php","line":47}}

Thanks

### Operating Environment

| framework           | 17.0.19.13 | Enabled | GPLv2+      | Sangoma   |
| sangomacrm          | 17.0.1.16  | Enabled | Commercial  | Sangoma   |

**Comment by jissphilip** [comment]
sangomacrm version 17.0.1.17

**Comment by krlenix** [comment]
Same here! HELP!

**Comment by kapilgupta01** [comment]
hi @krlenix issue has been resolved in the latest sangomacrm module so can you please let us know if on the latest module also you are facing the same issue ? thanks
