### ISSUE TITLE
[bug]: Unvollständiges upgrade durch unvollständiges Backup

### ISSUE THREAD

**Issue by jgrieb111260** [FreePBX/issue-tracker#468]
### FreePBX Version

FreePBX 17

### Issue Description

To upgrade, you should reinstall FreePBX 17 and then restore a backup from version 15 or 16 in this installation.
Unfortunately, the backup from version 15/16 is incomplete. Custom language packs are not backed up and are not available in FreePBX after the upgrade. They must be copied manually later.

### Operating Environment

FreePBX 17.0.19.12
Asterisk 21.4.1

**Comment by msanthosh18** [comment]
Hi @jgrieb111260 ,
We are unable to reproduce as mentioned above, can you give a try by upgrading below modules to latest.

framework           | 16.0.40.11
 soundlang           | 16.0.9  
backup              | 16.0.70.2

Once updated to latest version, you just run the backup again and cross check the  backup file has the content of sound language data or not,
Untar the backup file, browse to modulejson folder and open Soundlang.json file

**Comment by jgrieb111260** [comment]
I tested the backup and restore again with the current module versions. The result is the same.
To clarify again: This is not about restoring custom sound files in a standard language. It's about restoring the sound files of an entire custom language.
I also checked the Soundlang.json in the backup file. There is no complete data for the user-specific language "de" there.
Soundlang.json:
{
    "module": "soundlang",
    "version": null,
    "pbx_version": null,
    "skip_reset": false,
    "dirs": [],
    "files": [],
    "configs": {
        "packages": {
            "5": {
                "id": "5",
                "type": "asterisk",
                "module": "core-sounds",
                "language": "en",
                "license": "",
                "author": "Allison Smith",
                "authorlink": "http:\/\/www.theivrvoice.com",
                "format": "alaw",
                "version": "1.5",
                "installed": "1.5"
            },
            "6": {
                "id": "6",
                "type": "asterisk",
                "module": "core-sounds",
                "language": "en",
                "license": "",
                "author": "Allison Smith",
                "authorlink": "http:\/\/www.theivrvoice.com",
                "format": "g722",
                "version": "1.5",
                "installed": "1.5"
            },
            "7": {
                "id": "7",
                "type": "asterisk",
                "module": "core-sounds",
                "language": "en",
                "license": "",
                "author": "Allison Smith",
                "authorlink": "http:\/\/www.theivrvoice.com",
                "format": "g729",
                "version": "1.5",
                "installed": "1.5"
            },
            "8": {
                "id": "8",
                "type": "asterisk",
                "module": "core-sounds",
                "language": "en",
                "license": "",
                "author": "Allison Smith",
                "authorlink": "http:\/\/www.theivrvoice.com",
                "format": "ulaw",
                "version": "1.5",
                "installed": "1.5"
            },
            "67": {
                "id": "67",
                "type": "asterisk",
                "module": "extra-sounds",
                "language": "en",
                "license": "",
                "author": "Allison Smith",
                "authorlink": "http:\/\/www.theivrvoice.com",
                "format": "alaw",
                "version": "1.5",
                "installed": "1.5"
            },
            "68": {
                "id": "68",
                "type": "asterisk",
                "module": "extra-sounds",
                "language": "en",
                "license": "",
                "author": "Allison Smith",
                "authorlink": "http:\/\/www.theivrvoice.com",
                "format": "g722",
                "version": "1.5",
                "installed": "1.5"
            },
            "69": {
                "id": "69",
                "type": "asterisk",
                "module": "extra-sounds",
                "language": "en",
                "license": "",
                "author": "Allison Smith",
                "authorlink": "http:\/\/www.theivrvoice.com",
                "format": "g729",
                "version": "1.5",
                "installed": "1.5"
            },
            "70": {
                "id": "70",
                "type": "asterisk",
                "module": "extra-sounds",
                "language": "en",
                "license": "",
                "author": "Allison Smith",
                "authorlink": "http:\/\/www.theivrvoice.com",
                "format": "ulaw",
                "version": "1.5",
                "installed": "1.5"
            }
        },
        **"settings": [
            {
                "keyword": "formats",
                "value": "alaw,g722,g729,ulaw"
            },
            {
                "keyword": "language",
                "value": "de"
            }
        ],
        "customlangs": [
            {
                "id": "1",
                "language": "de",
                "description": "Deutsch"
            }
        ]
    },
    "dependencies": [],
    "garbage": []**
}

**Comment by girishmani1992** [comment]
Hi @jgrieb111260,

By default, we are not including custom files in backup files. We have to add "directory" in the Custom files section while taking backup from v15/v16 system so that same files are restored properly in their respective folders.

Attaching screen-shot for reference. 

![image](https://github.com/user-attachments/assets/03de0a89-516d-466d-a33b-adbb82ce513f)


Thanks

**Comment by kapilgupta01** [comment]
please let us know if the issue still exists.

**Comment by jgrieb111260** [comment]
***@***.***<https://www.griebsch.de/>

Hello,

The issue is solved.
Thanks


Systemhaus Griebsch GmbH
Jörg Griebsch
Hasselfelder Weg 3
37445 Walkenried

Fon: 05525 95996990
Fax: 05525 95996919
E-Mail: ***@***.******@***.***>
Web: www.griebsch.de<http://www.griebsch.de/>

Geschäftsführer: Allin Griebsch

HRB 201224
Amtsgericht Göttingen
AGB: http://www.griebsch.de/1/agb/

Von: kguptasangoma ***@***.***>
Gesendet: Dienstag, 15. Oktober 2024 06:08
An: FreePBX/issue-tracker ***@***.***>
Cc: Systemhaus Griebsch GmbH ***@***.***>; Mention ***@***.***>
Betreff: Re: [FreePBX/issue-tracker] [bug]: Unvollständiges upgrade durch unvollständiges Backup (Issue #468)


please let us know if the issue still exists.
