### ISSUE TITLE
[bug]: Unable to install module fetchcontactsbygroup

### ISSUE THREAD

**Issue by kalderista** [FreePBX/issue-tracker#47]
### FreePBX Version

FreePBX 16

### Issue Description

Hi,

Can’t find any docu about this. I’m trying to update Sangommaconnect module, but I get an error like this:

    Unable to locate the FreePBX BMO Class 'Fetchcontactsbygroup’A required module might be disabled or uninstalled. Recommended steps (run from the CLI): 1) fwconsole ma install fetchcontactsbygroup 2) fwconsole ma enable fetchcontactsbygroup

If I try to install fetchcontactsbygroup, I get this error:

    Unable to install module fetchcontactsbygroup:- Cannot find module

Contact Manager module is allready installed and update.

Regards

### Operating Environment

FreePBX 15.0.37.4
Asterisk 16.30.0

**Comment by ramarajan222** [comment]
Hi @kalderista,

This issue has been fixed with the latest contact manager module, update the contact manager module to the latest version(V15 = 15.0.13, V16 = 16.0.25).


`fwconsole ma upgrade contactmanager`

**Comment by kalderista** [comment]
Hi @ramarajan222 , thank you for your help. Now, it works properly ;)

Regards
