### ISSUE TITLE
[bug]: The Missed Call Notification module does not work.

### ISSUE THREAD

**Issue by jgrieb111260** [FreePBX/issue-tracker#470]
### FreePBX Version

FreePBX 17

### Issue Description

Even if all notification options are activated and the email address is stored, no message will be sent if a call is missed. The mail function was tested via the user administration and works.

### Operating Environment

FreePBX 17.0.19.12
Asterisk 21.4.1

**Comment by msanthosh18** [comment]
Hi @jgrieb111260 ,
We have an open ticket for this issue already and will you know the fixed version asap.

Thanks.

**Comment by msanthosh18** [comment]
Ref  - https://github.com/FreePBX/issue-tracker/issues/449
