### ISSUE TITLE
[bug]: Backups not completing, erroring out

### ISSUE THREAD

**Issue by John22546** [FreePBX/issue-tracker#471]
### FreePBX Version

FreePBX 16

### Issue Description

When running backups I receive error PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 73404416 bytes) in /var/www/html/admin/modules/backup/Json/json_encode.php on line 5 when the backup reaches this part of the endpoint KVStore
Exporting KVStore from Endpoint
Whoops\Exception\ErrorException: Allowed memory size of 536870912 bytes exhausted (tried to allocate 73404416 bytes) in file /var/www/html/admin/modules/backup/Json/json_encode.php on line 5
Stack trace:
  1. Whoops\Exception\ErrorException->() /var/www/html/admin/modules/backup/Json/json_encode.php:5
  2. Whoops\Run->handleError() /var/www/html/admin/libraries/Composer/vendor/filp/whoops/src/Whoops/Run.php:383
  3. Whoops\Run->handleShutdown() [internal]:0

### Operating Environment

FreePBX 16 asterisk 18.16.0  installed from ISO

Backup module 16.0.70.2
Framework 16.40.10
Core 16.0.68.30

### Relevant log output

```shell
Exporting KVStore from Endpoint
Whoops\Exception\ErrorException: Allowed memory size of 536870912 bytes exhausted (tried to allocate 73404416 bytes) in file /var/www/html/admin/modules/backup/Json/json_encode.php on line 5
Stack trace:
  1. Whoops\Exception\ErrorException->() /var/www/html/admin/modules/backup/Json/json_encode.php:5
  2. Whoops\Run->handleError() /var/www/html/admin/libraries/Composer/vendor/filp/whoops/src/Whoops/Run.php:383
  3. Whoops\Run->handleShutdown() [internal]:0
```

**Comment by msanthosh18** [comment]
Hi @John22546 ,
Looks like EPM has more data, can you run below commands and share the output
 
 cat /etc/php.ini | grep memory_limit
 cat /etc/php.d/freepbx.ini | grep memory_limit

**Comment by John22546** [comment]
Hello here are the outputs, I attempted setting php.ini to 2048M and 4096M and restarting http but got the same result, I haven't tried adjusting the freepbx.ini one though.
[root@UKS-FreePBX16-01 ~]# cat /etc/php.ini | grep memory_limit
memory_limit = 128M
[root@UKS-FreePBX16-01 ~]# cat /etc/php.d/freepbx.ini | grep memory_limit
memory_limit = 512M

**Comment by msanthosh18** [comment]
Hi @John22546 ,
can you try  adjusting the freepbx.ini, since we are unable to reproduce locally.

**Comment by John22546** [comment]
Hello, 

The freepbx.ini was adjusted to 1024 and it appears that resolved the issue and I am no longer getting the error.
