### ISSUE TITLE
[bug]: Calendar Event maintenance. Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by moretolearn01** [FreePBX/issue-tracker#474]
### FreePBX Version

FreePBX 16

### Issue Description

Attempt to create new event and the following toast appears, with no entry is displayed in the calendar.
"Maximum function nesting level of '256' reached, aborting!"
![Screenshot 2024-10-05 140925](https://github.com/user-attachments/assets/627f00fd-bf73-4836-9702-483222f86fdd)

Rebooted to see if this would help, which it didn't. Several events did display in the calendar, which are the attempts previously made when the error displayed.

This error message also pops up when deleting an event.
Maximum function nesting level of '256' reached, aborting!
File:/var/www/html/admin/modules/calendar/vendor/om/icalparser/src/Freq.php:300

### Operating Environment

FreePBX 16.0.40.11
Asterisk Version: 20.5.2
PBX Distro: 12.7.8-2306-1.sng7
Calendar module: 16.0.29
All modules up-to-date

**Comment by msanthosh18** [comment]
Can you give a try updating the below version 
fwconsole ma downloadinstall calendar --tag 16.0.34

**Comment by moretolearn01** [comment]
> Can you give a try updating the below version fwconsole ma downloadinstall calendar --tag 16.0.34

Thanks @msanthosh18 . This has resolved the issue.
