### ISSUE TITLE
[bug]: Launch failure

### ISSUE THREAD

**Issue by ghost** [FreePBX/issue-tracker#477]
### FreePBX Version

FreePBX 16

### Issue Description

Clean install of plain vanilla Debian 12 using instructions provided that include screenshots, followed by a scripted install of FreePBX 17 via SSH as root with all modules logging as installed successfully. Reboot, then access via browser where intro page requests username and password. Upon clicking submit this takes me to the landing page with three icon options. Attempts to login immediately return an error of invalid credentials, using the credentials just entered seconds before. I've repeated this whole blow-out-the-partitions, install Debian, install FreePBX several times and the result is the same. If I try to re-open the browser admin tool it locks up the IP interface. Console still works but no response to SSH, HTTP or even ping.

I have followed the instructions scrupulously. Any ideas? I have console access so should be able to copy anything from the machine to a thumb drive but no IP access.

### Operating Environment

Beelink Mini Pro which came with a Win 11 license so it should be of recent vintage. CPU is Intel

### Relevant log output

```shell
Let me know what you need
```

**Comment by JoseGoncalves** [comment]
From what you report I suspect you are being banned by `fail2ban` for trying to authenticate too many times with an invalid user/pass. Have you setup an admin password with punctuation chars (e.g. `%`, `&`, `/`, `(`, `)`, etc..)? If so, I would try to setup a password with only letters and numbers, to see if that solves it.

**Comment by ghost** [comment]
My password is letters/numbers with no special characters. The
authentication failure comes at the first try after a complete partition
blowout, clean reinstallation of Debian and script installation as root of
the FreePBX modules.

**Comment by JoseGoncalves** [comment]
In that case, first check if stopping the `fail2ban` service (in a console perform `sudo systemctl stop fail2ban.service`), you can regain network access to your machine.
If that solves it, you'll need to investigate which `fail2ban` jail is causing your issue. 
After you start the `fail2ban.service` again, you can execute `sudo fail2ban-client status` to see the configured jails and afterwards `sudo fail2ban-client status <jail-name>` for each of the configured jails.

**Comment by kapilgupta01** [comment]
Hi @frankgmccoy did you tried the steps as suggested by @JoseGoncalves in previous comment? thanks
