### ISSUE TITLE
[bug] FPBX 17 no GUI  after activation and restart

### ISSUE THREAD

**Issue by JrapozaVT** [FreePBX/issue-tracker#478]
### FreePBX Version

FreePBX 17

### Issue Description

I have rebuilt the server several times, GUI initially comes up, however right after putting my deployment ID in for this server, and a reboot, GUI will not start. says out of memory caused an error.

### Operating Environment

Debian 12, Astrix 21  as per the current directions 10/4/2023

**Comment by msanthosh18** [comment]
can you run systemctl restart apache2 and check the GUI

**Comment by JrapozaVT** [comment]
Yes it comes back, until system is restarted

**Comment by JrapozaVT** [comment]
Is there a way to fix this?

**Comment by msanthosh18** [comment]
Hi @JrapozaVT 
Can you run below commands and give a try, it should fix it after reboot.

```
sed -i '/After=/ s/$/ freepbx.service/' /usr/lib/systemd/system/apache2.service
sed -i '/^After=apache2.service/d' /usr/lib/systemd/system/freepbx.service
systemctl daemon-reload
reboot
```

**Comment by JrapozaVT** [comment]
Thank you very much, that fixed it!

**Comment by JrapozaVT** [comment]
Is there a fix for the restapps not starting automatically?

**Comment by msanthosh18** [comment]
By default restapps will not start automatically, its expected.
required first time restart manually.

Thanks.

**Comment by JrapozaVT** [comment]
Thank you
