### ISSUE TITLE
[improvement]: Add setting allow_unauthenticated_options for accepting incoming OPTIONS on endpoints

### ISSUE THREAD

**Issue by blazestudios97** [FreePBX/issue-tracker#482]
### FreePBX Version

FreePBX 17

### Improvement Description

By default chan_pjsip will challenge an incoming OPTIONS message just as it would an INVITE. This can cause issues with an ITSP trying to issue OPTIONS for keepalive checks on trunk endpoints registered/associated with them.

Please add the ability to manage the PJSIP endpoint setting `allow_unauthenticated_options` and/or by default set `allow_unauthenticated_options=yes` for trunk endpoints in chan_pjsip.

**Comment by kapilgupta01** [comment]
core v17.0.18.2

**Comment by mjrider** [comment]
I think i found the issue with my problem which results in my trunk is not registering to our upstream

And it's related to this error
[2024-10-25 13:04:04] ERROR[1065511] config_options.c: Could not find option suitable for category 'freepbx-test' named 'allow_unauthenticated_options' at line 22 of /etc/asterisk/pjsip.registration.conf

If i remove the option allow_unauthenticated_options in the config, it works

- asterisk version 21
- core 17.0.18.4

Downgrading core to 17.0.18.1 removes the issue

@kguptasangoma if you want a new issue for a regression, please so and i'll create a new issue


Edit:

if i read the documentation here https://docs.asterisk.org/Asterisk_21_Documentation/API_Documentation/Module_Configuration/res_pjsip_outbound_registration/ that option should not be used there
