### ISSUE TITLE
[bug]: Minor typo in Applications > DISA

### ISSUE THREAD

**Issue by dannybeckett** [FreePBX/issue-tracker#484]
### FreePBX Version

FreePBX 16

### Issue Description

The help text for *Require Confirmation* is missing an `R` from the beginning:

![1](https://github.com/user-attachments/assets/c1a9949d-997f-4262-9a66-c7f5d206bc4e)

### Operating Environment

Current PBX Version: 16.0.40.11
Current System Version: 12.7.8-2306-1.sng7
DISA module version: 16.0.5

**Comment by kapilgupta01** [comment]
disa v17.0.6
