### ISSUE TITLE
[bug]: FreePBX 17 unable to restore from FreePBX16 backup

### ISSUE THREAD

**Issue by John22546** [FreePBX/issue-tracker#485]
### FreePBX Version

FreePBX 17

### Issue Description

Hello,

I recently set up FreePBX 17 on debian 12, when trying to restore a backup file that is 5.26GB the process appears to hang (left overnight and still the same message 8 hours later). When pressing the "play" button to start the restore in FreePBX 17 I get a pop up window with a message saying "Scanning the backup file. Please wait..." but the restore process never moves past this stage.

### Operating Environment

FreePBX 17 with Debian 12 OS
Backup 17.0.5.60
Framework 17.0.19.13
Core 17.0.17

**Comment by jissphilip** [comment]
Hi @John22546 Please try uploading this backup file to server and Restore via CLI command 
fwconsole backup --restore {yourbackupfilepathandname}
