### ISSUE TITLE
[bug]: asterisk-version-switch command stops in the middle

### ISSUE THREAD

**Issue by maccadoo** [FreePBX/issue-tracker#49]
### FreePBX Version

FreePBX 17

### Issue Description

When I try to use asterisk-version-switch to change the version of asterisk from 21 to 20LTS, the command stops in the middle

root@freepbx:~# asterisk-version-switch

        Current version:  Asterisk 21.0.2 is running

        (LTS) = Long Term Support | (EOL) = End of Life | (S) = Standard

        Press 1 for  Asterisk 18 (Currently not available, Please select other asterisk versions)
        Press 2 for  Asterisk 18 Certified (Currently not available, Please select other asterisk versions)
        Press 3 for  Asterisk 20 (LTS)
        Press 4 for  Asterisk 21 (S)

        Press q to exit and not change your Asterisk Version

This action below will cause Asterisk to stop and all calls in progress will be terminated

Please, select the Asterisk Version to change to : 3

--------------------------------------------------------------------------------------------------------------------------------

Started Core FastAGI Server. PID is 5987
Running Asterisk post from Endpoint module
Running Asterisk post from Ucp module
Starting UCP Node Server...
[->--------------------------] < 1 sec
Started UCP Node Server. PID is 6086
Regenerate FreePBX Dialplan...
Reload Started

In Setcid.class.php line 88:
                                                                                                                 
  Optional parameter $id declared before required parameter $dest is implicitly treated as a required parameter  
                                                                                                                 

reload [--json] [--dry-run] [--skip-registry-checks] [--dont-reload-asterisk]

### Operating Environment

debian_version  12.5

I ran the official patch and installed it.
https://github.com/FreePBX/sng_freepbx_debian_install

**Comment by kapilgupta01** [comment]
Please update the setcid module to the latest edge and try again. 

thanks

**Comment by maccadoo** [comment]
Thank you.
I have confirmed that asterisk-version-switch worked fine.
