### ISSUE TITLE
[bug]: Parking Pro cannot set the default parking lot as private nor delete the lot.

### ISSUE THREAD

**Issue by AshcorTech** [FreePBX/issue-tracker#490]
### FreePBX Version

FreePBX 16

### Issue Description

When working with the parking pro commecial module, I can create new lots, make them public or private and delete them.  However the original lot that was automatically created at system install cannot be made private nor be deleted.  

This causes problems with certain 3rd party parking apps as they will park calls in the public lot even when it's not the extensions assigned private lot.  That in and of itself is not necessarily a sangoma module problem but the issues abover are.

### Operating Environment

Observed in FreePBX Distro 15 and 16.  It should be noted that the Distro15 system had at one time been able to mark the default lot as private.  Thinking it may be a distro15 vs 16 issue I then marked that lot as public and tried to make it private again and it would not become private so it is displaying the same behavior now as Distro16

**Comment by chrsmj** [comment]
Generally, commercial module issues are handled via [Sangoma support](http://help.sangoma.com), and not via GitHub.

**Comment by kapilgupta01** [comment]
Hi 

You've opened a bug for a Commercial Module.

This Issue tracking system is for our Free and Open Source modules only.

Please open [a commercial support ticket [here](https://help.sangoma.com/)!.

If you are using FreePBX 12 or higher, please make sure you attach a Support Debug package (which is generated through the System Admin module) to the commercial support ticket.  Do not attach it to THIS bug tracker, as it may contain confidential information that will not be hidden from the general public.


Thank you for using FreePBX.
Kapil Gupta
