### ISSUE TITLE
[bug]: status of bug #464

### ISSUE THREAD

**Issue by mdemoulin** [FreePBX/issue-tracker#493]
### FreePBX Version

FreePBX 17

### Issue Description

I submitted this bug report 2 weeks ago and was told that backup version 17.0.5.61 would fix it. I still do not see that when I check in in Module Admin; when can I expect this to be released? Sorry if I violated norms and standards by entering a new bug report

### Operating Environment

Asterisk 21.4.3, FreePBXFreePBX 17.0.19.13

**Comment by kapilgupta01** [comment]
Backup v17.0.5.61 is now in stable, please try.
