### ISSUE TITLE
[bug]: Yealink T54W provision via EPM but not connect to OpenVPN

### ISSUE THREAD

**Issue by hastla007** [FreePBX/issue-tracker#494]
### FreePBX Version

FreePBX 16

### Issue Description

Yealink T54W provision via EPM but then not connect to OpenVPN - tested on various firmwares.

### Operating Environment

PBX Version:16.0.40.11
PBX Distro:12.7.8-2306-1.sng7
Asterisk Version:18.20.2

Endpoint Manager: 16.0.86.30

**Comment by kapilgupta01** [comment]
Hi 

You've opened a bug for a Commercial Module.

This Issue tracking system is for our Free and Open Source modules only.

Please open [a commercial support ticket [here](https://help.sangoma.com/)!.

If you are using FreePBX 12 or higher, please make sure you attach a Support Debug package (which is generated through the System Admin module) to the commercial support ticket.  Do not attach it to THIS bug tracker, as it may contain confidential information that will not be hidden from the general public.


Thank you for using FreePBX.
Kapil Gupta
