### ISSUE TITLE
Need to add these packages in v17 install script

### ISSUE THREAD

**Issue by girishmani1992** [FreePBX/issue-tracker#497]
### FreePBX Version

FreePBX 17

### Issue Description

Hi,

Need to add below packages in v17 install script for avahi-daemon to work properly in debian.

avahi-daemon 

avahi-utils 

libnss-mdns

 

 

 

Thanks

### Operating Environment

Debian 12, pbx 17

**Comment by kapilgupta01** [comment]
updated script with new packages. thanks
