### ISSUE TITLE
[bug]: Is the apt repositories wrong?

### ISSUE THREAD

**Issue by maccadoo** [FreePBX/issue-tracker#50]
### FreePBX Version

FreePBX 17

### Issue Description

I ran the patch of official freepbx and installed it.
https://github.com/FreePBX/sng_freepbx_debian_install

The patch added an apt repository, is this repository correct?

patch added
https://repo.mongodb.org/apt/ubuntu

to

The official mongodb website recommend
https://repo.mongodb.org/apt/debian

The official document
https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-debian/

### Operating Environment

debian_version 12.5

**Comment by maccadoo** [comment]
I rewrote line 215 of the batch file.
It's working correctly in my environment.

add-apt-repository -y -S "deb [ arch=${arch} ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" >> "$log" 2>&1

to

add-apt-repository -y -S "deb [ arch=${arch} ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/7.0 main" >> "$log" 2>&1

**Comment by maccadoo** [comment]
I'm sorry
I misunderstood how mongodb works.
Please tell me how to test if mongodb is working properly.

**Comment by ramarajan222** [comment]
you can log in to Mongo db cli using the below command.

`mongosh
`
check the database

`
show databases
`

**Comment by ramarajan222** [comment]
moving the jira to close, reopen if needed. thanks

**Comment by maccadoo** [comment]
Please do not close.

As mentioned in the Debian Wiki, if you add Ubuntu repositories to Debian, it becomes FrankenDebian and less stable.
https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

Whether to use ubuntu repositories or debian repositories should be discussed you and developers

I'm using the repositories of "http://repo.mongodb.org/apt/debian"
I ran the command you mentioned and it seems to work fine using debian's repositories
mongosh 
check the database
test> show databases
admin   40.00 KiB
config  12.00 KiB
local   72.00 KiB

Is there anything else I should know for sure?
