### ISSUE TITLE
[improvement]: Update FreePBX 17 framework/install.php to allow installation of Asterisk 22

### ISSUE THREAD

**Issue by reraikes** [FreePBX/issue-tracker#509]
### FreePBX Version

FreePBX 17

### Improvement Description

Add Asterisk 22 to the "Supported Asterisk versions" in framework/install.php in the FreePBX 17 branch.

**Comment by kapilgupta01** [comment]
framework v17.0.19.17

**Comment by reraikes** [comment]
Up and running on FreePBX 17 + Asterisk 22.0.0.

Thanks!
