### ISSUE TITLE
[bug]: Undefined array key

### ISSUE THREAD

**Issue by poltrian** [FreePBX/issue-tracker#51]
### FreePBX Version

FreePBX 17

### Issue Description

I have Undefined array key in some places. For example, in the user administration or under System Admin Https. If I want to work on extensions, I have to switch from German to English. I installed a Debian and then installed the beta with the installation script. With a backup I adopted the setting from PBX16 (Centos Distro version). Am I missing a PHP module or are these still errors that can occur in the beta?

### Operating Environment

Debian 12 and FreePBX 17 Beta 1,0

**Comment by jissphilip** [comment]
HI , 
Please give us more details about the error screenshots etc , 

We have already fixed some of the undefined key errors in many module , So please update all module to EDGE version and give a try

Thank you

**Comment by poltrian** [comment]
Thanks, new version of contactmanager and sysadmind solved the problems
