### ISSUE TITLE
[bug]: Unable to locate the FreePBX BMO Class 'Userman'

### ISSUE THREAD

**Issue by Tharun-PBX** [FreePBX/issue-tracker#513]
### FreePBX Version

FreePBX 16

### Issue Description

Issue description.

After installing the Free PBX, after few random days of use the UI got crashed not showing as "Unable to locate the FreePBX BMO Class 'Userman'A required module might be disabled or uninstalled. Recommended steps (run from the CLI): 1) fwconsole ma install userman 2) fwconsole ma enable userman "

But when I have followed these steps, it wasn't helping to resolve.

### Operating Environment

Created the freePBX server VM using 	ISO  SNG7-PBX-64bit-2104-1.iso
Guest OS
Other 3.x Linux (32-bit)

Compatibility
ESXi 6.7 virtual machine

output error : 

Exception: Unable to locate the FreePBX BMO Class 'Userman'A required module might be disabled or uninstalled. Recommended steps (run from the CLI): 1) fwconsole ma install userman 2) fwconsole ma enable userman in file /var/www/html/admin/libraries/BMO/Self_Helper.class.php on line 212
Stack trace:
  1. Exception->() /var/www/html/admin/libraries/BMO/Self_Helper.class.php:212
  2. FreePBX\Self_Helper->loadObject() /var/www/html/admin/libraries/BMO/Self_Helper.class.php:106
  3. FreePBX\Self_Helper->autoLoad() /var/www/html/admin/libraries/BMO/Self_Helper.class.php:37
  4. FreePBX\Self_Helper->__get() /var/www/html/admin/modules/faxpro/Faxpro.class.php:18
  5. FreePBX\modules\Faxpro->__construct() /var/www/html/admin/libraries/BMO/Self_Helper.class.php:124
  6. FreePBX\Self_Helper->autoLoad() /var/www/html/admin/libraries/BMO/Self_Helper.class.php:37
  7. FreePBX\Self_Helper->__get() /var/www/html/admin/libraries/BMO/FreePBX.class.php:105
  8. FreePBX->__callStatic() /var/www/html/admin/modules/faxpro/functions.inc.php:6
  9. FreePBX->Faxpro() /var/www/html/admin/modules/faxpro/functions.inc.php:6
 10. require_once() /var/www/html/admin/bootstrap.php:353
 11. require_once() /etc/freepbx.conf:11
 12. include_once() /var/lib/asterisk/bin/fwconsole:12
locale: Cannot set LC_CTYPE to default locale: No such file or directory
Exception: Unable to locate the FreePBX BMO Class 'Userman'A required module might be disabled or uninstalled. Recommended steps (run from the CLI): 1) fwconsole ma install userman 2) fwconsole ma enable userman in file /var/www/html/admin/libraries/BMO/Self_Helper.class.php on line 212
Stack trace:
  1. Exception->() /var/www/html/admin/libraries/BMO/Self_Helper.class.php:212
  2. FreePBX\Self_Helper->loadObject() /var/www/html/admin/libraries/BMO/Self_Helper.class.php:106
  3. FreePBX\Self_Helper->autoLoad() /var/www/html/admin/libraries/BMO/Self_Helper.class.php:37
  4. FreePBX\Self_Helper->__get() /var/www/html/admin/modules/faxpro/Faxpro.class.php:18
  5. FreePBX\modules\Faxpro->__construct() /var/www/html/admin/libraries/BMO/Self_Helper.class.php:124
  6. FreePBX\Self_Helper->autoLoad() /var/www/html/admin/libraries/BMO/Self_Helper.class.php:37
  7. FreePBX\Self_Helper->__get() /var/www/html/admin/libraries/BMO/FreePBX.class.php:105
  8. FreePBX->__callStatic() /var/www/html/admin/modules/faxpro/functions.inc.php:6
  9. FreePBX->Faxpro() /var/www/html/admin/modules/faxpro/functions.inc.php:6
 10. require_once() /var/www/html/admin/bootstrap.php:353
 11. require_once() /etc/freepbx.conf:11
 12. include_once() /var/lib/asterisk/bin/fwconsole:12

**Comment by kapilgupta01** [comment]
did you tried to install the userman module?

**Comment by kapilgupta01** [comment]
`fwconsole ma install userman`

**Comment by Tharun-PBX** [comment]
Yes but still seeing the same issue

**Comment by kapilgupta01** [comment]
does userman installed properly?

**Comment by Tharun-PBX** [comment]
After trying to install that using the above command, still I was seeing the below o/p

output error :

Exception: Unable to locate the FreePBX BMO Class 'Userman'A required module might be disabled or uninstalled. Recommended steps (run from the CLI): 1) fwconsole ma install userman 2) fwconsole ma enable userman in file /var/www/html/admin/libraries/BMO/Self_Helper.class.php on line 212
Stack trace:
