### ISSUE TITLE
[bug]: Error updating Endpoint module from 17.0.1.87 to 17.0.1.88

### ISSUE THREAD

**Issue by snowgoer1998** [FreePBX/issue-tracker#514]
### FreePBX Version

FreePBX 17

### Issue Description

Getting an error during the update that reads Undefined Array Key "nonSSL"
Have tried
- fwconsole ma upgradeall
- fwconsole ma downloadinstall endpoint
- fwconsole ma downloadinstall endpoint --tag 17.0.1.88

all have resulted in the same error as listed above

### Operating Environment

 Module              | Version    | Status                                 | License     | Signature |
+---------------------+------------+----------------------------------------+-------------+-----------+
| accountcodepreserve | 17.0.0.1   | Enabled                                | GPLv2       | Sangoma   |
| adv_recovery        | 17.0.4     | Enabled                                | Commercial  | Sangoma   |
| allowlist           | 17.0.1.1   | Enabled                                | GPLv3+      | Sangoma   |
| amd                 | 17.0.1     | Enabled                                | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1   | Enabled                                | GPLv3+      | Sangoma   |
| api                 | 17.0.1.6   | Enabled                                | AGPLv3+     | Sangoma   |
| areminder           | 17.0.3.10  | Enabled                                | Commercial  | Sangoma   |
| arimanager          | 17.0.1.1   | Enabled                                | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2     | Enabled                                | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2     | Enabled                                | GPLv3+      | Sangoma   |
| backup              | 17.0.5.61  | Enabled                                | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2   | Enabled                                | GPLv3+      | Sangoma   |
| broadcast           | 17.0.1.6   | Enabled                                | Commercial  | Sangoma   |
| builtin             |            | Enabled                                |             | Unsigned  |
| bulkhandler         | 17.0.5     | Enabled                                | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.20  | Enabled                                | GPLv3+      | Sangoma   |
| callaccounting      | 17.0.5     | Enabled                                | Commercial+ | Sangoma   |
| callback            | 17.0.2.1   | Enabled                                | GPLv3+      | Sangoma   |
| callerid            | 17.0.1     | Enabled                                | Commercial  | Sangoma   |
| callforward         | 17.0.1.6   | Enabled                                | AGPLv3+     | Sangoma   |
| calllimit           | 17.0.1.2   | Enabled                                | Commercial  | Sangoma   |
| callrecording       | 17.0.3.8   | Enabled                                | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4   | Enabled                                | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.22  | Enabled                                | GPLv3+      | Sangoma   |
| cdrpro              | 17.0.3.21  | Enabled                                | Commercial  | Sangoma   |
| cel                 | 17.0.2.10  | Enabled                                | GPLv3+      | Sangoma   |
| certman             | 17.0.3.13  | Enabled                                | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1   | Enabled                                | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2   | Enabled                                | GPLv3+      | Sangoma   |
| conferencespro      | 17.0.1.7   | Enabled                                | Commercial  | Sangoma   |
| configedit          | 17.0.1.4   | Enabled                                | AGPLv3+     | Sangoma   |
| contactmanager      | 17.0.5.12  | Enabled                                | GPLv3+      | Sangoma   |
| core                | 17.0.17    | Enabled                                | GPLv3+      | Sangoma   |
| cos                 | 17.0.1.1   | Enabled                                | Commercial  | Sangoma   |
| customappsreg       | 17.0.1     | Enabled                                | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.3   | Enabled                                | GPLv2+      | Sangoma   |
| dashboard           | 17.0.4.6   | Enabled                                | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1   | Enabled                                | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2   | Enabled                                | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1   | Enabled                                | GPLv3+      | Sangoma   |
| disa                | 17.0.6     | Enabled                                | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3   | Enabled                                | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.2   | Enabled                                | GPLv3+      | Sangoma   |
| endpoint            | 17.0.1.87  | Disabled; Pending upgrade to 17.0.1.88 | Commercial  | Sangoma   |
| extensionroutes     | 17.0.1     | Enabled                                | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1     | Enabled                                | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4   | Enabled                                | GPLv3+      | Sangoma   |
| faxpro              | 17.0.1.19  | Enabled                                | Commercial  | Sangoma   |
| featurecodeadmin    | 17.0.2     | Enabled                                | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.30  | Enabled                                | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.10  | Enabled                                | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.28  | Enabled                                | AGPLv3+     | Sangoma   |
| framework           | 17.0.19.16 | Enabled                                | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6   | Enabled                                | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1     | Enabled                                | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1.1   | Enabled                                | GPLv2+      | Sangoma   |
| ivr                 | 17.0.8     | Enabled                                | GPLv3+      | Sangoma   |
| languages           | 17.0.1     | Enabled                                | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3   | Enabled                                | GPLv3+      | Sangoma   |
| manager             | 17.0.6     | Enabled                                | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3     | Enabled                                | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1   | Enabled                                | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.2   | Enabled                                | GPLv3+      | Sangoma   |
| music               | 17.0.5     | Enabled                                | GPLv3+      | Sangoma   |
| outcnam             | 17.0.1     | Enabled                                | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1     | Enabled                                | GPLv3+      | Sangoma   |
| paging              | 17.0.3     | Enabled                                | GPLv3+      | Sangoma   |
| pagingpro           | 17.0.1.6   | Enabled                                | Commercial  | Sangoma   |
| parking             | 17.0.2.5   | Enabled                                | GPLv3+      | Sangoma   |
| parkpro             | 17.0.1.4   | Enabled                                | Commercial  | Sangoma   |
| pbxmfa              | 17.0.2.3   | Enabled                                | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1     | Enabled                                | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2   | Enabled                                | GPLv3+      | Sangoma   |
| pinsetspro          | 17.0.2     | Enabled                                | Commercial  | Sangoma   |
| pm2                 | 17.0.3.3   | Enabled                                | AGPLv3+     | Sangoma   |
| pms                 | 17.0.2.30  | Enabled                                | Commercial  | Sangoma   |
| presencestate       | 17.0.2.4   | Enabled                                | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2   | Enabled                                | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4   | Enabled                                | GPLv3+      | Sangoma   |
| queues              | 17.0.1.12  | Enabled                                | GPLv2+      | Sangoma   |
| queuestats          | 17.0.1.7   | Enabled                                | Commercial  | Sangoma   |
| qxact_reports       | 17.0.3     | Enabled                                | Commercial  | Sangoma   |
| recording_report    | 17.0.3.8   | Enabled                                | Commercial  | Sangoma   |
| recordings          | 17.0.2.3   | Enabled                                | GPLv3+      | Sangoma   |
| restapps            | 17.0.1.25  | Enabled                                | Commercial  | Sangoma   |
| ringgroups          | 17.0.2.6   | Enabled                                | GPLv3+      | Sangoma   |
| sangomaconnect      | 17.0.1.41  | Enabled                                | Commercial  | Sangoma   |
| sangomacrm          | 17.0.1.17  | Enabled                                | Commercial  | Sangoma   |
| sangomartapi        | 17.0.2.15  | Enabled                                | Commercial  | Sangoma   |
| setcid              | 17.0.1.2   | Enabled                                | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.9   | Enabled                                | AGPLv3+     | Sangoma   |
| sipstation          | 17.0.3.4   | Enabled                                | Commercial  | Sangoma   |
| sms                 | 17.0.1.15  | Enabled                                | Commercial  | Sangoma   |
| smsplus             | 17.0.3     | Enabled                                | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1   | Enabled                                | GPLv3+      | Sangoma   |
| superfecta          | 17.0.3.5   | Enabled                                | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.98  | Enabled                                | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.18  | Enabled                                | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1   | Enabled                                | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1     | Enabled                                | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.23  | Enabled                                | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.29  | Enabled                                | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2     | Enabled                                | GPLv3+      | Sangoma   |
| vmnotify            | 17.0.1.7   | Enabled                                | Commercial  | Sangoma   |
| voicemail           | 17.0.5.23  | Enabled                                | GPLv3+      | Sangoma   |
| voicemail_report    | 17.0.1.1   | Enabled                                | Commercial  | Sangoma   |
| voipinnovations     | 17.0.1.4   | Enabled                                | Commercial  | Sangoma   |
| vqplus              | 17.0.1.17  | Enabled                                | Commercial  | Sangoma   |
| weakpasswords       | 17.0.1     | Enabled                                | GPLv3+      | Sangoma   |
| webcallback         | 17.0.4     | Enabled                                | Commercial  | Sangoma   |
| webrtc              | 17.0.2.2   | Enabled                                | GPLv3+      | Sangoma 

### Relevant log output

```shell
root@stjudevoipserver:~# fwconsole ma upgradeall
No repos specified, using: [standard,commercial] from last GUI settings

Module(s) requiring upgrades: endpoint
Upgrading module 'endpoint' from 17.0.1.88 to 17.0.1.88
Downloading module 'endpoint'
Processing endpoint
Verifying local module download...Verified
Extracting...Done
Download completed in 5 seconds
Create symlink...Done
Checking database tables...Done
Migrating tables as required...Done
Checking Settings and Defaults...Done

In functions_sangoma.php line 1509:

  Undefined array key "nonssl"


moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [<args>...]

All upgrades completed successfully!
Updating Hooks...Done
Chowning directories...Done
```

**Comment by kapilgupta01** [comment]
endpoint v17.0.1.89
