### ISSUE TITLE
[improvement]: Add mailutils to 17 installer script

### ISSUE THREAD

**Issue by lgaetz** [FreePBX/issue-tracker#517]
### FreePBX Version

FreePBX 17

### Improvement Description

Previous fpbx distros have included the mailx rpm which allows use of the mail command for generating email from the bash prompt. It would be useful for backward compatibility if this remains supported in 17

```
root@FreePBX17:~# mail
-bash: mail: command not found

root@FreePBX17:~# apt install mailutils

root@FreePBX17:~# mail
No mail for root
```

**Comment by kapilgupta01** [comment]
Hey @lgaetz  

Done. Latest script will have this utility as well. 

Thanks
Kapil
