### ISSUE TITLE
[bug]: Queue Name - data too long for column descr

### ISSUE THREAD

**Issue by inferno-cc** [FreePBX/issue-tracker#518]
### FreePBX Version

FreePBX 17

### Issue Description

When using a longer description for a queue the system generates an error 'data too long for column descr'.
When it was an edit of a queue, it looks like the queue is being removed from the database after this error :(

https://github.com/user-attachments/assets/5a5b6423-aac4-4d2c-a0d9-38d002ac9d15

### Operating Environment

+-------------------+------------+-----------------------------------+------------+-----------+
| Module            | Version    | Status                            | License    | Signature |
+-------------------+------------+-----------------------------------+------------+-----------+
| announcement      | 17.0.2.1   | Enabled                           | GPLv3+     | Sangoma   |
| arimanager        | 17.0.1.1   | Enabled                           | GPLv3+     | Sangoma   |
| asterisk-cli      | 17.0.2     | Enabled                           | GPLv3+     | Sangoma   |
| asteriskinfo      | 17.0.2     | Enabled                           | GPLv3+     | Sangoma   |
| backup            | 17.0.5.60  | Enabled                           | GPLv3+     | Sangoma   |
| builtin           |            | Enabled                           |            | Unsigned  |
| bulkhandler       | 17.0.5     | Enabled                           | GPLv3+     | Sangoma   |
| calendar          | 17.0.4.20  | Enabled                           | GPLv3+     | Sangoma   |
| callforward       | 17.0.1.6   | Enabled                           | AGPLv3+    | Sangoma   |
| callrecording     | 17.0.3.7   | Enabled                           | AGPLv3+    | Sangoma   |
| callwaiting       | 17.0.3.4   | Enabled                           | GPLv3+     | Sangoma   |
| cdr               | 17.0.4.21  | Enabled                           | GPLv3+     | Sangoma   |
| cel               | 17.0.2.9   | Enabled                           | GPLv3+     | Sangoma   |
| certman           | 17.0.3.13  | Enabled                           | AGPLv3+    | Sangoma   |
| conferences       | 17.0.3.2   | Enabled                           | GPLv3+     | Sangoma   |
| configedit        | 17.0.1.4   | Enabled                           | AGPLv3+    | Sangoma   |
| contactmanager    |            | Not Installed (Locally available) | GPLv3+     | Sangoma   |
| core              | 17.0.17    | Enabled                           | GPLv3+     | Sangoma   |
| customappsreg     | 17.0.1     | Enabled                           | GPLv3+     | Sangoma   |
| customcontexts    | 17.0.1.3   | Enabled                           | GPLv2+     | Sangoma   |
| dashboard         | 17.0.4.5   | Enabled                           | AGPLv3+    | Sangoma   |
| daynight          | 17.0.1.1   | Enabled                           | GPLv3+     | Sangoma   |
| donotdisturb      | 17.0.2.3   | Enabled                           | GPLv3+     | Sangoma   |
| dynroute          | 17.0.3.2   | Enabled                           | GPLv3+     | Sangoma   |
| extensionsettings | 17.0.1     | Enabled                           | GPLv3+     | Sangoma   |
| fax               | 17.0.3.4   | Enabled                           | GPLv3+     | Sangoma   |
| featurecodeadmin  | 17.0.2     | Enabled                           | GPLv3+     | Sangoma   |
| filestore         | 17.0.2.30  | Enabled                           | AGPLv3     | Sangoma   |
| findmefollow      | 17.0.4.10  | Enabled                           | GPLv3+     | Sangoma   |
| firewall          | 17.0.1.26  | Enabled                           | AGPLv3+    | Sangoma   |
| framework         | 17.0.19.11 | Enabled                           | GPLv2+     | Sangoma   |
| infoservices      | 17.0.1.1   | Enabled                           | GPLv2+     | Sangoma   |
| ivr               | 17.0.8     | Enabled                           | GPLv3+     | Sangoma   |
| languages         | 17.0.1     | Enabled                           | GPLv3+     | Sangoma   |
| logfiles          | 17.0.3.3   | Enabled                           | GPLv3+     | Sangoma   |
| manager           | 17.0.6     | Enabled                           | GPLv2+     | Sangoma   |
| miscapps          | 17.0.3     | Enabled                           | GPLv3+     | Sangoma   |
| miscdests         | 17.0.1.1   | Enabled                           | GPLv3+     | Sangoma   |
| music             | 17.0.5     | Enabled                           | GPLv3+     | Sangoma   |
| paging            | 17.0.3     | Enabled                           | GPLv3+     | Sangoma   |
| parking           |            | Not Installed (Locally available) | GPLv3+     | Sangoma   |
| pm2               | 17.0.3.3   | Enabled                           | AGPLv3+    | Sangoma   |
| presencestate     | 17.0.2.4   | Enabled                           | GPLv3+     | Sangoma   |
| printextensions   | 17.0.1.2   | Enabled                           | GPLv3+     | Sangoma   |
| queues            | 17.0.1.12  | Enabled                           | GPLv2+     | Sangoma   |
| recordings        | 17.0.2.2   | Enabled                           | GPLv3+     | Sangoma   |
| ringgroups        | 17.0.2.4   | Enabled                           | GPLv3+     | Sangoma   |
| setcid            | 17.0.1.2   | Enabled                           | GPLv3+     | Sangoma   |
| sipsettings       | 17.0.6.9   | Enabled                           | AGPLv3+    | Sangoma   |
| soundlang         | 17.0.4.1   | Enabled                           | GPLv3+     | Sangoma   |
| sysadmin          | 17.0.1.96  | Enabled                           | Commercial | Sangoma   |
| timeconditions    | 17.0.1.18  | Enabled                           | GPLv3+     | Sangoma   |
| userman           | 17.0.6.27  | Enabled                           | AGPLv3+    | Sangoma   |
| voicemail         | 17.0.5.22  | Enabled                           | GPLv3+     | Sangoma   |
| weakpasswords     | 17.0.1     | Enabled                           | GPLv3+     | Sangoma   |
+-------------------+------------+-----------------------------------+------------+-----------+

**Comment by kapilgupta01** [comment]
queues v17.0.1.13
