### ISSUE TITLE
[bug]: Freepbx Core 17.0.18.4 Bug

### ISSUE THREAD

**Issue by VNP-PH** [FreePBX/issue-tracker#522]
### FreePBX Version

FreePBX 17

### Issue Description

Once you upgrade to this version 17.0.18.4 PJSIP Carrier Registration no longer works.  freepbx will no long try to register. 17.0.17 works fine before upgrade.

### Operating Environment

Debian 12.7

**Comment by jcolp** [comment]
This is a duplicate of #519
