### ISSUE TITLE
[bug]: Commercial EPM - Custom Extension Management - Allow duplicate extension numbers

### ISSUE THREAD

**Issue by jakthree** [FreePBX/issue-tracker#527]
### FreePBX Version

FreePBX 17

### Issue Description

Commercial Endpoint Manager (EPM): v17.0.1.88
Custom Ext Management (CEM)
This is a feature request and possible bug report.
Feature request: I would like to map the same remote extension number to multiple local phones.
Possible bug: I may have found an issue with using EPM – Extension Mapping – Add Extension: choosing ‘Custom Extension’ from the dropdown list will cause duplicate entries in the CEM list.

My example system:
I have PBX-1 (local extension numbers 1xxx) and PBX-2 (remote extension numbers 2xxx).
Settings note: Extension 1000 and 2000 – Advanced – Max Contacts is set to 4. I think this is how multiple indexes of the same extension are created. (i.e. 1000-1, 1000-2, 1000-3, 1000-4)

I have two phones located at PBX-1.
Phone-1 accounts
  1013-1
  1000-2
  2000
  
Phone-2 accounts 
  1063-1 <-different extension
  1000-3 <-same extension as phone-1 but different index
  2000    <-same custom extension as phone-1

I think it should be mentioned that the custom extension don’t have indexes.

Starting screenshot of EPM – Extension Mapping.
 ![image](https://github.com/user-attachments/assets/21daa714-42d8-4ba2-b6fa-5a3391cd1ffc)

Starting screenshot of CEM list before custom extension(s) created.
![image](https://github.com/user-attachments/assets/d7592339-5fbd-4e68-9c04-34a0203935b0)

Here are steps to reproduce the ‘bug’.
Use EPM – Add new extension - account-4 ending with MAC BF.
Select Custom Extension from the dropdown list. (last item in the list). Note that ext 2000 is not in the dropdown list.
Fill in the ‘Create Custom Extension’ popup form and click [Send]
![image](https://github.com/user-attachments/assets/f018578e-9cfa-4f3d-987b-55292c9b9798)

Screenshot of EPM mapping after adding first custom extension to MAC ending in BF.
![image](https://github.com/user-attachments/assets/768c0770-8c25-45db-85ae-d42548a03eda)

Screenshot of CEM list after adding the first custom extension to MAC ending in BF.
Note that a (custom) extension was added to MAC BF.
![image](https://github.com/user-attachments/assets/e61973db-3ad1-4e15-9f48-49513c0545e4)

Now - Repeat the above steps to add the second custom extension 2000 to account-4 of MAC ending in A5
Screenshot of EPM mapping after adding first custom extension to MAC ending in A5
![image](https://github.com/user-attachments/assets/5f940dae-8cc5-45d0-b5ac-568bf5e415e2)
Note that the (custom) mapping for MAC BF has been removed and a new (custom) is listed for MAC A5.

Screenshot of CEM list after adding second custom extension.
![image](https://github.com/user-attachments/assets/f56988aa-0fab-4bfe-8c13-eee0e6d3933f)
 
Bug? Now there are two 2000 extensions listed.
When I attempt to add a New Custom Extension in the CEM page, I get a warning that the Extension already exists.
There is no way to determine which entry in the list is the ‘live’ enter associated with MAC A5. Deleting either entry removes the EPM mapped entry for MAC A5.

Now for the feature request.
In Extensions - Advanced - Max Contacts controls how many endpoint can associate with that extension. I suggest that Custom Ext Management have a similar setting by adding an index to the extension number. Maybe something like this.
![image](https://github.com/user-attachments/assets/50a0f654-f098-4e4e-b5ce-37f92867aca2)
 
The result would be listed like this.
![image](https://github.com/user-attachments/assets/9146ed0e-8ed3-48a9-a147-c84758cc556b)

The phones account registration credential would still use the extension number and password. The custom extension entry would be unique because of the index. You will be able to tell which custom ext is associated with the EPM mapping.

Thank you,

### Operating Environment

+---------------------+------------+---------+-------------+-----------+
| Module              | Version    | Status  | License     | Signature |
+---------------------+------------+---------+-------------+-----------+
| accountcodepreserve | 17.0.0.1   | Enabled | GPLv2       | Sangoma   |
| adv_recovery        | 17.0.4     | Enabled | Commercial  | Sangoma   |
| allowlist           | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| amd                 | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| announcement        | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| api                 | 17.0.1.6   | Enabled | AGPLv3+     | Sangoma   |
| areminder           | 17.0.3.10  | Enabled | Commercial  | Sangoma   |
| arimanager          | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| asterisk-cli        | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| asteriskinfo        | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| backup              | 17.0.5.61  | Enabled | GPLv3+      | Sangoma   |
| blacklist           | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| broadcast           | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| builtin             |            | Enabled |             | Unsigned  |
| bulkhandler         | 17.0.5     | Enabled | GPLv3+      | Sangoma   |
| calendar            | 17.0.4.20  | Enabled | GPLv3+      | Sangoma   |
| callaccounting      | 17.0.5     | Enabled | Commercial+ | Sangoma   |
| callback            | 17.0.2.1   | Enabled | GPLv3+      | Sangoma   |
| callerid            | 17.0.1     | Enabled | Commercial  | Sangoma   |
| callforward         | 17.0.1.6   | Enabled | AGPLv3+     | Sangoma   |
| calllimit           | 17.0.1.2   | Enabled | Commercial  | Sangoma   |
| callrecording       | 17.0.3.8   | Enabled | AGPLv3+     | Sangoma   |
| callwaiting         | 17.0.3.4   | Enabled | GPLv3+      | Sangoma   |
| cdr                 | 17.0.4.22  | Enabled | GPLv3+      | Sangoma   |
| cdrpro              | 17.0.3.21  | Enabled | Commercial  | Sangoma   |
| cel                 | 17.0.2.10  | Enabled | GPLv3+      | Sangoma   |
| certman             | 17.0.3.13  | Enabled | AGPLv3+     | Sangoma   |
| cidlookup           | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| conferences         | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| conferencespro      | 17.0.1.7   | Enabled | Commercial  | Sangoma   |
| configedit          | 17.0.1.4   | Enabled | AGPLv3+     | Sangoma   |
| contactmanager      | 17.0.5.12  | Enabled | GPLv3+      | Sangoma   |
| core                | 17.0.17    | Enabled | GPLv3+      | Sangoma   |
| cos                 | 17.0.1.1   | Enabled | Commercial  | Sangoma   |
| customappsreg       | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| customcontexts      | 17.0.1.3   | Enabled | GPLv2+      | Sangoma   |
| dashboard           | 17.0.4.6   | Enabled | AGPLv3+     | Sangoma   |
| daynight            | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| dictate             | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| directory           | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| disa                | 17.0.6     | Enabled | AGPLv3+     | Sangoma   |
| donotdisturb        | 17.0.2.3   | Enabled | GPLv3+      | Sangoma   |
| dynroute            | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| endpoint            | 17.0.1.88  | Enabled | Commercial  | Sangoma   |
| extensionroutes     | 17.0.1     | Enabled | Commercial  | Sangoma   |
| extensionsettings   | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| fax                 | 17.0.3.4   | Enabled | GPLv3+      | Sangoma   |
| faxpro              | 17.0.1.19  | Enabled | Commercial  | Sangoma   |
| featurecodeadmin    | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| filestore           | 17.0.2.30  | Enabled | AGPLv3      | Sangoma   |
| findmefollow        | 17.0.4.10  | Enabled | GPLv3+      | Sangoma   |
| firewall            | 17.0.1.28  | Enabled | AGPLv3+     | Sangoma   |
| framework           | 17.0.19.16 | Enabled | GPLv2+      | Sangoma   |
| hotelwakeup         | 17.0.1.6   | Enabled | GPLv2       | Sangoma   |
| iaxsettings         | 17.0.1     | Enabled | AGPLv3      | Sangoma   |
| infoservices        | 17.0.1.1   | Enabled | GPLv2+      | Sangoma   |
| ivr                 | 17.0.8     | Enabled | GPLv3+      | Sangoma   |
| languages           | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| logfiles            | 17.0.3.3   | Enabled | GPLv3+      | Sangoma   |
| manager             | 17.0.6     | Enabled | GPLv2+      | Sangoma   |
| miscapps            | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| miscdests           | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| missedcall          | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| music               | 17.0.5     | Enabled | GPLv3+      | Sangoma   |
| outcnam             | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| outroutemsg         | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| paging              | 17.0.3     | Enabled | GPLv3+      | Sangoma   |
| pagingpro           | 17.0.1.6   | Enabled | Commercial  | Sangoma   |
| parking             | 17.0.2.5   | Enabled | GPLv3+      | Sangoma   |
| parkpro             | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| pbxmfa              | 17.0.2.3   | Enabled | Commercial+ | Sangoma   |
| phpinfo             | 17.0.1     | Enabled | GPLv2+      | Sangoma   |
| pinsets             | 17.0.3.2   | Enabled | GPLv3+      | Sangoma   |
| pinsetspro          | 17.0.2     | Enabled | Commercial  | Sangoma   |
| pm2                 | 17.0.3.3   | Enabled | AGPLv3+     | Sangoma   |
| pms                 | 17.0.2.30  | Enabled | Commercial  | Sangoma   |
| presencestate       | 17.0.2.4   | Enabled | GPLv3+      | Sangoma   |
| printextensions     | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| queueprio           | 17.0.1.4   | Enabled | GPLv3+      | Sangoma   |
| queues              | 17.0.1.12  | Enabled | GPLv2+      | Sangoma   |
| queuestats          | 17.0.1.7   | Enabled | Commercial  | Sangoma   |
| qxact_reports       | 17.0.3     | Enabled | Commercial  | Sangoma   |
| recording_report    | 17.0.3.8   | Enabled | Commercial  | Sangoma   |
| recordings          | 17.0.2.3   | Enabled | GPLv3+      | Sangoma   |
| restapps            | 17.0.1.25  | Enabled | Commercial  | Sangoma   |
| ringgroups          | 17.0.2.6   | Enabled | GPLv3+      | Sangoma   |
| sangomaconnect      | 17.0.1.41  | Enabled | Commercial  | Sangoma   |
| sangomacrm          | 17.0.1.17  | Enabled | Commercial  | Sangoma   |
| sangomartapi        | 17.0.2.15  | Enabled | Commercial  | Sangoma   |
| setcid              | 17.0.1.2   | Enabled | GPLv3+      | Sangoma   |
| sipsettings         | 17.0.6.9   | Enabled | AGPLv3+     | Sangoma   |
| sipstation          | 17.0.3.4   | Enabled | Commercial  | Sangoma   |
| sms                 | 17.0.1.15  | Enabled | Commercial  | Sangoma   |
| smsplus             | 17.0.3     | Enabled | Commercial  | Sangoma   |
| soundlang           | 17.0.4.1   | Enabled | GPLv3+      | Sangoma   |
| superfecta          | 17.0.3.5   | Enabled | GPLv2+      | Sangoma   |
| sysadmin            | 17.0.1.98  | Enabled | Commercial  | Sangoma   |
| timeconditions      | 17.0.1.18  | Enabled | GPLv3+      | Sangoma   |
| tts                 | 17.0.1.1   | Enabled | GPLv3+      | Sangoma   |
| ttsengines          | 17.0.1     | Enabled | AGPLv3      | Sangoma   |
| ucp                 | 17.0.4.23  | Enabled | AGPLv3+     | Sangoma   |
| userman             | 17.0.6.29  | Enabled | AGPLv3+     | Sangoma   |
| vmblast             | 17.0.2     | Enabled | GPLv3+      | Sangoma   |
| vmnotify            | 17.0.1.7   | Enabled | Commercial  | Sangoma   |
| voicemail           | 17.0.5.23  | Enabled | GPLv3+      | Sangoma   |
| voicemail_report    | 17.0.1.1   | Enabled | Commercial  | Sangoma   |
| voipinnovations     | 17.0.1.4   | Enabled | Commercial  | Sangoma   |
| vqplus              | 17.0.1.17  | Enabled | Commercial  | Sangoma   |
| weakpasswords       | 17.0.1     | Enabled | GPLv3+      | Sangoma   |
| webcallback         | 17.0.4     | Enabled | Commercial  | Sangoma   |
| webrtc              | 17.0.2.2   | Enabled | GPLv3+      | Sangoma   |
+---------------------+------------+---------+-------------+-----------+

**Comment by kapilgupta01** [comment]
Hi 

You've opened a bug for a Commercial Module.

This Issue tracking system is for our Free and Open Source modules only.

Please open [a commercial support ticket [here](https://help.sangoma.com/)!.

If you are using FreePBX 12 or higher, please make sure you attach a Support Debug package (which is generated through the System Admin module) to the commercial support ticket.  Do not attach it to THIS bug tracker, as it may contain confidential information that will not be hidden from the general public.


Thank you for using FreePBX.
Kapil Gupta

**Comment by jakthree** [comment]
kguptasangoma,
I understand better the difference between the free and commercial modules.
Is opening a commercial support ticket and opening a Sangoma help center case the same thing?
I opened a help center case. The support case worker told me send an email to featurerequests@sangoma.com and then closed the case. I sent the email, but don't know what the next step is. I will just wait and see what happens.
Thank you for you help,

**Comment by kapilgupta01** [comment]
Hi @jakthree please send me your support ticket number to kgupta@sangoma.com thanks

**Comment by jakthree** [comment]
kgupta,
I sent an email to kgupta@sangoma.com with the Sangoma case number and other information.
Thank you,
