### ISSUE TITLE
[bug]: Undefined array key "contactmanager_dialinglocale"

### ISSUE THREAD

**Issue by poltrian** [FreePBX/issue-tracker#54]
### FreePBX Version

FreePBX 17

### Issue Description

Go to Administrator/ User Management, select a User and hit Send User Email again
var/www/html/admin/modules/contactmanager/Contactmanager.class.php

        public function usermanUpdateUser($id, $display, $data) {
            if($display == 'userman') {
                if(!empty($_POST['contactmanager_showingroups'])) {
                    $grps = !in_array("*",$_POST['contactmanager_showingroups']) ? $_POST['contactmanager_showingroups'] : array("*");
                    $grps = in_array("false",$_POST['contactmanager_showingroups']) ? array('false') : $grps;
                    $this->freepbx->Userman->setModuleSettingByID($id,'contactmanager','showingroups',$grps);
                } else {
                    $this->freepbx->Userman->setModuleSettingByID($id,'contactmanager','showingroups',null);
                }
                if(!empty($_POST['contactmanager_groups'])) {
                    $grps = !in_array("*",$_POST['contactmanager_groups']) ? $_POST['contactmanager_groups'] : array("*");
                    $grps = in_array("false",$_POST['contactmanager_groups']) ? array('false') : $grps;
                    $this->freepbx->Userman->setModuleSettingByID($id,'contactmanager','groups',$grps);
                } else {
                    $this->freepbx->Userman->setModuleSettingByID($id,'contactmanager','groups',null);
                }
                if(isset($_POST['contactmanager_image'])) {
                    $this->updateImageByID($id, $_POST['contactmanager_image'], (($_POST['contactmanager_gravatar']??'') == "on" ? 1 : 0), 'internal');
                }
                $this->setConfig('userLocale', $_POST['contactmanager_dialinglocale'], $id);
     
                $enableFavoriteContacts = $this->getEnableFavoriteContacts();
                $favoriteContactListId = '';
                if($enableFavoriteContacts) {
                    $favoriteContactListId = $_POST['favorite_contact'] == 'inherit' ? null : $_POST['favorite_contact'];
                }
                $this->freepbx->Userman->setModuleSettingByID($id,'contactmanager','favorite_contact_list_id',$favoriteContactListId);
            }
     
            $showingroups = $this->freepbx->Userman->getCombinedModuleSettingByID($id,'contactmanager','showingroups');
            $showingroups = is_array($showingroups) ? $showingroups : array();
            $groups = $this->getGroups();
            $groupIds = [];
            foreach ($groups as $group) {
                if ($group['type'] != 'internal') {
                    continue;
                }
                $groupIds[] = $group['id'];
                if (in_array($group['id'],$showingroups) || in_array("*",$showingroups)) {
                    $data['user'] = $id;

Arguments

    "Undefined array key "contactmanager_dialinglocale""

### Operating Environment

Debian 12 installed FREEPBX with Script

**Comment by jissphilip** [comment]
contactmanager-17.0.5.6

**Comment by poltrian** [comment]
How can i update?

**Comment by jissphilip** [comment]
fwconsole ma downloadinstall contactmanager --tag 17.0.5.6
