### ISSUE TITLE
[bug]: fwconsole: command not found

### ISSUE THREAD

**Issue by NeoLich** [FreePBX/issue-tracker#540]
### FreePBX Version

FreePBX 17

### Issue Description

Fresh install of Debian on a VM following instructions on website copied the install commands and ran them as root.  Script ran and installed FreePbx and told me it was successful.  fwconsole command did not work I got bash: fwconsole: command not found.   Looking back through the logs I found that fwconsole is in /usr/sbin/ but that was not part of my PATH so I added it to fix the issue. My issue is fixed but figured it might be a bug so I submitted this.

### Operating Environment

PBX Version: 17.0.19.16
PBX Distro: 12.7.8-2408-1.sng12
Asterisk Version: 21.5.0
VM OS: Debian GNU/Linux 12
Kernel: Linux 6.1.0-27-amd64

**Comment by si458** [comment]
just had exact same issue here
https://community.freepbx.org/t/freepbx-17-problems-feedback/96745
fwconsole is located inside `/sbin` and `/sbin` isnt being added to the `$PATH` value
i believe the setup script for freepbx 17 SHOULD do this but they dont which seems very werid?

**Comment by si458** [comment]
i spoke too soon `/sbin` gets added to path by default for `root` users
so simple running `sudo fwconsole` fixes the issue :)

**Comment by NeoLich** [comment]
I checked my path as root and my user and neither had /usr/sbin as a path even logged in to root it couldn't find fwconsole until I added sbin

**Comment by si458** [comment]
@NeoLich `fwconsole` is located inside `/sbin` and i found only my root user had that path set in `$path`

**Comment by kapilgupta01** [comment]
Installation script is setting the root PATH. Ref - https://github.com/FreePBX/sng_freepbx_debian_install/blob/master/sng_freepbx_debian_install.sh#L31

For any individual system specific user, i think you may need to manually copy/set the same path.
