### ISSUE TITLE
[bug]: SQLSTATE[HY000] [2002]

### ISSUE THREAD

**Issue by 1darcio** [FreePBX/issue-tracker#544]
### FreePBX Version

FreePBX 16

### Issue Description

SQLSTATE[HY000] [2002] No such file or directory::SQLSTATE[HY000] [2002] No such file or directory

### Operating Environment

How can I fix it

### Relevant log output

```shell
/var/www/html/admin/libraries/utility.functions.php
        return version_compare($version1, $version2);
    }
}
 
function compress_framework_css() {
    compress::web_files();
}
 
/**
 * Throw FreePBX DIE Message
 * @param string $text The message
 * @param string $extended_text The Extended Message (Optional)
 * @param string $type The message type (Optional)
 */
function die_freepbx($text, $extended_text="", $type="FATAL") {
    if(is_object($extended_text) && method_exists($extended_text,"getMessage")) {
        $e = $extended_text;
        $extended_text = htmlentities($e->getMessage());
        $code = $e->getCode();
        throw new \Exception($text . "::" . $extended_text,$code,$e);
    } else {
        $extended_text = htmlentities($extended_text);
        throw new \Exception($text . "::" . $extended_text);
    }
```

**Comment by kapilgupta01** [comment]
please check if mariadb is running properly.

**Comment by 1darcio** [comment]
Sorry but I don't know how. Could it may be problem with disk space?

**Comment by kapilgupta01** [comment]
it could be so please check "df -h" from your linux terminal.

`service mariadb status` to see the status of the process from linux terminal.

**Comment by kapilgupta01** [comment]
Hi, 

This appears to be a support issue. 

This system is setup for bug tracking only and does not handle support request or general questions.

If this is a PBXact issue or related to a commercial product, please open a support ticket at  https://help.sangoma.com/

For FreePBX support or general questions, you have the following options:

Self Service:
https://sangomakb.atlassian.net/wiki/spaces/FP/overview
Community Forums with search
http://community.freepbx.org  
Paid support.
https://help.sangoma.com/

Thank you for using FreePBX
Kapil Gupta

**Comment by 1darcio** [comment]
Only one question. Am I right that there is problem with disk space:

root@raspbx:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       3.5G  3.3G     0 100% /
devtmpfs        431M     0  431M   0% /dev
tmpfs           463M     0  463M   0% /dev/shm
tmpfs           463M   13M  451M   3% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           463M     0  463M   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   54M  199M  22% /boot
tmpfs            93M     0   93M   0% /run/user/0

**Comment by kapilgupta01** [comment]
Filesystem Size Used Avail Use% Mounted on
/dev/root 3.5G 3.3G 0 100% /

yes its full disk

**Comment by 1darcio** [comment]
Now all is OK, thank You for Your help :-).
