### ISSUE TITLE
[bug]: Backup Maintenance is not working. Old backup is not deleted.

### ISSUE THREAD

**Issue by rkaviya-sangoma** [FreePBX/issue-tracker#546]
### FreePBX Version

FreePBX 17

### Issue Description

Hi, 
We are facing an issue with latest backup module. When the maintenance’s triggers, the old backup file is not deleted. 
 We have set the config Append Backup Name as a directory to the Storage path” set to YES. And still those files are not deleted. 

### Operating Environment

FreePBX version: 17.0.19.17
Backup module: 17.0.5.61

**Comment by shahinco** [comment]
Hi Guys, 

Here i recognized another issue.. when i made change in a Backup Module. 
`**_Append Backup Name as a directory to the Storage path_**` --> YES  to NO 

the next backup run deleted backup file from another Directory. 

YES
`root@freepbx-17:/var/spool/asterisk/backup/FullBackup# ls -la
total 164832
drwx------ 2 asterisk asterisk     4096 Nov 18 11:16 .
drwxrwxr-x 3 asterisk asterisk     4096 Nov 18 10:42 ..
-rw-r--r-- 1 asterisk asterisk 84389799 Nov 18 11:15 20241118-111540-1731928540-17.0.19.17-90406580.tar.gz
-rw-r--r-- 1 asterisk asterisk 84389788 Nov 18 11:16 20241118-111638-1731928598-17.0.19.17-1938234082.tar.gz`

After changed to NO and 1st backup one file gone. 
`root@freepbx-17:/var/spool/asterisk/backup/FullBackup# ls -la
total 82420
drwx------ 2 asterisk asterisk     4096 Nov 18 11:31 .
drwxrwxr-x 3 asterisk asterisk     4096 Nov 18 11:31 ..
-rw-r--r-- 1 asterisk asterisk 84389788 Nov 18 11:16 20241118-111638-1731928598-17.0.19.17-1938234082.tar.gz`

This is unexpected and not wanted delete. 

Shahin

**Comment by kapilgupta01** [comment]
filestore v17.0.2.32
backup v17.0.5.62
