### ISSUE TITLE
[bug]: Whoops\Exception\ErrorException: Optional parameter $name declared before required parameter $foreign_name is implicitly treated as a required parameter in file /var/www/html/admin/modules/directory/functions.inc.php on line 284

### ISSUE THREAD

**Issue by LionSprings** [FreePBX/issue-tracker#55]
### FreePBX Version

FreePBX 17

### Issue Description

function directory_draw_entries_tr($id, $realid, $name = '',$foreign_name, $audio = '',$num = '',$e_id = '', $reuse_audio = false, $dataname = null){
need to change to 
function directory_draw_entries_tr($id, $realid, $name = '', $foreign_name = '', $audio = '',$num = '',$e_id = '', $reuse_audio = false, $dataname = null){
because old style is deprecated in PHP8 (https://www.php.net/manual/en/migration80.deprecated.php)

### Operating Environment

Debian12.5, FreePBX 17.0.15.8 

### Relevant log output

```shell
Whoops\Exception\ErrorException: Optional parameter $name declared before required parameter $foreign_name is implicitly treated as a required parameter in file /var/www/html/admin/modules/directory/functions.inc.php on line 284
Stack trace:
  1. Whoops\Exception\ErrorException->() /var/www/html/admin/modules/directory/functions.inc.php:284
  2. Whoops\Run->handleError() /var/www/html/admin/bootstrap.php:353
  3. require_once() /var/www/html/admin/bootstrap.php:353
  4. require_once() /etc/freepbx.conf:10
  5. include_once() /var/lib/asterisk/bin/fwconsole:12
```

**Comment by prasanthcode4** [comment]
@LionSprings in which version found the above issue? I verified that the code in version 17 is correct, but the mentioned line number appears in version 16, kindly confirm.

**Comment by LionSprings** [comment]
Where I can see a necessary information for you? It installed automatically with the script. May be it still stay inside of some .deb package?

**Comment by LionSprings** [comment]
I found it in the module admin 
Directory 16.0.3 "Enabled and up to date"
but I didn't have any upgrade options, Only "Force Download and Install 16.0.3"

**Comment by LionSprings** [comment]
Next, I downloaded the directory module  and manually replaced it in /var/www/html/admin/modules. After that I saw "upgrade to 17.0.1" in the admin interface. I did it and now I see "Module "Directory" is unsigned and should be re-downloaded" warning.

**Comment by LionSprings** [comment]
I solved the issue by
fwconsole ma downloadinstall directory --tag 17.0.1 --force
and now everything is ok

**Comment by prasanthcode4** [comment]
@LionSprings Thank you for the confirmation

**Comment by RapidTransit** [comment]
I ran into this issue with a fresh debian install and following the instructions at: https://www.freepbx.org/freepbx-17-official-debian-install-beta/

Not sure how to fix it.
