### ISSUE TITLE
[bug]: UCP incorrectly shows enabled/disabled state of call forwarding to extension 0

### ISSUE THREAD

**Issue by nvsystems** [FreePBX/issue-tracker#550]
### FreePBX Version

FreePBX 17

### Issue Description

Call forwarding in UCP does not properly show the call forwarding button as enabled if the destination of the call forwarding is set to 0.
My guess is that the destination "0" is evaluated as "false" or "null" due to a coding issue and therefor the button is set to state off despite the call forwarding actually being enabled.

A very quick way to reproduce:
Create an extension 0 as "Misc Application" with with Destination "Terminate Call / Put caller on hold forever". Now log into UCP for any user and make a call forwarding to 0 => buttons shows enabled for a short time and then a second or so later switches to disabled even though the call forwarding actually remains active (which I can for example see on the phone BLF state for the forwarding).

I think the problem is likely somewhere in [callforward-release-17.0/ucp/assets/global.js](https://github.com/FreePBX/callforward/blob/release/17.0/ucp/assets/js/global.js) or in https://github.com/FreePBX/callforward/blob/release/17.0/ucp/Callforward.class.php
but I have trouble fully understanding the code. The general comparison "var state = (number !== false);`" in the javascript seems correct since !== should not evaluate 0 as false... But somewhere there must be some code that redraws the widget and falsely evaluates a destination of 0 to be false or invalid. I can't find it though.

### Operating Environment

FreePBX 17 (fresh installation) on Debian, but this bug was already present in FreePBX 16 with the FreePBX Distro.

**Comment by kapilgupta01** [comment]
callforward v17.0.1.7

**Comment by nvsystems** [comment]
Thank you very much, greatly appreciated. Amazing job of finding the root cause!
