### ISSUE TITLE
[bug]: Asterisks Does Not Start

### ISSUE THREAD

**Issue by TreeMonkey82** [FreePBX/issue-tracker#557]
### FreePBX Version

FreePBX 17

### Issue Description

I have spent all day installing FreePBX 17 from scratch and this happens every time. I have been building on Linode and Vulture. First thing I notice is after a clean install Restapps has not started. You can of course start it by typing fwconsole start restapps. Once firewall and everything is set up, do a reboot and asterisks fails to start. Even after I start Asterisks, Apache fails to start as well. These are on clean installs. 

### Operating Environment

FreePBX 17.0.19.17

**Comment by chrsmj** [comment]
How much RAM ?

**Comment by bonyakevich-e** [comment]
Have the same issue. After system reboot FreePBX says "Cannot Connect to Asterisk" and:
```
root@SRV-EST-FPBX-01:~# systemctl status freepbx
○ freepbx.service - FreePBX VoIP Server
     Loaded: loaded (/lib/systemd/system/freepbx.service; enabled; preset: enabled)
     Active: inactive (dead)
```
Сlean installation except for the firewall being disabled (because it breaks the connection during its initial configuration)

PBX Version: 17.0.19.17

RAM: 
```
root@SRV-EST-FPBX-01:~# free -h
               total        used        free      shared  buff/cache   available
Mem:            31Gi       1.0Gi        30Gi        21Mi       340Mi        30Gi
Swap:          975Mi          0B       975Mi
```

**Comment by kapilgupta01** [comment]
We are here talking about 2 different issues.

Hi @bonyakevich-e  "Cannot Connect to Asterisk" please ensure your ARI settings are good and asterisk is running fine ? Is this you are facing on every single reboot of the system ? 

Hi @TreeMonkey82  After reboot, are you seeing apache is failed to start or asterisk failed to start ?

anycase, please see the log to find out why its fail to start ?

**Comment by bonyakevich-e** [comment]
Hi @kguptasangoma. I don't know what to say about "ARI settings are good" but "Enable the Asterisk REST Interface" is set to NO in Advanced Settings. Asterisk isn't running. It appears 2 out of 3 times. And the remaining one FreePBX/Asterisk starts successfully, but apache2 doesn't. So sometimes I have to enter `fwconsole start` and sometimes `systemctl start apache2` to make it work

**Comment by kapilgupta01** [comment]
Hi @bonyakevich-e please ensure freepbx.service file do not have "After:apache2.service" and apache2service file has "After:freepbx.service" , this will fix your apache2 start issue. 
also, whenever you see service not starting, please check `/var/log/syslog` to find out the reason for the failure.

**Comment by bonyakevich-e** [comment]
@kguptasangoma. Yes, there were these options in both files. I removed them and it seems it solved the problems with freepbx and apache2 as well! I rebooted the system four times and everything started automatically. I'll keep monitoring and if the problem returns, I'll give you feedback. Thank you!

**Comment by kapilgupta01** [comment]
hi @TreeMonkey82 please check `/var/log/syslog` to see what kind of error you are getting? for apache2 please refer to previous comments. thanks

**Comment by PVasileff** [comment]
I am experiencing a similar issue. Upon restart, sometimes Apache does not start correctly, and other times it’s Asterisk. I added Monit to monitor the Apache server’s PID file, and if it is not present, it restarts Apache. 
When checking the monit log, I sometimes see the following entries:

```
[2024-11-25T21:36:44+0200] error    : 'apache2' failed to start (exit status 1) -- '/bin/systemctl start apache2': Failed to start apache2.service: Transaction order is cyclic. See system logs for details.
See system logs and 'systemctl status apache2.service' for details.
```
from journalctl
For Apache2:
```
# journalctl -u apache2
Nov 22 14:07:42 pbx systemd[1]: apache2.service: Found ordering cycle on freepbx.service/stop
Nov 22 14:07:42 pbx systemd[1]: apache2.service: Found dependency on apache2.service/stop
Nov 22 14:07:42 pbx systemd[1]: apache2.service: Job freepbx.service/stop deleted to break ordering cycle starting with apache2.service/stop
```
for freepbx service:
```
Nov 22 14:07:42 pbx systemd[1]: apache2.service: Found ordering cycle on freepbx.service/stop
Nov 22 14:07:42 pbx systemd[1]: apache2.service: Found dependency on apache2.service/stop
Nov 22 14:07:42 pbx systemd[1]: apache2.service: Job freepbx.service/stop deleted to break ordering cycle starting with apache2.service/stop
```
I suspect the issues are related and assume it might be connected to the systemd script created for FreePBX.
I have reviewed the logs, and there are no entries indicating memory exhaustion on the server.

Debian 12.8
FreePBX 17.0.19.17

I reviewed the freepbx service file located at: /lib/systemd/system/freepbx.service 
and changed it from:

```
[Unit]
Description=FreePBX VoIP Server
After=mariadb.service
After=apache2.service
After=network-online.target
Wants=network-online.target
 
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/fwconsole start
ExecStop=/usr/sbin/fwconsole stop
 
[Install]
WantedBy=multi-user.target

```
to:

```
[Unit]
Description=FreePBX VoIP Server
After=mariadb.service network-online.target
Wants=mariadb.service network-online.target
 
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/fwconsole start
ExecStop=/usr/sbin/fwconsole stop
 
[Install]
WantedBy=multi-user.target

```
Currently, upon restarting the server, both services seem to start correctly.

**Comment by kapilgupta01** [comment]
yes , modification you did is the right fix. 
we have plan to deploy new freepbx rpm which will take care of this.
