### ISSUE TITLE
I have the same issue. I just installed FreePBX 17 on Debian 12, and in Reports -> Asterisk Info, I see these two Channels (see the screenshot).

### ISSUE THREAD

**Issue by PVasileff** [FreePBX/issue-tracker#559]
I have the same issue. I just installed FreePBX 17 on Debian 12, and in Reports -> Asterisk Info, I see these two Channels (see the screenshot).
Could you please let me know if this is a bug? Should I be concerned about it, and is there a way to fix it myself?

![freepbx17](https://github.com/user-attachments/assets/a98d9e70-3697-466d-a7f6-f805a8afc5f7)

_Originally posted by @PVasileff in https://github.com/FreePBX/issue-tracker/issues/61#issuecomment-2493948659_

**Comment by kapilgupta01** [comment]
please find the explanation in below comment as well.

https://github.com/FreePBX/issue-tracker/issues/61#issuecomment-2074611517

if you do not want dpma then please unload res_digium_phone_module (i think this is the same AFAIR)
