### ISSUE TITLE
[bug]:   Whoops\Exception\ErrorException (E_WARNING) Undefined array key "general"

### ISSUE THREAD

**Issue by poltrian** [FreePBX/issue-tracker#56]
### FreePBX Version

FreePBX 17

### Issue Description

There is still an error in the German language setting, the extensions.
Try to edit an extension in the German language setting and the following error occurs

  Whoops\Exception\ErrorException (E_WARNING)
Undefined array key "allgemein"

/var/www/html/admin/modules/core/views/extensions.php

    <div class="display no-border">
      <form class="popover-form fpbx-submit" id="frm_extensions" onsubmit="return frm_extensions_onsubmit(this);" name="frm_extensions" action="config.php?display=extensions<?php echo isset($_REQUEST['extdisplay']) && freepbx_trim ($_REQUEST['extdisplay']) != '' ? '&amp;extdisplay='.$_REQUEST['extdisplay'] : '' ?>" method="post" data-fpbx-delete="config.php?display=extensions&amp;extdisplay=<?php echo $_REQUEST['extdisplay'] ?>&amp;action=del" role="form">
        <?php foreach ( $html['top'] as $elem ) {
          echo $elem['html'];
        } ?>
        <?php foreach ( $html['bottom'] as $elem ) {
          echo $elem['html'];
        } ?>
        <div role="tabpanel">
          <div class="nav-container">
            <div class="scroller scroller-left"><i class="fa fa-chevron-left"></i></div>
            <div class="scroller scroller-right"><i class="fa fa-chevron-right"></i></div>
            <div class="wrapper">
              <ul class="nav nav-tabs list" role="tablist">
                <?php foreach(array_keys($html['middle']) as $category) { ?>
                                <?php $hidden = (isset($hideCategory) && is_array($hideCategory) && in_array($category,$hideCategory)) ? "hidden" : ""?>
                  <li data-name="<?php echo strtolower($category)?>" class="change-tab <?php echo ($active == strtolower($category)) ? 'active' : ''?> <?php echo $hidden?>"><a href="#<?php echo strtolower($category)?>" aria-controls="<?php echo strtolower($category)?>" role="tab" data-toggle="tab"><?php echo $tabtranslations[$category]?></a></li>
                <?php } ?>
              </ul>
            </div>
          </div>
          <div class="tab-content display">
            <?php foreach($html['middle'] as $category => $sections) { ?>
              <div id="<?php echo strtolower($category)?>" role="tabpanel" class="tab-pane <?php echo ($active == strtolower($category)) ? 'active' : ''?>">
                <div class="container-fluid">
                  <?php foreach($sections as $section => $elements) { ?>
                    <div class="section-title" data-for="<?php echo strtolower($category)."_".strtolower($section)?>"><h3><i class="fa fa-minus"></i> <?php echo $section?></h3></div>
                    <div class="section" data-id="<?php echo strtolower($category)."_".strtolower($section)?>">
                      <?php foreach($elements as $elem) { ?>
                        <div class="element-container">
                          <?php if(!empty($elem['prompttext'])) {?>
                            <div class="row">
                              <div class="col-md-12">
                                <div class="row">
                                  <div class="form-group">
                                    <div class="col-md-4 control-label">
                                      <label for="<?php echo $elem['name']?>"><?php echo $elem['prompttext']?></label>
                                      <?php if(!empty($elem['helptext'])) { ?>
                                        <i class="fa fa-question-circle fpbx-help-icon" data-for="<?php echo $elem['name']?>"></i>
                                      <?php } ?>

Arguments

    "Undefined array key "allgemein""

### Operating Environment

Debian 12 FreePBX 17 Beta

**Comment by prasanthcode4** [comment]
@poltrian unable to reproduce the issue on the development system. Could you please send a screenshot of the error along with the module version?

**Comment by poltrian** [comment]
@prasanthcode4 

You have to switch to german at right corner before you edit an Exception

[
![Unbenannt](https://github.com/FreePBX/issue-tracker/assets/50879520/f3268a43-d5d2-495f-b522-41c44386b541)
](url)

**Comment by jissphilip** [comment]
Fix : core version 17.0.9.31

This module has been published and is now in the "edge" track

To enable the edge track, go to “Advanced settings and set “Set Module Admin to Edge mode” to “Yes”

Then go to module admin and click "Check Online". Note this will show updates for ALL modules in the edge track. Update the module(s) relevant to your issue.

Once finished go to “Advanced settings and set “Set Module Admin to Edge mode” to “No”

You may also upgrade from the command line with "fwconsole ma --edge upgrade MODULENAME"
replacing MODULENAME with the modules rawname which can be seen in "fwconsole ma list"

Please feel free to test and verify your issue is fixed.

**Comment by poltrian** [comment]
Thanks, fixed is for me!
