### ISSUE TITLE
[bug]: fwconsole bulkimport not working with Contact Manager

### ISSUE THREAD

**Issue by fleptino** [FreePBX/issue-tracker#560]
### FreePBX Version

FreePBX 17

### Issue Description

When I try to import contacts with bulk manager in the web modules I have no problems. When I try it with command line, it is not working. I couldn't figure out any type to choose:

fwconsole bi --type=contacts --replace /root/kwh_import/imported_contacts.csv
You must specify the file type of --type=dids or --type=extensions

I also tried other types like contact, contactmanager a.s.o.

### Operating Environment

Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 but also tested with FreePBX 16 on CentOS 8.

### Relevant log output

```shell
You must specify the file type of --type=dids or --type=extensions
```

**Comment by kapilgupta01** [comment]
Hi @fleptino  Please refer to the below syntax , we have DIDs / Extensions bulk import via CLI.
https://sangomakb.atlassian.net/wiki/spaces/PG/pages/41779247/fwconsole+commands+13#Bulk-Import

you can use GUI to do bulk import of contacts.

Thanks
