### ISSUE TITLE
[bug]: FreePBX 17 Backup and Restore fails on importing from older backup

### ISSUE THREAD

**Issue by Ressy66** [FreePBX/issue-tracker#561]
### FreePBX Version

FreePBX 17

### Issue Description

Installed 17, our old version is 14, when importing 14 backup to 17, there are a few issues, this one is, it ignores the backup and restore database from 14.

Confirmed backup and restore in 17 is completely empty. this is a huge failure for any upgrade, to not have a critical component available.  This pbx was not in service, installed and left running disconnected as testing before commissioning this Christmas, guess that's not going to happen now with this and and another serious omission, with time groups (separate bug report coming) 

### Operating Environment

v17

### Relevant log output

```shell
[2024-09-02 13:50:47] [a074b590-43b2-4fac-9b52-547d7b4cba23.INFO]: Skipping Legacy Backup module  [] []
[2024-09-02 13:50:47] [a074b590-43b2-4fac-9b52-547d7b4cba23.INFO]: Done [] []
[2024-09-02 13:50:47] [a074b590-43b2-4fac-9b52-547d7b4cba23.INFO]:  [] []
```

**Comment by kapilgupta01** [comment]
Hi @Ressy66  `Skipping Legacy Backup module` This line means 17v Restore process is not restoring just the "backup" module configuration because 14's Backup module is different then 15+.  this is expected behavior. 

Are you seeing none of your 14 system modules got restored ?

**Comment by Ressy66** [comment]
Hi @kguptasangoma , there was some problem with timegroups as well, separate bug report,  I thought I read that we could restore from v14, I must have mis-read that. Thanks for clearing it up, I guess this isn't a bug so we can close it off.
