### ISSUE TITLE
[bug]: Scribe

### ISSUE THREAD

**Issue by c-ferrall** [FreePBX/issue-tracker#567]
### FreePBX Version

FreePBX 15

### Issue Description

Just added Scribe and it's working great except that I can't get the transcription to be included in the email.  I add {VM_PBX_SCRIBE} in the body as specified the documentation but the text is gone after a reload.

### Operating Environment

15.0.37.9

**Comment by kapilgupta01** [comment]
Hi @c-ferrall Please ensure your below settings are proper - 

https://sangomakb.atlassian.net/wiki/spaces/PG/pages/488898594/Scribe#Enable-Scribe-for-Voicemail-to-Email

**Comment by c-ferrall** [comment]
I added the mail command for the extension that I am testing Scribe with.  Does it have to be global?



-------- Original message --------
From: kguptasangoma ***@***.***>
Date: 11/25/24 22:41 (GMT-05:00)
To: FreePBX/issue-tracker ***@***.***>
Cc: Chris Ferrall ***@***.***>, Mention ***@***.***>
Subject: Re: [FreePBX/issue-tracker] [bug]: Scribe (Issue #567)


Hi @c-ferrall<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_c-2Dferrall&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Ig9syPS4d7UDiAkEQqWLuYniIQPK7Nti_iNbSee5km8&m=DdEqYBykx4zvciuOEhzP7kpObgu62GMrd9raF9lcYzvGA1XO5__h-ge1fniBFmfF&s=cTBdgy_bWWw_oehZtcR6GGpYzxtam2zzVQdHuFRdNjY&e=> Please ensure your below settings are proper -

https://sangomakb.atlassian.net/wiki/spaces/PG/pages/488898594/Scribe#Enable-Scribe-for-Voicemail-to-Email<https://urldefense.proofpoint.com/v2/url?u=https-3A__sangomakb.atlassian.net_wiki_spaces_PG_pages_488898594_Scribe-23Enable-2DScribe-2Dfor-2DVoicemail-2Dto-2DEmail&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=Ig9syPS4d7UDiAkEQqWLuYniIQPK7Nti_iNbSee5km8&m=DdEqYBykx4zvciuOEhzP7kpObgu62GMrd9raF9lcYzvGA1XO5__h-ge1fniBFmfF&s=xzaAKXUzT5M4fgpW5Acq8WADnL-7_Ubb7lshnJZHOKQ&e=>

**Comment by kapilgupta01** [comment]
Hi @c-ferrall you should not do any manual step just enable the "voicemail to email" settings from the scribe dashboard and that should done everything automatically for you.

**Comment by c-ferrall** [comment]
That did it.

Thanks

**Comment by kapilgupta01** [comment]
Thanks @c-ferrall  

Best Regards
Kapil
