### ISSUE TITLE
[bug]: Installer errors when "Installing sangomaconnectmodule"

### ISSUE THREAD

**Issue by kb9gxk** [FreePBX/issue-tracker#57]
### FreePBX Version

FreePBX 17

### Issue Description

Can't install FreePBX 17 because it exits when installing the Sangoma Connect Module.

### Operating Environment

Debian 12 - base vanila install

### Relevant log output

```shell
2024-03-25 12:26:35 - Installing sangomaconnectmodule
2024-03-25 12:26:42 - Installation failed at step Installing sangomaconnectmodule. Please check log /var/log/pbx/freepbx17-install-2024.03.25-12.26.08.log for details.
2024-03-25 12:26:42 - Error at line line: 597 exiting with code 2 (last command was: fwconsole ma install sangomaconnect >> $log 2>&1)2024-03-25 12:26:42 - Exiting script
```

**Comment by kb9gxk** [comment]
Further information:
```
root@pbx:~# fwconsole ma install sangomaconnect
Updating tables sangomaconnect_user_pre_setup, sangomaconnect_user_setup, sangomaconnect_user_device, sangomaconnect_sngphone_sms_routing, sangomaconnect_phone_locations, sangomaconnect_account_phone_locations...Done
No PBXID file found, not registering module to cloud.
Checking module cloud activation status
System not activated, cannot perform cloud activation
Initializing node dependencies
Found npm-cache v0.7.0
Running installation..
[npm-cache] [INFO] using /home/asterisk/.package_cache as cache directory
[npm-cache] [INFO] [composer] Dependency config file /var/www/html/admin/modules/sangomaconnect/node/composer.json does not exist. Skipping install
[npm-cache] [INFO] [npm] config file exists
[npm-cache] [INFO] [npm] cli exists
[npm-cache] [INFO] [npm] hash of /var/www/html/admin/modules/sangomaconnect/node/package.json: a386f4a77785ce2c5562d106a52cef80
[npm-cache] [INFO] [npm] cache exists
[npm-cache] [INFO] [npm] clearing installed dependencies at /var/www/html/admin/modules/sangomaconnect/node/node_modules
[npm-cache] [INFO] [npm] ...cleared
[npm-cache] [INFO] [npm] retrieving dependencies from /home/asterisk/.package_cache/npm/9.2.0/a386f4a77785ce2c5562d106a52cef80.tar.gz
[npm-cache] [INFO] [bower] Dependency config file /var/www/html/admin/modules/sangomaconnect/node/bower.json does not exist. Skipping install
[npm-cache] [INFO] [npm] done extracting
[npm-cache] [INFO] successfully installed all dependencies

Finished updating libraries!
SangomaConnect Server is not running
SangomaConnect module installed but not activated. Please buy a license and activate the module

In Sangomaconnect.class.php line 5146:
                         
  Undefined array key 0  
                         

moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [<args>...]
```

**Comment by prashobkarimbil** [comment]
Hi @kb9gxk,

I'm unable to reproduce the issue. I tested with version 17.0.1.20. 
Can you share your version details?

**Comment by kb9gxk** [comment]
> Hi @kb9gxk,
> 
> I'm unable to reproduce the issue. I tested with version 17.0.1.20. Can you share your version details?

Where do I get that?  I downloaded the install script from the Github Repo and copy/pasted the commands.

Edit:  I Think I found it in the logs
```
Updating tables sysadmin_options, sysadmin_update_log, sysadmin_fail2ban, sysadmin_expiry_notifications...Done
Sangoma PnP Server activated
Generating CSS...Done
Module sysadmin version 17.0.1.44 successfully installed
Updating Hooks...Done
Chowning directories...Done
2024-03-26 10:17:55 - Installing sangomaconnectmodule
Updating tables sangomaconnect_user_pre_setup, sangomaconnect_user_setup, sangomaconnect_user_device, sangomaconnect_sngphone_sms_routing, sangomaconnect_phone_locations, sangomaconnect_account_phone_locations...Done
No PBXID file found, not registering module to cloud.
Checking module cloud activation status
System not activated, cannot perform cloud activation
Initializing node dependencies
Found npm-cache v0.7.0
Running installation..
[npm-cache] [INFO] using /home/asterisk/.package_cache as cache directory
[npm-cache] [INFO] [composer] Dependency config file /var/www/html/admin/modules/sangomaconnect/node/composer.json does not exist. Skipping install
[npm-cache] [INFO] [npm] config file exists
[npm-cache] [INFO] [npm] cli exists
[npm-cache] [INFO] [npm] hash of /var/www/html/admin/modules/sangomaconnect/node/package.json: a386f4a77785ce2c5562d106a52cef80
[npm-cache] [INFO] [npm] cache exists
[npm-cache] [INFO] [npm] clearing installed dependencies at /var/www/html/admin/modules/sangomaconnect/node/node_modules
[npm-cache] [INFO] [npm] ...cleared
[npm-cache] [INFO] [npm] retrieving dependencies from /home/asterisk/.package_cache/npm/9.2.0/a386f4a77785ce2c5562d106a52cef80.tar.gz
[npm-cache] [INFO] [bower] Dependency config file /var/www/html/admin/modules/sangomaconnect/node/bower.json does not exist. Skipping install
[npm-cache] [INFO] [npm] done extracting
[npm-cache] [INFO] successfully installed all dependencies

Finished updating libraries!
SangomaConnect Server is not running
SangomaConnect module installed but not activated. Please buy a license and activate the module

In Sangomaconnect.class.php line 5146:
                         
  Undefined array key 0  
                         

moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [<args>...]

2024-03-26 10:18:02 - ****** INSTALLATION FAILED *****
2024-03-26 10:18:02 - Installation failed at step Installing sangomaconnectmodule. Please check log /var/log/pbx/freepbx17-install-2024.03.26-10.17.30.log for details.
2024-03-26 10:18:02 - Error at line line: 597 exiting with code 2 (last command was: fwconsole ma install sangomaconnect >> $log 2>&1)2024-03-26 10:18:02 - Exiting script
```

**Comment by jissphilip** [comment]
@kb9gxk 
Please use the below command the install the latest version of sangomaconnect module 

`fwconsole ma downloadinstall sangomaconnect --tag  17.0.1.20`
Or 
`fwconsole ma downloadinstall sangomaconnect --edge`

**Comment by kb9gxk** [comment]
@jissphilip 
> fwconsole ma downloadinstall sangomaconnect --tag 17.0.1.20

Tried both.  I think it's more on the "Undefined Array Key 0" that's causing the issue.
```
SangomaConnect Server is not running
SangomaConnect module installed but not activated. Please buy a license and activate the module

In Sangomaconnect.class.php line 5146:
                         
  **Undefined array key 0**  
```

**Comment by LightningManGTS** [comment]
Sangoma connect installs for me but I get this error running the cloudconnect agent action

Installation failed - Failed to download installer: https://connect.sangoma.com:443/static/files/service-proxy-client_1.2.3-1_x86_64.deb Error: Array ( [type] => 2 [message] => fopen(https://connect.sangoma.com:443/static/files/service-proxy-client_1.2.3-1_x86_64.deb): Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found [file] => /var/www/html/admin/modules/sangomaconnect/hooks/install-proxy-client [line] => 275)

**Comment by LightningManGTS** [comment]
for refrence, I also tried running --edge and got the following, so something is definitely wrong at the cloud connect step.:

root@THD-FreePBX-17:~# fwconsole ma downloadinstall sangomaconnect --edge
Edge repository temporarily enabled
No repos specified, using: [standard,extended,commercial,unsupported] from last GUI settings

Downloading module 'sangomaconnect'
Processing sangomaconnect
Downloading...
 20397549/20397549 [============================] 100%
Finished downloading
Extracting...Done
Download completed in 5 seconds
Updating tables sangomaconnect_user_pre_setup, sangomaconnect_user_setup, sangomaconnect_user_device, sangomaconnect_sngphone_sms_routing, sangomaconnect_phone_locations, sangomaconnect_account_phone_locations...Done
Checking module cloud activation status
SangomaConnect module is registered to the cloud for deployment 40011628
Initializing node dependencies
npm WARN deprecated is-buffer@1.0.2: This version of 'is-buffer' is out-of-date. You must update to v1.1.6 or newer
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
Installed npm-cache v0.7.0
Running installation..
[npm-cache] [INFO] using /home/asterisk/.package_cache as cache directory
[npm-cache] [INFO] [composer] Dependency config file /var/www/html/admin/modules/sangomaconnect/node/composer.json does not exist. Skipping install
[npm-cache] [INFO] [npm] config file exists
[npm-cache] [INFO] [npm] cli exists
[npm-cache] [INFO] [npm] hash of /var/www/html/admin/modules/sangomaconnect/node/package.json: a386f4a77785ce2c5562d106a52cef80
[npm-cache] [INFO] [npm] cache exists
[npm-cache] [INFO] [npm] clearing installed dependencies at /var/www/html/admin/modules/sangomaconnect/node/node_modules
[npm-cache] [INFO] [npm] ...cleared
[npm-cache] [INFO] [npm] retrieving dependencies from /home/asterisk/.package_cache/npm/9.2.0/a386f4a77785ce2c5562d106a52cef80.tar.gz
[npm-cache] [INFO] [bower] Dependency config file /var/www/html/admin/modules/sangomaconnect/node/bower.json does not exist. Skipping install
[npm-cache] [INFO] [npm] done extracting
[npm-cache] [INFO] successfully installed all dependencies

Finished updating libraries!
SangomaConnect Server is not running
Installing CloudConnect Agent version to 1.2.3-1
SangomaConnect module installed but disabled
Something went wrong!!
Generating CSS...Done
Module sangomaconnect version 17.0.1.23 successfully installed
Updating Hooks...Done
Chowning directories...Done
Resetting temporarily repository state

**Comment by LightningManGTS** [comment]
adding my freepbx info from my other issue

Operating Environment
Freepbx 17, Asterisk 21,

-------------------+------------+-----------------------------------+-------------+-----------+
| Module | Version | Status | License | Signature |
+-------------------+------------+-----------------------------------+-------------+-----------+
| amd | 17.0.1 | Enabled | GPLv3+ | Sangoma |
| announcement | 17.0.2.1 | Enabled | GPLv3+ | Sangoma |
| areminder | 17.0.3.9 | Enabled | Commercial | Sangoma |
| arimanager | 17.0.1 | Enabled | GPLv3+ | Sangoma |
| asterisk-cli | 17.0.2 | Enabled | GPLv3+ | Sangoma |
| asteriskinfo | 17.0.1 | Enabled | GPLv3+ | Sangoma |
| backup | 17.0.5.14 | Enabled | GPLv3+ | Sangoma |
| blacklist | 17.0.1.2 | Enabled | GPLv3+ | Sangoma |
| broadcast | 17.0.1.6 | Enabled | Commercial | Sangoma |
| builtin | | Enabled | | Unsigned |
| bulkhandler | 17.0.4 | Enabled | GPLv3+ | Sangoma |
| calendar | 17.0.4.6 | Enabled | GPLv3+ | Sangoma |
| callaccounting | 17.0.4 | Enabled | Commercial+ | Sangoma |
| callback | 17.0.2.1 | Enabled | GPLv3+ | Sangoma |
| callerid | 17.0.1 | Enabled | Commercial | Sangoma |
| callforward | 17.0.1.3 | Enabled | AGPLv3+ | Sangoma |
| calllimit | 17.0.1.2 | Enabled | Commercial | Sangoma |
| callrecording | 17.0.3.6 | Enabled | AGPLv3+ | Sangoma |
| callwaiting | 17.0.3.2 | Enabled | GPLv3+ | Sangoma |
| cdr | 17.0.4.13 | Enabled | GPLv3+ | Sangoma |
| cel | 17.0.2.7 | Enabled | GPLv3+ | Sangoma |
| certman | 17.0.3.7 | Enabled | AGPLv3+ | Sangoma |
| cidlookup | 17.0.1.1 | Enabled | GPLv3+ | Sangoma |
| conferences | 17.0.3.1 | Enabled | GPLv3+ | Sangoma |
| conferencespro | 17.0.1.6 | Enabled | Commercial | Sangoma |
| configedit | 17.0.1.1 | Enabled | AGPLv3+ | Sangoma |
| contactmanager | 17.0.5.6 | Enabled | GPLv3+ | Sangoma |
| core | 17.0.9.33 | Enabled | GPLv3+ | Sangoma |
| cos | 17.0.1.1 | Enabled | Commercial | Sangoma |
| customappsreg | 17.0.1 | Enabled | GPLv3+ | Sangoma |
| dashboard | 17.0.4.2 | Enabled | AGPLv3+ | Sangoma |
| daynight | 17.0.1.1 | Enabled | GPLv3+ | Sangoma |
| dictate | 17.0.1 | Enabled | GPLv3+ | Sangoma |
| directory | 17.0.1.1 | Enabled | GPLv3+ | Sangoma |
| donotdisturb | 17.0.2.1 | Enabled | GPLv3+ | Sangoma |
| endpoint | 17.0.1.53 | Enabled | Commercial | Sangoma |
| extensionroutes | 17.0.1 | Enabled | Commercial | Sangoma |
| extensionsettings | 17.0.1 | Enabled | GPLv3+ | Sangoma |
| fax | 17.0.3.2 | Enabled | GPLv3+ | Sangoma |
| faxpro | 17.0.1.14 | Enabled | Commercial | Sangoma |
| featurecodeadmin | 17.0.2 | Enabled | GPLv3+ | Sangoma |
| filestore | 17.0.2.9 | Enabled | AGPLv3 | Sangoma |
| findmefollow | 17.0.4.6 | Enabled | GPLv3+ | Sangoma |
| firewall | 17.0.1.13 | Enabled | AGPLv3+ | Sangoma |
| framework | 17.0.15.13 | Enabled | GPLv2+ | Sangoma |
| hotelwakeup | 17.0.1.5 | Enabled | GPLv2 | Sangoma |
| iaxsettings | 17.0.1 | Enabled | AGPLv3 | Sangoma |
| infoservices | 17.0.1 | Enabled | GPLv2+ | Sangoma |
| ivr | 17.0.5 | Enabled | GPLv3+ | Sangoma |
| languages | 17.0.1 | Enabled | GPLv3+ | Sangoma |
| logfiles | 17.0.2 | Enabled | GPLv3+ | Sangoma |
| manager | 17.0.3 | Enabled | GPLv2+ | Sangoma |
| miscapps | 17.0.3 | Enabled | GPLv3+ | Sangoma |
| miscdests | 17.0.1.1 | Enabled | GPLv3+ | Sangoma |
| music | 17.0.4 | Enabled | GPLv3+ | Sangoma |
| oembranding | | Not Installed (Locally available) | Commercial | Sangoma |
| paging | 17.0.3 | Enabled | GPLv3+ | Sangoma |
| pagingpro | 17.0.1.6 | Enabled | Commercial | Sangoma |
| parking | 17.0.2 | Enabled | GPLv3+ | Sangoma |
| parkpro | 17.0.1.4 | Enabled | Commercial | Sangoma |
| pbxmfa | 17.0.2 | Enabled | Commercial+ | Sangoma |
| pinsets | 17.0.3 | Enabled | GPLv3+ | Sangoma |
| pinsetspro | 17.0.2 | Enabled | Commercial | Sangoma |
| pm2 | 17.0.3.1 | Enabled | AGPLv3+ | Sangoma |
| presencestate | 17.0.2.1 | Enabled | GPLv3+ | Sangoma |
| printextensions | 17.0.1.2 | Enabled | GPLv3+ | Sangoma |
| queueprio | 17.0.1.4 | Enabled | GPLv3+ | Sangoma |
| queues | 17.0.1.7 | Enabled | GPLv2+ | Sangoma |
| queuestats | 17.0.1.6 | Enabled | Commercial | Sangoma |
| qxact_reports | 17.0.2 | Enabled | Commercial | Sangoma |
| recording_report | 17.0.3.6 | Enabled | Commercial | Sangoma |
| recordings | 17.0.2.2 | Enabled | GPLv3+ | Sangoma |
| restapps | 17.0.1.14 | Enabled | Commercial | Sangoma |
| ringgroups | 17.0.2.4 | Enabled | GPLv3+ | Sangoma |
| sangomaconnect | 17.0.1.20 | Enabled | Commercial | Sangoma |
| sangomartapi | 17.0.1.14 | Enabled | Commercial | Sangoma |
| setcid | 17.0.1.2 | Enabled | GPLv3+ | Sangoma |
| sipsettings | 17.0.6.3 | Enabled | AGPLv3+ | Sangoma |
| sipstation | 17.0.3.3 | Enabled | Commercial | Sangoma |
| sms | 17.0.1.8 | Enabled | Commercial | Sangoma |
| smsconnector | | Not Installed (Locally available) | GPLv3+ | Unknown |
| smsplus | 17.0.3 | Enabled | Commercial | Sangoma |
| soundlang | 17.0.4 | Enabled | GPLv3+ | Sangoma |
| sysadmin | 17.0.1.48 | Enabled | Commercial | Sangoma |
| timeconditions | 17.0.1.13 | Enabled | GPLv3+ | Sangoma |
| tts | 17.0.1.1 | Enabled | GPLv3+ | Sangoma |
| ttsengines | 17.0.1 | Enabled | AGPLv3 | Sangoma |
| ucp | 17.0.4.13 | Enabled | AGPLv3+ | Sangoma |
| userman | 17.0.6.16 | Enabled | AGPLv3+ | Sangoma |
| vmblast | 17.0.1 | Enabled | GPLv3+ | Sangoma |
| vmnotify | 17.0.1.5 | Enabled | Commercial | Sangoma |
| voicemail | 17.0.5.14 | Enabled | GPLv3+ | Sangoma |
| voicemail_report | | Not Installed (Locally available) | Commercial | Sangoma |
| vqplus | 17.0.1.13 | Enabled | Commercial | Sangoma |
| weakpasswords | 17.0.1 | Enabled | GPLv3+ | Sangoma |
| webrtc | 17.0.2.1 | Enabled | GPLv3+ | Sangoma |
+-------------------+------------+-----------------------------------+-------------+-----------+

**Comment by prashobkarimbil** [comment]
Hi @kb9gxk, 
can you share the out put of the following commands?

- `/sbin/ip -o addr`
- `/sbin/ip -o link`

Also, can you confirm that you are still getting the error In Sangomaconnect.class.php line 5146, from the logs.

We need the above information since we couldn't reproduce this issue locally.

**Comment by kb9gxk** [comment]
@prashobkarimbil 
```
jparrish@pbx:~$ /sbin/ip -o addr
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
3: eth1    inet 10.2.0.135/24 brd 10.2.0.255 scope global dynamic eth1\       valid_lft 86148sec preferred_lft 86148sec
jparrish@pbx:~$ /sbin/ip -o link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000\    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000\    link/ether 00:15:5d:00:9f:21 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000\    link/ether 00:15:5d:00:9f:22 brd ff:ff:ff:ff:ff:ff
```

I re-ran the command `fwconsole ma downloadinstall sangomaconnect --edge` and then the installer and it installed this time.  It did not work by just running the installer.

**Comment by kapilgupta01** [comment]
Please try with the latest sangomaconnect module which has fix for downloading "[service-proxy-client_1.2.3-](https://connect.sangoma.com/static/files/service-proxy-client_1.2.3-1_x86_64.deb)" rpm and undefined index error.

Thank you for testing FreePBX 17. 

Regards
Kapil
