### ISSUE TITLE
[bug]:  Do not start Apache if there is a delay in obtaining the IP address

### ISSUE THREAD

**Issue by kapilgupta01** [FreePBX/issue-tracker#573]
### FreePBX Version

FreePBX 17

### Issue Description

We are encountering a problem where a delay in obtaining a valid IP address during the boot process of the system (version 17) prevents the Apache2 process from loading the "ionCube" driver correctly. As a result, when the UI is accessed, it triggers a "memory allocation error." This issue occurs specifically when Apache2 starts before the system has obtained a valid IP address.

Proposed Solution:
To mitigate this issue, we plan to implement a pre-check script within the "apache2" service that will continuously monitor for a valid IP address. Apache2 will not start until the system receives a valid IP address, ensuring that the "ionCube" driver is properly loaded before the web UI is accessed.

Additional Context:
This script will be part of the sysadmin module.
The ionCube component is only relevant for commercial components of FreePBX, so the script will target these use cases specifically.

### Operating Environment

NA

**Comment by ramarajan222** [comment]
Fixed with latest sysadmin V17.0.2.8
