### ISSUE TITLE
[bug]: Scribe with external SMTP server

### ISSUE THREAD

**Issue by c-ferrall** [FreePBX/issue-tracker#577]
### FreePBX Version

FreePBX 15

### Issue Description

I enabled Scribe on an existing system that uses an external SMTP server.  The system has been in place for over a year and would send emails with no issue.  After I enabled Voicemail to Email in the scribe settings all emails being sent started bouncing.  After I disabled Voicemail to Email everything returned to normal operation.

### Operating Environment

PBX Version:15.0.37.9
PBX Distro:12.7.8-2306-1.sng7
Asterisk Version:16.20.0
Scribe 15.0.2

**Comment by kapilgupta01** [comment]
hi @c-ferrall can you please raise commercial module support ticket so we can ssh to your system to debug directly as its not easy to reproduce same SMTP behavior locally.

thanks

**Comment by kapilgupta01** [comment]
/
Hi 

You've opened a bug for a Commercial Module.

This Issue tracking system is for our Free and Open Source modules only.

Please open [a commercial support ticket [here](https://help.sangoma.com/)!.

If you are using FreePBX 12 or higher, please make sure you attach a Support Debug package (which is generated through the System Admin module) to the commercial support ticket.  Do not attach it to THIS bug tracker, as it may contain confidential information that will not be hidden from the general public.


Thank you for using FreePBX.
Kapil Gupta
