### ISSUE TITLE
[bug]: sangomaconnect should not be a forced requirement when not bought

### ISSUE THREAD

**Issue by Ressy66** [FreePBX/issue-tracker#579]
### FreePBX Version

FreePBX 17

### Issue Description

sangomaconnect, a full commercial module, that has no configuration available unless bought, was removed because in new user creation "services" it throw garbage in there, invalid:foo bar, etc, can not seem to find this template to remove such nonsense, but in an update today, updating fails at Sangoma Realtime API.
is it safe to remove this, if so I wonder what else will break?
I also had issue removing phone apps too which was another annoyance.

v17 seems to be too heavily reliant for modules that can not be used and cause annoyances, like above.

### Operating Environment

FreePBX 17.0.19.21
Asterisk 22

### Relevant log output

```shell
Exception (404)
Unable to locate the FreePBX BMO Class 'Sangomaconnect'A required module might be disabled or uninstalled. Recommended steps (run from the CLI): 1) fwconsole ma install sangomaconnect 2) fwconsole ma enable sangomaconnect
```

**Comment by kapilgupta01** [comment]
If you are not using sangomaconnect then please remove sangomartapi also. 
SangomaRTAPI module is an required module if running sangomaconnect desktop client.
