### ISSUE TITLE
[bug]: IAX2 is not working.

### ISSUE THREAD

**Issue by maccadoo** [FreePBX/issue-tracker#58]
### FreePBX Version

FreePBX 17

### Issue Description

IAX2 is not working.
I have set up an extension but can't get it to register.
There is no "Asterisk IAX Settings" in the settings section in the toolbar.

I access toolbar > Admin > Module Admin.
so I check the Repositories online. but I can not see "Asterisk IAX Settings".

### Operating Environment

debian_version 12.5

**Comment by ramarajan222** [comment]
Hi @maccadoo ,

Please install the Iaxsettings module and then give it a try
`fwconsole ma downloadinstall iaxsettings`

**Comment by maccadoo** [comment]
THX.
It's working now.
