### ISSUE TITLE
[improvement]: Change: Set the Default Directory Option to "Include" as the Default for New Extensions

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#584]
### FreePBX Version

FreePBX 17

### Improvement Description

Hi Team,

Currently, when creating a new extension, the "Default Directory" is set to "Exclude." Could we change this setting to "Include" as the default option so that new extensions are automatically added to the default directory group?

![image](https://github.com/user-attachments/assets/6269f9a1-4e00-423f-a98b-857d33515499)

**Comment by jissphilip** [comment]
directory version 17.0.1.2
