### ISSUE TITLE
[bug]: SangomaConnect 16.0.47.24 blocks reload due to supposed shortage of Supervisor licenses.

### ISSUE THREAD

**Issue by WillemVE17** [FreePBX/issue-tracker#585]
### FreePBX Version

FreePBX 16

### Issue Description

Upgrading module SangomaConnect from 16.0.47.21 to 16.047.24  failed. "Reload blocked due to Sangoma Desktop Queue Supervisor License".
It says:"Your license allows a maximum of 20 supervisors, but the currenty configuration includes 32 supervisors".
It could very well be that we have 32 users with their queues visibility enabled, but I cannot check that because the possibility to set or check that has been absent in User management/User/Sangoma Talk for months now.
But we have never setup users with supervisor settings nor have we ever bought these licenses.
Maybe the max of 20 is some sort of grace setting while the module is in beta, but counting the 32 standard users as supervisors seems like a bug to me.

### Operating Environment

PBX Version:16.0.40.11
PBX Distro:12.7.8-2306-1.sng7
Asterisk Version:16.30.0

**Comment by ramarajan222** [comment]
Hi @WillemVE17 

The Supervisor and Queue licenses are available on the portal, so you can purchase them and convert to the licensed version.
https://sangomakb.atlassian.net/wiki/spaces/SS1/pages/521797687/PBXact-How+to+purchase+Queue+Advanced+license
https://sangomakb.atlassian.net/wiki/spaces/SS1/pages/526090252/Sangoma+Desktop+Advanced+Queue+license+-+Migration+from+beta+to+licensed+version

If you wish to continue using the beta license, edit the file below and change the value from 20 to 32.

`cat /var/spool/asterisk/tmp/scd_queue_vis.conf`
