### ISSUE TITLE
[bug]: How to configure TATA SIP trunk (provider in india)

### ISSUE THREAD

**Issue by durgareddy8296** [FreePBX/issue-tracker#59]
### FreePBX Version

FreePBX 16

### Issue Description

Hi,
Team,
How to configure TATA SIP trunk (provider in india)
They are provide following information;
DID no : 7316832500
Start Range : 7316832500
End Range : 7316832589
Customer IP : 10.0.71.90
Gateway IP : 10.0.71.89
Subnet Mask : 255.255.255.252
SIP Server IP : 10.0.71.94
Username &; password is given to me

how to setup a sip trunk with the above information, And make outbound in inbound routes.

Please help…

### Operating Environment

freePBX Framework vertion : 16
Asteisk version : 18.16.0

**Comment by lgaetz** [comment]
The issue tracker is for bugs. Please raise support issues on the forum https://community.freepbx.org/

**Comment by durgareddy8296** [comment]
i don't konw how rise a support issue on the form
