### ISSUE TITLE
[bug]: Endpoint module conflict with mine

### ISSUE THREAD

**Issue by jcattan** [FreePBX/issue-tracker#592]
### FreePBX Version

FreePBX 16

### Issue Description

Hi,
your endpoint plugin doesn't want to install if mine is installed. 
error : 
```
fwconsole ma install endpoint -d -v
skipbreakingcheck Disabled
Force Disabled
Array
(
    [0] => install
    [1] => endpoint
)
Unable to install module endpoint:
 - Failed to install EndPoint Manager due to the following conflicting module(s): AutoProv End Point Manager
Updating Hooks...Done
Taking too long? Customize the chown command, See http://wiki.freepbx.org/display/FOP/FreePBX+Chown+Conf
Setting Permissions...

In Chown.class.php line 167:

  [Whoops\Exception\ErrorException (8)]
  Undefined index: byconfig


Exception trace:
  at /var/www/html/admin/libraries/Console/Chown.class.php:167
 Whoops\Run->handleError() at /var/www/html/admin/libraries/Console/Chown.class.php:167
 FreePBX\Console\Command\Chown->execute() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/admin/libraries/Console/Moduleadmin.class.php:1042
 FreePBX\Console\Command\Moduleadmin->setPerms() at /var/www/html/admin/libraries/Console/Moduleadmin.class.php:1479
 FreePBX\Console\Command\Moduleadmin->handleArgs() at /var/www/html/admin/libraries/Console/Moduleadmin.class.php:236
 FreePBX\Console\Command\Moduleadmin->execute() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:992
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /var/www/html/admin/libraries/Composer/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/lib/asterisk/bin/fwconsole:163

moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [<args>]...
```

If i disable my module, install yours and then enable mine, all works fine. 
but if there is any (auto) upgrade of your module it's fail with the preview error.

I need to install your enpoint module for SangomaTalk but i don't use it.

My module (fork of old OSS endpointman) is available here if necessary : https://github.com/jcattan/autoprov

Thanks for your help

### Operating Environment

 fwconsole ma list
No repos specified, using: [standard,extended,commercial,unsupported] from last GUI settings

+---------------------+------------+-----------------------------------+------------+-----------+
| Module              | Version    | Status                            | License    | Signature |
+---------------------+------------+-----------------------------------+------------+-----------+
| accountcodepreserve | 16.0.0.1   | Enabled                           | GPLv2      | Sangoma   |
| announcement        | 16.0.7     | Enabled                           | GPLv3+     | Sangoma   |
| arimanager          | 16.0.13    | Enabled                           | GPLv3+     | Sangoma   |
| asterisk-cli        | 16.0.8     | Enabled                           | GPLv3+     | Sangoma   |
| asteriskinfo        | 16.0.10    | Enabled                           | GPLv3+     | Sangoma   |
**| autoprov            | 16.0.0.3   | Enabled                           | GPLv3+     | Unknown   |**
| backup              | 16.0.70.2  | Enabled                           | GPLv3+     | Sangoma   |
| blacklist           | 16.0.21    | Enabled                           | GPLv3+     | Sangoma   |
| builtin             |            | Enabled                           |            | Unsigned  |
| bulkhandler         | 16.0.16    | Enabled                           | GPLv3+     | Sangoma   |
| calendar            | 16.0.34    | Enabled                           | GPLv3+     | Sangoma   |
| callforward         | 16.0.6     | Enabled                           | AGPLv3+    | Sangoma   |
| callrecording       | 16.0.22    | Enabled                           | AGPLv3+    | Sangoma   |
| callstatistics      |            | Not Installed (Locally available) |            | Unsigned  |
| callwaiting         | 16.0.5     | Enabled                           | GPLv3+     | Sangoma   |
| cdr                 | 16.0.46.22 | Enabled                           | GPLv3+     | Sangoma   |
| cel                 | 16.0.20    | Enabled                           | GPLv3+     | Sangoma   |
| certman             | 16.0.30    | Enabled                           | AGPLv3+    | Sangoma   |
| cidlookup           | 16.0.16    | Enabled                           | GPLv3+     | Sangoma   |
| conferences         | 16.0.9     | Enabled                           | GPLv3+     | Sangoma   |
| configedit          | 16.0.5     | Enabled                           | AGPLv3+    | Sangoma   |
| contactmanager      | 16.0.26.2  | Enabled                           | GPLv3+     | Sangoma   |
| core                | 16.0.68.30 | Enabled                           | GPLv3+     | Sangoma   |
| customappsreg       | 16.0.5     | Enabled                           | GPLv3+     | Sangoma   |
| dashboard           | 16.0.21    | Enabled                           | AGPLv3+    | Sangoma   |
| daynight            | 16.0.3     | Enabled                           | GPLv3+     | Sangoma   |
| donotdisturb        | 16.0.3     | Enabled                           | GPLv3+     | Sangoma   |
**| endpoint            | 16.0.86.30 | Enabled                           | Commercial | Sangoma   |**
| endpointman         |            | Not Installed (Locally available) | GPLv3+     | Unsigned  |
| extensionsettings   | 16.0.5     | Enabled                           | GPLv3+     | Sangoma   |
| fax                 | 16.0.13    | Enabled                           | GPLv3+     | Sangoma   |
| featurecodeadmin    | 16.0.11    | Enabled                           | GPLv3+     | Sangoma   |
| filestore           | 16.0.18.2  | Enabled                           | AGPLv3     | Sangoma   |
| findmefollow        | 16.0.23    | Enabled                           | GPLv3+     | Sangoma   |
| firewall            | 16.0.57.8  | Enabled                           | AGPLv3+    | Sangoma   |
| framework           | 16.0.40.11 | Enabled                           | GPLv2+     | Sangoma   |
| gestionrenvois      | 15.0.1     | Enabled                           |            | Unknown   |
| hotelwakeup         | 16.0.9     | Enabled                           | GPLv2      | Sangoma   |
| iaxsettings         | 16.0.4     | Enabled                           | AGPLv3     | Sangoma   |
| infoservices        | 16.0.2     | Enabled                           | GPLv2+     | Sangoma   |
| ivr                 | 16.0.9     | Enabled                           | GPLv3+     | Sangoma   |
| languages           | 16.0.4     | Enabled                           | GPLv3+     | Sangoma   |
| logfiles            | 16.0.7     | Enabled                           | GPLv3+     | Sangoma   |
| manager             | 16.0.23    | Enabled                           | GPLv2+     | Sangoma   |
| miscapps            | 16.0.2     | Enabled                           | GPLv3+     | Sangoma   |
| miscdests           | 16.0.2     | Enabled                           | GPLv3+     | Sangoma   |
| music               | 16.0.3     | Enabled                           | GPLv3+     | Sangoma   |
| outcnam             | 16.0.1     | Enabled                           | GPLv3+     | Sangoma   |
| paging              | 16.0.13    | Enabled                           | GPLv3+     | Sangoma   |
| parking             | 16.0.4     | Enabled                           | GPLv3+     | Sangoma   |
| phonebook           | 16.0.3     | Enabled                           | GPLv3+     | Sangoma   |
| phpinfo             | 16.0.1     | Enabled                           | GPLv2+     | Sangoma   |
| pm2                 | 16.0.8     | Enabled                           | AGPLv3+    | Sangoma   |
| presencestate       | 16.0.4     | Enabled                           | GPLv3+     | Sangoma   |
| printextensions     | 16.0.8     | Enabled                           | GPLv3+     | Sangoma   |
| queues              | 16.0.28    | Enabled                           | GPLv2+     | Sangoma   |
| recordings          | 16.0.16    | Enabled                           | GPLv3+     | Sangoma   |
| ringgroups          | 16.0.11    | Enabled                           | GPLv3+     | Sangoma   |
| routepermissions    | 16.0.0.1   | Enabled                           | AGPL 3     | Unknown   |
| sipsettings         | 16.0.27    | Enabled                           | AGPLv3+    | Sangoma   |
| soundlang           | 16.0.9     | Enabled                           | GPLv3+     | Sangoma   |
| superfecta          | 16.0.39    | Enabled                           | GPLv2+     | Sangoma   |
| sysadmin            | 16.0.45    | Enabled                           | Commercial | Sangoma   |
| taxation            | 14.0.0.1   | Enabled                           | GPLv3+     | Unknown   |
| timeconditions      | 16.0.11    | Enabled                           | GPLv3+     | Sangoma   |
| tts                 | 16.0.3     | Enabled                           | GPLv3+     | Sangoma   |
| ttsengines          | 16.0.3     | Enabled                           | AGPLv3     | Sangoma   |
| ucp                 | 16.0.38.2  | Enabled                           | AGPLv3+    | Sangoma   |
| userman             | 16.0.44.13 | Enabled                           | AGPLv3+    | Sangoma   |
| voicemail           | 16.0.60    | Enabled                           | GPLv3+     | Sangoma   |
| weakpasswords       | 16.0.1     | Enabled                           | GPLv3+     | Sangoma   |
| webrtc              | 16.0.18    | Enabled                           | GPLv3+     | Sangoma   |
+---------------------+------------+-----------------------------------+------------+-----------+

**Comment by jcattan** [comment]
the best and simple solution ... for me ... is not to force the endpoint module for SangomaTalk

I am working on updating my module for FreePBX 17 and I would like everything to be OK with my new version

**Comment by kapilgupta01** [comment]
Hi @jcattan I can not access https://github.com/jcattan/autoprov to download your module to check?

quick look into code does not give me any clue like why it could fail due to your module so if you can give me access to your module so i can try to reproduce issue locally to check further.

Thanks

**Comment by jcattan** [comment]
[autoprov16.0.0.3.tar.gz](https://github.com/user-attachments/files/18196877/autoprov16.0.0.3.tar.gz)
attached the module

**Comment by kapilgupta01** [comment]
Hi @jcattan issue is because you have added conflict of endpoint in your module.

Refer to autoprov_module_install_check_callback API.

Error is coming from your module which is blocking endpoint module to get install if your module is present.

Thanks
Kapil
