### ISSUE TITLE
[bug]: Sangoma Desktop and Sangoma Talk DND( do not disturb) is not working

### ISSUE THREAD

**Issue by hsmulb** [FreePBX/issue-tracker#60]
### FreePBX Version

FreePBX PBXact 15.0.37

### Issue Description

 Sangoma Desktop version 4.0.3  and Sangoma Talk DND( do not disturb) are not working. Calls still come through.

### Operating Environment

PBXact 15.0.37

**Comment by prashobkarimbil** [comment]
Hi @hsmulb,

We are unable to reproduce this issue.
Please update the following modules to the latest version then do the `Apply Config` (or `fwconsole r` through the CLI). 

- framework
- core
- sysadmin
- manager
- sangomaconnect
- restapps
- sangomartapi

If the issue still exists, feel free to reopen this ticket.

**Comment by prashobkarimbil** [comment]
Marking this ticket as closed
