### ISSUE TITLE
[bug]: There is an unfamiliar user on the Asterisk Rest Interface.

### ISSUE THREAD

**Issue by maccadoo** [FreePBX/issue-tracker#61]
### FreePBX Version

FreePBX 17

### Issue Description

![Screenshot 2024-03-27 19 34 31](https://github.com/FreePBX/issue-tracker/assets/7710522/7de99f64-8a97-4838-9dfc-889fe3ac67ba)
![Screenshot 2024-03-27 19 35 08](https://github.com/FreePBX/issue-tracker/assets/7710522/ab0c4fd6-92bb-457e-bcd0-e4f5e0cb06d6)
The user appears in the ARI even though it has not created any PEER in PJSIP.

### Operating Environment

debian_version 12.5

**Comment by kapilgupta01** [comment]
That is because of DPMA module.  DPMA will internally create an endpoint and use it for things when the DPMA module is loaded and DPMA traffic is received.

**Comment by PVasileff** [comment]
I have the same issue. I just installed FreePBX 17 on Debian 12, and in Reports -> Asterisk Info, I see these two Channels (see the screenshot).
Could you please let me know if this is a bug? Should I be concerned about it, and is there a way to fix it myself?

![freepbx17](https://github.com/user-attachments/assets/a98d9e70-3697-466d-a7f6-f805a8afc5f7)

**Comment by kapilgupta01** [comment]
please find the explanation in below comment as well.

https://github.com/FreePBX/issue-tracker/issues/61#issuecomment-2074611517 

if you do not want dpma then please unload res_digium_phone_module (i think this is the same AFAIR)
