### ISSUE TITLE
[bug]: Unable to install Japanese Language Packs

### ISSUE THREAD

**Issue by maccadoo** [FreePBX/issue-tracker#62]
### FreePBX Version

FreePBX 17

### Issue Description

root@freePBX:~# fwconsole sounds --install=ja
LICENSE FOR VOICE PROMPT FILES
------------------------------

The voice prompt files distributed herewith are Copyright (C) 2014
QLOOG, Inc., and provided under terms of the following License.  For
more information, or to purchase custom voice prompt files, please
contact QLOOG at:

info@qloog.com
http://www.qloog.com/

-----------------------Abbreviation---------------------------------

Accept License Agreement? [y/n]y
Installing ja...
In Soundlang.class.php line 1548:
  error code: 524  
                   
sounds [--list] [--listglobal] [--install INSTALL] [--uninstall UNINSTALL] [--global GLOBAL] [--sync]

### Operating Environment

debian_version 12.5

**Comment by ramarajan222** [comment]
We were unable to reproduce your issue, and were able to install Japanese language successfully.

Soundlang version on my system is 17.0.4 , please upgrade soundlang module if the old version is running on your system.

`
Accept License Agreement? [y/n]y
Installing ja...Done
root@vultr:~# ls -l /var/lib/asterisk/sounds/
total 644
drwxr-xr-x  2 asterisk asterisk   4096 Mar  1 11:47 custom
drwxr-xr-x 10 asterisk asterisk 290816 Mar 29 09:27 en
drwxr-xr-x  8 asterisk asterisk  40960 Mar  4 06:30 en_AU
drwxr-xr-x  8 asterisk asterisk  61440 Mar  4 06:30 en_GB
drwxr-xr-x  8 asterisk asterisk  45056 Mar  4 06:30 es
drwxr-xr-x  8 asterisk asterisk  57344 Mar  4 06:30 fr
drwxr-xr-x  8 asterisk asterisk  61440 Mar  4 06:30 it
drwxr-xr-x  8 asterisk asterisk  69632 Mar 29 09:50 ja
lrwxrwxrwx  1 asterisk asterisk     59 Mar  4 06:33 silence-30.gsm -> /var/www/html/admin/modules/broadcast/sounds/silence-30.gsm
lrwxrwxrwx  1 asterisk asterisk     58 Mar  4 06:33 silence-5.gsm -> /var/www/html/admin/modules/broadcast/sounds/silence-5.gsm
drwxr-xr-x  2 asterisk asterisk   4096 Mar 29 09:50 tmp
root@vultr:~# fwconsole ma list | grep sound
| soundlang        | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |

`

**Comment by ramarajan222** [comment]
Please reopen the jira , if the issue persists with the latest soundlang module(17.0.4).

**Comment by maccadoo** [comment]
I just ran the command and it installed without error.
Thank you
