### ISSUE TITLE
[bug]: FreePBX 17 beta - issue with Endpoint Manager Extension Mapping

### ISSUE THREAD

**Issue by icciaaron** [FreePBX/issue-tracker#65]
### FreePBX Version

FreePBX 17

### Issue Description

After creating a new Debian 12 FreePBX install, running the FreePBX 17 setup script, and restoring from SNG7, I have not been able to get into the EPM extension mapping GUI. The other aspects of EPM GUI are all working fine (DPMA, basefile edit, etc.). 

I get the following exception: "Whoops \ Exception \ ErrorException (E_WARNING)
Undefined array key 1" - PDF is attached with full output

This server is also using the PBXact branding.

To be clear, I am running the beta for fun and to be helpful.  I also have a fully functional SNG7 install, which I can cut back to if PBX17 presents connectivity issues. So far, everything is great except for a couple of GUI issues. BRAVO!

[EPM - extension mapping.pdf](https://github.com/FreePBX/issue-tracker/files/14774776/EPM.-.extension.mapping.pdf)

### Operating Environment

Debian 12
asterisk 21
framework 17.0.15.8 
endpoint 17.0.1.45

+-------------------+-----------+-----------------------------------+-------------+-----------+
| Module            | Version   | Status                            | License     | Signature |
+-------------------+-----------+-----------------------------------+-------------+-----------+
| amd               | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| announcement      | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| areminder         | 17.0.3.9  | Enabled                           | Commercial  | Sangoma   |
| arimanager        | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli      | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo      | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| backup            | 17.0.5.13 | Enabled                           | GPLv3+      | Sangoma   |
| blacklist         | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| broadcast         | 17.0.1.6  | Enabled                           | Commercial  | Sangoma   |
| builtin           |           | Enabled                           |             | Unsigned  |
| bulkhandler       | 17.0.4    | Enabled                           | GPLv3+      | Sangoma   |
| calendar          | 17.0.4.6  | Enabled                           | GPLv3+      | Sangoma   |
| callback          | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| callerid          | 17.0.1    | Enabled                           | Commercial  | Sangoma   |
| callforward       | 17.0.1.3  | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit         | 17.0.1.2  | Enabled                           | Commercial  | Sangoma   |
| callrecording     | 17.0.3.5  | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting       | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| cdr               | 17.0.4.13 | Enabled                           | GPLv3+      | Sangoma   |
| cel               | 17.0.2.7  | Enabled                           | GPLv3+      | Sangoma   |
| certman           | 17.0.3.7  | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup         | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| conferences       | 17.0.3.1  | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro    | 17.0.1.6  | Enabled                           | Commercial  | Sangoma   |
| configedit        | 17.0.1.1  | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager    | 17.0.5.6  | Enabled                           | GPLv3+      | Sangoma   |
| core              | 17.0.9.29 | Enabled                           | GPLv3+      | Sangoma   |
| cos               | 17.0.1.1  | Enabled                           | Commercial  | Sangoma   |
| customappsreg     | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| dashboard         | 17.0.4.2  | Enabled                           | AGPLv3+     | Sangoma   |
| daynight          | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| directory         |           | Not Installed (Locally available) | GPLv3+      | Sangoma   |
| donotdisturb      | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| endpoint          | 17.0.1.45 | Enabled                           | Commercial  | Sangoma   |
| extensionroutes   | 17.0.1    | Enabled                           | Commercial  | Sangoma   |
| extensionsettings | 16.0.5    | Enabled                           | GPLv3+      | Sangoma   |
| fax               | 17.0.3.2  | Enabled                           | GPLv3+      | Sangoma   |
| faxpro            | 17.0.1.14 | Enabled                           | Commercial  | Sangoma   |
| featurecodeadmin  | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| filestore         | 17.0.2.9  | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow      | 17.0.4.5  | Enabled                           | GPLv3+      | Sangoma   |
| firewall          | 17.0.1.13 | Enabled                           | AGPLv3+     | Sangoma   |
| framework         | 17.0.15.8 | Enabled                           | GPLv2+      | Sangoma   |
| hotelwakeup       | 17.0.1.5  | Enabled                           | GPLv2       | Sangoma   |
| infoservices      | 17.0.1    | Enabled                           | GPLv2+      | Sangoma   |
| ivr               | 17.0.4    | Enabled                           | GPLv3+      | Sangoma   |
| languages         | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| logfiles          | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| manager           | 17.0.3    | Enabled                           | GPLv2+      | Sangoma   |
| miscapps          | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| miscdests         | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| music             | 17.0.4    | Enabled                           | GPLv3+      | Sangoma   |
| oembranding       | 17.0.1.2  | Enabled                           | Commercial  | Sangoma   |
| paging            | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro         | 17.0.1.5  | Enabled                           | Commercial  | Sangoma   |
| parking           | 17.0.2    | Enabled                           | GPLv3+      | Sangoma   |
| parkpro           | 17.0.1.3  | Enabled                           | Commercial  | Sangoma   |
| pbxmfa            | 17.0.2    | Enabled                           | Commercial+ | Sangoma   |
| pinsets           | 17.0.3    | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro        | 17.0.2    | Enabled                           | Commercial  | Sangoma   |
| pm2               | 17.0.3.1  | Enabled                           | AGPLv3+     | Sangoma   |
| presencestate     | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
| printextensions   | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| queueprio         | 17.0.1.4  | Enabled                           | GPLv3+      | Sangoma   |
| queues            | 17.0.1.6  | Enabled                           | GPLv2+      | Sangoma   |
| queuestats        | 17.0.1.6  | Enabled                           | Commercial  | Sangoma   |
| qxact_reports     | 17.0.2    | Enabled                           | Commercial  | Sangoma   |
| recording_report  | 17.0.3.6  | Enabled                           | Commercial  | Sangoma   |
| recordings        | 17.0.2.2  | Enabled                           | GPLv3+      | Sangoma   |
| restapps          | 17.0.1.11 | Enabled                           | Commercial  | Sangoma   |
| ringgroups        | 17.0.2.4  | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect    | 17.0.1.20 | Enabled                           | Commercial  | Sangoma   |
| sangomartapi      | 17.0.1.11 | Enabled                           | Commercial  | Sangoma   |
| setcid            | 17.0.1.2  | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings       | 17.0.6.3  | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation        | 17.0.3.3  | Enabled                           | Commercial  | Sangoma   |
| sms               | 17.0.1.7  | Enabled                           | Commercial  | Sangoma   |
| smsplus           | 17.0.2    | Enabled                           | Commercial  | Sangoma   |
| soundlang         | 17.0.4    | Enabled                           | GPLv3+      | Sangoma   |
| sysadmin          | 17.0.1.46 | Enabled                           | Commercial  | Sangoma   |
| timeconditions    | 17.0.1.13 | Enabled                           | GPLv3+      | Sangoma   |
| tts               | 17.0.1.1  | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines        | 17.0.1    | Enabled                           | AGPLv3      | Sangoma   |
| ucp               | 17.0.4.13 | Enabled                           | AGPLv3+     | Sangoma   |
| userman           | 17.0.6.16 | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast           | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| vmnotify          | 17.0.1.5  | Enabled                           | Commercial  | Sangoma   |
| voicemail         | 17.0.5.13 | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report  | 17.0.1.1  | Enabled                           | Commercial  | Sangoma   |
| vqplus            | 17.0.1.13 | Enabled                           | Commercial  | Sangoma   |
| weakpasswords     | 17.0.1    | Enabled                           | GPLv3+      | Sangoma   |
| webrtc            | 17.0.2.1  | Enabled                           | GPLv3+      | Sangoma   |
+-------------------+-----------+-----------------------------------+-------------+-----------+

**Comment by jissphilip** [comment]
endpoint-17.0.1.47

**Comment by icciaaron** [comment]
BOOM! Fixed!

ICCI loves SANGOMA!
