### ISSUE TITLE
[bug]: execution via ansible hangs indefinitely

### ISSUE THREAD

**Issue by doczkal** [FreePBX/issue-tracker#69]
### FreePBX Version

FreePBX 17

### Issue Description

Running https://github.com/FreePBX/sng_freepbx_debian_install/blob/master/sng_freepbx_debian_install.sh via ansible hangs indefinitely if cli/php.ini is modified. **php.ini** was modified to include the ioncube loader.

with Ansible #24 you get 1) deterministic results 2) a readable IaaC 3) option for repeatable runs
...

### Operating Environment

Raspberry Pi OS Lite
Release date: March 15th 2024
System: 64-bit
Kernel version: 6.6
Debian version: 12 (bookworm)
Size: 414MB

### Relevant log output

```shell
Package configurationcal/src/freepbx# tail -f /var/log/pbx/freepbx17-install-2024.04.01-17.11.39.log 


   ┌────────────────────┤ Modified configuration file ├────────────────────┐
   │ php.ini: A new version (/usr/lib/php/8.2/php.ini-production.cli) of   │ 
   │ configuration file /etc/php/8.2/cli/php.ini is available, but the     │ 
   │ version installed currently has been locally modified.                │ 
   │                                                                       │ 
   │ What do you want to do about modified configuration file php.ini?     │ 
   │                                                                       │ 
   │         install the package maintainer's version                      │ 
   │         keep the local version currently installed                    │ 
   │         show the differences between the versions                     │ 
   │         show a side-by-side difference between the versions           │ 
   │         start a new shell to examine the situation                    │ 
   │                                                                       │ 
   │                                                                       │ 
   │                                <Ok>                                   │ 
   │                                                                       │ 
   └───────────────────────────────────────────────────────────────────────┘
```

root@asterisk:/etc/php# diff 8.2/cli/php.ini /usr/lib/php/8.2/php.ini-production.cli 
```
967d966
< zend_extension=/usr/lib/php/20220829/ioncube_loader_lin_8.2.so
1207,1209d1205
< ; Allow or prevent reconnect
< mysqli.reconnect = Off
< 
1444a1441,1445
> ; Debian Default Value: 0
> ; This is disabled in the Debian packages due to the strict permissions
> ; on /var/lib/php. Instead, GC is performed through /etc/cron.d/php,
> ; which uses the session.gc_maxlifetime setting. Please, check
> ; /usr/share/doc/php8.2-common/README.Debian.gz for further reference.
```

**Comment by jfinstrom** [comment]
In normal usage this is acceptable as the user would want the option to make the choice... In ansible you need to pass the environment variable:
    `DEBIAN_FRONTEND: noninteractive` so dpkg knows it shouldn't expect a human.

**Comment by ramarajan222** [comment]
Hi @doczkal 

We were unable to reproduce this issue on a local Ansible setup, could provide the exact steps to reproduce the issue?
Even we cloned the ansible code chrsmj:ansible-ize  and the installation was completed successfully.

**Comment by chrsmj** [comment]
Appreciate the feedback @ramarajan222 but perhaps @doczkal could post the Ansible Role they ran ?  As it might be a minimal wrapper role around the shell script installer -- using eg. [ansible.builtin.shell module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html) -- and not an attempt at a 1:1 rewrite/translation from bash to ansible eg. [chrsmj:ansible-ize fork](https://github.com/chrsmj/sng_freepbx_debian_install/tree/ansible-ize).

**Comment by doczkal** [comment]
> Appreciate the feedback @ramarajan222 but perhaps @doczkal could post the Ansible Role they ran ? As it might be a minimal wrapper role around the shell script installer -- using eg. [ansible.builtin.shell module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html) -- and not an attempt at a 1:1 rewrite/translation from bash to ansible eg. [chrsmj:ansible-ize fork](https://github.com/chrsmj/sng_freepbx_debian_install/tree/ansible-ize).

Yes, exactly as you assumed. I will start a new try maybe later this year.
