### ISSUE TITLE
[bug]: BMO Hooks doesn't trim whitespace

### ISSUE THREAD

**Issue by jfinstrom** [FreePBX/issue-tracker#71]
### FreePBX Version

FreePBX 16

### Issue Description

Adding a hook to module.xml is whitespace-sensitive. This means a subtle difference in spacing can cause the hook to fail.

* **Correct:** 
   `<method callingMethod="getHeaders" class="Findmefollow" namespace="FreePBX\modules">bulkhandlerGetHeaders</method>`

* **Incorrect (due to extra whitespace):**
   `<method callingMethod="getHeaders" class="Findmefollow" namespace="FreePBX\modules">bulkhandlerGetHeaders  </method>`

**Proposed Solution:**

Trim whitespace from the method name within the `UpdateBMOHooks` method in `/amp_conf/htdocs/admin/libraries/BMO/Hooks.class.php`.  As method names shouldn't contain whitespace, this change is unlikely to cause side effects.

**Impact:**

This bug makes it difficult to add hooks reliably, as the extra whitespace could be hard to detect visually as the formatting will seem correct.

### Operating Environment

All supported versions of FreePBX on all platforms use this code.

**Comment by kapilgupta01** [comment]
Hi James

thanks for reporting this issue. Pushed the code to latest 17 framework. 

Regards
Kapil
