### ISSUE TITLE
[improvement]: OS Version of Debian

### ISSUE THREAD

**Issue by hbhoge74** [FreePBX/issue-tracker#72]
### FreePBX Version

FreePBX 17

### Improvement Description

Ran into an issue with the installation of Beta 17.
Debian 12.5 Standard worked normally.
Debian 12.2 netInstall worked normally.
[debian-live-12.5.0-amd64-cinnamon failed to complete the installation.

**Comment by jcolp** [comment]
You're going to need to state what actually happened beyond that it failed to complete, including providing output and log.
