### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by cchalifo999** [FreePBX/issue-tracker#75]
### FreePBX Version

FreePBX 17

### Issue Description

backup to minio s3 
it is the same with freepbx 16 to

### Operating Environment

os :debain 12 
astrick default with install script for your repo
fwconsole ma list output:
+-------------------+------------+-----------------------------------+-------------+-----------+
| Module            | Version    | Status                            | License     | Signature |
+-------------------+------------+-----------------------------------+-------------+-----------+
| amd               | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| announcement      | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| areminder         | 17.0.3.9   | Enabled                           | Commercial  | Sangoma   |
| arimanager        | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli      | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo      | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| backup            | 17.0.5.14  | Enabled                           | GPLv3+      | Sangoma   |
| blacklist         | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| broadcast         | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| builtin           |            | Enabled                           |             | Unsigned  |
| bulkhandler       | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| calendar          | 17.0.4.6   | Enabled                           | GPLv3+      | Sangoma   |
| callaccounting    | 17.0.4     | Enabled                           | Commercial+ | Sangoma   |
| callback          | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| callerid          | 17.0.1     | Enabled                           | Commercial  | Sangoma   |
| callforward       | 17.0.1.3   | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit         | 17.0.1.2   | Enabled                           | Commercial  | Sangoma   |
| callrecording     | 17.0.3.6   | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting       | 17.0.3.2   | Enabled                           | GPLv3+      | Sangoma   |
| cdr               | 17.0.4.13  | Enabled                           | GPLv3+      | Sangoma   |
| cel               | 17.0.2.7   | Enabled                           | GPLv3+      | Sangoma   |
| certman           | 17.0.3.7   | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| conferences       | 17.0.3.1   | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro    | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| configedit        | 17.0.1.1   | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager    | 17.0.5.6   | Enabled                           | GPLv3+      | Sangoma   |
| core              | 17.0.9.33  | Enabled                           | GPLv3+      | Sangoma   |
| cos               | 17.0.1.1   | Enabled                           | Commercial  | Sangoma   |
| customappsreg     | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| dashboard         | 17.0.4.2   | Enabled                           | AGPLv3+     | Sangoma   |
| daynight          | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| dictate           | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| directory         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| donotdisturb      | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| endpoint          | 17.0.1.50  | Enabled                           | Commercial  | Sangoma   |
| extensionroutes   | 17.0.1     | Enabled                           | Commercial  | Sangoma   |
| extensionsettings | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| fax               | 17.0.3.2   | Enabled                           | GPLv3+      | Sangoma   |
| faxpro            | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| featurecodeadmin  | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| filestore         | 17.0.2.9   | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow      | 17.0.4.6   | Enabled                           | GPLv3+      | Sangoma   |
| firewall          | 17.0.1.13  | Enabled                           | AGPLv3+     | Sangoma   |
| framework         | 17.0.15.13 | Enabled                           | GPLv2+      | Sangoma   |
| hotelwakeup       | 17.0.1.5   | Enabled                           | GPLv2       | Sangoma   |
| iaxsettings       | 17.0.1     | Enabled                           | AGPLv3      | Sangoma   |
| infoservices      | 17.0.1     | Enabled                           | GPLv2+      | Sangoma   |
| ivr               | 17.0.5     | Enabled                           | GPLv3+      | Sangoma   |
| languages         | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| logfiles          | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| manager           | 17.0.3     | Enabled                           | GPLv2+      | Sangoma   |
| miscapps          | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| miscdests         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| music             | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| oembranding       |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| paging            | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro         | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| parking           | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| parkpro           | 17.0.1.4   | Enabled                           | Commercial  | Sangoma   |
| pbxmfa            | 17.0.2     | Enabled                           | Commercial+ | Sangoma   |
| pinsets           | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro        | 17.0.2     | Enabled                           | Commercial  | Sangoma   |
| pm2               | 17.0.3.1   | Enabled                           | AGPLv3+     | Sangoma   |
| presencestate     | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| printextensions   | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| queueprio         | 17.0.1.4   | Enabled                           | GPLv3+      | Sangoma   |
| queues            | 17.0.1.7   | Enabled                           | GPLv2+      | Sangoma   |
| queuestats        | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| qxact_reports     | 17.0.2     | Enabled                           | Commercial  | Sangoma   |
| recording_report  | 17.0.3.6   | Enabled                           | Commercial  | Sangoma   |
| recordings        | 17.0.2.2   | Enabled                           | GPLv3+      | Sangoma   |
| restapps          | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| ringgroups        | 17.0.2.4   | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect    | 17.0.1.20  | Enabled                           | Commercial  | Sangoma   |
| sangomartapi      | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| setcid            | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings       | 17.0.6.3   | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation        | 17.0.3.3   | Enabled                           | Commercial  | Sangoma   |
| sms               | 17.0.1.8   | Enabled                           | Commercial  | Sangoma   |
| smsplus           | 17.0.3     | Enabled                           | Commercial  | Sangoma   |
| soundlang         | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| sysadmin          | 17.0.1.48  | Enabled                           | Commercial  | Sangoma   |
| timeconditions    | 17.0.1.13  | Enabled                           | GPLv3+      | Sangoma   |
| tts               | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines        | 17.0.1     | Enabled                           | AGPLv3      | Sangoma   |
| ucp               | 17.0.4.13  | Enabled                           | AGPLv3+     | Sangoma   |
| userman           | 17.0.6.16  | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast           | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| vmnotify          | 17.0.1.5   | Enabled                           | Commercial  | Sangoma   |
| voicemail         | 17.0.5.14  | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report  | 17.0.1.1   | Enabled                           | Commercial  | Sangoma   |
| vqplus            | 17.0.1.13  | Enabled                           | Commercial  | Sangoma   |
| weakpasswords     | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| webrtc            | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
+-------------------+------------+-----------------------------------+-------------+-----------+

For Use With AWS S3 :
general:
path /
 Bucket Name  freepbx
 AWS Region  us-east-1
 
advanced:
custom enpoint : s3.cchalifo.click/

policey for bucket:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:DeleteBucketPolicy",
                "s3:GetBucketPolicy",
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:PutBucketPolicy"
            ],
            "Resource": [
                "arn:aws:s3:::freepbx"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:AbortMultipartUpload"
            ],
            "Resource": [
                "arn:aws:s3:::freepbx/*"
            ]
        }
    ]
}

### Relevant log output

```shell
Backup

Running with: /usr/sbin/fwconsole backup --backup='128b3f9c-21b5-407f-8fbe-254822bdd592' --transaction='f5be3e3f-8ee8-4f3e-9783-7ac017705718' >> /var/log/asterisk/backup_f5be3e3f-8ee8-4f3e-9783-7ac017705718_out.log 2> /var/log/asterisk/backup_f5be3e3f-8ee8-4f3e-9783-7ac017705718_err.log & echo $!
Running Backup ID: 128b3f9c-21b5-407f-8fbe-254822bdd592
Transaction: f5be3e3f-8ee8-4f3e-9783-7ac017705718
Starting backup 77
This backup will be stored locally and is subject to maintenance settings
Backup File Name: 20240407-204943-1712522983-17.0.15.13-694373269.tar.gz
Working with amd module
Exporting KVStore from Amd
	Adding module manifest for amd
Working with announcement module
	Adding module manifest for announcement
Working with areminder module
	Adding module manifest for areminder
Working with arimanager module
Exporting Databases from arimanager
Exporting Advanced settings from arimanager
	Adding module manifest for arimanager
Working with backup module
Exporting KVStore from Backup
	Adding module manifest for backup
Working with blacklist module
Exporting Feature Codes from blacklist
	Adding module manifest for blacklist
Working with broadcast module
Exporting Databases from broadcast
	Adding module manifest for broadcast
Working with calendar module
	Adding module manifest for calendar
Working with callaccounting module
Exporting Databases from callaccounting
Starting mysql dumps of : callaccounting_ratedeck callaccounting_rate_patterns callaccounting_decks_trunks callaccounting_cdr
Completed mysql dumps of : callaccounting_ratedeck callaccounting_rate_patterns callaccounting_decks_trunks callaccounting_cdr
Exporting Advanced settings from callaccounting
	Adding file to tar: files/tmp/callaccounting_dump/callaccounting.sql
	Adding module manifest for callaccounting
Working with callback module
	The module callback returned no data, No backup created
Working with callerid module
	The module callerid returned no data, No backup created
Working with callforward module
Exporting Feature Codes from callforward
	Adding module manifest for callforward
Working with calllimit module
	The module calllimit returned no data, No backup created
Working with callrecording module
Exporting Advanced settings from callrecording
	Adding module manifest for callrecording
Working with callwaiting module
Exporting Feature Codes from callwaiting
	Adding module manifest for callwaiting
Working with cdr module
Starting mysql dumps of : cdr
Completed mysql dumps of : cdr
	Adding directory to tar: /tmp/cdr_dump
	Adding file to tar: files/tmp/cdr_dump/cdr.sql.gz
	Adding module manifest for cdr
Working with cel module
Starting mysql dumps of : cel
Completed mysql dumps of : cel
Exporting Advanced settings from cel
	Adding directory to tar: /tmp/cel_dump
	Adding file to tar: files/tmp/cel_dump/cel.sql.gz
	Adding module manifest for cel
Working with certman module
	Adding directory to tar: /etc/asterisk/keys
	Adding directory to tar: /etc/asterisk/keys/integration
	Adding file to tar: files/etc/asterisk/keys/default.crt
	Adding file to tar: files/etc/asterisk/keys/ca.key
	Adding file to tar: files/etc/asterisk/keys/integration/webserver.key
	Adding file to tar: files/etc/asterisk/keys/integration/certificate.pem
	Adding file to tar: files/etc/asterisk/keys/integration/webserver.crt
	Adding file to tar: files/etc/asterisk/keys/default.csr
	Adding file to tar: files/etc/asterisk/keys/ca.crt
	Adding file to tar: files/etc/asterisk/keys/default.pem
	Adding file to tar: files/etc/asterisk/keys/default.key
	Adding file to tar: files/etc/asterisk/keys/ca.cfg
	Adding module manifest for certman
Working with cidlookup module
	Adding module manifest for cidlookup
Working with conferences module
Exporting KVStore from Conferences
Exporting Feature Codes from conferences
Exporting Advanced settings from conferences
	Adding module manifest for conferences
Working with conferencespro module
	The module conferencespro returned no data, No backup created
Working with contactmanager module
Exporting KVStore from Contactmanager
Exporting Feature Codes from contactmanager
Exporting Advanced settings from contactmanager
	Adding module manifest for contactmanager
Working with core module
Starting mysql dumps of : devices sip dahdi iax
Completed mysql dumps of : devices sip dahdi iax
Exporting Feature Codes from core
Exporting Advanced settings from core
Exporting KVStore from Core
	Adding file to tar: files/tmp/Devices_dump/Devices.sql
	Adding module manifest for core
Working with cos module
Exporting KVStore from Cos
Exporting Advanced settings from cos
	Adding module manifest for cos
	Skpping cos which depends on framework because framework is a system requirement. Framework should be removed as a dependency
Working with customappsreg module
Exporting KVStore from Customappsreg
	Adding module manifest for customappsreg
Working with dashboard module
Exporting Advanced settings from dashboard
	Adding module manifest for dashboard
Working with daynight module
Exporting Databases from daynight
Exporting Feature Codes from daynight
Exporting Advanced settings from daynight
	Adding module manifest for daynight
Working with dictate module
Exporting Feature Codes from dictate
	Adding module manifest for dictate
Working with directory module
	Adding module manifest for directory
Working with donotdisturb module
Exporting Feature Codes from donotdisturb
	Adding module manifest for donotdisturb
Working with endpoint module
Exporting Advanced settings from endpoint
Exporting Feature Codes from endpoint
Exporting Databases from endpoint
Exporting KVStore from Endpoint
	Adding module manifest for endpoint
Working with extensionroutes module
Exporting Databases from extensionroutes
	Adding module manifest for extensionroutes
Working with fax module
Exporting KVStore from Fax
Exporting Feature Codes from fax
	Adding module manifest for fax
Working with faxpro module
	Adding module manifest for faxpro
Working with filestore module
Exporting KVStore from Filestore
	Adding module manifest for filestore
Working with findmefollow module
Exporting Databases from findmefollow
Exporting Feature Codes from findmefollow
	Adding module manifest for findmefollow
Working with firewall module
Exporting KVStore from Firewall
	Adding file to tar: files/etc/firewall-4.rules
	Adding file to tar: files/etc/firewall-6.rules
	Adding module manifest for firewall
Working with framework module
	Adding module manifest for framework
Working with hotelwakeup module
Exporting Feature Codes from hotelwakeup
	Adding module manifest for hotelwakeup
Working with iaxsettings module
	Adding module manifest for iaxsettings
Working with infoservices module
Exporting Feature Codes from infoservices
Exporting Advanced settings from infoservices
	Adding module manifest for infoservices
Working with ivr module
	Adding module manifest for ivr
Working with languages module
	Adding module manifest for languages
Working with logfiles module
Exporting Databases from logfiles
	Adding module manifest for logfiles
Working with manager module
Exporting Databases from manager
	Adding module manifest for manager
Working with miscapps module
Exporting Feature Codes from miscapps
	Adding module manifest for miscapps
Working with miscdests module
	The module miscdests returned no data, No backup created
Working with music module
Exporting Advanced settings from music
	Adding directory to tar: /var/lib/asterisk/moh
	Adding directory to tar: /var/lib/asterisk/moh/.nomusic_reserved
	Adding file to tar: files/var/lib/asterisk/moh/macroform-the_simplicity.wav
	Adding file to tar: files/var/lib/asterisk/moh/macroform-the_simplicity.alaw
	Adding file to tar: files/var/lib/asterisk/moh/manolo_camp-morning_coffee.wav
	Adding file to tar: files/var/lib/asterisk/moh/CHANGES-asterisk-moh-opsound-sln16
	Adding file to tar: files/var/lib/asterisk/moh/reno_project-system.ulaw
	Adding file to tar: files/var/lib/asterisk/moh/macroform-cold_day.g722
	Adding file to tar: files/var/lib/asterisk/moh/.asterisk-moh-opsound-ulaw
	Adding file to tar: files/var/lib/asterisk/moh/LICENSE-asterisk-moh-opsound-wav
	Adding file to tar: files/var/lib/asterisk/moh/CHANGES-asterisk-moh-opsound-g722
	Adding file to tar: files/var/lib/asterisk/moh/manolo_camp-morning_coffee.ulaw
	Adding file to tar: files/var/lib/asterisk/moh/manolo_camp-morning_coffee.alaw
	Adding file to tar: files/var/lib/asterisk/moh/.nomusic_reserved/silence.wav
	Adding file to tar: files/var/lib/asterisk/moh/.asterisk-moh-opsound-sln16
	Adding file to tar: files/var/lib/asterisk/moh/macroform-the_simplicity.ulaw
	Adding file to tar: files/var/lib/asterisk/moh/CREDITS-asterisk-moh-opsound-wav
	Adding file to tar: files/var/lib/asterisk/moh/macroform-robot_dity.ulaw
	Adding file to tar: files/var/lib/asterisk/moh/CHANGES-asterisk-moh-opsound-alaw
	Adding file to tar: files/var/lib/asterisk/moh/CREDITS-asterisk-moh-opsound-sln16
	Adding file to tar: files/var/lib/asterisk/moh/CREDITS-asterisk-moh-opsound-ulaw
	Adding file to tar: files/var/lib/asterisk/moh/macroform-robot_dity.alaw
	Adding file to tar: files/var/lib/asterisk/moh/.asterisk-moh-opsound-alaw
	Adding file to tar: files/var/lib/asterisk/moh/manolo_camp-morning_coffee.g722
	Adding file to tar: files/var/lib/asterisk/moh/CHANGES-asterisk-moh-opsound-ulaw
	Adding file to tar: files/var/lib/asterisk/moh/macroform-robot_dity.g722
	Adding file to tar: files/var/lib/asterisk/moh/.asterisk-moh-opsound-g722
	Adding file to tar: files/var/lib/asterisk/moh/macroform-cold_day.sln16
	Adding file to tar: files/var/lib/asterisk/moh/macroform-cold_day.alaw
	Adding file to tar: files/var/lib/asterisk/moh/CREDITS-asterisk-moh-opsound-g722
	Adding file to tar: files/var/lib/asterisk/moh/macroform-the_simplicity.g722
	Adding file to tar: files/var/lib/asterisk/moh/manolo_camp-morning_coffee.sln16
	Adding file to tar: files/var/lib/asterisk/moh/reno_project-system.alaw
	Adding file to tar: files/var/lib/asterisk/moh/CHANGES-asterisk-moh-opsound-wav
	Adding file to tar: files/var/lib/asterisk/moh/LICENSE-asterisk-moh-opsound-ulaw
	Adding file to tar: files/var/lib/asterisk/moh/LICENSE-asterisk-moh-opsound-alaw
	Adding file to tar: files/var/lib/asterisk/moh/.asterisk-moh-opsound-sln
	Adding file to tar: files/var/lib/asterisk/moh/LICENSE-asterisk-moh-opsound-g722
	Adding file to tar: files/var/lib/asterisk/moh/macroform-the_simplicity.sln16
	Adding file to tar: files/var/lib/asterisk/moh/macroform-cold_day.ulaw
	Adding file to tar: files/var/lib/asterisk/moh/LICENSE-asterisk-moh-opsound-sln16
	Adding file to tar: files/var/lib/asterisk/moh/macroform-cold_day.wav
	Adding file to tar: files/var/lib/asterisk/moh/macroform-robot_dity.sln16
	Adding file to tar: files/var/lib/asterisk/moh/reno_project-system.wav
	Adding file to tar: files/var/lib/asterisk/moh/reno_project-system.sln16
	Adding file to tar: files/var/lib/asterisk/moh/reno_project-system.g722
	Adding file to tar: files/var/lib/asterisk/moh/CREDITS-asterisk-moh-opsound-alaw
	Adding file to tar: files/var/lib/asterisk/moh/macroform-robot_dity.wav
	Adding module manifest for music
Working with paging module
Exporting KVStore from Paging
Exporting Feature Codes from paging
	Adding module manifest for paging
Working with pagingpro module
Exporting Databases from pagingpro
Exporting Advanced settings from pagingpro
	Adding module manifest for pagingpro
Working with parking module
	Adding module manifest for parking
Working with parkpro module
Exporting Feature Codes from parkpro
	Adding module manifest for parkpro
Working with pinsets module
	Adding module manifest for pinsets
Working with pm2 module
Exporting Advanced settings from pm2
	Adding module manifest for pm2
Working with presencestate module
	Adding module manifest for presencestate
Working with printextensions module
Exporting KVStore from Printextensions
	Adding module manifest for printextensions
Working with queueprio module
Exporting Databases from queueprio
Exporting Feature Codes from queueprio
Exporting Advanced settings from queueprio
	Adding module manifest for queueprio
Working with queues module
Exporting Advanced settings from queues
Exporting Feature Codes from queues
Exporting Databases from queues
Exporting KVStore from Queues
	Adding module manifest for queues
Working with queuestats module
Exporting Advanced settings from queuestats
Exporting KVStore from Queuestats
Exporting KVStore based on ids  widgets,servers
	Adding module manifest for queuestats
Working with qxact_reports module
Exporting Databases from qxact_reports
Starting mysql dumps of : qxact_calls qxact_agent_calls qxact_agent_actions qxact_system_events qxact_reports qxact_reports_scheduler
Completed mysql dumps of : qxact_calls qxact_agent_calls qxact_agent_actions qxact_system_events qxact_reports qxact_reports_scheduler
	Adding file to tar: files/tmp/qxact_reports_dump/qxact_reports.sql
	Adding module manifest for qxact_reports
Working with recording_report module
Exporting KVStore from Recording_report
Exporting Databases from recording_report
Starting mysql dumps of : recording_report recording_files
Completed mysql dumps of : recording_report recording_files
By default backup file does not includes the call recordings so if you want to add recordings please add the path under custom directory option
	Adding file to tar: files/tmp/recording_report_dump/recording_report.sql
	Adding module manifest for recording_report
Working with recordings module
Exporting Feature Codes from recordings
	Adding module manifest for recordings
Working with restapps module
Exporting Feature Codes from restapps
	Adding module manifest for restapps
Working with ringgroups module
Exporting Advanced settings from ringgroups
	Adding module manifest for ringgroups
Working with sangomaconnect module
Exporting Advanced settings from sangomaconnect
Exporting KVStore from Sangomaconnect
Exporting Databases from sangomaconnect
	Adding module manifest for sangomaconnect
Working with setcid module
	The module setcid returned no data, No backup created
Working with sipsettings module
Exporting KVStore from Sipsettings
	Adding module manifest for sipsettings
Working with sipstation module
Exporting KVStore from Sipstation
Exporting Advanced settings from sipstation
	Adding module manifest for sipstation
	Skpping sipstation which depends on framework because framework is a system requirement. Framework should be removed as a dependency
Working with sms module
Exporting Databases from sms
Starting mysql dumps of : sms_messages sms_dids sms_routing sms_media sms_webhooks
Completed mysql dumps of : sms_messages sms_dids sms_routing sms_media sms_webhooks
	Adding file to tar: files/tmp/sms_dump/sms.sql
	Adding module manifest for sms
Working with soundlang module
	Adding module manifest for soundlang
Working with sysadmin module
Exporting Databases from sysadmin
Exporting KVStore from Sysadmin
Exporting Advanced settings from sysadmin
	Adding module manifest for sysadmin
	Skpping sysadmin which depends on framework because framework is a system requirement. Framework should be removed as a dependency
Working with timeconditions module
Exporting Databases from timeconditions
Exporting Feature Codes from timeconditions
Exporting Advanced settings from timeconditions
	Adding module manifest for timeconditions
Working with tts module
Exporting Databases from tts
	Adding module manifest for tts
Working with ttsengines module
	The module ttsengines returned no data, No backup created
Working with ucp module
Exporting Databases from ucp
Exporting Advanced settings from ucp
	Adding module manifest for ucp
Working with userman module
Exporting Databases from userman
Exporting KVStore from Userman
Exporting Advanced settings from userman
Exporting Module XML userman
	Adding module manifest for userman
	Depend field was blank for userman. Skipping because not sure what to do
Working with vmblast module
Exporting Databases from vmblast
	Adding module manifest for vmblast
Working with vmnotify module
Exporting Databases from vmnotify
	Adding module manifest for vmnotify
Working with voicemail module
Exclude Greeeting ?no
Exclude VMRecords ?no
Exporting Feature Codes from voicemail
Exporting Advanced settings from voicemail
	Adding file to tar: files/etc/asterisk/voicemail.conf
	Adding module manifest for voicemail
Working with vqplus module
	Adding module manifest for vqplus
Working with webrtc module
Exporting Databases from webrtc
Exporting KVStore from Webrtc
	Adding module manifest for webrtc
	Adding custom directory to tar: customdir/etc/asterisk
Starting Cleaning up
Cleaning up data generated by Callaccounting
	Removing /tmp/callaccounting_dump
Cleaning up data generated by Cdr
	Removing /tmp/cdr_dump
Cleaning up data generated by Cel
	Removing /tmp/cel_dump
Cleaning up data generated by Core
	Removing /tmp/Devices_dump
Cleaning up data generated by Qxact_reports
	Removing /tmp/qxact_reports_dump
Cleaning up data generated by Recording_report
	Removing /tmp/recording_report_dump
Cleaning up data generated by Sms
	Removing /tmp/sms_dump
Finished Cleaning up
Finished created backup file: 20240407-204943-1712522983-17.0.15.13-694373269.tar.gz
Performing Local Maintenance
Finished Local Maintenance
Performing Remote Maintenance
Error executing "ListObjectsV2" on "https://freepbx.s3.cchalifo.click/?list-type=2&prefix=&delimiter=%2F"; AWS HTTP error: cURL error 6: Could not resolve host: freepbx.s3.cchalifo.click (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://freepbx.s3.cchalifo.click/?list-type=2&prefix=&delimiter=%2F
Finished Remote Maintenance
Saving to selected Filestore locations
Error executing "ListObjectsV2" on "https://freepbx.s3.cchalifo.click/?list-type=2&prefix=20240407-204943-1712522983-17.0.15.13-694373269.tar.gz%2F&max-keys=1"; AWS HTTP error: cURL error 6: Could not resolve host: freepbx.s3.cchalifo.click (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://freepbx.s3.cchalifo.click/?list-type=2&prefix=20240407-204943-1712522983-17.0.15.13-694373269.tar.gz%2F&max-keys=1
Finished Saving to selected Filestore locations
There were errors during the backup process
	Error executing "ListObjectsV2" on "https://freepbx.s3.cchalifo.click/?list-type=2&prefix=&delimiter=%2F"; AWS HTTP error: cURL error 6: Could not resolve host: freepbx.s3.cchalifo.click (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://freepbx.s3.cchalifo.click/?list-type=2&prefix=&delimiter=%2F
	Error executing "ListObjectsV2" on "https://freepbx.s3.cchalifo.click/?list-type=2&prefix=20240407-204943-1712522983-17.0.15.13-694373269.tar.gz%2F&max-keys=1"; AWS HTTP error: cURL error 6: Could not resolve host: freepbx.s3.cchalifo.click (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://freepbx.s3.cchalifo.click/?list-type=2&prefix=20240407-204943-1712522983-17.0.15.13-694373269.tar.gz%2F&max-keys=1
There were warnings during the backup process
	The module callback returned no data, No backup created
	The module callerid returned no data, No backup created
	The module calllimit returned no data, No backup created
	The module conferencespro returned no data, No backup created
	The module miscdests returned no data, No backup created
	The module setcid returned no data, No backup created
	The module ttsengines returned no data, No backup created

FreePBX®
FreePBX is a registered trademark of
Sangoma Technologies Inc.
FreePBX 17.0.15.13 is licensed under the GPL
Copyright© 2007-2024
www.sangoma.com
```

**Comment by prasanthcode4** [comment]
hi @cchalifo999 , This error means there's a DNS issue, as the system can't find the IP address for the given hostname.
Please check the AWS details in the filestore module

**Comment by cchalifo999** [comment]
> hi @cchalifo999 , This error means there's a DNS issue, as the system can't find the IP address for the given hostname. Please check the AWS details in the filestore module

i did chceck AWS details in the filestore module i can conet to it from all of my other computers to my minio server

**Comment by kapilgupta01** [comment]
Hi @cchalifo999   Error is in below step so can you please check why its failed to resolve "freepbx.s3.cchalifo.click" from your machine. 

"Error executing "ListObjectsV2" on "https://freepbx.s3.cchalifo.click/?list-type=2&prefix=20240407-204943-1712522983-17.0.15.13-694373269.tar.gz%2F&max-keys=1"; AWS HTTP error: cURL error 6: Could not resolve host: freepbx.s3.cchalifo.click (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://freepbx.s3.cchalifo.click/?list-type=2&prefix=20240407-204943-1712522983-17.0.15.13-694373269.tar.gz%2F&max-keys=1
"
