### ISSUE TITLE
[bug]: refresh contact on sangoma phone desktop

### ISSUE THREAD

**Issue by jcattan** [FreePBX/issue-tracker#80]
### FreePBX Version

FreePBX 15

### Issue Description

when add edit remove contact in contact manager, it doesn't refresh on sangoma desktop. it works nice with sangoma talk.

### Operating Environment

Asterisk 18.20.2, Copyright (C) 1999 - 2022, Sangoma Technologies Corporation and others.

+---------------------+------------+----------+------------+-----------+
| Module              | Version    | Status   | License    | Signature |
+---------------------+------------+----------+------------+-----------+
| accountcodepreserve | 13.0.2.2   | Enabled  | GPLv2      | Sangoma   |
| announcement        | 15.0.3.13  | Enabled  | GPLv3+     | Sangoma   |
| arimanager          | 15.0.3.20  | Enabled  | GPLv3+     | Sangoma   |
| asterisk-cli        | 14.0.4     | Enabled  | GPLv3+     | Sangoma   |
| asteriskinfo        | 15.0.14    | Enabled  | GPLv3+     | Sangoma   |
| autoprov            | 15.0.0.5   | Disabled | GPLv3+     | Unknown   |
| backup              | 15.0.26    | Enabled  | GPLv3+     | Sangoma   |
| blacklist           | 15.0.4     | Enabled  | GPLv3+     | Sangoma   |
| builtin             |            | Enabled  |            | Unsigned  |
| bulkhandler         | 15.0.4     | Enabled  | GPLv3+     | Sangoma   |
| calendar            | 15.0.10    | Enabled  | GPLv3+     | Sangoma   |
| callforward         | 15.0.16    | Enabled  | AGPLv3+    | Sangoma   |
| callrecording       | 15.0.7.29  | Enabled  | AGPLv3+    | Sangoma   |
| callwaiting         | 15.0.4.6   | Enabled  | GPLv3+     | Sangoma   |
| cdr                 | 15.0.24.6  | Enabled  | GPLv3+     | Sangoma   |
| cel                 | 15.0.17    | Enabled  | GPLv3+     | Sangoma   |
| certman             | 15.0.49    | Enabled  | AGPLv3+    | Sangoma   |
| cidlookup           | 15.0.27    | Enabled  | GPLv3+     | Sangoma   |
| conferences         | 15.0.7.11  | Enabled  | GPLv3+     | Sangoma   |
| configedit          | 13.0.7.3   | Enabled  | AGPLv3+    | Sangoma   |
| contactmanager      | 15.0.13    | Enabled  | GPLv3+     | Sangoma   |
| core                | 15.0.22.34 | Enabled  | GPLv3+     | Sangoma   |
| customappsreg       | 15.0.14    | Enabled  | GPLv3+     | Sangoma   |
| dashboard           | 15.0.18    | Enabled  | AGPLv3+    | Sangoma   |
| daynight            | 15.0.12    | Enabled  | GPLv3+     | Sangoma   |
| dictate             | 15.0.7     | Enabled  | GPLv3+     | Sangoma   |
| directory           | 15.0.19    | Enabled  | GPLv3+     | Sangoma   |
| donotdisturb        | 15.0.10    | Enabled  | GPLv3+     | Sangoma   |
| endpoint            | 15.0.65.7  | Enabled  | Commercial | Sangoma   |
| extensionsettings   | 13.0.4     | Enabled  | GPLv3+     | Sangoma   |
| featurecodeadmin    | 13.0.6.11  | Enabled  | GPLv3+     | Sangoma   |
| filestore           | 15.0.9     | Enabled  | AGPLv3     | Sangoma   |
| findmefollow        | 15.0.37    | Enabled  | GPLv3+     | Sangoma   |
| firewall            | 15.0.43    | Enabled  | AGPLv3+    | Sangoma   |
| framework           | 15.0.37.4  | Enabled  | GPLv2+     | Sangoma   |
| fw_langpacks        | 14.0.1     | Enabled  | GPLv3+     | Sangoma   |
| gestionrenvois      | 15.0.1     | Enabled  |            | Unknown   |
| hotelwakeup         | 15.0.5.5   | Enabled  | GPLv2      | Sangoma   |
| infoservices        | 15.0.3     | Enabled  | GPLv2+     | Sangoma   |
| ivr                 | 15.0.30    | Enabled  | GPLv3+     | Sangoma   |
| languages           | 15.0.13    | Enabled  | GPLv3+     | Sangoma   |
| logfiles            | 15.0.15    | Enabled  | GPLv3+     | Sangoma   |
| manager             | 15.0.23    | Enabled  | GPLv2+     | Sangoma   |
| miscapps            | 15.0.10    | Enabled  | GPLv3+     | Sangoma   |
| miscdests           | 15.0.2.12  | Enabled  | GPLv3+     | Sangoma   |
| music               | 15.0.22    | Enabled  | GPLv3+     | Sangoma   |
| outroutemsg         | 15.0.9     | Enabled  | GPLv3+     | Sangoma   |
| paging              | 15.0.4.35  | Enabled  | GPLv3+     | Sangoma   |
| parking             | 15.0.15.4  | Enabled  | GPLv3+     | Sangoma   |
| pbdirectory         | 2.11.0.6   | Enabled  | GPLv3+     | Sangoma   |
| phonebook           | 15.0.12    | Enabled  | GPLv3+     | Sangoma   |
| phpinfo             | 13.0.2     | Enabled  | GPLv2+     | Sangoma   |
| pinsets             | 15.0.1.15  | Enabled  | GPLv3+     | Sangoma   |
| pm2                 | 15.0.10    | Enabled  | AGPLv3+    | Sangoma   |
| presencestate       | 15.0.11    | Enabled  | GPLv3+     | Sangoma   |
| printextensions     | 13.0.3.4   | Enabled  | GPLv3+     | Sangoma   |
| queues              | 15.0.39    | Enabled  | GPLv2+     | Sangoma   |
| recordings          | 15.0.6     | Enabled  | GPLv3+     | Sangoma   |
| restapi             | 13.0.21.2  | Enabled  | AGPLv3     | Sangoma   |
| restapps            | 15.0.42.5  | Enabled  | Commercial | Sangoma   |
| ringgroups          | 15.0.11.17 | Enabled  | GPLv3+     | Sangoma   |
| sangomaconnect      | 15.0.59.3  | Enabled  | Commercial | Sangoma   |
| sangomartapi        | 15.0.55.3  | Enabled  | Commercial | Sangoma   |
| setcid              | 15.0.9     | Enabled  | GPLv3+     | Sangoma   |
| sipsettings         | 15.0.11    | Enabled  | AGPLv3+    | Sangoma   |
| sms                 | 15.0.37    | Enabled  | Commercial | Sangoma   |
| soundlang           | 15.0.5.10  | Enabled  | GPLv3+     | Sangoma   |
| speeddial           | 2.11.0.4   | Enabled  | GPLv3+     | Sangoma   |
| sysadmin            | 15.0.33.14 | Enabled  | Commercial | Sangoma   |
| timeconditions      | 15.0.15.11 | Enabled  | GPLv3+     | Sangoma   |
| tts                 | 15.0.12    | Enabled  | GPLv3+     | Sangoma   |
| ttsengines          | 15.0.4.7   | Enabled  | AGPLv3     | Sangoma   |
| ucp                 | 15.0.15    | Enabled  | AGPLv3+    | Sangoma   |
| userman             | 15.0.69.19 | Enabled  | AGPLv3+    | Sangoma   |
| voicemail           | 15.0.32    | Enabled  | GPLv3+     | Sangoma   |
| weakpasswords       | 13.0.2     | Enabled  | GPLv3+     | Sangoma   |
| webrtc              | 15.0.10.13 | Enabled  | GPLv3+     | Sangoma   |
| xmpp                | 15.0.6.12  | Enabled  | AGPLv3     | Sangoma   |
| zulu                | 15.0.62    | Enabled  | Commercial | Sangoma   |

**Comment by jcattan** [comment]
up please i purchase licenses for that or tell me where can 'i report this bug

**Comment by kapilgupta01** [comment]
Hi @jcattan please either use "reload" option in the desktop client or re-login to get the fresh contacts. 
thanks

**Comment by jcattan** [comment]
I have already done this, I even uninstalled and reinstalled the application but without success for the contacts

**Comment by kapilgupta01** [comment]
Hi 

May be better to raise support request so our support team can help you out. 

You've opened a bug for a Commercial Module.

This Issue tracking system is for our Free and Open Source modules only.

Please open [a commercial support ticket [here](https://help.sangoma.com/)!.

If you are using FreePBX 12 or higher, please make sure you attach a Support Debug package (which is generated through the System Admin module) to the commercial support ticket.  Do not attach it to THIS bug tracker, as it may contain confidential information that will not be hidden from the general public.


Thank you for using FreePBX.
Kapil Gupta
