### ISSUE TITLE
[bug]: SangomaConnect CloudConnect Agent not available in the link provided to the module

### ISSUE THREAD

**Issue by LightningManGTS** [FreePBX/issue-tracker#81]
### FreePBX Version

FreePBX 17

### Issue Description

Just going to make a new issue for this since I added this on to another issue where the problem was slightly different (and lacked info from the original poster) 

I'm getting the below result from attempting to run the CloudConnect Agent install process

### Operating Environment

Debian 12 LXC (Proxmox, Unpriviledged), FreepPBX17, Asterisk 21

+-------------------+------------+-----------------------------------+-------------+-----------+
| Module            | Version    | Status                            | License     | Signature |
+-------------------+------------+-----------------------------------+-------------+-----------+
| amd               | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| announcement      | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| areminder         | 17.0.3.9   | Enabled                           | Commercial  | Sangoma   |
| arimanager        | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli      | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo      | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| backup            | 17.0.5.14  | Enabled                           | GPLv3+      | Sangoma   |
| blacklist         | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| broadcast         | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| builtin           |            | Enabled                           |             | Unsigned  |
| bulkhandler       | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| calendar          | 17.0.4.6   | Enabled                           | GPLv3+      | Sangoma   |
| callaccounting    | 17.0.4     | Enabled                           | Commercial+ | Sangoma   |
| callback          | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| callerid          | 17.0.1     | Enabled                           | Commercial  | Sangoma   |
| callforward       | 17.0.1.3   | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit         | 17.0.1.2   | Enabled                           | Commercial  | Sangoma   |
| callrecording     | 17.0.3.6   | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting       | 17.0.3.2   | Enabled                           | GPLv3+      | Sangoma   |
| cdr               | 17.0.4.13  | Enabled                           | GPLv3+      | Sangoma   |
| cel               | 17.0.2.7   | Enabled                           | GPLv3+      | Sangoma   |
| certman           | 17.0.3.7   | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| conferences       | 17.0.3.1   | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro    | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| configedit        | 17.0.1.1   | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager    | 17.0.5.6   | Enabled                           | GPLv3+      | Sangoma   |
| core              | 17.0.9.33  | Enabled                           | GPLv3+      | Sangoma   |
| cos               | 17.0.1.1   | Enabled                           | Commercial  | Sangoma   |
| customappsreg     | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| dashboard         | 17.0.4.2   | Enabled                           | AGPLv3+     | Sangoma   |
| daynight          | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| dictate           | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| directory         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| donotdisturb      | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| endpoint          | 17.0.1.53  | Enabled                           | Commercial  | Sangoma   |
| extensionroutes   | 17.0.1     | Enabled                           | Commercial  | Sangoma   |
| extensionsettings | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| fax               | 17.0.3.2   | Enabled                           | GPLv3+      | Sangoma   |
| faxpro            | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| featurecodeadmin  | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| filestore         | 17.0.2.9   | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow      | 17.0.4.6   | Enabled                           | GPLv3+      | Sangoma   |
| firewall          | 17.0.1.13  | Enabled                           | AGPLv3+     | Sangoma   |
| framework         | 17.0.15.13 | Enabled                           | GPLv2+      | Sangoma   |
| hotelwakeup       | 17.0.1.5   | Enabled                           | GPLv2       | Sangoma   |
| iaxsettings       | 17.0.1     | Enabled                           | AGPLv3      | Sangoma   |
| infoservices      | 17.0.1     | Enabled                           | GPLv2+      | Sangoma   |
| ivr               | 17.0.5     | Enabled                           | GPLv3+      | Sangoma   |
| languages         | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| logfiles          | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| manager           | 17.0.3     | Enabled                           | GPLv2+      | Sangoma   |
| miscapps          | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| miscdests         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| music             | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| oembranding       |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| paging            | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro         | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| parking           | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| parkpro           | 17.0.1.4   | Enabled                           | Commercial  | Sangoma   |
| pbxmfa            | 17.0.2     | Enabled                           | Commercial+ | Sangoma   |
| pinsets           | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro        | 17.0.2     | Enabled                           | Commercial  | Sangoma   |
| pm2               | 17.0.3.1   | Enabled                           | AGPLv3+     | Sangoma   |
| presencestate     | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| printextensions   | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| queueprio         | 17.0.1.4   | Enabled                           | GPLv3+      | Sangoma   |
| queues            | 17.0.1.7   | Enabled                           | GPLv2+      | Sangoma   |
| queuestats        | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| qxact_reports     | 17.0.2     | Enabled                           | Commercial  | Sangoma   |
| recording_report  | 17.0.3.6   | Enabled                           | Commercial  | Sangoma   |
| recordings        | 17.0.2.2   | Enabled                           | GPLv3+      | Sangoma   |
| restapps          | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| ringgroups        | 17.0.2.4   | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect    | 17.0.1.23  | Enabled                           | Commercial  | Sangoma   |
| sangomartapi      | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| setcid            | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings       | 17.0.6.3   | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation        | 17.0.3.3   | Enabled                           | Commercial  | Sangoma   |
| sms               | 17.0.1.8   | Enabled                           | Commercial  | Sangoma   |
| smsconnector      | 16.0.16    | Enabled                           | GPLv3+      | Unknown   |
| smsplus           | 17.0.3     | Enabled                           | Commercial  | Sangoma   |
| soundlang         | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| sysadmin          | 17.0.1.48  | Enabled                           | Commercial  | Sangoma   |
| timeconditions    | 17.0.1.13  | Enabled                           | GPLv3+      | Sangoma   |
| tts               | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines        | 17.0.1     | Enabled                           | AGPLv3      | Sangoma   |
| ucp               | 17.0.4.13  | Enabled                           | AGPLv3+     | Sangoma   |
| userman           | 17.0.6.16  | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast           | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| vmnotify          | 17.0.1.5   | Enabled                           | Commercial  | Sangoma   |
| voicemail         | 17.0.5.14  | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report  |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| vqplus            | 17.0.1.13  | Enabled                           | Commercial  | Sangoma   |
| weakpasswords     | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| webrtc            | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
+-------------------+------------+-----------------------------------+-------------+-----------+

### Relevant log output

```shell
Installation failed - Failed to download installer: https://connect.sangoma.com:443/static/files/service-proxy-client_1.2.3-1_x86_64.deb Error: Array ( [type] => 2 [message] => fopen(https://connect.sangoma.com:443/static/files/service-proxy-client_1.2.3-1_x86_64.deb): Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found [file] => /var/www/html/admin/modules/sangomaconnect/hooks/install-proxy-client [line] => 275 )
```

**Comment by LightningManGTS** [comment]
an updated version17.0.1.24 came out that did not resolve this issue.

**Comment by LightningManGTS** [comment]
pretty sure I found the problem 

`root@THD-FreePBX-17:~# apt search service-proxy-client

Sorting... Done

Full Text Search... Done

service-proxy-client/bookworm,now 1.2.3-0.sng12 amd64 [installed]

 Reverse tunnelling https and websocket proxy client`

If the module was looking for 1.2.3-0 instead of 1.2.3-1 it would probably finish the cloud connect install.

**Comment by ramarajan222** [comment]
We have fixed it at our side and now the proxy client is installed on your system.

` dpkg -l | grep service-proxy-client
ii  service-proxy-client                             1.2.3-1                                                                    amd64        Reverse tunnelling https and websocket proxy client`


Moving to close, reopen if needed. thanks.
