### ISSUE TITLE
Whoops error when editing a trunk after restore to Freepbx 17: 

### ISSUE THREAD

**Issue by Andsup** [FreePBX/issue-tracker#82]
### FreePBX Version

FreePBX 17

### Issue Description

Atfer a config restore from version 16.0.40.7 to 17.0.15.13

Error during PJSIP trunk edition :

Whoops \ Exception \ ErrorException (E_WARNING)
Undefined variable $mtfenable

Stacktrace:
#5 Whoops\Exception\ErrorException in /var/www/html/admin/modules/core/views/trunks/trunk_header.php:62
#4 Whoops\Run:handleError in /var/www/html/admin/modules/core/views/trunks/trunk_header.php:62
#3 include in /var/www/html/admin/libraries/view.functions.php:151
#2 load_view in /var/www/html/admin/libraries/view.functions.php:181
#1 show_view in /var/www/html/admin/modules/core/page.trunks.php:531
#0 include in /var/www/html/admin/config.php:658

### Operating Environment

fresh debian 12 install
FreePBX 17.0.15.13
edge modules
fwconsole ma upgradeall  : done
fwconsole restart : done

**Comment by jissphilip** [comment]
core version 17.0.9.35

**Comment by Andsup** [comment]
Confirmed.

Ok on my site.
Thanks.

**Comment by Andsup** [comment]
OK
