### ISSUE TITLE
File Store :  Whoops \ Exception \ ErrorException (E_WARNING) Undefined variable $enabled - 

### ISSUE THREAD

**Issue by Andsup** [FreePBX/issue-tracker#83]
### FreePBX Version

FreePBX 17

### Issue Description

after a restore from version 16.
File store -> local -> edit 

Whoops\Exception\ErrorException thrown with message "Undefined variable $enabled"

Stacktrace:
#7 Whoops\Exception\ErrorException in /var/www/html/admin/modules/filestore/drivers/Local/views/form.php:38
#6 Whoops\Run:handleError in /var/www/html/admin/modules/filestore/drivers/Local/views/form.php:38
#5 include in /var/www/html/admin/libraries/view.functions.php:151
#4 load_view in /var/www/html/admin/modules/filestore/drivers/DriverBase.php:77
#3 FreePBX\modules\Filestore\drivers\DriverBase:getDisplay in /var/www/html/admin/modules/filestore/Filestore.class.php:86
#2 FreePBX\modules\Filestore:getDisplay in /var/www/html/admin/modules/filestore/Filestore.class.php:143
#1 FreePBX\modules\Filestore:showPage in /var/www/html/admin/modules/filestore/page.filestore.php:2
#0 include in /var/www/html/admin/config.php:658

### Operating Environment

after a restore from version 16.
File store - local - edit 

FreePBX 17.0.15.13 
Updated to the latest edge modules

**Comment by jissphilip** [comment]
filestore version 17.0.2.10

**Comment by Andsup** [comment]
Fix confirmed
Thanks
