### ISSUE TITLE
[bug]: Unable to Print Extensions

### ISSUE THREAD

**Issue by AndrewStock61** [FreePBX/issue-tracker#84]
### FreePBX Version

FreePBX 17

### Issue Description

Good Day All…

When trying to print a PDF of my extension list I am getting an error message.

{“error”:{“type”:“Exception”,“message”:“FPDF error: Image file name is empty”,“file”:“/var/www/html/admin/modules/printextensions/vendor/setasign/fpdf/fpdf.php”,“line”:271}}

Is the FPDF php not installed when the system is installed? If not, how do I go about installing the fpdf.php program so I can print extensions so that I can provide it to my users.

Thanks in advance for any help anyone can provide me.

Andrew Stock

### Operating Environment

Debian 11

IncrediblePBX2027

Printing Extensions to a PDF.

**Comment by kapilgupta01** [comment]
please try with printextension v17.0.1.2

**Comment by karafen** [comment]
> please try with printextension v17.0.1.2

similar problem but with version 17.0.1.2

error:
{"error":{"type":"Whoops\\Exception\\ErrorException","message":"iconv(): Detected an illegal character in input string","code":8,"file":"\/var\/www\/html\/admin\/modules\/printextensions\/PDF.php","line":222}}

part of string in php:
	function fix_utf8($txt) {
		$txt = iconv('UTF-8', 'ISO-8859-1',  $txt);
		return $txt;
	}

**Comment by BundasTm** [comment]
Becouse the "Image: Footer" is empty in Advanced Settings.
