### ISSUE TITLE
[improvement]: Tailscale support for secure remote access

### ISSUE THREAD

**Issue by JackPala** [FreePBX/issue-tracker#85]
### FreePBX Version

FreePBX 16

### Improvement Description

The tailscale installer doesn't work out of box with FreePBX, because of a lack of dnf. Some type of official Tailscale support would be great for distributed teams because the VPN and PBX could be self contained in a single instance.

Trying to make it work unofficially right now from source. But official support would be really, really nice. Happy to write code to help

**Comment by kapilgupta01** [comment]
Hey @JackPala 

Thanks for your suggestion!

We're marking your suggestion as 'Patches Welcome'. This means that we're not, presently, going to be investigating the implementation of your suggestion, but we also agree that it has merit.

If you would like to implement this yourself, I suggest you start by having a read through the Developer Corner wiki page.

https://sangomakb.atlassian.net/wiki/spaces/FP/pages/10289341/Developer+Corner+Home#Getting-Involved

Thanks again for your time!

Regards,
Kapil Gupta
