### ISSUE TITLE
Intrusion Detection  : make it compatible with other running firewall service like filewalld, ufw

### ISSUE THREAD

**Issue by Andsup** [FreePBX/issue-tracker#86]
### FreePBX Version

FreePBX 17

### Improvement Description

Intrusion Detection  : make compatible with other firewall service like filewalld, ufw
Expected with the new way to deploy Freepbx on existing Debian server

During a iptables service (re)start, build the possibility to (re)start the installed and running firewall

Maybe just adding an extra zone with the system command to be run
or check before the action and restart if needed 

Thanks

**Comment by kapilgupta01** [comment]
Hey @Andsup 

Thanks for your suggestion! 

We're marking your suggestion as 'Patches Welcome'. This means that we're not, presently, going to be investigating the implementation of your suggestion, but we also agree that it has merit.

If you would like to implement this yourself, I suggest you start by having a read through the Developer Corner wiki page.

https://sangomakb.atlassian.net/wiki/spaces/FP/pages/10289341/Developer+Corner+Home#Getting-Involved

Thanks again for your time!

Regards,
Kapil Gupta
