### ISSUE TITLE
[improvement]: OpenLDAP2/PJSIP support of secure (realmed) passwords

### ISSUE THREAD

**Issue by atis** [FreePBX/issue-tracker#87]
### FreePBX Version

FreePBX 16

### Improvement Description

Asterisk supports realmed passwords, which are way more secure than plaintext passwords stored on server.
FreePBX with OpenLDAP2 is lacking this.

I have fixed this by importing _AstAccountRealmedPassword_ field, and writing it to PJSIP config as _md5_cred_ value.

This requires small changes in core/PJSIP and userman/OpenLDAP2

**Comment by blazestudios97** [comment]
What small changes are required?

**Comment by atis** [comment]
Created two pull requests:

https://github.com/FreePBX/userman/pull/29

https://github.com/FreePBX/core/pull/62

**Comment by LightningManGTS** [comment]
Is there anyway to review your changes and see if they're forward compatible with freepbx 17?

**Comment by atis** [comment]
A quick look, shows that it can't be automatically merged, as the web config editor in FPBX17 got squeezed into one long line, but it should be trivial to change. Other than that, I don't see any issues

**Comment by kapilgupta01** [comment]
core v17.0.9.36
userman v17.0.6.18
