### ISSUE TITLE
[improvement]: update Userman LDAP sync to automatically remove groups no longer in the sync scope

### ISSUE THREAD

**Issue by LightningManGTS** [FreePBX/issue-tracker#89]
### FreePBX Version

FreePBX 17

### Improvement Description

Changing the Group DN scope does not automatically remove the already sync'd entries that fall out of the new scope. this should be fixed as currently there is no way to delete read only items without deleting the directory sync and starting over.

**Comment by girishmani1992** [comment]
Hi @LightningManGTS ,

I have tried with latest version(17.0.6.20) of userman and groups which are not in sync scope are being deleted automatically. Please try with latest version of userman,


Thanks
