### ISSUE TITLE
[improvement]: Play a message before Voicemail Name Greeting (Toggleable)

### ISSUE THREAD

**Issue by qlong123** [FreePBX/issue-tracker#9]
### Improvement Description

Hi, I have an Idea to add a message that plays before the user's name greeting, this recording can be enabled and disabled with a toggle switch located on Voicemail settings for the user in FreePBX Admin.

Thanks

**Comment by blazestudios97** [comment]
Can you provide some more details into how this should work? Expectations, etc?

**Comment by blazestudios97** [comment]
Where's the PR/code for this if it is completed?

**Comment by kapilgupta01** [comment]
nope thats not complete, closed due to no response of understanding real requirement of this issue.

**Comment by blazestudios97** [comment]
Isn't there another status to indicate a "No Fix" or other outside of completed?

**Comment by jcolp** [comment]
There's close as not planned, that's the other option, which I just did.
