### ISSUE TITLE
[bug]: unknown encoder 'libfdk_aac'

### ISSUE THREAD

**Issue by SergYuh** [FreePBX/issue-tracker#90]
### FreePBX Version

FreePBX 17

### Issue Description

recordings cannot be played through the browser. ffmpeg error Unknown encoder 'libfdk_aac'

### Operating Environment

FreePBX 17.0.15.13
Asterisk 20.4.0

**Comment by kapilgupta01** [comment]
Hi @SergYuh Are you trying this on chrome browser ? 

Also paste the output of below command as this package should get download from our repo not from the debian default repo. 

`root@debian-pbx:~# apt policy ffmpeg
ffmpeg:
  Installed: 5.1.4-7.sng12
  Candidate: 5.1.4-8.sng12
  Version table:
     7:5.1.4-0+deb12u1 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        500 http://security.debian.org/debian-security bookworm-security/main amd64 Packages
     5.1.4-8.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
 *** 5.1.4-7.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
     5.1.4-6.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-5.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-3.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
`

**Comment by SergYuh** [comment]
I use yandex.browser, and there were no problems with this in freepbx 16. there is no error in Chrome, thank you

**Comment by SergYuh** [comment]
apt policy ffmpeg
ffmpeg:
  Установлен: 5.1.4-8.sng12
  Кандидат:   5.1.4-8.sng12
  Таблица версий:
     7:5.1.4-0+deb12u1 500
        500 http://ftp.ru.debian.org/debian bookworm/main amd64 Packages
        500 http://ftp.ru.debian.org/debian-security bookworm-security/main amd64 Packages
        500 http://ftp.ru.debian.org/debian-security bookworm-security/updates/main amd64 Packages
 *** 5.1.4-8.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
     5.1.4-7.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-6.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-5.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages
     5.1.4-3.sng12 600
        600 http://deb.freepbx.org/freepbx17-prod bookworm/main amd64 Packages

**Comment by kapilgupta01** [comment]
okay yes, thats known issue somehow chrome works fine but not other browsers.

**Comment by SergYuh** [comment]
hi. additional information.
if you edit the file
/var/www/html/admin/libraries/media/Media/Driver/Drivers/FfmpegShell.php
line 141
--acodec libfdk_aac > -acodec aac
then after that, playback works in any browser

**Comment by kapilgupta01** [comment]
thank you @SergYuh , pushed the changes to the latest framework, please give a try.
Framework v17.0.15.14
