### ISSUE TITLE
[new-feature]: Extension PJSIP NAT Support

### ISSUE THREAD

**Issue by anhackers44** [FreePBX/issue-tracker#91]
### FreePBX Version

FreePBX 17

### Feature Description

*Add a new field on the PJSIP Extension Advanced tab called "Endpoint Media Address"
* If this field is populated, write in pjsip.endpoint.conf a corresponding line for the pjsip endpoint "media_address=xx.xx.xx.xx"
* if this field is not populated, do not write this line

This is already supported for pjsip trunks, extending same feature to pjsip extensions.

**Comment by danardf** [comment]
@anhackers44 Ok I will try to work on it for 16 at least and next @kguptasangoma could merge on 17 too. (I guess)

**Comment by danardf** [comment]
@kguptasangoma 
Hi.
PR raised https://github.com/FreePBX/core/pull/119

You can also push it on 17.
This will solve all NAT issues with PJSIP extensions

**Comment by danardf** [comment]
It's merged on 16, Just wait for 17 I guess.

**Comment by danardf** [comment]
@kguptasangoma Once merged on 17, you can close this issue sure.

**Comment by jissphilip** [comment]
core version 17.0.16 
 core version 16.0.68.30

**Comment by danardf** [comment]
@jissphilip Thank you so much
