### ISSUE TITLE
[bug]: Asterisk manager users - permit/deny multiple ip ranges and ampersand char

### ISSUE THREAD

**Issue by ctrlaltca** [FreePBX/issue-tracker#96]
### FreePBX Version

FreePBX 17

### Issue Description

When adding a new manager in /admin/config.php?display=manager it's possible to specify deny/permit range of IPs.
The help says "If you want to deny many hosts or networks, use & char as separator. Example: 192.168.1.0/255.255.255.0&10.0.0.0/255.0.0.0"
When i insert the example string "192.168.1.0/255.255.255.0&10.0.0.0/255.0.0.0" in one of the fields:

- the main table shows the value correctly
![immagine](https://github.com/FreePBX/issue-tracker/assets/1631111/d53c0ef2-551c-4cda-b6da-c42ee172f3c4)

-  closing and reopening the detail popup shows the urlencoded value:
![immagine](https://github.com/FreePBX/issue-tracker/assets/1631111/9c43071e-0db4-4560-9bfb-29fe347d2fe0)

- when applying the config, the resulting file contains an error:
```
[test]
secret=test
deny=192.168.1.0/255.255.255.0
deny=amp;10.0.0.0/255.0.0.0
...
```

### Operating Environment

Debian 12.5
PBX Version: 17.0.15.13
PBX Distro: 12.7.8-2402-3.sng12
Asterisk Version: 21.0.2

**Comment by jissphilip** [comment]
The reported issue has been fixed on the latest manager version 17.0.5. Upgrade the manager module to 17.0.5 and give it a try . thanks.

**Comment by ctrlaltca** [comment]
I can't see the update yet, version is still 17.0.4. I'll wait a couple of days and test

**Comment by ctrlaltca** [comment]
Just got the updated module, i can confirm everything is working as expected now. Thank you.
