### ISSUE TITLE
[bug]: Sysadmin Pro support keys and support vpn non-functional

### ISSUE THREAD

**Issue by LightningManGTS** [FreePBX/issue-tracker#97]
### FreePBX Version

FreePBX 17

### Issue Description

When trying to install the support ssh key or the start the support VPN both fail to do anything as they likely still need to be refactored for Debian with deb packages (and potentially some PHP stuff)

### Operating Environment

Proxmox LXC (unprivilaged) Debian 12, Freepbx 17 Asterisk 21

+-------------------+------------+-----------------------------------+-------------+-----------+
| Module            | Version    | Status                            | License     | Signature |
+-------------------+------------+-----------------------------------+-------------+-----------+
| amd               | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| announcement      | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| areminder         | 17.0.3.9   | Enabled                           | Commercial  | Sangoma   |
| arimanager        | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| asterisk-cli      | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| asteriskinfo      | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| backup            | 17.0.5.14  | Enabled                           | GPLv3+      | Sangoma   |
| blacklist         | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| broadcast         | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| builtin           |            | Enabled                           |             | Unsigned  |
| bulkhandler       | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| calendar          | 17.0.4.6   | Enabled                           | GPLv3+      | Sangoma   |
| callaccounting    | 17.0.4     | Enabled                           | Commercial+ | Sangoma   |
| callback          | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| callerid          | 17.0.1     | Enabled                           | Commercial  | Sangoma   |
| callforward       | 17.0.1.3   | Enabled                           | AGPLv3+     | Sangoma   |
| calllimit         | 17.0.1.2   | Enabled                           | Commercial  | Sangoma   |
| callrecording     | 17.0.3.6   | Enabled                           | AGPLv3+     | Sangoma   |
| callwaiting       | 17.0.3.2   | Enabled                           | GPLv3+      | Sangoma   |
| cdr               | 17.0.4.13  | Enabled                           | GPLv3+      | Sangoma   |
| cel               | 17.0.2.7   | Enabled                           | GPLv3+      | Sangoma   |
| certman           | 17.0.3.8   | Enabled                           | AGPLv3+     | Sangoma   |
| cidlookup         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| conferences       | 17.0.3.1   | Enabled                           | GPLv3+      | Sangoma   |
| conferencespro    | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| configedit        | 17.0.1.1   | Enabled                           | AGPLv3+     | Sangoma   |
| contactmanager    | 17.0.5.7   | Enabled                           | GPLv3+      | Sangoma   |
| core              | 17.0.9.37  | Enabled                           | GPLv3+      | Sangoma   |
| cos               | 17.0.1.1   | Enabled                           | Commercial  | Sangoma   |
| customappsreg     | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| dashboard         | 17.0.4.2   | Enabled                           | AGPLv3+     | Sangoma   |
| daynight          | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| dictate           | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| directory         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| donotdisturb      | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| endpoint          | 17.0.1.54  | Enabled                           | Commercial  | Sangoma   |
| extensionroutes   | 17.0.1     | Enabled                           | Commercial  | Sangoma   |
| extensionsettings | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| fax               | 17.0.3.2   | Enabled                           | GPLv3+      | Sangoma   |
| faxpro            | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| featurecodeadmin  | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| filestore         | 17.0.2.10  | Enabled                           | AGPLv3      | Sangoma   |
| findmefollow      | 17.0.4.6   | Enabled                           | GPLv3+      | Sangoma   |
| firewall          | 17.0.1.14  | Enabled                           | AGPLv3+     | Sangoma   |
| framework         | 17.0.15.13 | Enabled                           | GPLv2+      | Sangoma   |
| hotelwakeup       | 17.0.1.5   | Enabled                           | GPLv2       | Sangoma   |
| iaxsettings       | 17.0.1     | Enabled                           | AGPLv3      | Sangoma   |
| infoservices      | 17.0.1     | Enabled                           | GPLv2+      | Sangoma   |
| ivr               | 17.0.5     | Enabled                           | GPLv3+      | Sangoma   |
| languages         | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| logfiles          | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| manager           | 17.0.4     | Enabled                           | GPLv2+      | Sangoma   |
| miscapps          | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| miscdests         | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| music             | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| oembranding       |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| paging            | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| pagingpro         | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| parking           | 17.0.2     | Enabled                           | GPLv3+      | Sangoma   |
| parkpro           | 17.0.1.4   | Enabled                           | Commercial  | Sangoma   |
| pbxmfa            | 17.0.2     | Enabled                           | Commercial+ | Sangoma   |
| pinsets           | 17.0.3     | Enabled                           | GPLv3+      | Sangoma   |
| pinsetspro        | 17.0.2     | Enabled                           | Commercial  | Sangoma   |
| pm2               | 17.0.3.1   | Enabled                           | AGPLv3+     | Sangoma   |
| presencestate     | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
| printextensions   | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| queueprio         | 17.0.1.4   | Enabled                           | GPLv3+      | Sangoma   |
| queues            | 17.0.1.7   | Enabled                           | GPLv2+      | Sangoma   |
| queuestats        | 17.0.1.6   | Enabled                           | Commercial  | Sangoma   |
| qxact_reports     | 17.0.2     | Enabled                           | Commercial  | Sangoma   |
| recording_report  | 17.0.3.8   | Enabled                           | Commercial  | Sangoma   |
| recordings        | 17.0.2.2   | Enabled                           | GPLv3+      | Sangoma   |
| restapps          | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| ringgroups        | 17.0.2.4   | Enabled                           | GPLv3+      | Sangoma   |
| sangomaconnect    | 17.0.1.24  | Enabled                           | Commercial  | Sangoma   |
| sangomartapi      | 17.0.1.17  | Enabled                           | Commercial  | Sangoma   |
| setcid            | 17.0.1.2   | Enabled                           | GPLv3+      | Sangoma   |
| sipsettings       | 17.0.6.3   | Enabled                           | AGPLv3+     | Sangoma   |
| sipstation        | 17.0.3.3   | Enabled                           | Commercial  | Sangoma   |
| sms               | 17.0.1.9   | Enabled                           | Commercial  | Sangoma   |
| smsconnector      | 16.0.16.1  | Enabled                           | GPLv3+      | Unknown   |
| smsplus           | 17.0.3     | Enabled                           | Commercial  | Sangoma   |
| soundlang         | 17.0.4     | Enabled                           | GPLv3+      | Sangoma   |
| sysadmin          | 17.0.1.54  | Enabled                           | Commercial  | Sangoma   |
| timeconditions    | 17.0.1.13  | Enabled                           | GPLv3+      | Sangoma   |
| tts               | 17.0.1.1   | Enabled                           | GPLv3+      | Sangoma   |
| ttsengines        | 17.0.1     | Enabled                           | AGPLv3      | Sangoma   |
| ucp               | 17.0.4.14  | Enabled                           | AGPLv3+     | Sangoma   |
| userman           | 17.0.6.18  | Enabled                           | AGPLv3+     | Sangoma   |
| vmblast           | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| vmnotify          | 17.0.1.5   | Enabled                           | Commercial  | Sangoma   |
| voicemail         | 17.0.5.14  | Enabled                           | GPLv3+      | Sangoma   |
| voicemail_report  |            | Not Installed (Locally available) | Commercial  | Sangoma   |
| vqplus            | 17.0.1.14  | Enabled                           | Commercial  | Sangoma   |
| weakpasswords     | 17.0.1     | Enabled                           | GPLv3+      | Sangoma   |
| webrtc            | 17.0.2.1   | Enabled                           | GPLv3+      | Sangoma   |
+-------------------+------------+-----------------------------------+-------------+-----------+

### Relevant log output

```shell
cat syslog | grep ssh

2024-04-15T13:54:11.954472+00:00 THD-FreePBX-17 incrond[120]: PATH (/var/spool/asterisk/incron) FILE (sysadmin.toggle-sshkeys-rpm) EVENT (IN_CLOSE_WRITE)
2024-04-15T13:54:11.954575+00:00 THD-FreePBX-17 incrond[120]: (system::sysadmin) CMD (/usr/bin/sysadmin_manager sysadmin.toggle-sshkeys-rpm)
2024-04-15T13:54:12.001541+00:00 THD-FreePBX-17 sysadmin-hook[1158625]: sysadmin hook started - ["\/usr\/bin\/sysadmin_manager","sysadmin.toggle-sshkeys-rpm"]
2024-04-15T13:54:12.016370+00:00 THD-FreePBX-17 sysadmin-hook[1158625]: Security check passed. Running '/var/www/html/admin/modules/sysadmin/hooks/toggle-sshkeys-rpm '

cat syslog | grep support-vpn

2024-04-16T13:09:36.194416+00:00 THD-FreePBX-17 incrond[120]: PATH (/var/spool/asterisk/incron) FILE (sysadmin.support-vpn-start) EVENT (IN_MODIFY)
2024-04-16T13:09:36.194650+00:00 THD-FreePBX-17 incrond[120]: (system::sysadmin) CMD (/usr/bin/sysadmin_manager sysadmin.support-vpn-start)
2024-04-16T13:09:36.194682+00:00 THD-FreePBX-17 incrond[120]: PATH (/var/spool/asterisk/incron) FILE (sysadmin.support-vpn-start) EVENT (IN_CLOSE_WRITE)
2024-04-16T13:09:36.194713+00:00 THD-FreePBX-17 incrond[120]: (system::sysadmin) CMD (/usr/bin/sysadmin_manager sysadmin.support-vpn-start)
2024-04-16T13:09:36.232406+00:00 THD-FreePBX-17 sysadmin-hook[1401821]: sysadmin hook started - ["\/usr\/bin\/sysadmin_manager","sysadmin.support-vpn-start"]
2024-04-16T13:09:36.232723+00:00 THD-FreePBX-17 sysadmin-hook[1401820]: sysadmin hook started - ["\/usr\/bin\/sysadmin_manager","sysadmin.support-vpn-start"]
2024-04-16T13:09:36.243617+00:00 THD-FreePBX-17 sysadmin-hook[1401820]: Security check passed. Running '/var/www/html/admin/modules/sysadmin/hooks/support-vpn-start '
2024-04-16T13:09:36.244536+00:00 THD-FreePBX-17 sysadmin-hook[1401821]: Security check passed. Running '/var/www/html/admin/modules/sysadmin/hooks/support-vpn-start '
2024-04-16T13:11:09.055483+00:00 THD-FreePBX-17 incrond[120]: PATH (/var/spool/asterisk/incron) FILE (sysadmin.support-vpn-start) EVENT (IN_MODIFY)
2024-04-16T13:11:09.055596+00:00 THD-FreePBX-17 incrond[120]: (system::sysadmin) CMD (/usr/bin/sysadmin_manager sysadmin.support-vpn-start)
2024-04-16T13:11:09.055628+00:00 THD-FreePBX-17 incrond[120]: PATH (/var/spool/asterisk/incron) FILE (sysadmin.support-vpn-start) EVENT (IN_MODIFY)
2024-04-16T13:11:09.056105+00:00 THD-FreePBX-17 incrond[120]: (system::sysadmin) CMD (/usr/bin/sysadmin_manager sysadmin.support-vpn-start)
2024-04-16T13:11:09.056142+00:00 THD-FreePBX-17 incrond[120]: PATH (/var/spool/asterisk/incron) FILE (sysadmin.support-vpn-start) EVENT (IN_CLOSE_WRITE)
2024-04-16T13:11:09.056170+00:00 THD-FreePBX-17 incrond[120]: (system::sysadmin) CMD (/usr/bin/sysadmin_manager sysadmin.support-vpn-start)
2024-04-16T13:11:09.093672+00:00 THD-FreePBX-17 sysadmin-hook[1402819]: sysadmin hook started - ["\/usr\/bin\/sysadmin_manager","sysadmin.support-vpn-start"]
2024-04-16T13:11:09.093925+00:00 THD-FreePBX-17 sysadmin-hook[1402817]: sysadmin hook started - ["\/usr\/bin\/sysadmin_manager","sysadmin.support-vpn-start"]
2024-04-16T13:11:09.094137+00:00 THD-FreePBX-17 sysadmin-hook[1402818]: sysadmin hook started - ["\/usr\/bin\/sysadmin_manager","sysadmin.support-vpn-start"]
2024-04-16T13:11:09.094228+00:00 THD-FreePBX-17 sysadmin-hook[1402819]: File '/var/spool/asterisk/incron/sysadmin.support-vpn-start' didn't exist. That's unpossible (Are you running incron commands manually?)
2024-04-16T13:11:09.104946+00:00 THD-FreePBX-17 sysadmin-hook[1402818]: Security check passed. Running '/var/www/html/admin/modules/sysadmin/hooks/support-vpn-start '
2024-04-16T13:11:09.105075+00:00 THD-FreePBX-17 sysadmin-hook[1402817]: Security check passed. Running '/var/www/html/admin/modules/sysadmin/hooks/support-vpn-start '
2024-04-16T13:11:09.108479+00:00 THD-FreePBX-17 sysadmin-hook[1402819]: Security check passed. Running '/var/www/html/admin/modules/sysadmin/hooks/support-vpn-start '
```

**Comment by ramarajan222** [comment]
Hi @LightningManGTS 

SSH Keys
You can check the ssh keys package is installed or not by using the below command.
` dpkg -l | grep ssh-keys`

This package will add the SSH keys to your system.

Support VPN:-
The Support VPN will start only if your license file has the backup login details and VPN ip , If you don't see these details on your license files then you need to enable it on the portal.

`cat /etc/sangoma/license.txt | grep "backup_\|vpn"
backup_password = XXXXXXXXXXXXXX
backup_username = yyyyyyyyyyyyyyy
vpn_ip = XXX.yyy.zzz.XXX
` 

Let us know if you have any further queries on this. 
thanks

**Comment by LightningManGTS** [comment]
I checked for the ssh key package and it is there, you are correct. No idea why support wasn't able to get in. I created a support ticket related to the sangomaconnect issue and the guy wasn't able to ssh in with the keys he had.

Regarding the vpn, I'm not sure how I would go about generating that information. I tried enabling the normal vpn and then the support vpn to no effect. for some reason under clients clicking add gives and error that array key client is undefined.

**Comment by ramarajan222** [comment]
We have a known issue with sysadmin VPN  and we are working on it.

Currently, no pending issues with support VPN and it should work on your system if the license file has the required information.
VPN was not enabled for your deployment, and the support team enabled the VPN for your deployment so now you should able to connect to the support VPN. 

Please update the license before trying to connect the support VPN

run "fwconsole sa u" to update the license.

Thanks.

**Comment by LightningManGTS** [comment]
Totally fair, actually on that note, the container also needed access to /dev/net/tun which it did not previously.
