### ISSUE TITLE
[bug]: Intrusion Detection Banned IP cannot be deleted or Unbanned

### ISSUE THREAD

**Issue by Matthew-Rauch** [FreePBX/issue-tracker#99]
### FreePBX Version

FreePBX 17

### Issue Description

I entered the Admin password incorrectly too many times so my IP was added to the Intrusion Detection Banned list.  When I accessed the page from another computer and try to delete the banned IP it clears for a second, refreshes, and is back.  Clicking the Unban All button does the same thing.  The IP can be added to the whitelist with that button, but it doesn't remove from the banned list, which overrides the whitelist.  The IP can be deleted from the whitelist.

### Operating Environment

System Firewall 17.0.1.14

**Comment by Matthew-Rauch** [comment]
I was able to remove the ip using the cli: fail2ban-client set pbx-gui unbanip a.b.c.d

**Comment by Andsup** [comment]
Same issue here.
And more : 
- I need to disable "Intrusion Detection" to avoid a freeze during the reboot
- NB : after reboot "Intrusion Detection" is again enable without action
- Some errors linked to faiL2ban and iptables (reported by logwatch) :
** ERRORS **
      7f384ef28990 -- exec: iptables -D INPUT -p all -j fail2ban-PBX-GUI: 1 Time(s)
      7f384ef28990 -- stderr: "Try `iptables -h' or 'iptables --help' for more in...: 1 Time(s)
      7f384ef28990 -- stderr: "iptables v1.8.9 (nf_tables): Chain 'fail2ban-PBX-G...: 1 Time(s)
      7f384ef28990 -- stderr: 'iptables: No chain/target/match by that name.': 2 Time(s)
      7f384efff870 -- exec: iptables -I fail2ban-apache-auth 1 -s 139.99.28.144 -...: 1 Time(s)
      7f384efff870 -- stderr: 'iptables: No chain/target/match by that name.': 1 Time(s)
      7f384f52a6b0 -- exec: iptables -D INPUT -p tcp -m multiport --dports ssh -j...: 3 Time(s)
      7f384f52a6b0 -- stderr: "Try `iptables -h' or 'iptables --help' for more in...: 3 Time(s)
      7f384f52a6b0 -- stderr: "iptables v1.8.9 (nf_tables): Chain 'fail2ban-SSH' ...: 3 Time(s)
      7f384f52a6b0 -- stderr: 'iptables: No chain/target/match by that name.': 6 Time(s)
      7f384f52a810 -- exec: iptables -D INPUT -p all -j fail2ban-apache-auth: 1 Time(s)
      7f384f52a810 -- stderr: "Try `iptables -h' or 'iptables --help' for more in...: 1 Time(s)
      7f384f52a810 -- stderr: "iptables v1.8.9 (nf_tables): Chain 'fail2ban-apach...: 1 Time(s)
      7f384f52a810 -- stderr: 'iptables: No chain/target/match by that name.': 2 Time(s)
      7f384f57edb0 -- exec: iptables -n -L INPUT | grep -q 'fail2ban-PBX-GUI[ \t]': 1 Time(s)
      7f384f57f0c0 -- exec: iptables -n -L INPUT | grep -q 'fail2ban-SSH[ \t]': 5 Time(s)
      7f384f57f210 -- exec: iptables -n -L INPUT | grep -q 'fail2ban-apache-auth[...: 2 Time(s)
      7f384f5b1b30 -- exec: iptables -I fail2ban-SSH 1 -s 80.80.219.117 -j REJECT...: 1 Time(s)
      7f384f5b1b30 -- stderr: 'iptables: No chain/target/match by that name.': 1 Time(s)
      7fc424328990 -- exec: iptables -D INPUT -p all -j fail2ban-PBX-GUI: 2 Time(s)
      7fc424328990 -- stderr: "Try `iptables -h' or 'iptables --help' for more in...: 2 Time(s)
      7fc424328990 -- stderr: "iptables v1.8.9 (nf_tables): Chain 'fail2ban-PBX-G...: 2 Time(s)
      7fc424328990 -- stderr: 'iptables: No chain/target/match by that name.': 4 Time(s)
      7fc424328b70 -- exec: iptables -D INPUT -p all -j fail2ban-recidive: 1 Time(s)
      7fc424328b70 -- stderr: "Try `iptables -h' or 'iptables --help' for more in...: 1 Time(s)
      7fc424328b70 -- stderr: "iptables v1.8.9 (nf_tables): Chain 'fail2ban-recid...: 1 Time(s)
      7fc424328b70 -- stderr: 'iptables: No chain/target/match by that name.': 2 Time(s)
      7fc4243f9d90 -- exec: iptables -I fail2ban-apache-auth 1 -s 149.129.147.213...: 1 Time(s)
      7fc4243f9d90 -- stderr: 'iptables: No chain/target/match by that name.': 1 Time(s)
      7fc4243fbaf0 -- exec: iptables -I fail2ban-apache-auth 1 -s 170.64.195.65 -...: 1 Time(s)
      7fc4243fbaf0 -- stderr: 'iptables: No chain/target/match by that name.': 1 Time(s)
      7fc4243fbc30 -- exec: iptables -I fail2ban-apache-auth 1 -s 104.248.254.95 ...: 1 Time(s)
      7fc4243fbc30 -- stderr: 'iptables: No chain/target/match by that name.': 1 Time(s)
      7fc4249377b0 -- exec: iptables -D INPUT -p tcp -m multiport --dports http,h...: 1 Time(s)
      7fc4249377b0 -- stderr: "Try `iptables -h' or 'iptables --help' for more in...: 1 Time(s)
      7fc4249377b0 -- stderr: "iptables v1.8.9 (nf_tables): Chain 'fail2ban-BadBo...: 1 Time(s)
      7fc4249377b0 -- stderr: 'iptables: No chain/target/match by that name.': 2 Time(s)
      7fc4249379f0 -- exec: iptables -D INPUT -p udp -m multiport --dports 1194 -...: 1 Time(s)
      7fc4249379f0 -- stderr: "Try `iptables -h' or 'iptables --help' for more in...: 1 Time(s)
      7fc4249379f0 -- stderr: "iptables v1.8.9 (nf_tables): Chain 'fail2ban-openv...: 1 Time(s)
      7fc4249379f0 -- stderr: 'iptables: No chain/target/match by that name.': 2 Time(s)
      7fc424952080 -- exec: iptables -D INPUT -p tcp -m multiport --dports ssh -j...: 1 Time(s)

      Failed to execute ban jail 'apache-tcpwrapper' action 'iptables-allports-ap...: 5 Time(s)
      Failed to execute ban jail 'pbx-gui' action 'iptables-allports-PBX-GUI' inf...: 1 Time(s)
      Failed to execute ban jail 'ssh-iptables' action 'iptables-multiport-SSH' i...: 1 Time(s)
      Failed to stop jail 'apache-api' action 'iptables-multiport-api': Error sto...: 1 Time(s)
      Failed to stop jail 'apache-badbots' action 'iptables-multiport-BadBots': E...: 1 Time(s)
      Failed to stop jail 'apache-tcpwrapper' action 'iptables-allports-apache-au...: 1 Time(s)
      Failed to stop jail 'asterisk-iptables' action 'iptables-allports-SIP': Err...: 1 Time(s)
      Failed to stop jail 'openvpn' action 'iptables-multiport': Error stopping a...: 1 Time(s)
      Failed to stop jail 'recidive' action 'iptables-allports': Error stopping a...: 1 Time(s)
      Failed to stop jail 'sshd' action 'iptables-multiport': Error stopping acti...: 1 Time(s)
      Failed to stop jail 'vsftpd-iptables' action 'iptables-multiport-FTP': Erro...: 1 Time(s)

    2024-04-17 04:09:49,614 fail2ban.CommandAction  [31522]: CRITICAL Unable to restore environment: 1 Time(s)
    2024-04-17 04:52:46,129 fail2ban.CommandAction  [31522]: CRITICAL Unable to restore environment: 1 Time(s)
    2024-04-17 08:31:10,871 fail2ban.CommandAction  [31522]: CRITICAL Unable to restore environment: 1 Time(s)
    2024-04-17 08:45:53,665 fail2ban.CommandAction  [31522]: CRITICAL Unable to restore environment: 1 Time(s)
    2024-04-17 14:10:03,175 fail2ban.CommandAction  [31522]: CRITICAL Unable to restore environment: 1 Time(s)
    2024-04-17 18:13:33,984 fail2ban.CommandAction  [31522]: CRITICAL Unable to restore environment: 1 Time(s)
    2024-04-17 22:14:32,245 fail2ban.CommandAction  [448275]: CRITICAL Unable to restore environment: 1 Time(s)
    2024-04-17 22:46:07,391 fail2ban.CommandAction  [448275]: CRITICAL Unable to restore environment: 1 Time(s)
    2024-04-17 22:46:11,410 fail2ban.CommandAction  [448275]: CRITICAL Unable to restore environment: 1 Time(s)

**Comment by kapilgupta01** [comment]
Thanks for reporting this issue, we are working on it. thanks.

**Comment by kapilgupta01** [comment]
firewall v17.0.1.16

**Comment by kapilgupta01** [comment]
Hi @Andsup Please give a try with the latest edge release ? also request you to update all the modules to the edge to ensure that you have up to date updated system. thanks

**Comment by Andsup** [comment]
Fixed.

Just run:
    fwconsole ma upgradeall
    firewall ==> 17.0.1.16
    sysadmin ==> 17.0.1.57
    fwconsole restart

FreePBX 17.0.15.14

one IP unbanned and "unban all" is ok  now.

**Comment by kapilgupta01** [comment]
thanks for the update @Andsup
